Add autofocus support
woocommerce/woocommerce pull request #11906
Opened 2016-09-12 19:34 UTC by corsonr

Add autofocus support to the WC fields.

2016-09-15 19:29 UTC, mikejolley commented on includes/wc-template-functions.php
> +		$args['autofocus'] = ( true == esc_attr( $args['autofocus'] ) ) ? apply_filters( 'woocommerce_form_field_autofocus', ' autofocus' ) : '' ;
esc_attr should not be used for comparison because it is used for sanitizing output.

2016-09-15 19:29 UTC, mikejolley commented on includes/wc-template-functions.php
> +		$args['autofocus'] = ( true == esc_attr( $args['autofocus'] ) ) ? apply_filters( 'woocommerce_form_field_autofocus', ' autofocus' ) : '' ;
True should also be a literal comparison (`===`).

2016-09-15 19:29 UTC, mikejolley commented on includes/wc-template-functions.php
> +		$args['autofocus'] = ( true == esc_attr( $args['autofocus'] ) ) ? apply_filters( 'woocommerce_form_field_autofocus', ' autofocus' ) : '' ;
There is an extra space before `' autofocus'`

2016-09-15 19:30 UTC, mikejolley commented on includes/wc-template-functions.php
> +				$field .= '<input type="' . esc_attr( $args['type'] ) . '" class="input-text ' . esc_attr( implode( ' ', $args['input_class'] ) ) . '" name="' . esc_attr( $key ) . '" id="' . esc_attr( $args['id'
This needs an escape.

2016-09-15 19:31 UTC, mikejolley requested changes
Just needs a few fixes before merge.

2016-09-16 01:48 UTC, corsonr commented on includes/wc-template-functions.php
> +		$args['autofocus'] = ( true == esc_attr( $args['autofocus'] ) ) ? apply_filters( 'woocommerce_form_field_autofocus', ' autofocus' ) : '' ;
Actually it was on purpose as it needs a space when added to a form tag, or should I add the space directly inside each form tag?

2016-09-16 01:57 UTC, claudiosanches approved these changes
Ok this one

2016-09-16 02:00 UTC, claudiosanches requested changes
It's ok, but should go with the `$custom_attributes`, since it's more easy and need less code to do it.

After `$custom_attributes = array();` you can add:

``` php
if ( true === $args['autofocus'] ) {
    $custom_attributes['autofocus'] = 'autofocus';
}
```

This make works with all fields and already escape all things.

2016-10-11 16:51 UTC, merged