Create new filter to custom log messages
woocommerce/woocommerce pull request #11927
Opened 2016-09-15 05:07 UTC by davefx

I've created a new filter for log messages, so I can add extra info to the log messages written by WooCommerce, its extensions or related plugins.

In my project, I'm using this to prepend a checksum to the message that associates every message with the request that created it.

2016-09-15 06:23 UTC, claudiosmweb commented
@mikejolley thoughts?

I just only don't like the filter name, we can change to:

```php
$message = apply_filters( 'woocommerce_logger_add_message', $message, $handle );
```

2016-09-15 09:05 UTC, davefx commented
OK. Filter name changed

2016-09-15 19:41 UTC, mikejolley commented on includes/class-wc-logger.php
> +		    $message = apply_filters('woocommerce_logger_add_message', $message, $handle);
Needs a space between the parenthesis.

2016-09-15 19:41 UTC, mikejolley requested changes

2016-09-15 19:44 UTC, davefx commented
Done

2016-09-15 19:45 UTC, davefx commented on includes/class-wc-logger.php
> +		    $message = apply_filters('woocommerce_logger_add_message', $message, $handle);
Done

2016-09-19 13:28 UTC, davefx commented on includes/class-wc-logger.php
> +		    $message = apply_filters('woocommerce_logger_add_message', $message, $handle);
Fixed in the pull request, @mikejolley

2016-10-05 19:39 UTC, merged