Product CRUD improvements
woocommerce/woocommerce pull request #12359
Opened 2016-11-15 17:53 UTC by mikejolley

This PR fixes the last todo items (that need to be taken care of in this branch, issues are logged for remaining) and makes all unit tests pass. I’ve also scanned for notices and whilst there may be more in testing, all I’ve seen are fixed.

This also closes #12326 which was a todo.

Once merged and @coderkevin completes ajax, we should be able to merge product-crud into master.

2016-11-15 20:03 UTC, emdashcodes requested changes
Just pointed out two things.
Could you also implement the new delete arguments in the product data store as part of these changes? I already made the change in WC_Data in master, but not in the products store.

2016-11-15 20:03 UTC, justinshreve commented on includes/api/class-wc-rest-products-controller.php
> +		// Update parent if grouped so price sorting works and stays in sync with the cheapest child. @todo
Isn't this todo complete by the sync code in grouped products? If so - we should remove the whole block

2016-11-15 20:03 UTC, justinshreve commented on includes/class-wc-comments.php
> +		update_post_meta( $product->get_id(), '_wc_average_rating', $average );
These three lines should use CRUD to update.

2016-11-15 23:25 UTC, coderkevin requested changes
In testing some other code, I ran into this in the log: `[15-Nov-2016 23:07:51 UTC] PHP Warning:  implode(): Invalid arguments passed in /srv/www/wordpress-default/wp-content/plugins/woocommerce/includes/wc-attribute-functions.php on line 42[15-Nov-2016 23:07:51 UTC] PHP Warning:  implode(): Invalid arguments passed in /srv/www/wordpress-default/wp-content/plugins/woocommerce/includes/wc-attribute-functions.php on line 42`

It should probably be addressed and fixed before we merge this.

2016-11-16 12:06 UTC, justinshreve commented
LGTM 👍

2016-11-16 12:17 UTC, merged