Order Item Data Store
woocommerce/woocommerce pull request #12403
Opened 2016-11-18 13:53 UTC by justinshreve

This PR implements data stores for all order item types. There is an abstract base class for order item stores, and then smaller stores that handle each specific set of data. This also updates the main data classes to use the new set_prop and get_prop methods.

#### Testing:

Unit Tests: All tests pass. `order/crud` tests have some line item tests specifically.

Cart/Ordering:
* Add a few different product types to your cart - enable things like shipping fees or taxes.
* Checkout and verify that info shows correctly on the order summary page (product name, cost, tax info, etc).

Admin:
* Verify that info shows correctly for the order line items in wp-admin.
* Add new fees, shipping costs, or products to the order. Save and verify everything works and displays correctly.

2016-11-18 20:50 UTC, mikejolley reviewed
Added a few items. Looks good overall - lets merge after the order data PR? Some things might clash (downloads).

2016-11-18 20:50 UTC, mikejolley commented on includes/class-wc-order-item-fee.php
> +		return $name ? $name : __( 'Fee', 'woocommerce' );
This should either be handled on read, or only when in view context?

2016-11-18 20:50 UTC, mikejolley commented on includes/class-wc-order-item-product.php
> +			$download_ids = $this->data_store->get_download_ids( $this, $order );
Might be a change after order data PR is in - I added a custom download data store.

2016-11-21 12:00 UTC, justinshreve commented
>  lets merge after the order data PR?

Sounds good -- I'll update the download IDs part once your PR is in.

2016-11-21 19:48 UTC, justinshreve commented
Finished remaining items, rebased, and re-tested.

2016-11-22 10:56 UTC, mikejolley requested changes
I think this is good to merge once the error log is removed :)

2016-11-22 10:56 UTC, mikejolley commented on includes/api/legacy/v3/class-wc-api-orders.php
> +		error_log( print_r ( $item, 1 ) );
Error log

2016-11-22 11:39 UTC, merged