AJAX Class and other fixes
woocommerce/woocommerce pull request #12465
Opened 2016-11-24 17:51 UTC by mikejolley

- Finishes up AJAX CRUD classes
- Fixes a bug with order item meta values
- Improves variation display in cart
- Removes attribute_ prefixes in variation class

2016-11-24 18:25 UTC, claudiosanches requested changes
Not a fan or products having "titles", not to mention that this forced you added a new method inside variations and introduced a new filter for it that doesn't exists in past versions...

We always used it inside the `WC_Product`:

```php
	public function get_title() {
		return apply_filters( 'woocommerce_product_title', $this->post ? $this->post->post_title : '', $this );
	}
```

So if someone is trying to change a variation title with this filter will not be possible anymore with this change now.
We are breaking backwards compatibility to keep a method that should be deprecated....

2016-11-24 18:25 UTC, claudiosanches commented on includes/data-stores/class-wc-product-variation-data-store-cpt.php
> +			'post_title'     => get_the_title( $product->get_parent_id() ) . ' &ndash;' . wc_get_formatted_variation( $product, true, false ),
Missing space here?

2016-11-24 18:25 UTC, claudiosanches commented on includes/abstracts/abstract-wc-legacy-product.php
> -	public function get_title() {
This should be deprecated, since products should have names and not titles.

2016-11-25 10:40 UTC, mikejolley commented
I'll fix up the hook name and add a comment. We kinda need the ability to get a parents title from a variation, so rather than introduce a new method I've jus kept the old one around. Discuss on slack with me later.

2016-11-25 10:44 UTC, merged