#12518 Make product attributes link through to archives
woocommerce/woocommerce pull request #12890
Opened 2017-01-18 23:15 UTC by claudiulodro

This relates to issue #12518. 

In the "Additional information" tab for products, link public attributes to their archive pages when possible.

2017-01-19 17:51 UTC, mikejolley requested changes

2017-01-19 17:51 UTC, mikejolley commented on templates/single-product/product-attributes.php
> +				if ( $attribute->is_taxonomy() ) :
In other templates, when we have a multi-line block of PHP, regardless of this being in a template file we've chosen to use bracket notation. Should probably use that here?

2017-01-19 17:51 UTC, mikejolley commented on templates/single-product/product-attributes.php
> +							$values[] = '<a href="' . esc_url( get_term_link( $attribute_value->term_id, $attribute->get_name() ) ) . '" rel="tag">' . $attribute_value->name . '</a>';
Should we escape name with esc_html or wp_kses?

2017-01-19 23:10 UTC, claudiulodro commented on templates/single-product/product-attributes.php
> +				if ( $attribute->is_taxonomy() ) :
Gotcha. Will do since that's how everyone else is doing it.

2017-01-19 23:18 UTC, claudiulodro commented on templates/single-product/product-attributes.php
> +							$values[] = '<a href="' . esc_url( get_term_link( $attribute_value->term_id, $attribute->get_name() ) ) . '" rel="tag">' . $attribute_value->name . '</a>';
Definitely. `esc_html` is the way to go, since attribute values aren't supposed to have links or other tags in their name.

2017-01-20 01:02 UTC, claudiulodro commented
@mikejolley, I have made the changes you requested.

2017-01-20 17:24 UTC, mikejolley commented
Looks good. @justinshreve @claudiosanches slip this into 2.7 or wait for 2.8?

2017-01-23 18:12 UTC, claudiosanches commented
@mikejolley it's a small improvement. So merging into 2.7.

2017-01-23 18:12 UTC, merged

2017-01-23 18:14 UTC, mikejolley commented
@claudiosanches readme!

2017-01-23 18:14 UTC, claudiosanches commented
@mikejolley doing it right now :)