Deprecate WC_Product::get_title() and update get_name() to pull from a variation's parent.
woocommerce/woocommerce pull request #12967
Opened 2017-01-24 20:18 UTC by justinshreve

Finishes & Closes #12876.

The PR #12965 prevents the duplicate tool from adding the title in the first place (since we stopped doing that in CRUD).. however, we still need a solution for older products that already have that title set.

I would recommend just deferring to the parents `name`still, for all products. I thought about targeting products with a certain product version, but I think that'll be too slow.

Things like the cart and mini-cart/widget still show which variation is in your cart, so I think it's okay that `get_name()` isn't returning data about the selected variation.

2017-01-25 00:34 UTC, mikejolley requested changes
I don't fully understand what exactly this is fixing, but I'm not keen on the change. You're seeing fallback logic in the cart with the variation attributes. After save, master actually shows variations like this:

https://dl.dropboxusercontent.com/s/458ozb9qpz5ommf/2017-01-25%20at%2000.30.png

Notice the attributes are formatted nicely as part of the title.

Your branch falls back to the list based display.

Can we not handle the bug with the 'old' titles by detecting them (look for "Variation #"?) and then update it, regenerate it, or pull from parent if detected?

2017-01-25 18:42 UTC, justinshreve commented
@mikejolley How about that? It'll catch during read and show the correct title, as well as fire off an update. It's something we could remove in a later version.

2017-01-25 20:17 UTC, justinshreve commented
@franticpsyx Mike mentioned that you might have asked us to keep`get_title`. Around the time of this commit: https://github.com/woocommerce/woocommerce/commit/6b8fc659bfd4d9de9c0d514f7056042bcb406d77. We weren't able to find the thread, but do you remember that/remember what your concerns were?

2017-01-25 22:28 UTC, franticpsyx commented
@justinshreve -- It was here: https://github.com/woocommerce/woocommerce/pull/12783

Issues:

- Repetition. In some locations where `get_name` is used the user sees a list of the variation attributes values in the variation title, followed by a breakdown of attribute names + values. E.g. in the cart & order details. In these cases, the variation title doesn't need to differ from the parent title, since it's followed by detailed attributes config info anyway.

- Sometimes `get_name` is not sufficient because it's missing attribute names. Examples in https://github.com/woocommerce/woocommerce/pull/12783

- Sometimes `get_name` helps keep everything short -- For example, variations in AJAX product search results are probably fine without the attribute names.

I suggested doing a quick scan of the locations where `get_name` is used and make a quick re-evaluation of user experience based on these observations.

2017-01-26 16:04 UTC, justinshreve commented
I backed out my deprecation changes from this PR and opened a separate issue for reviewing usage: #12990. This PR just fixes the `Variation #` and `Product #` titles for us. cc @mikejolley

2017-01-27 17:01 UTC, mikejolley commented
LGTM @justinshreve. Hopefully it doesn't have too much of a performance impact.

2017-01-27 17:01 UTC, merged