Trigger `'woocommerce_variable_product_sync'` hook after variable product is saved
woocommerce/woocommerce pull request #13064
Opened 2017-02-03 23:08 UTC by thenbrent

Because only a product ID is passed to callbacks on `'woocommerce_variable_product_sync'`, callbacks will need to instantiate their own instance of the product to do anything useful with it. This creates a lot of potential for problems given that the product has at that stage had its data only partially saved.

For example, a callback may modify some meta data on its own instance of the product, then save that, only to immediately have that overridden if the instance of `$product` in `WC_Product_Variable::sync()` also had changes to that meta data.

To avoid that, `WC_Product_Variable::sync()` can instead trigger `'woocommerce_variable_product_sync'` only after the product has been saved. This is backward compatible because the hook was triggered at the very end of the process in WC < 2.7.

2017-02-07 16:45 UTC, mikejolley commented
@thenbrent I'm not fond of nsync :p 

You're right about action position, although I think we should go further and do a deprecation action hook to discourage usage.

How about also only passing the object, not `$save` as thats irrelevant to syncing functions?

2017-02-07 18:32 UTC, thenbrent commented
> @thenbrent I'm not fond of nsync :p

😭 

> I think we should go further and do a deprecation action hook to discourage usage.

👍 

> How about also only passing the object, not $save as thats irrelevant to syncing functions?

I'll submit a revised patch this afternoon taking care of those 3 things. 😄

2017-02-07 22:09 UTC, thenbrent commented
@mikejolley just pushed up patches addressing https://github.com/woocommerce/woocommerce/pull/13064#issuecomment-278059756 I've also merged in master to address the merge conflict because of #13063.

The patch now:

* deprecates the `'woocommerce_variable_product_sync'` filter
* includes two new filters, one before saving and one after
* doesn't pass `$save` to callbacks on those filters

2017-02-08 10:27 UTC, mikejolley requested changes
Just a few notes.

2017-02-08 10:27 UTC, mikejolley commented on includes/class-wc-product-variable.php
> +			do_action( 'woocommerce_variable_product_sync_before_save', $product );
Save is also an 'optional' thing. TBH I think a hook name such as `woocommerce_variable_product_sync_data` would be fine. We'd have used `woocommerce_variable_product_sync` if available but it wouldn't be backwards compatible.

2017-02-08 10:27 UTC, mikejolley commented on includes/class-wc-product-variable.php
> +			do_action( 'woocommerce_variable_product_synced', $product );
I don't agree that this one is needed. Unless `$save` is true, this hook is identical to the one above, and if you really did need to kick logic in at this point there are action hooks in each object's save/create/update methods which can be used instead so you can capture all save events.

Did I miss a use case?

2017-02-08 10:27 UTC, mikejolley commented on includes/class-wc-product-variable.php
> +			wc_do_deprecated_action( 'woocommerce_variable_product_sync', array( $product->get_id(), $product->get_visible_children() ), '2.7', 'woocommerce_variable_product_sync_before_save' );
👍

2017-02-10 18:32 UTC, thenbrent commented on includes/class-wc-product-variable.php
> +			do_action( 'woocommerce_variable_product_synced', $product );
The main use case I had in mind was an easy replacement for `'woocommerce_variable_product_sync'`.

I checked for suitable replacements in `WC_Product_Variable::save()`, but there was only the `'woocommerce_before_' . $this->object_type . '_object_save'` hook, which runs before saving.

It looks like further upstream `'woocommerce_new_product'` or `'woocommerce_new_product'` would be suitable though, so I'll remove this and mention those in the deprecated notice for `'woocommerce_variable_product_sync'`.

2017-02-10 18:37 UTC, thenbrent commented
@mikejolley I've addressed those comments. For an explanation on why I've also added `'woocommerce_new_product'` & `'woocommerce_update_product'` to the deprecated notice in SHA: 5d560f3 see https://github.com/woocommerce/woocommerce/pull/13064#discussion_r100595362

2017-02-10 18:40 UTC, merged