Deprecated hook handling
woocommerce/woocommerce pull request #13192
Opened 2017-02-14 19:35 UTC by mikejolley

Closes #13132 

Adds deprecation handling classes based on @thenbrent’s work to deprecate actions and filters.

Also adds correct deprecation methods for soft deprecated functions.

Maps the order line item actions to the replacements - `$item` is already backwards compatible so can be passed to the hooks directly without modification.

2017-02-14 20:11 UTC, claudiulodro requested changes

2017-02-14 20:11 UTC, claudiulodro commented on includes/wc-deprecated-functions.php
> +include_once( 'class-wc-deprecated-action-hooks.php' );
Should there also be a `include_once( 'class-wc-deprecated-filter-hooks.php' );` here?

2017-02-14 20:13 UTC, claudiulodro commented on includes/wc-deprecated-functions.php
> +include_once( 'class-wc-deprecated-action-hooks.php' );
Other than that, the logic of the deprecated filter classes looks solid to me. You can make a new issue if you want me to write some tests for these classes to verify.

2017-02-15 11:16 UTC, mikejolley commented on includes/wc-deprecated-functions.php
> +include_once( 'class-wc-deprecated-action-hooks.php' );
Thanks 👍 I missed that.

2017-02-15 11:46 UTC, mikejolley commented
@claudiulodro How would you approach tests for this? Firing the actions/filters manually? Would be super interested to see if you wanted to give it a shot.

2017-02-15 16:40 UTC, merged

2017-02-15 23:29 UTC, thenbrent commented
So glad to see all those deprecated hooks being triggered now @mikejolley! 😂 

> How would you approach tests for this?

We tested it manually with Subscriptions 2.0. It probably won't be too much help, but this is the plugin we used: https://gist.github.com/thenbrent/53cfdbff0533c85e89e5