Video updates
woocommerce/woocommerce pull request #13390
Opened 2017-02-28 16:02 UTC by ryanr14

Updates the WooCommerce 101 references to WooCommerce Guided Tour.
Slight tweak to the embed code to allow time stamp embeds.
Added some new embeds.

2017-02-28 17:35 UTC, claudiulodro requested changes
Just needs a minor tabbing tweak. Videos work great.

2017-02-28 17:35 UTC, claudiulodro commented on includes/admin/class-wc-admin-help.php
> +				'wc-settings-products-display' => array(
The tabbing goes a little awry here. :)

2017-02-28 17:48 UTC, claudiulodro commented on includes/admin/class-wc-admin-help.php
> +				'wc-settings-products-display' => array(
I'll fix it real quick so we can get this out the door.

2017-02-28 17:51 UTC, claudiulodro approved these changes

2017-02-28 17:51 UTC, merged

2017-02-28 22:44 UTC, ryanr14 commented
Thanks a ton, @claudiulodro. :)

2017-03-02 18:50 UTC, claudiosanches commented
This TitleCase again will make people sad.