Helper: First pass at merging the Helper plugin into WooCommerce
woocommerce/woocommerce pull request #14595
Opened 2017-04-21 12:15 UTC by kovshenin

To keep non WordPress.org-hosted extensions up to date, WooCommerce currently uses a separate plugin called WooCommerce Helper. We're working towards bringing all the functionality that plugin provides (and more!) into WooCommerce Core. This first pass allows users to: 

* Connect their store to a WooCommerce.com account
* List their available product subscriptions
* Activate/deactivate subscriptions and extensions
* Receive package updates for active subscriptions
* Receive update notifications for inactive/unavailable subscriptions

If you experience any trouble while testing this, please turn on `WP_DEBUG` and look at the `helper` log in System Status for more insight.

2017-04-24 13:48 UTC, mikejolley requested changes
Given the code a quick scan and pointed out some potential issues. Leaving additional comments in a sec.

2017-04-24 13:48 UTC, mikejolley commented on assets/css/helper.scss
> +	table.widefat, .wp-editor-container, .stuffbox, p.popular-tags, .widgets-holder-wrap, .popular-tags, .feature-filter, .imgedit-group, .comment-ays {
Place each selector on a new line (https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#structure).

2017-04-24 13:48 UTC, mikejolley commented on includes/admin/helper/class-wc-helper-api.php
> +		return wp_remote_request( $url, $args );
Question: Default timeout is 3 secs. Is this sufficient?

2017-04-24 13:48 UTC, mikejolley commented on includes/admin/helper/class-wc-helper-api.php
> +		return wp_remote_request( $url, $args );
`wp_safe_remote_request` should be used here? `woocommerce_helper_api_base` is filterable.

2017-04-24 13:48 UTC, mikejolley commented on includes/admin/helper/class-wc-helper-plugin-info.php
> +			if ( dirname( $plugin['_filename'] ) == $args->slug ) {
===

2017-04-24 13:48 UTC, mikejolley commented on includes/admin/helper/views/html-main.php
> +	<h2>Subscriptions</h2>
This file is missing localisation on all many of the strings - flagging this one but there are more below.

2017-04-24 13:48 UTC, mikejolley commented on includes/admin/helper/views/html-main.php
> +							<strong><?php echo $updates[ $product_id ]['version']; ?> available</a></strong>
Missing escape

2017-04-24 13:48 UTC, mikejolley commented on includes/admin/helper/views/html-main.php
> +							<span><?php echo date( 'F jS, Y', $subscription['expires'] ); ?></span>
`date_i18n` here and lines 84, 81, 78

2017-04-24 13:48 UTC, mikejolley commented on includes/admin/helper/views/html-oauth-start.php
> +				<?php if ( ! empty( $_GET['wc-helper-status'] ) && $_GET['wc-helper-status'] = 'helper-disconnected' ) : ?>
`$_GET['wc-helper-status'] = 'helper-disconnected'`

you're setting GET to `'helper-disconnected'` here.

2017-04-24 13:48 UTC, mikejolley commented on includes/admin/helper/class-wc-helper-updater.php
> +class WC_Helper_Updater {
Just a nitpick; some classes and methods throughout the PR are missing docblocks.

2017-04-24 13:57 UTC, mikejolley commented
Had a quick test of this too @kovshenin and functionality worked flawlessly. I have a few expired products on my account which showed fine, as did the plugins I have installed which have no subs.

Just some ideas (forgive me if this has been discussed in other places):

![2017-04-24 at 14 47](https://cloud.githubusercontent.com/assets/90977/25340326/47ccbbee-28fd-11e7-823d-d3989c51ba03.png)

1. Helper is currently 'always on'. Should we a) add a way to disable this (some users have moaned about the extensions screen before and requested a filter to disable), and b) does it have to always be included, or can be do some kind of detection to see if it's needed or not? i.e. Woo plugin installed.

2. We have 2 sub-menus; extensions and helper. I don't recall where but I do remember a discussion about users expecting 'extensions' to be related to installed extensions. Why can't we merge these sections? Helper would fit quite nicely under there as a sub-menu item or like this:

![2017-04-24 at 14 54](https://cloud.githubusercontent.com/assets/90977/25340527/f13943e6-28fd-11e7-9f3a-3c44258f1541.png)

The connect banner shown on the helper screen (maybe a more compact version) could also go in there when needed?

cc @mattyza 

3. The actual menu item could show a count or alert symbol if action is required, like the 'plugins' menu does for updates.

2017-04-24 20:59 UTC, claudiosanches commented on includes/admin/helper/views/html-oauth-start.php
> +					<p><strong>Sorry to see you go</strong>. Feel free to reconnect again using the button below.</p>
This need to be hard coded?

2017-04-24 21:00 UTC, claudiosanches commented on includes/admin/helper/views/html-oauth-start.php
> +				<p><a class="button-primary" href="<?php echo esc_url( $connect_url ); ?>">Connect your store</a></p>
Another hard coded string.

2017-04-24 21:00 UTC, claudiosanches commented on includes/admin/helper/views/html-section-account.php
> +<h2>Your Account</h2>
Other hard coded string.

2017-04-24 21:02 UTC, claudiosanches commented
There is a few missing docblocks and hardcoded strings that requires to be fixed.

2017-04-25 08:38 UTC, mattyza commented
+1 to merging the "Extensions" and "Helper" screens. I believe this is/was always the intention, going in.

To the point about selectively disabling the Helper portion of the screen, perhaps we could do this automagically, through detection of the products using that screen? If no extensions with product keys are detected, don't show the screen. If extensions with product keys are present, we then show the screen.

Thoughts @mikejolley @kovshenin @garymurray ?

2017-04-25 10:06 UTC, garymurray commented
> merging the "Extensions" and "Helper" screens. I believe this is/was always the intention, going in.

Yes, I am going to look at how best we can merge those two screens together in some way. Its next on my agenda.

2017-04-26 11:56 UTC, kovshenin commented on includes/admin/helper/class-wc-helper-api.php
> +		return wp_remote_request( $url, $args );
Core's default timeout is 5 seconds. Unless WooCommerce changes this with `http_request_timeout` then it should be sufficient.

2017-04-26 13:00 UTC, kovshenin commented on includes/admin/helper/class-wc-helper-api.php
> +		return wp_remote_request( $url, $args );
b4ba43f551fe2fb25774455431548911c8637426

2017-04-26 15:54 UTC, kovshenin commented on includes/admin/helper/views/html-oauth-start.php
> +				<?php if ( ! empty( $_GET['wc-helper-status'] ) && $_GET['wc-helper-status'] = 'helper-disconnected' ) : ?>
Good catch :)

2017-04-26 15:58 UTC, kovshenin commented
Thanks so much for the reviews @claudiosanches and @mikejolley! I think I've addressed all of the issues in the latest chunk of commits.

I also like the idea of merging it with the Extensions screen, we talked about it a bit with @garymurray who's working on some mockups/flows, which will likely require some changes in the views, as well as the "routing" logic in the `WC_Helper` class.

2017-04-26 23:24 UTC, claudiosanches commented on includes/admin/helper/class-wc-helper-api.php
> +	 * @return null
This function don't return anything, can just remove it.

2017-04-26 23:24 UTC, claudiosanches commented on includes/admin/helper/class-wc-helper-api.php
> +	 */
Missing docblocks for `$endpoint`, `$args` and returned value.

2017-04-26 23:25 UTC, claudiosanches commented on includes/admin/helper/class-wc-helper-api.php
> +	 */
Missing docblocks for `$endpoint`, `$args` and returned value.

2017-04-26 23:25 UTC, claudiosanches commented on includes/admin/helper/class-wc-helper-options.php
> +	private static $option_name = 'woocommerce_helper_data';
Missing docblock.

2017-04-26 23:28 UTC, claudiosanches commented on includes/admin/helper/class-wc-helper-api.php
> +		if ( defined( 'WP_DEBUG' ) && WP_DEBUG && 'woocommerce.dev' === $host ) {
This method looks for internal tests only... Not sure if we should include it for all users.

2017-04-26 23:29 UTC, claudiosanches commented on includes/admin/helper/class-wc-helper-api.php
> +		if ( defined( 'WP_DEBUG' ) && WP_DEBUG && strpos( self::$api_base, 'https://woocommerce.dev/' ) === 0 ) {
Not sure if we should do it for all users, if we are testing it internally we could create a plugin to do it.

2017-04-26 23:35 UTC, claudiosanches commented on includes/admin/helper/class-wc-helper-updater.php
> +		if ( wp_remote_retrieve_response_code( $request ) != 200 ) {
Needs strict comparison

2017-05-30 19:39 UTC, merged