Confirm before deleting log files
woocommerce/woocommerce pull request #14697
Opened 2017-04-25 21:13 UTC by bekarice

Adds a js alert to confirm before deleting log files via System Status > Logs: [See gif](http://cloud.skyver.ge/330D0C3r2W41)

2017-04-25 21:18 UTC, claudiosanches requested changes
Looks good, and I like it, just need a few tweaks.
Thanks for help.

2017-04-25 21:18 UTC, claudiosanches commented on includes/admin/class-wc-admin-assets.php
> +					'delete_log_confirmation' => esc_html__( 'Are you sure you want to delete this log?', 'woocommerce' ),
Need to change to `esc_js( __() )`.

2017-04-25 21:18 UTC, claudiosanches commented on assets/js/admin/system-status.js
> +	$( '#log-viewer-select' ).on( 'click', ' h2 a.page-title-action', function( e ) {
Better change `e` to `evt` to avoid any conflict, we do it in other scripts in WooCommerce.

2017-04-25 21:18 UTC, claudiosanches commented on assets/js/admin/system-status.js
> +		return confirm( woocommerce_admin_system_status.delete_log_confirmation );
Need to update to `window.confirm()`.

2017-04-26 01:47 UTC, bekarice commented
@claudiosanches 🦅  👀   -- nice catches, updated. thanks!

2017-04-28 11:57 UTC, merged