Improve meta data updates
woocommerce/woocommerce pull request #14751
Opened 2017-04-27 11:58 UTC by crodas

Fixes #13791. Right now whenever `save_meta_data` is called (directly or through `WC_Order::save`) all the meta data are written back to the database, even if nothing changed.

That's a bit inefficient and can cause potential race conditions (although this won't happen unless many updates are done in parallel to the same order in different requests). I'm more concern about the overhead though.

This PR creates a tiny class that wraps the meta data array with  an `WC_Meta_Data` object (instead of `stdClass`) which implements a `get_changes` method (pretty similar to what there is already in `WC_Data` sub-classes. Before persisting the meta data back to the database it checks that it actually changed.

## Possible improvements.

1. Move the update/create logic to their own data-store
2. Rename `WC_Meta_Data` to something more generic, so it can be reused any where in the code. Where ever we need to check if an given/object changed or not.
3. Add unit tests to make sure no SQL is executed when `save_meta_data` is executed if no meta data changed.

## Downsides

1. It changes the internal representation of meta datas. It was `stdclass` objects and now they are `WC_Meta_Data`. That woudn't much of a problem but `get_meta_data` returns the array of objects.  There is no difference between using a `stdclass` object and a `WC_Meta_Data` object, but it works fine under normal circumstance (I merged this branch with #14731 locally and everything works as expected).

2017-04-27 16:44 UTC, crodas commented
@mikejolley Any idea why the test is failing? It seems unrelated to this Pull Request.

https://travis-ci.org/woocommerce/woocommerce/jobs/226468744

2017-04-27 16:45 UTC, mikejolley commented
@crodas Looks like Travis is having some issues.

2017-05-23 17:35 UTC, mikejolley requested changes

2017-05-23 17:35 UTC, mikejolley commented on includes/class-wc-meta-data.php
> +
File needs abspath check

2017-05-23 17:35 UTC, mikejolley commented on includes/class-wc-meta-data.php
> +	public $id;
Rather than defining these publicly, how about implementing a magic getter and setter which can also track the changes prior to setting the values?

2017-05-23 17:44 UTC, crodas commented on includes/class-wc-meta-data.php
> +	public $id;
That would be even better. I'm making it happen now.

2017-05-23 17:44 UTC, crodas commented on includes/class-wc-meta-data.php
> +
Will add.

2017-05-23 23:33 UTC, crodas commented on includes/class-wc-meta-data.php
> +
Added in dafc795

2017-05-29 16:41 UTC, crodas commented
Does it look any better now @mikejolley ?

2017-05-31 12:06 UTC, mikejolley requested changes

2017-05-31 12:06 UTC, mikejolley commented on includes/class-wc-meta-data.php
> +
Missing docblocks

2017-05-31 12:06 UTC, mikejolley commented on includes/class-wc-meta-data.php
> +
Remove line break

2017-05-31 12:06 UTC, mikejolley commented on tests/unit-tests/crud/data.php
> +			$this->assertEquals( $metadata[ $id ]->id, $meta->id);
Code standards - space before bracket

2017-05-31 13:41 UTC, crodas commented on includes/class-wc-meta-data.php
> +
Done

2017-05-31 13:41 UTC, crodas commented on tests/unit-tests/crud/data.php
> +			$this->assertEquals( $metadata[ $id ]->id, $meta->id);
Fixed

2017-06-01 15:22 UTC, bor0 commented on includes/abstracts/abstract-wc-data.php
>  				$this->meta_data[ $array_key ]->id = $new_meta_id;
Can't this be `$meta->id = $new_meta_id`?

2017-06-01 15:23 UTC, bor0 commented on includes/abstracts/abstract-wc-data.php
> +			$meta = $this->meta_data[ current( $array_key ) ];
Don't we need to set `$meta->id` here?

2017-06-01 15:25 UTC, bor0 commented on includes/class-wc-meta-data.php
> +		if ( array_key_exists( $key, $this->current_data )) {
Code styles

2017-06-01 15:25 UTC, bor0 commented on includes/class-wc-meta-data.php
> +		foreach ( $this->current_data as $id => $value) {
Code styles

2017-06-01 15:26 UTC, bor0 commented on tests/unit-tests/crud/data.php
> +		$object->add_meta_data( 'test_meta_key', array( 'val1' ), true );
Why is this change needed? Can it potentially break backwards compatibility?

2017-06-01 15:28 UTC, bor0 commented
Files [class-wc-order-item.php](https://github.com/crodas/woocommerce/blob/c59566759c23483549fb7c3a658ae12668c2b7a0/includes/class-wc-order-item.php#L206-L211) and [tests/unit-tests/crud/data.php](https://github.com/crodas/woocommerce/blob/improve_meta_data_updates/tests/unit-tests/crud/data.php#L234-L238) are still using `(object)` to build the meta object.

2017-06-01 15:28 UTC, bor0 requested changes
Left some questions, notes and some more files need the `(object)` to class instantiation change.

2017-06-01 15:31 UTC, crodas commented on includes/abstracts/abstract-wc-data.php
> +			$meta = $this->meta_data[ current( $array_key ) ];
No, if that block is evaluated TRUE means that you already provided the `meta_id` value and you found a meta data object by their ID. `update_meta_data( 'foobar', 'some value', 5)` is quite specific, update the `foobar` metadata with the ID=5. If `foobar` is found its ID will already by 5.

2017-06-01 15:42 UTC, crodas commented on includes/abstracts/abstract-wc-data.php
>  				$this->meta_data[ $array_key ]->id = $new_meta_id;
This `$meta === $this->meta_data[ $array_key ]` is TRUE (objects are always by reference unless `clone $object` is used). But that's a nice catch anyway, I will make that line shorter. Thanks!

2017-06-01 15:43 UTC, crodas commented on includes/class-wc-meta-data.php
> +		foreach ( $this->current_data as $id => $value) {
Thanks!

2017-06-01 15:44 UTC, crodas commented on tests/unit-tests/crud/data.php
> +		$object->add_meta_data( 'test_meta_key', array( 'val1' ), true );
It was a testing directly in the test unit, I could undo that and just add a new a method.

2017-06-01 16:06 UTC, crodas commented on tests/unit-tests/crud/data.php
> +		$object->add_meta_data( 'test_meta_key', array( 'val1' ), true );
Improved in b0f3b5a19

2017-06-01 16:34 UTC, crodas commented
> Files class-wc-order-item.php and tests/unit-tests/crud/data.php are still using (object) to build the meta object.

Regarding [class-wc-order-item.php](https://github.com/crodas/woocommerce/blob/improve_meta_data_updates/includes/class-wc-order-item.php#L206-L211), that's totally fine and expected. That bit of code is reading the metadata which is an object. It won't break that unless somebody is doing `get_class($meta) === 'stdclass'` or `$meta instanceof stdclass`. 

Regarding [tests/unit-tests/crud/data.php](https://github.com/woocommerce/woocommerce/blob/master/tests/unit-tests/crud/data.php#L218-L245), it works without any external modification. That's because [in here](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L325) we cast all the inputs to array (and I didn't changed that).

2017-06-01 16:34 UTC, crodas commented
Thanks for all your feedback @bor0 ! I really appreciate it.

2017-08-08 14:23 UTC, bor0 approved these changes

2017-08-08 14:32 UTC, merged