added new css for dark scheme #14833
woocommerce/woocommerce pull request #14834
Opened 2017-05-02 11:54 UTC by maheshprajapati

This issue resolved when this CSS added

2017-05-03 20:46 UTC, claudiosanches requested changes

2017-05-03 20:46 UTC, claudiosanches commented on includes/wc-template-functions.php
> +				} elseif ( is_array(!empty( $states )) ) {
`empty()` returns boolean, so will make `is_array()` always return false.
And no idea why this change is required here.

2017-05-03 20:46 UTC, claudiosanches commented on assets/css/twenty-seventeen.scss
> +.colors-dark {
Still now follow the coding standards.

Should be:

```scss
.colors-dark {
	.checkout-button {
		border: 2px solid #555;

		&:hover {
			border-color: #fff;
		}
	}
}
```

2017-05-04 06:10 UTC, maheshprajapati commented on includes/wc-template-functions.php
> +				} elseif ( is_array(!empty( $states )) ) {
i think this is correct for this issue isset( $states ) && is_array( $states )

2017-05-04 16:49 UTC, claudiosanches commented on includes/wc-template-functions.php
> +				} elseif ( is_array(!empty( $states )) ) {
No idea for what issue.
And if is a different issue, so should be into a different Pull Request.

2017-05-05 16:52 UTC, claudiulodro commented on includes/wc-template-functions.php
> +				} elseif ( is_array(!empty( $states )) ) {
The CSS look good, but I can't merge this pull request until you remove this change. 

We do one pull request per issue, and this line doesn't have anything to do with the CSS changes. Feel free to open a separate PR with this change if there is a good reason for it, but I can tell you right now that it has some logic problems in it.

2017-05-07 14:11 UTC, closed without merging