Fix #14967 -
woocommerce/woocommerce pull request #15010
Opened 2017-05-10 17:58 UTC by reescott

Allows logs to be stored by microseconds by moving the responsibility of the timestamp to the database.

2017-05-10 21:44 UTC, claudiosanches commented
This will require a update script and maybe could be some difference for database timezone.

2017-05-11 09:04 UTC, sirreal commented
> This will require a update script

👍 

> maybe could be some difference for database timezone.

@claudiosanches My understanding is that this should just add precision to the column, why would timezone be affected?

2017-05-11 09:32 UTC, sirreal requested changes
Thanks for the PR! Unfortunately, this only fixes for MySQL 5.6+ and actually appears to _break_ MySQL <5.6 as-is!

I think we can get this working in a more compatible way, please see my comments for a suggestion. I'm happy to look again when this issue is ironed out.

The downside of this approach is that it will only fix for MySQL 5.6+. Any system using an inferior version will continue to have the issue.

2017-05-11 09:32 UTC, sirreal commented on includes/class-wc-install.php
> +  timestamp datetime(6) NOT NULL DEFAULT NOW(5),
This is going to be problematic as it appears to be _invalid syntax_ in MySQL `<5.6`.

You can see it failing in the automated tests:

> WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL DEFAULT NOW(5),

https://travis-ci.org/woocommerce/woocommerce/jobs/230864195#L316

Maybe a [version comment](https://dev.mysql.com/doc/refman/5.5/en/comments.html) will work here, something like `timestamp datetime/*!50600 (6) */ NOT NULL DEFAULT NOW/*!50600 (5) */` (untested).

2017-05-11 09:32 UTC, sirreal commented on includes/log-handlers/class-wc-log-handler-db.php
> +	protected static function add($level, $message, $source, $context ) {
Style nit: space inside the parens 🙂

2017-05-11 15:06 UTC, claudiosanches commented
@sirreal 

> @claudiosanches My understanding is that this should just add precision to the column, why would timezone be affected?

Currently the `$timestamp` comes from:

```php
	public function log( $level, $message, $context = array() ) {
		if ( ! WC_Log_Levels::is_valid_level( $level ) ) {
			wc_doing_it_wrong( __METHOD__, sprintf( __( 'WC_Logger::log was called with an invalid level "%s".', 'woocommerce' ), $level ), '3.0' );
		}

		if ( $this->should_handle( $level ) ) {
			$timestamp = current_time( 'timestamp' );

			foreach ( $this->handlers as $handler ) {
				$handler->handle( $timestamp, $level, $message, $context );
			}
		}
	}
```

As you can see in https://developer.wordpress.org/reference/functions/current_time/ the timestamp uses the WordPress options to determine the timezone, that is not always the same timezone from the server or database.

2017-05-11 15:31 UTC, sirreal commented
@claudiosanches You're right! Nice catch 👍

2017-05-11 15:45 UTC, claudiosanches commented
Not to mention that this change has not been tested, since the `WC_Log_Handler_Interface` expects a `$timezone` has first parameter in the `handle` method.
If change from database, need to change for the email and file handlers too.
Better find other solution for it.

2017-05-11 15:45 UTC, closed without merging