Back to attributes link on attributes edit page
woocommerce/woocommerce pull request #15088
Opened 2017-05-15 23:26 UTC by AnwerAR

see #15059 The issue was about editing product attributes. Added "Back to attributes" link.

2017-05-16 11:02 UTC, mikejolley requested changes

2017-05-16 11:02 UTC, mikejolley commented on includes/admin/class-wc-admin-attributes.php
> +		echo '<div class="updated"><p>' . __( 'Attribute updated successfully', 'woocommerce' ) . '</p><p><a href="'. admin_url( 'edit.php?post_type=product&amp;page=product_attributes' ).'">&larr; ' . __(
Wrap URL in `esc_url`

2017-05-16 11:02 UTC, mikejolley commented on includes/admin/class-wc-admin-attributes.php
> +		echo '<div class="updated"><p>' . __( 'Attribute updated successfully', 'woocommerce' ) . '</p><p><a href="'. admin_url( 'edit.php?post_type=product&amp;page=product_attributes' ).'">&larr; ' . __(
Also needs space here `).'"`

2017-05-16 14:39 UTC, AnwerAR commented on includes/admin/class-wc-admin-attributes.php
> +		echo '<div class="updated"><p>' . __( 'Attribute updated successfully', 'woocommerce' ) . '</p><p><a href="'. admin_url( 'edit.php?post_type=product&amp;page=product_attributes' ).'">&larr; ' . __(
Should i replace `admin_url` with `esc_url` or can wrap `admin_url` into `esc_url`?

2017-05-16 14:49 UTC, mikejolley commented
Not sure what you're doing here... ecs_url is not valid, and I mean't WRAP the admin_url with an escaping function.

2017-05-16 19:04 UTC, mikejolley commented
Same typo. `ecs_url`?

2017-05-16 20:08 UTC, claudiosanches commented
We need to avoid using arrows `&larr; `, this is bad for RTL languages, even worse that is not able not even to translate it different.

2017-05-17 15:52 UTC, AnwerAR commented
@mikejolley OMG, sorry for typo. it's correct on my localhost. but i do not push changes from localhost. wanna understand `Grunt` tasks first. 
@claudiulodro shall i completely remove `&larr;` or need to be wrapped in `gettext` function along with message? what about `is_rtl() ? '&larr;' : '&rarr;';`?

2017-05-25 10:15 UTC, merged