Check for an existing display name before updating a user on checkout
woocommerce/woocommerce pull request #15239
Opened 2017-05-23 16:59 UTC by ryelle

Fixes #15020

Currently when completing an order, the user's display name is set to "First Name Last Name", which can seem unexpected. This PR adds a check to only update the display name if the existing display name is an email (following the logic in this comment https://github.com/woocommerce/woocommerce/issues/15020#issuecomment-300758499).

**To test**

1. Create a user with their username as the display name
2. Place an order, the display name should still be the username
3. Create another user with the email as their display name (I forced this by adding the email as "nickname")
4. Place an order, the display name should be updated to "First Name Last Name"

Maybe we should add Display Name to the Edit Account form, so that customers can also manage this? Since it is a front-end facing detail in reviews, I think they'd want to control it. Happy to create another issue/PR for this if so 🙂

2017-05-23 18:59 UTC, mikejolley commented
@ryelle That works :) 

A setting may be a good idea but that impacts this PR more-so so I'll explain before merging anything. 

Since this code is in the data-store, adding a user setting would mean it may be ignored during update. So we'd need to:

a) Move this logic into the checkout class inside the `process_customer` method and use a new setter
b) Add a setter/getter for display name to the WC_Customer class
c) Handle the new setter/getter/data in the data store.

That would be the items I'd think need to go in this PR. The UI for the field could be submitted separately.

2017-05-23 19:10 UTC, ryelle commented
Oh I definitely meant that a setting UI would be a separate PR. Do you want me to still make these changes for this PR?

2017-05-23 19:31 UTC, mikejolley commented
Yep; covering the CRUD and Data stores will be good experience as a bonus :)

2017-05-24 18:06 UTC, mikejolley requested changes
Just one change needed it seems :)

2017-05-24 18:06 UTC, mikejolley commented on includes/class-wc-checkout.php
> +			$current_user = get_user_by( 'id', $customer_id );
Since you now have display_name in the CRUD object, you can use the getter here instead of loading the user from WordPress.

2017-05-24 18:15 UTC, ryelle commented on includes/class-wc-checkout.php
> +			$current_user = get_user_by( 'id', $customer_id );
Done 👍

2017-05-24 18:20 UTC, merged