Helper Bug Fixes
woocommerce/woocommerce pull request #15721
Opened 2017-06-21 13:31 UTC by kovshenin

Some final helper changes.

2017-06-21 17:33 UTC, josemarques commented on includes/admin/helper/class-wc-helper.php
> +					'message' => sprintf( __( 'To receive updates and support for this extension, you need to <strong>purchase</strong> a new subscription or <a href="%1$s" target="_blank">be added as a collaborato
Dot missing at the end of the sentence.

2017-06-21 17:34 UTC, josemarques submitted a review, later dismissed

2017-06-21 17:34 UTC, josemarques commented on includes/admin/helper/class-wc-helper.php
> +					'message' => sprintf( __( 'To receive updates and support for this extension, you need to <strong>purchase</strong> a new subscription or <a href="%1$s" target="_blank">be added as a collaborato
Dot missing at the end of the sentence.

2017-06-21 17:37 UTC, josemarques commented
@kovshenin the download buttons are pointing to the product page and not to the zip file:

![screen shot 2017-06-21 at 18 36 37](https://user-images.githubusercontent.com/57050/27398114-a5f64a42-56b0-11e7-8dbb-1ba0573007a9.png)

2017-06-22 11:58 UTC, mikejolley requested changes

2017-06-22 11:58 UTC, mikejolley commented on includes/admin/helper/class-wc-helper.php
> +		uasort( $subscriptions, function( $a, $b ) {
Need to avoid anonymous functions because of 5.2 -.-

2017-06-22 11:58 UTC, mikejolley commented on includes/admin/helper/class-wc-helper.php
> +			} elseif ( $subscription['expired'] && ! empty( $subscription['master_user_email'] ) ) {
Can `expired` also be empty?

2017-06-22 11:58 UTC, mikejolley commented on includes/admin/helper/views/html-main.php
> +									printf( '</br>' . __( 'Shared by %s', 'woocommerce' ), $subscription['master_user_email'] );
Looks like this needs escaping.

2017-06-22 11:58 UTC, mikejolley commented on includes/admin/helper/views/html-main.php
> +									printf( __( 'Subscription: Not available - %1$d of %2$d already in use', 'woocommerce' ), $subscription['sites_active'], $subscription['sites_max'] );
Add escaping.

2017-06-22 11:58 UTC, mikejolley commented on includes/admin/helper/views/html-main.php
> +							<a class="button <?php if ( empty( $subscription['download_primary'] ) ) : ?>button-secondary<?php endif; ?>" href="<?php echo esc_url( $subscription['download_url'] ); ?>" target="_blank"><?p
echo and ternary operator would be cleaner.

2017-06-22 13:43 UTC, kovshenin commented on includes/admin/helper/class-wc-helper.php
> +			} elseif ( $subscription['expired'] && ! empty( $subscription['master_user_email'] ) ) {
No, expired is always explicitly set in the API response, like most other keys.

2017-06-22 15:17 UTC, merged