Force height for the gallery if the image is no loaded at time of init
woocommerce/woocommerce pull request #15893
Opened 2017-06-30 15:00 UTC by mikejolley

2017-07-03 16:37 UTC, claudiosanches commented
Need to fix conflicts.

2017-07-04 10:49 UTC, mikejolley commented
Can still be checked even if it conflicts. Updating now.

2017-07-04 14:55 UTC, claudiosanches requested changes

2017-07-04 14:55 UTC, claudiosanches commented on assets/js/frontend/single-product.js
> +				setTimeout(function(){
Missing spacing.

2017-07-04 17:09 UTC, claudiosanches approved these changes

2017-07-04 17:10 UTC, merged