Checkout: Order Pay to Template
woocommerce/woocommerce pull request #16036
Opened 2017-07-09 18:22 UTC by terence1990

Put the Order Pay content into a template for easy over-riding. This will have no affect to existing users as it there is a template fallback.

2017-07-10 18:36 UTC, WPprodigy commented on templates/checkout/order-pay.php
> +	<?php if ($order->payment_method_title) : ?>
Should use `$order->get_payment_method_title()` I think. https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/class-wc-order.php#L668

2017-07-10 18:36 UTC, WPprodigy commented on templates/checkout/order-pay.php
> +			echo $order->payment_method_title;
Would use `$order->get_payment_method_title()` here as well then.

2017-07-10 18:37 UTC, WPprodigy commented on includes/shortcodes/class-wc-shortcode-checkout.php
> +						'order'              => $order
No need for all the space between the key/value in the array :)

2017-07-10 18:39 UTC, claudiosanches requested changes
Creating a template for this is just fine, but not sure the reason from change the data removing important things and using deprecated arguments from `WC_Order` class... Missing fix coding standards too.
Let me know when you fixed this things.
Thanks for contribute.

2017-07-10 18:39 UTC, claudiosanches commented on templates/checkout/order-pay.php
> +			echo $order->payment_method_title;
And should keep `wp_kses_post()`.

2017-07-11 08:58 UTC, terence1990 commented
Changes have been made according to all of your comments, @claudiosanches i think my original commits were made based on an old master branch, have correct order-pay template to use what's current in the master branch

2017-07-11 10:25 UTC, mikejolley commented
@claudiosanches Is the naming of this template accurate? I mean it contains order details but there is nothing about payment in there?

2017-07-12 09:35 UTC, terence1990 commented
@mikejolley hmm yeah it's not contextual enough, the template is for the view usually just before you get redirected to the vendor.

In my use case i am dealing with Sage 3D Secure on this page. Not really sure what to call this view as it is so transitional.

2017-07-15 16:42 UTC, terence1990 commented
@mikejolley I have changed the name to order-receipt to reflect the actions / hooks naming.

2017-08-09 09:11 UTC, merged