Add enclosure and escape arguments to importer. Introduce filter to change importer arguments
woocommerce/woocommerce pull request #16053
Opened 2017-07-10 15:19 UTC by webspecnick

This PR is twofold. The first change introduces a new filter to change arguments passed to `WC_Product_CSV_Importer_Controller::get_importer()`. The second change introduces `enclosure` and `escape` arguments to `WC_Product_CSV_Importer` which get passed to `fgetcsv`.

Use case:  
A client is using a legacy inventory tracking system that has trouble outputting text and escaping correctly. We decided that the easiest way to create the import CSV file is to have the legacy system use backticks instead of quotes as the enclosure. I can then use `woocommerce_product_csv_importer_args` to change the enclosure arg to the backtick.

Possible workaround: I could create an additional separate system that converts the CSV from the legacy system into one WooCommerce expects, or I could write my own importer class, perhaps extending the base one and updating `read_file`.

Use case:
A user wants to change the arguments passed to an arbitrary importer class, whether that is a WooCommerce core class or provided by another plugin. The user can use `woocommerce_product_csv_importer_args` to filter and change the arguments passed to it.

Possible workaround: A user can create their own importer class and use `woocommerce_product_csv_importer_class` to change which class is used.

2017-07-10 17:39 UTC, claudiosanches commented
Require fix the coding standards, better read this before: https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md#how-to-submit-a-pr
Let me know when you fix this styling issues.
Thanks for contribute.

2017-07-10 17:41 UTC, claudiosanches requested changes

2017-07-10 17:41 UTC, claudiosanches commented on includes/admin/importers/class-wc-product-csv-importer-controller.php
> +		$args = apply_filters('woocommerce_product_csv_importer_args', $args, $importer_class);
Missing spaces after `(` and before `)`.

2017-07-10 17:41 UTC, claudiosanches commented on includes/import/class-wc-product-csv-importer.php
> +			'enclosure'        => '"', //The enclousure argument passed to fgetcsv.
Use space after `//` like all the other comments.

2017-07-10 17:41 UTC, claudiosanches commented on includes/import/class-wc-product-csv-importer.php
> +			'escape'           => '\\', //The escape argument passed to fgetcsv.
The comments here could be more clear than just saying that are passing to `fgetcsv`, or don't need any comment.

2017-07-11 12:40 UTC, webspecnick commented
@claudiosanches I have fixed the styling issues. Thank you for pointing them out.

2017-07-12 11:11 UTC, merged