Add select2 to layered nav
woocommerce/woocommerce pull request #16052
Opened 2017-07-10 13:38 UTC by mikejolley

Closes #13189 
Closes #13336 

Implements select2 for the layered nav if available for dropdowns.

Adds a button to submit multiple selects so multiple values can be chosen before it updates. 

backwards compatible with old queries.

2017-07-10 17:35 UTC, claudiosanches requested changes

2017-07-10 17:35 UTC, claudiosanches commented on includes/widgets/class-wc-widget-layered-nav.php
> +			$_chosen_attributes   = WC_Query                                                                                       ::get_layered_nav_chosen_attributes();
Missing `;`

2017-07-10 17:35 UTC, claudiosanches commented on includes/widgets/class-wc-widget-layered-nav.php
> +			$_chosen_attributes   = WC_Query                                                                                       ::get_layered_nav_chosen_attributes();
Not sure if this even will work... Looks like that is missing more than just `;`.

2017-07-11 09:32 UTC, mikejolley commented on includes/widgets/class-wc-widget-layered-nav.php
> +			$_chosen_attributes   = WC_Query                                                                                       ::get_layered_nav_chosen_attributes();
@claudiosanches no it's not, it's just be spaced weirdly.

2017-07-11 15:38 UTC, claudiosanches commented on includes/widgets/class-wc-widget-layered-nav.php
> +			$_chosen_attributes   = WC_Query                                                                                       ::get_layered_nav_chosen_attributes();
Ohhhh, sorry xD

2017-07-11 15:39 UTC, merged

2017-07-11 15:39 UTC, claudiulodro commented
I don't get any filters applying on the dropdown AND widget. It just loads up the page at `http://local.wordpress.dev/shop/?filter_color=`

2017-07-11 15:42 UTC, claudiulodro commented
Additionally, there are some underlines on the regular widget that aren't present on the other layered nav widget:

<img width="154" alt="screen shot 2017-07-11 at 8 40 50 am" src="https://user-images.githubusercontent.com/7317227/28076870-d7df742a-6614-11e7-9d41-37c02946710f.png">

2017-07-11 15:48 UTC, mikejolley commented
@claudiulodro JS cache

2017-07-11 16:11 UTC, claudiulodro commented
@mikejolley I'm busting it. All the JS is inline anyways, so I think it doesn't need busting. . .

I think the problem is you have a race condition with select2/Woo. On change, select2 updates the value in the hidden input. On change, we submit the form. The two race.

If I change it so that the form submits after 1 millisecond, everything works great. Feels like a hack to do it that way, though. I think if you do the 'change' listener on the hidden input, everything should also work properly.