Moving WooCommerce class to a separate file and fixing coding standards
woocommerce/woocommerce pull request #16115
Opened 2017-07-13 19:04 UTC by claudiosanches

This is a good start point to fully follow all coding standards and best practices, not to mention to inspire people to do the same, and also will helps after #15798 is merged.

2017-07-13 19:06 UTC, claudiosanches commented
Thanks @aristath to raise this issue.

2017-07-14 09:55 UTC, mikejolley requested changes

2017-07-14 09:55 UTC, mikejolley commented on includes/class-woocommerce.php
> + * Main WooCommerce Class
Do we need a file docblock which says the same as the class docblock below?

2017-07-14 09:55 UTC, mikejolley commented on woocommerce.php
> +function wc() {
will this break anything?

2017-07-14 09:55 UTC, mikejolley commented on woocommerce.php
> +	define( 'WC_PLUGIN_FILE', __FILE__ );
This is the only constant needed here. The rest can use this for __FILE__

2017-07-14 15:40 UTC, claudiosanches commented on woocommerce.php
> +function wc() {
PHP functions name are case-insensitive.

See: http://php.net/manual/en/functions.user-defined.php

2017-07-14 15:41 UTC, claudiosanches commented on includes/class-woocommerce.php
> + * Main WooCommerce Class
We can change what this say, but the best practice is have a docblock for the file and another for the class.

2017-07-17 10:09 UTC, merged