Newsletter signup in wizard
woocommerce/woocommerce pull request #16384
Opened 2017-08-08 17:01 UTC by mikejolley

Adds a newsletter form to the wizard.

2017-08-08 18:53 UTC, claudiosanches requested changes
Looks good, just missing a hard coded string.

2017-08-08 18:53 UTC, claudiosanches commented on includes/admin/class-wc-admin-setup-wizard.php
> +				<input type="email" value="<?php echo esc_attr( $current_user->user_email ); ?>" name="EMAIL" placeholder="<?php esc_attr_e( 'Email address', 'woocommerce' ); ?>" required><input type="submit" va
Allow translate the placeholder in the input, but not the value on the button:

```
value="Subscribe"
```

2017-08-08 21:28 UTC, claudiulodro commented
<img width="1333" alt="screen shot 2017-08-08 at 2 27 14 pm" src="https://user-images.githubusercontent.com/7317227/29095465-b93e8f1e-7c45-11e7-999c-4b1147ce640c.png">

Not really a part of your PR (which looks good to go), but the subject line and contact email should probably be updated. Who can we hassle about that? :)

2017-08-10 10:27 UTC, MarinaWoo commented
Seeing it in situ, can you change the sign up copy to:

_Join the WooCommerce mailing list for help getting started, tips and product updates_

@claudiulodro I will sort out the MailChimp subject line and contact email, TY!

2017-08-18 17:22 UTC, merged