fix-condition
woocommerce/woocommerce pull request #16532
Opened 2017-08-19 05:28 UTC by Umangvaghela

fix-condition

2017-08-21 12:12 UTC, mikejolley requested changes

2017-08-21 12:12 UTC, mikejolley commented on includes/class-wc-form-handler.php
> +					if ( 0 ===  wc_notice_count( 'error' )  ) {
There is extra white space

2017-08-21 12:12 UTC, mikejolley commented on includes/class-wc-form-handler.php
> +		if ( $was_added_to_cart && 0 ===  wc_notice_count( 'error' )  ) {
There is extra white space

2017-08-21 12:12 UTC, mikejolley commented on includes/class-wc-form-handler.php
> +			} elseif ( 'yes' ===  get_option( 'woocommerce_cart_redirect_after_add' )  ) {
There is extra white space

2017-08-22 06:16 UTC, Umangvaghela commented on includes/class-wc-form-handler.php
> +			} elseif ( 'yes' ===  get_option( 'woocommerce_cart_redirect_after_add' )  ) {
@mikejolley

Fix this issue on new pull request https://github.com/woocommerce/woocommerce/pull/16558

2017-08-22 09:24 UTC, closed without merging