Tailored the Jetpack step message to the services selected
woocommerce/woocommerce pull request #16796
Opened 2017-09-13 05:28 UTC by marcinbot

Fixes the message appearing on the Jetpack connection step to include the selected services that require a Jetpack connection. No message appears if there are no relevant services selected.

2017-09-13 16:04 UTC, jeffstieler submitted a review, later dismissed
My apologies for forgetting to discuss translation strategy for this.

Unfortunately, we can't concatenate features because that enforces left-to-right.

Let's refactor this to have fully written out strings that can be translated based on which features have been enabled.

2017-09-16 18:19 UTC, mikejolley requested changes
Small things to tweak.

2017-09-16 18:19 UTC, mikejolley commented on includes/admin/class-wc-admin-setup-wizard.php
> +				<?php echo $description ?>
esc_html

2017-09-16 18:19 UTC, mikejolley commented on includes/admin/class-wc-admin-setup-wizard.php
> +			$description = __( "Your store's almost ready. Connect to Jetpack for full access to Stripe payments, automated taxes, live rates and discounted shipping labels.", 'woocommerce' );
`store's` looks like bad english. Use `store is`.

2017-09-16 23:43 UTC, jeffstieler commented
Issues addressed - cool to merge in @mikejolley? This is a pretty minor change.

2017-09-19 20:58 UTC, jeffstieler approved these changes
Approving these changes and merging. The logic for choosing the tailored text works, and I'd prefer to tweak copy all at once.

2017-09-19 20:59 UTC, merged