Preventing Notice in Shipping Zones
woocommerce/woocommerce pull request #18006
Opened 2017-12-04 19:18 UTC by ahmedofali

Adding variable to prevent the notice of undefined variable if function call did not made it through the switch case

2017-12-05 14:21 UTC, claudiosanches requested changes
I recommend you install EditorConfig in your Editor/IDE, so this formatting issues will be easily avoided.

Please let me know when you update and fix the things I pointed out.
Thanks for your contribution.

2017-12-05 14:21 UTC, claudiosanches commented on includes/class-wc-shipping-zones.php
> +                $zone_id = false ;
Need fix the indentation here, we use spaces on WordPress and not spaces.
And need to remove that extra space before `;`.

2017-12-05 14:21 UTC, claudiosanches commented on includes/class-wc-shipping-zones.php
> +
Need remove spaces from this new line.

2017-12-05 19:42 UTC, ahmedofali commented
Well I have fixed indentation problem.

2017-12-06 13:25 UTC, claudiosanches commented on includes/class-wc-shipping-zones.php
> +
Still have spaces on this line.

2017-12-06 15:36 UTC, closed without merging