Helper: Prompt a Helper connection only on relevant screens
woocommerce/woocommerce pull request #18513
Opened 2018-01-18 09:31 UTC by kovshenin

There is no need to prompt the user for a connection to WooCommerce.com on screens that are not related to WooCommerce or plugin/extension management.

Fixes #18452

2018-01-18 17:01 UTC, mikejolley approved these changes

2018-01-18 17:01 UTC, mikejolley commented on includes/admin/helper/class-wc-helper.php
> +		if ( ! in_array( $screen_id, $screens ) ) {
3rd param should be true for strict mode (phpcs rule).

2018-01-18 17:11 UTC, shivapoudel requested changes

2018-01-18 17:11 UTC, shivapoudel commented on includes/admin/helper/class-wc-helper.php
> +		$screens = array(
Better to utilize core function `wc_get_screen_ids`

2018-01-18 17:37 UTC, bekarice commented on includes/admin/helper/class-wc-helper.php
>  		if ( 'woocommerce_page_wc-addons' == $screen_id && ! empty( $_REQUEST['section'] ) && 'helper' == $_REQUEST['section'] ) {
i know this isn't included in the PR, but a quick note: you may also want to make adjustments to use `sanitize_title( __( 'WooCommerce', 'woocommerce' ) ) . '_page_wc-settings'` here instead to compare against screen ID like other parts of WC do (for sites with "WooCommerce" translated, esp when languages use non-ASCII characters). See https://core.trac.wordpress.org/ticket/21454 and https://core.trac.wordpress.org/ticket/18857 (and maybe one day @mikejolley's patch can finally be applied :wink:)

2018-01-19 07:11 UTC, kloon commented
@kovshenin if you can add the strict param to the in_array, use wc_get_screen_ids instead of hardcoding the screens and do the escaping as suggested we are good to merge.

2018-01-22 15:43 UTC, merged