Avoid using eval in add-to-cart-variation.js
woocommerce/woocommerce pull request #19496
Opened 2018-03-22 18:01 UTC by valdrinkoshi

Addresses https://github.com/woocommerce/woocommerce/issues/19129

This PR avoids using `wp.template` which internally uses `eval` (which doesn't play well with sites that want to disable `unsafe-eval`s), while at the same time supporting custom values in the variation.

Note: this PR supports custom values like `data.variation.customvalue` but not more complex data structures like `data.variation.internalObject.customvalue` or arrays e.g. `data.variation.items[0].customvalue`.

2018-06-15 13:12 UTC, mikejolley requested changes
I think at the very least we'd need to account for `{{{ }}}` and `{{ }}` syntaxes (one is unescaped) otherwise it will cause breakages. We cannot anticipate how this is being used and customised in the wild.

2018-06-15 17:08 UTC, valdrinkoshi commented
@mikejolley updated to bail out and use `wp.template` if the template contains complex bindings or evaluate interpolations, WDYT?

2018-06-27 15:46 UTC, mikejolley approved these changes

2018-06-27 15:46 UTC, mikejolley commented
@claudiulodro 3.5?

2018-06-27 17:43 UTC, merged