Apply strip_tags to attributes in loop template
woocommerce/woocommerce pull request #19522
Opened 2018-03-26 06:45 UTC by peterfabian

Fixes #19491 

Testing instructions:
1. Create a product with html tags in the title, e.g. <em>Very</em> nice beanie.
2. Go to /shop/ page (tested with Storefront theme).
3. Look for `aria-label` attribute for `/shop/?add-to-cart=X` anchor; before the fix, you should see `aria-label="Add “<em>Very</em> nice Beanie” to your cart"`.
4. After the fix, the `<em>` tags are stripped: `aria-label="Add “Very nice Beanie” to your cart"`

2018-03-26 10:13 UTC, mikejolley requested changes
The problem with tackling this in the template is:

1. The template version needs a bump to indicate the change (from 3.3 to 3.4)
2. This affects all attributes. I'm not certain but there could be instances where tags are wanted in the attribute e.g. for tooltips?

I'd recommend tackling this in the `woocommerce_template_loop_add_to_cart` function and just stripping tags for the aria-label attribute instead. Thats done outside of template and fixes this problem only.

2018-03-27 15:43 UTC, peterfabian commented
Thanks for the review. I updated the PR according to the suggestion.

2018-03-27 15:49 UTC, mikejolley commented on includes/wc-template-functions.php
> +			if ( array_key_exists( 'attributes', $args ) && array_key_exists( 'aria-label', $args['attributes'] ) ) {
Any reason using this instead of `isset`? These could both be combined into a single isset() statement :)

2018-03-27 17:54 UTC, claudiosanches commented
Why not include into `wc_implode_html_attributes()` since already is applying `esc_attr()`, there is the place where we should avoid include HTML.
Not to mention that there avoid us to update a template with conditional code.

2018-03-28 09:35 UTC, peterfabian commented
@claudiosanches as Mike mentioned, that would affect all attributes, then, which might be not desired? 
Plus it would affect all select input boxes created by `woocommerce_wp_select` from `wc-meta-box-functions.php`. 

Given that tags are not forbidden in quoted attributes, I'm not sure if they should always be just stripped. 

If you (@claudiosanches @mikejolley) think it's better handled elsewhere, please let me know.

2018-03-28 09:57 UTC, mikejolley approved these changes
👍 This is what I had in mind.

@claudiosanches Some elements like data attributes/tooltips may want tags so it's best to target specific attributes IMO since `esc_attr` doesn't help us.

2018-03-28 09:57 UTC, merged

2018-03-28 15:11 UTC, claudiosanches commented
Ohh sorry, I just show now that we are not changing a template, so no problem.