Add privacy policy to account pages
woocommerce/woocommerce pull request #19747
Opened 2018-04-17 17:33 UTC by mikejolley

This implements some privacy settings to control text on checkout/account, and updates the template functions to handle the new options.

2018-04-17 20:43 UTC, claudiulodro requested changes

2018-04-17 20:43 UTC, claudiulodro commented on includes/wc-template-functions.php
> +	}
This needs a default or something, otherwise `wc_get_privacy_policy_text()` will return an uninitialized `$text`

2018-04-17 20:44 UTC, claudiulodro commented
Should we show the registration notice here also? Or is the checkout notice enough for this page?

<img width="578" alt="screen shot 2018-04-17 at 1 37 34 pm" src="https://user-images.githubusercontent.com/7317227/38895601-51282004-4245-11e8-8b42-59f2c4b8d46e.png">

2018-04-18 10:03 UTC, mikejolley commented
@claudiulodro Since we surface a similar message on checkout I don't think we need to do it there too.

2018-04-18 14:25 UTC, claudiulodro approved these changes

2018-04-18 14:26 UTC, merged