Notice about HTTPS as a requirement
woocommerce/woocommerce pull request #19756
Opened 2018-04-17 21:34 UTC by claudiosanches

### Requirements completed:

- [x] Add an admin notice if HTTPS is not used. This should check checkout and admin, and could also check site and home URLs. *
- [x] Link to docs on how to get SSL setup
- [x] Should be dismissible but at least we've done our bit to inform the user

* Checking using `is_ssl()` and checking the shop page, since should be better have HTTPS over all site instead of just a few pages, not to mention that is safer too.

Also the message is based by user, so every user on admin should be able to see and dismiss the message.

### Steps to test:

- Just change to a new theme.

Also it's possible forcing an update, but changing theme should be good enough for here.
For even running `WC_Admin_Notices::add_notice( 'no_secure_connection' );`.

Related to #19735

2018-04-17 21:49 UTC, GlennMartin1 requested changes
The word "required" is misspelled in the admin notice.

2018-04-18 09:11 UTC, kloon submitted a review, later dismissed
Just the one small spelling mistake then this can be merged.

2018-04-18 09:11 UTC, kloon commented on includes/admin/views/html-notice-secure-connection.php
> +			__( 'Your store is not using HTTPS, this is requeried to sell in some countries and to protect your customer data. <a href="%s">Learn more about HTTPS and SSL Certificates.</a>', 'woocommerce' ),
Required not requeried

2018-04-18 12:53 UTC, mikejolley approved these changes

2018-04-18 12:53 UTC, merged