Parent:0 terms via API PUT/POST
woocommerce/woocommerce pull request #19929
Opened 2018-05-02 06:43 UTC by kloon

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR introduces a check that unsets the parent request when creating any term, ie Categories and Attributes, when the supplied value is 0. 0 means there is no parent as that is what is returned when you call GET request on these terms so we need to ensure we cover the scenario where a PUT or POST can be sent with parent:0.

I also notice no API unit tests for categories, I can add some, just want to make sure I did not miss it. Definitely nothing under the api folder in the unit test suite.

Closes #19924 

### How to test the changes in this Pull Request:

1. Create an product category via the API with a property of parent:0
2. No error response should be given.
3. The category should be created with no parent set.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Update - Allow category API PUT/POST requests with parent:0

2018-05-02 09:33 UTC, mikejolley submitted a review, later dismissed
This change would effectively disable the ability to change a parent from an ID TO 0. I think it would be better to handle 0 full rather than unset anything.

2018-05-02 16:49 UTC, claudiosanches requested changes
We don't need none of this code... It's just extra conditional check for something that WordPress already check for us.

We can change all of those code to just:

```php
		if ( isset( $request['parent'] ) ) {
			if ( ! is_taxonomy_hierarchical( $taxonomy ) ) {
				return new WP_Error( 'woocommerce_rest_taxonomy_not_hierarchical', __( 'Can not set resource parent, taxonomy is not hierarchical.', 'woocommerce' ), array( 'status' => 400 ) );
			}

			$args['parent'] = $request['parent'];
		}
```

Error output when using a parent that does not exists:

```php
{"code":"missing_parent","message":"Parent term does not exist.","data":{"status":400}}
```

2018-05-03 14:36 UTC, claudiosanches commented on includes/abstracts/abstract-wc-rest-terms-controller.php
> -			if ( ! is_taxonomy_hierarchical( $taxonomy ) ) {
We still need to check if is hierarchical first, WordPress by default does not check it while using `wp_insert_term` or `wp_update_term`.

2018-05-04 15:16 UTC, claudiosanches approved these changes

2018-05-04 17:56 UTC, merged