solution for issue woocommerce/issues/20142    v2
woocommerce/woocommerce pull request #20160
Opened 2018-05-22 08:41 UTC by FabriSancho

solution for issue woocommerce#20142 v2

2018-05-22 09:06 UTC, mikejolley requested changes

2018-05-22 09:06 UTC, mikejolley commented on includes/data-stores/class-wc-product-data-store-cpt.php
> +		return apply_filters( 'woocommerce_search_products_ids', wp_parse_id_list( $product_ids ) ) );
This has no context, how about including some of the args passed to `search_products` also? `$term, $type = '', $include_variations....`

2018-05-22 09:15 UTC, mikejolley commented
Suggested a tweak above.

>  now we’ll see the next batch of excuses xD

There is no excuse for the way you're commenting.

 r/e https://wordpress.org/support/topic/woocommerce-nightmare-again-this-time-product-searches/#post-10307182

I'd really, really suggest trying to be a little more respectful when commenting--I guarantee you it would lead to better interactions with developers and more constructive outcomes than ranting in threads and quoting me out of context.

I've been trying to give you constructive feedback/direction even when I disagreed with your approach and it's been met with hostility both here and on the forums. _We don't have to accept any code from you, nor help you with your change._ Please bare that in mind in future with all projects and developers.

2018-05-22 13:38 UTC, FabriSancho reviewed
as your wish

2018-05-30 14:05 UTC, mikejolley approved these changes

2018-05-30 14:06 UTC, merged