Fix - nav error while saving setting form
woocommerce/woocommerce pull request #20335
Opened 2018-06-01 09:15 UTC by roshansameer

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### How to test the changes in this Pull Request:

1. Goto settings > Change any input field and try to navigate into new tab.
2. After save warn is displayed, stay on similar page and try to save the settings.
3. After trying to save again the save warn is displayed on save button, which shouldn't be in save btn.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> After input submit is changed to button. Seems like this error came up.

CC @claudiulodro

2018-06-01 12:12 UTC, mikejolley commented on assets/js/admin/settings.js
> +		$( '.submit button' ).click( function() {
Use `:input` so it works for both types.

2018-06-01 12:12 UTC, mikejolley requested changes
Just a small change to make this future proof.

2018-06-01 19:30 UTC, roshansameer commented
@mikejolley Done :)

2018-06-04 09:21 UTC, mikejolley approved these changes

2018-06-04 09:21 UTC, merged