Added new filters when adding shipping rates
woocommerce/woocommerce pull request #20633
Opened 2018-06-26 19:18 UTC by daigo75

Ref. https://github.com/woocommerce/woocommerce/issues/20632

2018-06-27 14:22 UTC, mikejolley requested changes

2018-06-27 14:22 UTC, mikejolley commented on includes/abstracts/abstract-wc-shipping-method.php
> +		), $this ) );
I think $this is in the wrong place?

2018-06-27 14:46 UTC, daigo75 commented
You're absolutely right. I must have copy/pasted it without noticing, my head is all over the place these days.

I'll upload the fix shortly.

2018-06-27 15:11 UTC, daigo75 commented
Done. The shipping method (the `$this`) is passed to the filter to provide additional context. Now the variable is in the correct place.

2018-06-27 15:42 UTC, mikejolley commented
@daigo75 Can we also use `woocommerce_shipping_method_` prefix on these new hooks?

2018-06-27 21:00 UTC, daigo75 commented
Of course. Done, as requested.

2018-06-28 13:28 UTC, mikejolley approved these changes

2018-06-28 13:29 UTC, merged