Adding product data to `removed_from_cart` event
woocommerce/woocommerce pull request #20801
Opened 2018-07-14 14:32 UTC by LuigiPulcini

Adding `$thisbutton.data()` to the arguments sent by the `removed_from_cart` event.
This would help developers easily detect which product has just been removed and alter their theme/plugin accordingly.

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Enter a short summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2018-07-18 13:14 UTC, kloon requested changes
Lets make it do the same as added_to_cart and pass the whole $thisbutton object instead of just the data.

2018-07-18 13:47 UTC, LuigiPulcini commented
If you go to https://www.staging2.waveplayer.info/ you can see this in action. You can add a track to the cart and the cart button corresponding to that track becomes green. Now, if you hover the minicart and remove the item you have just added, the green cart button go back to its original state.
Since each cart button represents a single product, I needed the product id passed by the `removed_from_cart` event in order to deactivate the appropriate button.

2018-07-18 13:52 UTC, kloon commented
@LuigiPulcini makes total sense, I am just requesting that instead of passing `$thisbutton.data()` just pass `$thisbutton` as that is what we are doing with added_to_cart, that way we stick to a standard. You can still get the data in the referencing function by calling .data on $thisbutton.

2018-07-18 13:59 UTC, LuigiPulcini commented
Yes, @kloon, that would be great. I mentioned it could be an alternative solution and one more consistent to what the `added_to_cart` event already does.

2018-07-18 14:36 UTC, kloon commented
Would you mind updating your PR to change that?

2018-07-23 15:18 UTC, LuigiPulcini commented
Hi, kloon,
Sorry for my late reply. I changed my PR according to our previous conversation.
See if that works for you.
Thanks for your help.

2018-07-25 12:13 UTC, kloon approved these changes
Thanks @LuigiPulcini, LGTM! :shipit:

2018-07-25 12:14 UTC, merged