Make wc_get_attachment_image_attributes do what it is suppose to.
woocommerce/woocommerce pull request #20848
Opened 2018-07-19 10:11 UTC by kloon

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
wc_get_attachment_image_attributes was trying to reference a sub array of src which is not present in WordPress, instead it was referencing the first char only. This PR makes it so it checks the actual src string and ensure we do not display images in the woocommerce_uploads folder. It also fixes a undefined index as reported in 20844 due to the unsetting of src by lazy loading plugins.

Closes #20844  .

### How to test the changes in this Pull Request:

1. Run `vendor/bin/phpunit tests/unit-tests/product/functions.php` which has new tests specifically to test the various scenarios.
2. Alternatively, upload an image to the woocommerce_uploads folder and set it as the image of a product, it should not display the image but display the placeholder image instead.
3. Also test using a lazy load plugin to make sure #20844 does not occur.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Tweak - Prohibit use of images located in the woocommerce_uploads folder.

2018-07-19 11:43 UTC, peterfabian requested changes
Great that you added tests. 

However, if the purpose of function `wc_get_attachment_image_attributes ` is to prevent images from `woocommece_uploads` folder to be displayed, I think we need also replace the records in the `srcset`, otherwise only `src` points to placeholder.

Additionally, there are more tags e.g. `data-src`, `data-large_image` which show the URL of the image in the HTML code, so I'm not entirely sure how to review this, since it's not clear to me what the function should actually do.

2018-07-23 08:35 UTC, kloon commented
@peterfabian the functionality is what I get from reading the code and it makes sense since woocommerce_uploads is reserved for private files such as downloads.

Regarding the other src records, I could be wrong but I think since we are manipulating the image src before WordPress outputs it, WordPress should take care of the other records for us.

2018-07-26 21:16 UTC, peterfabian commented
I just think this change does not work for me as I would think it should according to your description.

When I performed the actions you mention in step 2, I get this behaviour:

- If I forbid access to `woocommece_uploads` via nginx configuration, then no image at all is displayed. 
- If I allow access to `woocommece_uploads`, then the original image is shown, not the placeholder.

I think it's because of the `srcset`, as mentioned previously.

2018-07-27 12:14 UTC, kloon commented
Maybe someone else from @woocommerce/proton knows what the purpose of this function is supposed to be? From my interpretation, it should replace the src with the placeholder image if it contains a URL that is in woocommerce_uploads.

2018-08-04 14:52 UTC, claudiulodro commented
This function looks like it should replace images located in the `woocommerce_uploads` folder with the placeholder image on the frontend. It's been [virtually unchanged](https://github.com/woocommerce/woocommerce/blob/3973beae5d5843c4a9e46f398b0acceb0d011ebb/includes/wc-product-functions.php#L452) for at least 5 years.

Looking [at the WP core code](https://github.com/WordPress/WordPress/blob/3d4c461e504812689f97b7062f6da9d155448bc9/wp-includes/media.php#L911-L927), it doesn't look like WP will do any further srcset handling or anything like that after this filter. This filter is the last step when generating the image HTML.

So, I think we need to do it similar to [wc_prepare_attachment_for_js](https://github.com/woocommerce/woocommerce/blob/3973beae5d5843c4a9e46f398b0acceb0d011ebb/includes/wc-product-functions.php#L468), and loop through replacing all image URLs we find with the placeholder image URL.

2018-09-04 17:07 UTC, claudiulodro submitted a review, later dismissed

2018-09-04 18:58 UTC, claudiulodro commented
So if you var_dump the `$attr`, you can see it may have the following structure:
```
array(5) {
  ["src"]=>
  string(74) "http://local.wordpress.test/wp-content/uploads/2018/08/album-1-200x200.jpg"
  ["class"]=>
  string(59) "attachment-woocommerce_thumbnail size-woocommerce_thumbnail"
  ["alt"]=>
  string(0) ""
  ["srcset"]=>
  string(557) "http://local.wordpress.test/wp-content/uploads/2018/08/album-1-200x200.jpg 200w, http://local.wordpress.test/wp-content/uploads/2018/08/album-1-150x150.jpg 150w, http://local.wordpress.test/wp-content/uploads/2018/08/album-1-300x300.jpg 300w, http://local.wordpress.test/wp-content/uploads/2018/08/album-1-768x768.jpg 768w, http://local.wordpress.test/wp-content/uploads/2018/08/album-1-624x624.jpg 624w, http://local.wordpress.test/wp-content/uploads/2018/08/album-1-100x100.jpg 100w, http://local.wordpress.test/wp-content/uploads/2018/08/album-1.jpg 800w"
  ["sizes"]=>
  string(31) "(max-width: 200px) 100vw, 200px"
}
```

So the srcset will be one long string with all of the info already populated in it. I think we can just unset the srcset attribute in this array when injecting the placeholder and be back in business.

2018-09-07 18:38 UTC, claudiulodro commented
I've added the srcset handling I mentioned in my above comment ^. This looks good to me now. 

@peterfabian please approve/reject the latest changes since your review status is "requested changes". Thanks!

2018-09-07 18:38 UTC, claudiulodro approved these changes

2018-09-07 18:56 UTC, peterfabian approved these changes
LGTM now.

2018-09-07 19:08 UTC, merged