Fix/21025
woocommerce/woocommerce pull request #21108
Opened 2018-08-20 16:42 UTC by peterfabian

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #21025  .

### How to test the changes in this Pull Request:

1. Add a product to cart, try to tab to the 'View cart' link, see you need to go through a lot of links first.
2. Apply branch.
3. Link 'View cart' should now be at tab index 1. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Add to cart notice actions (View cart/Continue shopping) now have tabindex 1.

2018-08-20 18:58 UTC, claudiulodro commented on templates/notices/error.php
>   * @version     3.3.0
Please bump version to 3.5.0 and remove `@author` tag

2018-08-20 19:01 UTC, claudiulodro requested changes
There is [one other wp_kses_post these notices get run through](https://github.com/woocommerce/woocommerce/blob/439fec579c822613af08fa14c6e3347b15594570/includes/wc-notice-functions.php#L147). I wasn't able to make this work without modifying this one, too.

Overall this should work well. I like your solution for injecting `tabindex` into `wp_kses`.

2018-08-20 19:01 UTC, claudiulodro commented on templates/notices/notice.php
>   * @version     1.6.4
Please bump version to 3.5.0 and remove @author tag

2018-08-20 19:01 UTC, claudiulodro commented on templates/notices/success.php
>   * @version     3.3.0
Please bump version to 3.5.0 and remove @author tag

2018-08-20 19:28 UTC, claudiulodro commented
What do you think about abstracting the wp_kses_post tweak into a new `wc_kses_notices`? That should reduce the copy+pasting of that.

2018-08-21 10:05 UTC, peterfabian commented
Thanks for the review, all your points were valid, so I updated the PR accordingly.

2018-08-21 19:15 UTC, claudiulodro approved these changes
Looks great! Thanks.

2018-08-21 19:16 UTC, claudiulodro requested changes
Almost! Sorry I should have noticed this earlier. [A unit test needs updating](https://travis-ci.org/woocommerce/woocommerce/jobs/418622560).

2018-08-22 09:09 UTC, peterfabian commented
Well spotted, thanks. Shame on me for not checking 🙈

2018-08-22 11:19 UTC, kloon requested changes
Just a small suggestion regarding the phpcs ignore rules, otherwise good to go.

2018-08-23 12:32 UTC, peterfabian commented on templates/notices/success.php
> +			echo wc_kses_notice( $message ); // phpcs:ignore WordPress.XSS.EscapeOutput.OutputNotEscaped
Good idea, thanks. Fixed.

2018-08-23 13:29 UTC, kloon approved these changes
Good to 🚢

2018-08-23 20:10 UTC, claudiulodro approved these changes

2018-08-23 20:11 UTC, merged