Include URL for the last element in breadcrumb list
woocommerce/woocommerce pull request #21111
Opened 2018-08-20 21:51 UTC by rodrigoprimo

### Changes proposed in this Pull Request:

I noticed that the structured data generated by WooCommerce doesn't pass Google Structured Data validation (https://search.google.com/structured-data/testing-tool) due to the following error in the last element of the BreadcrumbList:

"The value provided for item.id must be a valid URL."

This happens because the code was explicitly omitting the URL for the last element. This commit simply removes this check and now an URL is included for every element (unless there is no URL set).

It is important to note that I don't know much about Structured Data and I don't know if there is a reason for the code to omit the URL for the last element, I simply saw the error in the testing tool mentioned above while working on a fix for #21057 and checked if it was easy to fix it. Thus, it is important that this PR is reviewed by someone who is familiar with this functionality. 

cc @ebrahimdabiri in case you can help here as you opened #21057 and @opportus as you are the original author of the structured data code.

### How to test the changes in this Pull Request:

1. Navigate on a few WooCommerce pages in the frontend to populate the breadcrumb list
2. Open the source code of the last page and copy the contents of the following tag `<script type="application/ld+json">`
3. Paste it in the Google Structured Data Testing Tool (https://search.google.com/structured-data/testing-tool) and check that there are no errors

### Changelog entry

> Fix: structured data breadcrumb elements should always contain an URL

2018-08-21 20:14 UTC, claudiulodro commented
Good catch. I noticed that too when testing the previous structured data PR.

The structured data requirements may have changed over time. The last item in the breadcrumb is going to be the current page's URL so Google may not have needed it in the past ¯\\_(ツ)_/¯

This doesn't seem to solve the issue in my testing. No URL gets generated for the last item in the list and if I dump the contents of `$crumbs` I get:
```
array(4) {
--
  | [0]=>
  | array(2) {
  | [0]=>
  | string(4) "Home"
  | [1]=>
  | string(27) "http://local.wordpress.test"
  | }
  | [1]=>
  | array(2) {
  | [0]=>
  | string(8) "Clothing"
  | [1]=>
  | string(54) "http://local.wordpress.test/product-category/clothing/"
  | }
  | [2]=>
  | array(2) {
  | [0]=>
  | string(7) "Hoodies"
  | [1]=>
  | string(62) "http://local.wordpress.test/product-category/clothing/hoodies/"
  | }
  | [3]=>
  | array(2) {
  | [0]=>
  | string(16) "Hoodie with Logo"
  | [1]=>
  | string(0) ""
  | }
  | }


```

@rodrigoprimo do you get a URL generated for the current product in `$crumbs` in your testing?

2018-08-22 11:02 UTC, kloon requested changes
The structured data is build based on what `$breadcrumbs->get_breadcrumb();` returns, unfortunately if you are on a product page it does not include a URL for the current product since breadcrumbs should not link to the current product you are on.

You will need to make changes to either get_breadcrumb to accept a paramater to return the url for the current product, or make `generate_breadcrumblist_data` figure out the URL if it is the last element in the $crumbs array.

2018-09-03 21:35 UTC, mantis4444 commented
Joining you guys! I also suffer from this bug since now I'm working on the SEO. Did my hack and hope with the next update my hack will be cleaned together with the bug

2018-09-04 20:38 UTC, claudiulodro commented
Updated. I get no errors with the latest change in the structured data testing tool for single product pages.

2018-09-05 12:56 UTC, kloon approved these changes
Seems to do the trick, thanks @claudiulodro

2018-09-05 18:03 UTC, mantis4444 commented
Guys you forgot category page.

2018-09-05 20:34 UTC, claudiulodro commented
Good catch @mantis4444. Thanks for the heads-up. Fixed in the latest commit.

2018-09-12 10:44 UTC, kloon approved these changes

2018-09-12 10:45 UTC, merged