Add/template form action hooks
woocommerce/woocommerce pull request #21248
Opened 2018-09-01 15:49 UTC by robertdevore

This PR is based on some issues I ran into when adding new form fields to a user's account and then accessing them via the WooCommerce edit account & registration forms.

When trying to add the option for a user to upload a file (example: medical verification documents), the form does not allow for image uploads.

Currently, you'd need to override the template file within your plugin/theme and add in `enctype="multipart/form-data"` to each form.

In WordPress Core, there is currently an action hook for the edit profile screen, `user_edit_form_tag` in `wp-admin/user-edit.php`.

This PR follows that logic and adds action hooks into the form tags for both the edit account and register forms.

`woocommerce_edit_account_form_tag`

`woocommerce_register_form_tag`

This way, developers can add the specific form tags needed without having to override the template itself.

Example:

```
function make_form_accept_uploads() {
	echo ' enctype="multipart/form-data"';
}
add_action( 'woocommerce_edit_account_form_tag', 'make_form_accept_uploads' );```

2018-09-02 16:51 UTC, appleapplekute approved these changes

2018-09-04 18:11 UTC, claudiulodro requested changes
Hi. Thanks for the contribution. 

This change seems reasonable. Please make the small code style tweak and update the version numbers at the top of the files to `3.5.0` and this is good to merge.

2018-09-04 18:11 UTC, claudiulodro commented on templates/myaccount/form-edit-account.php
> +<form class="woocommerce-EditAccountForm edit-account" action="" method="post"<?php do_action( 'woocommerce_edit_account_form_tag' ); ?>>
Just a small code style tweak please on both of these forms: I would like to see a space between the opening/closing PHP tags. `post" <?php ... ?> >`.

2018-09-04 18:45 UTC, claudiulodro approved these changes
Looks great! 👍 Thanks for the contribution.

2018-09-04 18:47 UTC, merged