fixes an issue with additional payment select fields having 'disabled…
woocommerce/woocommerce pull request #21391
Opened 2018-09-19 11:45 UTC by netzkollektiv

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This fixes an issue for payment fields including select fields using "disabled selected" as pseudo-placeholder. The following HTML will lead to an error: 

`<select>
<option name="" disabled selected>Please select a value</option>
<option name="val1">Value 1</option>
<option name="val2">Value 2</option>
</select>`

> Uncaught TypeError: Cannot read property 'length' of null
>    at HTMLSelectElement.<anonymous> (checkout.js?ver=3.4.5:378)
>    at Function.each (jquery.js?ver=1.12.4:2)
>    at jQuery.fn.init.each (jquery.js?ver=1.12.4:2)
>    at Object.success (checkout.js?ver=3.4.5:372)
>    at i (jquery.js?ver=1.12.4:2)
>    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
>    at y (jquery.js?ver=1.12.4:4)
>    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)

### How to test the changes in this Pull Request:

1. create a payment field for a payment module including the HTML shown above
2. go to checkout
3. change your name or address, so that `wc_checkout_form.update_checkout_action` is triggered
4. check console for errors

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

Fixes an issue with select payment fields using `disabed select` as placeholders

2018-09-24 18:34 UTC, claudiulodro requested changes

2018-09-24 18:34 UTC, claudiulodro commented on assets/js/frontend/checkout.js
> +								} else if ( $(this).val() !== null  && 0 === $( this ).val().length ) {
This change looks reasonable. The code style just needs a little changing to follow WP style guidelines. 

The conditional should be a yoda conditional and there should be spacing around `this`, e.g. `null !== $( this ).val()`. If you can please make this change we can get this merged for 3.5.0.

2018-09-26 14:11 UTC, netzkollektiv commented
@kloon @claudiulodro
Thanks, made the requested changes! Happy to get it merged!

2018-09-26 16:23 UTC, claudiulodro approved these changes
Thanks for the contribution. Everything looks good now.

2018-09-26 16:23 UTC, merged