Fix: copy customer ID for orders placed manually via wp-admin
woocommerce/woocommerce pull request #21673
Opened 2018-10-25 15:48 UTC by rodrigoprimo

### Changes proposed in this Pull Request:

This PR adds a new database update routine to copy the customer ID for orders placed manually via wp-admin from the `_customer_user` postmeta to the `post_author` field in `wp_posts`. This is necessary due to a bug in wc_update_350_order_customer_id() that made this function skip copying data for manually placed orders via wp-admin in some cases. The bug only affected stores that executed the database updated routine via the wp-admin interface and not stores that executed the update routine via the WP-CLI command.

This new update routine gets all the IDs of the orders that were placed manually via wp-admin using the postmeta `_created_via` and then executes another query to get the customer ID for those orders using the postmeta `_customer_user`. Finally, it executes an update query to change the post_author value for each of the manually placed orders. This strategy should work well for most stores but it will be slow for stores with a significant number of manually placed orders.

It is also important to note that this update routine will run for every store, but it only needs to run for stores that updated the database to 3.5 using the wp-admin interface. I couldn't think of a way to skip this update routine for stores that updated the database to 3.5 using the WP-CLI command.

Closes #21656 

### How to test the changes in this Pull Request:

1. Check that the update routine is not altering anything other than what is needed
2. See #21656 for instructions on how to reproduce the problem and run the 3.5.1 update routine to confirm that this PR fixes it.

### Changelog entry

> Fix: copy customer ID for orders placed manually via wp-admin to fix issue caused by a bug in the 3.5 update routine

2018-10-25 17:19 UTC, rodrigoprimo commented
cc @stianandreassen in case you are available to test this PR as you reported the issue

2018-10-25 17:41 UTC, stianandreassen commented
Tested on a copy of the affected DB, and this PR successfully restores customers to orders entered manually by `shop_manager` in wp-admin.

2018-10-26 08:52 UTC, stianandreassen approved these changes
Tested on a copy of the affected DB, and this PR successfully restores customers to orders entered manually by `shop_manager` in wp-admin.

2018-10-26 10:54 UTC, kloon requested changes
LGTM and restores everything. Just one suggestion, can we also break this up into chunks as we did with the original update routine, just in case there are a lot of records to go through.

2018-10-26 13:16 UTC, rodrigoprimo commented
@kloon, I don't think we can break this up into chunks as we did in `wc_update_350_order_customer_id()`, but please let me know if you see a way that I'm missing.

We could paginate the first query to get say 1000 order IDs per run. This would work well for the first few queries, but the closer we get to the end of the IDs the slower the queries would get. For example, on my machine using a large database with a million orders where `_created_via` is set to `admin` getting all order IDs takes about the same time as getting just the last 1000 order IDs:

```
MySQL > SELECT `post_id` FROM wp_postmeta WHERE `meta_key` = '_created_via' AND meta_value = 'admin';
1000000 rows in set (21.79 sec)

MySQL > SELECT `post_id` FROM wp_postmeta WHERE `meta_key` = '_created_via' AND meta_value = 'admin' LIMIT 999000,1000;
1000 rows in set (15.43 sec)
```

We could run in batches in `wc_update_350_order_customer_id()` without using pagination. I don't see a way to do this here.

I decided to go with this approach assuming that the number of stores with a significant number of orders placed manually via wp-admin is relatively small, but I don't have any data to back up this claim. It should be possible to copy the customer IDs using a temporary table and a single update call as we did when `wc_update_350_order_customer_id()` is called via WP-CLI. This should be faster, but it is also more complex and more resource intensive. Given the time constraints and my assumption above about the number of affected stores, I didn't try this option.

Do you see another way to copy the data?

I considered getting the IDs of all shop managers (and potentially other custom roles with permission to place orders manually) and then searching for orders in wp_posts using post_author, but getting users by role in WP is super slow as each user roles are stored in a single serialized user meta entry. So this approach would be problematic for stores with a significant number of users, which I believe is more common than a considerable number of orders placed manually.

2018-10-29 17:07 UTC, rodrigoprimo commented
For the next release (WC 3.5.1), we decided to revert the PR that changed WC to use `post_author` instead of `_customer_user` postmeta. Closing this PR in favor of #21740.

2018-10-29 17:07 UTC, closed without merging