fix: Manually adding fee on order generate html code
woocommerce/woocommerce pull request #21769
Opened 2018-10-31 16:07 UTC by nishitlangaliya

### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Other information:
* [X] Have you successfully ran tests with your changes locally?

> I found that add fee manually triggers `woocommerce_add_order_fee` which returns whole html in response instead of only line item fee html. esc_html function was not working as it should be. html_entity_decode works fine for the solution. also with current issue if you try to edit fee then it returns html string in edit input box `order_item_name` so to display only value we need to clean the html string.

2018-11-02 16:41 UTC, claudiulodro requested changes
Hi @nishitlangaliya.

Thanks for giving this a shot! I think you are on the wrong path, though. :) 

This change makes it possible to do XSS with the fee name, and doesn't solve the real source of the problem. I think the best solution would be to find the change that made it so HTML is in the fee name and remove/fix it so that HTML is no longer in the fee name. That will solve the issue everywhere. Happy to answer any questions if you have them.

2018-11-02 17:28 UTC, nishitlangaliya commented
@claudiulodro ,

Thanks for review PR and provide your valuable suggestions. As per my understanding from your feedback, I am looking for source where it saves html string and remove Html while save so that fee name save as plane text.  I am moving forward with solution. If I will have any query I will ask you for the same :)  Let me know if I am misunderstood or missing here.

Thanks

2018-11-02 18:51 UTC, nishitlangaliya commented
@claudiulodro,

As per suggestion I have made the adjustment in code to save fee without html string in database so that no issue occurs while retrieve it. Please review PR and let me know if still any changes required.

Thanks

2018-11-05 20:27 UTC, claudiulodro approved these changes
The latest version looks great. Good work. Thanks!

2018-11-05 20:27 UTC, merged

2018-11-06 01:30 UTC, nishitlangaliya commented
@claudiulodro,

Thanks for your appreciation :) I am happy to contribute!!!