Update routine to roll back the post_author db changes.
woocommerce/woocommerce pull request #21881
Opened 2018-11-11 20:17 UTC by kloon

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
In #21740 the post_author changes was rolled back, but it left all the DB changes in place. This is resulting in the WP interface displaying orders as belonging to the current logged in admin when it should not. This RP rolls back the DB changes as well to ensure all orders not created via the admin is assigned the ID 1 again as per previous versions of WooCommerce.

Closes #21834 

### How to test the changes in this Pull Request:

1. Check that you have orders in the DB with different post_author IDs.
2. Check out this branch and run the DB update routine.
3. Check that orders in the DB are all assigned the ID 1, unless the order was created via wp-admin.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Rollback - post_author DB changes.

2018-11-20 16:11 UTC, rodrigoprimo requested changes
Besides what I mentioned in the inline comments, I think we also need to add the two new update functions to `class-wc-install.php` or they won't be executed.

2018-11-20 16:11 UTC, rodrigoprimo commented
Have you tested this query on a large database with a significant number of entries where post_author != 1 to see if it performs well?

2018-11-27 19:22 UTC, claudiulodro commented
Moving this to 3.5.3. I'm not rushing out the changes without extensive review and testing; we don't want to ruin any databases.

2019-01-15 17:33 UTC, claudiulodro commented
Is this PR still needed, given that the issue only affected people that upgraded during the first week of the release months ago?

2019-01-16 12:00 UTC, rodrigoprimo commented
> Is this PR still needed, given that the issue only affected people that upgraded during the first week of the release months ago?

IMHO, it is not. I think it is safer to leave the post_author field in some sites with the ID of the customer since we don't use this field anyway, than to try to update it.

2019-01-16 12:55 UTC, mikejolley commented
+1. Another update routine makes me weary. Best to leave until we add the change back IMO.

2019-01-16 12:55 UTC, closed without merging