FIx:  Delete wc_layered_nav_counts_* transients whenever a product is updated
woocommerce/woocommerce pull request #22029
Opened 2018-11-23 17:40 UTC by rodrigoprimo

### Changes proposed in this Pull Request:

This PR moves the code to delete wc_layered_nav_counts_* transients from WC_Product_Data_Store_CPT::update_attributes() to wc_delete_product_transients(). This way those transients will be deleted whenever a product is updated and not only when the product attributes are updated. This is needed to make sure that the "Filter Products by Attribute" displays the correct list of attributes when a product changes from out of stock to in stock or vice versa via the "Quick Edit" interface or the WC API.

This PR also includes PHPCS fixes for all the modified files.

Closes #21429.

### How to test the changes in this Pull Request:

1. See #21429 for instructions on how to test this problem when updating products using the "Quick Edit" interface.
2. To test using the WC API, follow the same steps described in the issue above, but instead of using the "Quick Edit" interface, use the WC API to update a product stock quantity to zero (or from zero to any number >= 1).

### Changelog entry

> Fix: update "Filter Products by Attribute" widget when product stock quantity changes via "Quick Edit" or WC API

2019-01-04 15:21 UTC, claudiulodro commented
Overall this change seems to solve the reported issue. It does introduce a new bug, though. If you delete an attribute from a product the counts do not get updated. Here is a gif example:
![newattsbug](https://user-images.githubusercontent.com/7317227/50695019-54c0cd00-0ff0-11e9-87a8-02df5fd2022b.gif)

I think we should be able to keep the old transient clearing in `update_attributes` and this new one you've added. That should cover all cases.

2019-01-04 15:22 UTC, claudiulodro requested changes
See comment about new bug.

2019-01-10 16:31 UTC, rodrigoprimo commented
Good catch, I didn't notice that my change had broken the deletion of the transient when a product attribute is removed. I agree with you that restoring the code to remove transient inside WC_Product_Data_Store_CPT::update_attributes() while keeping the new code in wc_delete_product_transients() is the best approach. I just push a commit that implements this.

2019-01-11 19:06 UTC, claudiulodro approved these changes
Latest version looks good and works well in all situations. 👍

2019-01-14 17:26 UTC, merged