notify script plugins that the cart was emptied
woocommerce/woocommerce pull request #22469
Opened 2019-01-15 18:54 UTC by rrennick

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Script plugins relying on the `updated_cart_totals` event get a notification when products are removed from the cart except when the cart is emptied. It looks like the reasoning for this was that the cart elements are no longer present. Adding the `updated_cart_totals` event when the cart is emptied could create compatibility issues with scripts attached to the event that are expecting the cart content to be present.

This PR adds a new trigger `updated_cart_emptied` that can be used by plugins to monitor for the empty cart event.

Closes #22453 .

### How to test the changes in this Pull Request:

1. Add multiple items to the cart
2. Add listeners to `updated_cart_totals` and `updated_cart_emptied`.
3. Remove the items from the cart & verify the triggers are called as described above.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Add a trigger `updated_cart_emptied` for the empty cart event..

2019-01-16 07:04 UTC, kloon requested changes
Happy to include the new trigger, can we perhaps just change the name with a wc prefix? Something like wc_cart_emptied

2019-01-16 14:37 UTC, rrennick commented
@kloon Thanks, update to `wc_emptied_cart`.

2019-01-16 14:39 UTC, kloon approved these changes

2019-01-16 16:27 UTC, merged

2019-01-16 16:54 UTC, mattLummus commented
Thank you guys for the quick PR! ❤️

2020-05-22 06:45 UTC, anoordende commented
> @kloon Thanks, update to `wc_emptied_cart`.

A silly little thing, but got me going round in circles for a while. This should be `wc_cart_emptied`.