Hide ratings when reviews are disabled
woocommerce/woocommerce pull request #22476
Opened 2019-01-16 10:00 UTC by kloon

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Ratings forms part of the review system, this PR fixes an issue where if you disable reviews it will still show the ratings. Since ratings are part of reviews and the settings are hidden when you disable reviews the ratings should also not be disabled as reviews when you disable reviews.

Closes #22470 

### How to test the changes in this Pull Request:

1. Enable ratings and enable reviews and save settings
2. Create a rating for a product
3. Disable just the reviews setting and save
4. Check the shop page for the product and ensure no star ratings are displayed.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix - Hide ratings on the shop page when reviews are disabled.

2019-01-16 16:26 UTC, mikejolley requested changes

2019-01-16 16:26 UTC, mikejolley commented on templates/loop/rating.php
> +if ( 'no' === get_option( 'woocommerce_enable_review_rating' ) || 'no' === get_option( 'woocommerce_enable_reviews' ) ) {
Can we make a helper function for this to see if ratings should be enabled/visible? Then if we need to tweak this logic in the future, we can avoid a template update.

2019-01-17 13:30 UTC, mikejolley commented
Let's keep this back for 3.6 since it's spanning multiple template files. The bug itself isn't critical or new.

2019-01-17 14:38 UTC, kloon commented
Sounds good.

2019-01-21 15:19 UTC, mikejolley requested changes
Versions need changing to 3.6.0 then this can be merged.

2019-01-22 13:32 UTC, mikejolley approved these changes

2019-01-22 13:32 UTC, merged