Fix transient version issues
woocommerce/woocommerce pull request #22511
Opened 2019-01-21 13:14 UTC by mikejolley

This is an alternative to https://github.com/woocommerce/woocommerce/pull/21282

The current stategy to invalidate transients is to use a version in the transient name. When transient version changes, attempt to cleanup transients so they are not kept in the DB.

This cleanup routine can be resource intensive and can also fire multiple times within a page (after every save for example). The current code tries to defer this cleanup to prevent pages loading slow.

#21282 changes the defer logic but keeps the cleanup in place.

This PR exists to show that the cleanup isn't neccessary. Instead, rather than having the version part of the transient name, it stores the version within the transient value.

When the value is loaded, the version is checked. If stale, the transient is recreated. The name however remains the same. This means cleanup is no longer neccessary.

Closes #21100
Closes #21282

2019-01-31 20:00 UTC, claudiulodro requested changes
Overall, I really like the proposed approach to transients. 👍 Big improvement and excellent idea!

Other than the minor code change I suggested, the main issues I see are [some failing tests](https://travis-ci.org/woocommerce/woocommerce/jobs/482412925). There is likely a bug around transient cleanup or the tests just need updating.

2019-01-31 20:02 UTC, claudiulodro commented
Everything worked well in my testing, except the layered nav disappeared for a few minutes after switching to this PR. Likely related to the failing unit test.

2019-02-06 13:11 UTC, kloon approved these changes
Good to merge, works as expected and all issues reported have been resolved.

2019-02-06 13:19 UTC, merged

2019-02-24 19:26 UTC, Braintelligence commented
I have products with >5k variants that when I try to update generate a lot of delete_version_transients objects in cron and the product never gets updated (loading icon keeps spinning, no errors in the logs to be seen).
Could this PR help me leviate this problem?

2019-02-24 22:05 UTC, mikejolley commented
It will prevent the cron jobs.

2019-02-25 19:29 UTC, Braintelligence commented
In the meantime I found out that destroying and recreating the variants helped updating the product. With ~4500 variants it takes about 4 minutes and 10 seconds to update the product.
For some reason some old products don't want to update even within 30 minutes with the same amount of variants. Perhaps I broke something there before I managed to fix my cron issues.
Thank you very much for clearing this up @mikejolley! Less cron jobs will surely help with the performance as well 👍

2019-03-02 11:26 UTC, mikejolley commented
@Braintelligence If only in development, you could give the master branch a shot. It's hard to say tbh because I don't know what problem you're running into or if its actually related to these transients.

2019-03-19 13:03 UTC, Braintelligence commented
@mikejolley I confirmed a bug in 3.6 beta maybe related to this.

If you have a product with, let's say 4300 possible variants, and generate them with a `WC_MAX_LINKED_VARIATIONS=1000` 5 times you get 5010 variants and thus duplicates.

If you do it again from scratch with `WC_MAX_LINKED_VARIATIONS=10000`, you get only the possible 4300 variants.

For some reason the new variant generation logic doesn't properly care for already present variants.