use `name` for POST/PUT category image name for consistency
woocommerce/woocommerce pull request #22553
Opened 2019-01-24 18:14 UTC by rrennick

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In all versions of the API the image name (title in the media library) field is output as the `name`. Updating via PUT/POST (for existing media) uses the `title` field. Images attached to products use `name`. This PR updates PUT/POST to use `name`.

Closes #22449 .

### How to test the changes in this Pull Request:

1. Without the PR PUT 
URL: `/wp-json/wc/v3/products/categories/(category-id)`
Payload: `{"id":(category-id),"image":{"id":(attachment-id),"name":"Updated Title"}}`
2. The response should have `name` as the original image title from the media library
3. Repeat with the PR
4. The response should have `name` as `Updated Title` from the media library
5. Visit the media library & the image title should be `Updated Title`.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Changelog entry

> Fix category image `name` field to be used for API POST/PUT.

2019-01-24 18:17 UTC, claudiosanches requested changes
Schema for v1 and v2 uses `title`, we changed it only in v3, so this patch need to target v3 only.

2019-01-24 19:40 UTC, rrennick commented
@claudiosanches Thanks, I updated the commit.

2019-01-24 19:53 UTC, claudiosanches approved these changes
Thanks for your help.
Great work.

2019-01-25 07:02 UTC, kloon commented
@rrennick could you perhaps just do the two PHPCS fixes that is failing in the commit? Will ensure the build pass. Thanks!

2019-01-25 13:57 UTC, rrennick commented
@kloon Thanks for the reminder. When I ran the phpcs locally, it found line #184 which was missed by the Travis job. Is there a ruleset that needs to be updated?

2019-01-31 13:46 UTC, merged