Improve slow term ordering queries
woocommerce/woocommerce pull request #22570
Opened 2019-01-25 21:34 UTC by mikejolley

Whilst testing performance I found some slow sorting methods which we can avoid with some newer filters.

Background; attributes and product cats can be sorted into a custom order. This custom sort param is stored in term meta. We previously had a custom param (menu_order) you could pass into get_terms to sort terms. We also tried to apply this default if nothing was passed. This lead to all term queries for some taxonomies to join termmeta in order to sort by the order param.

Lots of this was legacy also - back when wp_termmeta did not exist. We don't need that legacy code any more.

This PR does the following:

- Removes legacy woocomerce_termmeta table which is unused, and swaps out all calls to legacy term meta functions to the new WP ones.
- Rather than try to apply term sorting on the fly if no params are sent, this applies our sorting setting as the default sort order via the `get_terms_defaults` hook
- Use `pre_get_terms` hook to detect `menu_order` sorting param and apply to the term query. Meta sorting is now possible through WP.
- Use `terms_clauses` hook to support numeric name sorting and to improve the menu order sorting to work if meta is missing.

Because sorting is applied by default using the hooks above, we no longer need to sort the results of get_terms using manual php based sorting functions so I removed those also.

Things to test:
- Product categories. Drag and drop sort in the backend and ensure the results show on the frontend on shop page or in product cat widgets.
- Product attributes. Same as above, but also check attributes are sorted on variable product pages.
- On the backend cats/attribute screens, click a table heading to sort by something else like name. This should override our default and sort correctly.

Note; there is an update routine to migrate old meta to a consistent `order` meta key. We had things like `order_pa_color` before because terms could share meta data, but WP implemented term splitting so this was no longer needed.

2019-01-28 17:38 UTC, rodrigoprimo commented
I skimmed through this PR and here are some initial thoughts:

- A few unit tests and two e2e tests are failing. I didn't check them but judging by the name of the tests that are failing, it seems related to the changes in this PR. Could you please take a look?
- For future PRs, could you please do PHPCS changes in their own commits? Example of a commit that includes coding standards fixes: https://github.com/woocommerce/woocommerce/pull/22570/commits/8675f3195d3e36262ca160ecb0a60032fee951d6. It is much faster to review PRs when the PHPCS changes are in their own commits. 
- I added a [commit](https://github.com/woocommerce/woocommerce/pull/22570/commits/c798ea9ea89b1d0b4ee3be454fce6263e29cf41e) to fix PHPCS errors on `includes/admin/class-wc-admin-taxonomies.php`.

Once the tests are passing, I can take a closer look and review this PR.

2019-02-04 19:44 UTC, claudiulodro submitted a review, later dismissed
Seems like a reasonable change. Term meta has been in WP for years at this point, so I don't think anyone still needs the legacy tables. Code looked good, sorting worked fine in my testing, and unit tests pass.

Just curious, what sort of performance improvements did you record for this change (if any)?

Tagging this with 'Needs docs' so we remember to document the deprecations.

2019-02-07 13:47 UTC, mikejolley commented
@claudiulodro I didn't keep a record :D It was shown in the profiler - the sorting was all PHP based before so was sorting on potentially thousands of results then returning a subset.

2019-02-07 13:49 UTC, mikejolley commented on includes/wc-term-functions.php
> + * @deprecated 3.6.0 No longer used as WP supports meta based sorting.
Whoops, no I repurposed it in the end so it needs to stay hooked.

2019-02-07 14:36 UTC, claudiosanches commented on includes/wc-deprecated-functions.php
> + * @param  int    $old_term_id      Old term ID.
Missing `@deprecated` for those functions.

2019-03-05 11:51 UTC, kloon requested changes
Looks good and works, just missing a `@deprecated` param on delete_meta function docblock

2019-03-05 11:51 UTC, kloon commented on includes/admin/class-wc-admin-taxonomies.php
>  	public function delete_term( $term_id ) {
@deprecated missing?

2019-03-05 19:31 UTC, mikejolley commented
@kloon Docblock sorted and synced with master. Merge after re-review :)?

2019-03-07 13:28 UTC, kloon approved these changes

2019-03-07 16:33 UTC, merged