REST API: Add Blocks Products Controller
woocommerce/woocommerce pull request #22856
Opened 2019-02-25 22:04 UTC by timmyc

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

See #22809 for more background - this branch builds upon what was added there and includes support for the `wc-blocks/v1/products` endpoint.

### How to test the changes in this Pull Request:

1. You can use Postman to make requests to `wc-blocks/v1/products`
2. and/or run `phpunit tests/unit-tests/api/wc-blocks/products.php`

### Other information:

For https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/426

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### Changelog entry

Adds new `wc-blocks/v1` endpoint for getting product info for use in Woo Blocks

2019-02-26 17:16 UTC, ryelle reviewed
This tests out well, but the textdomain needs to be updated in all the translations, it's still `woo-gutenberg-products-block`.

2019-02-26 17:43 UTC, timmyc commented
Doh! good catch @ryelle fixed in c84cae4

2019-02-26 17:51 UTC, ryelle approved these changes
Looks good now 👍

2019-02-26 18:08 UTC, claudiosanches requested changes

2019-02-26 18:08 UTC, claudiosanches commented on includes/api/wc-blocks/class-wc-rest-blocks-products-controller.php
> +		$params['cat_operator']       = array(
We generally don't use short names on REST API, also this comes from our shortcode, I don't like to expose it here... So last move way from short names, let's change to `category_operator` and `attribute_operator`.

2019-02-26 18:19 UTC, claudiosanches commented on includes/api/wc-blocks/class-wc-rest-blocks-products-controller.php
> +			'enum'              => array( 'IN', 'NOT IN', 'AND' ),
Also those options probably can be improve here, we don't use any in LOWERCASE or even that contains spaces, let's change it to `ìn`, `not_in`, and `and`.

2019-02-26 18:20 UTC, claudiosanches commented on includes/api/wc-blocks/class-wc-rest-blocks-products-controller.php
> +			'sanitize_callback' => 'sanitize_text_field',
Also should good set the default to `in`, since it's the default behavior anyway, but need to have this documented in this schema.

2019-02-26 22:42 UTC, timmyc commented
@claudiosanches applied updates per the feedback, and ported over the tests from the blocks plugin which make assertions around those operators as well.

2019-02-26 23:31 UTC, claudiosanches approved these changes
I udated the `sanitize_callback` to `sanitize_key`, and fixed a few minor coding standards issues. All good now.

2019-02-26 23:32 UTC, merged

2019-02-27 00:15 UTC, timmyc commented
@claudiosanches thanks for the fixes and the merge 🤠