Hide 'other' payment method from invoice
woocommerce/woocommerce pull request #22889
Opened 2019-02-27 13:57 UTC by mikejolley

When you select 'Other' in the backend for the payment method, no gateway exists to look up a proper gateway title.

Therefore, we shouldn't output anything if using 'other' on invoices.

Closes #22817

To test, edit order and set the payment method to "other", send yourself an invoice, check it shows nothing after this patch.

2019-03-07 18:38 UTC, rodrigoprimo requested changes
I was not able to confirm the desired behavior happens following the test instructions. After applying this patch and changing the payment method of an order to "other", I still see the section "Payment method: other" in the invoice email. What I don't see anymore is the text "Payment via other" in the order edit page. I haven't checked, but I believe the code should be changed somewhere else to hide the "Payment method" in the invoice e-mail when using the "other" payment method?

2019-03-11 17:00 UTC, mikejolley commented
@rodrigoprimo you're right, I did the order panel. I've updated this to cover the email now.

2019-03-11 19:29 UTC, rodrigoprimo reviewed
I could confirm that after the latest change the Payment method section is not displayed in the invoice e-mail if the payment method chosen is 'other'.

~~Just one last thing that I noticed in this second review, the payment method section still shows 'other' in the order page under My Account and in the order completed e-mail (subject: "Your Woo Performance Testing order is now complete". I didn't check if this is happening in other places as well.~~

~~For consistency, should we maybe remove the payment method section when the payment method is 'other' in the two places mentioned above and check for other instances that we should change as well?~~

Edit: I tested again and couldn't reproduce the problems that I mentioned in the two paragraphs above. I probably made a mistake when testing the first time. Everything is working now. Thanks.

2019-03-13 15:00 UTC, rodrigoprimo approved these changes

2019-03-13 15:01 UTC, merged