Fix/phpcs errors
woocommerce/woocommerce pull request #22965
Opened 2019-03-07 21:49 UTC by psealock

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

phpcs fixes for touched files in Tracks project.

2019-03-08 10:45 UTC, mikejolley commented on includes/admin/class-wc-admin-setup-wizard.php
> +		// phpcs:disable WordPress.VIP.SuperGlobalInputUsage.AccessDetected, WordPress.VIP.ValidatedSanitizedInput.InputNotValidated, WordPress.VIP.ValidatedSanitizedInput.MissingUnslash, WordPress.Securit
I've just noticed all those disables... Maybe this block should be checked again. For example, unslashing is needed!

e.g.:

```
$address        = sanitize_text_field( $_POST['store_address'] );
```

to:

```
$address        = wc_clean( wp_unslash( $_POST['store_address'] ) );
```

Would you mind checking this? Also bare in mind the .VIP. rules no longer exist. I think it's .SECURITY. so they can be removed.

2019-03-08 10:48 UTC, mikejolley commented on includes/admin/class-wc-admin.php
> +			echo esc_html( $message );
Might be html in here. Probably best to echo and add exclusion rule. It's not user generated.

2019-03-08 10:50 UTC, mikejolley requested changes
Added some comments. The disables in wizard need a look.

2019-03-10 23:01 UTC, psealock commented
Thanks @mikejolley !

I updated the preview emails `$message` to not escape html and removed the wizard disables in favour of `wc_clean` and `wp_unslash`. Thanks for the tip.

2019-03-11 11:08 UTC, mikejolley approved these changes

2019-03-11 11:08 UTC, merged