Show linkout to Marketplace when there are no product metabox suggestions to display
woocommerce/woocommerce pull request #22994
Opened 2019-03-12 00:51 UTC by haszari

### Changes proposed in this Pull Request:
When a user has dismissed all the product metabox suggestions, or if there are none to display, the UI is a little confusing.

This PR shows a nice message and button linking to the marketplace so it's clear why it's there.

### How to test the changes in this Pull Request:
1. Clone this branch and get it running as your woocommerce extension in a test environment.
2. Edit a product, scroll down to metabox, click `Get more options` tab.
3. Dismiss all the suggestions – should see nice new UI.

Also, after dismissing all the suggestions, reload the page, and click on the tab.

### Screenshots

<img width="1005" alt="Screen Shot 2019-03-12 at 1 38 46 PM" src="https://user-images.githubusercontent.com/4167300/54167271-d855d900-44cd-11e9-82aa-8af8b3778883.png">

2019-03-12 11:36 UTC, kloon requested changes
Not getting the same results, in my tests after dismissing all the suggestions it first showed a blank page and then removed the tab for suggestions. Then I reloaded the edit product page for the product and the tab was still missing.

I am in the right branch https://cld.wthms.co/i0DYSJ, here is a screencast after clearing cookies and the user meta ![](https://cld.wthms.co/YLrZAG+)

2019-03-12 20:27 UTC, haszari commented
> I am in the right branch https://cld.wthms.co/i0DYSJ, here is a screencast after clearing cookies and the user meta 

Apologies @kloon – I forgot to push my last commit.

(Thanks for testing the fallback option of hiding everything though.)

2019-03-13 00:02 UTC, timmyc requested changes
This is testing well for me - just the one comment having the two sentences passed through the translate method, and all is looking good here.

2019-03-13 00:02 UTC, timmyc commented on includes/admin/marketplace-suggestions/templates/html-product-data-extensions.php
> +			<h4>Enhance your products</h4>
These two lines need to be translated.

2019-03-13 01:46 UTC, haszari commented on includes/admin/marketplace-suggestions/templates/html-product-data-extensions.php
> +			<h4>Enhance your products</h4>
Woops – now fixed.

2019-03-13 03:18 UTC, timmyc approved these changes

2019-03-13 03:18 UTC, timmyc commented
Still testing out well for me, thanks for fixing up the translations.

2019-03-13 14:30 UTC, mikejolley submitted a review, later dismissed
There is still a string missing translation functions. There is also a merge conflict so you may need to regenerate that minified file.

2019-03-13 14:30 UTC, mikejolley commented on includes/admin/marketplace-suggestions/templates/html-product-data-extensions.php
> +		<a href="https://woocommerce.com/product-category/woocommerce-extensions/?utm_source=editproduct&amp;utm_campaign=marketplacesuggestions&amp;utm_medium=product" target="blank" class="button">Browse
This button is not translatable.

2019-03-13 18:57 UTC, haszari commented
All fixed up now @mikejolley. Have rebased onto master & recompiled the js to pick up the upstream changes (hiatus in products list) & tested this is all working correctly.

2019-03-14 02:04 UTC, haszari commented
Has been re-rebased and minified js rebuilt to catch the upstream changes (https://github.com/woocommerce/woocommerce/pull/23025), totally 100% ready for merge :)

2019-03-14 07:33 UTC, kloon approved these changes
All good now, thanks!

2019-03-14 07:35 UTC, merged