Tweak: update paying customer information on payment complete
woocommerce/woocommerce pull request #23402
Opened 2019-04-19 18:29 UTC by bekarice

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The [`wc_paying_customer()` method](https://github.com/woocommerce/woocommerce/blob/0cd54b67c7653171a73759e8d7e229ffdfa4cd6a/includes/wc-user-functions.php#L189-L199) sets the paying customer meta. However, when setting the customer total spent value, [all paid statuses are used](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-customer-data-store.php#L379-L422). Setting the paying customer information, including money spent an order count, therefore seems more appropriate to do on `woocommerce_payment_complete` instead of scoping this only to `completed` orders.

### How to test the changes in this Pull Request:

1. Submit an order for an existing paying customer, but ensure it requires shipping so the order status changes to "processing".
2. Observe no `customer.updated` webhooks are sent, as the customer information is not updated at this point, even though the order has been paid for.
3. Complete the order, then observe customer webhooks are fired.
4. Repeat with these changes, and see that the customer is updated immediately with the paid order.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Update customer order and lifetime spend totals upon `payment_complete` to trigger customer.updated webhooks for paid orders.

2019-04-23 22:09 UTC, claudiosanches requested changes
To run `woocommerce_payment_complete` need to use `$order->payment_complete()`, but this don't happens in the admin interface, so this change will stop filling customer information when changing the status to `complete` on the admin.

2019-04-24 16:27 UTC, bekarice commented
@claudiosanches great point -- do you think it makes sense to fire on both actions? I don't see any downside other than the fact that it sends a duplicate webhook for orders that move directly from pending -> completed

2019-04-30 01:43 UTC, claudiosanches commented
@bekarice we could avoid duplicated webhooks change it:

```php
	if ( $customer_id > 0 && 'shop_order_refund' !== $order->get_type() ) {
		$customer = new WC_Customer( $customer_id );
		$customer->set_is_paying_customer( true );
		$customer->save();
	}
```

to:


```php
	if ( $customer_id > 0 && 'shop_order_refund' !== $order->get_type() ) {
		$customer = new WC_Customer( $customer_id );

		if ( ! $customer->get_is_paying_customer() ) {
			$customer->set_is_paying_customer( true );
			$customer->save();
		}
	}
}
```

We only need to set it one time anyway.

2019-07-09 18:41 UTC, peterfabian commented
@bekarice would you like to update the PR or are you fine if we take over?

2019-07-10 22:35 UTC, bekarice commented
@peterfabian whoa totally missed that ping, sorry about this! I'm pushing that suggested change now, thanks for the reminder 🍻

2019-07-12 13:13 UTC, rodrigoprimo approved these changes
LGTM

2019-07-12 13:15 UTC, merged