When the user has not added any address on its account, change wording to "Add" instead of "Edit" in the link
woocommerce/woocommerce pull request #23532
Opened 2019-04-26 15:44 UTC by Mahjouba91

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

It makes more sense to have a correct action wording, instead of using "Edit" whereas there is not any address yet.

2019-04-26 22:05 UTC, claudiosanches requested changes
Thanks for your help!
Just one small change to be made and then I'll be good to go.

2019-04-26 22:05 UTC, claudiosanches commented on templates/myaccount/my-address.php
> +			<?php if ( $address ) : ?>
We could save a few lines of code, replacing:

```php
<?php if ( $address ) : ?>
    <a href="<?php echo esc_url( wc_get_endpoint_url( 'edit-address', $name ) ); ?>" class="edit"><?php _e( 'Edit', 'woocommerce' ); ?></a>
<?php else: ?>
    <a href="<?php echo esc_url( wc_get_endpoint_url( 'edit-address', $name ) ); ?>" class="edit"><?php _e( 'Add', 'woocommerce' ); ?></a>
<?php endif; ?>
```
With:
```php
<a href="<?php echo esc_url( wc_get_endpoint_url( 'edit-address', $name ) ); ?>" class="edit"><?php echo $address ? esc_html__( 'Edit', 'woocommerce' ) : esc_html__( 'Add', 'woocommerce' ); ?></a>
```

2019-04-27 10:58 UTC, Mahjouba91 commented
Hey, Thanks for your review, I have applied it.

2019-04-29 21:44 UTC, claudiosanches approved these changes
Looks great, thanks for your help!

2019-05-10 09:42 UTC, merged