add filter to allow disabling endpoint 404 behavior, per #23622
woocommerce/woocommerce pull request #23660
Opened 2019-05-09 00:52 UTC by thomasplevy

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added a filter to allow developers to easily disable the 404 behavior for endpoints accessed outside of the account page, per #23622 

### How to test the changes in this Pull Request:

1. Created a page with a child page that has the slug "downloads"
2. Prior to this change that page will 404 (confirming that the 404 status works as expected
3. After this change the 404 still occurs
4. Adding the following code to the functions.php file of a theme causes the page to be accessible (with no 404): `add_filter( 'woocommerce_account_endpoints_on_wrong_page_not_found', '__return_false' );`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them? See #23622
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Feature: Add filter woocommerce_account_endpoints_on_wrong_page_not_found to disable endpoint 404s when accessed outside the account page.

2019-05-09 21:00 UTC, claudiosanches requested changes
Looks good, but let's change this filter name to `woocommerce_account_endpoint_page_not_found`.

2019-05-09 22:51 UTC, thomasplevy commented
> Looks good, but let's change this filter name to woocommerce_account_endpoint_page_not_found.

updated!

Should I open another issue to address the first part of #23622? This PR will only add a filter to help me as a developer ensure my plugin's shared endpoints still work after WC 3.6, it will not resolve issues with child pages sharing a slug with a WC endpoint.

2019-05-10 15:50 UTC, claudiosanches approved these changes
Thanks for your help!

2019-05-10 15:50 UTC, merged

2019-05-10 15:55 UTC, thomasplevy commented
@claudiosanches 

Glad to help but can you let me know how you'd like me to handle the first part of issues #23622?

2019-05-10 18:13 UTC, claudiosanches commented
@thomasplevy yes, please, feel free to submit Pull Request, I'll happy to test and help you.