Add different new hooks for mini cart and cart
woocommerce/woocommerce pull request #23678
Opened 2019-05-10 15:39 UTC by Mahjouba91

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #23545 .

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2019-05-10 15:41 UTC, Mahjouba91 commented
There is no need to add a woocommerce_after_cart_collaterals since there is already a woocommerce_after_cart that can be used.

2019-05-22 23:56 UTC, claudiosanches requested changes
I just reviewed and there's a few things to improve, but only small things, in general looks good.

Thanks for your help!

2019-05-22 23:56 UTC, claudiosanches commented on templates/cart/cart.php
> +<?php do_action( 'woocommerce_before_cart_collaterals' ); ?>
This requires to bump this template version to 3.7.

2019-05-22 23:56 UTC, claudiosanches commented on templates/cart/mini-cart.php
> +	<?php do_action( 'woocommerce_widget_shopping_cart_after_buttons' ); ?>
Also need to increase this template version.

2019-05-22 23:56 UTC, claudiosanches commented on templates/cart/mini-cart.php
> +	<p class="woocommerce-mini-cart__total total"><?php do_action( 'woocommerce_widget_shopping_cart_total' ); ?></p>
Missing docblock here saying about calling `woocommerce_widget_shopping_cart_subtotal` and the priority, like we does for another actions like:

```php
<p class="woocommerce-mini-cart__total total"><?php 
    /**
     * woocommerce_widget_shopping_cart_total hook.
     *
     * @hooked woocommerce_widget_shopping_cart_subtotal - 10
     */
    do_action( 'woocommerce_widget_shopping_cart_total' );
?></p>
```

2019-07-04 07:27 UTC, kloon commented
@Mahjouba91 just checking if you saw @claudiosanches comments? If you can implement that we can get this reviewed and merged for the 3.7 release. Thanks!

2019-07-14 17:39 UTC, kloon commented
Closing in favor of #24145

2019-07-14 17:39 UTC, closed without merging