Deprecate get_used_coupons in favor of get_used_coupon_codes
woocommerce/woocommerce pull request #23689
Opened 2019-05-13 12:45 UTC by kloon

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR introduces WC_Abstract_Order::get_used_coupon_codes which replaces WC_Abstract_Order::get_used_coupons. The name of the later just does not make sense since only codes are returned and not the actual coupon objects. This also paves way for #23663 which introduces a new get_coupons method same as we have for other line item types already.

### How to test the changes in this Pull Request:

1. Make sure unit tests pass

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Add WC_Abstract_Order::get_used_coupon_codes method to replace deprecated WC_Abstract_Order::get_used_coupons

2019-05-13 16:10 UTC, claudiosanches requested changes

2019-05-13 16:10 UTC, claudiosanches commented on includes/abstracts/abstract-wc-order.php
> +	 * @deprecated 3.7.0 - Replaced with better named method to reflect the actual data being returned.
We should move this method to `WC_Abstract_Legacy_Order`.

2019-05-14 01:01 UTC, danielbitzer commented
I'd suggest naming the new method simply: `get_coupon_codes`. The word used is implied and my PR (https://github.com/woocommerce/woocommerce/pull/23663) adds a `WC_Abstract_Order::get_coupons()` method which does not contain the word used but will return the same coupons. There is a slight potential for confusion between what is a 'used coupon code' vs a 'coupon code'.

2019-05-14 15:46 UTC, claudiosanches approved these changes
LGTM!

2019-05-15 13:34 UTC, merged

2020-08-03 07:28 UTC, antondrob commented
Update docs please https://docs.woocommerce.com/wc-apidocs/source-class-WC_Abstract_Order.html#773-788