Normalize register/login submit button css classes
woocommerce/woocommerce pull request #23701
Opened 2019-05-14 11:58 UTC by sandrodz

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

CSS classname for register and login button had a discrepency. Login button had `woocommere-button` and register had `woocommerce-Button` notice the capital B. Besides register was missing a specific selector.

### Changelog entry

> Normalize register/login submit button css classes

2019-07-11 13:09 UTC, vedanshujain commented
WooCommerce actually use `woocommerce-Button` convention in many places, see https://github.com/woocommerce/woocommerce/search?q=woocommerce-Button&unscoped_q=woocommerce-Button . So this is not a typo, and is intended.

Also since `register` have name attribute, you can use a selector like so `.woocommerce-Button[name='register']` to select the button. 

I am closing this PR, but feel free to re-open if I missed something.

2019-07-11 13:26 UTC, sandrodz commented
@vedanshujain Compare it to login: https://github.com/sandrodz/woocommerce/blob/7abe7e5712a1c0629d7c34bfe76ce9979ad5def8/templates/myaccount/form-login.php#L54

My intento was to align it with login button which clearly has a different naming structure. And has a specific selector.

2019-07-11 13:43 UTC, sandrodz commented
There are many ways to target these buttons, what I am proposing is not out of necessity - but out of love of standardization.

2019-07-12 15:33 UTC, vedanshujain commented
Ah ok. Changing from `woocommerce-Button` to `woocommerce-button` may break the back compat is case some one is using this selector from Javascript to select the button. 

What do you think about keeping `woocommerce-Button` as it is, but add the selector that you have proposed, which follows the WP Core standards

2019-07-30 20:22 UTC, claudiosanches requested changes

2019-07-30 20:22 UTC, claudiosanches commented on templates/myaccount/form-login.php
> +				<button type="submit" class="woocommerce-button button woocommerce-form-register__submit" name="register" value="<?php esc_attr_e( 'Register', 'woocommerce' ); ?>"><?php esc_html_e( 'Register', '
Please keep `woocommerce-Button` for backwards compatibility.

2019-07-30 20:22 UTC, claudiosanches commented on templates/myaccount/form-login.php
> +				<button type="submit" class="woocommerce-button button woocommerce-form-register__submit" name="register" value="<?php esc_attr_e( 'Register', 'woocommerce' ); ?>"><?php esc_html_e( 'Register', '
Just let as `woocommerce-Button woocommerce-button button woocommerce-form-register__submit` and it will be fine.

2019-07-31 23:39 UTC, claudiosanches approved these changes
Thanks for your help!

2019-09-03 11:45 UTC, merged