fix#23722 Signature mismatch of get_formatted_order_total
woocommerce/woocommerce pull request #23723
Opened 2019-05-15 13:28 UTC by Mr-AjayM

### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #23722 .

### How to test the changes in this Pull Request:

1. Go to 'plugins\woocommerce\includes\abstracts\abstract-wc-order.php'
2. Find the method call get_formatted_order_total and method signature.

> updated the get_formatted_order_total method signature.

2019-05-15 16:08 UTC, claudiosanches requested changes
Thanks for your help. Just need to do a small fix and this PR will be ready to go.

2019-05-15 16:08 UTC, claudiosanches commented on includes/abstracts/abstract-wc-order.php
> +	public function get_formatted_order_total( $tax_display ) {
It's missing default value and `$display_refunded`,

This is how suppose to be:

```php
	/**
	 * Gets order total - formatted for display.
	 *
	 * @param string $tax_display      Type of tax display.
	 * @param bool   $display_refunded If should include refunded value.
	 *
	 * @return string
	 */
	public function get_formatted_order_total( $tax_display = '', $display_refunded = true ) {
```

2019-05-16 04:30 UTC, Mr-AjayM commented
Hello @claudiosanches 

Thanks for sharing your inputs for this!

I have updated the changes, kindly review it and let me know if we need to do any additional changes for this.

Thanks & Regards,
Aj

2019-05-16 09:01 UTC, kloon commented
Curious if this was throwing an error, and if so how to replicate that? The parameters are not used anywhere in the function in WC_Abstract_Order so seems useless to include them?

The function is already extended in WC_Order which extends WC_Abstract_Order so when it is called in WC_Abstract_Order it is actually calling the function in WC_Order.

2019-05-16 10:59 UTC, Mr-AjayM commented
@kloon It's showing me this warning when running the PHPCS with the WooCommerce Core standards. I am not sure either solve by removing the parameter when calling the function of adding the parameters in the definition of the function.  

That also makes sense that we are not using any parameter in the method as well. Let's wait for other feedback as well.

2019-05-16 15:49 UTC, claudiosanches commented
@kloon depends on the PHP version and configuration, there's changes on it on PHP 7 too, see: https://stackoverflow.com/questions/36079651/silence-declaration-should-be-compatible-warnings-in-php-7
Also we have some fixes like that in the past: https://github.com/woocommerce/woocommerce/pull/3420

2019-05-16 20:03 UTC, claudiosanches commented
@Mr-AjayM what PHP version are you using on your environment?

2019-05-17 04:24 UTC, Mr-AjayM commented
@claudiosanches I am on PHP version 7.0.10 in my local environment.

2019-06-18 19:07 UTC, claudiosanches commented
Testing it better, in fact this change may cause a PHP warning, if extending this class:

```
PHP Warning:  Declaration of WC_Order::get_formatted_order_total() should be compatible with WC_Abstract_Order::get_formatted_order_total($tax_display = '', $display_refunded = true) in wp-content/plugins/woocommerce/includes/class-wc-order.php on line 0
```

We can't reproduce this the reported error, so let's leave close for now, if we get more reports like that, we'll update the abstract class.
Thanks for your help.

2019-06-18 19:07 UTC, closed without merging