fixed availability schema protocol
woocommerce/woocommerce pull request #23774
Opened 2019-05-21 07:12 UTC by connorhu

As you can see in the example, the scheme only can be on http:
https://schema.org/InStock
The Google Search console has also marked it invalid.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

2019-05-21 15:01 UTC, claudiosanches requested changes
All our entries for schema.org uses HTTPS, so if it's required to be fixed, so is missing more places.

>  The Google Search console has also marked it invalid.

Can you show me?
Screenshot or a page that I can test on https://search.google.com/structured-data/testing-tool/u/0/ ?

2019-05-21 15:15 UTC, claudiosanches commented
@connorhu both don't help, since is not in english.

2019-05-21 15:48 UTC, connorhu commented
![image](https://user-images.githubusercontent.com/1845575/58110836-90031780-7bf0-11e9-8847-c04481267ad8.png)

2019-05-21 16:03 UTC, claudiosanches commented
Still using `https://search.google.com/structured-data/testing-tool/u/0/` doesn't shows any warning like that... Google have been updating it in the past months, and we are patching those changes, still since is not showing in the structured data test site, let's wait a little more before try something.
You can remove this HTTPS using the `woocommerce_structured_data_product` filter.
Thanks for your help, I'll keep an eye on it.

2019-05-21 16:06 UTC, connorhu commented
As I said don't use the Structured data testing tool, because it's not so up-to-date. For testing use the new version of search console. http://search.google.com/search-console

2019-05-22 21:05 UTC, claudiosanches approved these changes
Thanks for your help!

2019-05-22 21:07 UTC, merged