Avoid attempting to cache expired sessions
woocommerce/woocommerce pull request #23863
Opened 2019-06-03 21:46 UTC by Jon007

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Currrently get_session() attempts to cache a session even if it is already expired.
The current code used passes negative expiry seconds to wp_cache_add() if the session expired in the past:
`wp_cache_add( $this->get_cache_prefix() . $customer_id, $value, WC_SESSION_CACHE_GROUP, $this->_session_expiration - time() );`

Depending on the caching layers used this will give errors in the logs such as:
ERR invalid expire time in setex in /var/www/html/wp-content/plugins/redis-cache/includes/predis/src/Client.php:370
as reported on: https://wordpress.org/support/topic/error-when-trying-to-get-a-get-a-cache-not-available/

The solution proposed here is to not cache sessions which are expired by testing if the cache expiry seconds would be negative.

### How to test the changes in this Pull Request:

It can be tested that the change proposed is harmless.
What is more difficult is to reproduce the original error condition which is along the lines of:
1.  never clear sessions so there is a build up of expired sessions..
2. this error may start to appear in the logs

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.
Avoid caching expired sessions (negative expiry causing errors in some caching modules).

2019-06-06 17:04 UTC, Reddog1971 approved these changes

2019-06-18 18:53 UTC, claudiosanches requested changes

2019-06-18 18:53 UTC, claudiosanches commented on includes/class-wc-session-handler.php
> +			if ($cache_duration > 0){
Need to fix coding standards here, please change to:

```php
if ( 0 < $cache_duration ) {
```

2019-06-18 20:15 UTC, Jon007 reviewed
ok

2019-06-18 20:18 UTC, Jon007 reviewed
think that is done now. . .

2019-06-19 23:12 UTC, claudiosanches approved these changes
Thanks for your help!

2019-06-27 13:15 UTC, merged