Prevents taxes columns from being removed when the order is no longer editable
woocommerce/woocommerce pull request #23884
Opened 2019-06-07 13:11 UTC by claudiosanches

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Currently we are allowing to remove taxes columns when an order is no longer editable (orders on processing or complete statuses), this patch will prevent this from happens.

Closes #23875.

### How to test the changes in this Pull Request:

1. Enable taxes, those need to be excluded from the products prices.
2. Place an order, and move the status to processing or complete.
3. Check that it's possible to remove (just mouse hover under the tax column to see the "x" icon).
4. Apply this PR, and then check that the "x" is no longer available.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [X] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Prevents taxes columns from being removed when the order is no longer editable

2019-06-20 10:13 UTC, kloon requested changes
While this removes the button, you can still call the ajax endpoint manually and it will remove the order. I suggest another check is added in WC_Ajax::remove_order_tax to make sure the order is editable before proceeding to remove the taxes.

2019-06-20 13:02 UTC, kloon commented
@claudiosanches I made some changes to the branch to include the check in the ajax function. Let me know if you are happy with that.

2019-06-24 15:25 UTC, claudiosanches commented
@kloon looks fine for me, I haven't included something like that because all other ajax endpoints doesn't include any check like that. Not sure if we should include in all or not.

2019-07-04 07:25 UTC, kloon approved these changes
This is good to go, keeping the check in wc-ajax.php, don't think it does any harm to have that extra check in place.

2019-07-04 07:25 UTC, merged