Allow notice type changes when updating cart contents
woocommerce/woocommerce pull request #24021
Opened 2019-06-27 14:12 UTC by AndyMardell

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

On add to cart, remove from cart or update cart, allow notice type to be changed from default 'success'.

Use case: I want to change the status of cart notifications from default 'success' notice type in order to apply a different style to the notification. You can already add a new notice_type 'added' using the `woocommerce_notice_types` filter, but you can't then use this new notice_type on cart notifications.

### How to test the changes in this Pull Request:

1. Add this to functions.php

```function theme_notice_types() {
	return array(
		'error',
		'success',
		'notice',
		'added',
	);
}
add_filter( 'woocommerce_notice_types', 'theme_notice_types' );

function theme_add_to_cart_notice_type() {
	return 'added';
}
add_filter( 'wc_add_to_cart_notice_type', 'theme_add_to_cart_notice_type' );
```

2. Add the following to `wp-content/themes/mytheme/woocommerce/notices/added.php`

```<?php foreach ( $messages as $message ) : ?>
	<div class="woocommerce-added" role="alert">
		<?php
			echo wc_kses_notice( $message );
		?>
	</div>
<?php endforeach; ?>
```

3. Add to cart and you should see a notice with the class of `woocommerce-added`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable? N/A
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Allow notice type changes when updating cart contents

2019-07-08 22:00 UTC, claudiosanches requested changes

2019-07-08 22:00 UTC, claudiosanches commented on includes/wc-cart-functions.php
> +		wc_add_notice( $message, apply_filters( 'wc_add_to_cart_notice_type', 'success' ) );
We don't allow `wc_` prefixes for hooks.
Need to update to `woocommerce_add_to_cart_notice_type`.

2019-07-09 20:25 UTC, AndyMardell commented
@claudiosanches Renamed - thanks!

2019-07-10 17:06 UTC, claudiosanches approved these changes
Looks great, thanks for your help!

2019-07-14 19:06 UTC, merged