Update/avoid ajax request on checkout page load
woocommerce/woocommerce pull request #24265
Opened 2019-07-30 07:17 UTC by Rasheed08

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2019-07-30 07:18 UTC, Rasheed08 commented on assets/js/frontend/checkout.js
> +			$( function() {
NAGEL

2019-07-30 07:19 UTC, Rasheed08 commented
https://shopnagel.wordpress.com/

2019-07-30 19:34 UTC, claudiosanches requested changes
It's missing a description, steps to test, if this fix an issue or the reason for this change.

2019-07-31 00:27 UTC, dechov commented
@claudiosanches It's an enhancement – description in https://github.com/woocommerce/woocommerce/pull/24271.

2019-07-31 00:27 UTC, closed without merging

2019-08-02 21:53 UTC, claudiosanches commented
@dechov thanks for opening a new PR with full details.