Coupon expiry date tooltip to help understand behaviour
woocommerce/woocommerce pull request #24394
Opened 2019-08-13 08:46 UTC by nicomollet

Help understand if the date is included or excluded when addind a coupon expiry date.
In the current state, the coupon expires at 00:00:00 of the submitted date.

### All Submissions:

* [ x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added a tooltip in the "Coupon expity date" field, in backend coupon form.

2019-08-13 12:56 UTC, nicomollet commented
I had to apply coding standards to the whole file, just for one little new string.

2019-10-01 21:22 UTC, claudiosanches requested changes
While you are trying to fix coding standards some bugs was been introduced, if you like, you can start a new Pull Request proposing only the changes you made in the description, I can fix those coding standards issues later.

2019-10-01 21:22 UTC, claudiosanches commented on includes/admin/meta-boxes/class-wc-meta-box-coupon-data.php
> -		</div>
It isn't correct this change.
We need to close `<div id="coupon_options" class="panel-wrap coupon_data">` in here. But this is not what is happening anymore.

2019-10-01 21:22 UTC, claudiosanches commented on includes/admin/meta-boxes/class-wc-meta-box-coupon-data.php
> +		if ( wp_verify_nonce( wp_unslash( $_POST['woocommerce_meta_nonce'] ), 'woocommerce_save_data' ) ) { // @codingStandardsIgnoreLine.
We already check for nonces before hit this method, so no need to include it again.

2019-10-02 09:49 UTC, nicomollet commented
Closing this PR and made a new one with just the fix I need:
https://github.com/woocommerce/woocommerce/pull/24749

2019-10-02 09:49 UTC, closed without merging