Add new hook for add-order-item
woocommerce/woocommerce pull request #24518
Opened 2019-08-28 11:59 UTC by pinalj

Added a new hook for validations in the add_order_item() called in
WC->Orders->Add/Edit Orders.

Allow plugins to perform validations/changes to the order before a product is added to the order.

2019-08-28 16:07 UTC, claudiosanches requested changes
Thanks for your help! Just a minor change before merge.

2019-08-29 07:11 UTC, pinalj commented on includes/class-wc-ajax.php
> +				$check = apply_filters( 'woocommerce_add_item_check', $product, $order, $qty );
Thanks, updated the hook name as suggested.

2019-08-29 19:47 UTC, claudiosanches approved these changes
Thanks for your contribution!

2019-08-29 19:48 UTC, merged

2019-08-31 15:32 UTC, TimothyBJacobs commented
@claudiosanches This doesn't seem right, if a plugin filters to return a `WP_Error`, any later filters won't be able to determine what the product is. Shouldn't there be a separate first parameter for the `WP_Error` check?

2019-10-02 15:27 UTC, claudiosanches commented
@TimothyBJacobs no need for an extra parameter, also this will stop immediately.

2019-10-02 15:33 UTC, TimothyBJacobs commented
I'm not seeing that.

The filter is `$check = apply_filters( 'woocommerce_ajax_add_order_item_validation', $product, $order, $qty );`.

If I have two plugins, and the first does.

```
add_filter( 'woocommerce_ajax_add_order_item_validation', function( $product_or_error, $order ) {
    if ( ! isset( $_POST['some_key'] ) && $product->get_meta() ) {
        return new WP_Error();
    }

    return $product_or_error;
}, 10, 2 );
```

```
add_filter( 'woocommerce_ajax_add_order_item_validation', function( $product_or_error, $order ) {
    if ( ! isset( $_POST['some_key'] ) && $product_or_error->get_meta() ) {
        return new WP_Error();
    }

    return $product_or_error;
}, 10, 2 );
```

Won't this now fatal because `$product_or_error` is a `WP_Error` instance from the first filter that applies?

2019-10-02 18:44 UTC, claudiosanches commented
@TimothyBJacobs you need to check if is an `WP_Error` instance instead of a `WP_Product` instance.

2019-10-02 18:48 UTC, TimothyBJacobs commented
Yes, that will avoid the fatal, but now I no longer have access to the product. And if I am validating based on some product attribute, I won't be able to.

Adding a separate parameter is how WC works elsewhere. For instance:

```
$validation_error  = new WP_Error();
$validation_error  = apply_filters( 'woocommerce_process_registration_errors', $validation_error, $username, $password, $email );
```

```
$validation_error = new WP_Error();
$validation_error = apply_filters( 'woocommerce_process_login_errors', $validation_error, $creds['user_login'], $creds['user_password'] );
```

```
$passed_validation = apply_filters( 'woocommerce_add_to_cart_validation', true, $item, $quantity );
```

```
$passed_validation = apply_filters( 'woocommerce_update_cart_validation', true, $cart_item_key, $values, $quantity );
```

2019-10-02 18:54 UTC, claudiosanches commented
@TimothyBJacobs please feel free to submit a Pull Request, if you are so strongly against this filter, we can change, no problem.