Use isset for data['payment_method']
woocommerce/woocommerce pull request #24627
Opened 2019-09-13 03:33 UTC by twocs

Some create_order calls in the backend, for example using WooCommerce Deposits, may not have a value for payment_method. For example, an order may not require payment. This triggers a PHP Notice. 

I see that isset is used for other times that $data['payment_method'] is used, even in this file in the function get_posted_data() : 646.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Check that data is set before trying to use it to access another object.

### How to test the changes in this Pull Request:

1. Create_order without setting $data['payment_method']
2. No PHP notice will be emitted
3. All other orders should proceed

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

2019-09-30 13:33 UTC, kloon requested changes
I do not think we should just set it to a blank string when no payment_method is passed, the defaults from the datastore should cover this already.

I think perhaps you should mimic what `WC_Checkout::validate_checkout` does and wrap the $order->set_payment_method inside a needs_payment check?

2019-10-02 17:07 UTC, claudiosanches commented
This also may cause a backwards compatibility issue, if having some kind of dynamic payment method.

2019-12-05 16:00 UTC, claudiosanches commented
Closing since you can set an empty value for `payment_method` like `deposit`, this is render correct and avoid any error.

2019-12-05 16:00 UTC, closed without merging

2019-12-08 05:24 UTC, twocs commented
Can you please provide refernce to the WooCommerce guidelines that suggest that even when in the same dile error catching is worked out, you still let some random conditions through because a user could somehow guess that they could use an arbitrary value to fix the errors caused by WooCommerce guidelines?

If there is no such rule, don't lock in inflexibility to the core. It's awful.