Update the message on View Order use myaccount Title
woocommerce/woocommerce pull request #24643
Opened 2019-09-16 18:57 UTC by garrett-eclipse

Hello,

This little PR updates the message on the View Order screen when the order isn't viewable by allowing the 'My account' link to use the actual title of the page set for myaccount.

Cheers

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updates the error message when on View Order screen but viewing an invalid order or one you don't have permissions to. The existing implementation provides My Account link with the text translatable. This PR updates the title of the link to use the page title of the myaccount page.

### How to test the changes in this Pull Request:

1. Implement the PR.
2. Go to the View Order screen and enter an invalid ID.
3. Change you My Account page to use an alternate title, then go back to step #2 and confirm the link uses the new title.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?

### Changelog entry

Updates the Invalid Order message on the View Order screen to use the actual title of the myaccount page rather than the text string 'My Account'.

2019-09-27 11:45 UTC, kloon requested changes
There are other places where the link is used and the labels are hardcoded as My Account. I am not sure we should be changing this to the page title. Any specific reasons why you would think this would be beneficial?

I can think of a couple of scenarios where existing users would be inconvenienced by this change causing links to all of a sudden display different text than what they are used to.

cc @woocommerce/proton for more feedback

2019-09-30 17:39 UTC, garrett-eclipse commented
Thanks @kloon I see what you're saying there. 

I just found it frustrating to have to go through so many files to change from My Account to My Portal. Would be nice to just change the page title and have that change affect all links to the page.

I would wager in most cases a user has updated the page title they would expect it to appear as the new page title instead of as 'My Account' still. Right now you have to change the page title and then scrub through files to find all other instances.

2019-09-30 17:55 UTC, rodrigoprimo commented
I don't have a strong opinion on what is the best title to use for the "My account" page. But regardless of that, I agree that we can't merge this PR as is as it will change the behavior for existing users and that could cause some inconveniences.

2019-09-30 18:14 UTC, garrett-eclipse commented
Sounds like it'll cause issues and not sure how else to approach so going to close this out.

2019-09-30 18:14 UTC, closed without merging