Fix for compatibility with WPML
woocommerce/woocommerce pull request #24657
Opened 2019-09-20 09:33 UTC by miguelfspinto

With WPML, query parameter lang is added on home_url which means that geolocalization.min.js will not find any href with that query parameter. We need to remove this parameter from the home_url, otherwise it will not match the regex for the query in the JS function.

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2019-09-27 11:37 UTC, kloon requested changes
Can you just add a comment to the code to explain why you are doing this otherwise it won't make much sense when reading the code.

2019-09-27 11:49 UTC, miguelfspinto commented
You need to remove all query parameters in home_url. Otherwise, the script geolocation will not append the hash in any url with the format like "domain.xxx/path1/path2/xxx" because with your look for domains that start with domain.xxx?query=1&query2=2

2019-09-27 11:50 UTC, miguelfspinto commented
> You need to remove all query parameters in home_url. Otherwise, the script geolocation will not append the hash in any url with the format like "domain.xxx/path1/path2/xxx" because with your look for domains that start with domain.xxx?query=1&query2=2



> Can you just add a comment to the code to explain why you are doing this otherwise it won't make much sense when reading the code.

You need to remove all query parameters in home_url. Otherwise, the script geolocation will not append the hash in any url with the format like "domain.xxx/path1/path2/xxx" because with your look for domains that start with domain.xxx?query=1&query2=2

2019-09-27 11:51 UTC, kloon commented
@miguelfspinto sorry should have been clearer, I mean can you please add an inline comment to the code.

While we have this PR for reference if you are reading the actual codebase and come across this line there is no indication as to why this is there.

2019-09-27 13:24 UTC, miguelfspinto commented
> @miguelfspinto sorry should have been clearer, I mean can you please add an inline comment to the code.
> 
> While we have this PR for reference if you are reading the actual codebase and come across this line there is no indication as to why this is there.

Done. Let me know if you want me to change the comment format or text.

2019-09-30 12:57 UTC, kloon commented
Thanks for your contribution @miguelfspinto. I have cherry-picked your changes and just did some coding standards fixes in #24722 to replace this since we are in a bit of a tight squeeze to get changes merged for 3.8.

In the future it would help a lot if you can ensure all your changes pass the coding standards tests. Be sure to run composer install in your local development environment so it installs the pre-commit hooks and checks which should give your errors before actually allowing you to commit.

2019-09-30 12:57 UTC, closed without merging