Added delimiter property with filter
woocommerce/woocommerce pull request #24759
Opened 2019-10-03 02:47 UTC by rafsuntaskin

Added support for custom delimiter #24579

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Added support for custom delimiter in CSV export

Closes #24579

### How to test the changes in this Pull Request:

1. 
2.
3.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry
Created new filter to change separator string in while exporting CSV files

2019-10-04 21:32 UTC, claudiosanches requested changes
Thanks for your contribution, there's only two minor issues to fix before we can merge it.

2019-10-04 21:32 UTC, claudiosanches commented on includes/export/abstract-wc-csv-exporter.php
> +	protected $delimiter = ",";
Please, use single quotes in here, since not required double quotes.

2019-10-04 21:32 UTC, claudiosanches commented on includes/export/abstract-wc-csv-exporter.php
> +	 * @return String
This should be in lowercase, just change to `string`

2019-10-07 14:49 UTC, claudiosanches approved these changes
Thanks for your contribution!

2019-10-08 09:23 UTC, merged

2020-09-11 08:33 UTC, julientora commented
Hey there. As Jany-M asked before, it would be very appreciated to have this option enabled...

2020-09-11 13:40 UTC, rafsuntaskin commented
@Jany-M @julientora ,

It is a filter added so you need a custom snippet to alter the default delimiter.
You can try the following:
`
add_filter( 'woocommerce_csv_export_delimiter', function ( $delimiter ) {

	// set your custom delimiter
	$delimiter = ';';

	return $delimiter;
} );
`

2020-09-11 15:09 UTC, julientora commented
@rafsuntaskin I really appreciate your help, thank you. Unfortunately, it doesn't work. 
Are you sure it is a filter and it is REALLY implemented in the very last version ?

2020-09-11 22:00 UTC, rafsuntaskin commented
Hi @julientora ,

Sorry about that, I placed the wrong filter. It needs to be `product` instead of `CSV` while we are exporting products.

I have updated the snippet so it should work fine now.

Thanks
Rafsun

2020-09-14 09:33 UTC, julientora commented
Hi @rafsuntaskin ! It works perfectly. Thank you for your help.

2022-03-10 15:37 UTC, vhngroup commented
Thanks, it's great for me. 
i copy the content from this link https://gist.github.com/rafsuntaskin/8225bc350a968817734abd4b889542a6 in file functions.php in my child theme. "remember close the the PHP sintax ?>"

2024-02-14 10:22 UTC, Tekwar87 commented
Hello,

This code is used to change the column delimiter.

But is there something to change the separator of attribute values?

It always uses "," and some of my values also use "," so I can't use Excel's replace all for example.

2024-02-14 15:22 UTC, Jany-M commented
@Tekwar87 check the snippet that @rafsuntaskin provided, at [https://gist.github.com/rafsuntaskin/8225bc350a968817734abd4b889542a6](https://gist.github.com/rafsuntaskin/8225bc350a968817734abd4b889542a6)