Fix/24791
woocommerce/woocommerce pull request #24793
Opened 2019-10-09 08:33 UTC by xristos3490

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Replaced the use of `stripslashes` with `stripslashes_deep` when dealing with non-scalar setting values under the `WC_Admin_Settings::get_option` method.

Closes #24791 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Use of recursive stripslashes function when escaping admin settings values #24791

2019-10-14 15:13 UTC, claudiosanches requested changes

2019-10-14 15:13 UTC, claudiosanches commented on includes/admin/class-wc-admin-settings.php
> +				$option_value = array_map( 'stripslashes_deep', $option_value );
This code can be more clean, like:

```php
$option_value = wp_unslash( $option_value );
```

2019-10-15 09:38 UTC, xristos3490 commented on includes/admin/class-wc-admin-settings.php
> +				$option_value = array_map( 'stripslashes_deep', $option_value );
Nice catch @claudiosanches

2019-10-16 18:41 UTC, claudiosanches approved these changes
Thanks for your contribution!

2019-10-16 18:41 UTC, merged