remove unnecessary codes
woocommerce/woocommerce pull request #24907
Opened 2019-10-26 18:08 UTC by princeahmed

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2019-10-27 11:34 UTC, claudiosanches requested changes
Please fill the issue template, it's missing arguments about this change, why it suppose to be merged, also missing changelog, and instructions to test.

2019-12-26 07:33 UTC, vedanshujain approved these changes
LGTM!

2019-12-26 07:44 UTC, vedanshujain commented
@claudiosanches looks like you need to approve before it can be merged.

2020-01-30 18:31 UTC, claudiosanches commented
Bug introduced in https://github.com/woocommerce/woocommerce/commit/72c10bdd33ebc8ed3de200acf1493900dae98361

2020-01-30 18:31 UTC, claudiosanches approved these changes

2020-01-30 18:32 UTC, merged

2020-01-30 18:32 UTC, claudiosanches commented
Just a small change in the code, there's no need for a changelog.