detect when add to cart change state
woocommerce/woocommerce pull request #25009
Opened 2019-11-09 23:59 UTC by miguelfspinto

hooks events when add to cart change state

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2019-11-20 09:48 UTC, kloon submitted a review, later dismissed
Hi @miguelfspinto 

This PR lacks a lot of contexts, could you please edit the PR and fill out the template provided so we know what you are trying to solve with this as well as how to test this and a changelog description.

Thanks!

2019-11-20 15:44 UTC, miguelfspinto commented
> Hi @miguelfspinto
> 
> This PR lacks a lot of contexts, could you please edit the PR and fill out the template provided so we know what you are trying to solve with this as well as how to test this and a changelog description.
> 
> Thanks!

done.

2020-01-17 15:35 UTC, miguelfspinto commented
> Hi @miguelfspinto
> 
> This PR lacks a lot of contexts, could you please edit the PR and fill out the template provided so we know what you are trying to solve with this as well as how to test this and a changelog description.
> 
> Thanks!

Hi @kloon , can you confirm that everything is fine?

2020-03-18 09:42 UTC, miguelfspinto commented
Can you please add feedback this topic?

2020-03-31 19:27 UTC, claudiosanches requested changes
Those events are related to variations, so probably better update the `woocommerce_add_button_change_state` name to indicate it.

2020-03-31 19:45 UTC, miguelfspinto commented
> Those events are related to variations, so probably better update the `woocommerce_add_button_change_state` name to indicate it.

Hi Claudio. Already done.

2020-03-31 20:55 UTC, claudiosanches approved these changes
Thanks for your contribution.

2020-05-11 23:39 UTC, ObliviousHarmony commented
Would you be able to achieve the same by binding the the form's `show_variation` and `hide_variation` events?

2020-05-12 07:37 UTC, miguelfspinto commented
No. I wouldn't. I want to change the button text depending on the class.

Christopher Allford <notifications@github.com> escreveu no dia terça,
12/05/2020 à(s) 00:39:

> Would you be able to achieve the same by binding the the form's
> show_variation and hide_variation events?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/woocommerce/woocommerce/pull/25009#issuecomment-627022425>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABCB4WH3QRTHIEWH7HSY3U3RRCECVANCNFSM4JLKD7ZQ>
> .
>

2020-05-14 21:44 UTC, ObliviousHarmony commented
I was thinking that if you bind to the event after WooCommerce, you would be able to check the class on the button and update the text. I'm just not sure we should start getting so granular with events like this.

2020-05-15 08:30 UTC, miguelfspinto commented
> I was thinking that if you bind to the event after WooCommerce, you would be able to check the class on the button and update the text. I'm just not sure we should start getting so granular with events like this.

I don't understand how can i do it? Can you explain please?

2020-05-28 21:45 UTC, peterfabian commented
I'm guessing what @ObliviousHarmony meant is that when you bind your code to `show_variation` and `hide_variation` events after the WC code sets up the binding (and you would use [jQuery which guarantees that "Event handlers bound to an element are called in the same order that they were bound"](https://api.jquery.com/on/)), your handler would be called after the WooCommerce handler, thus the classes should already be changed and you can react to those changes in the same way as if you reacted to `woocommerce_add_button_change_state`.

Alternatively, you might be able to use [Mutation Observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to detect changes of class on an element?

2020-06-04 08:09 UTC, miguelfspinto commented
thank you @peterfabian and @ObliviousHarmony . I changed my code adding the following snippet. You can close this pull request.

`if (typeof wc_add_to_cart_variation_params !== 'undefined') {
        $('.variations_form').each(function () {
            $(this).on('hide_variation,show_variation', function () {
                $(this).find(".single_add_to_cart_button").trigger("woocommerce_add_button_change_state");
            });
        });
    }`

2020-06-04 08:47 UTC, miguelfspinto commented
Hi @peterfabian and @ObliviousHarmony 
It is not working.
I added the following snippet but nothing.

if (typeof wc_add_to_cart_variation_params !== 'undefined') {
        $('.variations_form').each(function () {
            //trigger after VariationForm is executed
            $(this).on('wc_variation_form', function () {
                //trigger after hide variation e show variation
                console.log("event binded on cart from springkode");
                $(this).on('hide_variation,show_variation', function () {
                    $(this).find(".single_add_to_cart_button").trigger("woocommerce_add_button_change_state");
                });
            });
        });
    }

2020-06-04 14:54 UTC, ObliviousHarmony commented
Hello @miguelfspinto,

There's a slight mistake in your `$(this).on()` method call. You need to use spaces to bind to multiple events using jQuery. I tested in the developer console with this and was able to see everything working as expected:

```javascript
jQuery('.variations_form').each(function () {
    jQuery(this).on('hide_variation show_variation', function () {
    	console.log('variation change event');
    });
});
```

2020-06-04 15:56 UTC, ObliviousHarmony commented
Hi @miguelfspinto,

Sorry, the snippet I shared wasn't meant to be a solution to your problem as much as a demonstration of a working case.

Just to confirm, the `hide_variation,show_variation` comma delimiter mistake in the snippet you initially provided is not the source of the problem you're encountering, right? The second snippet you shared has it working. I've got a few thoughts about the timing issue.

1. Can you add the snippet in a way that is loaded synchronously with the rest of the page content?
2. You could also check to see if the event handler has been bound to the `hide_variation` or `show_variation` event.

2020-06-04 16:01 UTC, miguelfspinto commented
> Hi @miguelfspinto,
> 
> Sorry, the snippet I shared wasn't meant to be a solution to your problem as much as a demonstration of a working case.
> 
> Just to confirm, the `hide_variation,show_variation` comma delimiter mistake in the snippet you initially provided is not the source of the problem you're encountering, right? The second snippet you shared has it working. I've got a few thoughts about the timing issue.
> 
> 1. Can you add the snippet in a way that is loaded synchronously with the rest of the page content?
> 2. You could also check to see if the event handler has been bound to the `hide_variation` or `show_variation` event.

Hi @ObliviousHarmony ,
1 . Yes. I can add the snippet just right the form, in the add-to-cart/variable.php template file.
2. Yes. I already added some console.logs in the add-to-cart-variation.js file to understand the order of the events and i can successfully bind the show_variation and hide_variation successfully.
What do you suggest for the timming issues?

2020-06-04 16:23 UTC, ObliviousHarmony commented
Hey @miguelfspinto,

Ah, I see what you're saying. Everything is working but since `check_variations` is triggered before `wc_variation_form`, you aren't able to trigger on the first variation check done on page load. What about binding to `check_variations` and then removing it after the first execution? Something like `$(this).off('check_variations');` at the end of your `.each()` function?

2020-06-04 16:34 UTC, miguelfspinto commented
> Hey @miguelfspinto,
> 
> Ah, I see what you're saying. Everything is working but since `check_variations` is triggered before `wc_variation_form`, you aren't able to trigger on the first variation check done on page load. What about binding to `check_variations` and then removing it after the first execution? Something like `$(this).off('check_variations');` at the end of your `.each()` function?

I will try that. I just don't understand why are you so resistant to place that trigger. I think it is a lot of useful. You can check the behaviour in this link: https://www.springkode.com/product/cotton-sweatshirt-dark-grey/?v=pt => We can customize the text on the button based on the behaviours that customer need to perform.

2020-06-04 16:36 UTC, miguelfspinto commented
> $(this).off('check_variations');

One question, @ObliviousHarmony , if I use $(this).off('check_variations'); i will unbind any event that other plugin could bind, right? Is it not dangerous to do it?

2020-06-04 16:58 UTC, ObliviousHarmony commented
Sorry! You need to pass a reference to the handler as well, otherwise it will unbind all handlers.

> On Jun 4, 2020, at 9:36 AM, Miguel Pinto <notifications@github.com> wrote:
> 
> ﻿
> $(this).off('check_variations');
> 
> One question, @ObliviousHarmony , if I use $(this).off('check_variations'); i will unbind any event that other plugin could bind, right? Is it not dangerous to do it?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-04 17:24 UTC, ObliviousHarmony commented
As far as resistance to the filter goes @miguelfspinto, it mostly has to do with the granularity of the event itself. There's a careful line to walk between extensibility and rigidity that informs a lot of my decisions around things like this. 

The more events, filters, and actions we add, the more extensible WooCommerce as a platform becomes. The cost of this however lies in having to support it virtually forever. This makes future enhancements difficult as they have to work around very specific extension points. It is very hard to make performance or testing improvements in a codebase that cannot be changed in any meaningful way.

Looking at making this less granular we find that we already have the `show_variation` and `hide_variation` events which can solve this for you, so there's not necessarily a need to drill down further in my opinion.

2020-06-04 17:33 UTC, miguelfspinto commented
> As far as resistance to the filter goes @miguelfspinto, it mostly has to do with the granularity of the event itself. There's a careful line to walk between extensibility and rigidity that informs a lot of my decisions around things like this.
> 
> The more events, filters, and actions we add, the more extensible WooCommerce as a platform becomes. The cost of this however lies in having to support it virtually forever. This makes future enhancements difficult as they have to work around very specific extension points. It is very hard to make performance or testing improvements in a codebase that cannot be changed in any meaningful way.
> 
> Looking at making this less granular we find that we already have the `show_variation` and `hide_variation` events which can solve this for you, so there's not necessarily a need to drill down further in my opinion.

Hi @ObliviousHarmony , thanks for your reply.
You're totally right. And I am very proud of woocommerce team and your amazing job. 🥇 
I will use the bind/unbind solution you provided.
Thank you again for all the help and your time.  👍

2020-06-04 17:47 UTC, ObliviousHarmony commented
Thank you for the kind words @miguelfspinto, I am glad I was able to help 😄

2020-06-04 17:47 UTC, closed without merging