Make trash status translatable
woocommerce/woocommerce pull request #25254
Opened 2019-12-18 09:27 UTC by nicomollet

When looking at admin screen on `/wp-admin/edit.php?post_status=trash&post_type=shop_order` orders with `trash` status have the status not localized. The status is not defined in the `wc_get_order_statuses()` function.
This commit adds the localized string.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds readable version of `trash` order status.

### How to test the changes in this Pull Request:

1. Go to `/wp-admin/edit.php?post_status=trash&post_type=shop_order` admin screen 
2. See the status being changed from `trash` to `Trash`
3. The string is now translatable

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2019-12-18 09:28 UTC, nicomollet commented
Showing with this image what the admin looks like before the pull request.
![Annotation 2019-12-18 102408](https://user-images.githubusercontent.com/108828/71073611-0107af00-2181-11ea-8c5e-4b8eaec99f6c.png)

2019-12-18 15:37 UTC, claudiosanches requested changes
> When looking at admin screen on /wp-admin/edit.php?post_status=trash&post_type=shop_order orders with trash status have the status not localized. The status is not defined in the wc_get_order_statuses() function.
>This commit adds the localized string.

`trash` is a default status from WordPress core, and you should translate it on WordPress.
Also this code only control custom statuses, including `wc-trash` will not replace `trash` from WordPress core.

2019-12-18 15:37 UTC, closed without merging

2019-12-19 08:55 UTC, nicomollet commented
@claudiosanches well the `trash` status seems to be translated as a WordPress status.
Look at the posts admin screen showing the status column. It is translated as `Corbeille`.

So I don't understand why it is not translated in WooCommerce also.

![Annotation 2019-12-19 095228](https://user-images.githubusercontent.com/108828/71159056-4beafa80-2245-11ea-93b4-4ee871512201.png)

2019-12-19 18:43 UTC, claudiosanches commented
@nicomollet as I said, the code on this PR doesn't fix the issue, only creates more problem.

2020-02-29 07:37 UTC, beegii4870 commented
Add next code to the /includes/wc-order-functions.php on function wc_get_order_status_name after line 147 ($status   = isset( $statuses[ 'wc-' . $status ] ) ? $statuses[ 'wc-' . $status ] : $status;)

	if($status == "trash"){
		$status = __( 'Trash', 'woocommerce' );
	}

It will show WooCommerce translation.