Fix free shipping save in setup wizard. (#25139)
woocommerce/woocommerce pull request #25390
Opened 2020-01-12 18:36 UTC by OlegApanovich

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

There is some wrong setup wizard options in shipping section. When we try so save shipping option we also save shipping cost settings any way it is a Free Shipping or Flat Rate shipping methods.
Obviously in case of Free Shipping cost option is unnecessary.

Our request $_POST['shipping_zones'] has such value when when we try to save it with Free Shipping for a domestic method and with Flate rate for Other locations 

  ["domestic"]=>
  array(3) {
    ["method"]=>
    string(13) "free_shipping"
    ["flat_rate"]=>
    array(1) {
      ["cost"]=>
      string(3) "100"
    }
    ["enabled"]=>
    string(3) "yes"
  }
  ["intl"]=>
  array(3) {
    ["method"]=>
    string(9) "flat_rate"
    ["flat_rate"]=>
    array(1) {
      ["cost"]=>
      string(4) "1000"
    }
    ["enabled"]=>
    string(3) "yes"
  }

As we can see flat_rate setting with cost 100 is redundant for domestic method, but we have it in our Post request anyway. More over we also try to do checking with it wrong setting.
And it produce fold for a Free Shing method and as result do not save in wocommerce settings after setup wizard over. In my PL I replased checking of all WP_REST_Request request with just individual setting checking,

We also can add additional code to ajax request that trying to remove redundant cost setting for a free shipping but it will become our js code more complicated. For now it quite enough that I add in PL to fix current issue.

Closes # .

### How to test the changes in this Pull Request:

1. All steps already has initial issue.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry
Fix free shipping save in setup wizard.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2020-03-31 20:28 UTC, claudiosanches requested changes
All input sanitization got removed in this PR.
Please introduce sanitization again.
Thanks.

2020-03-31 20:28 UTC, claudiosanches commented on includes/admin/class-wc-admin-setup-wizard.php
> +				$settings = $_POST['shipping_zones']['domestic'][ $domestic_method ];
Better keep the sanitization here.

2020-03-31 20:28 UTC, claudiosanches commented on includes/admin/class-wc-admin-setup-wizard.php
> +				$settings = $_POST['shipping_zones']['intl'][ $intl_method ];
Missing sanitization here too.

2020-04-14 20:21 UTC, claudiosanches requested changes
There's some conflicts to solve.

2020-04-15 07:33 UTC, OlegApanovich commented
> There's some conflicts to solve.

Conflicts resolved.

2020-06-23 17:29 UTC, claudiosanches commented
Thank you very much for your help, but since we are using a new OBW this PR it's no longer necessary, we are going to remove this setup wizard in the next release.

2020-06-23 17:29 UTC, closed without merging