Update cart-empty.php
woocommerce/woocommerce pull request #25419
Opened 2020-01-17 07:26 UTC by shaikhaezaz80

Added filter to change "Return to Shop" button text

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2020-01-17 10:34 UTC, kloon commented
Hi @shaikhaezaz80, can I please ask you to update the PR description and title so it reflects what the changes are and also include testing instruction for us.

2020-01-17 12:20 UTC, shaikhaezaz80 commented
I updated the description @kloon

2020-01-20 11:31 UTC, kloon submitted a review, later dismissed
Hi, thanks for your contribution, just a couple of small changes:
1. Ensure your code is following the WP Coding Standards, please see the errors here https://travis-ci.org/woocommerce/woocommerce/jobs/638311404?utm_medium=notification&utm_source=github_status
2. There are other places in the codebase where this button also appears, might be worthwhile adding the filter to all these places, do a search to find it.

If you can address those two issues we can get this merged.

2020-02-04 16:59 UTC, claudiosanches requested changes

2020-02-04 16:59 UTC, claudiosanches commented on templates/cart/cart-empty.php
> +			<?php echo apply_filters('woocommerce_return_to_shop_title', sprintf( '%s', __('Return To Shop', 'woocommerce' ) )); ?>
Why there's a sprintf on this filter? I can't see any real work use for it.
Also not following WordPress coding standards.

2020-02-04 17:01 UTC, claudiosanches commented
I'm removing this issue from the 4.0.0 milestone since there's issues with this PR that didn't get any update. We may close this PR due the author's inactivity.

2020-03-06 15:09 UTC, rodrigoprimo commented
Closing due to inactivity. Please leave a comment if you still plan to work on this and we will reopen. Thanks.

2020-04-01 14:36 UTC, shaikhaezaz80 commented
My apologies for inactivity. I edited the requested changes and seems like everything is fine now and good to go.

2020-06-23 20:01 UTC, claudiosanches approved these changes
Thanks for your help!

2020-09-05 14:36 UTC, rodrigoprimo approved these changes
Thanks for your contribution!

2020-09-05 14:37 UTC, merged

2020-10-02 10:46 UTC, JimmyAppelt commented
@rodrigoprimo @claudiosanches any reason why the string capitalization has been changed?

2020-10-02 11:50 UTC, rodrigoprimo commented
Good catch, @JimmyAppelt. I completely missed this when reviewing this PR. I opened #27845 to revert the string to its original version.