Add support for placeholders in quantity inputs
woocommerce/woocommerce pull request #25418
Opened 2020-01-16 19:48 UTC by helgatheviking

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Allow the `woocommerce_quantity_input()` function and the `quantity-input.php` template to support a placeholder attribute.

Closes # .

### How to test the changes in this Pull Request:

Use the following snippet:

```
function kia_add_placeholder_attr_to_inputs( $args, $product ) {
	$args['placeholder'] = '0';
	$args['input_value'] = '';
	return $args;
}
add_filter( 'woocommerce_quantity_input_args', 'kia_add_placeholder_attr_to_inputs', 10, 2  );
```

A product should now an empty quantity input with a 0 placeholder. This is not that practical, but it shows it works. A place where this would be beneficial in core would be in grouped products. I can add a commit for that if you are open to it.

In Mix and Match I've had customers complain about needing to remove the 0 before being able to type in a value and I agree that's not good UX.

https://share.getcloudapp.com/qGuD7mkm

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Add support for placeholder attribute in quantity inputs.

2020-01-16 19:49 UTC, helgatheviking commented
FYI, I think this has a good application in the grouped products template, but didn't want to add it to this commit if you didn't want it.

2020-01-20 11:44 UTC, kloon requested changes
A small couple of changes to get this merged. Regarding grouped products, you might as well also add it there in this PR since you are making the changes to the other products.

2020-01-20 11:44 UTC, kloon commented on includes/wc-template-functions.php
> +			'placeholder'  => '',
Could you please add a new filter as per the attributes above this, just so it follows the same trend.

2020-01-20 11:44 UTC, kloon commented on templates/global/quantity-input.php
> + * @version 3.9.1
This should be 3.10 since we do not roll out enhancement with fix releases anymore, we will just do bug fixes in fix releases.

2020-02-04 17:05 UTC, claudiosanches approved these changes
Great work, thanks for your help!
I'll merge into a feature branch so I can bump template versions to 4.0.0.

2020-02-04 17:05 UTC, merged