[3.9] Fix shipping form always shown in checkout when custom fields are present
woocommerce/woocommerce pull request #25639
Opened 2020-02-11 19:11 UTC by adriandmitroca

### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

I've added extra if statement that checks if field that is being compared for actually exists. Thanks to it shipping form is not always shown on page load if custom fields are implemented and the function checks only existing fields which is correct behavior.

### Changelog entry

Fix - Shipping form in checkout always shown when custom fields are present

2020-03-06 12:34 UTC, rodrigoprimo commented
@adriandmitroca, could you please include instructions on how to reproduce the problem that this PR fixes and how to test it as requested in the PR template? Thanks!

2020-03-06 12:45 UTC, adriandmitroca commented
You can test this for example by adding a VAT field to billing fields in the checkout.

2020-04-01 18:42 UTC, claudiosanches requested changes

2020-04-01 18:42 UTC, claudiosanches commented on assets/js/frontend/checkout.js
> +						return $( this ).val() !== $billing.find( '#' + id ).val();
A filter need to return true or false, and in this case there's nothing getting returned if the fields doesn't exists.

2020-05-08 14:38 UTC, closed without merging