Removed the nonce_user_logged_out filter usage
woocommerce/woocommerce pull request #25971
Opened 2020-03-19 05:57 UTC by ObliviousHarmony

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This filter is used to prevent CSRF attacks for unregistered users. This however causes problems because after a wc-ajax cart action, a session is initialized, and any nonce stored on the page becomes unusable. Since giving everyone a session would pose a number of problems, we will just remove the filter usage.

Closes #23682.

### How to test the changes in this Pull Request:

1.  Add a plugin containing this code:
```
add_action( 'wp_footer', function() {
	?>
	<script>
		function ajax_test_call() {
			jQuery.ajax( {
				url: '<?php echo esc_url_raw( rest_url() ) . 'wp/v2/product'; ?>',
				method: 'GET',
				beforeSend: function ( xhr ) {
					xhr.setRequestHeader( 'X-WP-Nonce', '<?php echo wp_create_nonce( 'wp_rest' ); ?>' );
				},
			} ).done( function ( response ) {
				console.log( response );
			} );
		}
	</script>
	<?php
} );
```
2. Visit the shop in an incognito window.
3. Open the developer console and run the `ajax_test_call()` function. It should print a list of the products.
4. Add an item to the cart.
5. Run the `ajax_test_call()` function again. Without this PR it should return 403, and with it, the products will be returned as expected.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix - Corrected the user associated with nonces after cart actions.

2020-06-23 20:43 UTC, claudiosanches requested changes
While it works as expected, it also removes nonce check in the cart, we need to further discuss it with the team.

2020-11-16 05:29 UTC, tyrann0us commented
Hi @claudiosanches,

>[…] we need to further discuss it with the team.

Did the discussion lead to a result? This topic has already been addressed several times, see https://github.com/woocommerce/woocommerce/search?q=nonce_user_logged_out+is%3Aissue&type=Issues.

Even the official PayPal (https://woocommerce.com/products/woocommerce-paypal-payments/, private GitHub repository) and PayPal PLUS (https://wordpress.org/plugins/woo-paypalplus/) plugins include a workaround for this, see e.g. https://github.com/inpsyde/paypal-plus-plugin/blob/933925da7ddff70c65cdbd710a610064127abe63/src/Nonce.php#L71-L91.

It would be really great if you could fix this! Thanks!

2021-02-12 19:45 UTC, Tabrisrp commented
Upvoting for follow-up work on this, [as per my comment on the related issue](https://github.com/woocommerce/woocommerce/issues/23682#issuecomment-778411999)

2021-03-30 17:39 UTC, claudiosanches commented
Closing since it will make our cart vulnerable to attacks and I don't recommend anyone doing it for any reason.

Here a new fix for this issue: https://github.com/woocommerce/woocommerce/pull/29542

2021-03-30 17:39 UTC, closed without merging