Fix WooCommerce DB update done notice action
woocommerce/woocommerce pull request #26031
Opened 2020-03-30 02:37 UTC by becdetat

This resolves https://github.com/woocommerce/woocommerce-admin/issues/3973 (the 'Thanks!' button doesn't work properly after 24 hours) by removing the nonce wrapper from the 'Thanks!' action URL generation.

### Changes proposed in this Pull Request:

Removes the nonce wrapper from the 'Thanks!' action URL generation when generating the final DB update admin note.

Closes https://github.com/woocommerce/woocommerce-admin/issues/3973.

### How to test the changes in this Pull Request:

Edit `includes/admin/notes/class-wc-notes-run-db-update.php` and at the end of the constructor add this:

```
$note_id = $this->update_needed_notice();
$this->update_done_notice($note_id);
```

Refresh the page and the done notice should appear. Remove the added code from the constructor before continuing.

Click the 'Thanks!' button and the notice should disappear. To fully test, repeat and wait for at least 24 hours before clicking 'Thanks!', and the notice should still disappear. That shouldn't be required though as it's pretty obvious that the nonce generation code has just been removed from the action URL.

### Changelog entry

Fix database update complete notice action if the notice has been left for 24+ hours.

2020-03-31 18:17 UTC, claudiosanches requested changes
> (the 'Thanks!' button doesn't work properly after 24 hours) by removing the nonce wrapper from the 'Thanks!' action URL generation.

This is the expect behavior of nonces in WordPress, not to mention that this is placed for security reasons, also by just removing the nonce on `update_done_notice()` makes impossible to remove any notice since WooCommerce will check for the `_wc_notice_nonce` in:

https://github.com/woocommerce/woocommerce/blob/9ac9970a77e6f313ab548016e7fc0adc189ca039/includes/admin/class-wc-admin-notices.php#L147-L164

Note that since is missing the nonce all code will get ignored.

2020-03-31 18:19 UTC, claudiosanches commented
As I said in my review it's a expected behavior, this same nonce is present in another 12 files and all are required for security reasons, so I'm closing this PR, we can't remove this nonce check.

2020-03-31 18:19 UTC, closed without merging

2020-04-02 02:37 UTC, becdetat commented
Thanks for the explanation @claudiosanches .

I've reproduced the issue by waiting more than 24 hours and pressing the action:

![image](https://user-images.githubusercontent.com/224531/78205049-8d46a380-74de-11ea-94ba-1d50996f2324.png)

Do you have any suggestions for a workaround or a different way of approaching the issue?

2020-04-02 11:49 UTC, rrennick commented
@becdetat I think this scenario (nonces) may be one where we will need to enhance the note functionality in some way (eg. allow notes to auto expire / action, use a callback for the action urls, or other dynamic URL generation).

2021-11-10 05:15 UTC, amirhosseinhpv commented
This is how i managed to remove notice, just run this function or add it into your function.php then comment it again:

`(new WC_Notes_Run_Db_Update())->set_notice_actioned();`