Update minimum PHP version to 7.0
woocommerce/woocommerce pull request #26090
Opened 2020-04-07 00:12 UTC by ObliviousHarmony

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

We've been declaring a PHP 7 requirement since 3.9, but this isn't actually reflected in our codebase. This PR moves forward with the assumption that 7.0 is the minimum version.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dev - Increased the minimum PHP version to 7.0.

2020-04-15 16:49 UTC, claudiosanches approved these changes
LGTM!

2020-04-15 16:49 UTC, claudiosanches requested changes
There's some conflicts to fix before we can merge.

2020-04-15 21:38 UTC, ObliviousHarmony commented
> There's some conflicts to fix before we can merge.

My favorite! 

Do you think that, given the fact that this requirement is enforced, we should discuss it a bit before pulling the trigger?

2020-04-16 21:53 UTC, claudiosanches approved these changes

2020-04-16 22:01 UTC, merged