Revert deprecation of $type on the get_european_union_countries method
woocommerce/woocommerce pull request #26107
Opened 2020-04-07 22:09 UTC by webdados

Closes #26105 

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Revert deprecation of $type parameter on the WC_Countries get_european_union_countries method.

Closes #26105 

### How to test the changes in this Pull Request:

1. Call WC()->countries->get_european_union_countries('eu_vat') and make sure you get the EU countries + Monaco + Isle of Man + Greaat Britain instead of a list of 80 countries

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Revert deprecation of $type parameter on the WC_Countries get_european_union_countries method

2020-04-09 21:38 UTC, claudiosanches commented on includes/class-wc-countries.php
> +			//The UK is still part of the EU VAT zone
Please update to:

```
// The UK is still part of the EU VAT zone.
```

2020-04-09 21:39 UTC, claudiosanches requested changes
This change looks good.
There's just a small tweak to do before we can approve.
Thanks!

2020-04-10 09:47 UTC, webdados commented on includes/class-wc-countries.php
> +			//The UK is still part of the EU VAT zone
Done

2020-04-10 11:19 UTC, webdados commented
@claudiosanches Should we add a date check so that IM and GB are only returned until December 31st 2020?
https://www.avalara.com/vatlive/en/vat-news/uk-to-leave-eu-vat-regime-31-dec-20200.html

2020-04-13 14:53 UTC, claudiosanches approved these changes
Thanks!

2020-04-23 13:50 UTC, merged