Add hooks to "Add payment method form" to show additional fields and validate input
woocommerce/woocommerce pull request #26445
Opened 2020-05-11 01:34 UTC by tsteur

### All Submissions:

* [ x ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #26414

### How to test the changes in this Pull Request:

1. Copy https://gist.github.com/tsteur/59f233312635e31f26d3d8c16973b179 into your theme
2. Enter 20 into the shown form field in add payment method page
3. It should show an error message and not add the card vs if you type any other number it will do it. This allows us implementation of captcha see issue description.

### Other information:

* [ x ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable? -> None written. Maybe not needed?
* [ x ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Dev - Added action before the "Add payment method" save button.
Dev - Added filter to validate manually added fields when adding payment method

2020-05-14 08:35 UTC, Konamiman requested changes
Hi @tsteur, thanks for your pull request. While the implementation looks good, I'd suggest changing the names of the action and the filter you have implemented:

* For `woocommerce_add_payment_method_validation`, I would go with `woocommerce_add_payment_method_form_is_valid`, for consistentcy with other WooCommerce validation filters ending with `_is_valid` and to make clear that it's a form validation.

* For `woocommerce_add_payment_method_before_save`, since we have other `_before_save` filters and they refer to the act of saving an object rather than rendering HTML, I'd change it to `woocommerce_add_payment_method_form_bottom`.

Also could you please fix the notified coding standard error (a missing space before a parenthesis)?

2020-05-14 21:21 UTC, tsteur commented
Thanks for the feedback @Konamiman 

I've applied the changes and the coding style tests are passing now too.

It looks like the other tests are failing but seems like some random travis failure to me. Here at Matomo we have these randomly failing travis tests in the last days too. I can't trigger a rebuild but happy to do some white space commits to trigger a new build if that helps.

2020-05-15 08:15 UTC, Konamiman approved these changes

2020-05-15 08:16 UTC, Konamiman commented
I've been able to trigger the build myself and this time there were no errors.

2020-05-15 08:16 UTC, merged