Update woocommerce.js
woocommerce/woocommerce pull request #26526
Opened 2020-05-15 13:01 UTC by thirumani02

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

I removed the selector <code>.woocommerce form</code> & added <code>.woocommerce-form</code> to avail this show password input script to all pages not only to woocommerce page. Also widen the scope of  <code>.show-password-input</code> also to the ajax form with selectors  <code>.woocommerce-form</code>. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Tweak: I made this change to avail show/hide toggle function to all forms (from custom plugins or theme snippets) which has "woocommerce-form" class/selector.

2020-06-25 19:47 UTC, claudiosanches requested changes
Thanks for your help, but changing to `.woocommerce-form` will not work in all places that it suppose to work.

2020-06-25 19:47 UTC, claudiosanches commented on assets/js/frontend/woocommerce.js
> +	$( '.woocommerce-form .woocommerce-Input[type="password"]' ).wrap( '<span class="password-input"></span>' );
Doing it will disable it on other forms like in the My Account page.

2020-06-25 19:47 UTC, claudiosanches commented on assets/js/frontend/woocommerce.js
> +	$( '.woocommerce-form' ).on('click', '.show-password-input', function() {
```suggestion
	$( '.woocommerce-form' ).on( 'click', '.show-password-input', function() {
```

2022-03-10 18:43 UTC, barryhughes commented
As there are some unaddressed concerns and we haven't seen any movement on this in quite a while, going ahead and closing it out.

2022-03-10 18:43 UTC, closed without merging