Add a woocommerce_check_cart_item_stock_ignore_ids filter to allow bypass of check_cart_item_stock()
woocommerce/woocommerce pull request #26979
Opened 2020-07-08 16:50 UTC by kevinruscoe

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

check_cart_item_stock() is used to deal with cart items that are no longer available.

In some custom development scenarios you may want to omit specific cart items from this check. It uses $this->get_cart() as a means of getting the cart items and therefore we can't see a way to manipulate this other than using wp_debug_backtrace_summary to find out if do_action('woocommerce_check_cart_items') is a caller (which eventually fires the check_cart_item_stock function).

This adds a `woocommerce_check_cart_item_stock_ignore_ids` filter that allows you to pass an array of IDs for the check to ignore.

Closes #26944 .

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Add a `woocommerce_check_cart_item_stock_ignore_ids` filter so you can ignore certain products when `check_cart_item_stock()` is ran.

2020-08-01 09:53 UTC, ninetyninew commented
Hey, just to let you know I am going to do further work on this to also take advantage of the cart item key too, this way you can remove products from this check based on the cart item key which in turn means you can remove products from the checked based on any specific meta the cart item may have in relation to this - in some scenarios the product id would not be enough.

2020-08-01 11:39 UTC, kevinruscoe commented
@ninetyninew Sounds good, I'd suggest to copy the `$cart_item_ids_to_ignore = apply_filters( 'woocommerce_check_cart_item_stock_ignore_ids', array() );` line, to something like `$cart_line_item_ids_to_ignore = apply_filters( 'woocommerce_cart_line_item_ids_to_ignore', array() );`, then merge the 2 arras together, and use that final array to check against in the loop below.

Whilst you're at it, it might be worth coming up with some better filter names. Tbh, I don't think they're clear enough what they do and they're pretty generic.

2020-08-01 15:39 UTC, ninetyninew commented
This should do it https://github.com/ninetyninew/woocommerce/commit/386a491a6aff5e10600959edb0a4e9281678ca6e

What do you think? This means you can ignore specific product ids where needed and also ignore by cart item key.

The cart item key is important as you may have items added to the cart containing specific meta which means check_cart_item_stock should not be used.

I can either do this as a new pull request or you update yours?

2020-09-15 12:18 UTC, rodrigoprimo commented
Thanks for your contribution, @kevinruscoe! Instead of creating a filter to populate a variable with a list of IDs to ignore, what if we created a filter to modify whatever is returned by `$this->get_cart()`? I believe this is a more flexible and less specific solution. Would this work for your use case?

This is what I have in mind (not super happy about the filter name):

```php
$cart_items = apply_filters( 'woocommerce_check_cart_item_stock_items', $this->get_cart() );

foreach ( $cart_items as $cart_item_key => $values ) {
   ...
}
```

2020-10-15 00:34 UTC, claudiosanches requested changes
Thanks for your help, but there's other alternatives to do what you intent to do.

Like it's possible to use the `woocommerce_get_cart_contents` checking if `woocommerce_check_cart_items` got triggered with `has_filter()`.

2020-10-15 00:34 UTC, claudiosanches commented on includes/class-wc-cart.php
> +		$cart_item_ids_to_ignore = apply_filters( 'woocommerce_check_cart_item_stock_ignore_ids', array() );
This is very custom, and don't have any use on core by default.

2020-10-15 00:35 UTC, closed without merging

2020-12-21 08:51 UTC, ninetyninew commented
@claudiosanches Thanks for the info on `woocommerce_get_cart_contents` checking if `woocommerce_check_cart_items` got triggered with `has_filter()`. Although I'm struggling to figure out how this would help with stopping the stock check for a specific cart item, I tested this:

`
add_filter( 'woocommerce_get_cart_contents', 'test123' );
public function test123( $cart_contents ) {

	if( has_filter( 'woocommerce_check_cart_items' ) ) {

		foreach( $cart_contents as $k => $v ) {

			if( isset( $v['some_meta_key'] ) ) { // some_meta_key would be a key we define to stop this cart item being checked

				unset( $cart_contents[$k] );

			}

		}
	
	}

	return $cart_contents;

}
`

But this would still remove the cart item when loading the cart. So while I get why this will not be considered for core, I can't see any way we could use anything WooCommerce includes in core to disable the stock check for specific cart items, which while we are trying to do this for a specific reason (rental products) I suspect there may be other scenarios where a developer building something custom would want to bypass the cart stock check on a specific item - so I feel like `woocommerce_check_cart_items` does limit the extensibility possible. Maybe you were thinking of another means of using those filters I am unaware of? Any pointers here would be really appreciated.

2021-02-02 11:57 UTC, ninetyninew commented
Just incase anyone is looking for similar info on this kind of functionality, I saw this recently, it might help - not yet tested this myself: https://wordpress.stackexchange.com/questions/378040/wooocommerce-disable-check-cart-item-stock-if-cart-item-has-specific-meta