Add postcode validation for Bosnia and Herzegovina
woocommerce/woocommerce pull request #27048
Opened 2020-07-16 12:01 UTC by vallter2

Postcode in Bosnia and Herzegovina consists of 5 numbers. First number is 7 or 8 and the rest 4 numbers can be in range 0-9.

https://bs.wikipedia.org/wiki/Spisak_po%C5%A1tanskih_brojeva_u_Bosni_i_Hercegovini

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

Add postcode validation for Bosnia and Herzegovina

2020-07-16 14:27 UTC, claudiosanches approved these changes
Great work! Thanks for your help!

2020-07-17 11:08 UTC, benomius21 commented
Great work, very helpful. Good job.

2020-07-20 16:12 UTC, claudiosanches requested changes

2020-07-20 16:19 UTC, vallter2 commented on includes/class-wc-countries.php
> +						'country' => array(
Fixed... Thanks

2020-07-20 21:08 UTC, claudiosanches approved these changes
Great work, thanks!

2020-08-10 19:23 UTC, rrennick approved these changes

2020-08-10 19:24 UTC, merged