#27103 fix, PHPDoc fix for new  boolean parameter
woocommerce/woocommerce pull request #27104
Opened 2020-07-23 04:42 UTC by codemascot

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

I think we should set the value of `$autoload` parameter `true` to make it backward compatible. Otherwise it can break other plugin, though the change of error due to option autoload fairly low!

Closes #27103

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2020-07-23 12:40 UTC, rrennick commented
> Otherwise it can break other plugin, though the change of error due to option autoload fairly low!

@codemascot Can you clarify this? `autoload` being set to `no` is generally reserved for options that are rarely accessed or ones that contain a large amount of data (eg. a cached RSS feed).

2020-07-23 15:04 UTC, codemascot commented
@rrennick According to current behavior, the `$autoload`is set to `null` which it making the autoload *yes* while updating the option! Now if any other plugin is using this `WC_Rate_Limiter` with autoload is null, then setting this to `$autoload` variable to `true` provides the old behavior. And if anyone doesn't need to autoload then they can pass the value of `$autoload` false.

2020-07-24 00:20 UTC, ChrisBates commented
@rrennick I think the specific case I mentioned in #27103 would fit "rarely accessed" for sure. But more to the point the rate limit `action_id` is unique to the user - so no matter if it's a small data payload, why does User A's rate limited action need to load for Users B-Z?

Ultimately though, I have evidence that this is causing database read waits when a store is under a heavy load and doing very high volume. I believe it to be a combination of our specific InnoDB config, and the large number of read/writes happening at the same time. 

Having these specific actions set to autoload is to blame (imo), and I still see no real reason why they need to be autoload.

![image](https://user-images.githubusercontent.com/50668839/88350585-b1cad200-cd92-11ea-8699-e1ae23c0ce9e.png)

2020-07-24 13:01 UTC, rrennick commented
> I have evidence that this is causing database read waits when a store is under a heavy load and doing very high volume.

Accessing autoload options don't require database reads. WordPress runs a single query to retrieve all autoload options. Writing these options to the DB might be contributing to the DB waits but changing autoload from yes to no won't help with that.

Based on what you have described changing those to `no` would add a significant number of DB reads to your install. I'd suggest you investigate adding object caching to your install.

2020-07-24 14:20 UTC, ChrisBates commented
@rrennick We have added object caching, which has resolve the waits. However the issue I've described is still flawed, in my opinion.

The options being stored by the rate limiter are _user specific_ (at least in the `payment_methods_[user_id]` instance) - why do they need to be auto-loaded by all users? In our instance there were over 2,000 of these records being loaded in. 

I agree that setting autoload = no may not resolve the wait locks (assuming my understanding is correct, and InnoDB is locking the entire options table thanks to `innodb_autoinc_lock_mode=1`) ... But I still fail to see how auto-loading user specific data is relevant, or how setting it to autoload = no would add significant DB reads?

2021-03-09 20:26 UTC, 84em commented
I'd like to +1 this. We have a site with almost 2400 of these options.  It is a busy site, only getting busier, so this will grow in size.  

The options are only ~ 24k of autoloaded data, but my concern is as the site grows, so will all the autoloaded options.  

I don't see the need for these to be autoloaded on every page request.  

And ideally I think these should be stored as transients so they can be easily pruned?  Is there a need to store this information indefinitely?

Short term, I would really like to see these changed to autoload=no

2021-06-02 20:58 UTC, claudiosanches requested changes
Thank you very much for writing this code and starting this PR, but I think this feature needs a new table, doesn't make sense to keep it in the `wp_options` table, I'm planing to work on it soon, so I'm closing this PR for now, thanks!

2021-06-02 20:58 UTC, closed without merging