add args to wc_create_new_customer to autogenerate password/username:
woocommerce/woocommerce pull request #27132
Opened 2020-07-27 03:14 UTC by haszari

- this feature is currently controlled by store options
- in woo blocks plugin we'd like to always autogenerate, to streamline
checkout flow
- have added these options in `args` to for control independent of
store settings
- also updated new account email template where appropriate
+ fix phpcs issue date => gmdate

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2020-07-27 03:26 UTC, haszari commented on includes/wc-user-functions.php
> +	update_user_meta( $user_id, 'wc_last_active', (string) strtotime( gmdate( 'Y-m-d', time() ) ) );
This change was prompted by phpcs linter.

2020-07-31 18:36 UTC, ObliviousHarmony requested changes
Hello @haszari,

My first thought when reviewing this change was that we should pass a generated `$username` and `$password` to this function if we want to override the option's behavior. The caveat there though is that the `woocommerce_created_customer` action will have an incorrect value for `$password_generated` based on the assumption it wasn't. I think with that in mind this is a reasonable change. 

As far as testing goes, we've actually got really good coverage of this function in the `tests/legacy/unit-tests/customer/functions.php` file! Note that there is now a failing test in Travis due to this change. You could add this case to the existing test function and that should suffice.

If I was to do anything here myself I'd likely refactor the function into a few different classes, but I won't impose my insanity on others 😄

2020-08-03 00:28 UTC, haszari commented
Thanks for the review @ObliviousHarmony !

I've marked this PR as blocked for now. We're looking at implementing this differently in blocks – the plan is to add a new create account routine (PHP api) that ignores the options and always creates a new account as follows:

- Automatically generates a username.
- Emails the user to set the initial password.

Of course we may leverage existing Woo core code to implement some of this new flow. 

See the linked blocks [PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2377) and [issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2851#issuecomment-664092646) for more details (work in progress). pca54o-75-p2

> As far as testing goes, we've actually got really good coverage of this function in the tests/legacy/unit-tests/customer/functions.php file! Note that there is now a failing test in Travis due to this change. You could add this case to the existing test function and that should suffice.

Aha, thanks for highlighting that. As an exercise for myself, I've pushed a change which hopefully fixes the failure. Side note: I don't know how to run Woo core unit tests locally – I use docker based environments for dev, not sure what needs setting up for the unit tests. (I see there are [docs](https://github.com/woocommerce/woocommerce/tree/master/tests) but I think they are focused more on VVV use case.)

> If I was to do anything here myself I'd likely refactor the function into a few different classes, but I won't impose my insanity on others 😄

You actually raise an interesting point. When I add the new create account flow, I'm implementing essentially a new woo core PHP api, in blocks plugin initially. So it would be good if we build the new flow using similar patterns/approach as you're using for new code in core, to ease the path for merging into core in future. So I might ping you for a review on the blocks side :)

2020-10-04 23:02 UTC, haszari commented
Closing this – we're handling this by using a token-based set password flow. https://github.com/woocommerce/woocommerce/issues/27754

2020-10-04 23:02 UTC, closed without merging