Add filters to ignore reduce/increase/reserve stock for specific items
woocommerce/woocommerce pull request #27200
Opened 2020-08-01 16:37 UTC by ninetyninew

### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

These changes add filters to the reduce/increase/reserve stock functions to allow specific order items to be excluded, this functionality allows these functions to be bypassed for specific items which require it (deemed through use of specific meta set against the order item). In some custom development scenarios in the present code this would require the use of a backtrace to find out which functions are being called and the order items removed in some other way.

Closes https://github.com/woocommerce/woocommerce/issues/26943.

### How to test the changes in this Pull Request:

1. Create some custom functionality which adds some order item meta which should be used to ignore the checks
2. Add the filters in a plugin/theme, return that the order item id should be ignored if the above meta is set
3. Purchase the products, check the stock hasn't been reduced/reserved
4. Refund the order, check the stock haven't been increased.

### Changelog entry

> Add filters to ignore reduce/increase/reserve stock for specific items

Note that I do feel it might be wise to add some overall filter for this which these 3 functions (and potentially otherwise I am unaware of to hook into).

2020-08-04 13:58 UTC, claudiosanches requested changes
Those fields doesn't looks good, it's very specific for customization, and only for the customization you are looking for, those doesn't help in other cases, making too specif for us to keep supporting it.

2020-08-04 14:39 UTC, ninetyninew commented
> Those fields doesn't looks good, it's very specific for customization, and only for the customization you are looking for, those doesn't help in other cases, making too specif for us to keep supporting it.

Hi, thanks for the info. I just wanted to add a little more clarity here around why this would be useful.

You could have scenarios where a product is available for purchase and alternatively a customer could rent it (or any other scenario where the stock checks need to be bypassed depending on the item in cart), this would be achieved by, for example, a ?=rental=1 on the product page, if that product is added to cart with rental?=1 some meta is added to the cart item to flag that the cart item is a rental. Currently with no filter like requested WooCommerce just checks the stock levels and if the purchasable part of this product is out of stock it would remove those cart items from your basket. Without these filters there is no way to achieve this type of functionality without backtracking the callers of the functions. I appreciate it's not something you would generally need for stores which are purely purchase only but for any store providing additional services they could make use of these optional 3 (or combined into 1) filters.

Thanks for checking this out.

@claudiosanches

2022-03-10 18:27 UTC, barryhughes commented
Thanks for explaining. After further review, though, we feel this is too specific for inclusion.

2022-03-10 18:27 UTC, barryhughes commented
Thanks for explaining. After further review, though, we feel this is too specific for inclusion.

2022-03-10 18:27 UTC, closed without merging