Fix for issue #27021
woocommerce/woocommerce pull request #27242
Opened 2020-08-06 07:18 UTC by jgreys

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #27021

### How to test the changes in this Pull Request:

1. Add product to cart
2. Go to checkout
3. Fill an invalid phone number, for example insert: a123
4. Submit
5. The phone input is marked as invalid (red border)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Fixes phone input validation styling

2020-08-20 13:46 UTC, rrennick submitted a review, later dismissed
This PR worked fine with the above issue addressed.

2020-08-20 13:46 UTC, rrennick commented on assets/js/frontend/checkout.js
> +					var pattern = new RegExp(/[\s\#0-9_\-\+\/\(\)\.]/g);
@jgreys Thanks for the pull request. `var pattern` is a duplicate declaration of `pattern`. You'll need to move the declaration to the beginning of the function and remove the `var` on line #254.

2020-08-24 17:34 UTC, rrennick commented
@jgreys Thanks, I've added it to the review queue.

2020-08-28 12:44 UTC, mi5t4n commented
hhgfhg

2020-09-04 17:24 UTC, claudiosanches requested changes
Hello, there's some coding standards fixes that need to get applied.

2020-09-04 17:24 UTC, claudiosanches commented on assets/js/frontend/checkout.js
> +						pattern = new RegExp(/^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\
```suggestion
						pattern = new RegExp( /^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[0-9a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i ); // eslint-disable-line max-len
```

2020-09-04 17:24 UTC, claudiosanches commented on assets/js/frontend/checkout.js
> +					pattern = new RegExp(/[\s\#0-9_\-\+\/\(\)\.]/g);
```suggestion
					pattern = new RegExp( /[\s\#0-9_\-\+\/\(\)\.]/g );
```

2020-12-27 09:34 UTC, jgreys commented
Hello, do you need me to change anything else? Is it still in review? 🙂

2021-02-18 22:30 UTC, claudiosanches approved these changes
Thanks for your contribution!

2021-02-18 22:31 UTC, merged

2024-08-02 14:08 UTC, senadir commented
Sorry for reaching out to an old PR but why was `woocommece-invalid-phone` added to email field?