Fixing force jQuery code wrap in wc_print_js() and adding defer to inline script tag
woocommerce/woocommerce pull request #27547
Opened 2020-09-01 08:41 UTC by isaumya

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

A lot of themes and WooCommerce Plugins/Extensions uses `wc_enqueue_js()` to add their scripts that they would like to be added as inline scripts. Then `wc_print_js()` sanitize the scripts inside the queue and then add then as inline JS.

Currently, the problem is `wc_print_js()` forcefully wraps the `$wc_queued_js` queue variable inside `jQuery(function($) { ... });` unnecessarily. Also, the inline script tag doesn't have `defer` attribute in it. This leads to two problems:

1. Many extensions or themes that are trying to make the web `jQuery` free and write their code in pure vanilla JS, even their code gets wrapped with that `jQuery` call. So, if a site developer/owner things to get rid of `jQuery` on his/her website as none of the themes or plugins they use need `jQuery`, they still have to load `jQuery` as their vanilla JS codes are wrapped within a `jQuery` function for no reason. Removing this unnecessary jQuery wrap solves that major issue. So, if anyone wants to use jQuery they still can write their jQuery code however they line, but if someone chooses to go with vanilla JS, they are not forced to load jQuery.
2. Ad there is no `defer` tag in the inline script tag if any site owner loads their JS codes with `defer` to ensure they are not render-blocking, the script inside the inline script tag will simply fail. I really see no harm in adding the `defer` tag in the inline script. As unlike `async`, `defer` maintain the same order that they are called, it will not lead to major issues like `async` which doesn't follow the order of the scripts.
3. Due to the above two mentioned changes, I saw inside the WooCommerce core in some places `$` has been used to refer to `jQuery`, so instead of wrapping those scripts to `jQuery(function($) { ... });` so that they can use `$` to refer to `jQuery`, I've replaced the `$()` with `jQuery()` so that they don't need that extra two lines of code.

Closing: #27512

### How to test the changes in this Pull Request:

1. Install the plugin
2. Use it normally as this pull request doesn't add any major breaking changes. It is just improvements in terms of web performance.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

- Fixed forcefully wrapping codes added via `wc_enqueue_js()` with a jQuery function wrapper. Now inline scripts that are added via `wc_enqueue_js()` will no longer have a jQuery wrapper function around it. So, if anyone writes vanilla JS code, it will truly be jQuery dependency-free.
- Added `defer` attribute to the inline script tag added by `wc_print_js()` to ensure if anyone is loading the `jQuery` scripts in defer mode to better web performance, these inline scripts will no longer throw any errors. Also due to using defer the scripts will follow the proper script order whether you load your jQuery in defer mode or not.
- Some WooCommerce core inline JS file used `$()` to call `jQuery()` , now they have been changed to `jQuery()` so that it works perfectly with the new `wc_print_js()`.

2020-09-02 20:36 UTC, claudiosanches requested changes
Thanks for helping, but this change isn't backwards compatible, and it will cause problems for many 3rd party plugins.

2020-09-02 20:36 UTC, claudiosanches commented on includes/wc-core-functions.php
> +		$js = "<!-- WooCommerce JavaScript -->\n<script type=\"text/javascript\" defer>\n$wc_queued_js\n</script>\n";
Removing it will break any existing 3rd party plugin that relies on it.

2020-09-03 06:19 UTC, isaumya commented
> Thanks for helping, but this change isn't backwards compatible, and it will cause problems for many 3rd party plugins.

Hi @claudiosanches,
First of all, thank you so much for your reply to this matter. I think the only problem this will cause to the plugins/extensions which directly uses `$` to refer to `jQuery` in its code as the only thing that the wrapper function does is make sure `$` points to `jQuery` inside it. And I totally understand your point. 

But I don't think there is any debate about adding the `defer` tag as that will not cause any breaking changes or backwards compatibility issues. The only thing that you are worried about is removing the `jQuery` wrap function and I understand that.

Now that being said, this does not mean that we should keep doing it in the wrong way and force wrapping all inline js to be wrapped inside a `jQuery` function forcefully. WooCoomerce has also made breaking changes previously for the betterment of the system but I do agree that pushing such a breaking change instantly create a lot of screams in the development community.

### An Alternate Approach

This is why here is an alternate change that I will recommend and would love to know what you think about it. So, lets say by default WooCommerce will add the script tag like this (for now):

```
$js = "<!-- WooCommerce JavaScript -->\n<script type=\"text/javascript\" defer>\njQuery(function($) { $wc_queued_js });\n</script>\n";
```

**Note:** I have added the `defer` attribute to the `script` tag.

Now we can have a `filter` like `wp_print_js_no_jquery_wrap` which will be set to `false` by default and if it is set to `false` the `wc_print_js()` will use the above mentioned script tag. 

But inside there `functions.php` of the theme or in somewhere if someone adds `add_filter('wp_print_js_no_jquery_wrap', '__return_true');` then the filter will have a `true` value and will not wrap the inline js with the `jQuery` wrap function and instead will use the structure I've proposed.

Now this will give us an opportunity to show depreciation message to the developers that in the upcoming release of WooCommerce, we will be removing the `jQuery` wrap function from `wc_print_js()`. So, if you are using `$` directly inside your internal js to refer to `jQuery`, like `$()`, either change it to `jQuery()` or add a `jQuery` wrapper function around it to pass` jQuery` as `$`.

I think this is the best approach, as most people won't be passing that filter as `true` so all of them will see this deprecation notice and will have time to improve their code. Please let me know what do you think about this?

I really don't think we should not care about web performance and have bad code just for backward compatibility. Instead, let's give developers time to update their codes. There are many good developers like SkyVerge who uses vanilla JS in all the internal JS scripts and for trying hard to make the web a better and faster place. I think WooCommerce should also give web performance the highest priority. Just adding the `defer` is already would be a great step and then removing this `jQuery` wrapper function eventually. Please let me know what do you think about this approach.

#### On Another Note
As per W3C Validation `script` tags do not need the `type="text/javascript"` in them and ask to remove it. I didn't remove it in the PR because I wanted to hear your thought about it about making the code better. Removing `type="text/javascript"` from the script tag will not create any backward compatibility issues.

Looking forward to your reply. 🙂

2020-10-14 22:27 UTC, claudiosanches commented on includes/wc-core-functions.php
> +		$js = "<!-- WooCommerce JavaScript -->\n<script type=\"text/javascript\" defer>\n$wc_queued_js\n</script>\n";
Sorry, I understand what you are saying, yet this will cause issues for existing plugins and integrations.

2020-10-14 22:30 UTC, closed without merging

2022-05-12 07:20 UTC, fliespl commented
@claudiosanches how about wrapping woocommerce_queued_js into

```
    document.addEventListener("DOMContentLoaded", function () {

});
```

That should allow to lazy-load/defer jquery main script as well as keep plugins working as expected.

2022-12-30 17:30 UTC, Oremaker commented
This should be fixed at some point, jQuery defer should be allowed at least