Fix HTTP 401 `Sorry, you cannot list resources` REST API response
woocommerce/woocommerce pull request #27587
Opened 2020-09-04 08:03 UTC by om4james

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes an edge-case that causes a `Sorry, you cannot list resources` HTTP 401 error response to occur during REST API requests on sites where a plugin or code determines the current WordPress user before WooCommerce is fully initialized.

Based on suggestions and feedback from @ObliviousHarmony (thanks Christopher!)

Closes #26847.

### How to test the changes in this Pull Request:

Please see #26847 for suggested steps to reproduce the bug and test that this change fixes the issue.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix unexpected HTTP 401 `Sorry, you cannot list resources` REST API responses that occur when a plugin or custom code determines the current WordPress user before WooCommerce is fully initialized.

2020-09-11 00:09 UTC, om4james commented
Hi @ObliviousHarmony I'd really appreciate it if you could review this PR as it is based on your ideas and feedback in #26847. 

Thank you 🙏

2020-09-11 00:17 UTC, ObliviousHarmony commented
Hey @om4james,

Sorry for not better communicating my intentions here. This is on my short list to review it had just been a hectic week here in the Pacific Northwest!

2020-09-11 00:19 UTC, om4james commented
No worries at all.

My main aim is to make sure it's on your radar, as I'd love it to be included in WC 5.6.

The issue is affecting some WooCommerce Zapier users, and quite likely a small portion of other REST API users. 

If you need anything from me please let me know.

Thanks

2020-09-15 17:01 UTC, ObliviousHarmony approved these changes, later dismissed
Thanks for this @om4james, everything seems to work as expected. I've left a few thoughts but it looks great!

2020-09-16 11:22 UTC, om4james reviewed
Thanks for your feedback @ObliviousHarmony, I've responded to your comments.
James

2020-09-16 11:22 UTC, om4james commented on includes/class-wc-rest-authentication.php
> +		add_filter( 'rest_authentication_errors', array( $this, 'authentication_fallback' ) );
I think we should use the default priority (of 10) unless there is a technical reason to increase it to 15.

Specifying it as 15 just to match existing code is more of a vanity change that doesn't serve much of a purpose I think.

2020-09-16 11:22 UTC, om4james commented on includes/class-wc-rest-authentication.php
> +	public function authentication_fallback( $error ) {
Are you suggesting that we add the following kind of check (similar to check_authentication_error()) at the beginning of this new authentication_fallback() method above the line 105 if statement?
```
		if ( ! empty( $error ) ) {
			return $error;
		}
```

2020-09-16 14:56 UTC, ObliviousHarmony commented on includes/class-wc-rest-authentication.php
> +	public function authentication_fallback( $error ) {
If another plugin has already explicitly declared a failure we shouldn't waste our time trying to authenticate since the request has already failed.

2020-09-22 08:18 UTC, om4james commented on includes/class-wc-rest-authentication.php
> +	public function authentication_fallback( $error ) {
@ObliviousHarmony good thinking, I've made that change in ce3126045228c88c7f2fffd0785bba50d2dd6751

2020-09-24 03:03 UTC, om4james commented
Hi @ObliviousHarmony ,

This PR is ready for someone else to review. Do you have any suggestions on who might be best to review and approve this so that it can be merged?

Note: The E2E tests are [failing in this PR](https://travis-ci.org/github/woocommerce/woocommerce/jobs/729239026), but they are also [failing in WC master](https://travis-ci.org/github/woocommerce/woocommerce/jobs/729757864). So the changes in this PR aren't causing any additional failures I don't think.

I'd really like to get this into WC 4.6 so that our affected WooCommerce Zapier users (and other REST API users) can benefit from this fix.

Thank you for your time.

James

2020-09-24 19:08 UTC, ObliviousHarmony commented
Hello @om4james,

Unfortunately the PR freeze for 4.6 was last week and so this will have to wait until 4.7. I'll see about getting it a second review though so we can have that committed to.

2020-10-05 17:46 UTC, rrennick commented
@om4james Do you have the steps to test this?

2020-10-05 19:26 UTC, om4james commented
Hi @rrennick issue #26847 explains how to reproduce the bug.

Once you reproduce it against master using those steps, please check out this branch and verify that a 401 no longer occurs.

Thank you

2020-10-07 13:44 UTC, vedanshujain requested changes
Great work and testing well! Needs a small change, and will it be feasible to write some tests for this method.

2020-10-08 01:33 UTC, om4james commented on includes/class-wc-rest-authentication.php
> +				wp_set_current_user( $user_id );
Thanks @vedanshujain , I agree.
Based on https://developer.wordpress.org/reference/hooks/rest_authentication_errors/, I think the correct response is to return true, which indicates that the authentication method was used, and it succeeded.
I've gone ahead and implemented that in 79dd557b7708d0ae37b1ed63cfc3683f4d72c974.

2020-10-08 02:30 UTC, om4james commented
> Great work and testing well! Needs a small change, and will it be feasible to write some tests for this method.

The challenge here is that the [WC_REST_Authentication class currently only has 3% coverage](https://codecov.io/gh/woocommerce/woocommerce/src/master/includes/class-wc-rest-authentication.php), even though the class has existed since WooCommerce 2.6.

The coverage on this class is incidental, there aren't any dedicated tests to test any of the functionality of the `WC_REST_Authentication` class.

I'm all for writing unit tests wherever practical, however in this case I feel as though it may be quite difficult and time consuming to do so.

Is it possible to perform the manual testing of this PR as I've outlined, and get it merged into the upcoming WC 4.7? 

The bug was reported 3+ months ago, and it is potentially affecting many WooCommerce REST API users. It's definitely affecting WooCommerce Zapier users who have reached out to us for support, and we don't currently have a solution or workaround for them until this is merged and released.

Thank you.

2020-10-08 11:01 UTC, vedanshujain approved these changes
LGTM!

2020-10-08 11:02 UTC, merged

2020-10-08 11:36 UTC, om4james commented
Thank you @vedanshujain. And thank you @ObliviousHarmony for your guidance and feedback while we implemented a solution! 💯