Added filter for no stock notification emails
woocommerce/woocommerce pull request #27634
Opened 2020-09-09 19:20 UTC by jondcampbell

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added one new filter so we can do a check before sending the no stock notification. We have some subscription products that are out of stock and we want renewals to work properly but to not have email notifications happening every time the orders go through. This is a kinda related to (and based on): https://github.com/woocommerce/woocommerce/pull/26908

Closes # .

### How to test the changes in this Pull Request:

1. Use the filter to stop the no stock notification emails from happening

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [] Have you successfully run tests with your changes locally?

> New - Add `woocommerce_should_send_no_stock_notification` filter

2020-09-11 16:07 UTC, rrennick requested changes
This should be good to go with the requested changes.

2020-09-11 16:59 UTC, jondcampbell commented on includes/class-wc-emails.php
> +		$should_notify = apply_filters( 'woocommerce_should_send_no_stock_notification', true, $product );
@rrennick I've made the requested changes.

2020-09-11 18:07 UTC, rrennick approved these changes
@jondcampbell Thanks for the quick turn around on the changes. 

**Note** Before merging this the @since will need to be updated to the appropriate version.

2020-09-18 15:05 UTC, rodrigoprimo approved these changes
Looks good to me. Thanks for your contribution.

2020-09-18 15:07 UTC, rodrigoprimo commented
I will merge this and update the version in the `@since` tag in a separate commit.

2020-09-18 15:07 UTC, merged

2020-09-18 15:09 UTC, rodrigoprimo commented
Version updated in commit d99053dbedcaaca04c8ecbb8c8bea6848ee40c19