Fix taxes endpoint not returning multiple postcodes/cities (#27750)
woocommerce/woocommerce pull request #27751
Opened 2020-09-22 18:43 UTC by mahmoudsaeed

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The proposed changes allow the `taxes` endpoint to return an array of postcodes/cities for tax rates with multiple (semi-colon separated) postcodes and/or cities, otherwise a string is returned.

Example response:
```
{
    "id": 5,
    "country": "US",
    "state": "FL",
    "postcode": [
        "32789",
        "33255"
    ],
    "city": [
        "MIAMI",
        "ORLANDO"
    ],
    "rate": "6.0000",
    "name": "US FL",
    "priority": 30,
    "compound": true,
    "shipping": true,
    "order": 4,
    "class": "standard",
    "_links": {
        "self": [
            {
                "href": "http://wordpress.local/wp-json/wc/v3/taxes/5"
            }
        ],
        "collection": [
            {
                "href": "http://wordpress.local/wp-json/wc/v3/taxes"
            }
        ]
    }
}
```

Closes #27750 .

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2021-01-19 14:39 UTC, Konamiman requested changes
Hi @mahmoudsaeed, thank you for your contribution. I've tested your changes and they work as expected, however there's a problem with your approach: modifying the type of an existing field of the response is a breaking change and could cause trouble to clients (which could be assuming that a string is always returned).

Therefore I would suggest the following changes to your pull request:

1. Leave the current `postcode` and `city` fields untouched. We'll mark these as deprecated.
2. Add two new fields: `postcodes` and `cities` - note that they are in plural. Make those always return an array, even when there's just one value to return or there is nothing to return at all (empty array in the later case).

Please note that 2 should be implemented in the v3 class (`includes/rest-api/Controllers/Version3/class-wc-rest-taxes-controller.php`) instead of the v1 class, since older versions of the API shouldn't change. This will probably mean that you'll need to extract some portions of the original code from v1 into protected methods that will be overriden in the v3 class.

Once you have applied these changes please ping me and I'll be glad to review your pull request again.

2021-03-15 20:22 UTC, mahmoudsaeed commented
Thanks @Konamiman for reviewing this. I have made the requested changes.

2021-03-23 15:37 UTC, Konamiman approved these changes

2021-03-23 15:48 UTC, Konamiman commented
Hi @mahmoudsaeed, sorry for the delay. I've re-reviewed and approved the pull request, also I've edited the description to introduce testing instructions (which replace your "example output") and a changelog entry to conform to our standards. I'll merge as soon as the CI checks are good.

2021-03-23 16:04 UTC, merged