remove woocommerce_form_field radio type input label content HTML esc…
woocommerce/woocommerce pull request #27816
Opened 2020-09-30 16:40 UTC by anttiruonakoski

…aping. fixes #26865

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Label content for input elements of radio type will be no longer HTML escaped when inputs are outputted by woocommerce_form_field(). This enables for example to style label content with any tags as span. Currently, styling is not possible, because output is forced as plain text. 

Closes #26865 .

### Other information:

* [ x ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2020-10-01 20:50 UTC, claudiosanches requested changes

2020-10-01 20:50 UTC, claudiosanches commented on includes/wc-template-functions.php
> +						$field .= '<label for="' . esc_attr( $args['id'] ) . '_' . esc_attr( $option_key ) . '" class="radio ' . implode( ' ', $args['label_class'] ) . '">' . $option_text . '</label>';
We still need to keep some escaping, so probably better to use `wp_kses_post()` that will allow some HTML.

```suggestion
						$field .= '<label for="' . esc_attr( $args['id'] ) . '_' . esc_attr( $option_key ) . '" class="radio ' . implode( ' ', $args['label_class'] ) . '">' . wp_kses_post( $option_text ) . '</label>';
```

2022-06-23 12:14 UTC, jorgeatorres commented
Hi @anttiruonakoski,

Thanks for your contribution and apologies for the delay in getting back to you.

Overall this looks good but there are some conflicts that need to be resolved. Would you please rebase this branch to fix the conflicts? Also, even though the goal here is sort of clear, it'd be great to have some testing instructions (a snippet of code) to be able to properly test.

I can see it's been a while since you last worked on this, so please let us know if you're no longer interested or if you have any questions.

Thanks again!

2022-07-05 14:24 UTC, peterfabian commented
Hi @anttiruonakoski ! Please let us know if you still want to update the PR based on @jorgeatorres 's comment. If not, we can take over. Thanks! 

Side note for next reviewer: we should double check the set of HTML tags we want to allow here.

2022-09-01 10:12 UTC, kaushikasomaiya commented
Can anyone confirm if the radio field type supports validation `required` in WooCommerce?

2022-09-02 09:28 UTC, peterfabian commented
@kaushikasomaiya Can you please elaborate? Looking at the mozilla docs, this is what they say about required + radio:

> In the case of a same named group of [radio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio) buttons, if a single radio button in the group has the required attribute, a radio button in that group must be checked, although it doesn't have to be the one with the attribute is applied. So to improve code maintenance, it is recommended to either include the required attribute in every same-named radio button in the group, or else in none.

As I understand it, the validation happens in the browser, not within WooCommerce?

2022-09-02 11:29 UTC, kaushikasomaiya commented
> As I understand it, the validation happens in the browser, not within WooCommerce?

@peterfabian I will do a test and get back to you. WooCommerce doesn't use HTML5 browser validation, it has its own validation. Last time I did some tests with user's code [here](https://wordpress.org/support/topic/checkout-woocommerce-invalid-class-for-radio/), I wasn't able to get the radio field validated.

But I will do some more tests to confirm it.

2022-10-18 14:45 UTC, Konamiman commented
Assigning a reviewer from Proton so that we can continue taking a look at this.

2023-05-01 07:32 UTC, samueljseay commented
We are closing this pull request, as the last activity has been quite some time ago and we have not received a response from you. If you are still interested, please open another PR based on a recent version of the trunk branch.

cc @vedanshujain @Konamiman

2023-05-01 14:24 UTC, vedanshujain commented
This will need a new PR to apply the changes against trunk since current changes are pre-monorepo. Re-opening anyway to track that work.

2023-05-03 21:06 UTC, jonathansadowski commented
@vedanshujain,

Thanks for the follow-up. I'm going to close this, as we're trying to reduce the number of open PRs that aren't immediately actionable. Please create an issue or a new PR if you'd like to track this as opposed to re-opening this PR.

2023-05-03 21:06 UTC, closed without merging