Fixed: If product is virtual, shipping content dosn't hide
woocommerce/woocommerce pull request #27889
Opened 2020-10-06 02:32 UTC by Knyazevich

Fix the issue when a user makes a product virtual on the "Shipping" tab and still able to edit dimensions and other shipping data.

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #27574.

### How to test the changes in this Pull Request:

1. Go to the product editing screen, scroll to the "Product data" metabox;
2. Make sure that the product is simple;
3. Click the "Shipping" tab;
4. Click "Virtual:" checkbox.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Hide "Shipping" panel after making a product virtual.

2020-10-06 02:37 UTC, Knyazevich commented
**To the reviewer:** I will be very appreciated if you add the `hacktoberfest-accepted` label to this PR in case if it looks ok generally for you :slightly_smiling_face:

2020-10-09 20:38 UTC, claudiosanches requested changes
Works great, thanks for your help!
But there's a minor coding standard issue to fix.

2020-10-09 20:38 UTC, claudiosanches commented on assets/js/admin/meta-boxes-product.js
> +			if ('block' === $( $shipping_tab ).css( 'display' )) {
```suggestion
			if ( 'block' === $( $shipping_tab ).css( 'display' ) ) {
```

2020-12-05 18:33 UTC, rodrigoprimo commented
Closing as this was fixed in #28414.

2020-12-05 18:33 UTC, closed without merging