Fire after_password_reset during the my-account/lostpassword flow
woocommerce/woocommerce pull request #28077
Opened 2020-10-23 15:45 UTC by loranallensmith

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a call to the WordPress hook `after_password_reset` to the `reset_password` function that runs when a user requests a password reset via the `my-account/lost-password` flow.  I noticed that #27864 focuses on this flow as well, but this change seems to address a different underlying issue.  Still, it would be worth checking to see if firing this action here results in the same doubled-notification bug mentioned in #27864.  I didn't see it on my end.

Closes #27795.

### How to test the changes in this Pull Request:

1. I tested this with a simple listener snippet.

```
function test_after_password_reset_hook() {
	error_log("The after_password_reset hook has fired.");
}
add_action('after_password_reset', 'test_after_password_reset_hook');
```

After going through the `lost-password` flow, there is an entry in my `debug.log` file showing that the hook fired.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fire the WordPress `after_password_reset` action when a user resets their password via `my-account/lost-password`

cc: @jackmcconnell, @jvdl-1

2020-10-23 20:41 UTC, claudiosanches approved these changes
Hello @loranallensmith, thanks for sending this PR, but this code still introduces the same problem like in #27864, in fact I prefer if we could use the `reset_password` instead, but the real issue here is the `after_password_reset` hook, since WP core uses it to send a notification:

https://github.com/WordPress/WordPress/blob/d6cff7965a10c89e629a87eb6e4ecb0ed9614d50/wp-includes/default-filters.php#L458

So on this code there's two notifications now. I just tested and I'm getting the email twice, like in #27864

2020-10-23 20:41 UTC, claudiosanches requested changes
Sorry, I sent my first commit with an incorrect status. :smile:

2020-10-27 15:56 UTC, loranallensmith commented
@claudiosanches Thanks for testing this out and letting me know about how that notification hook is wired up in WP. 🙌 

I think I'll close this PR out for now and then maybe work with the developer in #27795 to figure out alternate solutions. :smiley:

2020-10-27 15:56 UTC, closed without merging

2021-03-05 23:58 UTC, EngKhaledB commented
Hi @loranallensmith. @claudiosanches
WooCommerce is already hooking the customer password reset with this action: `woocommerce_customer_reset_password` on https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-form-handler.php#L1054
It fires the hook after a successful password reset. So, I see there is no need to define new hooks.
I hope this help :).