Replace usages of depracted jQuery.fn.click() event shorthand
woocommerce/woocommerce pull request #28332
Opened 2020-11-18 18:23 UTC by rodrigoprimo

### Changes proposed in this Pull Request:

This PR replaces all instances in the WooCommerce codebase where `jQuery.fn.click( handler )` event shorthand was used with `jQuery.fn.on( 'click', handler )`. This event shorthand was deprecated in jQuery 3.3 (see https://github.com/jquery/jquery/issues/3214). The jQuery documentation was not updated yet (see https://github.com/jquery/jquery-migrate/issues/288 and https://github.com/jquery/api.jquery.com/issues/972).

jQuery.click() was not deprecated, and so it was not replaced.

For context on why we are doing this change, see #28286 and #28285.

### How to test the changes in this Pull Request:

For testing this PR, I suggest checking the code changes and making sure they make sense, and testing that the functionality of some of the changes was not affected and the old behavior was preserved. IMO, it is unnecessary to test all the changes as this would take a significant amount of time.

### Changelog entry

> Dev: replaces deprecated `jQuery.fn.click( handler )` with `jQuery.fn.on( 'click', handler )`

2020-12-04 20:49 UTC, roykho requested changes
Sorry for the late review as I didn't see a ping about this. Just some coding standard changes needed.

2020-12-04 20:49 UTC, roykho commented on assets/js/admin/meta-boxes-order.js
> +			$( '#woocommerce-order-actions input, #woocommerce-order-actions a' ).on('click', function() {
A space is needed after the `on(` function

2020-12-04 20:49 UTC, roykho commented on includes/admin/reports/class-wc-report-coupon-usage.php
> +			jQuery('.section_title').on('click', function(){
A space is needed after the `on(` function

2020-12-04 20:49 UTC, roykho commented on includes/admin/reports/class-wc-report-sales-by-product.php
> +			jQuery('.section_title').on('click', function(){
A space is needed after the `on(` function

2020-12-05 14:14 UTC, rodrigoprimo commented
Thanks for the review, @roykho. I pushed a new commit fixing the issues that you mentioned. For consistency, I added spaces where needed to the rest of the JS blocks that were modified in this PR.

2020-12-07 14:03 UTC, roykho approved these changes
LGTM!

2020-12-07 14:03 UTC, merged