Add notice to deprecate old reports closes #27789
woocommerce/woocommerce pull request #28799
Opened 2021-01-12 15:39 UTC by roykho

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #27789

### How to test the changes in this Pull Request:

1. Go to the "legacy" woocommerce->reports.
2. Ensure you're seeing a notice that the report is being replaced with links to documentation and the new analytics page.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

* Add - Notice to deprecate legacy reports in favor of the newer analytics page.

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-01-13 14:46 UTC, peterfabian requested changes
Looks good to me, thanks! 

One small issue: it doesn't show up for me on the Stock report. I think we should include it over there, too.
<img width="1356" alt="Screenshot 2021-01-13 at 15 45 51" src="https://user-images.githubusercontent.com/2207451/104467383-8f35ab00-55b6-11eb-9963-d6ee611de800.png">

2021-01-13 14:46 UTC, peterfabian commented on includes/admin/views/html-report-by-date.php
> +		?>
I've submitted a rewording of the docs to the following new text:


> With the release of WooCommerce 4.0 in March 2019, these reports are deprecated and won’t receive further updates.
> There is a new and better Analytics section available for users running WordPress 5.3+. Learn more about the new reports and admin experience in the WooCommerce Analytics documentation.

So if it gets approved, we can also change it here.

2021-01-13 16:19 UTC, roykho commented
I've updated the code to show up on top of the page which will show on every reports page. This should be more clear and consistent across the pages.

2021-01-14 10:38 UTC, peterfabian requested changes
Thanks, I can see it being displayed on all the required pages 👍 
Being at the top, though, it overlaps with Help button. Can you please make it not overlap?
<img width="1305" alt="Screenshot 2021-01-14 at 11 36 03" src="https://user-images.githubusercontent.com/2207451/104580036-0f165080-565d-11eb-9a20-f28f559294ea.png">

2021-01-14 18:04 UTC, peterfabian approved these changes
Works great now, thanks!

2021-01-14 18:05 UTC, merged

2021-01-14 18:06 UTC, peterfabian commented
I've added label release highlight here as I think we should explicitly mention this in the dev blog post.

2021-02-09 23:19 UTC, jsmusiker commented
@roykho if you are removing Legacy Reports, what about the “Profit” reports that are part of the Cost of Goods plugin? I could be wrong but I haven’t seen anything related to Profit or Inventory Value in the new Reports.

2021-02-10 00:04 UTC, roykho commented
Hi @jsmusiker - we're not removing it at this time. It is a soft deprecation. Meaning we're urging people to start using the newer analytics pages. The legacy reports will still live around either under a flag in the future or could be a separate plugin but we will decide that later.

2021-02-10 00:12 UTC, jsmusiker commented
Ok @roykho thank you for replying! Just making sure you all are aware of the Cost of Goods Reports! I feel like it’s not that well known that the Reports are even there.  And didn’t want them to be lost, because they are very helpful. Just so we are on the same page, I’m talking about the Cost of Goods Plugin sold on WC, but Developed by SkyVerge.