Add 'woocommerce_review_order_before_payment_methods' action in 'payments.php'
woocommerce/woocommerce pull request #28846
Opened 2021-01-19 05:31 UTC by franticpsyx

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added `woocommerce_review_order_before_payment_methods` action in `payments.php` template.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Added 'woocommerce_review_order_before_payment_methods' action in 'payments.php' template.

2022-06-23 12:37 UTC, jorgeatorres requested changes
Hi @manospsyx!

Thanks for the PR 😺.

Overall this looks good, but it needs to be rebased to fix conflicts before we can merge and a docblock needs to be added for the new action.
Also, for context, it'd be great if you described the use case here and possibly add some testing instructions or a snippet to the PR.

Thanks again!

2022-06-23 12:37 UTC, jorgeatorres commented on templates/checkout/payment.php
> +	<?php do_action( 'woocommerce_review_order_before_payment_methods' ); ?>
Can we please add a docblock for this new action?

2023-03-10 17:43 UTC, jorgeatorres commented
Closing due to inactivity. @manospsyx: please let me know if your team still needs this change and I'll happily take over.

2023-03-10 17:43 UTC, closed without merging

2023-03-11 08:43 UTC, manospsyx commented
@xristos3490 do you still need this one?