Tracker return string values
woocommerce/woocommerce pull request #28893
Opened 2021-01-22 05:18 UTC by menakas

### All Submissions:
Just before merging #28584, @peterfabian  made an observation [here](https://github.com/woocommerce/woocommerce/pull/28584#pullrequestreview-571110861) about the type of the values returned.

On verifying with test data, I found that  the non-string values were not logged by the tracker. So, this pull request converts all the values calculated in the `get_orders()` function into string.

In addition, I've added code to ensure that default value for first and last order dates are not returned.

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1. Opt to share usage data on a test site.
2. Trigger a snapshot send using `WC_Tracker::send_tracking_data(true)`
3. Verify the values in Tracker after a day. 
4. On master, I could find only 4 values(the first and last order dates which are string). With this branch, I'm expecting to find all the values. I shall confirm this.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.
Ensure that all tracker values collected for orders are of string type.

2021-01-27 09:14 UTC, peterfabian requested changes
Looks good, thanks! I haven't checked the tracker yet, will need to wait until tomorrow, but the data is sent as strings. I just have 2 small items of feedback that might need addressing. 

I was curious about the data types of other pieces of data we send, so I checked if there's any other data we send to tracker as integers and it seems like there is, e.g.:
<img width="414" alt="Screenshot 2021-01-27 at 10 08 50" src="https://user-images.githubusercontent.com/2207451/105969007-0e7fb000-6088-11eb-9c3f-980c61de76e3.png">

Looking at tracker in Hue, though, I can see e.g. `users_customer (int)`, so some of them are `int`. I guess that means that the data type we send from WC must match the data type in the database, is that correct? Just trying to understand how this works.

2021-01-27 09:14 UTC, peterfabian commented on includes/class-wc-tracker.php
> +		return array_map( 'strval', $order_data );
Based on [this WP core ticket](https://core.trac.wordpress.org/ticket/42918), it might be better to use `(string)` type casting for type conversion.

2021-01-27 09:30 UTC, peterfabian commented
Actually, looking into Hue some more, I can see that some data points from orders are typed as `double` (I'm looking at wctracker_snapshots), so I'm slightly confused about how the data gets through and ends up being typed in the way it does in the end.

![Screenshot 2021-01-27 at 10 25 49](https://user-images.githubusercontent.com/2207451/105971117-70411980-608a-11eb-8d22-aa21fe3573c7.png)

2021-01-27 09:49 UTC, peterfabian commented
Sorry, one more thing, I'm getting these warnings on a new site:
```
Notice: Undefined variable: order_data in /srv/users/userff53baab/apps/userff53baab/public/wp-content/plugins/woocommerce/includes/class-wc-tracker.php on line 465

Warning: array_map(): Expected parameter 2 to be an array, null given in /srv/users/userff53baab/apps/userff53baab/public/wp-content/plugins/woocommerce/includes/class-wc-tracker.php on line 465
```

So there are some edge cases that should be handled.

2021-01-27 12:55 UTC, menakas commented
>so I'm slightly confused about how the data gets through and ends up being typed in the way it does in the end.

The date first gets captured in the `wctracker` database, and then gets transformed with a SQLT into the `woocommerce_data` database (`wctrackersnapshots`).

2021-01-27 13:47 UTC, menakas commented
I don't understand why Travis is failing Code Standard for this file `includes/admin/class-wc-admin-notices.php` here.

2021-01-27 16:16 UTC, peterfabian commented on includes/class-wc-tracker.php
> +		return array_map( 'strval', $order_data );
Good point, I haven't noticed that. Either way it's fine for me, it's a small difference.

2021-01-28 12:16 UTC, peterfabian approved these changes
Looks good, thanks!

2021-01-28 12:17 UTC, merged