Wc 25076 wc emails in hebrew
woocommerce/woocommerce pull request #28934
Opened 2021-01-25 21:48 UTC by mfs-mindsize

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR aims to resolve the bugs raised in WC issue:

"CSS fix for WooCommerce emails in `Hebrew` on mobile devices" #25076

[https://github.com/woocommerce/woocommerce/issues/25076](https://github.com/woocommerce/woocommerce/issues/25076)

Note: Best I could tell, the underlying markup + CSS "defects" impact more than rtl. Therefore, what you see in terms of changes might not be what you're expecting.  

Also, while I was under the hook I added escaping output where appropriate.

### How to test the changes in this Pull Request:

You'll have to be able to send test emails.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Fixed email header and CSS that was buggy for rtl emails (Issue #25076)

2021-01-26 13:36 UTC, rrennick commented
@mfs-mindsize The `Closes #{issue-number}` is in the PR template because Github has an automation for that pattern which automatically closes the issue when the PR is merged. Can you edit your PRs and add the `Closes #` back?

2021-01-27 18:52 UTC, mfs-mindsize commented
@rrennick - Updated. Sorry 'bout that. Now I know :)

2021-01-29 15:24 UTC, roykho commented on templates/emails/email-header.php
> +		<title><?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?></title>
This is the wrong use of escaping here. Should be `esc_html()`. I see other areas in this PR doing the same as well.

2021-02-01 08:16 UTC, vedanshujain reviewed
I am not able to repro the issue, so have asked for additional details for helping reproduce in https://github.com/woocommerce/woocommerce/issues/25076#issuecomment-770662701.

Thanks for fixing the code standard violations along with the bug fix.

2021-02-09 08:29 UTC, vedanshujain requested changes
@mfs-mindsize I was able to reproduce this in android gmail, unfortunately does not looks like this PR fixes this issues. I can still reproduce the incorrect formatting after applying the patch.

Based on a cursory look, it seems like you have missed setting the max width on footer, which is causing the table to expand and then entire container div to expand. Can you add the max-width prop in footer as well like you did for body and header?

Thanks for helping out!

2023-05-01 07:42 UTC, samueljseay commented
We are closing this pull request, as the last activity has been quite some time ago and we have not received a response from you. If you are still interested, please open another PR based on a recent version of the trunk branch.

2023-05-01 07:42 UTC, closed without merging