Fixed logged-in users are able to access reset password page.
woocommerce/woocommerce pull request #29164
Opened 2021-02-18 09:23 UTC by sun

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #28956

### How to test the changes in this Pull Request:

1. Log in as a customer.
2. Access the user password reset page.
3. You should not see the form, but be redirected to the user dashboard. But the user can actually access the form.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed logged-in users are able to access reset password page.

2021-02-23 20:15 UTC, sun commented
The build failure does not seem to be related to the change in this PR.

2021-03-04 15:16 UTC, roykho commented
Hi @sun - thanks for the PR. With this change, it is confusing to see the title `Lost Password` when there is no action you can take for it. I think if a customer intentionally visits that URL, there may be some issue with their password or they want to change it. So perhaps in addition to your change, redirect them to the `Account Details` page so they can set their new password?

2021-03-08 19:20 UTC, sun commented
Hm, I guess you're right. But then I begin to wonder why the logic of the control structure was  substantially changed in the first place. The password reset page behavior seemed to have worked fine in the past.

I wonder whether all of this is caused by an unnecessary additional "cleanup" of the code in the controller as part of a PR that intended to do something less invasive. I guess we need to check the history of the file to find out 🤔

2021-05-17 18:31 UTC, claudiosanches requested changes
Hello @sun ,

Thanks for your help, but this code introduces some bugs in the `/my-account/` page, could you please check my comment about it?

2021-05-17 18:31 UTC, claudiosanches commented on includes/shortcodes/class-wc-shortcode-my-account.php
> +		if ( ! is_user_logged_in() && isset( $wp->query_vars['lost-password'] ) ) {
It introduces a bug, now there's no more a login form, everyone that tries to access `/my-account/` will see the sidebar and all items like they are logged in.

2023-05-02 03:29 UTC, samueljseay commented
We are closing this pull request, as the last activity has been quite some time ago and we have not received a response from you. If you are still interested, please open another PR based on a recent version of the trunk branch.

2023-05-02 03:29 UTC, closed without merging