add portugal states
woocommerce/woocommerce pull request #29586
Opened 2021-04-03 23:12 UTC by masteradhoc

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add States based on Issue #29206
Closes #29206 .

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [-] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> add portugal states

2021-04-06 19:56 UTC, claudiosanches requested changes
Thanks for your help.

But there's some issues with this change since is using ISO and based in the wikipedia instead of the CLDR as recommended in this file header.

Please replace all names to match with those: https://github.com/unicode-org/cldr/blob/release-38-1/common/subdivisions/en.xml#L4139-L4159

2021-04-06 20:19 UTC, masteradhoc commented
@claudiosanches thanks for your comment. to help get this merged quickly i've made the adjustments and also fixed the codesnif - hopefully ;)

2021-04-07 15:26 UTC, claudiosanches requested changes
Sorry, I meant only the names of the states, the previous codes as already fine, please replace `pt` to `PT-`.

2021-04-07 16:30 UTC, claudiosanches commented on i18n/states.php
> +	'PT' => array( // Portugal states.
```suggestion
	'PT' => array( // Portugal states. Ref: https://github.com/unicode-org/cldr/blob/release-38-1/common/subdivisions/en.xml#L4139-L4159
```

2021-04-07 16:31 UTC, claudiosanches approved these changes
Thank you very much!

2021-04-07 16:31 UTC, merged