Add action hooks to WooCommerce email trigger function. Resolves #24641
woocommerce/woocommerce pull request #29711
Opened 2021-04-17 16:32 UTC by EdithAllison

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds an action hook to the email trigger. This allows developers to run their own code after the sending of a WooCommerce email is triggered. Action hook includes send result (true / false) and the email object. 

Sample use case: Allows inserting a note into order when an email is sent so customer service can easily see which emails have been sent by the plugin to the customer. 

Closes #24641

### How to test the changes in this Pull Request:

1. Add action to the theme's functions.php file. A simple test case would be to write to debug log when email is being sent:

add_action('woocommerce_email_trigger_new_order_order', 'agentur_neworder', 20, 2 );

function agentur_neworder($result, $email) {
	error_log('NEW ORDER RESULT: ' . $result);
	error_log( print_r($email, true) );
}

2. Place a new order
3. Check debug log. If successful it will contain the result note and email object. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> New action hook for email trigger function which allows developers to run their own code after Woo emails are triggered.

2021-05-17 18:15 UTC, claudiosanches requested changes
Hello @EdithAllison,

Thanks for your help, in generally looks good, nice choice for naming all those actions, but there's some small tweaks in the code missing before we can merge this PR.

2021-05-17 18:15 UTC, claudiosanches commented on includes/emails/class-wc-email-cancelled-order.php
> +				$result = ( $this->send( $this->get_recipient(), $this->get_subject(), $this->get_content(), $this->get_headers(), $this->get_attachments() ) ) ? true : false;
By default `WC_Email->send()` returns boolean, so there's no need to any extra code:

```suggestion
				$result = $this->send( $this->get_recipient(), $this->get_subject(), $this->get_content(), $this->get_headers(), $this->get_attachments() );
```

2021-05-18 08:59 UTC, EdithAllison commented
@claudiosanches Many thanks for considering this PR, completely agree with code simplification. I've updated the PR as suggested 👍

2021-06-17 15:26 UTC, claudiosanches requested changes
Hello @EdithAllison,

I'm checking here, why not changing `WC_Email->send()` method instead? So will be required just one hook for all emails, since all email classes extend `WC_Email` as well.

2021-06-17 15:42 UTC, claudiosanches commented
I wrote a new PR with just one hook that may help: https://github.com/woocommerce/woocommerce/pull/30123
I'm going to close this PR for now.
Thanks.

2021-06-17 15:42 UTC, closed without merging

2021-06-18 09:49 UTC, EdithAllison commented
@claudiosanches Noted. I didn't realised Woo was using its own email class, I wrongly assumed it was using WP core email functionality. Agree that a single change to Woo email class is a better implementation, thank you for taking the time to review and create a PR.