Move Tracker to use direct sql queries
woocommerce/woocommerce pull request #29877
Opened 2021-05-11 12:25 UTC by menakas

WIP

Fix for #29839 

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-05-11 22:27 UTC, deltaWhiskey commented
Checking the performance of `WC_Tracker::get_orders()` on a test store with 28,608 orders, 100 products, and 1,000 customers:
* the version in this PR finished in 0.005 to 0.008 seconds
* WooCommerce 5.1.1 (with CRUD functions) ran for 12-24 seconds, then exited with an out of memory error, having used just under 1 GB RAM
* WooCommerce 5.0.0 (before the CRUD functions were added) finished in 0.005 to 0.007 seconds.

2021-05-11 22:34 UTC, deltaWhiskey commented
The WC Tracker snapshot generated by this PR was compared to that generated by WooCommerce 5.2.2, and was mostly the same. The differences seem acceptable to me. They were:
* This restores a pre-5.1.0 behavior when reporting order counts by status; this includes order statuses that have zero orders, while 5.2.2 omits them.
* This restores a pre-5.1.0 behavior for reporting certain money amounts; it uses a floating point number instead of limiting the precision.
* Version 5.2.2 reported order breakouts by gateway with keys like `gateway_paypal`. This version reports them like `gateway_paypal_USD_count` and `gateway_paypal_USD_total`.

2021-05-12 20:23 UTC, roykho requested changes
Nice work. I see you've removed the deprecated `get_order_totals` method. Will this pose BW compatibility issue?

Other than that, I left some comments on coding standards.

2021-05-12 20:23 UTC, roykho commented on includes/class-wc-tracker.php
> +	 * Get order counts
Needs full stop at the end of sentence.

2021-05-12 20:23 UTC, roykho commented on includes/class-wc-tracker.php
> +	 * Get order totals
Needs full stop at the end of sentence.

2021-05-12 20:23 UTC, roykho commented on includes/class-wc-tracker.php
> +	 * Get last order date
Needs full stop at the end of sentence.

2021-05-12 20:23 UTC, roykho commented on includes/class-wc-tracker.php
> +	 * Get order details by gateway
Needs full stop at the end of sentence.

2021-05-12 21:27 UTC, deltaWhiskey commented
Thanks for the review, @roykho !

Removing `get_order_totals()` looks safe to me. It was made public in #22807 , but then that code was removed in #23302 .

Coding standard fixes have been applied.

2021-05-12 21:53 UTC, roykho approved these changes
LGTM! Thanks for the PR!

2021-05-12 21:53 UTC, merged