Show variations in upsells when parent is not published
woocommerce/woocommerce pull request #30042
Opened 2021-06-04 10:56 UTC by Dekadinious

I was struggling to get the upsell section to show for our eCommerce site. After some digging I found that line 1525 stopped variations from showing in the upsell section if the parent product was set to privately published. This makes testing products and upsells hard, and it's inconsistent behaviour when simple products that are privately published do show up. The proposed change will make variations show up as long as the current user can edit the parent product. This is consistent with the behaviour for simple products.

### All Submissions:

* [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

2021-08-06 10:22 UTC, vedanshujain commented
@Dekadinious thanks for the PR, your changes make sense on first look, but can you please the template along with testing instructions so that we can check better. Thanks!

2021-08-06 10:54 UTC, Dekadinious commented
> @Dekadinious thanks for the PR, your changes make sense on first look, but can you please the template along with testing instructions so that we can check better. Thanks!

I am not sure what you mean with the template in your comment. It's not really hard to test. Make a private product. Add some products as upsells for that product and make sure that the upsells are also private products. Now go front end. The upsells do not appear, so you can't test how they look, because the code does not allow for private upsells.

2021-08-11 10:18 UTC, Dekadinious commented
@vedanshujain Sorry, I forgot to tag you :)

2023-11-21 14:45 UTC, jorgeatorres requested changes
Hi @Dekadinious!

Thanks for your contribution. This does seem like a good addition, but given it's been open for a while (apologies for the delay!), there are some conflicts with `trunk` that need to be resolved.

If you're still willing to work on this, would you mind rebasing or refreshing this branch? If you're short on time, please say so and we'll take care of getting it across the finish line.

Also, as @vedanshujain asked, it'd be good to have proper testing instructions as part of the first comment in the PR. We ask that every PR includes testing instructions for future reference.

Looking forward to hearing back from you.

2023-11-27 08:41 UTC, Dekadinious commented
It seems the conflicts are too complex to solve in the web editor according to Github, and I do not have this branch/pull request/code base in my development environment. Would you mind helping me?

2023-11-30 15:41 UTC, jorgeatorres commented
Hi @Dekadinious,

I've rebased your branch with the latest `trunk` and conflicts have been fixed. We still need testing instructions and a changelog file.
Would you be able to add some testing instructions to the original comment? I can add the changelog file if you want.

Please let me know!

2023-12-01 08:28 UTC, Dekadinious commented
I tried adding testing instructions. I don't know if they are up to standards as these are my first. You can add to the changelog for me :) @jorgeatorres

2023-12-01 16:04 UTC, jorgeatorres approved these changes
LGTM.

2023-12-01 17:08 UTC, merged