Exclude block templates from showing up in product edit page
woocommerce/woocommerce pull request #30138
Opened 2021-06-21 18:42 UTC by Aljullu

This PR hooks into the [`theme_product_templates` filter](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/class-wp-theme.php#L1297) in order to filter out block-based templates from appearing as template options in the product edit page. This way, templates created with the template editor included in WP 5.8 do not appear in the product edit page.

The rationale is that currently WooCommerce relies on PHP templating to format the product page so templates chosen from that selector have no effect in the frontend of classic themes.

In the future, we might enable the selector again for block-based themes. But that would require some investigation on how we can ensure only templates relevant to products show up in the selector (related issue in Gutenberg: https://github.com/WordPress/gutenberg/issues/31704).

Closes #30136.

### How to test the changes in this Pull Request:

Requisites:
* WP 5.8 or Gutenberg plugin enabled.
* A classic theme.

Steps:

1. Go to create a new page, in the sidebar, create a new template:<br>
![](https://user-images.githubusercontent.com/3616980/122780878-8ce72380-d2af-11eb-8491-700c128cafe9.png)
2. Make some edits and click on Publish. Make sure the template you created is marked for publishing:<br>
![](https://user-images.githubusercontent.com/3616980/122781013-b0aa6980-d2af-11eb-90db-2e365137f857.png)
3. Now, go to edit a product.
4. Verify there is no metabox in the sidebar that lets you change the template.<br>
![](https://user-images.githubusercontent.com/3616980/122781187-dafc2700-d2af-11eb-8d8a-3b8f492acbe3.png)<br>
<i>(this is what you shouldn't see)</i> :point_up_2: 

### Changelog entry

> Exclude block templates from showing up in product edit page

2021-06-25 08:11 UTC, vedanshujain approved these changes, later dismissed
LGTM and working as expected. I will leave it for @nerrad to do a final review before merge.

2021-06-25 12:29 UTC, nerrad requested changes
I left a comment that should probably be addressed before merging (assuming the `gutenberg_get_block_template` function only appears in WP 5.8+).

Also, I didn't verify, but I'm assuming this filter is only executed on WC Admin product editor routes?

Other than the above, this looks great!

2021-06-25 12:29 UTC, nerrad commented on includes/admin/class-wc-admin-meta-boxes.php
> +			$gutenberg_template = gutenberg_get_block_template( $theme . '//' . $template_key );
Is this function WP version specific? If so, there should probably be a `function_exists` check before calling it (maybe in the initial check at the beginning of the function logic)?

2021-06-29 11:24 UTC, frontdevde commented
Tested as per testing instructions and it worked as expected for me. 

|before|after|
|-|-|
|<img width="303" alt="Screenshot 2021-06-29 at 12 36 06" src="https://user-images.githubusercontent.com/1562646/123789212-34caa580-d8dd-11eb-889c-f3f9b58406a1.png">|<img width="300" alt="Screenshot 2021-06-29 at 12 36 41" src="https://user-images.githubusercontent.com/1562646/123789230-38f6c300-d8dd-11eb-8375-667c7b26241c.png">|

> there should probably be a function_exists check before calling it (maybe in the initial check at the beginning of the function logic)

As Albert is AFK at the moment, I added a small commit that hopefully addresses Darren's comment (who is AFK as well). As suggested, I added a check to test if the `gutenberg_get_block_template` function exists at the beginning of the function logic.

> Also, I didn't verify, but I'm assuming this filter is only executed on WC Admin product editor routes?

During my testing, that appeared to be the case, yes.

2021-06-29 11:35 UTC, nerrad approved these changes
Thanks for the changes @frontdevde - looks good to me 👍🏻

2021-06-29 11:42 UTC, merged