Add new hook to order-tracking form
woocommerce/woocommerce pull request #30320
Opened 2021-07-20 06:37 UTC by erikdemarco

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add additional hook for order tracking, So developer can add additional field for example adding captcha field.

2022-03-23 16:40 UTC, jorgeatorres requested changes
Hi @erikdemarco!

Thanks for your contribution 💯. The new hooks make perfect sense and would be a welcome addition.
The only thing we'd like to address before merging is to [add a docblock](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters) to each new action.

Once that's done, we should be good to go 👍.

2022-03-23 16:40 UTC, jorgeatorres commented on templates/order/form-tracking.php
> +	<?php do_action( 'woocommerce_order_tracking_form_start' ); ?>
Missing docblock.

2022-03-23 16:40 UTC, jorgeatorres commented on templates/order/form-tracking.php
> +	<?php do_action( 'woocommerce_order_tracking_form' ); ?>
Missing docblock.

2022-03-23 16:40 UTC, jorgeatorres commented on templates/order/form-tracking.php
> +	<?php do_action( 'woocommerce_order_tracking_form_end' ); ?>
Missing docblock.

2022-03-24 00:17 UTC, erikdemarco commented
@jorgeatorres is it already good?

2022-04-05 17:12 UTC, jorgeatorres approved these changes
Hi @erikdemarco,

Thanks for your contribution! I pushed some tiny changes to add some more context to the docblocks, but this is now good to go.

Thanks again! 💯

2022-04-05 18:10 UTC, merged