Add mobile data to WCTracker
woocommerce/woocommerce pull request #30415
Opened 2021-08-03 21:02 UTC by joshbetz

Adds an endpoint to consolidate the data that is needed every time the
app is opened instead of relying on multiple endpoints.

This is also a good place to include some basic mobile data usage in
WCTracker. We track each platform independently, so we can see which
versions of the apps are used on a given site.

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2021-10-01 21:56 UTC, jonathansadowski requested changes
Sorry for the delay in reviewing this. I commented about some comments/docblocks that seem to be inaccurate / need updating, otherwise this tested well for me.

I do have some inarticulable pause about adding telemetry to the v3 namespace. I do wonder if it makes sense to place it in some other namespace. Placing it there really encourages its usage outside of the apps, in my mind... but I'm not sure if that's just me. /cc @vedanshujain did you have any opinions in that regard?

2021-10-01 21:56 UTC, jonathansadowski commented on includes/rest-api/Controllers/Version2/class-wc-rest-telemetry-v2-controller.php
> +	 * Register the route for /system_status
Looks like the comment here was carried over from the class used as an example.

2021-10-01 21:56 UTC, jonathansadowski commented on includes/rest-api/Controllers/Version3/class-wc-rest-telemetry-controller.php
> + * Handles requests to the /system_status/App/* endpoints.
This docblock doesn't seem to be accurate.

2021-10-04 14:11 UTC, joshbetz commented
Thanks @jonathansadowski. I'll double check all the comment blocks and make sure to fix the ones you mentioned.

> I do have some inarticulable pause about adding telemetry to the v3 namespace.

I don't have any strong opinions on this. Happy to put it in a new namespace or even `wc-analytics`.

2021-10-12 15:38 UTC, jonathansadowski requested changes
Looking good — I added a few minor comments, but otherwise everything tested out well. Thanks for updating the namespace used!

2021-10-12 15:38 UTC, jonathansadowski commented on tests/e2e/core-tests/specs/api/telemetry.test.js
> +				.post( `/wc/v3/telemetry`, data )
Looks like this still needs to be updated with the new route

2021-10-12 15:38 UTC, jonathansadowski commented on includes/rest-api/Controllers/Telemetry/class-wc-rest-telemetry-controller.php
> + * Handles requests to the /telemetry endpoint.
Can you update this to `/tracker`?

2021-10-12 15:38 UTC, jonathansadowski commented on includes/rest-api/Controllers/Telemetry/class-wc-rest-telemetry-controller.php
> +	 * Register the route for /telemetry
Same as above

2021-10-12 15:38 UTC, jonathansadowski commented on tests/e2e/core-tests/specs/api/telemetry.test.js
> +				.post( `/wc/v3/telemetry`, {
Same as above

2021-10-13 22:51 UTC, jonathansadowski submitted a review, later dismissed
Thanks for making the requested updates. Everything looks good. I verified that the test failures are unrelated to this change, and that the unit tests pass for me when I run locally with this branch.

2021-10-14 16:03 UTC, jonathansadowski approved these changes
Thanks for the rebase. All tests good except for the sniff re: `Server.php` and the filename, but I don't think we should fix that in the context of this PR.

Looking good, nice work.

2021-10-14 16:03 UTC, merged

2021-10-14 16:06 UTC, jonathansadowski commented
I didn't add the needs changelog or needs testing instructions labels because of the scope of this API being limited to mobile consumption.

2021-10-15 09:47 UTC, Konamiman commented
I have updated the testing instructions since the endpoint is actually `/wp-json/wc-telemetry/tracker`, not `/wp-json/wc/v3/telemetry` (and I have added `curl` and WP CLI examples too).