Update the Azerbaijani manat symbol AZN
woocommerce/woocommerce pull request #30605
Opened 2021-08-30 16:40 UTC by SamirMahmudzade

I try to fix currency symbol problem. 
⋔ &#8916;

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-04-04 19:05 UTC, barryhughes requested changes

2022-04-04 19:05 UTC, barryhughes commented on includes/wc-core-functions.php
> +			'AZN' => '&#8916',
Though it looks very similar, I'm not quite sure this is the correct symbol ... `&#8916;` seems to be the mathematical "pitchfork" operator `⋔`.

Looking at [CLDR R40](https://github.com/unicode-org/cldr/blob/release-40/common/main/az.xml#L5192) it looks like we should use [`&#8380;` ("Manat Sign" ₼)](https://unicode-table.com/en/20BC/). Also, we should add a semi-colon to the end:

```suggestion
			'AZN' => '&#8380;',
```

What do you think?

2022-08-04 22:59 UTC, barryhughes commented on includes/wc-core-functions.php
> +			'AZN' => '&#8916',
Hi @SamirMahmudzade—just checking to make sure you saw my previous question and confirm if you are interested in moving this one forward?

2022-11-12 22:45 UTC, SamirMahmudzade commented
&#x20BC; HEX CODE
&8380; HTML CODE

Azerbaijani Manat  Currency Sign "₼" - AZN

2022-11-15 13:46 UTC, barryhughes commented
Let's watch for checks passing, adjust if needed, then we can merge.

2022-11-17 07:06 UTC, barryhughes approved these changes

2022-11-17 07:07 UTC, merged