Added text to be displayed when no search results
woocommerce/woocommerce pull request #30641
Opened 2021-09-03 15:14 UTC by san-coding

Added text to be displayed when invalid data is entered into the search input field and no search results found
 in `WooCommerce-> Marketplace` , fixes issue #30588

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1. Create any test site using JN site.
2. Install and activate all the required plugins.
3. Install and activate WooCommerce 5.7.0 Beta-1.
4. Complete the setup wizard.
5. Go to WooCommerce->Marketplace.
6. Search invalid data (non-existing) in search field.
7. Screen displays `Sorry, could not find anything. Try searching again using a different term.`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Updated file [html-admin-page-addons.php](https://github.com/woocommerce/woocommerce/blob/c975dda18c78e211976d53c04376517c1618ad70/includes/admin/views/html-admin-page-addons.php#L65-L70) , added an `if` condition to check if search results are empty and display the message.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2021-09-03 15:19 UTC, san-coding commented
Hey @vedanshujain @andfinally @kloon  , I have added this PR #30641 , please review it , thank you

2021-09-05 05:09 UTC, san-coding commented
Ok , now I see that the changes I have made are wrong, but how do I know that no search results are being returned

2021-09-05 05:12 UTC, san-coding commented
> now I see that the changes I have made are wrong, but how do I know that no search results are being returned , is any variable storing the number of results returned, please help me out @vedanshujain @andfinally @kloon , thanks

2021-09-07 10:58 UTC, vedanshujain commented
@san-coding you should be able to use `$addon` to see if there are search results. Can you check if the presence of both `$search` and more than one in `$addon` gives you expected behavior?

2021-09-07 13:23 UTC, san-coding commented
> @san-coding you should be able to use `$addon` to see if there are search results. Can you check if the presence of both `$search` and more than one in `$addon` gives you expected behavior?

Ok thanks , I will check and make changes

2021-09-09 04:03 UTC, san-coding commented
Hey @vedanshujain , could you please review this

2021-09-13 09:27 UTC, san-coding commented
Have added required space and replaced `sizeof()` with `count()`

2021-09-13 10:08 UTC, san-coding commented
@vedanshujain , looks like all checks have passed, you may review and merge

2021-09-28 10:30 UTC, san-coding commented
@vedanshujain @rodelgc @andfinally someone please review this

2021-09-29 06:15 UTC, kloon requested changes

2021-09-29 06:15 UTC, kloon commented on includes/admin/views/html-admin-page-addons.php
> +					<?php // translators: search keyword. ?>
You can remove this since there is no placeholder in the string below.

2021-09-29 07:16 UTC, san-coding commented on includes/admin/views/html-admin-page-addons.php
> +					<?php // translators: search keyword. ?>
should I make the below change ?
```suggestion
					<?php // translators: search keyword. ?>
```

2021-09-29 07:17 UTC, san-coding commented on includes/admin/views/html-admin-page-addons.php
> +					<?php // translators: search keyword. ?>
What exactly should I remove

2021-10-02 13:41 UTC, eopws commented on includes/admin/views/html-admin-page-addons.php
> +					<?php // translators: search keyword. ?>
He is talking about this `<?php // translators: search keyword. ?>`

2021-10-02 18:01 UTC, san-coding commented
Thank you , I have made the changes, please review this PR

2021-10-02 18:02 UTC, san-coding commented
can you please add a label `hacktoberfest-accepted` to this PR, thank you

2021-10-02 18:02 UTC, san-coding commented on includes/admin/views/html-admin-page-addons.php
> +					<?php // translators: search keyword. ?>
have made the changes

2021-10-10 14:10 UTC, san-coding commented
@kloon @eopws @vedanshujain please review this

2021-10-11 09:51 UTC, kloon approved these changes
Changes look good to me now, thanks!

2021-10-11 09:56 UTC, san-coding commented
@kloon thanks

2021-10-12 14:36 UTC, peterfabian commented
Requesting a review from the core team before merging just to double check, should be a quick one.

2021-10-13 11:43 UTC, vedanshujain approved these changes
LGTM!

2021-10-13 11:43 UTC, merged

2021-10-13 14:27 UTC, san-coding commented
Thanks you 👍🏻

2021-10-15 10:03 UTC, peterfabian commented
> A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label.

My reading of [the rules](https://hacktoberfest.digitalocean.com/) is that the label is not necessary, but please let us know if you think we need to add it. Thx!

2021-10-15 11:15 UTC, drjamesj commented
Hi @san-coding @vedanshujain - there is a slight issue for this PR when there is no search term the error message still displays (ie. on the landing page when you first access Marketplace).

To reproduce:
- login to wp-admin
- navigate to WooCommerce -> Marketplace
- you will see the error message `Sorry, could not find anything. Try searching again using a different term.` on this page when it should not show here

![image](https://user-images.githubusercontent.com/37321814/137478697-1fb37d5b-0693-4e51-8b33-350576afbec4.png)

I am happy to open a PR to correct this if you like. Just let me know.

2021-10-15 14:09 UTC, san-coding commented
Ohh i will look into this and get back to you soon, can you revert the merge, adding a condition to check if search term exists would be enough i guess

2021-10-15 14:53 UTC, san-coding commented
@drjamesj , checkout this file in the trunk branch, maybe it has been solved
https://github.com/woocommerce/woocommerce/blob/7486c0540a111aa518dfbfdd93484b5791b2ecbd/includes/admin/views/html-admin-page-addons.php#L67