fix ensure cancelling unpaid orders is always re-scheduled
woocommerce/woocommerce pull request #30830
Opened 2021-09-28 15:29 UTC by Ekliptor

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # https://github.com/woocommerce/woocommerce/issues/30682

I have moved the `wp_schedule_single_event()`to the beginning of the `wc_cancel_unpaid_orders()`as suggested in my bug report. This ensures that cancelling order does not stop in case of a script timeout or plugin-related crash happening once. Moving it up will ensure it gets scheduled for retry.

### How to test the changes in this Pull Request:

1. add a call to `do_action('woocommerce_cancel_unpaid_orders');` inside a WP init hook to call the new code. Alternatively call `wc_cancel_unpaid_orders();` directly
2. call `exit` in `wc_cancel_unpaid_orders()`to simulate a crash.
3. On next script run: print `$timestamp = wp_next_scheduled ( 'woocommerce_cancel_unpaid_orders' );` to ensure `$timestamp > 0`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

fix ensure cancelling unpaid orders is always re-scheduled

2021-10-13 15:13 UTC, claudiosanches requested changes

2021-10-13 15:13 UTC, claudiosanches commented on includes/wc-order-functions.php
> +	// re-schedule the event before cancelling orders
```suggestion
	// Re-schedule the event before cancelling orders
```

2021-10-13 15:13 UTC, claudiosanches commented on includes/wc-order-functions.php
> +	// this way in case of a DB timeout or (plugin) crash the event is always scheduled for retry
```suggestion
	// this way in case of a DB timeout or (plugin) crash the event is always scheduled for retry.
```

2021-10-13 15:24 UTC, claudiosanches approved these changes
Works great.

Just a note: during update WooCommerce re-schedule all events, so no migration or any action is required to fix existing stores.

2021-10-13 15:25 UTC, merged

2021-11-11 22:10 UTC, azanoni commented
Sadly this doesnt fix the issue, I tried with my client this version (5.9.0) and we are still experience the same issue, random (maybe because other plugin cause this) the cron job is "deleted", the only way to restoring this again is change the HOLD STOCK MINUTES with another number...save it, and after that the CRON appear again.

2021-11-13 13:14 UTC, Ekliptor commented
Can you paste a System Report under WooCommerce -> Status?
I'm also assuming another plugin is modifying the `woocommerce_cancel_unpaid_orders` single event.

The current fix keeps using `wp_schedule_single_event()`.
A more "brutal" fix would be to add an additional `wp_schedule_event()` that checks hourly if the event is still scheduled. If not, re-schedule it using `wp_schedule_single_event()` according to your "hold stock minutes" setting.

2021-11-13 13:57 UTC, azanoni commented
`
### WordPress Environment ###

WordPress address (URL): https://clientdomain.com
Site address (URL): https://clientdomain.com
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: ❌ 5.7.4 - There is a newer version of WordPress available (5.8.2)
WP Multisite: –
WP Memory Limit: 98 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.29
PHP Post Max Size: 100 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.22-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: custompref_
Total Database Size: 13816.08MB
Database Data Size: 12213.97MB
Database Index Size: 1602.11MB
custompref_woocommerce_sessions: Data: 23.05MB + Index: 1.02MB + Engine InnoDB
custompref_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_woocommerce_downloadable_product_permissions: Data: 11.52MB + Index: 27.92MB + Engine InnoDB
custompref_woocommerce_order_items: Data: 8.52MB + Index: 3.52MB + Engine InnoDB
custompref_woocommerce_order_itemmeta: Data: 104.64MB + Index: 58.14MB + Engine InnoDB
custompref_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
migrate_memberships: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
translator_categories: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
translator_dictionary: Data: 0.42MB + Index: 0.06MB + Engine InnoDB
translator_dictionary_theme: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_languages: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
translator_languages_list: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
translator_languages_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
translator_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
translator_position_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_products_downloads: Data: 30.56MB + Index: 54.13MB + Engine InnoDB
translator_profile_digit_styles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_profile_list_styles: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
translator_profile_theme: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_sort_type: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
translator_texts_styles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_translations: Data: 4.52MB + Index: 0.89MB + Engine InnoDB
translator_translations_import_log: Data: 6.52MB + Index: 0.02MB + Engine InnoDB
translator_translation_styles: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
translator_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
translator_users_ip: Data: 24.55MB + Index: 0.00MB + Engine InnoDB
translator_user_languages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
translator_user_roles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_actionscheduler_actions: Data: 22.05MB + Index: 22.11MB + Engine InnoDB
custompref_actionscheduler_claims: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
custompref_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_actionscheduler_logs: Data: 17.05MB + Index: 13.03MB + Engine InnoDB
custompref_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_affiliate_custompref_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_affiliate_custompref_affiliates: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
custompref_affiliate_custompref_campaigns: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
custompref_affiliate_custompref_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_affiliate_custompref_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_affiliate_custompref_customermeta: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
custompref_affiliate_custompref_customers: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
custompref_affiliate_custompref_payouts: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
custompref_affiliate_custompref_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_affiliate_custompref_referrals: Data: 3.52MB + Index: 0.23MB + Engine InnoDB
custompref_affiliate_custompref_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_affiliate_custompref_sales: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
custompref_affiliate_custompref_visits: Data: 8784.00MB + Index: 398.00MB + Engine InnoDB
custompref_bbapp_iap_ordermeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_bbapp_iap_orders: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
custompref_bbapp_iap_products: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_bbapp_itemmeta: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
custompref_bbapp_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
custompref_bbapp_notifications: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
custompref_bbapp_notifications_devices: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
custompref_bbapp_push_notifications: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
custompref_bbapp_push_notifications_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bbapp_push_queue: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
custompref_bbapp_queue: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
custompref_bbapp_user_segment: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
custompref_bb_performance_cache: Data: 3.52MB + Index: 0.08MB + Engine InnoDB
custompref_bp_activity: Data: 8.52MB + Index: 6.03MB + Engine InnoDB
custompref_bp_activity_meta: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
custompref_bp_document: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
custompref_bp_document_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_bp_document_folder_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_document_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_follow: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
custompref_bp_friends: Data: 0.38MB + Index: 0.42MB + Engine InnoDB
custompref_bp_groups: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
custompref_bp_groups_groupmeta: Data: 0.28MB + Index: 0.17MB + Engine InnoDB
custompref_bp_groups_members: Data: 1.52MB + Index: 1.88MB + Engine InnoDB
custompref_bp_invitations: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
custompref_bp_media: Data: 0.19MB + Index: 0.25MB + Engine InnoDB
custompref_bp_media_albums: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
custompref_bp_messages_messages: Data: 8.52MB + Index: 0.80MB + Engine InnoDB
custompref_bp_messages_meta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
custompref_bp_messages_notices: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
custompref_bp_messages_recipients: Data: 0.28MB + Index: 0.80MB + Engine InnoDB
custompref_bp_moderation: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_moderation_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
custompref_bp_notifications: Data: 6.52MB + I [...]

2021-11-14 17:55 UTC, Ekliptor commented
OK most likely not plugin-related.
Before we go for the "brutal" fix adding a 2nd cron to watch if the 1st cron is running, I would like to understand **how** the cron still can get lost?

By digging through the code, I see the cron definitely gets stored in DB immediately, so a crash/timeout/abort could not stop it from being re-scheduled. To call stack to store is a new cron in DB is *roughly* as follows:
`wp_schedule_single_event()` -> `_set_cron_array()` -> `update_option()` -> `$wpdb->update()`

Any idea from WP team?