Add new performance test Shopper / Browse products by category
woocommerce/woocommerce pull request #30848
Opened 2021-09-30 07:18 UTC by veljkho

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #30634

### How to test the changes in this Pull Request:

- docker run --network="host" -v [WC ROOT PATH]/tests:/tests -it loadimpact/k6 run /tests/performance/tests/simple-all-shopper-requests.js

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-10-07 10:36 UTC, tammullen requested changes
Thanks for this! Just some changes needed to make it easier to run on any type of site.

2021-10-07 10:36 UTC, tammullen commented on tests/performance/requests/shopper/category-page.js
> +		response = http.get(`${base_url}/product-category/accessories/`, {
Can we make the category name a parameter so it will be easier to run against any site

2021-10-07 10:36 UTC, tammullen commented on tests/performance/requests/shopper/category-page.js
> +					'<h1 class="woocommerce-products-header__title page-title">Accessories</h1>'
Would be better for running against multiple sites if not looking for Accessories

2021-10-07 10:36 UTC, tammullen commented on tests/performance/requests/shopper/category-page.js
> +let categoryPageTrend = new Trend("wc_get_site_root");
`wc_get_site_root` is for the `${base_url}/` request. This one should be named something like `wc_get_product_category_name`

2021-10-07 10:36 UTC, tammullen commented on package-lock.json
> -              "version": "npm:wp-prettier@1.19.1",
I think `package-lock.json` has been included by mistake?

2021-10-21 12:52 UTC, veljkho commented on tests/performance/requests/shopper/category-page.js
> +		response = http.get(`${base_url}/product-category/accessories/`, {
Sure, that's good point!

2021-10-21 12:53 UTC, veljkho commented on tests/performance/requests/shopper/category-page.js
> +					'<h1 class="woocommerce-products-header__title page-title">Accessories</h1>'
Yes, I added the same parameter.

2021-10-21 12:53 UTC, veljkho commented on tests/performance/requests/shopper/category-page.js
> +let categoryPageTrend = new Trend("wc_get_site_root");
Good point!

2021-10-21 12:53 UTC, veljkho commented on package-lock.json
> -              "version": "npm:wp-prettier@1.19.1",
Ouch, this was unintentional.

2021-10-21 12:55 UTC, veljkho commented
I'm going to close this PR and instead open a new one with all the fixes @tammullen . It was too complex with today's problems with the local environment to merge with the trunk and fix issues, especially having issues with local env.

2021-10-21 12:55 UTC, closed without merging