Proof of concept: use WP CLI tool to generate order data for REST API E2E tests.
woocommerce/woocommerce pull request #30851
Opened 2021-09-30 14:04 UTC by Konamiman

This pull request is a proof of concept that shows how the WP CLI tool can be used to generate product and order data directly in the database in order to be used by E2E REST API tests. Here an order is generated via WP CLI and then retrieved via REST API, but the opposite would also be possible.

2021-10-01 16:59 UTC, rrennick commented
@Konamiman In our E2E/API testing infrastructure the test environment is either a docker container or an external site. The E2E test scripts don't use WP CLI because they do not have access to WP CLI on the external site. We can and do use WP CLI to initialize the docker E2E container. Those commands are run local to the container vs local to the test script.

2021-10-05 13:19 UTC, Konamiman commented
@rrennick Would it be possible to add WP CLI to the docker container and use it only for REST API tests when those are run in such container? Not ideal but that would be the only way to properly test the REST API (if we use the API for both creating and retrieving data we aren't really testing atomic operations).

2021-10-05 14:00 UTC, rrennick commented
> Would it be possible to add WP CLI to the docker container and use it only for REST API tests when those are run in such container?

We can create as many [container initialization scripts](https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e/docker) as needed. Alternatively, if it's not practical to create all the data during initialization, there should be a way to keep the WP CLI process active.

2021-10-07 16:27 UTC, rrennick commented on tests/e2e/api-core-tests/tests/orders/orders.test.js
> +const { itIf } = require( '../../utils/exec' );
You need to require these from the `@woocommerce/e2e-utils` package vs the relative path because that path is outside the npm package. When this package is built and installed in another project the relative path doesn't exist.

2021-10-07 16:28 UTC, rrennick commented on tests/e2e/api-core-tests/utils/exec.js
> +const itIf = ( condition ) =>
You don't need this if you are using the one from the utils package.

2021-10-07 16:29 UTC, rrennick requested changes
@Konamiman This is shaping up nicely. I didn't review the whole PR but wanted to add these suggestions.

2021-10-08 07:41 UTC, Konamiman commented on tests/e2e/api-core-tests/utils/exec.js
> +const itIf = ( condition ) =>
I tried, but if I require `@woocommerce/e2e-utils` instead of that one I get errors:

![image](https://user-images.githubusercontent.com/937723/136517518-eb5e14a1-43df-49c8-9192-2b035a744b15.png)

2021-10-08 07:44 UTC, Konamiman commented on tests/e2e/api-core-tests/tests/orders/orders.test.js
> +const { itIf } = require( '../../utils/exec' );
But the previous lines (the declarations for `order` and `ordersApi`) are also relative paths and I didn't introduce these, they are in `trunk` already 🤔

2021-10-12 14:32 UTC, rrennick commented on tests/e2e/api-core-tests/utils/exec.js
> +const itIf = ( condition ) =>
@Konamiman Thanks for the clarification. That's something we should fix but not within the scope of this PR.

2021-11-02 08:11 UTC, Konamiman commented
Incorporated the changes from https://github.com/woocommerce/woocommerce/pull/31010, there are now merge conflicts.

2023-05-02 04:01 UTC, samueljseay commented
We are closing this pull request, as the last activity has been quite some time ago. If you are still interested or you feel like this is a mistake, please open another PR based on a recent version of the trunk branch. Thanks!

@Konamiman it looks like this would take significant rework to update to trunk, so I'm closing but feel free to reopen a rebased version if it suits you 😃

2023-05-02 04:01 UTC, closed without merging

2023-05-03 07:43 UTC, Konamiman commented
@samueljseay No problem, it was a proof of concept after all (and at this point I don't remember the context). If @woocommerce/solaris is interested we can resurrect this.