Bump WooCommerce Admin version to 2.7.1 final
woocommerce/woocommerce pull request #30877
Opened 2021-10-04 17:55 UTC by joshuatf

No changes have been made since `2.7.1-rc.1`.  This PR just bumps to the final release for `2.7.1` for inclusion in WC 5.8.

Changelog from beta to RC1 and testing instructions can be found in https://github.com/woocommerce/woocommerce/pull/30800.

2021-10-04 18:07 UTC, claudiosanches requested changes
I noticed a change in the `plugin-api-version`, is that intentional?

2021-10-04 18:15 UTC, joshuatf commented
@claudiosanches I'm not sure what's causing that.  I based this on `5.8.0-rc.1` and just ran a `composer update` after bumping the version.  Maybe the lock files are out of sync?  Or did I do something wrong?

2021-10-04 19:36 UTC, claudiosanches approved these changes
Looks great!

2021-10-05 14:58 UTC, barryhughes approved these changes

2021-10-05 14:58 UTC, merged