Revamp Featured page in WooCommerce Marketplace
woocommerce/woocommerce pull request #30900
Opened 2021-10-07 20:08 UTC by tgglv

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Related to 11239-gh-Automattic/woocommerce.com.

We want to revamp the Marketplace page according to [Figma designs](seb2o1DExPxoh5d53ftJif-fi-812%3A13394). Together with the new design, the approach of treating data from WooCommerce.com API was changed as well. Instead of the current approach of sections/containers for products and banners, the new approach uses groups of products displayed one after another. 

Changes:
- Refactor current implementation of featured page blocks (the current version works on custom markup functions like "open container", put some product cards, "close container"; the update uses a simplified approach of showing groups of product cards instead)
- Add markup for showing ratings and review count for products
- Reuses current addon's product card for both search results, products by categories, and featured products
- CSS tweaks to make marketplace product card looks like on the design

### How to test the changes in this Pull Request:

#### Preparation
1. To test these changes properly you need an API for testing.
There're 2 options: 
- Local WCCOM (use 11456-gh-Automattic/woocommerce.com for this option) or
- Hardcoded JSON response from [this script](2a667-pb/)

For the 2nd option save the script in `index.php` file and launch PHP-Builtin server with the command like:
```sh
php -S host.docker.internal:9000
```

2. Disable using transient by changing the first line of the `render_featured` method in `includes/admin/class-wc-admin-addons.php` to: `$featured = false;`

3. Change the API URL used in `$raw_featured = wp_safe_remote_get(...` in the same method from `https://woocommerce.test/wp-json/wccom-extensions/2.0/featured` to `http://host.docker.internal:9000` (you may need to change the function used to `wp_remote_get` as well)

#### Testing
1. Open your testing WP site with WooCommerce on this branch
2. Open WP Admin > WooCommerce > Marketplace page, make sure that you are viewing the "Featured" section 
3. You should see something similar to the image below:
![image](https://user-images.githubusercontent.com/15897544/136460277-195c6afc-c655-4973-9adb-d8954264021b.png)

4. Try extensions search (e.g. via typing "memberships"), the page should look as expected

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enhancement - Revamp the WooCommerce Marketplace page.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2021-10-13 10:42 UTC, andfinally commented on includes/admin/class-wc-admin-addons.php
> +			// Important: WCCOM Extensions API v2.0 is used.
As mentioned in 11257-gh-Automattic/woocommerce.com#issuecomment-942166271, we want to return the country to the endpoint, like we do on other pages.

```suggestion
			$parameter_string = '';
			$country  = WC()->countries->get_base_country();
			if ( ! empty( $country ) ) {
				$parameter_string = '?' . http_build_query( array( 'country' => $country ) );
			}

			// Important: WCCOM Extensions API v2.0 is used.
```

2021-10-13 10:42 UTC, andfinally commented on includes/admin/class-wc-admin-addons.php
> +				'https://woocommerce.com/wp-json/wccom-extensions/2.0/featured',
```suggestion
				'https://woocommerce.com/wp-json/wccom-extensions/2.0/featured' . $parameter_string,
```

2021-10-13 18:40 UTC, andfinally commented
The `wccom_get_star_class` method will be moved to a more generic location in another PR, please see https://github.com/woocommerce/woocommerce/pull/30840#discussion_r727983661.

2021-10-13 21:10 UTC, barryhughes commented
> Hardcoded JSON response from [this script](https://github.com/woocommerce/woocommerce/pull/2a667-pb/)

Hi @tgglv—can you confirm the URL here is correct? It leads me to a 404.

2021-10-13 22:09 UTC, barryhughes requested changes
Looks good! Left a few notes—main concern would be the removal of public methods without a deprecation stage (but, perhaps that is ok for `WC_Admin_Addons`).

2021-10-13 22:09 UTC, barryhughes commented on includes/admin/class-wc-admin-addons.php
> +	public static function render_featured() {
Here and a few other places we're removing a public method.

I realize this is a pretty specialized class and so it _probably_ is not used by 3PDs/our own extensions, but generally speaking we're pretty careful not to remove public methods without at least deprecating them first.

2021-10-13 22:09 UTC, barryhughes commented on includes/admin/class-wc-admin-addons.php
> +			$country  = WC()->countries->get_base_country();
Minor PHPCS issue:

```suggestion
			$country          = WC()->countries->get_base_country();
```

2021-10-13 22:09 UTC, barryhughes commented on includes/admin/class-wc-admin-addons.php
> +		$capacity           = $block->capacity ?? 3;
Minor thing (PHPCS):

```suggestion
		$capacity             = $block->capacity ?? 3;
```

2021-10-13 22:09 UTC, barryhughes commented on includes/admin/views/html-admin-page-addons.php
> +	} else if (
I think this function is being relocated via another PR, but worth flagging this should be `elseif` (no space), because current PHPCS rules.

2021-10-13 22:09 UTC, barryhughes commented on includes/admin/class-wc-admin-addons.php
> +								<span class="product-reviews-count">(<?php echo wp_kses_post( $mapped->reviews_count ); ?>)</span>
I don't have a local WPCOM setup to test this against, but I wondered: is `$mapped->reviews_count` an integer?

If it is, could we use a less expensive cast like `(int)` or else the `absint()` function, and/or if it is more complex than that but still does not contain HTML, can we use `esc_html()` (also less expensive)?

2021-10-13 22:09 UTC, barryhughes commented on includes/admin/class-wc-admin-addons.php
> +								<span class="price"><?php echo wp_kses_post( $mapped->price ); ?></span>
Do we need `wp_kses_post()` here or would `esc_html()` suffice?

2021-10-13 22:09 UTC, barryhughes commented on includes/admin/class-wc-admin-addons.php
> +											wp_kses_post( $mapped->vendor_name )
Is `esc_html()` sufficient here?

2021-10-14 05:23 UTC, tgglv commented
> > Hardcoded JSON response from [this script](https://github.com/woocommerce/woocommerce/pull/2a667-pb/)
> 
> Hi @tgglv—can you confirm the URL here is correct? It leads me to a 404.

Thanks for the review @barryhughes. 
Don't know why the link was changed. Actually, it's PasteBin: https://mc.a8c.com/pb/2a667/

2021-10-14 06:25 UTC, tgglv commented on includes/admin/class-wc-admin-addons.php
> +	public static function render_featured() {
Totally agree with the approach of deprecating public functions, @barryhughes.

The only thing the removed functions were used is to show Add-ons on the Marketplace page. The most of these were added in these PRs: 
- https://github.com/woocommerce/woocommerce/pull/11951
- https://github.com/woocommerce/woocommerce/pull/9750
- https://github.com/woocommerce/woocommerce/pull/15598

These PRs are 4-6 years old. Methods are public to be used in HTML template.
It might be weird to show our promoted products from our Marketplace in other 3PD extensions.

2021-10-14 08:45 UTC, tgglv commented on includes/admin/class-wc-admin-addons.php
> +			$country  = WC()->countries->get_base_country();
Thanks, applied in https://github.com/woocommerce/woocommerce/pull/30900/commits/f54d7b0991520208fa826f1147e29d6fa04e27f5.

2021-10-14 08:46 UTC, tgglv commented on includes/admin/class-wc-admin-addons.php
> +		$capacity           = $block->capacity ?? 3;
Applied in https://github.com/woocommerce/woocommerce/pull/30900/commits/f54d7b0991520208fa826f1147e29d6fa04e27f5, thanks!

2021-10-14 08:46 UTC, tgglv commented on includes/admin/views/html-admin-page-addons.php
> +	} else if (
Indeed. Fixed in https://github.com/woocommerce/woocommerce/pull/30900/commits/f54d7b0991520208fa826f1147e29d6fa04e27f5.

2021-10-14 09:29 UTC, andfinally commented on includes/admin/class-wc-admin-addons.php
> +	public static function render_featured() {
Hi @barryhughes, thanks, we've now restored and commented the deprecated methods in https://github.com/woocommerce/woocommerce/pull/30900/commits/85fa25ad929ae9c85598c907c263856637cced7d. 

(We haven't restored any of the CSS classes we're deleting – we think CSS is too fragile for 3PDs to have used.)

2021-10-14 11:13 UTC, andfinally commented on includes/admin/class-wc-admin-addons.php
> +								<span class="product-reviews-count">(<?php echo wp_kses_post( $mapped->reviews_count ); ?>)</span>
Thanks, it is an integer – fixed in https://github.com/woocommerce/woocommerce/pull/30900/commits/22b67783d0cecbefb601b7dbf5f0c41cc64c772f.

2021-10-14 11:13 UTC, andfinally commented on includes/admin/class-wc-admin-addons.php
> +								<span class="price"><?php echo wp_kses_post( $mapped->price ); ?></span>
We've addressed this in https://github.com/woocommerce/woocommerce/pull/30900/commits/124dc35e42b93020496f86f7e6dcf679860637c0 – we had to use `wp_kses` instead of `esc_html`, as this value contains `span` and `bdi` tags.

2021-10-14 11:17 UTC, andfinally commented on includes/admin/class-wc-admin-addons.php
> +											wp_kses_post( $mapped->vendor_name )
Yes thanks, changed in https://github.com/woocommerce/woocommerce/pull/30900/commits/22b67783d0cecbefb601b7dbf5f0c41cc64c772f.

2021-10-14 11:20 UTC, andfinally commented
(The 404 on the script was because GitHub changed the PasteBin link.)

2021-10-14 14:19 UTC, Konamiman commented
Hi @tgglv, there are merge conflicts, can you please address them?

2021-10-14 15:41 UTC, barryhughes commented on includes/admin/class-wc-admin-addons.php
> +	public static function render_featured() {
Thanks! The only one I think we're missing is `get_featured()`.

(It has been renamed to `render_featured()`, but in principle we should keep a stub or alias with the old name, and mark it deprecated.)

> It might be weird to show our promoted products from our Marketplace in other 3PD extensions.

Yep, I figured it was rather unlikely—but sometimes it's hard to predict what is happening out there (that to say, taking a better safe than sorry approach here 🙃).

2021-10-14 15:42 UTC, barryhughes requested changes
One last note from me (re `::get_featured()`), plus we need to resolve conflicts per note from @Konamiman.

Those things done, it should be good to merge :+1:

2021-10-14 20:16 UTC, tgglv commented on includes/admin/class-wc-admin-addons.php
> +	public static function render_featured() {
> Thanks! The only one I think we're missing is get_featured().

Thanks for noticing that, @barryhughes! It was returned back in https://github.com/woocommerce/woocommerce/pull/30900/commits/7cbdd71af636cba5e43e75e4e69dea5038e89844.

> Yep, I figured it was rather unlikely—but sometimes it's hard to predict what is happening out there (that to say, taking a better safe than sorry approach here 🙃).

Indeed. I guess we will ask about these methods across Woo to know more about the possible usage of those methods.

2021-10-14 20:17 UTC, tgglv commented
> Hi @tgglv, there are merge conflicts, can you please address them?

Hey @Konamiman, fortunately, conflicts are gone.

2021-10-15 03:49 UTC, barryhughes approved these changes
LGTM!

2021-10-15 03:50 UTC, barryhughes commented
@andfinally I didn't want to merge without your approval on the PR, but we're all set from my perspective.

2021-10-15 07:22 UTC, merged

2021-10-15 10:31 UTC, Konamiman commented
I have updated the testing instructions since they were pointing to the deprecated `get_featured` method for the code changes, instead of the `render_featured` method. Also added a mention to replace `wp_safe_remote_get` with `wp_remote_get`, otherwise WP will throw an "Invalid URL" error when serving the script from localhost.