Add troubleshooting section to running unit test section
woocommerce/woocommerce pull request #30950
Opened 2021-10-14 14:06 UTC by nielslange

### Changes proposed in this Pull Request:

Following the steps to run unit test, might lead to a problem that was firstly mentioned by Daniel Bachhuber in 2015 in https://github.com/wp-cli/wp-cli/issues/1938#issuecomment-124237542. This PR adds troubleshooting instructions in case a unit test cannot be executed and an error message appears instead.

### How to test the changes in this Pull Request:

1. Check out this PR.
2. Look up the file `tests/README.md`.
3. Check the section `### Troubleshooting`.

---

@Konamiman I added you as a reviewer and noticed that my linting settings changed a few additional parts in the file. Please let me know if I shall update my PR and remove the additional markdown lintings.

2021-10-19 09:33 UTC, Konamiman commented on tests/README.md
> +If you run into this problem, simply delete the WordPress test directory and run teh installer again. In this particular case, you'd run the following command:
Typo: `teh`

2021-10-19 09:34 UTC, Konamiman requested changes
Hi @nielslange, yes, I think it's better to undo the changes done by the linter, they aren't really needed and they are also breaking the doc structure (e.g. the second list in "Writing tests"). Also there are merge conflicts for the file, could you please address these too?

2021-10-19 10:46 UTC, nielslange commented on tests/README.md
> +If you run into this problem, simply delete the WordPress test directory and run teh installer again. In this particular case, you'd run the following command:
Oh, my no. 1 typo. 🙈 Just fixed it.

2021-10-19 10:47 UTC, nielslange commented
> Hi @nielslange, yes, I think it's better to undo the changes done by the linter, they aren't really needed and they are also breaking the doc structure (e.g. the second list in "Writing tests"). Also there are merge conflicts for the file, could you please address these too?

Thanks for your review, @Konamiman. I created a fresh PR that only contains the newly added section and does not apply any linting changes.

2021-10-20 06:57 UTC, Konamiman commented on plugins/woocommerce/tests/README.md
> +```
Just a small thing: the note about the database name could go outside the code block for better visibility:

```
$ rm -rf /var/folders/qr/3cnz_5_j3j1cljph_246ty1h0000gn/T/wordpress-tests-lib
$ tests/bin/install.sh woocommerce_tests_1 root root
```
(Note that `woocommerce_tests` changed to `woocommerce_tests_1` as the database `woocommerce_tests` already exists due to the prior command)

2021-10-20 11:30 UTC, nielslange commented on plugins/woocommerce/tests/README.md
> +```
As suggested, I placed the note outside the code block. I haven't placed it in brackets, though. Please let me know if you prefer to place it in brackets, as you suggested initially. I opted against brackets, as personally don't see the added value in having them. That said, if you prefer having them, just let me know. 😉

2021-10-27 07:22 UTC, Konamiman commented
Looks good. "Troubleshooting" was missing from the table of contents but I have added it myself.

2021-10-27 07:22 UTC, Konamiman approved these changes

2021-10-27 07:22 UTC, merged