Update has_block_template function to use apply_filters
woocommerce/woocommerce pull request #30997
Opened 2021-10-20 14:54 UTC by tjcafferkey

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adding an `apply_filters( 'woocommerce_has_block_template ')` will allow us to a step forward to rendering block templates from Woo Blocks in an effort to replace core PHP Templates.

Context found [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4926)

Closes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4970

### How to test the changes in this Pull Request:

This will need some regression testing to confirm we haven't introduced any adverse side effects.

1. Activate a block template enabled theme.
2. Add `single-product.html` in `theme-dir/block-templates` with the following content.

```html

 <p>You are using the block template now</p> 

```

3. Check on the frontend product page that this template is getting served to the user instead of the core PHP template.
4. Delete the `single-product.html` template file and confirm that the core PHP template is getting rendered
5. Activate a classic theme and confirm core PHP template is getting rendered there.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Changelog entry

> Update has_block_template method: Add apply_filters to the function which will enable third-party plugins to override the return value.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2021-10-25 09:15 UTC, Aljullu submitted a review, later dismissed
Approving from the WC Blocks side.

This will still need a review from a maintainer of WC core, though.

2021-10-25 09:15 UTC, Aljullu commented on plugins/woocommerce/includes/class-wc-template-loader.php
> +		return apply_filters( 'wc_has_block_template', is_readable( get_stylesheet_directory() . '/block-templates/' . $template_name . '.html' ) );
Question for the WC core reviewer: is there any preference on using `wc_` or `woocommerce_` as the filter prefix? I noticed there are filters with both prefixes, but `woocommerce_` seems to be more popular?

2021-10-28 16:46 UTC, barryhughes requested changes
Nice, works well. Left a few notes/requests re the new hook.

2021-10-28 16:46 UTC, barryhughes commented on plugins/woocommerce/includes/class-wc-template-loader.php
> +		return apply_filters( 'wc_has_block_template', is_readable( get_stylesheet_directory() . '/block-templates/' . $template_name . '.html' ) );
That's right! `woocommerce_` as prefix [is preferred](https://github.com/woocommerce/woocommerce/wiki/Naming-conventions#php) and is what new code should use. Some other thoughts on this hook:

- An additional param containing the `$template_name` may be useful (otherwise callbacks will not necessarily know which template is being assessed).
- Casting the result `(bool)` could add an extra layer of safety (to ensure rogue callbacks don't change type on us).
- A docblock may be useful.

2021-10-29 15:14 UTC, barryhughes commented on plugins/woocommerce/includes/class-wc-template-loader.php
> +		return apply_filters( 'woocommerce_has_block_template', $has_template, $template_name );
Hi! My earlier comment probably wasn't clear enough, but this is what I meant re applying a cast (basically, apply it to the `apply_filters()` call before we return):

```suggestion
		$has_template = is_readable( get_stylesheet_directory() . '/block-templates/' . $template_name . '.html' );

		/**
		 * Filters the value of the result of the block template check.
		 *
		 * @since x.x.x
		 *
		 * @param boolean $has_template value to be filtered.
		 * @param string $template_name The name of the template.
		 */
		return (bool) apply_filters( 'woocommerce_has_block_template', $has_template, $template_name );
```

To explain: the [`is_readable()`](https://www.php.net/manual/en/function.is-readable.php) function always returns a boolean, so no cast needed there. However, this filter can be used by anyone, including 3PDs, and they may unintentionally change the type during filtering. So, the cast is here to guarantee the declared return type per the method's docblock.

2021-10-29 15:14 UTC, barryhughes requested changes
Should relocate the cast to boolean.

2021-10-29 15:16 UTC, tjcafferkey commented on plugins/woocommerce/includes/class-wc-template-loader.php
> +		return apply_filters( 'woocommerce_has_block_template', $has_template, $template_name );
Ah apologies @barryhughes . Makes total sense, not sure how I misinterpreted that looking back. I've committed you suggestion. Thank you.

2021-10-29 15:28 UTC, barryhughes approved these changes
LGTM!

2021-10-29 15:36 UTC, barryhughes commented
One of the tests failed, probably a temp issue/unrelated glitch—but going to re-run before merging just to be safe.

2021-10-29 15:47 UTC, merged