Fix/unsupported operand types
woocommerce/woocommerce pull request #31012
Opened 2021-10-22 04:59 UTC by RatulHasan

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #31008

### How to test the changes in this Pull Request:

1. Save bulk edit without any error.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Fix Uncaught TypeError: Unsupported operand types: string * float on set new price 

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2021-12-06 17:24 UTC, jeffstieler requested changes
Thanks for your contribution!

This indeed fixes the issue, but we'd like the logic changed to be a float type casting for consistency with similar operations in WooCommerce.

2021-12-06 17:24 UTC, jeffstieler commented on plugins/woocommerce/includes/admin/class-wc-admin-post-types.php
> +		$old_price     = empty( $product->{"get_{$price_type}_price"}() ) ? 0 : $product->{"get_{$price_type}_price"}();
Let's change this to a `(float)` value cast instead of using `empty()` and a ternary.

2022-04-13 20:51 UTC, RatulHasan commented
@jeffstieler, Fixed the logic of those codes.

2022-04-13 23:38 UTC, barryhughes approved these changes

2022-04-13 23:38 UTC, merged