Release preparation: 5.9.0-rc.1
woocommerce/woocommerce pull request #31023
Opened 2021-10-25 07:22 UTC by Konamiman

### Changes proposed in this Pull Request:

* Add new entries for WooCommerce, Admin and Blocks to `changelog.txt`; and copy them to `readme.txt`

### Important!

After this is merged and cherrypicked into `release/5.9`, that branch needs to get an extra commit that:

* Changes `Version` in `woocommerce.php` to `5.9.0-RC.1`

Extra commit: https://github.com/woocommerce/woocommerce/commit/315d9c4c9ed996c6b115109fdd0086e6e5ffa6c4

2021-10-25 07:36 UTC, peterfabian requested changes
Please check WC Admin chages. Thx!

2021-10-25 07:36 UTC, peterfabian commented on changelog.txt
> +* Fix - Updated link to WooCommerce Developers Blog in readme.txt. #7824
Aren't there more PRs merged to rc 3?

https://github.com/woocommerce/woocommerce-admin/compare/release/2.8.0-rc.2...release/2.8.0-rc.3

2021-10-25 07:47 UTC, peterfabian approved these changes
I can see now it's based on https://github.com/woocommerce/woocommerce/pull/31018 so should he fine 👍

2021-10-25 07:48 UTC, merged

2021-11-05 12:57 UTC, Konamiman commented
PR to add the changelog for 5.9 into `trunk` for 6.0: https://github.com/woocommerce/woocommerce/pull/31092