Remove path from "include currency-info.php" in locale-info.php
woocommerce/woocommerce pull request #31036
Opened 2021-10-27 09:23 UTC by Konamiman

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This pull request is the same as https://github.com/woocommerce/woocommerce/pull/30935, but targeting the `release/5.9` branch for inclusion in WooCommerce 5.9. Same testing instructions and changelog entry.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2021-10-28 09:23 UTC, peterfabian requested changes
Please update. Thanks!

2021-10-28 09:23 UTC, peterfabian commented on i18n/locale-info.php
> +$locales = 'currency-info.php';
it's missing the `include` portion :)

2021-10-28 09:25 UTC, Konamiman commented on i18n/locale-info.php
> +$locales = 'currency-info.php';
🤦‍♂️

2021-10-28 09:30 UTC, peterfabian approved these changes
Looks good now, thanks!

2021-10-28 09:58 UTC, merged

2021-10-28 09:59 UTC, Konamiman commented
Merged into `release/5.9` for inclusion in WooCommerce 5.9 RC 2. Needs to be cherry-picked into `trunk`.

2021-11-05 12:53 UTC, Konamiman commented
No need to cherrypick to `trunk` as the change has been already applied there.