add cookie consent filter
woocommerce/woocommerce pull request #31317
Opened 2021-11-27 15:32 UTC by kkmuffme

for https://github.com/woocommerce/woocommerce/issues/31118

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

add a filter for cookie consent

Closes #31118

### How to test the changes in this Pull Request:

1. add products to cart
2. check if cookies are set/products in cart

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

>Add cookie consent filter

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-01-14 11:59 UTC, vedanshujain requested changes
Thanks, for your contribution, I have added some suggestions that should be applied before we can merge.

2022-01-14 11:59 UTC, vedanshujain commented on plugins/woocommerce/includes/wc-core-functions.php
> +	if ( apply_filters( 'woocommerce_cookie_consent', true, $name ) === false && !Constants::is_true( 'WP_DEBUG' ) ) {
```suggestion
	if ( ! apply_filters( 'woocommerce_set_cookie_enabled', true, $name ,$value, $expire, $secure ) ) {
```

I think we should rename this filter since it's a pretty generic cookie escape condition, cookie consent notification is just one of the use case. Also suggestion to add all the params instead of just `$name`.

2022-01-15 07:59 UTC, kkmuffme commented on plugins/woocommerce/includes/wc-core-functions.php
> +	if ( apply_filters( 'woocommerce_cookie_consent', true, $name ) === false && !Constants::is_true( 'WP_DEBUG' ) ) {
Looks good to me. Do you put the changes or should I submit them for the PR?

2022-01-17 10:35 UTC, vedanshujain commented on plugins/woocommerce/includes/wc-core-functions.php
> +	if ( apply_filters( 'woocommerce_cookie_consent', true, $name ) === false && !Constants::is_true( 'WP_DEBUG' ) ) {
I can commit them from the GH interface, no worries.

2022-01-17 10:57 UTC, vedanshujain approved these changes

2022-01-17 10:58 UTC, merged