Support gift cards in admin order refunds template
woocommerce/woocommerce pull request #31414
Opened 2021-12-10 15:50 UTC by xristos3490

Closes #31413 

### Specification
Please check the issue description for additional details.

2021-12-16 08:45 UTC, manospsyx commented
@woocommerce/proton see https://somewherewarmattic.wordpress.com/2021/11/17/gift-cards-refunds-support/#comment-173

2022-01-31 16:06 UTC, barryhughes commented on plugins/woocommerce/includes/admin/meta-boxes/views/html-order-items.php
> +		<?php if ( (bool) apply_filters( 'woocommerce_admin_order_should_render_refunds', 0 < $order->get_total() - $order->get_total_refunded() || 0 < absint( $order->get_item_count() - $order->get_item_c
Where possible we should [avoid placing filter hooks inside templates](https://github.com/woocommerce/woocommerce/wiki/Adding-Actions-and-Filters#placement-of-filter-hooks) and we should also [document any new hooks](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters) we add.

I realize the duplication of the logic predates your change, and you were just wrapping it in a filter, but this is actually a pretty nice opportunity to clean it up. We could for example place the hook inside `WC_Meta_Box_Order_Items::output()` (adding a docblock to explain what it does) and then pass the result in here as a variable.

2022-01-31 16:07 UTC, barryhughes requested changes
Thanks for submitting this: seems reasonable but a few small changes are needed.

2022-02-08 17:26 UTC, xristos3490 commented on plugins/woocommerce/includes/admin/meta-boxes/views/html-order-items.php
> +		<?php if ( (bool) apply_filters( 'woocommerce_admin_order_should_render_refunds', 0 < $order->get_total() - $order->get_total_refunded() || 0 < absint( $order->get_item_count() - $order->get_item_c
Thanks for the review, @barryhughes! Sounds reasonable!

2022-02-09 07:27 UTC, xristos3490 commented
Tests are failing.

> We could for example place the hook inside WC_Meta_Box_Order_Items::output() (adding a docblock to explain what it does) and then pass the result in here as a variable.

Adding a filter into the `WC_Meta_Box_Order_Items::output()` function creates the need to include the same filter into multiple _WC_AJAX_ endpoints due to how each AJAX admin handler renders the order items table. e.g., `WC_AJAX::maybe_add_order_item()` [Line 973](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-ajax.php#L973) and others.

Instead of writing the same filter in multiple places, we could:
- Refactor the way we render the `html-order-items.php` in all accuracies by using a global `render` function, for example, in the `WC_Meta_Box_Order_Items` class, or;
- Leave the filter inline inside the template as is.

Moreover, I think introducing a new variable inside the `html-order-items.php`, or a dedicated `render` method for that matter, could potentially break 3rd party extensions using this template to include additional functionality in the order items table. 

Thoughts?

2022-02-15 16:53 UTC, barryhughes commented
You're right, it doesn't seem viable in this case and there isn't a particularly clean way to tidy this up without a larger body of work.

> Moreover, I think introducing a new variable inside the html-order-items.php, or a dedicated render method for that matter, could potentially break 3rd party extensions using this template to include additional functionality in the order items table.
> ...
> In my opinion, and because the template in question is widely used, I would opt for leaving the filter inline.

It still seems a shame to repeat it unnecessarily by inlining it. Given that all of the other data available to the template remains the same, do you see difficulties if we do something along these lines (ie, place the filter *once* at the top of the template):

```php
<?php
/**
 * Order items HTML for meta box.
 *
 * @package WooCommerce\Admin
 */

/**
 * Docblock for the new filter.
 */
$render_refunds = (bool) apply_filters( 'woocommerce_admin_order_should_render_refunds', 0 < $order->get_total() - $order->get_total_refunded() || 0 < absint( $order->get_item_count() - $order->get_item_count_refunded() ), $order->get_id(), $order );
?>

<!-- Other template code -->

<?php if ( $render_refunds ) : ?>
    <!-- Refund HTML -->
<?php endif; ?>

<!-- Other template code -->
```

2022-02-16 19:51 UTC, xristos3490 commented
> It still seems a shame to repeat it unnecessarily by inlining it.

I feel the same way! 

> do you see difficulties if we do something along these lines 

No. Placing the filter _once_ at the top of the template seems like a good idea at this point!

2022-02-16 23:05 UTC, barryhughes commented
Excellent, thanks. I tweaked the docblock a little (I believe this will actually ship in 6.4) and once tests pass I'll go ahead and merge. Thanks for the contribution :-)

2022-02-16 23:34 UTC, barryhughes approved these changes

2022-02-16 23:34 UTC, merged

2022-02-17 07:56 UTC, xristos3490 commented
Thanks, @barryhughes! 🙇 
I'll keep an eye on this to pass this filter/fix into the extension!