prevent line breaks in plugin author names
woocommerce/woocommerce pull request #31503
Opened 2021-12-23 15:04 UTC by Spreeuw

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
preventing unintended line breaks in the plain text version of the System Status Report when a plugin lists multiple authors separated by comma, such as:
```
Some plugin: by Some Company
LLC – 1.0
```
instead of:
```
Some plugin: by Some Company, LLC – 1.0
```

Or:

```
Another plugin: by John
Jane
Jack
Josh – 2.0
```
instead of:
```
Another plugin: by John, Jane, Jack, Josh – 2.0
```

Closes # .

### How to test the changes in this Pull Request:

1. Install a plugin with multiple authors (for example: [UpdraftPlus WordPress Backup Plugin](https://wordpress.org/plugins/updraftplus/), which currently lists "UpdraftPlus.Com, DavidAnderson")
2. Go to WooCommerce > Status
3. Click "Get system report" and observe that the plugin authors are no longer separated by newlines.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix: author list formatting in plain text system status report

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-01-28 12:15 UTC, vedanshujain requested changes
I think we can remove this whole logic actually.

2022-01-28 12:15 UTC, vedanshujain commented on plugins/woocommerce/legacy/js/admin/system-status.js
> +							}
```suggestion
						
```

I think we can just get rid of this line break logic. Status report looks fine without it as well, then you won't need to add all the data attributes above as well.

2022-01-28 19:52 UTC, Spreeuw commented
@vedanshujain thanks, that works for me too, I was simply trying to preserve the logic for whatever the original author intended it 👌

2023-05-01 07:53 UTC, samueljseay commented
@vedanshujain is this still relevant, can we rebase this and merge it as is?

2023-11-10 19:35 UTC, barryhughes commented
Thanks for your patience here, @Spreeuw—I'm sorry we lost sight of this change. 

Picking this back up, I do have a few concerns about how readable things will be after this change. On one hand, in relation to plugin authors, I think this is very welcome. For example, we go from:

```
Test Plugin: by Billy
Bobble
Baz – 1.0
```

To:

```
Test Plugin: by Billy, Bobble, Baz – 1.0
```

That's great, and I think it's an improvement. However, your proposed change also impacts other sections of the report. For example, looking at the Action Scheduler section, things are nice and readable at present:

```
### Action Scheduler ###

Complete: 195
Oldest: 2023-10-10 15:20:44 -0700
Newest: 2023-11-10 10:51:04 -0800

Failed: 521
Oldest: 2023-07-13 09:27:10 -0700
Newest: 2023-11-09 06:52:40 -0800

Pending: 3
Oldest: 2023-11-10 11:51:04 -0800
Newest: 2023-11-14 18:38:33 -0800
```

With this change, that becomes:

```
### Action Scheduler ###

Complete: 195, Oldest: 2023-10-10 15:20:44 -0700, Newest: 2023-11-10 10:51:04 -0800
Failed: 521, Oldest: 2023-07-13 09:27:10 -0700, Newest: 2023-11-09 06:52:40 -0800
Pending: 3, Oldest: 2023-11-10 11:51:04 -0800, Newest: 2023-11-14 18:38:33 -0800
```

Which is a little less readable. Something similar can be seen elsewhere, such as with the list of taxonomies. I tend to think that downsides outweight the benefits, currently. Perhaps there is a straightforward way to limit the change to only the plugin sections?

cc @thisissandip as you might have thoughts on this one.

2023-11-10 19:37 UTC, barryhughes requested changes
Please see above notes, I think we'd need some other changes before we can accept this.

2026-08-12 18:20 UTC, nerrad commented
This PR is stale and there have been significant changes to System Status since it was written.

2026-08-12 18:20 UTC, closed without merging