Issue/31555 add status field coupons api
woocommerce/woocommerce pull request #31561
Opened 2022-01-05 10:36 UTC by anitaa1990

Addresses part 1 of #31555. 

## All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

## Background

The Woo mobile app is working on adding coupon management to the app. As part of that project, there are a few enhancements in the GET Coupon(s) API endpoint that we would need to make. 
- We would need to display the status of the coupon. It looks like the GET Coupons and GET Coupon endpoints don't provide the status of the field. But this is available in `wp-admin`.
- It looks like only published coupons are available in the API response. It would be nice to list all coupons available for the store, regardless of the status, since Core displays it that way. 
-  Update the status of a coupon from the API.

### Designs
<img width="1541" alt="Screenshot 2022-01-05 at 4 03 09 PM" src="https://user-images.githubusercontent.com/22608780/148203152-e532f716-8538-4ea2-a85a-e8267d6c329b.png">
<img width="292" alt="Screenshot 2022-01-05 at 4 03 52 PM" src="https://user-images.githubusercontent.com/22608780/148203270-9a1112a5-842f-4e3d-9cfb-152bc282da84.png">

## Proposed Changes
This PR addresses the first point from the above list. i.e. add the `status` field to the GET Coupon(s) API response. Using an example JSON, this is how it would look like:

```
{
        "id": 13,
        "code": "test",
        "amount": "100.00",
        "status": "publish",   <-- New property added here
        "date_created": "2022-01-04T07:11:29",
        "date_created_gmt": "2022-01-04T07:11:29",
        "date_modified": "2022-01-05T09:45:28",
        "date_modified_gmt": "2022-01-05T09:45:28",
        "discount_type": "fixed_cart",
       ...
}
```

This change would allow us to reliably show the status of the coupon (as displayed in the designs). The rest of the blockers mentioned above will be taken care of in a separate PR. 

## How to test the changes in this Pull Request:
This is just a suggestion but please feel free to test other scenarios. 🙂

1. Add a new coupon in wp-admin → Coupons → Add New.
2. Publish the coupon (since only published coupons will be available in the API response).
3. In the API, run `GET /wp-json/wc/v3/coupons`.
4. Confirm that the `status` field is available in the API response.

## Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

## Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Adds `status` field to the `GET /coupons` endpoint. This will display the status of the coupon. 

## Questions
- I have marked this PR as draft for now since I'm not sure how to go about adding unit tests for this PR. I have updated some existing unit tests for coupons. But these tests seem to be part of the legacy package. Should I create a new class for `class-wc-coupon-data-store-cpt.php` or should I continue to use `plugins/woocommerce/tests/legacy/unit-tests/coupon/data-store.php`?
- Since this PR adds changes to the data in the coupons section, I feel like we should also update the related documentation [here](https://github.com/woocommerce/woocommerce/wiki/Coupon-Data). I can do that in this PR, if this is fine?

2022-01-05 17:17 UTC, joshbetz commented on plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php
> +				'status'	                  => $post_object->post_status,
```suggestion
				'status'                 => $post_object->post_status,
```

2022-01-05 17:18 UTC, joshbetz commented on plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php
> +				'status'	                  => $post_object->post_status,
Fixes an indentation issue

```suggestion
				'status'	                      => $post_object->post_status,
```

2022-01-05 17:19 UTC, joshbetz commented on plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php
> +				'status'                      => array(
```suggestion
				'status' => array(
```

2022-01-05 17:21 UTC, joshbetz commented on plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-coupons-v2-controller.php
> +					'description' => __( 'The status of the coupon. Should always be draft, published or pending review', 'woocommerce' ),
Minor: Oxford comma https://make.wordpress.org/docs/style-guide/punctuation/commas/#oxford-serial-commas
```suggestion
					'description' => __( 'The status of the coupon. Should always be draft, published, or pending review', 'woocommerce' ),
```

2022-01-05 17:23 UTC, joshbetz requested changes
A few minor style things, but otherwise this looks great to me.

2022-01-06 05:22 UTC, anitaa1990 commented
Thank you for the review @joshbetz 🙇‍♀️ I've updated the suggestions requested. Is there a command to run those indentation tests locally before I open the PR? I could do that in future PRs 😅

2022-01-06 20:41 UTC, joshbetz commented on plugins/woocommerce/tests/legacy/unit-tests/coupon/data.php
> +			'status'					 => 'publish',
```suggestion
			'status'                       => 'publish',
```

2022-01-06 20:42 UTC, joshbetz submitted a review, later dismissed

2022-01-07 06:39 UTC, anitaa1990 commented
Thanks for approving the PR @joshbetz 😄 I'm not sure how to merge this! There seems like one of the checks was cancelled and till it is completed, I'm not able to merge the PR. Do you know what I need to do?

2022-01-10 18:01 UTC, jeffstieler approved these changes
👍

2022-01-10 18:41 UTC, merged

2022-04-20 20:54 UTC, DanielLanger commented
@jeffstieler @anitaa1990 im not seeing this in the API docs https://woocommerce.github.io/woocommerce-rest-api-docs/#coupons

nor am I able to use the field. was this deployed?