Style the 2022 theme store notice.
woocommerce/woocommerce pull request #31683
Opened 2022-01-19 00:18 UTC by jeffstieler

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR seeks to add styling to the store-wide notice in the 2022 theme. I made the decision to bottom-align the notice. If that needs to change LMK!

| **Before** | **After** |
|-----|-----|
| ![Screen Shot 2022-01-18 at 5 12 11 PM](https://user-images.githubusercontent.com/63922/150039560-09409e00-a377-4550-bbac-cffc45a12fb1.png) | ![Screen Shot 2022-01-18 at 5 11 23 PM](https://user-images.githubusercontent.com/63922/150039630-650e4e32-9b78-4d0d-9f5c-83a386b6a383.png) |

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Fix - 2022 theme store notice styling.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-01-20 16:47 UTC, peterfabian requested changes
Thanks, looks good once the typo is fixed. Also, the dismiss button doesn't seem to work, but that's maybe out of scope for this one.

2022-01-20 16:47 UTC, peterfabian commented on plugins/woocommerce/legacy/css/twenty-twenty-two.scss
> +.awoocommerce-store-notice {
`awoocommerce` a typo? I don't see the corresponding class in the HTML.

2022-01-20 16:49 UTC, jeffstieler commented on plugins/woocommerce/legacy/css/twenty-twenty-two.scss
> +.awoocommerce-store-notice {
🤦‍♂️  😅

2022-01-20 17:09 UTC, jeffstieler commented
> Also, the dismiss button doesn't seem to work, but that's maybe out of scope for this one.

The dismiss button is working on my local store. Are you disallowing cookies perhaps? _(my screen capture app is crashing otherwise I'd offer proof)_

2022-02-01 09:06 UTC, peterfabian approved these changes
All works now, thanks. The dismiss problem was maybe just a quirk, not sure.

2022-02-01 09:06 UTC, merged