Add github workflow to automatically enforce the code freeze.
woocommerce/woocommerce pull request #31873
Opened 2022-02-09 19:51 UTC by jonathansadowski

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-02-10 14:39 UTC, roykho requested changes
Let some comments but I also have a concern. What if there are some PRs that haven't been merged yet? Sometimes they get created late and the release lead may not have time to get it merged. Then that means they would have to cherry pick right? What if the script checks for any PR that has a current milestone (next release) that hasn't been merged yet. It will not create the branch until these are merged in?

2022-02-10 14:39 UTC, roykho commented on .github/workflows/scripts/release-code-freeze.php
> +	echo "Created milestone {$milestone_to_create}.\n";
Maybe remove the ending period so it doesn't look like a milestone with a version and ending period has been created.

`Getting the list of milestones...
Latest open milestone: 6.4.0
Created milestone 6.5.0.
Created branch release/6.4.`

2022-02-10 14:39 UTC, roykho commented on .github/workflows/scripts/release-code-freeze.php
> +	echo "Created branch {$release_branch_to_create}.\n";
Same comment as above about the period.

2022-02-10 14:39 UTC, roykho commented on .github/workflows/scripts/release-code-freeze.php
> +	echo "DRY RUN: Skipping actual creation of release branch and milestone...\n";
Instead of using `\n` for newline perhaps use `PHP_EOL`. Same with other areas with `\n`

2022-02-10 14:39 UTC, roykho commented on .github/workflows/scripts/release-code-freeze.php
> +}
Needs empty line at the EOF.

2022-02-10 14:59 UTC, jonathansadowski commented
Thanks for the review. I've addressed the comments that you had with the code in my last commit.

> What if there are some PRs that haven't been merged yet? Sometimes they get created late and the release lead may not have time to get it merged.

I think that this is part of the motivation of automatically enforcing the code-freeze — to inspire contributors to a release to get their contributions in with plenty of time for inclusion in the release. Yes, they'll need to be cherry-picked, but they'll automatically be placed into the subsequent milestone, so it should be clear that they missed the train for the current release.

> What if the script checks for any PR that has a current milestone (next release) that hasn't been merged yet. 

In practice, I don't think that this would help us actually enforce the code freeze. It'd also introduce a lot of complexity regarding state into the equation, as we'd need to track that the action ran, did nothing, and then somehow schedule it to run again.

Maybe we can discuss on our call later the best way to handle this, and some of the edge-cases around it.

2022-02-10 15:07 UTC, roykho commented
> I think that this is part of the motivation of automatically enforcing the code-freeze

Yeah I understand however because we cherry pick, that kind of already defeats the purpose. My question/concern mostly stemmed from having to merge WC Admin and Blocks. Other contributions yeah I would agree if it isn't merged in on time, then they've missed the train. But same cannot be said for the packages as we still need to get those in.

2022-02-10 15:57 UTC, jonathansadowski commented
With Admin eventually going away as a package we pull in, the package issue will only really apply to Blocks, and they've been doing a pretty good job of making sure the version bump comes ahead of code freeze. We shouldn't encourage the exception. If they get it to us late, it needs to be cherry-picked, and there's a process for that. We shouldn't hide that work.

2022-02-10 17:45 UTC, roykho requested changes, later dismissed
Sorry I missed several PHP_EOL changes the first round.

2022-02-10 17:45 UTC, roykho commented on .github/workflows/scripts/post-request-shared.php
> +	echo "Getting the list of milestones...\n";
PHP_EOL

2022-02-10 17:45 UTC, roykho commented on .github/workflows/scripts/post-request-shared.php
> +	echo 'Latest open milestone: ' . $milestones[0]['title'] . "\n";
PHP_EOL

2022-02-10 17:45 UTC, roykho commented on .github/workflows/scripts/post-request-shared.php
> +		echo "WARNING: No milestone without release branch found, the newest one will be assigned.\n";
PHP_EOL

2022-02-11 14:33 UTC, jonathansadowski commented
Thanks for catching those additional `PHP_EOL`. Updated!

2022-02-11 15:14 UTC, roykho commented
So I had thought more on this feature. Currently it will blindly bump the version increasing it whenever this script is ran wether manually or scheduled. This can pose a problem for example if our current version is 6.3.0 and someone manually created a future milestone of 6.4.0. When this script is run, it will then bump the 6.4.0 to 6.5.0 and create a release/6.5 branch and milestone which is not what we want.

Discussed this with @jonathansadowski  on Slack and decided that we should have a way to first check the version for the current outgoing release and bump the version based on that and not from what the current (newest) milestone is. This will prevent the concern above from happening.

2022-02-25 18:25 UTC, jonathansadowski commented
Thanks for the feedback. I think this is ready for re-review.

2022-02-25 19:36 UTC, roykho commented
So currently if it can't create either the milestone or the branch it will show an error like this:

```
*** Error: Unable to create 6.6.0 milestone
*** Error: Unable to create release/6.5
```

This usually means either the branch or the milestone has already been created which is possible and not cause for a concern. So I am thinking perhaps change it to `Notice: Unable to create 6.6.0 milestone...skipping...` Or something to that affect so that it is not seen as something went wrong? Of course if the API comes back due to other reasons (timeout or can't reach the server) yes we should show the error accordingly. What do you think?

2022-02-25 21:03 UTC, jonathansadowski commented
Good idea. I've updated the message and added detection for the error GitHub returns when the branch or milestone already exist.

2022-02-25 22:07 UTC, roykho approved these changes
LGTM! Good work. Approved. But will let you merge it since I am not sure when we should have this take affect.

2022-02-25 22:14 UTC, merged

2022-02-25 22:15 UTC, jonathansadowski commented
Thanks — I think next release sounds as good as any 😄