Fix/#31990 - Guest order: Billing and shipping address not visible on order confirmation page
woocommerce/woocommerce pull request #31995
Opened 2022-02-28 09:50 UTC by priyankabehera

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #31990.
Here as we need to show the address either billing or shipping whichever is set up by admin from the WooCommerce setting for both logged in and guest users. So there is no need for the condition to check if the user is logged in. 

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-04-21 12:37 UTC, vedanshujain requested changes
hey @priyankabehera  thanks for the pull requests. I have added couple of minor notes that needs to be addressed before we can merge.

Additionally, seems like this PR has some commits that were reverted in the trunk. Maybe you would want to create a new PR with just your commit? Also please add the testing instructions. Thanks!

2022-04-21 12:37 UTC, vedanshujain commented on includes/admin/meta-boxes/views/html-product-data-general.php
> -		do_action( 'woocommerce_product_options_external' );
We actually cannot remove existing actions for backward compatibility. This would need to be added back.

2022-04-21 12:37 UTC, vedanshujain commented on templates/order/order-details.php
> -if ( $show_customer_details ) {
maybe we can improve the `$show_customer_details` instead of removing it, to display it when this is a guest order?

2022-04-28 06:16 UTC, priyankabehera commented
Hi @vedanshujain 

I am working on your points and I will create a new PR to solve the conflict.

2022-07-04 14:04 UTC, closed without merging