Fix issue #31477
woocommerce/woocommerce pull request #32049
Opened 2022-03-10 02:02 UTC by froger-me

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/31477

### How to test the changes in this Pull Request:

See https://github.com/woocommerce/woocommerce/issues/31477

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Fix `data.coupon_code` being `undefined` in checkout.js when removing a coupon on Checkout

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-03-30 21:35 UTC, barryhughes submitted a review, later dismissed
LGTM.

As soon as tests pass, we can merge—thank you :-)

2022-03-30 23:40 UTC, froger-me commented
Thanks @barryhughes ; I notice the E2E failure but I'm not really familiar with the automated test process. Is there anything I need to do on my end, and if yes, could you please offer guidance?

2022-03-30 23:46 UTC, barryhughes commented
So I re-ran the tests (since sometimes they fail unexpectedly, for unrelated reasons) but this seems to be failing consistently and in relation to coupon-related tests ... so it definitely deserves a closer look. 

Feel free to poke around if you have time (I don't have any specific tips, though) and if you don't, don't worry: we'll figure it out. My suspicion is there is an oversight in one of the tests.

2022-03-30 23:53 UTC, froger-me commented
What I can gather from the test's trace (and I don't know what to do with that info) is that there is a `TimeoutError` thrown I assume when loading assets to execute the test, resulting in a missing HTML element `.woocommerce-message` that's necessary.

2022-04-14 20:50 UTC, barryhughes commented
(Re-based on latest `trunk` code.)

2022-04-14 22:23 UTC, barryhughes commented
Sorry for the delay getting back to you here, @froger-me. The test fails are legitimate, as this change prevents removal of the coupon from the checkout. We're going to need a small change: I'll leave some notes inline.

2022-04-14 22:26 UTC, barryhughes commented on plugins/woocommerce/legacy/js/frontend/checkout.js
> +				coupon_code:	coupon
Let's revert this change, taking things back to:

```suggestion
				security: wc_checkout_params.remove_coupon_nonce,
				coupon:   coupon
```

Reason being this ajax handler expects to receive the `coupon` field in the request. Further down (line 671) we should switch from:

```js
$( document.body ).trigger( 'removed_coupon_in_checkout', [ data.coupon_code ] );
```

To:

```js
$( document.body ).trigger( 'removed_coupon_in_checkout', [ data.coupon ] );
```

2022-04-14 22:26 UTC, barryhughes requested changes
Please see notes; we need a minor change before we can accept this. Thanks!

2022-04-18 19:18 UTC, barryhughes approved these changes

2022-04-18 19:18 UTC, merged