CLI tool to analyze PR code
woocommerce/woocommerce pull request #32063
Opened 2022-03-12 06:27 UTC by claudiosanches

Working in progress...

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

CLI tool to analyze PRs for:

- Template files changed without a version bump
- Changes to database schema of Core, ActionScheduler, Admin, and Blocks
- New actions and filters

### How to test the changes in this Pull Request:

1. Check out this branch
2. Run `pnpm install`
3. Run `./tools/code-analyzer/bin/dev analyzer woocommerce/woocommerce branch-to-compare` 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

None

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-04-04 15:26 UTC, roykho commented
I think we need to add the tool to this workspace https://github.com/woocommerce/woocommerce/blob/trunk/pnpm-workspace.yaml otherwise `pnpm install` will not install the modules.

I tried adding some new hooks but it didn't seem to detect it? I did something like this:
```
/**
 * Test hook
 *
 * @since 6.5
 */
do_action( 'woocommerce_test_hook' );
```

2022-04-04 16:54 UTC, claudiosanches commented
@roykho the regex uses the full version number, that's why doesn't match with `6.5`, it is search for `6.5.0`. I'll try to improve it.

2022-04-04 19:10 UTC, roykho requested changes
This is the initial pass of the review. I have left some comments. I also noticed that if you pushed up changes that reverted the change, this tool is still picking up as there are changes. Perhaps we should account for that.

2022-04-04 19:10 UTC, roykho commented on tools/code-analyzer/bin/run.cmd
> +node "%~dp0\run" %*
Need an empty line at EOF.

2022-04-04 19:10 UTC, roykho commented on tools/code-analyzer/src/commands/analyzer/index.ts
> +		const matchHooks = `@since\\s+(${verRegEx})(.*?)(apply_filters|do_action)\\(\\s+(\\'|\\")(.*?)(\\'|\\")`;
Seems this pattern is incomplete. Missing a closing `)`. Also perhaps we should match `do_action( 'hook' );` and without space `do_action('hook');`.

2022-04-04 19:10 UTC, roykho commented on tools/code-analyzer/src/commands/analyzer/index.ts
> +					/(do_action|apply_filters)\(\s+(\'|\")(.*)(\'|\")/
Same comment as above.

2022-04-12 19:55 UTC, roykho commented
So I am still seeing the issue with the reverted code being picked up.

2022-04-14 17:17 UTC, roykho commented
I have found several issues and will break it down into two sections. One for CLI and one for GitHub.

**CLI**
* When no changes are found. I am still seeing a lingering header `## HOOKS:`
```
Generating patch for test/pr-cli-pr-review... done
Getting WooCommerce version... done
WooCommerce Version: 6.4.0
Scanning template changes... done
Scanning for new hooks... done
No template changes found

## HOOKS:
```
* When adding an action hook like `do_action()`, I see it being called a filter.
```
NOTICE | New filter found | \'woo_test\' introduced in 6.4.0
```
Perhaps change the `New filter found` to `New hook found`. So that way it can work for both filters and actions.
Second issue there is I am seeing the escape slashes.

**GITHUB**
* When no changes are found, a comment is created with the lingering header `## HOOKS:` just like in the CLI.
* For every change in the PR, a new comment is created. I would suggest to delete all the comments created by this action and add a new one on each trigger. This way you always have one up-to-date comment at the end.

2022-04-14 17:17 UTC, roykho requested changes
Left comments.

2022-05-10 02:42 UTC, psealock commented
**Status update** - I'm able to reproduce issues found by @roykho and fixed some eslint errors

### Fixed issues
* lingering header `## HOOKS` is resolved

### Unresolved issues
* hooks being called filters in `New filter found`
* Reverted code still produces a Comment
* A new comment is created on every `push` instead of editing or deleting the old

2022-05-11 17:57 UTC, psealock commented
@roykho Can you give this another look?

## Changes

* Updated RegEx so multiple hooks introduced in the same file can be found.
* Changed `diff` logic to pull down branches to compare instead of downloading a patch from Github. This means removed hooks due to reverted code don't produce a hook result.
* Updated the comment creation to include Update, Delete, and Add. This means there is a single comment being revised/deleted as necessary when hooks are added/updated/removed.

## Testing Instructions

1. Create a branch from this one
2. Add some test hooks. Try multiple hooks, some in the same file
3. Commit changes, push to origin and create a test pull request like [this one](https://github.com/woocommerce/woocommerce/pull/32955).
4. See the comment being added by woocommercebot.
5. Update or remove one hook, commit, push and see the comment updated to reflect changes.
6. Remove all hooks, commit, push and see the comment removed

2022-05-11 21:41 UTC, roykho requested changes
So in the CLI tool, I am still seeing slashes.
```
FILE: /plugins/woocommerce/woocommerce.php
---------------------------------------------------
HOOK: new_test
---------------------------------------------------
 NOTICE | New action found | \'new_test\' introduced in 6.6.0
---------------------------------------------------
HOOK: woo_test_filter
---------------------------------------------------
 NOTICE | New filter found | \'woo_test_filter\' introduced in 6.6.0
```

Also it would be good if the woocommercebot can add the `release: highlight` label to the PR when there are hook or template changes because we'll need this label to know what needs to be included in the release blog. Also make sure we remove this label if changes are reverted just like how to you remove the woocommercebot comment.

2022-05-11 21:41 UTC, roykho commented on .github/workflows/pr-highlight-changes.yml
> +              uses: actions/checkout@v2
Let's use v3 to be consistent with all other workflows.

2022-05-12 02:06 UTC, psealock commented
Thanks for the review @roykho 

I fixed the `actions/checkout` to `v3` and removed extra slashes. 

```
## HOOKS:
FILE: /plugins/woocommerce/includes/admin/class-wc-admin-assets.php
---------------------------------------------------
HOOK: woocommerce_test_hook_one
---------------------------------------------------
 NOTICE | New action found | 'woocommerce_test_hook_one' introduced in 6.6.0
---------------------------------------------------
FILE: /plugins/woocommerce/includes/admin/class-wc-admin-attributes.php
---------------------------------------------------
HOOK: woocommerce_test_hook_three
---------------------------------------------------
 NOTICE | New action found | 'woocommerce_test_hook_three' introduced in 6.6.0
---------------------------------------------------
```

I also add and remove the `release: highlight` label depending on if any hooks/template changes have been found. Could you give this another look?

2022-05-12 13:23 UTC, roykho commented
@psealock - so now I am seeing an error when I add a hook seen here https://github.com/woocommerce/woocommerce/runs/6406607045?check_suite_focus=true#step:3:14

My testing PR is here https://github.com/woocommerce/woocommerce/pull/32969

2022-05-12 23:00 UTC, psealock commented
Darn! Those slashes were needed in the Github context but not the CLI context. https://github.com/woocommerce/woocommerce/pull/32063/commits/5f68f1ed6878cf92fe5090aa617e7f38d3426865 makes a change to the output depending on the context to solve this problem. It should be working now if you can give it another look. Thanks @roykho

2022-05-13 02:55 UTC, roykho approved these changes
LGTM! Tested nicely now. Good Job!

2022-05-13 13:47 UTC, roykho commented
Hi @psealock - so just rereading the original task description and actually we also need to detect database changes.

2022-05-16 19:45 UTC, psealock commented
Thanks for the review @roykho. I created a new issue to track database changes https://github.com/woocommerce/platform-private/issues/51. I will continue with that next

2022-05-17 01:47 UTC, merged