Add build-watch command for woocommerce-admin
woocommerce/woocommerce pull request #32347
Opened 2022-03-24 18:14 UTC by louwie17

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added a `nx build-watch` command for the `woocommerce-admin` project. This actually watches changes in all the `js` packages and the client code.
This PR also modifies the current `build-watch` command for `woocommerce` to include the `build:feature-config` script that `woocommerce-admin` requires.

Closes # .

### How to test the changes in this Pull Request:

1. Run `pnpm nx build-watch woocommerce` and make sure it runs correctly
2. Run `pnpm nx build-watch woocommerce-admin` and make sure it runs correctly
3. While the above command is running, update files in both the `client` code or any of the `js` packages and see if it updates correctly.

### Changelog entry

> Dev: add `build-watch` command for the new WooCommerce Admin project.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-03-24 18:19 UTC, louwie17 commented on plugins/woocommerce/project.json
> +					"pnpm nx watch-assets woocommerce"
@Konamiman & @peterfabian I added the `build:feature-config` to the `build-watch` script for `woocommerce` only given it was already called for the `build` command. Let me know if there is any other places it should be run or if this will suffice?

2022-03-25 02:17 UTC, ilyasfoo requested changes
Thanks for adding this, @louwie17! I've bumped into these errors when I try to clean & build: `pnpm nx clean woocommerce-admin && pnpm nx build-watch woocommerce-admin`


```
ERROR in ./client/wp-admin-scripts/print-shipping-label-banner/index.js
Module build failed (from ../../node_modules/.pnpm/babel-loader@8.2.3_fa907c5a4f16ccc493e21649ccc59574/node_modules/babel-loader/lib/index.js):
Error: [redacted]/woocommerce/plugins/woocommerce-admin/babel.config.js: Error while loading config - Cannot find module './build/slack'
Require stack:
- [redacted]/woocommerce/packages/js/e2e-environment/index.js
- [redacted]/woocommerce/plugins/woocommerce-admin/babel.config.js
- [redacted]/woocommerce/node_modules/.pnpm/@babel+core@7.17.8/node_modules/@babel/core/lib/config/files/module-types.js
- [redacted]/woocommerce/node_modules/.pnpm/@babel+core@7.17.8/node_modules/@babel/core/lib/config/files/configuration.js
- [redacted]/woocommerce/node_modules/.pnpm/@babel+core@7.17.8/node_modules/@babel/core/lib/config/files/index.js
- [redacted]/woocommerce/node_modules/.pnpm/@babel+core@7.17.8/node_modules/@babel/core/lib/index.js
- [redacted]/woocommerce/node_modules/.pnpm/babel-loader@8.2.3_fa907c5a4f16ccc493e21649ccc59574/node_modules/babel-loader/lib/index.js
- [redacted]/woocommerce/node_modules/.pnpm/loader-runner@4.2.0/node_modules/loader-runner/lib/loadLoader.js
- [redacted]/woocommerce/node_modules/.pnpm/loader-runner@4.2.0/node_modules/loader-runner/lib/LoaderRunner.js
- [redacted]/woocommerce/node_modules/.pnpm/webpack@5.70.0_webpack-cli@4.9.2/node_modules/webpack/lib/NormalModule.js
- [redacted]/woocommerce/node_modules/.pnpm/webpack@5.70.0_webpack-cli@4.9.2/node_modules/webpack/lib/ModuleFilenameHelpers.js
- [redacted]/woocommerce/plugins/woocommerce-admin/unminify.js
- [redacted]/woocommerce/plugins/woocommerce-admin/webpack.config.js
- [redacted]/woocommerce/node_modules/.pnpm/webpack-cli@4.9.2_b04de8011015a40c567469bf79798750/node_modules/webpack-cli/lib/webpack-cli.js
- [redacted]/woocommerce/node_modules/.pnpm/webpack-cli@4.9.2_b04de8011015a40c567469bf79798750/node_modules/webpack-cli/lib/bootstrap.js
- [redacted]/woocommerce/node_modules/.pnpm/webpack-cli@4.9.2_b04de8011015a40c567469bf79798750/node_modules/webpack-cli/bin/cli.js
- [redacted]/woocommerce/node_modules/.pnpm/webpack@5.70.0_webpack-cli@4.9.2/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> ([redacted]/woocommerce/packages/js/e2e-environment/index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)

ERROR in components
Module not found: Error: Can't resolve '../../packages/js/components' in '[redacted]/woocommerce/plugins/woocommerce-admin'

ERROR in currency
Module not found: Error: Can't resolve '../../packages/js/currency' in '[redacted]/woocommerce/plugins/woocommerce-admin'

ERROR in customer-effort-score
Module not found: Error: Can't resolve '../../packages/js/customer-effort-score' in '[redacted]/woocommerce/plugins/woocommerce-admin'

ERROR in data
Module not found: Error: Can't resolve '../../packages/js/data' in '[redacted]/woocommerce/plugins/woocommerce-admin'

ERROR in experimental
Module not found: Error: Can't resolve '../../packages/js/experimental' in '[redacted]/woocommerce/plugins/woocommerce-admin'

ERROR in onboarding
Module not found: Error: Can't resolve '../../packages/js/onboarding' in '[redacted]/woocommerce/plugins/woocommerce-admin'
```


And another:
```
ERROR in ./client/tasks/fills/woocommerce-payments.js 8:0-68
Module not found: Error: Can't resolve '@woocommerce/onboarding' in '[redacted]/woocommerce/plugins/woocommerce-admin/client/tasks/fills'
 @ ./client/tasks/fills/index.js 11:0-32
 @ ./client/tasks/index.ts 5:0-17
 @ ./client/header/index.js 19:0-44 87:43-59
 @ ./client/layout/index.js 26:0-35 146:21-27
 @ ./client/index.js 15:0-80 27:89-99 43:90-101 58:19-29

ERROR in ./client/tasks/task-list-item.tsx 14:0-68
Module not found: Error: Can't resolve '@woocommerce/onboarding' in '[redacted]/woocommerce/plugins/woocommerce-admin/client/tasks'
 @ ./client/tasks/task-list.tsx 19:0-48 113:56-68
 @ ./client/tasks/tasks.tsx 23:28-25:14
 @ ./client/tasks/index.ts 4:0-32 9:15-20
 @ ./client/header/index.js 19:0-44 87:43-59
 @ ./client/layout/index.js 26:0-35 146:21-27
 @ ./client/index.js 15:0-80 27:89-99 43:90-101 58:19-29

ERROR in ./client/tasks/task.tsx 6:0-60
Module not found: Error: Can't resolve '@woocommerce/onboarding' in '[redacted]/woocommerce/plugins/woocommerce-admin/client/tasks'
 @ ./client/tasks/tasks.tsx 19:0-30 112:21-25
 @ ./client/tasks/index.ts 4:0-32 9:15-20
 @ ./client/header/index.js 19:0-44 87:43-59
 @ ./client/layout/index.js 26:0-35 146:21-27
 @ ./client/index.js 15:0-80 27:89-99 43:90-101 58:19-29
```

2022-03-25 13:05 UTC, louwie17 commented
Thanks for the review @ilyasfoo, it is fixed now, it seemed to be an issue where the `build` process for packages was still being run while it was also running the build/watch for the `client` code.
I made sure now that the build is done first, and then the watch is triggered.

2022-03-28 04:28 UTC, chihsuan approved these changes
Thanks for adding the command. Looks good and tested well. 👍

2022-03-28 06:09 UTC, rjchow commented
Hey thanks for doing this! Does this replace the `pnpm start` command [referenced in the README](https://github.com/woocommerce/woocommerce/blob/c5be40ec1523c15c49dab0d86f8b5396db90283a/DEVELOPMENT.md#getting-started-with-developing)?

2022-03-28 06:50 UTC, ilyasfoo approved these changes
Thanks for fixing it, LGTM!

2022-03-28 11:55 UTC, merged

2022-03-28 11:59 UTC, louwie17 commented
> Hey thanks for doing this! Does this replace the `pnpm start` command [referenced in the README](https://github.com/woocommerce/woocommerce/blob/c5be40ec1523c15c49dab0d86f8b5396db90283a/DEVELOPMENT.md#getting-started-with-developing)?

@rjchow you can still use `start` when your inside the `woocommerce-admin` folder. This command essentially does the exact same thing, just more the `nx` mono repo way.

2022-03-28 12:05 UTC, louwie17 commented
Although `pnpm start` from the root directory as that doc mentions, actually doesn't work. It would have to be run from the nested folder, or using `nx`.
I always referred to the wiki developer docs witch reference `build-watch`: https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment#install-dependencies-and-generate-assets