Update woocommerce-admin links to point to woocommerce repo
woocommerce/woocommerce pull request #32518
Opened 2022-04-07 08:58 UTC by chihsuan

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #32516.

- Update the links of woocommerce-admin in docs and package.json to point to https://github.com/woocommerce/woocommerce.
- Removed woocommerce-admin link from contributing guide.

### How to test the changes in this Pull Request:

1. Review the changes and make sure all links are correctly updated.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

docs: Update woocommerce-admin links to point to woocommerce repo

### FOR PR REVIEWER ONLY:

* [x] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-04-13 03:52 UTC, adrianduffell requested changes
This looks great, thanks for taking care of these details 👍 

I've just left a minor suggestion for a wording change.

2022-04-13 03:52 UTC, adrianduffell commented on .github/CONTRIBUTING.md
> +If you are contributing code to the (Javascript-driven) to Gutenberg blocks, note that it's developed in external package.
```suggestion
If you are contributing code to the (Javascript-driven) Gutenberg blocks, note that it's developed in an external package.
```

2022-04-13 04:38 UTC, chihsuan commented on .github/CONTRIBUTING.md
> +If you are contributing code to the (Javascript-driven) to Gutenberg blocks, note that it's developed in external package.
Good catch. Committed the suggestion!

2022-04-14 05:33 UTC, adrianduffell approved these changes

2022-04-14 05:34 UTC, adrianduffell commented
LGTM thanks @chihsuan! 🚀

2022-04-14 05:40 UTC, merged