Fix/starter pack monorepo
woocommerce/woocommerce pull request #32514
Opened 2022-04-07 04:55 UTC by psealock

### All Submissions:

* [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-04-11 16:07 UTC, jonathansadowski requested changes
When I try to run this, I get an error about a missing module (`fs-extra`).

Also, remember to run the changelogger ;)

2022-04-11 23:15 UTC, psealock commented
Thanks @jonathansadowski, I added the missing dependency and the changelogger has been run.

2022-04-20 19:09 UTC, jonathansadowski approved these changes, later dismissed
This tests well, nice work. I added a question about the executor, but I'm not sure if that'll matter once we move to Turborepo, so feel-free to merge as-is, or if you decide to update, I'm happy to re-review.

2022-04-20 19:09 UTC, jonathansadowski commented on plugins/woocommerce-admin/project.json
> +				"script": "create-wc-extension"
If we're going to keep this around, should this be `create-extension`?

2022-04-20 22:52 UTC, psealock commented
Thanks for the review @jonathansadowski. I removed the outdated reference, updated the README, and rebased against trunk. Could you give it quick look again? Thanks

2022-04-25 20:51 UTC, merged

2022-05-23 03:39 UTC, timnolte commented
There is a lot of other documentation that hasn't been properly updated to reflect these changes, for example the actual [WooCommerce Extension Developer documentation](https://developer.woocommerce.com/extension-developer-guide/creating-your-first-extension/).

2022-05-23 03:51 UTC, timnolte commented
I'm trying to use this setup using Node v16 & restricting the `pnpm` version to `6.24.x`, and i'm still getting the error:
> Error: Cannot find module 'fs-extra'
I'm performing this all from the `woocommerce` main monorepo directory. I first run `pnpm install` then attempt `pnpm run create-extension` and it just fails.

2022-05-24 05:31 UTC, psealock commented
Thanks for the comment @timnolte. Indeed, you are correct `fs-extra` has not been properly declared as a dependency.

I'll get a fix going and review the [documentation](https://developer.woocommerce.com/extension-developer-guide/creating-your-first-extension/).

2022-05-24 05:50 UTC, psealock commented
@timnolte could you give this a spin? https://github.com/woocommerce/woocommerce/pull/33169