Add `@types/testing-library__jest-dom` & declare TS modules
woocommerce/woocommerce pull request #32616
Opened 2022-04-14 03:14 UTC by chihsuan

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Part of https://github.com/woocommerce/woocommerce/issues/32581

Add `@types/testing-library__jest-dom` & declare as TS modules for non-TS modules to fix admin TS errors:

- Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement | null>'.
- Could not find a declaration file for module '@wordpress/plugins'.
- Could not find a declaration file for module '@woocommerce/tracks'.
- Cannot find module './logo.png' or its corresponding type declarations.

### How to test the changes in this Pull Request:

1. Run `pnpm install & pnpm nx build woocommerce-admin`
2. Run `pnpm nx ts:check woocommerce-admin`
3. Should not have 

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-04-15 06:05 UTC, rjchow requested changes

2022-04-15 06:05 UTC, rjchow commented on plugins/woocommerce-admin/client/typings/index.d.ts
> +declare module '@wordpress/plugins';
Hmm doing this just means that we will ignore any type definitions for everything imported from @wordpress/plugins

I think a better way is to install the typings from DefinitelyTyped : https://www.npmjs.com/package/@types/wordpress__plugins

And we should do it for the @wp/data, compose too.

For @woocommerce/tracks its one of our own packages and there aren't DefinitelyTyped definitions for it. I wonder if we should accept the error and create an issue to make type definitions for it?

2022-04-15 06:05 UTC, rjchow commented on plugins/woocommerce-admin/client/typings/index.d.ts
> +declare module '*.jpg';
```suggestion
declare module '*.jpg';
declare module '*.svg';
```

2022-04-15 06:05 UTC, rjchow commented on plugins/woocommerce-admin/client/typings/index.d.ts
> +declare module '*.jpg';
I noticed there was a declaration error for .svg too 😄

2022-04-15 08:52 UTC, chihsuan commented on plugins/woocommerce-admin/client/typings/index.d.ts
> +declare module '@wordpress/plugins';
Good catch! I didn't notice that they have `@types` packages.

> For @woocommerce/tracks its one of our own packages and there aren't DefinitelyTyped definitions for it. I wonder if we should accept the error and create an issue to make type definitions for it?

Yes, I think we could create an issue for this, but I'd like to ignore this error. Is that good?

2022-04-15 09:06 UTC, chihsuan commented on plugins/woocommerce-admin/client/typings/index.d.ts
> +declare module '*.jpg';
Thanks, updated. 2bf5c8f5abffd36ea910db3e44a5e08f61bbb075

2022-04-15 09:09 UTC, chihsuan commented on plugins/woocommerce-admin/client/typings/index.d.ts
> +declare module '@wordpress/plugins';
Added @wp/data, compose, plugin type definitions in 8df6178d3b5126d9d6461aeacc0dd2dc054a54e2

2022-04-19 02:43 UTC, rjchow approved these changes
Looks great! Thanks for making the changes 😃

2022-04-19 03:31 UTC, merged