Replace the date_created column name with a class property in the analytics DataStore
woocommerce/woocommerce pull request #32644
Opened 2022-04-15 15:09 UTC by xristos3490

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Please see the issue for the description.

Closes #32643

### How to test the changes in this Pull Request:

N/A

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [ ] Have you created a changelog file by running `pnpm nx affected --target=changelog`?

### FOR PR REVIEWER ONLY:

* [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-05-20 02:37 UTC, chihsuan requested changes
@xristos3490 Thanks for working on this! I just left a comment and it would be great if you could add a changelog entry via `pnpm nx  changelog woocommerce`

2022-05-20 02:37 UTC, chihsuan commented on plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php
> +	public static function db_datetime_format( $time_interval, $table_name, $date_column_name ) {
```suggestion
	public static function db_datetime_format( $time_interval, $table_name, $date_column_name = 'date_created' ) {
```

Could we add a default value for `$date_column_name` for backward compatibility?

2022-05-25 13:27 UTC, xristos3490 commented on plugins/woocommerce/src/Admin/API/Reports/TimeInterval.php
> +	public static function db_datetime_format( $time_interval, $table_name, $date_column_name ) {
Great catch, @chihsuan! 🎉

2022-05-25 13:37 UTC, xristos3490 commented
Thanks for the review, @chihsuan! Changelog file added 👍

2022-05-25 14:04 UTC, botwoo commented
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/32644/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add changelog` 58abc685cbe446368436dd64ed2ca594d3d45f90
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

2022-05-26 01:24 UTC, chihsuan approved these changes
Thanks @xristos3490. Looks good! 🚢

2022-05-26 01:24 UTC, merged