Add: temporary workaround to allow experimental products view task to be tracked correctly
woocommerce/woocommerce pull request #33052
Opened 2022-05-16 08:43 UTC by rjchow

- Wrap product task import around experiment
- Changelog
- Move out logic to be reusable
- Rigged a hack to let products task report its experimental assignment

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-05-17 07:26 UTC, botwoo commented
:bar_chart: Test reports for 212dda28cbd5b5e96b4e99ac09e2d8028cf89ded `changelogs` have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33052/api/)
- E2E Test Report (TBC)

Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them.

2022-05-17 08:09 UTC, botwoo commented
:bar_chart: Test reports for edd9aeebb542c21984e916c20c0fef41ac20510d `fixed tests` have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33052/api/)
- E2E Test Report (TBC)

Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them.

2022-05-18 02:12 UTC, ilyasfoo requested changes
Nice work on this so far, @rjchow! I've found a couple of issues:

1. It seems `import` variant is not passed, it gives the currently enabled experiment instead (either `card` or `stacked`)
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/3747241/168942799-b3274ccf-2675-45c7-855f-0220b8a9d0bd.png">


2. I'm getting this error in console:
```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    at a
    at ExternalLink (http://localhost:8888/wp-includes/js/dist/components.js?ver=796933f78811baa51a86b257df543749:48298:5)
    at span
    at div
    at a
    at Link (http://localhost:8888/wp-content/plugins/woocommerce/assets/client/admin/components/index.js?ver=1652785922:12734:5)
    at ListItem (http://localhost:8888/wp-content/plugins/woocommerce/assets/client/admin/components/index.js?ver=1652785922:12987:5)
    at li
    at Transition (http://localhost:8888/wp-content/plugins/woocommerce/assets/client/admin/components/index.js?ver=1652785922:55300:30)
    at CSSTransition (http://localhost:8888/wp-content/plugins/woocommerce/assets/client/admin/components/index.js?ver=1652785922:54850:35)
    at ul
    at TransitionGroup (http://localhost:8888/wp-content/plugins/woocommerce/assets/client/admin/components/index.js?ver=1652785922:55868:30)
    at List (http://localhost:8888/wp-content/plugins/woocommerce/assets/client/admin/components/index.js?ver=1652785922:12835:5)
    at div
    at CardList (http://localhost:8888/wp-content/plugins/woocommerce/assets/client/admin/chunks/client_tasks_fills_components_load-sample-product-modal_tsx-client_tasks_fills_components_use-09152e.min.js:165:5)
    at div
    at Products (http://localhost:8888/wp-content/plugins/woocommerce/assets/client/admin/chunks/client_tasks_fills_experimental-import-products_index_tsx.min.js:130:104)
    at slot_SlotComponent (http://localhost:8888/wp-includes/js/dist/components.js?ver=796933f78811baa51a86b257df543749:64450:5)
    at Slot
    at http://localhost:8888/wp-includes/js/dist/components.js?ver=796933f78811baa51a86b257df543749:64910:5
    at __webpack_modules__.../../packages/js/onboarding/build-module/components/WooOnboardingTask/WooOnboardingTask.js.WooOnboardingTask.Slot (http://localhost:8888/wp-content/plugins/woocommerce/assets/client/admin/app/index.js?ver=1652785922:5296:5)
```

2022-05-18 02:12 UTC, ilyasfoo commented on packages/js/onboarding/src/components/WooOnboardingTask/WooOnboardingTask.js
> +		setTimeout( () => pollForExperimentalVariant( id ), 200 );
I think this would require passing `count + 1`
```suggestion
		setTimeout( () => pollForExperimentalVariant( id, count + 1 ), 200 );
```

2022-05-18 02:13 UTC, rjchow commented on packages/js/onboarding/src/components/WooOnboardingTask/WooOnboardingTask.js
> +		setTimeout( () => pollForExperimentalVariant( id ), 200 );
🤦‍♂️

2022-05-18 07:17 UTC, ilyasfoo approved these changes
LGTM! We agreed to address the `<a>` warning in another PR

2022-05-18 07:24 UTC, merged