Include screenreader text for the regular & discounted price.
woocommerce/woocommerce pull request #33122
Opened 2022-05-19 19:02 UTC by discoinfiltrator

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Include screenreader text for the regular & discounted price. Using the same markup & language as in the woocommerce-blocks ProductPrice component:

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/components/product-price/index.tsx

Closes #31099 .

### How to test the changes in this Pull Request:

1. Ensure that a Product is on sale.
2. On this products item page, read the sale and discounted prices with a screen reader. Both should be read out.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-05-19 19:03 UTC, discoinfiltrator commented on plugins/woocommerce/includes/wc-formatting-functions.php
> +	$decimal       = ( ! empty( wc_get_price_decimal_separator() ) ) ? wc_get_price_decimal_separator() : $decimal_point;
phpcs gave warnings on these lines so I updated the spacing.

2022-05-19 19:04 UTC, discoinfiltrator commented on plugins/woocommerce/includes/wc-formatting-functions.php
> +	$price .= '<del>' . ( is_numeric( $regular_price ) ? wc_price( $regular_price ) : $regular_price ) . '</del>';
Removed `aria-hidden="true"` because we want this to be accessible to screen readers.

2022-05-19 19:04 UTC, discoinfiltrator commented on plugins/woocommerce/includes/wc-formatting-functions.php
> +	$price  = '<span class="screen-reader-text">' . __( 'Previous price:', 'woocommerce' ) . '</span>';
Same markup as in https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/components/product-price/index.tsx

2022-08-29 11:15 UTC, peterfabian approved these changes, later dismissed
Thanks for making WC more usable with screen readers! The change looks good to me.

2022-08-29 12:29 UTC, peterfabian requested changes
Actually, I can see that after my push that the tests are failing. @discoinfiltrator please let me know if you plan to update the tests. Thanks!

2023-05-03 11:04 UTC, samueljseay commented
We are closing this pull request, as the last activity has been quite some time ago. If you are still interested or you feel like this is a mistake, please open another PR based on a recent version of the trunk branch. Thanks!

2023-05-03 11:04 UTC, closed without merging