Add confirmation dialog for load sample products
woocommerce/woocommerce pull request #33171
Opened 2022-05-24 07:28 UTC by chihsuan

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #33167.

### How to test the changes in this Pull Request:

Make sure your site has the `woocommerce_allow_tracking` option set to yes

**Test load sample product - stack layout**

1. Go to Tools > WCA Test Helper > Experiments
2. Enable treatment for `woocommerce_products_task_layout_stacked`
3. Make sure there are no products in store (if there are in trash, empty them)
4. Navigate to `WooCommerce > Home`
5. Go to "Add products" task
6. Click `View more product types`
7. Click `Load sample products`
8. Observe that a confirmation dialog  is displayed
9. Click `Import sample products` button
10. Confirm that it loads the sample products
11. Go back to "Add products" task
12. Repeat 6~8 but click the `Cancel` button instead.
13. Confirm that the confirmation dialog is hidden

**Test load sample product - card layout**

1. Go to Tools > WCA Test Helper > Experiments
2. Enable treatment for `woocommerce_products_task_layout_card`
3. Make sure there are no products in store (if there are in trash, empty them)
4. Navigate to `WooCommerce > Home`
5. Go to "Add products" task
6. Click `View more product types`
7. Click the `CAN’T DECIDE?` card
8. Observe that a confirmation dialog  is displayed
9. Click `Import sample products` button
10. Confirm that it loads the sample products
11. Go back to "Add products" task
12. Repeat 6~8 but click the `Cancel` button instead.
13. Confirm that the confirmation dialog is hidden

**Test load sample product - import product view**

1. Go to Tools > WCA Test Helper > Experiments
2. Enable treatment for either `woocommerce_products_task_layout_stacked` or `woocommerce_products_task_layout_card`
3. Make sure there are no products in store (if there are in trash, empty them)
4. Go to OBW
5. Choose `Yes, on another platform` on the Business Details step
6. Navigate to `WooCommerce > Home`
7. Go to "Add products" task
8. Click `Or add your products from scratch`
9. Click the `Import sample products` button
10. Observe that a confirmation dialog  is displayed
11. Click `Import sample products` button
12. Confirm that it loads the sample products
13. Go back to "Add products" task
14. Repeat 6~8 but click the `Cancel` button instead.
15. Confirm that the confirmation dialog is hidden

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-05-24 07:42 UTC, botwoo commented
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33171/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `` 1c52d9c17ac5aff81988a4715db8f9b448af0134
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

2022-05-24 08:51 UTC, ilyasfoo requested changes
Thanks for such a quick turnaround on this one, @chihsuan! I have a few feedback:

For **Import screen** and **Stacked layout screen**, it seems `wcadmin_task_completion_time` track is triggered when clicking "Load sample products", making it inaccurate. We should change the track to trigger after user confirm to load samples.

2022-05-24 08:51 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/tasks/fills/components/load-sample-product-confirm-modal.tsx
> +			title="Load sample products"
Missed translation here

2022-05-24 08:51 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/tasks/fills/components/load-sample-product-confirm-modal.tsx
> +				{ __(
The `__` calls are missing `woocommerce` 2nd parameter

2022-05-24 08:59 UTC, chihsuan commented
> For Import screen and Stacked layout screen, it seems wcadmin_task_completion_time track is triggered when clicking "Load sample products", making it inaccurate. We should change the track to trigger after user confirm to load samples.

~Nice catch! Changed in 31af5fe5cc0a09855c9e036b3ca48a383b2af4fd~

Wait, looks like there is another track. 🤔

2022-05-24 08:59 UTC, chihsuan commented on plugins/woocommerce-admin/client/tasks/fills/components/load-sample-product-confirm-modal.tsx
> +			title="Load sample products"
Oops. Added in 8ff2c334d7144b390811a7c15b5ab80e8f54d707.

2022-05-24 08:59 UTC, chihsuan commented on plugins/woocommerce-admin/client/tasks/fills/components/load-sample-product-confirm-modal.tsx
> +				{ __(
Added in https://github.com/woocommerce/woocommerce/commit/8ff2c334d7144b390811a7c15b5ab80e8f54d707.

2022-05-24 09:12 UTC, chihsuan commented
> For Import screen and Stacked layout screen, it seems wcadmin_task_completion_time track is triggered when clicking "Load sample products", making it inaccurate. We should change the track to trigger after user confirm to load samples.

@ilyasfoo Thanks for catching this. Looks like we have duplicated the `wcadmin_task_completion_time` track for import sample products. I just removed an unnecessary one.

https://github.com/woocommerce/woocommerce/pull/33171/commits/1b8e90b52975889934ac793537ec9b4349114eae

2022-05-24 09:37 UTC, ilyasfoo approved these changes
>Thanks for catching this. Looks like we have duplicated the wcadmin_task_completion_time track for import sample products. I just removed an unnecessary one.

@chihsuan Nice! That would've been a sneaky bug otherwise, thanks for fixing it!

LGTM! 🚢 🚢

2022-05-24 09:53 UTC, merged

2022-05-26 16:57 UTC, jonathansadowski commented
This has been cherry-picked into the 6.6 release branch.