Fix typos COT verification messages.
woocommerce/woocommerce pull request #33207
Opened 2022-05-26 12:40 UTC by vedanshujain

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

### How to test the changes in this Pull Request:

1. Run the migration verification process, and check that verification messages change as expected.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm nx changelog <project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-05-26 13:07 UTC, botwoo commented
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33207/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Add changelog.` a82125f5c3124917a9a2c1adec0bbf1fd9d58588
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

2022-06-13 18:04 UTC, jorgeatorres requested changes
Hi @vedanshujain!
Overall this LGTM with only a few minor details that I've pointed out in the feedback. Let me know what you think 🙂.

2022-06-13 18:04 UTC, jorgeatorres commented on plugins/woocommerce/changelog/fix-typos
> +Fix typos in various cot migration messages.'
There's an apostrophe at the end of the line 😅.

2022-06-13 18:04 UTC, jorgeatorres commented on plugins/woocommerce/src/Database/Migrations/CustomOrderTable/CLIRunner.php
> +						'%1$d orders were verified in %2$f seconds. %3$d error(s) found %4$s. Please review above errors.',
```suggestion
						'%1$d orders were verified in %2$f seconds. %3$d error(s) found: %4$s. Please review above errors.',
```

2022-06-13 18:04 UTC, jorgeatorres commented on plugins/woocommerce/src/Database/Migrations/CustomOrderTable/CLIRunner.php
> +						'%1$d order was verified in %2$f seconds',
We probably want to end these sentences with a dot ".", for consistency with the other messages below.

2022-06-13 19:08 UTC, jorgeatorres commented
@vedanshujain: FYI I went ahead and made the relevant changes.

2022-06-13 19:08 UTC, jorgeatorres approved these changes

2022-06-13 19:08 UTC, merged