Update shipping recommendations display logic
woocommerce/woocommerce pull request #33529
Opened 2022-06-21 05:20 UTC by chihsuan

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #33370.

This PR updates shipping recommendations display logic and adds some tests for it.

AC:
- [x] Display WCS as recommended extension to be installed in Shipping Settings If the store sells physical products and is located in US, but JP and WCS are not installed:

### How to test the changes in this Pull Request:

1. Use a fresh site
2. Go to OBW and set store country to US
3. Go to `Woocommerce > Settings > Shipping` tab
4. Add a shipping zone
5. Observe that "Woocommerce Shipping" is displayed as a recommended extension
6. Change store country to a non-US country.
7.  Go back to `Woocommerce > Settings > Shipping` tab
8. Observe that "Woocommerce Shipping" is not displayed as a recommended extension
9. Change store country back to US
10. Install `Woocommerce Shipping` and activate `Woocommerce Shipping`
11. Go back to `Woocommerce > Settings > Shipping` tab
12. Observe that "Woocommerce Shipping" is not displayed as a recommended extension

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-06-21 05:50 UTC, botwoo commented
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33529/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Update shipping recommendations display logic` f9fc606fb0e913002e70d0f6def7116dcedb2ff2
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

2022-06-22 07:26 UTC, rjchow reviewed
Do we also need to check for the condition of whether the OBW profile indicates physical items || OBW not completed?

2022-06-22 08:34 UTC, chihsuan commented
> Do we also need to check for the condition of whether the OBW profile indicates physical items || OBW not completed?

@rjchow You're right. I completely missed that.

2022-06-22 09:12 UTC, chihsuan commented
I've updated it in 0ecdda988dcd6d57d2d341c739d99858e1f43aee

2022-06-22 09:12 UTC, chihsuan commented on packages/js/data/src/onboarding/types.ts
> +	| 'downloads'
https://github.com/woocommerce/woocommerce/blob/9c4c3834a725e01739a9e985cda26aac69dd2355/plugins/woocommerce/src/Internal/Admin/Onboarding/OnboardingProducts.php#L37-L39

2022-06-22 10:37 UTC, ilyasfoo requested changes
Did a quick test and it seems the "Get started" button isn't working, no errors in console https://d.pr/i/0yvG9J

2022-06-22 11:13 UTC, chihsuan commented
> Did a quick test and it seems the "Get started" button isn't working, no errors in console https://d.pr/i/0yvG9J

@ilyasfoo Thanks, this is expected. I didn’t implement it and left a todo comment there. It should go to new WCS flow when new flow page is created.

2022-06-22 11:22 UTC, ilyasfoo commented
Ah, of course, sorry! Didn't fully read the instructions yet

2022-06-22 12:03 UTC, ilyasfoo approved these changes, later dismissed
Looking great, @chihsuan! Thanks for adding unit tests, the coverage is excellent!

This tested well, however, I'm wondering if this step has any significance?

> Add a shipping zone and go back to the shipping tab.

2022-06-22 12:03 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/shipping/test/experimental-shipping-recommendations.tsx
> +	it( 'should not render when WCS is already installed and Jetpack is conneclted', () => {
Small typo

```suggestion
	it( 'should not render when WCS is already installed and Jetpack is connected', () => {
```

2022-06-23 01:20 UTC, chihsuan commented on plugins/woocommerce-admin/client/shipping/test/experimental-shipping-recommendations.tsx
> +	it( 'should not render when WCS is already installed and Jetpack is conneclted', () => {
Thanks, committed the suggestion!

2022-06-23 01:23 UTC, chihsuan commented
> This tested well, however, I'm wondering if this step has any significance?
> 
> > Add a shipping zone and go back to the shipping tab.

@ilyasfoo Good question. Actually, this is optional. I added this step to show the same UI. Let me remove it from the instructions.

2022-06-23 01:24 UTC, chihsuan commented on plugins/woocommerce-admin/client/shipping/test/experimental-shipping-recommendations.tsx
> +	it( 'should not render when WCS is already installed and Jetpack is conneclted', () => {
@ilyasfoo Could you approve this again? Thanks!

2022-06-23 01:34 UTC, ilyasfoo approved these changes
Alright, thanks for clarifying! Re-approving :shipit:

2022-06-23 01:54 UTC, merged