Update shipping task display logic
woocommerce/woocommerce pull request #33533
Opened 2022-06-21 09:02 UTC by chihsuan

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-06-21 09:47 UTC, botwoo commented
:bar_chart: Test reports for this pull request have been published and are accessible through the following links:

- [REST API Test Report](https://woocommerce.github.io/woocommerce-test-reports/pr/33533/api/)
- E2E Test Report (TBC)

Latest commit referenced in the reports: `Update ReviewShippingOptions.php` 4da34cc6a313150892777a3021c6b4ed178e9808
This comment will automatically be updated with the latest referenced commit when you push new changes to this pull request.

---

_Visit the [WooCommerce Test Reports](https://woocommerce.github.io/woocommerce-test-reports) homepage to view all published reports. See the [FAQs](https://github.com/woocommerce/woocommerce-test-reports/wiki/FAQs) page if you're having problems accessing them._

2022-06-23 06:24 UTC, ilyasfoo requested changes
The "Add shipping costs" task seems to be added only on experiment `woocommerce_tasklist_setup_experiment_1_2022_06` tasklist. When it's treatment, this passes. It seems the default tasklist doesn't have "Add shipping costs" task:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/3747241/175223310-d48cff87-3daa-4076-b3da-1e1bc87c713c.png">

It also seems not showing for when `woocommerce_tasklist_setup_experiment_2_2022_06` is treatment. I wonder if we should add to all the variants of tasklist?

------
> Review shipping options Task

I assume step #6 meant `woocommerce_admin_reviewed_default_shipping_zones` instead?

2022-06-23 06:50 UTC, chihsuan commented
> The "Add shipping costs" task seems to be added only on experiment `woocommerce_tasklist_setup_experiment_1_2022_06` tasklist. When it's treatment, this passes. It seems the default tasklist doesn't have "Add shipping costs" task: <img alt="image" width="500" src="https://user-images.githubusercontent.com/3747241/175223310-d48cff87-3daa-4076-b3da-1e1bc87c713c.png">
> 
> It also seems not showing for when `woocommerce_tasklist_setup_experiment_2_2022_06` is treatment. I wonder if we should add to all the variants of tasklist?
> 
@ilyasfoo Thanks for testing it with different variants!

I found actually the task title is different in different variants and I was assigned to `woocommerce_tasklist_setup_experiment_1_2022_06` treatment group

https://github.com/woocommerce/woocommerce/blob/93c15e9f7d7b4d8804aff00a0274b8b928cab67a/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Shipping.php#L28-L37


I believe all task lists include a Shipping task.

![Screen Shot 2022-06-23 at 14 48 28](https://user-images.githubusercontent.com/4344253/175233692-b713b966-9a12-46e3-9921-5cbcab989f36.png)
control

![Screen Shot 2022-06-23 at 14 47 01](https://user-images.githubusercontent.com/4344253/175233460-2a4e31c4-92af-4944-bd06-ae56e09dbab5.png)
`woocommerce_tasklist_setup_experiment_1_2022_06` treatment


![Screen Shot 2022-06-23 at 14 47 23](https://user-images.githubusercontent.com/4344253/175233488-1fa81d69-a084-4e3f-85ff-b0673a2131dc.png)
`woocommerce_tasklist_setup_experiment_2_2022_06` treatment


> I assume step #6 meant `woocommerce_admin_reviewed_default_shipping_zones` instead?

Ah, yes!

2022-06-23 07:07 UTC, ilyasfoo reviewed
Thanks for clearing that up, @chihsuan!

Another one:

> When automated shipping options have been set in #33366:
> - Change the name of the shipping task to `Review shipping options` and move it the `Things to do next` section.

My understanding of the above is when it's true, only one shipping task should be shown. In my case, it seems possible for both tasks to appear. Is this intended?

<img width="767" alt="image" src="https://user-images.githubusercontent.com/3747241/175236729-94f92658-306b-4e68-8283-6987d23dbc52.png">

2022-06-23 07:25 UTC, chihsuan commented
> My understanding of the above is when it's true, only one shipping task should be shown.

Yes, ideally only one shipping task should be shown.

>  In my case, it seems possible for both tasks to appear. Is this intended?

Because `woocommerce_admin_created_default_shipping_zones` option is set manually, it's possible to see two shipping tasks now. When #33366 is done, we shouldn't see two tasks simultaneously.

But that's a good question. I just added a check to prevent it happened when we have an unexpected bug. ef2eb977d9bf834f82af6c5091e64caff7ee6984

2022-06-23 07:35 UTC, ilyasfoo approved these changes
@chihsuan Awesome! LGTM! 🚢

2022-06-23 07:56 UTC, merged