Fix product variation tooltip
woocommerce/woocommerce pull request #33741
Opened 2022-07-05 19:25 UTC by louwie17

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #33552 .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-07-05 19:38 UTC, louwie17 commented on plugins/woocommerce/client/legacy/js/admin/meta-boxes-product-variation.js
> +				'.toolbar-variations-defaults .woocommerce-help-tip',
Added this `'.toolbar-variations-defaults .woocommerce-help-tip'` to make sure that the default form value tooltip was also being initialized.

2022-07-06 00:27 UTC, joelclimbsthings commented
Thanks @louwie17 , code changes look good and the tooltip is working. One issue that may or may not be worth fixing depending on how involved it would be; if you approach the tooltip from the bottom you can pretty easily get a flashing behavior:

![Peek 2022-07-05 17-24](https://user-images.githubusercontent.com/444632/177437863-19ea61b1-29f8-47b8-9fbe-4ffba4a9acc8.gif)

Saw it on both Firefox and Chrome, and haven't seen it on other tooltips.

2022-07-06 00:28 UTC, joelclimbsthings requested changes
--

2022-07-06 12:26 UTC, louwie17 commented
> Thanks @louwie17 , code changes look good and the tooltip is working. One issue that may or may not be worth fixing depending on how involved it would be; if you approach the tooltip from the bottom you can pretty easily get a flashing behavior:

Thanks for the review @joelclimbsthings, I was able to reproduce the flickering, nice catch! Adding `pointer-events: none` to the tooltip css seemed to do the trick and still keeps the tooltip working as expected.
This is ready for a re-review if you have some time @joelclimbsthings :)

2022-07-06 16:53 UTC, joelclimbsthings approved these changes
Thanks @louwie17 , had to remember to clear the turbo cache again, but it worked great! Nice solution. 🚢

2022-07-06 16:54 UTC, merged