Product creation experience: add more context about product data
woocommerce/woocommerce pull request #33755
Opened 2022-07-06 15:01 UTC by octaedro

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-07-08 13:23 UTC, louwie17 reviewed
This tested well @octaedro, I just noticed one spelling mistake in the class name. 

But as @jarekmorawski mentioned in the [last comment in the original issue](https://github.com/woocommerce/woocommerce/issues/33539#issuecomment-1177903551), the tooltip text does feel a little odd, pointing users to click on it instead, and not something we have done before.
I like the idea that Jarek proposed, or maybe we want to add a link within the tooltip that users can click? (although a recent change I made doesn't allow users to hover over the tooltip content, so that would make clicking a link within a bit difficult, I could update that though).

2022-07-08 13:23 UTC, louwie17 commented on plugins/woocommerce/client/legacy/css/admin.scss
> +		.tips_prodcut_types {
Spelling mistake, have to switch the `c` and `u` in `prodcut`

2022-07-08 13:23 UTC, louwie17 commented on plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php
> +			<a href="https://woocommerce.com/document/managing-products/#product-types" class="tips_prodcut_types" target="_blank"><?php echo wc_help_tip( __( 'Click in the icon to learn more about each produ
Same spelling issue as here as above in the class name.

2022-07-15 17:08 UTC, octaedro commented on plugins/woocommerce/client/legacy/css/admin.scss
> +		.tips_prodcut_types {
Nice catch! I fixed it in commit 0188d18

2022-07-15 17:08 UTC, octaedro commented
Hey @louwie17,

Could you take another look at this PR?

I added the fix to the typo you mentioned, the changes that [Jarek suggested](https://github.com/woocommerce/woocommerce/issues/33539#issuecomment-1184271711), and updated the testing instructions as well.

2022-07-18 19:37 UTC, louwie17 requested changes
Thanks for the updates @octaedro, nice work on getting the tooltip content to update when the dropdown changes 👍 
I just left one minor suggestion for a styling change to keep in sync with how the other tooltips look. Suggestion in in-line comment.

2022-07-18 19:37 UTC, louwie17 commented on plugins/woocommerce/client/legacy/css/admin.scss
> +				margin-left: 1em;
We might want to better reflect how the tip icon looks compared to the other icons:
<img width="780" alt="Screen Shot 2022-07-18 at 4 14 16 PM" src="https://user-images.githubusercontent.com/2240960/179602909-21fcc61a-94c5-44b5-bf81-ba6ce21e4edd.png">

They have this css:
```
font-size: 1.4em;
margin-left: 9px;
```

2022-07-18 21:13 UTC, octaedro commented on plugins/woocommerce/client/legacy/css/admin.scss
> +				margin-left: 1em;
Good eyes @louwie17! I fixed the icon's style in the commit d4266a3

2022-07-20 12:44 UTC, louwie17 approved these changes
Thanks for sticking with the several changes and iterations of this issue @octaedro, this tested well and code looks good as well, this is ready to ship :shipit: 💯

2022-07-20 16:36 UTC, merged