Fix free features is still rendered when no recommendation
woocommerce/woocommerce pull request #33923
Opened 2022-07-15 04:46 UTC by chihsuan

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #33915.

### How to test the changes in this Pull Request:
1. Start with a fresh install
2. Start OBW and use the following selections and click Continue

- Store Details.country/region: Afghanistan
- Industry: Food and drink
- Product Types: Physical products
- Business Details[how many products do you plan to display]: 1-10
- Business Details[currently selling else where?]: Yes, on another platform
- Business Details[How many employees do you have]: <10
- Business Details[What's your current annual revenue?]: Up to 3.000
- Business Details[Which platform is the store using?] BigCommerce

3. On the `Free features` tab, make a note of the plugins. You should see `MailPoet` and `Google Listings and Ads` only (when Jetpack is already installed).
4. Open a new tab and install and active the plugins listed on `Free features` manually.
5. Refresh `Free features` tab
6. Observe that the FreeFeatures tab is **not** rendered.

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-07-18 12:42 UTC, ilyasfoo requested changes
It seems in my test, the business step displays empty screen after clicking on continue. There's no error in console:

<img src="https://cdn-std.droplr.net/files/acc_1119691/LvEGKi">

2022-07-19 04:47 UTC, chihsuan commented
> It seems in my test, the business step displays empty screen after clicking on continue. There's no error in console:
> 
> ![](https://camo.githubusercontent.com/ed5101a3a6069652c291937362737c7325c6ecfe1dcb7ea708937108a22be302/68747470733a2f2f63646e2d7374642e64726f706c722e6e65742f66696c65732f6163635f313131393639312f4c7645474b69)

@ilyasfoo Sorry, I forgot to update the submit logic so it went to an empty free features screen.

I've fixed that in e6bd879bcfe66053efe9c1f9a19d1be2905ceefe. You can use [this release zip file](https://github.com/woocommerce/woocommerce/suites/7414922765/artifacts/302500464). 🙂

2022-07-19 04:48 UTC, chihsuan commented
E2E is failing but I think it's unrelated.

  > 2 failed
    [Chrome] › merchant/order-refund.spec.js:53:2 › WooCommerce Orders > Refund an order › can issue a refund by quantity 
    [Chrome] › merchant/order-refund.spec.js:111:2 › WooCommerce Orders > Refund an order › can delete an issued refund

2022-07-21 04:46 UTC, ilyasfoo approved these changes
Tested well, great work @chihsuan! 🚢

2022-07-21 04:57 UTC, merged