Add support for refunds and other order types in custom order tables
woocommerce/woocommerce pull request #34050
Opened 2022-07-23 05:42 UTC by vedanshujain

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-08-09 06:42 UTC, vedanshujain commented on plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php
> +	protected $internal_data_store_key_getters = array();
note that this prop, along with methods `get_internal_data_store_key_getters`, `update_order_from_object` and `update_order_meta_from_object` are moved form CPT data store to the abstract to provide more coverage and compatibility for custom data stores.

2022-08-23 16:38 UTC, jorgeatorres requested changes
Hi @vedanshujain!

Great work here 🥇. I really like how clean the implementation is in regards to order type (even supporting `read_multiple()` and everything). I left some feedback, which shouldn't be too difficult to address.

Overall this works great. I didn't test very extreme scenarios but I did confirm that migration picked up the refunds correctly and that refunding orders (while COT is authoritative) resulted in the proper records being created.

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php
> -	public function get_internal_data_store_key_getters() {
Similarly to this method, and given those were moved to `Abstract_WC_Order_Data_Store_CPT`, I believe it should be safe to remove `update_order_from_object()` and `update_order_meta_from_object()` from this datastore's class.

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php
> +	final public function init( OrdersTableDataStore $data_store, DataSynchronizer $data_synchronizer, OrdersTableRefundDataStore $refund_data_store, BatchProcessingController $batch_processing_controll
I'm not sure why the sniffs check didn't pick this up, but with the reordering of the params, the docblock also needs to be updated.

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php
> +		$this->refund_data_store = $refund_data_store;
Incorrect alignment of =.

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php
> +	public function get_total_tax_refunded( $order ): int {
Even though this hasn't been implemented yet, I believe this would also return a `float`, not `int`.

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php
> +			$order->set_date_created( gmdate( 'Y-m-d H:i:s e' ) );
Per our discussion in #34167 this should be `time()`.

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php
> +		$this->persist_save( $order );
Nice. This makes things clearer.

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php
> +			$order->set_date_created( gmdate( 'Y-m-d H:i:s e' ) );
Same as above. This should be `time()`.

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php
> +			$order->set_date_modified( gmdate( 'Y-m-d H:i:s' ) );
Another case of `time()` vs `gmdate()`?

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php
> +	protected function update_post_meta( &$refund ) {
Not that it makes a lot of difference, but why rename the variable to `$refund`?

2022-08-23 16:38 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableRefundDataStore.php
> + * For example, order save hooks etc can't be fired when saving refund, so we need to do it a seperate datastore..
```suggestion
 * For example, order save hooks etc can't be fired when saving refund, so we need to do it a separate datastore.
```

2022-08-24 09:57 UTC, vedanshujain commented on plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php
> -	public function get_internal_data_store_key_getters() {
Seems like they are duplicate methods, I added them to abstract classes but didn't remove them from here. Removed in https://github.com/woocommerce/woocommerce/pull/34050/commits/12e93996b3e841d4c37c4f5058fb0ff01bd5e953 now

2022-08-24 09:58 UTC, vedanshujain commented on plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php
> +	final public function init( OrdersTableDataStore $data_store, DataSynchronizer $data_synchronizer, OrdersTableRefundDataStore $refund_data_store, BatchProcessingController $batch_processing_controll
Maybe because they were added as part of a merge commit? Anycase, updated in commits/66016677b75c5c60720514907b34e19287867f67

2022-08-24 09:58 UTC, vedanshujain commented on plugins/woocommerce/src/Internal/DataStores/Orders/CustomOrdersTableController.php
> +		$this->refund_data_store = $refund_data_store;
Updated in https://github.com/woocommerce/woocommerce/pull/34050/commits/66016677b75c5c60720514907b34e19287867f67

2022-08-24 09:59 UTC, vedanshujain commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php
> +	public function get_total_tax_refunded( $order ): int {
Updated in https://github.com/woocommerce/woocommerce/pull/34050/commits/9a12ec0b8f39228101ffa493d056cf9ae6f1e0d5

2022-08-24 10:04 UTC, vedanshujain commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php
> +			$order->set_date_created( gmdate( 'Y-m-d H:i:s e' ) );
I missed this, thanks for catching it. Updated all date-related instances in https://github.com/woocommerce/woocommerce/pull/34050/commits/9a12ec0b8f39228101ffa493d056cf9ae6f1e0d5

2022-08-24 19:32 UTC, jorgeatorres approved these changes
LGTM :shipit: Thank you @vedanshujain!

2022-08-24 19:33 UTC, merged