Update store location profiler
woocommerce/woocommerce pull request #34153
Opened 2022-08-02 06:36 UTC by chihsuan

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-08-02 23:11 UTC, moon0326 approved these changes
LGTM and tested well 👍 🚀

2022-08-02 23:14 UTC, moon0326 requested changes
Actually, I noticed that the `Add store details` task is not marked as complete after completing the OBW.

**Steps to reproduce**: same as the testing instruction provided + navigate to WooCommerge -> Home and observe the task is not marked as complete.

2022-08-03 01:46 UTC, chihsuan commented
> Actually, I noticed that the `Add store details` task is not marked as complete after completing the OBW.
> 
> **Steps to reproduce**: same as the testing instruction provided + navigate to WooCommerge -> Home and observe the task is not marked as complete.
> 
> Record:
> 
>  Screen.Capture.on.2022-08-02.at.16-15-49.mp4

Thanks for catching it @moon0326! 

It seems that the store details task is only marked as complete [when "store address" and "city" fields are also filled out](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/StoreDetails.php#L73) as discussed [here](https://github.com/woocommerce/woocommerce/issues/32587#issuecomment-1172106157).

@verofasulo @SamratBiswas1 Since only the "Country / Region" field is mandatory in OBW now,  do you think we should change the complete logic of the `Add store details` task?

2022-08-03 10:16 UTC, chihsuan commented
> It seems that the store details task is only marked as complete [when "store address" and "city" fields are also filled out](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/StoreDetails.php#L73) as discussed [here](https://github.com/woocommerce/woocommerce/issues/32587#issuecomment-1172106157).
> 
> @verofasulo @SamratBiswas1 Since only the "Country / Region" field is mandatory in OBW now, do you think we should change the complete logic of the `Add store details` task?

Hi @moon0326 We have just discussed this on the Design call today. We decided that country is required for profiler step 1, but all address fields (post/zip code etc) are required to complete the task. 

Since it's not included in the original scope, could you please re-approve this PR?  I'll create a follow-up issue for the task complete logic. Thank you! 🙏

2022-08-03 16:42 UTC, moon0326 approved these changes
LGTM 👍 🚀

2022-08-03 16:42 UTC, moon0326 commented
> > It seems that the store details task is only marked as complete [when "store address" and "city" fields are also filled out](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/StoreDetails.php#L73) as discussed [here](https://github.com/woocommerce/woocommerce/issues/32587#issuecomment-1172106157).
> > @verofasulo @SamratBiswas1 Since only the "Country / Region" field is mandatory in OBW now, do you think we should change the complete logic of the `Add store details` task?
> 
> Hi @moon0326 We have just discussed this on the Design call today. We decided that country is required for profiler step 1, but all address fields (post/zip code etc) are required to complete the task.
> 
> Since it's not included in the original scope, could you please re-approve this PR? I'll create a follow-up issue for the task complete logic. Thank you! 🙏

Done 👍

2022-08-04 01:02 UTC, merged