Fix #32961
woocommerce/woocommerce pull request #34409
Opened 2022-08-21 22:18 UTC by daniyalahmadk

Fixed the issue by using native WordPress function:

https://developer.wordpress.org/reference/classes/wp_site_health/__construct/

### All Submissions:

-   [ x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1. Change the PHP Memory Limit to -1
2. Go to WooCommerce > Status and check the memory limit.

### Other information:

-   [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ x] Have you written new tests for your changes, as applicable?
-   [ x] Have you successfully run tests with your changes locally?
-   [ x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-10-09 10:55 UTC, Konamiman requested changes
Hi @daniyalahmadk, thanks for your contribution and sorry for the delay in the review. I've left some comments, could you please take a look? I'll pay more attention to your answers this time so we don't have to wait another year to get this moving. 🙂

2023-10-09 10:55 UTC, Konamiman commented on plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php
> +			$wp_memory_limit = WP_Site_Health::get_instance()->php_memory_limit;
With the old code and memory limit configured as -1 in `php.ini`, I see that with the existing code the status report is showing a memory limit of 256M (the value of `WP_MEMORY_LIMIT`), but with your change it shows just -1. Is this expected?

2023-10-09 10:55 UTC, Konamiman commented on plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php
> +		require_once ABSPATH . 'wp-admin/includes/plugin.php';
Why these changes? They seem unrelated to the issue of the memory limit display, or am I missing something?

2023-10-09 10:55 UTC, Konamiman commented on plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php
> -	}
Public methods in existing classes can't be removed (unless the class is in the `Automattic\WooCommerce\Internal` namespace or a subnamespace of that one) in order to keep backwards compatibility.

2023-10-09 10:55 UTC, Konamiman commented on plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php
> +				$wp_memory_limit = wc_let_to_num($environment['wp_memory_limit']);
The linter is complaining about this (missing spaces around the parenthesis) and other similiar lines in this file. Could you please fix them? You can do so by running `vendor/bin/phpcbf includes/admin/views/html-admin-page-status-report.php` while inside the `plugins/woocommerce` directory.

2025-04-24 23:38 UTC, nerrad commented
This is over two years old and quite stale so I'm going to close.

2025-04-24 23:38 UTC, closed without merging