Fix "1 of 2 steps" is shown for the first step in a 3 step tour
woocommerce/woocommerce pull request #34413
Opened 2022-08-22 03:08 UTC by chihsuan

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #34194.

This PR fixes the wrong step info of the shipping tour.

Before:

<img width="1392" alt="182948809-ee1db5ee-21e4-4f19-9c33-31a58aaa853b" src="https://user-images.githubusercontent.com/4344253/185830786-b3298ce2-c34b-4203-8018-7016f3743960.png">

After

![Screen Shot 2022-08-22 at 11 06 31](https://user-images.githubusercontent.com/4344253/185830798-cddd4c50-2b3c-4e8c-a8e2-472502767f8d.png)

### How to test the changes in this Pull Request:

1. Start with a fresh install and enable the shipping-smart-defaults and shipping-setting-tour feature flags
2. Start OBW and choose United States as store country
3. Choose "Physical products"
4. Complete the OBW without installing anything from the Business Details tab.
5. Navigate to WooCommerce -> Settings -> Shipping
6. "United States (US)" zone should be created with Free shipping method
7. Observe that the 3 step tour is displayed, with step one showing "Step 1 of 3"
8. There should be 3 steps in the tour, covering shipping zones, shipping methods and recommended shipping options
9. The tour should not appear again upon revisit or refresh of the page, if you complete the tour

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-08-26 03:55 UTC, ilyasfoo requested changes
I think the fix is unreliable, I've been getting 2 steps even with the delay. It seems on my instance it takes at least 2 seconds to load. On sites with worse performance (eg: 20+ plugins activated), I imagine it would require more delay.

<img width="1188" alt="image" src="https://cdn-std.droplr.net/files/acc_1119691/xjI2RR">

I think as an alternative to refactoring, we could also just copy & paste all the relevant resolver resolution status which should be reliable enough

2022-08-26 04:11 UTC, chihsuan commented
> I think the fix is unreliable, I've been getting 2 steps even with the delay. It seems on my instance it takes at least 2 seconds to load. On sites with worse performance (eg: 20+ plugins activated), I imagine it would require more delay.

Thanks for testing this! 👍 

> I think as an alternative to refactoring, we could also just copy & paste all the relevant resolver resolution status which should be reliable enough

In this case, I would prefer refactoring because if we copy & paste the logic then we need to ensure when we change one side, we must change another. Otherwise, it would break this again.

2022-08-26 09:16 UTC, chihsuan commented
@ilyasfoo I just found out that there is a simple way to fix this. 😃 We can put `<shippingTour />` directly in the `<ShippingRecommendations />` component so that we can pass a prop to ShippingTour to determine whether to show the step or not. I've updated the PR.

2022-08-29 09:19 UTC, ilyasfoo approved these changes
Awesome, @chihsuan! This tested well, LGTM! 🚢

2022-08-29 09:25 UTC, merged