Added woocommerce_reduce_order_item_stock action hook to let other plugin hook functionalities without looping through the order items again and again.
woocommerce/woocommerce pull request #34721
Opened 2022-09-17 03:30 UTC by yousuf-hossain-shanto

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Assume, you have to do something when the WooCommerce reduce order item stock by iterating through the line items. How can you do that?

The answer will, by using the ```woocommerce_reduce_order_stock``` hook which send order data to pass to callback function. But, you have to call ```$order->get_items()``` again and iterate again. And per iteration, you have to check 4-3 more conditions and call more queries again and again. But if we add a new hook at the end of the iteration block then we can reduce a lot of query call and complexities. Is't it good? I also have a real world example from my current project but can't disclose it before the plugin release, because of some company policies.

Into this PR, I have added a new ```woocommerce_reduce_order_item_stock``` hook which will pass line item, product and order data to the callback functions to do necessary things into the loop WooCommerce called to reduce stock. This will help the developers to reduce extra complexities.

### How to test the changes in this Pull Request:

1. By running pnpm test command

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm changelog add --filter=<project>`?

2023-01-19 14:25 UTC, jorgeatorres requested changes
Hi @yousuf-hossain-shanto!

Thanks for your contribution. It would've been nice to get more details about your use case here, but we see no harm on adding this filter.
That said, we have a few suggestions before this can be merged:

- We think it'd be useful to have all the info in the filter, so maybe the arguments should be: `$item, $changes, $order` instead. That way you can use the `from` and `to` values, but also the product.
- The docblock needs to be updated with these changes, but also the `@since` tag bumped to 7.4.0.

Please let me know what you think. Thanks again!

2023-01-21 04:14 UTC, yousuf-hossain-shanto commented
Hello @jorgeatorres, thanks for your feedback. I just made the changes as you said. Let me explain a bit about my use case

I'm working on a WC plugin where I have to execute some functions right after the stock change of a specific order item. Now I'm doing it using ```woocommerce_reduce_order_stock``` hook. WC is already using a loop through order items in the ```wc_reduce_stock_levels( $order_id )``` function. To access specific order item right after the stock change, there is no other option without using another loop through order items. This repeatedly looping issue can be resolved by adding the proposed ```woocommerce_reduce_order_item_stock``` hook.

Please feel free to ask me more about it

2023-03-08 15:10 UTC, jorgeatorres requested changes
Hi there!

Thanks for making the changes. I've left some feedback that needs to be addressed: a tiny coding standards issue and an update to the version tag in the docblock, which has to be changed because now the target WC version is 7.6.0.

Also, for me to be able to merge this, you need to add a changelog file to the PR, by running `pnpm changelog add --filter=woocommerce` locally and then adding the resulting file and pushing via Git.

I tried to make all these fixes for you, but your fork doesn't let me push changes, so I believe you'll have to do this yourself.

Once this is taken care of, we'll be ready to merge. Thanks again for your contribution!

2023-03-08 15:10 UTC, jorgeatorres commented on plugins/woocommerce/includes/wc-stock-functions.php
> +		$change = array(
This `=` sign should be aligned with the one below as per WP coding standards.

```suggestion
		$change    = array(
```

2023-03-08 15:10 UTC, jorgeatorres commented on plugins/woocommerce/includes/wc-stock-functions.php
> +		 * @since 7.4.0
Given it's been a few days you initially submitted this, the `@since` tag should now be `7.6.0` as that's when it'll be included in WC.

2023-03-08 16:09 UTC, yousuf-hossain-shanto commented
Hello @jorgeatorres , thanks a lot for your suggestion. I just committed the changes. Consider checking it

2023-03-08 21:04 UTC, jorgeatorres approved these changes
LGTM. Thank you @yousuf-hossain-shanto for your work on this one!

2023-03-08 21:05 UTC, merged