Add handling for plugin-feature incompatibilities
woocommerce/woocommerce pull request #34879
Opened 2022-09-29 11:17 UTC by Konamiman

WIP

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you successfully run tests with your changes locally?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> run changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-10-11 14:15 UTC, jorgeatorres requested changes
Hey @Konamiman! 👋

Great job here 🥇. I left some comments but overall this works and looks great.

My main concern (with the code) has to do with the renaming of `custom_order_tables` to `high_performance_order_storage`. I added some notes about this directly as part of the review.

There is another thing we feel should be discussed, which didn't really fit into the code review per se:

- Even though there's support for allowing enabling of features/plugins with incompatible features, there's really no UI for this at the moment. I might've missed whether this is planned or not, but it'd be very useful.
- "Uncertain" compatibility shouldn't prevent activation of plugins, or at least not if the uncertain compatibility is with a legacy feature. For example, "Analytics" is enabled _by default_ but then because all plugins have "uncertain" compatibility with it, it prevents them from being activated. This effectively means no one can activate current version of WC plugins even if they aren't using HPOS or any other experimental feature.

Please let me know what you think.

2022-10-11 14:15 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Features/FeaturesController.php
> +			'high_performance_order_storage' => array(
I don't think it's a good idea to change the name of this feature at this point: we [documented `'custom_order_tables'`](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility) as the proper way to declare (in)compatibility with HPOS.

Changing the name also means settings that have already been saved (for instance, enabling COT) stop working. There are also other implications for tests or users of `FeaturesUtil::feature_is_enabled()` that might be referring to the old name.

That said, I'm not entirely against renaming but then we should make sure that the methods in this class are able to work with either name as if they were synonyms. Also, we would need to make sure that the setting `woocommerce_feature_custom_order_tables_enabled` is migrated, but all of that might be too much work (or not?).

We're also manually setting this option in tests (`HPOSToggleTrait`) and the "COT Enable" plugin so this breaks a few things, though maybe that's "expected" given this hasn't been publicly released (?). In any case, we'd need to update the wiki, the "COT Enable" plugin and possibly other locations.

2022-10-11 14:15 UTC, jorgeatorres commented on plugins/woocommerce/includes/admin/class-wc-admin-settings.php
> +									<?php disabled( $value['disabled'] ); ?>
We should check if `'disabled'` exists before using it. This produces a PHP warning when browsing the WC settings on the admin.

2022-10-11 14:15 UTC, jorgeatorres commented on plugins/woocommerce/src/Utilities/PluginUtil.php
> +		$plugin_data = $this->proxy->call_function( 'get_plugin_data', WP_PLUGIN_DIR . DIRECTORY_SEPARATOR . $plugin_id );
Would it make sense to also cache the result of this function call? `get_plugin_data()` doesn't seem to cache things on its own, so this might result in unnecessary I/O if the function is called a few times during a request.

2022-10-11 14:15 UTC, jorgeatorres commented on plugins/woocommerce/src/Utilities/PluginUtil.php
> +			$all_plugins = $this->proxy->call_function( 'get_plugins' );
`get_plugins()` isn't [necessarily available on the frontend](https://developer.wordpress.org/reference/functions/get_plugins/#more-information).
There are a few places in WooCommerce where this function is also called, so we might be benefiting from those, but to err on the safe side, we should check whether the function exists or not, and if necessary, import the relevant admin file.

2022-10-11 14:15 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Features/FeaturesController.php
> +					$desc_tip = sprintf(
We should pass this string through `_n()` using `$incompatible_count - 2` as number to properly handle cases where the "remaining" plugins is just 1.
Otherwise, you end with a string such as "This feature shouldn't be enabled: Plugin1, Plugin2 and **1 more active plugins** aren't compatible with it." (emphasis mine)

Ideally, it'd say "one" instead of 1 but in any case we need to handle the pluralization of "plugins" correctly :)

2022-10-11 14:15 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Features/FeaturesController.php
> +				$message = sprintf(
Also needs to be passed through `_n()`.

2022-10-11 14:42 UTC, peterfabian commented
@Konamiman We discussed this with @beaulebens now and since HEs are not available during the rollout of 7.1 and if I understand correctly this paragraph

> Regardless of the current view, for plugins that haven't declared positive compatibility with at least one of the currently enabled features (again, excluding "Analytics" and "New navigation"), a warning will be shown

...it means that the default plugins list will show the warnings. Can we disable those until later please (maybe we'll put them back in 7.2 or when a higher % of plugins are compatible)? So that we'll still have the extra view, but the default view won't be flooded by the notices for everyone?

2022-10-12 10:20 UTC, vedanshujain commented
>  Can we disable those until later please (maybe we'll put them back in 7.2 or when a higher % of plugins are compatible)? 

Addressed in https://github.com/woocommerce/woocommerce/pull/34879/commits/5a3e897e1ddf776364a3b74ca3fd6058a8d3afa6

2022-10-12 10:20 UTC, vedanshujain commented on plugins/woocommerce/src/Internal/Features/FeaturesController.php
> +				$message = sprintf(
This is probably not required, the messaging seems correct for both 1 or more cases.

2022-10-12 10:20 UTC, vedanshujain commented on plugins/woocommerce/src/Internal/Features/FeaturesController.php
> +					$desc_tip = sprintf(
Addressed in https://github.com/woocommerce/woocommerce/pull/34879/commits/ee75210125c9740789c4167a7eebf2899166292a

2022-10-12 10:20 UTC, vedanshujain commented on plugins/woocommerce/src/Internal/Features/FeaturesController.php
> +			'high_performance_order_storage' => array(
Agree, given that we have published this change in upgrade parties and other public channels, we shouldn't change the name of the feature without a proper migration. Reverted in : https://github.com/woocommerce/woocommerce/pull/34879/commits/ee75210125c9740789c4167a7eebf2899166292a

2022-10-12 10:20 UTC, vedanshujain commented on plugins/woocommerce/includes/admin/class-wc-admin-settings.php
> +									<?php disabled( $value['disabled'] ); ?>
Addressed in https://github.com/woocommerce/woocommerce/pull/34879/commits/ee75210125c9740789c4167a7eebf2899166292a

2022-10-12 10:20 UTC, vedanshujain commented on plugins/woocommerce/src/Utilities/PluginUtil.php
> +			$all_plugins = $this->proxy->call_function( 'get_plugins' );
Addressed in https://github.com/woocommerce/woocommerce/pull/34879/commits/b3d25732c084e7918de756c7d96d1b1b0b0877d0#diff-3f95d040ab0c6a9f9bec0925cd1ab043c3a4dfdfc896e3460bf2edf5f22a52f6R56 (by loading the file in `init` method)

2022-10-12 13:55 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Features/FeaturesController.php
> +				$message = sprintf(
That's true in English, but we don't necessarily know how pluralization works for other languages. This seems like a minor inconvenience though, so I'm not holding off merging for that.

2022-10-12 14:08 UTC, jorgeatorres approved these changes
LGTM.Thanks @Konamiman & @vedanshujain!

2022-10-12 14:08 UTC, merged