Add contextual product more menu
woocommerce/woocommerce pull request #35447
Opened 2022-10-31 23:51 UTC by joshuatf

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds the product form's more menu and several links.

Note that the welcome guide and CES modal still need to be completed before they can be hooked up to this component.

<img width="234" alt="Screen Shot 2022-10-31 at 4 45 39 PM" src="https://user-images.githubusercontent.com/10561050/199130031-ecde579e-19b2-41ac-8e40-08824cfb95dc.png">

Closes #35177  .

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Navigate to the new product management experience ( Add new (MVP) )
2. Click the "more" (vertical ellipsis) button in the top right of the header
3. Note that each of the links closes the menu
4. Note that clicking "Use the classic editor" takes you to the classic editing experience
5. Navigate back to the new experience and publish a product
6. Click again on "Use the classic editor"
7. Note that you are taken to the classic editor for the respective published product

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-11-04 12:19 UTC, louwie17 requested changes
Tests well, and code looks good, just left a similar comment as #35431 in relation to the `registerPlugin` call.

2022-11-04 12:19 UTC, louwie17 commented on plugins/woocommerce-admin/client/products/product-more-menu.tsx
> +registerPlugin( 'woocommerce-product-more-menu', {
Similar to the this comment https://github.com/woocommerce/woocommerce/pull/35431#discussion_r1013332260 in the product title PR, I don't think this is necessary.

2022-11-15 20:23 UTC, joshuatf commented
Thanks for the review @louwie17!  I've rebased this after the product title PR merge and removed the unnecessary plugin registration call. 😄

2022-11-16 12:44 UTC, louwie17 approved these changes
LGTM 🚀 thanks for the rebase and `registerPlugin` update.

2022-11-16 15:02 UTC, merged