Add tracing support for key HPOS options.
woocommerce/woocommerce pull request #35446
Opened 2022-10-31 23:37 UTC by barryhughes

Track if HPOS is enabled—including relevant details such as if COT or CPT is the authoritative data store, if transactions are in use, etc. Replaces https://github.com/woocommerce/woocommerce/pull/35270 (which tried to do the same with Tracks, instead of WC Tracker).

Closes #34898.

### How to test the changes in this Pull Request:

Using WP CLI, try running:

`wp eval "print_r( WC_Tracker::get_tracking_data()['settings'] );"` 

At the end of the output, you should see a number of HPOS-related options, looking something like this:

```
    [hpos_enabled] => yes
    [hpos_sync_enabled] => yes
    [hpos_cot_authoritative] => yes
    [hpos_transactions_enabled] => no
    [hpos_transactions_level] => REPEATABLE READ
```

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2022-10-31 23:38 UTC, barryhughes commented
@peterfabian I hope you don't mind me selecting you directly for the review, felt like a good choice re our earlier conversation.

2022-11-22 15:01 UTC, peterfabian commented on plugins/woocommerce/includes/class-wc-tracker.php
> +			'hpos_cot_authoritative'                => get_option( 'woocommerce_feature_custom_order_tables_enabled' ),
I don't think this option determines whether HPOS is authoritative but rather whether the checkbox in Settings > Advanced is checked or not. I'd suggest to rename, and then including the option which says which table is in use.

2022-11-22 15:01 UTC, peterfabian requested changes
Looks good, thanks!

2022-11-24 13:31 UTC, barryhughes commented on plugins/woocommerce/includes/class-wc-tracker.php
> +			'hpos_cot_authoritative'                => get_option( 'woocommerce_feature_custom_order_tables_enabled' ),
Yes, they were the wrong way round: thanks for the catch, updated in https://github.com/woocommerce/woocommerce/pull/35446/commits/a15a167d1de3e8b7bf311867133f4ebd103dc4f9.

2022-11-24 13:34 UTC, peterfabian approved these changes
Looks good now, thanks!

2022-11-24 14:26 UTC, merged