Support opening direction prop for ExperimentalCollapsibleList component
woocommerce/woocommerce pull request #36806
Opened 2023-02-09 19:21 UTC by moon0326

### All Submissions:

-   [X] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #36805  .

This PR adds `direction` props to control which direction hidden items open.

![Screen Shot 2023-02-09 at 11 20 28 AM](https://user-images.githubusercontent.com/4723145/217915838-e1d38a05-79f6-4bc4-a9d1-af63efc3242d.jpg)

### How to test the changes in this Pull Request:

1. Run `pnpm --filter=@woocommerce/storybook run storybook` 
2. Click `experimental -> List -> List with CollapsibleListItem`
3. Change `direction` control to `bottom.
4. Confirm it works as expected.

### Other information:

-   [X] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [X] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-02-10 15:46 UTC, adrianduffell requested changes, later dismissed
Thanks @moon0326 ! This tested great, nice work!

One suggestion I have is to change the direction names  to `up | down` or something else. 🤔

It may just be me, but I was a bit confused with `top` initially because I was (wrongly) expecting it to put the items at the top of the list

2023-02-10 21:47 UTC, moon0326 commented
> Thanks @moon0326 ! This tested great, nice work!
> 
> One suggestion I have is to change the direction names to `up | down` or something else. 🤔
> 
> It may just be me, but I was a bit confused with `top` initially because I was (wrongly) expecting it to put the items at the top of the list

Good suggestion!

Updated in https://github.com/woocommerce/woocommerce/pull/36806/commits/28cd974a28647a59aa0aeedd416886061025fba1

2023-02-13 21:54 UTC, chihsuan approved these changes
Thanks @moon0326 LGTM and tested well! 🚀

2023-02-17 03:54 UTC, ilyasfoo approved these changes
Nice work, @moon0326! I'd prefer to add a test for direction but that could be worked on as a follow up. LGTM! 🚀

2023-02-17 22:11 UTC, merged