Update product editor package
woocommerce/woocommerce pull request #36830
Opened 2023-02-14 10:28 UTC by louwie17

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-02-16 13:58 UTC, nathanss requested changes

2023-02-16 13:58 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-field-item/README.md
> +| `id`         | String   | A unique string to identify your fill. Used for configuiration management.                                               |
typo here

2023-02-16 13:58 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-field-item/README.md
> +This is the slot component, and will not be used as frequently. It must also receive the required `location` prop that will be identical to the fill `location`.
Can you include context as to why it will not be used as frequently?

2023-02-16 13:58 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-section-item/README.md
> +This is the slot component, and will not be used as frequently. It must also receive the required `location` prop that will be identical to the fill `location`.
Same comments here are the above as it's copied

2023-02-16 13:58 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-tab-item/README.md
> +This is the slot component, and will not be used as frequently. It must also receive the required `location` prop that will be identical to the fill `location`.
Same

2023-02-16 13:58 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-section-item/woo-product-section-item.tsx
> +						>( children, tabOrder || 20, {
I'm not sure it falls within the scope of this PR, if not, please disregard it, but how about moving 20 and other numbers to a constant?

2023-02-16 13:58 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-tab-item/woo-product-tab-item.tsx
> +							templateData.order || 20,
Same comment as above

2023-02-17 12:02 UTC, louwie17 commented on packages/js/product-editor/src/components/woo-product-field-item/README.md
> +This is the slot component, and will not be used as frequently. It must also receive the required `location` prop that will be identical to the fill `location`.
Good point, I am not why I added that part, let me update this and the other two places as well.

2023-02-17 12:20 UTC, louwie17 commented
@nathanss thanks for taking a detailed look at the README's 👍 there were a couple other discrepancies that I also fixed, all as part of this commit:  https://github.com/woocommerce/woocommerce/pull/36830/commits/af16af11a3ffdb4182787305aa376183bc7b45b4

This should be ready for a re-review whenever you have some time.

2023-02-23 18:12 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-field-item/README.md
> +This is the slot component, and will not be used as frequently. It must also receive the required `location` prop that will be identical to the fill `location`.
I think you forgot to update this one

2023-02-23 18:14 UTC, nathanss requested changes

2023-02-23 18:14 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-field-item/README.md
> +This is the slot component, and will not be used as frequently. It must also receive the required `location` prop that will be identical to the fill `location`.
I think you forgot to update this one

2023-02-23 18:14 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-field-item/README.md
> +| `id`         | String   | A unique string to identify your fill. Used for configuiration management.                                               |
you forgot to fix this typo

2023-02-23 18:14 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-section-item/README.md
> +This is the slot component, and will not be used as frequently. It must also receive the required `location` prop that will be identical to the fill `location`.
you forgot to update here as well

2023-02-23 18:14 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-tab-item/README.md
> +This is the slot component, and will not be used as frequently. It must also receive the required `location` prop that will be identical to the fill `location`.
you forgot to update here as well

2023-02-23 18:14 UTC, nathanss commented on packages/js/product-editor/src/components/woo-product-tab-item/woo-product-tab-item.tsx
> +							templateData.order || 20,
you forgot the constant here

2023-02-23 18:43 UTC, nathanss approved these changes, later dismissed

2023-02-23 18:48 UTC, louwie17 commented
Thanks for the second review @nathanss, looks like I made all your previously suggested changes in the `components` package but forgot to do it in the `product-editor` package 🤦

2023-02-24 13:21 UTC, nathanss approved these changes

2023-02-24 13:37 UTC, merged