Fix HPOS unit tests for WC Order unit test classes
woocommerce/woocommerce pull request #36843
Opened 2023-02-15 11:56 UTC by vedanshujain

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-02-27 10:40 UTC, vedanshujain commented
Note that the test `Run unit tests on PR / PHP 7.4 WP latest HPOS ` will fail and is expected. Verify that none of the failures belong to WC_Tests_WC_Order_Query, WC_Abstract_Order_Test and WC_Order_Data_Store_CPT_Test. The Highlight templates changes seems like a build error, which I will fix in #36832

2023-02-27 10:58 UTC, vedanshujain commented
Note that I am checking `Highlight templates changes` test in #36685 but it looks like a build error rather than something in the code. Test `Run unit tests on PR / PHP 7.4 WP latest HPOS` is expected to fail, as will pass when all PRs in the stack is merged, however there should be no failing test for WC_Tests_WC_Order_Query, WC_Abstract_Order_Test and WC_Order_Data_Store_CPT_Test .

2023-03-03 09:30 UTC, Konamiman requested changes
I have requested a couple of minor styling changes, otherwise it looks good. There are a few unit tests that are failing in CI but they all pass for me locally.

2023-03-03 09:30 UTC, Konamiman commented on plugins/woocommerce/tests/php/includes/class-wc-order-factory-test.php
> +		\Automattic\WooCommerce\RestApi\UnitTests\Helpers\OrderHelper::toggle_cot( false );
I think these (and similar others in the same file) should be simplified into `use` statements for the namespaces, for readability and for consistency with what we normally do.

2023-03-03 09:30 UTC, Konamiman commented on plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/OrdersTableDataStoreTests.php
> +		$order_id = \Automattic\WooCommerce\RestApi\UnitTests\Helpers\OrderHelper::create_complex_data_store_order( $this->sut );
Same: please change to `use`s and simple class names.

2023-03-06 16:34 UTC, vedanshujain commented on plugins/woocommerce/tests/php/src/Internal/DataStores/Orders/OrdersTableDataStoreTests.php
> +		$order_id = \Automattic\WooCommerce\RestApi\UnitTests\Helpers\OrderHelper::create_complex_data_store_order( $this->sut );
Done in https://github.com/woocommerce/woocommerce/pull/36843/commits/fb356b686e10f779fb7e6a50908eefe9b7dea045

2023-03-06 16:34 UTC, vedanshujain commented on plugins/woocommerce/tests/php/includes/class-wc-order-factory-test.php
> +		\Automattic\WooCommerce\RestApi\UnitTests\Helpers\OrderHelper::toggle_cot( false );
Done in https://github.com/woocommerce/woocommerce/pull/36843/commits/fb356b686e10f779fb7e6a50908eefe9b7dea045

2023-03-06 16:34 UTC, vedanshujain commented
> There are a few unit tests that are failing in CI but they all pass for me locally.

This is expected, and they will start to pass as I continue to fold this PR stack.

2023-03-08 17:06 UTC, merged

2023-03-08 17:43 UTC, vedanshujain commented
Note that this was deleted and remerged in #37130