Use esc_html_e instead of esc_attr_e
woocommerce/woocommerce pull request #36868
Opened 2023-02-17 12:01 UTC by cyberwani

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-02-17 17:53 UTC, rrennick requested changes
@cyberwani Thanks for submitting this. It looks great. Could you add a changelog entry with

```
pnpm --filter=plugins/woocommerce run changelog add
```

2023-02-22 05:47 UTC, cyberwani commented
> @cyberwani Thanks for submitting this. It looks great. Could you add a changelog entry with
> 
> ```
> pnpm --filter=plugins/woocommerce run changelog add
> ```

I am on windows, and I got the error when I tried to install the package. See the below screenshot.
![image](https://user-images.githubusercontent.com/1647283/220533893-d6dcc49b-fb6a-458f-b03a-15aa9bf68092.png)

2023-05-12 17:27 UTC, rrennick commented
@cyberwani My apologies for dropping the ball on this PR. I added the changelog for you. The template version needs to be updated in `cart.php`. It would be quite difficult for me to make that change to the PR because it's based on your fork's `trunk` branch. If you could do that in the next few days then the version would be `7.8.0`.

2023-05-18 14:56 UTC, rrennick approved these changes

2023-05-18 14:56 UTC, merged