Add/36661 existing attribute layout
woocommerce/woocommerce pull request #36944
Opened 2023-02-24 00:38 UTC by octaedro

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-02-27 15:18 UTC, louwie17 requested changes
Nice work @octaedro, this was testing quite well and changes look good.
I did notice two very small things, a spelling mistake ( in code comment ) and the `Expand / close` buttons show up for me on the bottom of the `Add descriptive pieces of information...` screen (see screenshot )
I think we did want to hide this as well, maybe just hide the whole toolbar as we are already hiding the `Save Attributes` button.
![Screenshot 2023-02-27 at 4 10 48 PM](https://user-images.githubusercontent.com/2240960/221603457-cd0e310b-30f7-4b47-8179-64e1a6af21f2.png)

2023-02-27 15:18 UTC, louwie17 commented on plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-attributes.php
> +$is_add_glboal_attribute_visible = ! $has_local_attributes && $has_global_attributes;
Spelling mistake: `glboal` -> `global`

2023-02-28 03:52 UTC, octaedro commented on plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-attributes.php
> +$is_add_glboal_attribute_visible = ! $has_local_attributes && $has_global_attributes;
Nice catch!

2023-02-28 03:57 UTC, octaedro commented
Thank you @louwie17 for your review.
I just addressed the changes that you suggested. Could you give this PR another look?

2023-02-28 09:42 UTC, louwie17 requested changes
Thanks for updating the changes, I did notice one more bug which may of been caused by one of my prior suggestions (I am not sure).
When I don't have any global attributes and remove the auto added one the attributes section is fully blank, not allowing me to add any new attributes anymore.
See video:

https://user-images.githubusercontent.com/2240960/221814475-70a57be0-b05e-4418-9e0b-7f299e7418a3.mp4

2023-02-28 21:42 UTC, octaedro commented
> When I don't have any global attributes and remove the auto added one the attributes section is fully blank, not allowing me to add any new attributes anymore.

Nice catch @louwie17! I fixed it in the commit [552e120](https://github.com/woocommerce/woocommerce/pull/36944/commits/552e120e53b6a4e554b4160014742a125f239031)

2023-03-01 08:46 UTC, louwie17 requested changes
Hey Fernando, sorry, but I found some more edge cases :| as I was playing around with this.
But you did fix the last issue, thanks!
I know there is a lot of funny JQuery logic going on in here, so rather tough to find all the use cases in one go.

Edge case 1:
- Add a global attribute and add some terms and click **Save attributes**
- Remove the just added global attributes
- Add the same global attribute back in and add terms
- Click **Save attributes** and notice how it shows two rows of the global attribute
<img width="1022" alt="Screenshot 2023-03-01 at 9 41 27 AM" src="https://user-images.githubusercontent.com/2240960/222088238-bc9c6090-465d-4796-b89f-e78920550cf8.png">
- Click **Remove** on one and notice the placeholder is back but it shows the other global attribute at the bottom.
<img width="863" alt="Screenshot 2023-03-01 at 9 42 16 AM" src="https://user-images.githubusercontent.com/2240960/222088189-0893624c-2767-4441-8510-c36e4bba31d7.png">


Edge case 2:
- Add a global attribute through the new dropdown
- Don't add any terms and click **Save attributes**
- Only the **Save attributes** button shows
Expected: show either the toolbar again at the top, or the placeholder screen with the dropdown.
<img width="1017" alt="Screenshot 2023-03-01 at 9 37 10 AM" src="https://user-images.githubusercontent.com/2240960/222088340-d0617287-a434-4da0-9785-1c3477ab4c14.png">

2023-03-01 13:19 UTC, octaedro commented
Thank you @louwie17 for reporting these bugs.
I added [a small fix](https://github.com/woocommerce/woocommerce/pull/36944/commits/7d4a250a817cb74f59c0bdcb3423b66517bd306f) for [this screen](https://user-images.githubusercontent.com/2240960/222088340-d0617287-a434-4da0-9785-1c3477ab4c14.png). We should add a fix [like this](https://github.com/woocommerce/woocommerce/blob/3e2443713ca9debc158999bad3c23c965fe3b713/plugins/woocommerce/client/legacy/js/admin/meta-boxes-product-variation.js#L62-L64) to solve the 2nd case. (More context for that behavior [here](https://github.com/woocommerce/woocommerce/pull/36957#issuecomment-1450001696)).
Since the errors you mentioned are older than this PR, maybe we can merge this and create a couple of issues to tackle the bugs you mentioned in a couple of follow-up PRs.

2023-03-01 14:38 UTC, louwie17 approved these changes
Thanks for fixing that second scenario, and you are right that the first scenario is already present in `trunk`.
@octaedro do you know if there is an issue already created for that? So we can fix that.

For the rest this works as expected, thanks for sticking with the updates 🎉

2023-03-01 14:56 UTC, merged