Hide product attribute selector when adding the first local attribute
woocommerce/woocommerce pull request #36984
Opened 2023-02-27 18:01 UTC by nathanss

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #36665 .

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-02-28 14:05 UTC, louwie17 requested changes
Overall this tested well, although I did notice one issue when a user clicks `Remove` right away, as the dropdown will not show up then and the user will not be able to add attributes unless they refresh:
![Screenshot 2023-02-28 at 2 54 32 PM](https://user-images.githubusercontent.com/2240960/221876029-97cc8837-296a-4390-8756-52bed14711c5.png)

I am also kinda questioning this change in general, to me it feels a little strange that the `dropdown` only shows up after a user enters some values and then is displayed permanently (see video in PR description).
I think we are much better of keeping it displayed permanently (as it is now) without adding extra logic to handle all these edge cases. The fact we are having it showing up somewhat randomly from a users perspective, might cause them to be more confused then helping them be less so.
cc: @octaedro @jarekmorawski

2023-02-28 14:36 UTC, nathanss commented
@louwie17 I am also not so confident about this change, especially since the current architecture makes it very hard to maintain consistency, it seems very easy to let bugs and edge cases like this slip.

2023-02-28 15:20 UTC, mattsherman commented
> although I did notice one issue when a user clicks Remove right away, as the dropdown will not show up then and the user will not be able to add attributes unless they refresh

This is definitely a case that should be addressed if we proceed with this change.

I'm on the fence as to whether this change should be made at this point in time. On the one hand, it does (potentially) slightly reduce confusion in the case where there are no global attributes and no custom attributes.

But, the overall UX of this section is still confusing. You can still click "Add" multiple times after the first attribute is filled out, and get multiple empty attribute fields... when saving these are ignored though, so it isn't a big deal.

2023-02-28 15:22 UTC, mattsherman requested changes
The scenario where the user clicks "Remove" when there is only one attribute and the dropdown doesn't appear needs to be addressed.

Other than that, I think this change works as expected.

2023-02-28 15:24 UTC, mattsherman commented on plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js
> +			lastAttribute.find( 'h3' ).trigger( 'click' );
Why is this needed?

2023-02-28 20:00 UTC, mattsherman commented on plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js
> +			}
Should we do this when `$attributes.length > 0` to be a bit more robust and handle some unexpected case somehow more than one attribute was added?

2023-02-28 20:04 UTC, mattsherman commented on plugins/woocommerce/client/legacy/js/admin/meta-boxes-product.js
> +		$( '#product_attributes_actions' ).removeClass( 'hidden' );
The UI allows the attributes to be saved when not filled out. So, a save can result in zero attributes. We should check the number of attributes before showing these actions.

2023-03-01 11:49 UTC, jarekmorawski commented
> I am also kinda questioning this change in general, to me it feels a little strange that the dropdown only shows up after a user enters some values and then is displayed permanently (see video in PR description).

The idea was that the user would only see the form when they first enter this screen. They wouldn't see Remove button or the dropdown. The dropdown doesn't make much sense because what there's nothing we could show there. Can we hide them?

2023-03-01 12:09 UTC, nathanss commented
@jarekmorawski 

The objection that I have to this change is that it would make the user have to click twice in 'Save attributes' to add more than one Attribute if I didn't take the liberty of showing the toolbar again after the first attribute value is blurred:

https://user-images.githubusercontent.com/13437655/222134955-6a5e0f46-6acb-4292-abfa-117350a84d45.mov

It seems that this would make the experience worse for users that want to add more than one attribute.

On a related note, a lot of improvements that would be very simple with React can easily get complicated with the current architecture: Check this internal P2: pcQJnU-1if-p2

2023-03-01 13:00 UTC, jarekmorawski commented
I see your point. Clicking the save button twice adds unnecessary friction, and I'm sure there's a way to improve the whole flow without over-complicating the experience.

I'd like to spend a bit more time thinking about this. @pmcpinto, would you be okay with pausing this work for a while so we can explore a bit and see if there're other improvements we can make?

2023-03-02 09:51 UTC, pmcpinto commented
> I'd like to spend a bit more time thinking about this. @pmcpinto, would you be okay with pausing this work for a while so we can explore a bit and see if there're other improvements we can make?

Yes, let's do it

2023-03-07 10:51 UTC, jarekmorawski commented
I added extra flows and designs to 37099.

2023-03-10 16:09 UTC, octaedro commented
[This epic](https://github.com/woocommerce/woocommerce/issues/37099) changes a little bit the flow tackled by this PR so I'm going to close it.

2023-03-10 16:09 UTC, closed without merging