Notify betadownload only when secret is available
woocommerce/woocommerce pull request #37080
Opened 2023-03-06 14:21 UTC by szepeviktor

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This workflow failed in all recent PR-s.

2023-03-06 14:31 UTC, szepeviktor commented
![image](https://user-images.githubusercontent.com/952007/223139464-03649945-8e99-451e-83ac-ffcfefd0b0ac.png)

2023-03-08 10:48 UTC, lsinger requested changes
Thank you for addressing this, @szepeviktor! 

There's actually already [a guard](https://github.com/woocommerce/woocommerce/blob/9f2f03b4e8785163e36017be3af1d69b46cdc81b/.github/workflows/pr-build-live-branch.yml#L16) in this file to skip the workflow in forks because the secret would not be available then. That guard doesn't seem to work as expected, so I'd suggest using your solution of checking for the secret in place of the repository owner check. 

Note that `env.SECRET` is not available at that point and the check would need to be for `secrets.WOOBETA_SECRET` then. 

Would you mind making those changes?

2023-03-08 11:19 UTC, szepeviktor commented
Hello!
The secret context is not available in `if:`.

I let paid Automattic engineers resolve this.
My intention was to make you aware this problem.

2025-10-16 17:36 UTC, szepeviktor commented
Resolved in #48190

2025-10-16 17:36 UTC, closed without merging