Add the new feature to enable the new product editor blocks experience
woocommerce/woocommerce pull request #37137
Opened 2023-03-08 21:00 UTC by mdperez86

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

1.
2.
3.

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-03-08 23:09 UTC, joelclimbsthings requested changes
Thanks @mdperez86 , this will be a big help. I had one question, but aside from that  in my testing it seems to be working well!

2023-03-08 23:09 UTC, joelclimbsthings commented on plugins/woocommerce/src/Admin/Features/BlockEditorFeatureEnabled.php
> +		if ( ! Features::is_enabled( 'new-product-management-experience' ) && Features::is_enabled( self::FEATURE_ID ) ) {
So, if both feature flags are enabled, the block editor is still displayed but this condition is not met, so the styles/etc are not enqueued. Should this just be:
```php
if (Features::is_enabled( self::FEATURE_ID ) )
```

?

2023-03-09 13:32 UTC, mdperez86 commented on plugins/woocommerce/src/Admin/Features/BlockEditorFeatureEnabled.php
> +		if ( ! Features::is_enabled( 'new-product-management-experience' ) && Features::is_enabled( self::FEATURE_ID ) ) {
Yes they are. The same styles are being enqueued also if `new-product-management-experience` is enabled. So we don't want the same styles to be enqueue twice. See `plugins/woocommerce/src/Admin/Features/NewProductManagementExperience.php`.
Good catch!!. But this is intentional.

2023-03-09 18:02 UTC, joelclimbsthings commented on plugins/woocommerce/src/Admin/Features/BlockEditorFeatureEnabled.php
> +		if ( ! Features::is_enabled( 'new-product-management-experience' ) && Features::is_enabled( self::FEATURE_ID ) ) {
Ah, understood!

2023-03-09 18:03 UTC, joelclimbsthings approved these changes
Great job @mdperez86 , looks good! 🚢

2023-03-09 18:33 UTC, merged