Introduce a beta post command to the release post tool
woocommerce/woocommerce pull request #37142
Opened 2023-03-09 11:19 UTC by samueljseay

### All Submissions:

-   [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR introduces a new beta post generating command to simplify generating beta posts as part of release duties. I've tried to keep it very simple to use and infer as much information as possible.

Beta posts are a basic version of the release post and they consist of some basic info:

* Title
* Link to previous version post
* List of change highlights 
* Link to changelog of current version
* List of template/filter/hook changes 
* Dates of RC and Final
* Tags to ensure they're posted to the right place

The biggest pain I found was having to copy paste this stuff every time and remember to update all the links, so for the beta post I've opted to keep it simple for now and avoid trying to fill in everything. This new command fills in everything from the list above except for: **List of template/filter/hook changes** and **List of change highlights **.

It also make some assumptions to keep things simple:

* When you run it, it assumes you're doing a beta post for a release that will happen **next month**. 
* If you're running it to do a beta.2 or beta.3 (any beta above first), it will work out the previous version as being current beta -1
* If it's your first beta for a version (beta.1) it will work out the latest non-prerelease Github release and use that, It will also search developer.woocommerce.com posts to suggest the post to link to. It's a best effort based on search

**With these assumptions in place you get a quickly auto-generated and drafted post with a very simple command and it's up to you to go and adjust any details that weren't perfect. Instead of trying to make a complex command that does everything.
My reasoning is that if a command is hard to remember or takes too long, you're not going to run it. It needs to be convenient but also save you enough hassle. I hope this strikes the right balance.**

### How to test the changes in this Pull Request:

1. You'll need a wp.com oauth app, hopefully you already have one setup, otherwise [create one here](https://developer.wordpress.com/apps/new/). And you're going to need all the env variables set. e.g:

```
GITHUB_ACCESS_TOKEN="<create a classic token in github dev settings>"
WPCOM_OAUTH_CLIENT_ID="<id for the app you created>"
WPCOM_OAUTH_CLIENT_SECRET="<secret for the app you created>"

# optional - override if you need the redirect handler to run on a different port or path
WPCOM_OAUTH_REDIRECT_URI="http://localhost:3000/oauth"
```
2. Try an output only command e.g. `pnpm release-post beta 7.5.0-beta.1 --outputOnly`
3. Try publish draft by omitting `--outputOnly`

Have a look at the output and see if you're happy with it. It's designed that it expects you to run it around the right time, so the month is only going to be correct if you're running this when you first start rotation. But you can also override that.

4. Test override by providing a `--releaseDate` in your command in format `mm-dd-yyyy`. This flag refers to the final release date and so RC date will work backwards from that.

Note that during testing it will search the developer WC.com posts for a reasonable post to be chosen as the one to link to from previous, its not perfect, Feedback welcome on improving this. We could show every post with the right tag ordered by most recent published date instead. 

### Other information:

-   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [x] Have you written new tests for your changes, as applicable?
-   [x] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [x] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-03-10 20:14 UTC, jonathansadowski requested changes
Thanks for improving this... I added a few minor comments

2023-03-10 20:14 UTC, jonathansadowski commented on tools/release-posts/templates/beta-release.ejs
> +		href="https://github.com/woocommerce/woocommerce/blob/release/<%= previousVersion.major %>.<%= previousVersion.minor %>/plugins/woocommerce/readme.txt"
I think this should be `version.major` and `version.minor`, instead of `previousVersion`...

2023-03-10 20:14 UTC, jonathansadowski commented on tools/release-posts/templates/beta-release.ejs
> +	Beta <%= betaNumber %> for the March 2023 release of WooCommerce is now
If we're able to calculate the schedule below, could we remove the hard-coding for the Month / Year here?

2023-03-14 14:12 UTC, samueljseay commented on tools/release-posts/templates/beta-release.ejs
> +		href="https://github.com/woocommerce/woocommerce/blob/release/<%= previousVersion.major %>.<%= previousVersion.minor %>/plugins/woocommerce/readme.txt"
Whooops thanks!

2023-03-14 14:12 UTC, samueljseay commented on tools/release-posts/templates/beta-release.ejs
> +	Beta <%= betaNumber %> for the March 2023 release of WooCommerce is now
I thought I did this. Must have forgot to push it. Thanks for spotting.

2023-03-16 06:30 UTC, samueljseay commented
Thanks for spotting the mistakes @jonathansadowski I tested this and I believe its ready for re-review 🙇

2023-03-16 13:55 UTC, jonathansadowski approved these changes
Thanks for updating those two pieces. Looks good to me! 👍

2023-03-16 19:37 UTC, merged