Prevent unwanted helper api calls when loading subscription notes
woocommerce/woocommerce pull request #37378
Opened 2023-03-22 15:34 UTC by thilinah

### All Submissions:

-   [ ] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
-   [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
-   [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Connected WooCommerce stores send requests to helper API for fetching details related to subscriptions and to get information about plugin updates. The responses from these API endpoints are cached to prevent stores from sending multiple requests frequently. 

For example, the `GET subscriptions` request is cached for  1 hour and `POST update-check` request is cached for 12 hours.

But for some stores, the cache can be completely broken due to DB having a full disk. This is because when `set_transient` is called if the object cache is not configured for the site wp options table will be used to store the transient value. (further discussions in this [P2 post](https://wp.me/p6JqRr-4N1#comment-12553) and the [issue](https://github.com/Automattic/woocommerce.com/issues/11649)).

#### Problem

- Subscription notes are loaded via `admin_init`
- In order to prevent subscription notes from on every call to `admin_init` the option `LAST_REFRESH_OPTION_KEY` is used.
- But when the db disk is full, saving the latest updated time in wp_option should fail.
- This leads to subscription notes being loaded on every admin page load and cron run.
- Since the transients are not saved when the disk is full, this leads to store making get subscription API call multiple times.

Fix
- There is no need to check if subscription notes need to be refreshed on every admin page load. Instead, it can be checked only when the user visits a WC page showing the `Activity` tab.

Closes # .

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

#### Cron should not load subscription notes
- Make sure the site is connected to WCCOM via <your test site root>wp-admin/admin.php?page=wc-addons&section=helper
- Every time subscription notes are updated the option `woocommerce_admin-wc-helper-last-refresh` will be set to the current time. We will use this fact for testing.
- Checkout trunk.
- Run `wp option delete woocommerce_admin-wc-helper-last-refresh`
- Run cron `wp cron event run --all`
- Run `wp option get woocommerce_admin-wc-helper-last-refresh` and notice it exists.
- Checkout this branch.
- Run `wp option delete woocommerce_admin-wc-helper-last-refresh`
- Run cron `wp cron event run --all`
- Run `wp option get woocommerce_admin-wc-helper-last-refresh` and notice it doesn't exist.

#### Only visiting a WC Admin or a page with WC Admin Header Shall load subscription notes
- Checkout this branch.
- Run `wp option delete woocommerce_admin-wc-helper-last-refresh`
- Visit a non WC page like `wp-admin/edit-comments.php`
- Run `wp option get woocommerce_admin-wc-helper-last-refresh` and notice it doesn't exist.
- Visit a WC related page that shows `Activity` tab, such as `wp-admin/edit.php?post_type=shop_order`
![Screenshot 2023-06-02 at 12 47 59](https://github.com/woocommerce/woocommerce/assets/1531403/62dfce78-c733-424f-93b6-3212a3e2b6f1)
- Run `wp option get woocommerce_admin-wc-helper-last-refresh` and notice that it exists. (this means subscription notes are loading on this page)
- Repeat this test on any page to make sure all pages showing `Activity` tab are loading subscription notes.

#### Make sure the subscription notes are loading after this update
- Checkout this branch.
- Make sure your store is connected.
- You need to have an active product that is expiring soon (less than in 60 days)
- If this is not the case, you may update the expiry date of the subscription via the dashboard.
- Under [My Subscriptions](https://wp.test:4443/wp-admin/admin.php?page=wc-addons&section=helper) you should be able to see the expiry date.
![Screenshot 2023-06-02 at 12 41 41](https://github.com/woocommerce/woocommerce/assets/1531403/72f437db-a72f-4b6d-8bdd-5f599eded92f)
- Disable the auto-renew for this product via [My Subscriptions](https://woocommerce.test/my-account/my-subscriptions/)
- Run the following in `wp shell` to remove subscription notes.
```
\Automattic\WooCommerce\Admin\Notes\Notes::delete_notes_with_name('wc-admin-wc-helper-subscription');
```
- Update subscriptions under [My Subscriptions](https://wp.test:4443/wp-admin/admin.php?page=wc-addons&section=helper) 
![Screenshot 2023-06-02 at 12 41 55](https://github.com/woocommerce/woocommerce/assets/1531403/c92c0379-8c84-4fc3-bda3-853d18821d24)
- Run `wp option delete woocommerce_admin-wc-helper-last-refresh` reset last subscription notes refresh time.
- Load any WC page.
- Notice there is a new subscription note as a reminder to enable auto-renew for the above mentioned product.
![Screenshot 2023-06-02 at 12 41 21](https://github.com/woocommerce/woocommerce/assets/1531403/78982bb4-6308-4ae5-b8f2-1cc12f6797a5)

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?
-   [ ] Have you created a changelog file for each project being changed, ie `pnpm --filter=<project> changelog add`?
-   [ ] Have you included testing instructions?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-03-28 09:21 UTC, vedanshujain requested changes, later dismissed
Requesting a minor change if its possible

2023-03-28 09:21 UTC, vedanshujain commented on plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php
>  		$this->check_connection();
seems like this isn't required either, perhaps we can move this below the early return statements?

2023-04-07 13:09 UTC, vedanshujain commented
@thilinah This looks good to me, but I am assuming you are waiting for wc-admin folks to also take a look?

2023-04-18 02:43 UTC, rcstr submitted a review, later dismissed
Changes looks good and work as expected

2023-05-05 12:15 UTC, thilinah commented
> @thilinah This looks good to me, but I am assuming you are waiting for wc-admin folks to also take a look?

@vedanshujain if the changes look good can you please approve the PR, I see it's blocked due to the change request.

2023-05-05 12:34 UTC, vedanshujain commented
@thilinah dismissed my review, should be mergeable now

2023-05-16 09:01 UTC, nirolph submitted a review, later dismissed

2023-05-23 07:41 UTC, denho commented
@thilinah The WC notes are shown not only on `wc-admin` and `wc-addons` pages. They are also loaded on other WC pages in admin, such as orders list or settings.  
<img width="386" alt="image" src="https://github.com/woocommerce/woocommerce/assets/2803994/c1e5d142-fc47-41cc-bd16-8c52e3f18ad0">
On those pages, the subscription notes are not refreshed due to changes in your PR, and the user will not get the latest  notes until they visit `wc-admin` and `wc-addons` pages.

2023-06-01 12:31 UTC, thilinah commented
> On those pages, the subscription notes are not refreshed due to changes in your PR, and the user will not get the latest notes until they visit wc-admin and wc-addons pages.

@denho in this case I think skipping subscription notes loading based on the page won't work. I've noticed that other WC plugins like subscriptions and bookings also show the `Activity` button. So post_types such as `shop_order`, `shop_subscription`, `shop_coupon`, `product`. 

Due to this, I think we should consider moving forward with https://github.com/woocommerce/woocommerce/pull/36846 and move the discussion to that PR for refining the approach.

2023-06-01 12:38 UTC, thilinah commented
Also, another way could be to make sure subscription notes are not loaded via the cron.

2023-06-02 11:10 UTC, thilinah commented
@denho @nirolph @rcstr re-requesting reviews for this PR since the code and test instructions are updated.

2023-06-13 17:26 UTC, rcstr approved these changes
Changes looks good and works as described

2023-06-20 15:51 UTC, jonathansadowski commented
I'm going to clear the milestone from this for now, so that this doesn't inadvertently get missed once it's merged. A milestone will be added automatically by our automation upon merge.

2023-06-26 11:45 UTC, denho approved these changes
Added some suggestions in the code. Otherwise, LGTM!

2023-06-26 11:45 UTC, denho commented on plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php
> +		if ( ! \Automattic\WooCommerce\Admin\PageController::is_admin_or_embed_page() ) {
How about adding `use \Automattic\WooCommerce\Admin\PageController` and replacing this line with 
```suggestion
		if ( ! PageController::is_admin_or_embed_page() ) {
```

2023-06-26 11:45 UTC, denho commented on plugins/woocommerce/src/Internal/Admin/Notes/WooSubscriptionsNotes.php
> +	public function admin_head() {
Would be good to have a more meaningful description of the method functionality in the DocBlock, and method name.

2023-07-03 13:22 UTC, thilinah commented
@jonathansadowski, the PR is approved. Is it possible to get this merged?

2023-07-10 19:39 UTC, jonathansadowski commented
Hi @thilinah, please feel free to merge once checks have passed (as they have in this case), and you've gotten your PR approved. If you don't have access to merge yourself, let me know and I can take a look further.

2023-07-11 13:15 UTC, thilinah commented
@jonathansadowski I'm not authorized to merge.

2023-07-11 14:02 UTC, merged

2023-07-11 14:03 UTC, jonathansadowski commented
Thanks @thilinah, I've merged this for now — I'll look into whether or not that should be the case.