Fixed issue of Backtrace for error Uncaught TypeError: Unsupported op…
woocommerce/woocommerce pull request #37571
Opened 2023-04-05 04:17 UTC by nikhiltechahead

…erand types: string * int inwoocommerce/includes/admin/reports/class-wc-report-sales-by-date.php

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

2023-04-06 02:49 UTC, nikhiltechahead commented
This PR is to fix the **Backtrace for error 'Uncaught TypeError: Unsupported operand types: string * int inwoocommerce/includes/admin/reports/class-wc-report-sales-by-date.php:412 #36761**

**Issue:** https://github.com/woocommerce/woocommerce/issues/36761

2023-09-05 17:01 UTC, rrennick requested changes
@nikhiltechahead I apologize for the delay in responding for this PR. I mistakenly thought we had fixed these warnings in another PR. In addition to the code issue I identified, could you please add testing instructions so that non-coding testers will be able to test this PR?

2023-09-05 17:01 UTC, rrennick commented on plugins/woocommerce/includes/admin/reports/class-wc-report-sales-by-date.php
>  			$this->report_data->total_tax_refunded          += floatval( $value->total_tax < 0 ? $value->total_tax * -1 : $value->total_tax );
This is another instance that should be fixed.

2026-08-12 17:51 UTC, nerrad commented
It looks like the original issue was addressed separately as a part of #64362

2026-08-12 17:51 UTC, closed without merging