Solved issue of Ellipsis menu overlaps on small screen
woocommerce/woocommerce pull request #37583
Opened 2023-04-05 19:17 UTC by kshojib

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #37517 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create any test site.
2. Install and activate WooCommerce 6.9 Beta 2.
3. Go to "Woocommerce > Home" page.
4. Open the browser devtools.
5. Click on the "Responsive Design mode".
6. Change it to any smaller viewports.

2023-04-06 03:36 UTC, chihsuan requested changes
Hey @kshojib Thanks you so much for fixing this issue! 👍 

Tested well. However, I think we don't need to add woocommerce/package.json and pnpm.lock files. Could you please remove them? Thank you!

2023-04-07 10:43 UTC, chihsuan submitted a review, later dismissed
Thanks for fixing it @kshojib!

Left one suggestion for the changelog message. Others look good. Pre-approving! 👍

2023-04-07 10:43 UTC, chihsuan commented on plugins/woocommerce/changelog/fix-37517-fix-ellipsis-menu-overlaps
> +37517-fix-ellipsis-menu-overlaps
```suggestion
Fix ellipsis menu overlaps on small screen
```

2023-04-12 02:01 UTC, chihsuan submitted a review, later dismissed
LGTM!

2023-04-12 10:54 UTC, ilyasfoo approved these changes
Tested well, thanks folks! 🚢

2023-04-12 10:57 UTC, ilyasfoo requested changes
Actually, it seems there's [lint error](https://github.com/woocommerce/woocommerce/actions/runs/4637576333/jobs/8277388073?pr=37583#step:4:628):

```
plugins/woocommerce-admin lint: client/task-lists/progress-header/progress-header.scss
plugins/woocommerce-admin lint:  77:9  ✖  Expected indentation of 2 tabs  indentation
plugins/woocommerce-admin lint:  86:9  ✖  Expected indentation of 2 tabs  indentation
plugins/woocommerce-admin lint:  ELIFECYCLE  Command failed with exit code 2.
```

2023-04-17 05:22 UTC, ilyasfoo approved these changes
Thanks, @kshojib! LGTM

2023-04-17 05:22 UTC, merged