Add track inventory field to inventory section
woocommerce/woocommerce pull request #37585
Opened 2023-04-05 20:28 UTC by mdperez86

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/37400

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Got to `/wp-admin/tools.php?page=woocommerce-admin-test-helper`
2. Under Features tab make sure to enable `block-editor-feature-enabled`
3. Then visit `/wp-admin/admin.php?page=wc-admin&path=/add-product`
4. Under the Inventory tab in the track inventory fields should be shown
5. Track stock quantity for this product should be visible in the inventory section
6. When enabled, the Available Quantity field should be present

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/13334210/230203135-249e81b0-eaa1-4c21-84cf-253f8c67563d.png">

2023-04-10 22:41 UTC, joelclimbsthings commented on packages/js/product-editor/src/blocks/track-inventory/block.json
> +		"multiple": true,
This likely doesn't actually need `multiple` flagged as true, I believe?

2023-04-10 22:56 UTC, joelclimbsthings requested changes
Great job @mdperez86 ! I had a couple minor comments. We're also going to want this to be embedded inside the inventory section block that is added in [this PR](https://github.com/woocommerce/woocommerce/pull/37623), but if we want to merge this first I don't mind inserting it there.

2023-04-10 22:56 UTC, joelclimbsthings commented on packages/js/product-editor/src/blocks/track-inventory/block.json
> +		"multiple": true,
This likely doesn't actually need multiple flagged as true, I believe?

2023-04-10 22:56 UTC, joelclimbsthings commented on packages/js/product-editor/src/blocks/track-inventory/editor.scss
> +.wp-block-woocommerce-product-track-inventory-fields {
Is there a reason we're naming some of these `editor.scss` and others `style.scss`, or should all of them be `editor.scss` now?

2023-04-10 22:56 UTC, joelclimbsthings commented on packages/js/product-editor/src/blocks/track-inventory/edit.tsx
> +	const isStockQuantityValid = useValidation(
Have you already modified `useValidation()` like you mentioned in the call last week? Otherwise these will just have to be updated again, right?

2023-04-10 22:56 UTC, joelclimbsthings commented on packages/js/product-editor/src/blocks/track-inventory/edit.tsx
> +				<div className="wp-block-columns">
It looks like these classes just narrow the size of the field, is this the method we're using for that across the editor?

2023-04-11 13:58 UTC, mdperez86 commented on packages/js/product-editor/src/blocks/track-inventory/editor.scss
> +.wp-block-woocommerce-product-track-inventory-fields {
Well I just copied the name from a block made by @joshuatf. I have no idea why and no opinion on this.

2023-04-11 14:13 UTC, mdperez86 commented on packages/js/product-editor/src/blocks/track-inventory/edit.tsx
> +	const isStockQuantityValid = useValidation(
Nope I haven't worked in the validations stuff yet cause I started to work in this issue before.

> Otherwise these will just have to be updated again, right?

It's true. I'll do it anyway once I implement the validation update.

2023-04-11 14:16 UTC, mdperez86 commented on packages/js/product-editor/src/blocks/track-inventory/edit.tsx
> +				<div className="wp-block-columns">
I's the way the `core/columns` block manage the size so I just reuse the same logic without using the block itself.

Do you have any other suggestion/idea for this?

2023-04-11 14:18 UTC, mdperez86 commented on packages/js/product-editor/src/blocks/track-inventory/block.json
> +		"multiple": true,
Yes, maybe not.

2023-04-11 14:21 UTC, mdperez86 commented on packages/js/product-editor/src/blocks/track-inventory/block.json
> +		"multiple": true,
done -> https://github.com/woocommerce/woocommerce/pull/37585/commits/ef9e6ba71cf488240e9aecafa16e4932da4dcd53

2023-04-11 18:51 UTC, joelclimbsthings approved these changes
Thanks @mdperez86 ! Approving with one minor comment, and I'd like to get this merged so I can integrate it into my other PRs.

2023-04-11 18:51 UTC, joelclimbsthings commented on packages/js/product-editor/src/blocks/track-inventory/edit.tsx
> +				<div className="wp-block-columns">
It feels a bit "heavy" to have to add two containers for this use case. We could always use some simple styles of some kind, although to don't feel strongly about it and we can optimize this another time.

2023-04-11 18:52 UTC, merged