Add table name methods to OrderUtil
woocommerce/woocommerce pull request #37624
Opened 2023-04-08 00:45 UTC by coreymckrill

### Changes proposed in this Pull Request:

Adds methods to determine the names of the database tables currently being used for orders and order meta, without needing to make a separate check first to see if HPOS is enabled and in use. This also allows devs to get the table names dynamically instead of having to either hardcode them or call the `OrdersTableDataStore` class directly, which is discouraged since it's in the `Internal` namespace. 

### How to test the changes in this Pull Request:

One way to test this is with wp-cli, by opening an interactive shell to call the new methods directly. Note that you'll have to close the shell and re-open it after you change the state of HPOS.

1. With HPOS disabled, try using the shell to run the two new methods:
    ```
    wp shell
    wp> \Automattic\WooCommerce\Utilities\OrderUtil::get_table_for_orders()
    => string(8) "wp_posts"
    wp> \Automattic\WooCommerce\Utilities\OrderUtil::get_table_for_order_meta()
    => string(11) "wp_postmeta"
    ```
2. Now [enable HPOS](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#easy-way) and run the commands again:
    ```
    wp shell
    wp> \Automattic\WooCommerce\Utilities\OrderUtil::get_table_for_orders()
    => string(8) "wp_wc_orders"
    wp> \Automattic\WooCommerce\Utilities\OrderUtil::get_table_for_order_meta()
    => string(11) "wp_wc_orders_meta"
    ```

2023-04-12 12:12 UTC, vedanshujain requested changes
Requesting a placement change.

2023-04-12 12:12 UTC, vedanshujain commented on plugins/woocommerce/src/Utilities/OrderUtil.php
> +		if ( self::custom_orders_table_usage_is_enabled() ) {
So instead of static methods, we are adding any new utils as a non-static method in a separate Util class, and for convenience to users, we provide a static proxy for them here (see other methods). This way, we can mock these methods if we want to in our tests using the DI container.  You would want to refactor these to follow the same pattern, but otherwise looks good.

2023-04-12 21:25 UTC, coreymckrill commented on plugins/woocommerce/src/Utilities/OrderUtil.php
> +		if ( self::custom_orders_table_usage_is_enabled() ) {
Ah makes sense. Updated in b2e96aa

2023-04-14 09:33 UTC, vedanshujain approved these changes
LGTM! Triggering the e2e test again, as the failure seems unrelated.

2023-04-17 14:35 UTC, merged