CSS3 transitions for all fade animations
woocommerce/woocommerce pull request #37692
Opened 2023-04-12 21:19 UTC by apenchev

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #37691.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add this custom code to your theme's functions.php:
```
function carousel_options( $options ) {
	return array_merge(
		$options,
		array(
			'animation' => 'fade',
			'animationSpeed' => 2600,
			'fadeFirstSlide' => true,
			'easing' => 'easeInOutExpo',
			'smoothHeight' => false,
		)
	);
}
add_filter( 'woocommerce_single_product_carousel_options', 'carousel_options' );
```
2. Go to a Single Product Page.
3. Check that the first gallery image DOES not fade on page load
4. Confirm that switching between gallery images happens with a fade animation that takes about 2.6s.

2023-05-03 11:01 UTC, apenchev commented
@vedanshujain Would you be able to take a look?

2023-05-29 12:03 UTC, apenchev commented
:/

2023-06-14 19:19 UTC, apenchev commented
> @vedanshujain Would you be able to take a look?

2023-09-28 08:45 UTC, Konamiman approved these changes

2023-09-28 08:46 UTC, Konamiman commented
Testing works as expected, but I'm requesting analysis since I'm not really expert in JavaScript, thanks.

2023-09-28 09:30 UTC, alopezari commented
Thanks @Konamiman!

Will make sure to test this thoroughly once it gets included in the next release package 👍

2023-10-05 14:44 UTC, gigitux reviewed
Thanks for working on this! 

I've thoroughly tested the pull request and it looks good to me. However, my primary concern is to ensure that this PR won't cause any regressions or disrupt existing plugins or themes. I've pinpointed a specific concern with line 728, and I'd like to hear your insights before granting my approval.

2023-10-05 14:44 UTC, gigitux commented on plugins/woocommerce/client/legacy/js/flexslider/jquery.flexslider.js
> +            slider.slides.eq(slider.currentSlide).off("transitionend");
Is there a reason for this change? Could it be an issue for "extensions" that add a handler on the transitionend?

2023-10-28 12:56 UTC, apenchev commented on plugins/woocommerce/client/legacy/js/flexslider/jquery.flexslider.js
> +            slider.slides.eq(slider.currentSlide).off("transitionend");
Thanks for testing! Old line 725 used to call `jQuery.animate()` and then pass `slider.wrapup` as [the `complete` callback. param](https://api.jquery.com/animate/#animate-properties-duration-easing-complete-complete). In order to replicate [the `complete` callback param](https://api.jquery.com/animate/#animate-properties-duration-easing-complete-complete) from jQuery, we now call `slider.wrapup` during the CSS `transitionend` event on new line 729.

Theoretically, there might be existing plugins that subscribe to the `transitionend` CSS event on slides. Such a plugin would rely on touch-device-exclusive behaviour (remember, before this PR, CSS transitions are ONLY used inside `if (touch) { }`. If this PR were to be accepted, those plugins would now have their `slider.slides` `transitionend` callbacks also triggered on touch-enabled devices as well. Seems unlikely to me, but it is something to consider.

2023-10-30 09:29 UTC, gigitux commented on plugins/woocommerce/client/legacy/js/flexslider/jquery.flexslider.js
> +            slider.slides.eq(slider.currentSlide).off("transitionend");
Hi, @apenchev - thanks for the explanation. Just to be sure. Given this:

> If there are existing plugins subscribing to transitionend on slider.slides, they are doing it knowing that the subscription would only work on touch-enabled devices (remember, before this PR, CSS transitions are ONLY used inside if (touch) { })

> inside of if (!touch) { } we remove existing transitionend subscriptions before adding our own transitionend subscription

It means that this PR doesn't introduce any potential breaking change. Right?

2023-10-30 15:57 UTC, apenchev commented on plugins/woocommerce/client/legacy/js/flexslider/jquery.flexslider.js
> +            slider.slides.eq(slider.currentSlide).off("transitionend");
Unfortunately, the PR does introduce a potential breaking change. My explaination was not correct, as I assumed that we do a .transitionend cleanup inside of `if (!touch) { }`, but we don't clean up everything. I will try and send a small fix that attempts to do a full .transitionend cleanup inside of `if (!touch) { }`.

2023-10-30 16:14 UTC, apenchev commented on plugins/woocommerce/client/legacy/js/flexslider/jquery.flexslider.js
> +            slider.slides.eq(slider.currentSlide).off("transitionend");
I've pushed the commit with the proper transitionend cleanup.

2023-11-14 08:33 UTC, gigitux requested changes
Hi @apenchev,
Sorry for the late answer!
Thanks for your work in addressing the feedback and improving the code to avoid any potential breaking changes.

I noticed that with the latest changes, the thumbnails aren't visible anymore:


https://github.com/woocommerce/woocommerce/assets/4463174/f399e673-6238-4b5f-8df6-b52b2d81e98a

Can you check and see if you are able to replicate it?

2023-11-23 15:48 UTC, apenchev commented
> 'animationSpeed' => 1600,

I can't reproduce it, looks good on my end. :/ I'm using the StoreFront default theme, WooCommerce status is:

WooCommerce: 8.3.1
WooCommerce REST API: 8.3.1
WooCommerce Blocks package: 11.4.9
Action Scheduler package: 3.6.4
WordPress: 6.4.1

2023-11-23 15:55 UTC, apenchev commented
> Hi @apenchev, Sorry for the late answer! Thanks for your work in addressing the feedback and improving the code to avoid any potential breaking changes.
> 
> I noticed that with the latest changes, the thumbnails aren't visible anymore:
> 
>  Screen.Capture.Nov.14.mov 
> Can you check and see if you are able to replicate it?

Yes, the bug happens on the Twenty Twenty-Four theme when you set the animation to 'fade' whether you're using this PR or not. ;D I'm using the StoreFront theme for testing so I didn't see this bug.

In conculustion, this PR doesn't add this bug, I seem to get it even on a clean install simply by adding:


```
function carousel_options( $options ) {
	return array_merge(
		$options,
		array( 'animation' => 'fade' )
	);
}
add_filter( 'woocommerce_single_product_carousel_options', 'carousel_options' ); 
```

2023-12-05 15:15 UTC, apenchev commented
@gigitux I've greatly simplified the code in the PR and re-tested it. It still cleans up all `transitionend` subscriptions inside `if (!touch) { }` in order to make sure that we don't introduce regressions, as we discussed.

2023-12-06 08:36 UTC, gigitux reviewed
Thanks for your effort on this PR! It is LGTM and it is ready to be shipped. Before approving the PR, can you rebase it with trunk?

2023-12-06 14:53 UTC, apenchev commented
trunk merged.

2023-12-06 16:02 UTC, gigitux approved these changes
Thanks again for your effort! I'll merge the PR once all CI checks pass.

2023-12-06 16:44 UTC, merged