Move tabs to header and adjust title position
woocommerce/woocommerce pull request #37696
Opened 2023-04-13 00:27 UTC by joshuatf

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Moves the tabs to the header and adjusts the title positioning.

<img width="538" alt="Screen Shot 2023-04-12 at 5 20 51 PM" src="https://user-images.githubusercontent.com/10561050/231614531-7bb67262-bf1f-4a60-a33c-554af173072a.png">
<img width="908" alt="Screen Shot 2023-04-12 at 5 14 48 PM" src="https://user-images.githubusercontent.com/10561050/231614534-33fc986a-9edf-43e2-91ae-9512a9b2cbe8.png">

Closes #37686  .

### How to test the changes in this Pull Request:

1. Got to `/wp-admin/tools.php?page=woocommerce-admin-test-helper`
2. Under the Features tab make sure to enable `product-block-editor`
3. Visit `/wp-admin/admin.php?page=wc-admin&path=/add-product`
4. Check that the tabs now appear in the header
5. Click on various tabs to make sure they work as expected
6. Check that the title is centered in the header
7. Narrow the viewport and check that the title is left aligned (note that the buttons may need to be grouped on mobile to improve this experience cc @jarekmorawski )

2023-04-13 12:51 UTC, mdperez86 requested changes
Maybe this is something not covered yet from the design point of view but when the name of the product is too long something like this happened.
 
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/13334210/231763389-ffa8e66e-48de-4519-8607-259b92368aa5.png">

Just imagine in lower screens, but I think this is something is about to be covered in the future.

2023-04-13 12:57 UTC, jarekmorawski commented
> (note that the buttons may need to be grouped on mobile to improve this experience cc @jarekmorawski )

Can we hide the title/product name on mobile and use that space to show the buttons?

<img width="510" alt="image" src="https://user-images.githubusercontent.com/79307566/231765510-9e866de0-3fc0-404c-997b-109e8f04bbee.png">

> Maybe this is something not covered yet from the design point of view but when the name of the product is too long something like this happened.

Ha ha. Good call! I think we can truncate the title if it's longer than 75 characters and/or extends beyond a single line.

2023-04-14 17:35 UTC, joshuatf commented
Done and done. cc @mdperez86 @jarekmorawski 
<img width="458" alt="Screen Shot 2023-04-14 at 10 34 40 AM" src="https://user-images.githubusercontent.com/10561050/232117205-2d7b4276-d75d-4a30-a8d7-7895b2183625.png">
<img width="1217" alt="Screen Shot 2023-04-14 at 10 29 42 AM" src="https://user-images.githubusercontent.com/10561050/232117207-fd3c48f8-896e-41a8-84f5-b0b9ff5be456.png">

2023-04-17 15:23 UTC, mdperez86 requested changes
Thanks for addressing this so far @joshuatf ! I left another comment regarding a11y.

2023-04-17 15:23 UTC, mdperez86 commented on packages/js/product-editor/src/utils/get-header-title.ts
> +export const getTruncatedTitle = ( title: string ) => {
One reason why I don't like this approach is because of a11y. If we do it this way we also truncate screen readers to read the whole product title as the page h1 element will only contains the truncated string. Because of that I prefer using the css ellipsis feat than the js one. But if you want to continue with this approach then an aria-label or similar a11y enhancement should be applied to the h1 element or whatever the element that contains the truncated string.

```jsx
<h1 aria-label="Full name">Truncated name...</h1>
```

2023-04-17 17:19 UTC, joshuatf commented on packages/js/product-editor/src/utils/get-header-title.ts
> +export const getTruncatedTitle = ( title: string ) => {
Good callout, @mdperez86!  Agreed that CSS is better for several reasons.

This does mean that we cannot truncate reliably using characters (support for this CSS property exists, but is a little wonky in IE), but can easily truncate based on width.  I set this to a max of `500px` which is roughly the 75 character limit we had before and I think might work better than a character limit given different font sets can vary in width.  Does that work okay @jarekmorawski?

2023-04-17 19:00 UTC, mdperez86 approved these changes
Agreed also about using the width prop to truncate the string. In future we might want to be able to read the whole product name when the visual one is been truncated like using the title prop or a tooltip/popover on mouse over for example.
Good job here @joshuatf !!!

2023-04-17 22:39 UTC, merged