Dev/37219 add hook to remove order items
woocommerce/woocommerce pull request #37822
Opened 2023-04-19 09:16 UTC by ashwinparthasarathi

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Added action hooks to the WC_Abstract_Order::remove_order_items() to facilitate the tracking of the removal of products from an order for failed payments & order reuse.

Closes #37219

2023-04-19 09:50 UTC, peterfabian requested changes
Thanks for working on this PR! I think in general it looks good, I just think we should be good citizens and add a bit of documentation. 

As for testing steps, I think it would be cool to think about a minimum example where you'd use the hook. Maybe include a small snippet (to be added e.g. via https://wordpress.org/plugins/code-snippets/) or you can create a tiny single-purpose plugin to test it, describe how you used it, and how to check the action ran successfully. Hope that makes sense.

2023-04-19 09:50 UTC, peterfabian commented on plugins/woocommerce/includes/abstracts/abstract-wc-order.php
> +		do_action( 'woocommerce_remove_order_items', $this, $type );
Could you please add a docblock to the action? Please see e.g. this action for inspiration: https://github.com/woocommerce/woocommerce/blob/7.6.0/plugins/woocommerce/includes/class-wc-ajax.php#L1360-L1370

It might also be good to quickly mention what the difference is between `woocommerce_remove_order_items` and `woocommerce_delete_order_items`, as their name doesn't reveal the difference.

2023-04-19 09:50 UTC, peterfabian commented on plugins/woocommerce/includes/abstracts/abstract-wc-order.php
> +		do_action( 'woocommerce_removed_order_items', $this, $type );
Same here please.

2023-04-19 09:51 UTC, peterfabian commented
cc @melek if you folks would like to test it out in the context of Jetpack.

2023-04-19 10:39 UTC, ashwinparthasarathi commented on plugins/woocommerce/includes/abstracts/abstract-wc-order.php
> +		do_action( 'woocommerce_remove_order_items', $this, $type );
Updated docblock for the hook

2023-04-19 10:39 UTC, ashwinparthasarathi commented on plugins/woocommerce/includes/abstracts/abstract-wc-order.php
> +		do_action( 'woocommerce_removed_order_items', $this, $type );
Updated docblock for the hook

2023-04-19 11:49 UTC, ashwinparthasarathi commented
@peterfabian I have made the necessary changes for documentation in the code with Docblocks and in the PR testing instructions.

2023-04-19 13:20 UTC, peterfabian commented on plugins/woocommerce/includes/abstracts/abstract-wc-order.php
> +		do_action( 'woocommerce_remove_order_items', $this, $type );
Looks good, thanks for updating.

2023-04-19 19:17 UTC, jorgeatorres commented
Regarding the testing instructions on this PR, I've noticed a few things:

- We might need to change the `add_action()` calls in the "test plugin": the second argument to `add_action()` is actually the priority not the # of args, so that should be changed from `add_action( <hook>, 2 )` to `add_action( <hook>, 10, 2 )` for example.
- Property `data_store` in $order (first callback) is supposed to be protected, so it'd be better to use a different method. Maybe `$order->get_item_type( $type )` makes more sense in this context?
- I tested with the Stripe gateway by using a test card [that produces a decline](https://stripe.com/docs/testing#declined-payments). Under this scenario the changes worked fine.
- As for 'triggering' the code with the StoreAPI, after some checks I believe all we have to do is "perform" the checkout and it'll automatically call the relevant methods (and thus the new hooks here). For example, the following should do the trick:
   1. Create/enable the test plugin.
   2. Take note of a product ID that is available.
   3. Generate a nonce for use with the StoreAPI: to do so, in a WP-CLI shell (`wp shell`) run `wp_create_nonce( 'wc_store_api' )` and take note of the resulting nonce.
   4. Add the item from step 2 to the cart (with the nonce from step 3):
   ```curl --header "Nonce: <NONCE>" --request POST https://example.test/wp-json/wc/store/v1/cart/add-item?id=<PRODUCT ID>&quantity=1```
   5. Initiate the checkout:
   ```curl --header "Nonce: <NONCE>" --request GET https://example.test/wp-json/wc/store/v1/checkout```
   6. The above creates a draft order. Let's try to "pay":
   ```curl --header "Nonce: <NONCE>" --request POST https://example.test/wp-json/wc/store/v1/checkout```
   7. The above will fail (as it doesn't include billing/payment information) but it should trigger the code in the test plugin.

2023-04-21 11:03 UTC, peterfabian commented
Thanks @jorgeatorres ! @ashwinparthasarathi do you plan to update the PR as suggested by @jorgeatorres ?

2023-04-24 08:11 UTC, ashwinparthasarathi commented
Yes, definitely @peterfabian. Thank you @jorgeatorres for your input.

2023-05-15 12:00 UTC, peterfabian commented
Just noting here that if we want to get this merged before the code freeze for WC 7.8, we need to get this PR ready this week. I think we just need to improve the testing instructions and we should be good to go :)

2023-05-19 10:09 UTC, peterfabian commented
Updated the testing instructions based on @jorgeatorres comment. Hope you don't mind @ashwinparthasarathi 🙌

2023-05-19 10:09 UTC, peterfabian approved these changes
Looks good, thanks for the contribution!

2023-05-19 10:10 UTC, merged