Enhancement: Add order note to display held stock inventory. #29132
woocommerce/woocommerce pull request #37833
Opened 2023-04-19 12:33 UTC by Abdalsalaam

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #29132 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new order without completing the payment process or with "Direct bank transfer" payment method.
2. Check the order notes.
3.  <img width="301" alt="Screenshot 2023-04-19 at 2 32 16 PM" src="https://user-images.githubusercontent.com/19236737/233075997-5fdfa23f-339c-40f5-b27f-dee3518fbb42.png">

2023-04-19 22:08 UTC, jorgeatorres requested changes, later dismissed
Hi @Abdalsalaam!

Thank you for your contribution and for participating on this special day 🥇. Overall, the code looks good to me and works correctly. I left a couple of tiny suggestions, but nothing huge.

While testing, however, I noticed that depending on the product names involved, the message can look a bit confusing, especially when variable products are added to the mix, as those can output commas (`,`) as part of their names. For example:

<img width="281" alt="Screenshot 2023-04-19 at 18 59 29" src="https://user-images.githubusercontent.com/184724/233209887-d304ab39-c6af-4bad-b6c7-c76f30d42038.png">

<img width="282" alt="Screenshot 2023-04-19 at 18 46 43" src="https://user-images.githubusercontent.com/184724/233210007-28ca4093-9bef-4528-94d4-6416eef5eea3.png">

The use of colons to indicate IDs might also be confusing given colons are also used before the product names list.

I was wondering if, for simplicity's sake, we should only list the product IDs for which we're holding stock (no names) or just a generic message with no specific IDs or names.

@vedanshujain: as the author of the original issue, did you have any specific formatting in mind? Do you think a message with just product IDs or a generic message work here?

If not, we would need to be a bit more clever on how to separate the product names to prevent any confusion (or notes that are too large).

@Abdalsalaam: code-wise this looks good to me (with the few exceptions mentioned in the review), but I'd like to hear from @vedanshujain first. If you have some ideas on how to change the presentation to make things clearer, by all means please share those too!

Once again, thanks for all your hard work on this.

2023-04-19 22:08 UTC, jorgeatorres commented on plugins/woocommerce/src/Checkout/Helpers/ReserveStock.php
> +			$order->add_order_note( sprintf( __( 'Stock is held for %s minutes for payment:', 'woocommerce' ), $minutes ) . ' ' . implode( ', ', $order_notes ) );
Just noting that translatable strings require a comment in the line above that indicates to translators what the placeholders mean. See https://codex.wordpress.org/I18n_for_WordPress_Developers#Descriptions.

In this case, it could be something like

``// translators: %s is a time in minutes``

2023-04-19 22:08 UTC, jorgeatorres commented on plugins/woocommerce/src/Checkout/Helpers/ReserveStock.php
> +		if ( ! empty( $rows ) ) {
For consistency, I think it would be best to check here the same variable that we're going to add in the notes (that is `$order_notes`) instead of `$rows`.
I don't see an scenario where `$rows` and `$order_notes` could get out of sync.

2023-04-19 22:08 UTC, jorgeatorres commented on plugins/woocommerce/src/Checkout/Helpers/ReserveStock.php
> +		$order_notes = array();
`$order_notes` seems a bit generic for this use case. Maybe we can rename this variable `$held_stock_product_names` or something like that. This is definitely not a blocker, just thought I'd mention it.

2023-04-19 23:08 UTC, Abdalsalaam commented
Thank you @jorgeatorres ! I did the changes, for the note I think its good to have the product name in the note, I suggest to use **/** instead of commas to separate products, also we can use **X**  for the quantity, it will be like this :

Stock held for 10080 minutes for payment: Product (ID: #6293), Color: Green, Attribute: Red x 1; Import Product - Variable - Yellow (ID: #5953) x 1"

2023-04-25 17:52 UTC, jorgeatorres commented
Hi @Abdalsalaam!

I particularly like the last idea, with the dash/bullet list. I think that looks much clearer.
Maybe we can rephrase the message a little so that it's clear that the list of items/products comes after. Something like "Stock hold of X minutes applied to: <list of items/quantities>".
If you can think of a different better phrasing, feel free to propose that instead.

I also think we should limit the number of products that are listed. If the order contains tons of items, the note could end up being too large. Maybe we should only apply it to the first 5 products and if there are more, we just add something like "- ... and N more items." That's obviously less useful, but also less noisy. What are your thoughts on that? Definitely not a blocker, but worth discussing now that we're working on this.

Looking forward to hearing back from you!

2023-04-26 00:28 UTC, Abdalsalaam commented
> 

I like your Idea, i think we should it it now yes. let me an edit for it.

2023-04-26 22:10 UTC, Abdalsalaam commented
@jorgeatorres 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/19236737/234714139-c8e22988-cd29-4895-8e72-bd0b8f9b0a3d.png">

What do you think?

2023-05-03 21:34 UTC, jorgeatorres commented
Hi @Abdalsalaam,

Thanks for making the changes. I think it looks really great. I'll go through a re-review as soon as possible!

2023-05-08 22:45 UTC, jorgeatorres approved these changes
@Abdalsalaam:

Thanks again for your contribution and all the work you put into this 🥇. I pushed a couple of commits with some small adjustments to the code (we were missing a couple of translatable strings, etc.) but overall, this works and looks great.

As such, I'm approving now. It's been a pleasure working with you in this PR and hope we'll be seeing more contributions from you, not only on Contributor Day 😸 

Thanks!

2023-05-08 22:46 UTC, merged

2023-05-24 02:16 UTC, rodelgc commented
### Steps to test

1. Create a new order with less than 5 products, without completing the payment process or with "Direct bank transfer" payment method.
2. Verify that an order note that says "Stock hold of 5 minutes is applied to:" and a list of products in the order were shown.
3. Repeat the steps above with more than 5 products.
4. Verify that the order note now says "...and X more items" after the 5th item. See screenshot in https://github.com/woocommerce/woocommerce/pull/37833#issuecomment-1524105782