Add pattern for thousand and decimal separator in Woo settings
woocommerce/woocommerce pull request #37838
Opened 2023-04-19 13:22 UTC by wputasic

fix: Incorporate pattern for thousand and decimal separator to restrict input to only comma and period as valid values.

This fix is related to:  https://github.com/woocommerce/woocommerce/issues/34373

2023-04-19 14:31 UTC, opr requested changes
Hey @wputasic thanks for working on this! I tested it and it works well, but I wonder if we should allow users to specify a space as a separator too, and maybe even apostrophe?

https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use shows some examples of different formats, and mentions that some countries do use apostrophes, or even middle dots.

What do you think about being less explicit, and instead disallowing alphanumerical characters, leaving the rest free to add? I'm not sure what the _best_ solution is, but I would love to hear your thoughts, and anyone else's!

Also, for your testing instructions, please could you remove the "old" behaviour from the steps and just describe the new, intended behaviour?

We also need a changelog entry for this PR.

You could generate this by `pnpm --filter=woocommerce changelog add` and following the prompts.

2023-04-19 15:03 UTC, wputasic commented
Hey @opr I agree with the it should be less explicit, testing the new code now, that will only disallow numbers and letters. Regarding the description I remove old behaviour, and I will add changelog.

2023-04-19 15:41 UTC, wputasic commented
@opr new version that only disallow numbers and letters, also change log added

2023-04-19 15:56 UTC, opr requested changes
Hey @wputasic! Thanks for adding the changelog.

The new regex looks a little complex, would you mind breaking it down for me?

What do you think of this approach instead? `[^a-zA-Z\d]{1}` would disallow any alphanumeric character, and limit the input to 1 character.

2023-04-19 16:13 UTC, wputasic commented
Hey @opr 
Breaking it down:
    ^ - Start of the string
    [^a-zA-Z0-9]* - Matches any number of characters that are not alphanumeric (letters or digits)
    ([ ]|[^a-zA-Z0-9]) - Matches either a single space or a single non-alphanumeric character
    [^a-zA-Z0-9]* - Matches any number of characters that are not alphanumeric (letters or digits)
    $ - End of the string
    
So, the main difference between these two regular expressions is what they are trying to match. Your pattern matches any single character that is not a word character or a digit, whereas my pattern matches a string that contains only one special character, which can be either a space or any other non-alphanumeric character, surrounded by zero or more non-alphanumeric characters. My mistake is not to limit it to 1 character. 

I also agree that your is less complex.

2023-04-20 10:56 UTC, Konamiman requested changes
Hi @wputasic, the problem with the `A-Za-z` pattern is that it'll still allow non-ASCII letters such as `á` or `あ`. If the goal is to disallow any kind of letters and digits the pattern to use is `[^\p{L}\p{Nl}\p{Nd}]`, which disallows [the unicode categories for letters and numbers](https://www.regular-expressions.info/posixbrackets.html). Combined with a more descriptive error message it could be something like this:

```php
'custom_attributes' => array(
	'pattern'  => '[^\p{L}\p{Nl}\p{Nd}]',
	'title' => __( 'Use a character that is not a letter or a digit.', 'woocommerce')
)
```

2023-04-20 14:10 UTC, wputasic commented
@Konamiman thanks for heads up, I will test and push the change

2023-05-15 11:55 UTC, peterfabian commented
Hey @wputasic 👋 

Do you reckon you will be able to work on the PR this week? Just trying to understand which PRs are potentially going to make it before the code freeze for WC 7.8 that's happening next Monday. Thanks! 🙌

2025-06-10 00:39 UTC, closed without merging