Update= disable drag and drop within images block
woocommerce/woocommerce pull request #38045
Opened 2023-04-28 13:52 UTC by louwie17

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This adds support to `ImageGallery` component to disable dragging, by the new `allowDragging` prop (defaults to `true`).
As a second change this disables dragging within the product images block.

Closes #37955 

![Screenshot 2023-04-28 at 3 51 51 PM](https://user-images.githubusercontent.com/2240960/235166260-14c25b99-9945-4193-8718-4f90dd410841.png)

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Build and load this branch and enable the `new-product-management-experience` feature flag ( the non-block editor )
2. Go to **Products > Add New** and scroll down to images and add some images.
3. Now re-arrange them by dragging the images around, this should still work as expected.
4. Now enable the block based editor, with the `product-block-editor` feature flag
5. Go to **Products > Add New** and scroll down to images and add some images.
6. Try dragging images around, this should **not** be possible, the drag handle should also not be visible within the image toolbar.
7. Click on the arrows within the image toolbar, this should still move images around successfully.

2023-05-02 21:53 UTC, joelclimbsthings requested changes
Nice work @louwie17 ! The code looks good at first glance, although I'm encountering an error. If you:
- Replace an image
- Immediately click the arrow to attempt to move that image after it's replaced

I'd guess that the issue actually lies within the block itself, and was probably preexisting to this PR. Let me know if you'd rather address in a follow-up.

![image](https://user-images.githubusercontent.com/444632/235792913-4caddfe0-3b8f-4a7a-b604-11af93f18457.png)

2023-05-04 11:42 UTC, louwie17 commented
Thanks for the review @joelclimbsthings, it turned out to be an issue with the `onReplace` method, where its changes were not being reflected as we were altering the same array.
I assume this happened because of some logic within React or the data store that check if the array reference changed, and only updates the store if it changed. Directly altering the array location of a single item doesn't change this.
I fixed it in this commit: https://github.com/woocommerce/woocommerce/pull/38045/commits/6739f4aa2cf8667449735b60232607e928be1693 where I mapped it to a new array.

Should be ready for a re-review.

2023-05-04 19:27 UTC, joelclimbsthings submitted a review, later dismissed
Nice job @louwie17 ! Working well 🚢 

Edit: Had to push a quick fix for a linting error in https://github.com/woocommerce/woocommerce/commit/3f424fe6f447bc5c6b2869d5b78b506e9912f038. Wanted to make sure it was mergable when you return.

2023-05-04 19:44 UTC, joelclimbsthings approved these changes

2023-05-05 07:45 UTC, merged