Dev/38122 remove separator between buttons and empty state screen
woocommerce/woocommerce pull request #38123
Opened 2023-05-04 18:40 UTC by octaedro

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

2023-05-05 19:56 UTC, mattsherman requested changes
The separator is not shown when the variations list is shown.

<img width="809" alt="Screenshot 2023-05-05 at 15 48 25" src="https://user-images.githubusercontent.com/2098816/236557162-d5123b71-4768-4d0f-a9f4-a089c338d79c.png">

2023-05-05 19:56 UTC, mattsherman commented on plugins/woocommerce/client/legacy/css/admin.scss
> +	&:not(#variable_product_options_inner) {
Haven't spent much time looking into what the selector should be, but this isn't right. 

`#variable_product_options_inner` is a child of `.wc-metaboxes-wrapper`

2023-05-08 18:53 UTC, octaedro commented
Thank you @mattsherman for your comments.
I just fixed the bug you mentioned, could you take another look at this PR?

2023-05-08 18:53 UTC, octaedro commented
Thank you @mattsherman for your comments.
I just fixed the bug you mentioned, could you take another look at this PR?

2023-05-08 19:46 UTC, mattsherman approved these changes
Works as expected. Nice job. :shipit:

2023-05-09 15:43 UTC, merged