Add single selection mode to SelectTree
woocommerce/woocommerce pull request #38140
Opened 2023-05-05 13:23 UTC by nathanss

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Add single selection mode to SelectTree.

https://user-images.githubusercontent.com/13437655/236469085-deeb839b-0507-461b-a3ae-4884ff33a5b0.mov

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Launch storybook.
2. Go to http://localhost:6007/?path=/story/woocommerce-admin-experimental-selecttreecontrol--single-select-tree
3. Test functionality with mouse
4. Test functionality with keyboard

2023-05-08 19:36 UTC, mattsherman requested changes
Overall, works as expected. Nice job.

There is a lot of use of `any` in the code. This should be avoided as it really weakens our type-checking.

2023-05-08 19:36 UTC, mattsherman commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
Whoa, whoa, whoa... why are we disabling `@typescript-eslint/no-explicit-any` at the file level?! We shouldn't be doing this. It greatly diminishes the type checking.

2023-05-08 19:36 UTC, mattsherman commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
> +	const inputProps: any = {
We shouldn't use `any` -- use a specific type.

2023-05-08 19:36 UTC, mattsherman commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
> +		onBlur: ( event: any ) => {
We shouldn't use `any` -- use a specific type.

2023-05-08 19:36 UTC, mattsherman commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
> +		onKeyDown: ( event: any ) => {
We shouldn't use `any` -- use a specific type.

2023-05-08 19:36 UTC, mattsherman commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
> +		onChange: ( event: any ) =>
We shouldn't use `any` -- use a specific type.

2023-05-08 19:36 UTC, mattsherman commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
> +							onChange: ( event: any ) =>
We shouldn't use `any` -- use a specific type.

2023-05-08 19:36 UTC, mattsherman commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
> +					?.contains( event.relatedTarget )
You could extract this to a function and do something like `! isInsideDropdown( event.relatedTarget )`... if you did that, you don't even need the comment... the code self-documents.

2023-05-08 19:36 UTC, mattsherman requested changes
Overall, works as expected. Nice job.

There is a lot of use of `any` in the code. This should be avoided as it really weakens our type-checking.

2023-05-09 18:34 UTC, nathanss commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
My bad. This was by mistake, I disable it sometimes just to speed things up while I'm testing things, but it was never intended to reach production 😛 Thanks for catching it.

2023-05-09 21:04 UTC, joshuatf reviewed
Just a heads up that we're having a discussion around drop-down behavior tomorrow with @jarekmorawski.

I think we need to DRY up our use of `SelectTree` and `SelectControl` as there is a lot of duplication and fix divergence in behavior as best we can.  If you can attend @nathanss, your input would be valuable.

2023-05-10 00:06 UTC, mattsherman commented
@nathanss Can you please resolve the conflict in the following file before I re-review it?

- `packages/js/components/src/experimental-select-tree-control/select-tree.tsx`

2023-05-10 23:45 UTC, mattsherman approved these changes
Nice iteration on this, @nathanss. 🚢

2023-05-11 16:42 UTC, merged