Code Freeze CLI: Remove old version bump tool
woocommerce/woocommerce pull request #38182
Opened 2023-05-09 04:29 UTC by psealock

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Code freeze was the only place using the version bump tool. https://github.com/woocommerce/woocommerce/pull/38036 copied that code over to the new Code Freeze CLI in Monorepo Utils and https://github.com/woocommerce/woocommerce/pull/38067 implemented its usage in the code freeze action. This removed the only usage of the tool in the monorepo. This PR makes the final adjustment to remove unused code.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Confirm this code is no longer used anywhere

2023-05-09 20:05 UTC, ObliviousHarmony approved these changes

2023-05-09 20:06 UTC, ObliviousHarmony requested changes
It looks like the tool is also present in `pnpm-workspace.yaml`

2023-05-09 21:24 UTC, psealock commented
Ah right, thanks @ObliviousHarmony. Fixed in https://github.com/woocommerce/woocommerce/pull/38182/commits/c67d9ca22044b2a2b8b1ae3b0dc8389e9a7fafbc

2023-05-11 02:30 UTC, psealock commented
This is ready for another look @ObliviousHarmony 🙇🏽‍♂️

2023-05-11 16:23 UTC, ObliviousHarmony approved these changes

2023-05-11 21:15 UTC, merged