Remove Storefront Placement
woocommerce/woocommerce pull request #38198
Opened 2023-05-10 09:34 UTC by corsonr

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/Automattic/woocommerce.com/issues/16784

The goal of the PR is to remove this broken Storefront placement:

<img width="824" alt="image" src="https://github.com/corsonr/woocommerce/assets/1649788/ee551d8b-def2-47a0-8ca5-15a0af0deb32">

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to WP Admin > WooCommerce > Extensions
2. Click a category and scroll down to the bottom.
2. Confirm the storefront placement has gone

2023-11-17 12:13 UTC, andfinally requested changes
Thanks! The placement change looks good. We should add this to the test steps:

> This placement appears in the old version of the in-app marketplace. To view it, go to `WooCommerce > Settings > Advanced > Features`, uncheck the checkbox next to `New, faster way to find extensions and themes for your WooCommerce store`, and refresh.

How can we test the inbox notification change?

2023-11-17 12:13 UTC, andfinally commented on plugins/woocommerce/changelog/2023-05-11-08-37-39-697751
> +Significance: minor
We have two changelogs here. I would suggest we delete these, and just add one like this. If we don't want to include this with the published WooCommerce core changelog, just make the significance `patch`.

```
Significance: minor
Type: tweak
Comment: Remove in-app Storefront placement. Display remote inbox notification title when notification has no action.
```

2023-11-17 12:13 UTC, andfinally commented on packages/js/experimental/src/inbox-note/inbox-note.tsx
> +			return '<a href="#">' + note.title + '</a>';
The titles on all my inbox notifications are showing with markup because we're returning a string here instead of an element.

<img width="500" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1647564/a21f46aa-c732-4e76-a131-3c60e891099c">

Also, why do we need a link? Maybe we should do this.

```diff
Index: packages/js/experimental/src/inbox-note/inbox-note.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/js/experimental/src/inbox-note/inbox-note.tsx b/packages/js/experimental/src/inbox-note/inbox-note.tsx
--- a/packages/js/experimental/src/inbox-note/inbox-note.tsx	(revision 2b292e546f794563944c3ec17cfefda0213acaed)
+++ b/packages/js/experimental/src/inbox-note/inbox-note.tsx	(date 1700222954214)
@@ -146,7 +146,11 @@
 		const hasAction = note.has_actions;
 
 		if ( ! hasAction ) {
-			return '<a href="#">' + note.title + '</a>';
+			return (
+				<>
+					{ note.title }
+				</>
+			);
 		}
 
 		if ( note.actions && note.actions.length === 1 ) {
```

<img width="500" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1647564/4e6b7fa9-7752-4091-85d3-3cff99c3584d">

And... all my inbox notifications seem to lack `has_actions`, even though I can see buttons on them.

2024-04-30 11:12 UTC, andfinally commented
This PR looks a bit stale, should we close it? I'm no longer seeing the Storefront placement in the extensions browse page – if I remember correctly, we removed it from the new page.

2024-04-30 11:38 UTC, corsonr commented
@andfinally yes, I we can close it.

2024-05-01 09:14 UTC, mcliwanow reviewed
+1 for closing this one

2024-05-01 11:38 UTC, closed without merging