Change attributes of tracks event product_attributes_add
woocommerce/woocommerce pull request #38278
Opened 2023-05-12 14:20 UTC by nathanss

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The previous attributes of `product_attributes_add` were not working as expected, as tracks don't support objects or arrays. This improves the attributes.

An event with the same name is also called on the [Attributes page ](https://github.com/woocommerce/woocommerce/blob/ac78d3de2b58e04e63a79fc4714ed2bdcc7e754b/plugins/woocommerce-admin/client/wp-admin-scripts/attributes-tracking/index.js#L16-L23), but some attributes only make sense on the product page and some only on the attributes page. Please let me know if I should update this event somehow in order for it to work properly.

Also, I'm not sure if we should send 'null' as a value, or another 'nullish' value, like empty string. I had to handle that separately on 'used_for_variations_count' for non variable products because the checkbox is actually checked, but invisible.

Closes #38171 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to current product editor and create a new product.
2. Change to Variable product type.
3. Go to attributes tab.
4. Add a combination of Global attributes, local attributes, some with 'Visible on the product' page checked, and some with 'Used for variations' checked.
5. Click 'Save attributes'.
6. Verify that the tracks event `wcadmin_product_attributes_add` was fired with the expected parameters.
7. Create another product with 'Simple' product type.
8. Add a combination of Global attributes, local attributes, some with 'Visible on the product' page checked.
9. Click 'Save attributes'.
10. Verify that the tracks event `wcadmin_product_attributes_add` was fired with the expected parameters.

2023-05-15 22:15 UTC, mattsherman commented
> An event with the same name is also called on the [Attributes page ](https://github.com/woocommerce/woocommerce/blob/ac78d3de2b58e04e63a79fc4714ed2bdcc7e754b/plugins/woocommerce-admin/client/wp-admin-scripts/attributes-tracking/index.js#L16-L23), but some attributes only make sense on the product page and some only on the attributes page. Please let me know if I should update this event somehow in order for it to work properly.

I'm confused. Can you please tell me where in the UI this other attribute is supposed to be fired? I don't really understand what is meant by "product page" and "attributes page" in the above!

> Also, I'm not sure if we should send 'null' as a value, or another 'nullish' value, like empty string. I had to handle that separately on 'used_for_variations_count' for non variable products because the checkbox is actually checked, but invisible.

I think that we should send an empty string, though I'm not sure. I'd test with with sending null. If it results in the property either not being included at all or included with an empty string, I'd go with null.

2023-05-16 15:33 UTC, nathanss commented
> I'm confused. Can you please tell me where in the UI this other attribute is supposed to be fired? I don't really understand what is meant by "product page" and "attributes page" in the above!

I agree it's confusing, but this event is called both in the Products > Attributes page (global attributes) and in the product page. Some attributes only make sense in one page or the other. 

> I think that we should send an empty string, though I'm not sure. I'd test with with sending null. If it results in the property either not being included at all or included with an empty string, I'd go with null.

It seems there's no problem sending null, so I'm sending null values because I think that's what makes more sense, semantically.

2023-05-17 01:30 UTC, mattsherman requested changes
I did not test this yet, but I did take a look at the code and left some comments. I'll re-review and test once those changes are made!

2023-05-17 01:30 UTC, mattsherman commented on plugins/woocommerce-admin/client/wp-admin-scripts/attributes-tracking/index.js
> +		used_for_variations_count: null,
We should not add these properties here. They have absolutely nothing to do with this screen. Analysis can use the `page` property to determine whether to look for other properties. Otherwise, we will always have to remember to update this call as well whenever other properties are added on the product screen.

The larger issue though is that we really shouldn't be using the `product_attributes_add` event name in two different scenarios. This was a less-than-ideal design design in my opinion.

2023-05-17 01:30 UTC, mattsherman commented on plugins/woocommerce-admin/client/wp-admin-scripts/product-tracking/shared.ts
> +				slug: null,
These should be left off, as they have nothing to do with this screen.

2023-05-17 01:30 UTC, mattsherman commented on plugins/woocommerce-admin/client/wp-admin-scripts/product-tracking/shared.ts
> +						: null,
This should be pull out into it's own function.

2023-05-17 01:30 UTC, mattsherman commented on plugins/woocommerce-admin/client/wp-admin-scripts/product-tracking/shared.ts
> +						: null,
I feel like `0` is more semantic than `null` in this case.

Maybe we should have another property that tracks what type of product the attributes were being added to, though!

2023-05-17 01:35 UTC, mattsherman commented
> I agree it's confusing, but this event is called both in the Products > Attributes page (global attributes) and in the product page. Some attributes only make sense in one page or the other.

Ah, I see. I personally think we shouldn't be using the same Tracks event name for two different scenarios like this.

@pmcpinto @louwie17 Why was this done originally? It feels odd to overload a single Tracks event with two different scenarios like this. Does it make some analysis much easier? I would think we could compare two different Tracks events if we wanted to see the breakdown of global attributes vs local attribute creation -- I know we used to be able to in Tracks Trends at least.

2023-05-17 16:30 UTC, pmcpinto commented
Hey everyone, the initial idea was to have a single event, as at the fundamental level the user is doing the same action (creating an attribute) and to keep it aligned with some of the event tracking best practices: usually, the event should be focused on the "what happened" and the properties on the "how/where it happened". This case is tricky as different options are available depending on where the attribute is created. So I'm happy to revisit this and create separate events. Let me know what you think.

2023-05-17 18:04 UTC, nathanss commented
@pmcpinto Hey, I'm super in favour of having two different events. On top of the different attributes for each of them, it's also confusing that the one on the product page is called when "Save attributes" is called, while the one on the attributes page is called for every new attribute added. 

So maybe we can call the event on the product page `product_attributes_save` (the one this PR is changing) and keep the one on the attributes page with the same name. What do you think?

2023-05-18 15:41 UTC, pmcpinto commented
Sounds good to me. Thanks!

2023-05-19 14:55 UTC, mattsherman commented
> usually, the event should be focused on the "what happened" and the properties on the "how/where it happened".

@pmcpinto I definitely see your point. If these were the same user action, I'd agree. But, as we know, global attributes and custom attributes are really different beasts.

I also think our naming guidelines for Tracks events is at odds with this...

```
Event name is expected to be of the form:<source>_<context>_<optional subcontext>_<action>_<optional qualifier>
```

But, it does really depend on what we view as the `context`... is that the place in the UI, or the object (type) being acted upon. It definitely is subject to debate!

In this case I agree with Nathan's suggestion to have two separate events, but there could be situations where your original approach is best. As always, guidelines are just guidelines. 😄

2023-05-19 15:18 UTC, mattsherman approved these changes
Nice work on this, @nathanss ! :shipit:

2023-05-19 15:18 UTC, mattsherman commented on plugins/woocommerce-admin/client/wp-admin-scripts/product-tracking/shared.ts
> +				page: 'product',
We don't technically need this prop anymore, but we can keep it here for now, as it isn't causing any harm.

2023-05-19 15:44 UTC, merged

2023-05-22 09:34 UTC, pmcpinto commented
> In this case I agree with Nathan's suggestion to have two separate events, but there could be situations where your original approach is best. As always, guidelines are just guidelines. 😄

Yep, you're totally right 😄 . 2 events make more sense in this situation.