Fix double scrollbars on product editor page
woocommerce/woocommerce pull request #38281
Opened 2023-05-12 16:15 UTC by joshuatf

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes the double scrollbars in the page.  In order to do this, this PR does a few things:

* Refactors the `Layout` component to a functional component (to allow easier use of hooks)
* Creates a hook that helps create a slug from a route path and adds this class to the body to allow styling various elements on a page
* Styles the interface skeleton without fixing its position to the screen

Closes #38149 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to `/wp-admin/tools.php?page=woocommerce-admin-test-helper`
2. Under Features tab make sure to enable product-block-editor
3. Then visit `/wp-admin/admin.php?page=wc-admin&path=/add-product`
4. Reduce your viewport/browser height so you can scroll the page
5. Make sure that only one scrollbar is shown when scrolling the product editor
6. Narrow your viewport and make sure the header stays the correct width and location on various screen sizes (note that padding of the editor on mobile devices will be adjusted in a separate issue)
7. Open your console
8. Run `localStorage.setItem( 'debug', 'wc-admin:tracks' );` in the console.
9. Navigate to various WooCommerce Admin pages (not legacy pages), such as Analytics pages, Home, or the new Product editing experience
10. Make sure that `wcadmin_page_view` event is correctly triggered on each page

2023-05-15 09:17 UTC, louwie17 requested changes
Nice work! I like the creation of the `usePageClasses` hook 👌 
I did notice the fix only works for existing products and not on the create new page:
![Screenshot 2023-05-15 at 11 03 40 AM](https://github.com/woocommerce/woocommerce/assets/2240960/9fa35122-619f-4121-b1a0-1566239a3a70)

I did leave an inline comment about moving some of that css to WooCommerce Admin instead of the Editor component.

2023-05-15 09:17 UTC, louwie17 commented on packages/js/product-editor/src/components/editor/style.scss
> +.woocommerce-admin-page__product_product-id {
I don't think we should be adding a WooCommerce Admin specific page class to the css of the editor within a package. If this CSS is specific to the product page it should be moved to the `product-page.scss` sheet.

2023-05-15 09:17 UTC, louwie17 requested changes
Nice work! I like the creation of the `usePageClasses` hook 👌 
I did notice the fix only works for existing products and not on the create new page:
![Screenshot 2023-05-15 at 11 03 40 AM](https://github.com/woocommerce/woocommerce/assets/2240960/9fa35122-619f-4121-b1a0-1566239a3a70)

I did leave an inline comment about moving some of that css to WooCommerce Admin instead of the Editor component.

2023-05-15 09:17 UTC, louwie17 requested changes
Nice work! I like the creation of the `usePageClasses` hook 👌 
I did notice the fix only works for existing products and not on the create new page:
![Screenshot 2023-05-15 at 11 03 40 AM](https://github.com/woocommerce/woocommerce/assets/2240960/9fa35122-619f-4121-b1a0-1566239a3a70)

I did leave an inline comment about moving some of that css to WooCommerce Admin instead of the Editor component.

2023-05-15 18:08 UTC, joshuatf commented
@louwie17 Good catch!  And agreed.  I moved the product page styles to our client.  This required a quick rename of the (old-new) existing stylesheet.

2023-05-16 09:56 UTC, louwie17 approved these changes
Nice work, and thanks for moving some of the wcAdmin specific css to the client. This tested well 🚀

2023-05-16 09:56 UTC, louwie17 approved these changes, later dismissed
Nice work, and thanks for moving some of the wcAdmin specific css to the client. This tested well 🚀 

I guess just requires some lint error fixing.

2023-05-17 20:13 UTC, joshuatf commented
Hey @louwie17, had to fix up a failing test.  Could you give this another look?

2023-05-18 08:25 UTC, louwie17 approved these changes
Thanks for fixing the tests, LGTM 🚀

2023-05-18 08:25 UTC, merged