Replace deprecated `page` methods
woocommerce/woocommerce pull request #38344
Opened 2023-05-18 10:07 UTC by rodelgc

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

2023-05-18 10:53 UTC, rodelgc commented on plugins/woocommerce/tests/e2e-pw/test-data/data.js
> +		expectedNumberOfIndustries: 7, // There are 7 checkboxes on the page (in Liberia), adjust this constant if we change that
I encountered this issue during PR testing so I went ahead and included this minor fix.

2023-05-18 11:03 UTC, rodelgc commented
I'll submit this PR for review when https://github.com/woocommerce/woocommerce/pull/38335 is merged.

2023-06-10 23:11 UTC, rodelgc commented
Submitting this PR now for review. @nigeljamesstevenson this PR contains several changes to the texts used as locator arguments, and might therefore affect your PR (https://github.com/woocommerce/woocommerce/pull/38400). Just in case this PR gets merged before yours, I'd be happy to help with updating your PR if there are conflicts with mine.

2023-06-12 12:09 UTC, nigeljamesstevenson commented
> Submitting this PR now for review. @nigeljamesstevenson this PR contains several changes to the texts used as locator arguments, and might therefore affect your PR (https://github.com/woocommerce/woocommerce/pull/38400). Just in case this PR gets merged before yours, I'd be happy to help with updating your PR if there are conflicts with mine.

This is great stuff - Thanks a lot @rodelgc ! 
I will test and merge your PRs and will work through any conflicts with my [PR](https://github.com/woocommerce/woocommerce/pull/38400) - any issues and I'll hit you up - thanks again 😊

2023-06-13 10:15 UTC, nigeljamesstevenson commented
There are a few page.click calls in the `create-variations.spec.js` on the following lines:

- 54
- 63
- 113

2023-06-13 10:24 UTC, nigeljamesstevenson commented
There are page.dispatchEvent calls in the following locations:
e2e-pw/global-teardown.js line

- 32

merchant/create-shipping-classes.spec.js line

- 12
- 16
- 20

merchant/order-coupon.spec.js line

- 136 - although based on the comment in the code this one may require some thought

2023-06-13 10:29 UTC, nigeljamesstevenson commented
There are page.fill calls in the following locations:

merchant/create-shipping-zones.spec.js at line

- 308
- 331

2023-06-13 10:31 UTC, nigeljamesstevenson commented
There are page.hover calls in the following locations:

merchant/create-shipping-zones.spec.js line

- 335

2023-06-13 12:20 UTC, nigeljamesstevenson commented
There are page.isVisible calls in the following locations:

merchant/create-shipping-zones.spec.js line

- 335

2023-06-13 12:24 UTC, nigeljamesstevenson commented
There are page.isVisible calls in the following locations:

merchant/products/add-variable-product/create-variable-product.spec.js line

- 41

2023-06-13 12:29 UTC, nigeljamesstevenson commented
There are page.textContent calls in the following locations:

activate-and-setup/complete-onboarding-wizard.spec.js line

- 53
- 76

admin-analytics/analytics-overview.spec.js line

- 29

merchant/order-refund.spec.js line

- 57

shopper/order-email-receiving.spec.js line

- 91

e2e-pw/utils/onboarding.js line

- 35
- 46
- 71
- 85
- 111
- 146

2023-06-13 12:32 UTC, nigeljamesstevenson commented
There are page.type calls in the following locations:

merchant/create-shipping-zones.spec.js line

- 311

2023-06-13 12:33 UTC, nigeljamesstevenson commented
There are page.waitForSelector calls in the following locations:

merchant/create-shipping-zones.spec.js line

- 336

2023-06-13 12:35 UTC, nigeljamesstevenson requested changes
Hi @rodelgc - great work making all these updates - this is a BIG task 😊

I have listed a few more that I have spotted -  I know some of these will be taken into consideration with variations etc, but have listed them all for completeness - thanks!

2023-06-13 12:35 UTC, nigeljamesstevenson commented on plugins/woocommerce/tests/e2e-pw/tests/merchant/create-shipping-zones.spec.js
There are still a fair few page.click calls on the following lines:

- 96
- 159
- 310
- 312
- 316
- 322
- 330
- 332
- 342

2023-06-17 04:02 UTC, rodelgc commented
Thank you @nigeljamesstevenson 
Done addressing the review comments. Resubmitting for another round of review.

2023-06-20 11:49 UTC, nigeljamesstevenson commented
Looks great @rodelgc - unfortunately a few conflicts to be resolved

2023-06-20 11:49 UTC, nigeljamesstevenson approved these changes

2023-06-26 01:04 UTC, rodelgc commented
> Looks great @rodelgc - unfortunately a few conflicts to be resolved

Done resolving merge conflicts in my latest change (https://github.com/woocommerce/woocommerce/pull/38344/commits/7cec7fe70e16001979f3a73c1f525de7fd89a7f2)

There are only 3 files I changed in that commit:
- complete-onboarding-wizard.spec.js
- payment.spec.js
- page-loads.spec.js

2023-06-26 01:06 UTC, merged