Maybe default the selected state as the first one when it's "*"
woocommerce/woocommerce pull request #38469
Opened 2023-05-25 19:48 UTC by sc0ttkclark

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

When WC is provided only the country for the option `woocommerce_default_country` then it will fail to select a default state within the listed states.

Try this by manually setting `woocommerce_default_country` to "US" and you will see it selects the first country in the list instead of the first state within that country.

This only happens for countries that have states like US and CA for instance.

### How to test the changes in this Pull Request:

1. Create a WC store (but don't complete onboarding)
2. Manually set option: `wp option update woocommerce_default_country US` (use US or CA or any other country that has states that are selectable)
3. Go to the WooCommerce > Settings page
4. Look at the "Country / State" option, it should be now default to the first state for that country (previously it would set as "Afghanistan")

2023-05-26 17:08 UTC, rrennick requested changes
@sc0ttkclark Thanks for submitting this. The suggestions below should ensure this works correctly for all countries.

2023-05-26 17:08 UTC, rrennick commented on plugins/woocommerce/includes/class-wc-countries.php
> +					if ( '*' === $selected_state ) {
If you test with `wp option update woocommerce_default_country CA`, it defaults to `Afganistan`.

```suggestion
					if ( $selected_country === $key && '*' === $selected_state ) {
```

2023-05-26 17:08 UTC, rrennick commented on plugins/woocommerce/includes/class-wc-countries.php
> +						$selected_state = key( $states );
We only want to select a default state in countries that have states.

```suggestion
						$selected_state = key( $states ) ?? '*';
```

2023-05-26 17:27 UTC, sc0ttkclark commented
Sounds good, I'll get those implemented

2023-05-29 19:02 UTC, rrennick approved these changes
@sc0ttkclark Thanks for a great convenience fix for merchants setting up a new store.

2023-05-29 19:02 UTC, merged