add: updated payment gateways for 2023 Q3
woocommerce/woocommerce pull request #38646
Opened 2023-06-08 07:09 UTC by rjchow

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

2023-06-08 15:01 UTC, ilyasfoo requested changes
Thanks for working on this, @rjchow! I wanted to copy paste the whole spreadsheet and let ChatGPT figure it out so bad. One minor missed change I think

2023-06-08 15:01 UTC, ilyasfoo commented on plugins/woocommerce/src/Admin/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
> +							'ID',
I think missing `IN`
```suggestion
							'ID',
							'IN',
```

2023-06-09 04:57 UTC, ilyasfoo commented on plugins/woocommerce/src/Admin/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php
> +							'ID',
This will be addressed in https://github.com/woocommerce/woocommerce/pull/38658/

2023-06-09 04:58 UTC, ilyasfoo approved these changes
LGTM! Follow-up PR: https://github.com/woocommerce/woocommerce/pull/38658/

2023-06-09 07:27 UTC, adrianduffell approved these changes
LGTM thank you @rjchow ! 🚀

2023-06-09 09:15 UTC, merged