On-/offboarding copy updates
woocommerce/woocommerce pull request #39055
Opened 2023-06-30 19:40 UTC by mdperez86

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #38960

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Message 

#### Comment 

</details>

2023-07-07 20:55 UTC, louwie17 requested changes
Nice work on this @mdperez86, this tested well.
I left one comment in relation to the changelog for the CES package, if you could update that.
Also it looks like the Guide in the design uses a `primary` variant for the next button, I know this wasn't explicitly mentioned in the current issue.
So I can create a separate issue for it, but it should be a relatively simple fix if you could add it.
It just be matching the original Guide component in our copied version for this line: https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/guide/index.tsx#L154
Here is our version: https://github.com/woocommerce/woocommerce/blob/e6eda7fce5796e8baf784f68787593a2ad62ed93/plugins/woocommerce-admin/client/products/tour/components/guide/index.tsx#L101

2023-07-07 20:55 UTC, louwie17 commented on packages/js/customer-effort-score/changelog/enhancement-38960
> +New product block editor modal text enhancements
We should change this changelog to be CES specific.
In this case we are fixing the onsubmit label.

2023-07-10 15:06 UTC, mdperez86 commented on packages/js/customer-effort-score/changelog/enhancement-38960
> +New product block editor modal text enhancements
done -> [743725a](https://github.com/woocommerce/woocommerce/pull/39055/commits/743725aa8d48b12e218ddf67d808e7e816f32077)

2023-07-10 18:51 UTC, louwie17 approved these changes
LGTM 🚀 Thanks for the updates, this still tested well, thanks :)

2023-07-10 18:51 UTC, merged

2023-07-13 04:08 UTC, mattsherman commented
@mdperez86 @louwie17 This PR broke the alignment of the feedback bar content... it used to line up with the form (same left/right margins). It now is offset...

<img width="1258" alt="Screenshot 2023-07-13 at 00 06 02" src="https://github.com/woocommerce/woocommerce/assets/2098816/7af41f57-f176-4d53-acdb-4e41894d669e">

2023-07-13 04:12 UTC, mattsherman commented
It also broke the positioning of the snackbar notices... they should appear above the feedback bar (they did). They no longer do -- they now overlap the feedback bar (they shouldn't).

<img width="1258" alt="Screenshot 2023-07-13 at 00 10 33" src="https://github.com/woocommerce/woocommerce/assets/2098816/292e37f3-ad72-4c6d-90b6-e1be93220a6b">

2023-07-13 04:14 UTC, mattsherman commented
(I can create a new issue for these bugs later -- it's too late in the evening right now... just didn't want to lose track of them)

2023-07-13 13:07 UTC, louwie17 commented
> (I can create a new issue for these bugs later -- it's too late in the evening right now... just didn't want to lose track of them)

Good catch @mattsherman, I had not noticed those when reviewing. It be nice to get those in before the code freeze on Monday (if possible), especially the alignment one (cc @mdperez86 )

2023-07-13 15:03 UTC, mattsherman commented
@louwie17 @mdperez86 Here is the issue for tracking the regressions...

https://github.com/woocommerce/woocommerce/issues/39228