Try/single composer packages simple script
woocommerce/woocommerce pull request #39073
Opened 2023-07-04 01:57 UTC by psealock

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Message 

#### Comment 

</details>

2023-07-10 18:07 UTC, jonathansadowski requested changes
I added a minor suggestion about some potentially unneeded code after the removal of the check for `automattic/jetpack-changelogger` in the `require` or `require-dev` section, but that also brought up a question:

Do we need to add `.extra.changelogger` to the `composer.json` files for each project that we want checked, or is there some other way that I'm missing that we're indicating that a project requires a change file?

2023-07-10 18:07 UTC, jonathansadowski commented on tools/monorepo/check-changelogger-use.php
> +	$data                                   = isset( $data['extra']['changelogger'] ) ? $data['extra']['changelogger'] : array();
Minor suggestion: if we're continuing above when `$data['extra']['changelogger']` isn't set, we shouldn't need this `isset` check here, correct?

```suggestion
	$data                                   = $data['extra']['changelogger'];
```

2023-07-11 03:49 UTC, psealock commented
>Do we need to add .extra.changelogger to the composer.json files for each project that we want checked, or is there some other way that I'm missing that we're indicating that a project requires a change file?

Good call out here. Indeed the current way of checking `.extra.changelogger` won't work if we ever have a package or plugin that simply uses the default settings of Jetpack Changelogger. As it is now all our packages/project have this property and new ones would require it. That is less than ideal. Some projects are internal and don't require changelogs while others don't use Changelogger such as the e2e packages. Can you think of a good way to differentiate now that individual projects don't require Jetpack Changelogger?

2023-07-11 15:41 UTC, jonathansadowski commented
> Can you think of a good way to differentiate now that individual projects don't require Jetpack Changelogger?

Maybe it would be easier to just maintain a config of projects that require changelogger, and if it's not in that list, it won't check. A bit of a pain to maintain, but more straight-forward.

2023-07-18 02:07 UTC, psealock commented
Using `time pnpm install` on this branch and `trunk` I'm seeing a ~2 second reduction in time, which isn't too impressive.

@jonathansadowski, I've updated the mechanism for distinguishing Jetpack Changelogger projects to use a config option in `composer.json`:

```json
"config": {
	"changelog": "true"
}
```

2023-07-24 22:03 UTC, psealock commented
ping @jonathansadowski if you have a chance to re-review 🙇🏽‍♂️

2024-01-09 00:55 UTC, closed without merging