Update the admin's menu remaining tasks bubble CSS class and loosen the query selector for handling the runtime update
woocommerce/woocommerce pull request #39273
Opened 2023-07-17 14:07 UTC by xristos3490

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The tasks bubble/nudge in the **WooCommerce > Home** admin menu is limited to the current structure, which poses a challenge for third-party developers (3PDs) to rearrange the menu and still keep the badge updated automatically.

This PR aims to:
- Add a more specific class name to the bubble element, and;
- Update the `updateBadge()` function to accommodate different menu structures by loosening the query selector.

Closes #39045 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Pick a task to handle the completion status with ease; for example, we'll use the "Personalize your store" task.
2. Create a new shop or use an existing one and if the task is completed, update the `woocommerce_task_list_tracked_completed_actions` option and remove the `personalize` id from the serialized array.
3. Apply this patch and build `woocommerce/admin/client`.
4. Click on the task, and then continue by clicking "Skip" on the homepage prompt and then the "Complete task" button.
5. Ensure that the bubble next to **WooCommerce > Home** menu item updates automatically. 

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement

#### Message 

#### Comment 

</details>

2023-08-01 04:23 UTC, ilyasfoo requested changes
Apart from the console slip in the PR, changes look good, LGTM!

2023-08-01 04:23 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/task-lists/components/task.tsx
> +		window.console.log("RUNNING");
Debug 😄 
```suggestion
```

2023-08-01 07:43 UTC, xristos3490 commented on plugins/woocommerce-admin/client/task-lists/components/task.tsx
> +		window.console.log("RUNNING");
Oops! Nice catch!

2023-08-01 07:44 UTC, xristos3490 commented
Thanks for the review, @ilyasfoo! Cleaned up the log message at https://github.com/woocommerce/woocommerce/pull/39273/commits/f2283c250ceab79dc25a57ec2588facee77be351

2023-08-01 07:59 UTC, ilyasfoo approved these changes
LGTM! 🚢

2023-08-01 10:02 UTC, merged

2023-08-01 14:57 UTC, nigeljamesstevenson commented
Hi @xristos3490 @ilyasfoo 👋🏻

We were considering this PR as a candidate for GlobalStep testing. With that we would want the test steps to be handled through the UI so would be looking to validate the `woocommerce_task_list_tracked_completed_actions` with the Beta Tester/WCA Test Helper. i.e. once installed on the likes of a JN site, the Beta Tester can then be used via Tools > WCA Test Helper > Options and we can then view/edit/delete the woocommerce_task_list_tracked_completed_actions option

However, when looking at a test store, after completing the tasks for `You added products` and `Your personalized your store`, 
![image](https://github.com/woocommerce/woocommerce/assets/105309450/61fcc1a6-44d3-4b7c-ba96-13429973079e)

`woocommerce_task_list_tracked_completed_actions` contained
[
  "appearance"
]
`woocommerce_task_list_tracked_completed_tasks` contained
[
  "purchase",
  "appearance",
  "products"
]

None of which contained the `personalize` id as mentioned in [step 2](https://github.com/woocommerce/woocommerce/pull/39273#:~:text=remove%20the%20personalize%20id)

Just wondering if you have any guidance on this?

2023-08-02 00:37 UTC, ilyasfoo commented
Good catch, @nigeljamesstevenson!

I think it was mistaken, the id should be `appearance` instead of `personalize`. I opted to delete the whole option instead which was much simpler.

2023-08-02 07:37 UTC, xristos3490 commented
Nice catch! I intended to write "appearance" in the validation steps. I have updated it for future reference.