add: feature flag for customize your store task
woocommerce/woocommerce pull request #39397
Opened 2023-07-25 06:53 UTC by rjchow

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-07-27 14:17 UTC, ilyasfoo requested changes
Looking good, thanks for the legwork @rjchow! One minor comment about the PHP script still being imported.

2023-07-27 14:17 UTC, ilyasfoo commented on plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php
> +		'CustomizeStore',
In the current state, `CustomizeStore` script will still be imported in the `init_tasks` function. I think we should add check in there as well.

2023-07-31 10:14 UTC, rjchow commented on plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php
> +		'CustomizeStore',
as discussed, resolved by adding a comment to clarify the role of DEFAULT_TASKS

2023-07-31 11:20 UTC, ilyasfoo approved these changes
Nitpick comment about optionally removing `CustomizeStore` from the defunct list. LGTM anyways!  🚢

2023-07-31 11:20 UTC, ilyasfoo commented on plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php
> +		'CustomizeStore',
Looks good! Do you intend to remove `CustomizeStore` from the list though?

2023-08-01 05:00 UTC, chihsuan approved these changes
Great work! LGTM and tested well. 🚀

2023-08-01 09:51 UTC, rjchow commented on plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php
> +		'CustomizeStore',
ok will do 😅

2023-08-01 12:28 UTC, merged