Ensure My Subscriptions page is still accessible when new marketplace is enabled
woocommerce/woocommerce pull request #39569
Opened 2023-08-03 16:30 UTC by andfinally

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes 17518-gh-Automattic/woocommerce.com.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Check out the branch.
2. From the `plugins/woocommerce` folder, run `pnpm build --filter=woocommerce`.
3. If you get a fatal error, run `composer dump-autoload` to refresh the composer autoload file.
4. Visit the Extensions page. ((WP Env URL is http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fextensions).)
5. You should see tabs for `Discover`, `Browse` and `My Subscriptions`. 
6. Click on `My Subscriptions`. You should see the My Subscriptions page. This page should continue to function as normal.
a. You should see your connection status, and be able to disconnect and reconnect.
b. You should see your subscriptions, and download the extensions for them.
c. You should be able to refresh the list by clicking the `Update` button.
7. Click the `Browse Extensions` tab. You should go to the Extensions tab of the new marketplace UI.

### Screenshots

<img width="500" src="https://github.com/woocommerce/woocommerce/assets/1647564/9b697f9c-0d8e-4cd5-ab62-4701f755a7f7">

<img width="500" src="https://github.com/woocommerce/woocommerce/assets/1647564/9b2d2bc6-f696-4f47-a592-5c6e0b6775a1">

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-08-03 16:31 UTC, andfinally commented on plugins/woocommerce/includes/admin/class-wc-admin-menus.php
> +use Automattic\WooCommerce\Internal\Admin\WCAdminAssets;
I reordered these.

2023-08-04 12:46 UTC, kdevnel approved these changes
Wow, this is really solid! Love the solution and it works exactly as described. What could have been problematic, works perfectly. Glad to see the React user menu seamlessly works with this!

Perhaps we should include removing these lines from my helper class:

https://github.com/woocommerce/woocommerce/blob/c8c7098a032adb8b82b0d5bb184a30e65f8eb59d/plugins/woocommerce/includes/admin/helper/class-wc-helper-admin.php#L69-L71

This would remove the redundant code (that isn't needed anymore), and will also remove the PHPCS complaint about TODO comments in the code.

2023-08-04 14:20 UTC, andfinally commented
Thanks @kdevnel, good point – deleted the two commented lines from `class-wc-helper-admin.php`.

2023-08-04 15:06 UTC, jonathansadowski commented
It again looks like Atlas was assigned as a reviewer because a previous version of this PR touched something in `.github`. As that no longer appears to be the case, I'm going to resign from this PR as a reviewer, but as always, if there's anything ya'll need a hand reviewing, just let us know

2023-08-08 09:19 UTC, Dan-Q requested changes
This flash of content is a bit ugly:

https://github.com/woocommerce/woocommerce/assets/53293/97188075-f5f6-47a7-a18c-d81d964e57b7

It's happening because we treat the "My Subscriptions" tab as just another tab, let it render, and only afterwards do we redirect the navigation. That feels like a bit of a hack: we're making the user wait longer and making the code more fragile just so we don't have to do a tiny bit of extra development!

[Here's how I'd propose changing it](https://github.com/woocommerce/woocommerce/compare/add/wccom-17518-my-subscriptions...add/wccom-17518-my-subscriptions-with-hyperlink) (sorry it's not a GH suggestion: it spanned too many lines outside of those you touched to be allowed - but you can integrate it by simply merging the branch `add/wccom-17518-my-subscriptions-with-hyperlink` into this branch if you agree with it):

1. Expand Tabs so they can be not only `<Button>`s, but also hyperlinks (`<a>`), if a `href` prop is passed to them. If the aim of the exercise is "when the user clicks, go to another page", a hyperlink is always the correct choice (better a11y too).
2. Instead of catching the "special case" of `tabKey === 'my-subscriptions'` and then redirecting to a special URL, just pass the special URL in as the `href` of that Tab!

What do you think?

2023-08-08 15:22 UTC, andfinally commented
Brilliant addition, thanks Dan! 👌  Merged your branch.

2023-08-09 13:28 UTC, raicem approved these changes
Nice! Sold work. Thanks @andfinally.

2023-08-09 14:19 UTC, merged