Update marketplace product card for updated WCCOM search API
woocommerce/woocommerce pull request #39689
Opened 2023-08-11 14:30 UTC by kdevnel

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

As part of https://github.com/Automattic/woocommerce.com/issues/17829 we need to ensure that the product cards display the correct currency symbol and price for both the Discover page, and the search results.

This PR updates to using the values from the new API endpoint changes on `woocommerce.com` that include pricing and currency symbols in the correct format.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch locally 
2. Update [this line](https://github.com/woocommerce/woocommerce/blob/4d8fd6378c3eb91d5fc3ac437f35f89670c3c6a7/plugins/woocommerce-admin/client/marketplace/components/constants.ts#L3C3-L3C3) to `export const MARKETPLACE_URL = 'https://woocommerce.test';`
3. From `plugins/woocommerce-admin` run `pnpm run build`
4. Visit the Discovery page (wp-env URL: http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fextensions)
5. Check that the product cards correctly display as either "Free download" or with a rounded price.
    - Note: there is a separate issue to deal with an encoding issue so the price currently displays with an entity code for the currency symbol at the start. This means seeing `&#36;29 annually` is to be expected and should appear in the API response. It is the equivalent of `$29 annually`

<img width="1515" alt="Screenshot 2023-08-14 at 16 04 05" src="https://github.com/woocommerce/woocommerce/assets/22053773/62433065-54ff-4b0b-9ad2-19a887101b9b">

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-08-15 10:08 UTC, andfinally requested changes
Looks like we need to rebase this branch, but I guess the changes to look at are the ones in https://github.com/woocommerce/woocommerce/pull/39689/commits/2d947ff136becf5582b911b70abad051eeac3edb.

I'm getting `&#036;0 annually` for a free product. This is because the price in the featured endpoint is `0` and not `'0'`. For example:

```js
{
    "id": 3545890,
    "title": "Multichannel for WooCommerce: Google, Amazon, eBay &amp; Walmart Integration",
    "description": "Get the official Google, Amazon, eBay and Walmart extension and create, sync and manage multichannel listings directly from WooCommerce.",
    "vendorName": "",
    "vendorUrl": "https://woocommerce.test/vendor/codisto/",
    "icon": null,
    "url": "https://woocommerce.test/products/amazon-ebay-integration/?utm_source=extensionsscreen&utm_medium=product&utm_campaign=wcaddons",
    "currencySymbol": "&#036;",
    "price": 0,
    "productType": "simple",
    "averageRating": 3.3,
    "reviewsCount": 42,
    "currency": "USD"
}
```

<img width="500" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1647564/86e890b1-5163-41a9-89fe-24b412fee3a2">

2023-08-15 13:13 UTC, kdevnel commented
Thanks for the feedback! There is another problem around displaying the currency symbol that I need to address. Will post up for review again once I've resolved.

2023-08-16 12:00 UTC, kdevnel commented
Okay, I solved my issues now. I have changed to using the same method to get the price in both endpoints, and I am favouring the float. That way we can use it as a number in all places, and it is much more predictable to work with.

Also, I was today years old when I discovered that WooCommerce.com only displayed prices in USD until very recently. I was trying to solve a problem that didn't exist previously in relation to currency symbols. For simplicity, I've hardcoded the `$` sign. We can always do more with that later if need be.

Thanks for all the previous feedback! It's super helpful.

**PS About testing**
To get the most out of this, switch your WCCOM testing site to the `update/17829-marketplace-search-api` branch.

2023-08-16 14:51 UTC, raicem approved these changes
Thank you for sorting out the tricky situation with prices!

2023-08-17 07:56 UTC, andfinally approved these changes
Works nicely, looks neat!

2023-08-17 07:59 UTC, merged