Add quick actions dropdown menu per variation item
woocommerce/woocommerce pull request #39816
Opened 2023-08-19 19:13 UTC by mdperez86

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #39787

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-08-21 19:19 UTC, AnnaMag requested changes
@mdperez86 tests great. One piece to improve is listing the variation options fully for 3 terms, instead of hiding the 3rd term under as _+1_
<img width="625" alt="Screenshot 2023-08-21 at 21 13 11" src="https://github.com/woocommerce
<img width="547" alt="Screenshot 2023-08-21 at 21 13 23" src="https://github.com/woocommerce/woocommerce/assets/13561163/dc3464fd-da27-41de-803c-0d154b3a987c">
<img width="625" alt="Screenshot 2023-08-21 at 21 13 11" src="https://github.com/woocommerce/woocommerce/assets/13561163/52b25e2d-985b-4db5-9188-f148f0d780c5">

2023-08-21 19:48 UTC, mdperez86 commented
> @mdperez86 tests great. One piece to improve is listing the variation options entirely for 3 terms instead of including the 3rd term in the _+1_ category. <img width="625" alt="Screenshot 2023-08-21 at 21 13 11" src="https://github.com/woocommerce <img alt="Screenshot 2023-08-21 at 21 13 23" width="547" src="https://user-images.githubusercontent.com/13561163/262131832-dc3464fd-da27-41de-803c-0d154b3a987c.png"> <img alt="Screenshot 2023-08-21 at 21 13 11" width="625" src="https://user-images.githubusercontent.com/13561163/262132082-52b25e2d-985b-4db5-9188-f148f0d780c5.png">

@AnnaMag thanks for the review! Would you mind to create a separate issue to cover that, since what you mentioned here does not belongs to the scope of this issue!

2023-08-21 19:51 UTC, AnnaMag commented
@mdperez86 tracks recommendations. 
OPTIONS
- `wcadmin_product_options_add_button ` **Add new** button
- follow-up to the latter: `wcadmin_product_options_add` with props '{'attribute': X, 'values': array[]}'. Given that there might be a few of those, we could consider an array here.
- `wcadmin_product_options_edit ` Edit 
- within the latter one:  `wcadmin_product_options_update` with props {'filter': true/false, 'default': true/false, 'visible': true/false} on Update (if values changed)
VARIATIONS
- `wcadmin_product_variations_preview` 
- `wcadmin_product_variations_delete`
- `wcadmin_product_variations_hide`  (Not visible to customers).

Imo we can move those to a separate issue.

2023-08-21 19:52 UTC, AnnaMag approved these changes
LGTM

2023-08-22 11:18 UTC, AnnaMag commented
@mdperez86 Tests well.

2023-08-22 11:42 UTC, louwie17 commented
> @AnnaMag thanks for the review! Would you mind to create a separate issue to cover that, since what you mentioned here does not belongs to the scope of this issue!

The testing team had also noticed this and created an issue for this: https://github.com/woocommerce/woocommerce/issues/39842

2023-08-22 13:32 UTC, AnnaMag commented
I opened an issue yesterday: https://github.com/woocommerce/woocommerce/issues/39832.

2023-08-22 13:36 UTC, louwie17 commented
> I opened an issue yesterday: #39832.

Thanks for closing the other one :)

2023-08-22 14:42 UTC, merged