Add code snippet to add a country
woocommerce/woocommerce pull request #39850
Opened 2023-08-22 14:07 UTC by nielslange

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woodocs/issues/102

This PR adds the code snippet [Add a country](http://www.woocommerce.com/document/add-a-new-country-to-countries-list/) to the Woo docs.

### How to test the changes in this Pull Request:

1. Compare the content of the file docs/snippets/add-a-country.md with the content on http://www.woocommerce.com/document/add-a-new-country-to-countries-list/.
2. Verify that the new link within docs/snippets/README.md points to the newly added code snippet.

2023-08-22 17:27 UTC, barryhughes requested changes
Looks good, confirmed the snippet works. Left a note about a minor adjustment we should probably do.

2023-08-22 17:27 UTC, barryhughes commented on docs/snippets/add-a-country.md
> +> This is a **Developer level** doc. If you are unfamiliar with code and resolving potential conflicts, select a [WooExpert or Developer](https://woocommerce.com/customizations/) for assistance. We a
Similar to related PRs, we can drop this call-out.

```suggestion
```

2023-08-23 10:52 UTC, nielslange commented on docs/snippets/add-a-country.md
> +> This is a **Developer level** doc. If you are unfamiliar with code and resolving potential conflicts, select a [WooExpert or Developer](https://woocommerce.com/customizations/) for assistance. We a
Removing this note based on p1692723749470709/1692723559.960259-slack-C0516GKR69W

2023-08-23 11:46 UTC, nielslange commented
> Looks good, confirmed the snippet works. Left a note about a minor adjustment we should probably do.

Thanks for reviewing this PR, @barryhughes. Unfortunately, I do not have the necessary permissions to merge this PR without your approval. I applied all your suggestions. Could you double-check and approve this PR so that I can merge it?

2023-08-23 16:16 UTC, barryhughes approved these changes

2023-08-23 20:39 UTC, merged