Optimize customize store preview frame resize performance
woocommerce/woocommerce pull request #39930
Opened 2023-08-28 07:22 UTC by chihsuan

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #39929.

I thought MemoizedBlockList was a specific component in a previous PR, but didn't realize it was just a variable for performance issues to [avoid re-rendering if size changes]()https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-preview/auto.js#L18.

The frame resizing performance has improved drastically after this PR

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Use WP 6.3 
2. Install the `WooCommerce Beta Tester` plugin
3. Go to /wp-admin/tools.php?page=woocommerce-admin-test-helper and enable `customize-store` feature flag
4. Go to `WooCommerce > Home`
5. Click on `Customize your store` task 
6. Click on `Assembler Hub` button
7. You should see the Assembler Hub screen
8. Try to resize the preview frame by hovering the frame and dragging the resizing handler.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Optimize customize store preview frame resize performance

#### Comment 

</details>

2023-08-28 22:30 UTC, moon0326 approved these changes
Thank you so much for the fix 👍 

LGTM and tested well. It's super fast now 🚀

2023-08-29 07:06 UTC, rjchow requested changes
Beautiful! It's very smooth now
I noticed a bug where, if you drag it too far open then the handle is obscured and cannot be resized anymore:

https://github.com/woocommerce/woocommerce/assets/27843274/d35fe537-84ee-4b8c-8d03-bfc5a47236fd

2023-08-29 13:11 UTC, chihsuan commented
> Beautiful! It's very smooth now I noticed a bug where, if you drag it too far open then the handle is obscured and cannot be resized anymore:
> 
>  Screen.Recording.2023-08-29.at.17.04.00.mov

Good catch! @rjchow Fixed in 19fe2e1c9d0b872855f304540b892999a5b3a304 😃 

https://github.com/woocommerce/woocommerce/assets/4344253/55d6f700-886f-4c71-be4b-69e07e897c01

2023-08-30 05:32 UTC, rjchow approved these changes
Nice! Thanks for fixing that!

2023-08-30 05:38 UTC, merged

2023-08-30 13:39 UTC, jonathansadowski commented
Hi @chihsuan, it looks like there's an unused import of `useState` in `plugins/woocommerce-admin/client/customize-store/assembler-hub/layout.tsx` after this PR. Would you mind creating a follow-up PR to clean that up?