Add/39126 add tags to product editor
woocommerce/woocommerce pull request #39966
Opened 2023-08-30 16:06 UTC by octaedro

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-09-04 17:23 UTC, mdperez86 requested changes, later dismissed
@octaedro Big job here! I left some comments.

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/product-editor/src/components/tags-field/tag-field.tsx
> +				id="tag-field"
We should use `import { useInstanceId } from '@wordpress/compose';` instead to avoid `id` conflicts

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/product-editor/src/components/tags-field/use-tag-search.ts
> +	const isAsync =
I don't think we need this since the request is being cached anyway when calling `resolveSelect`

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/product-editor/src/components/tags-field/use-tag-search.ts
> +			if ( ! isAsync && initialTags.length > 0 ) {
We don't need this since `resolveSelect` caches the response.

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/product-editor/src/components/tags-field/use-tag-search.ts
> +				initialTags: getProductTags( productTagQueryObject ),
Since we are going to make a request to search I don't think we need a different way to do the same request using `useSelect` and `resolveSelect`. I would rather do the same filter function and call it at the very beginning inside a `useEffect` and then inside the `onChange`.
```
async function filter(...) {
  return resolveSelect(...)
}

useEffect(() => filter(...).then(...), deps);

function onChange() {
  filter(...).then(...)
}
```

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/product-editor/src/components/tags-field/use-tag-search.ts
> +				totalCount: getProductTagsTotalCount( productTagQueryObject ),
Also we don't need the `totalCount` if we are not going to do pagination

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/product-editor/src/components/tags-field/use-tag-search.ts
> +			if ( ! isAsync && initialTags.length > 0 ) {
Also this condition here produces a wrong filtering behavior

Wrong 
<img width="687" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13334210/630cedd5-ed09-42a4-ad16-4f63e9f259cb">

Correct 
<img width="682" alt="image" src="https://github.com/woocommerce/woocommerce/assets/13334210/bc525e1a-f3bc-4187-adf4-9cd7eec56d2a">

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/product-editor/src/components/tags-field/tag-field.tsx
> +import { debounce } from 'lodash';
We should not use lodash anymore since this is intended to be removed

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/product-editor/src/components/tags-field/tag-field.tsx
> +		() => debounce( onInputChange, 150 ),
use `import { useDebounce } from '@wordpress/compose';` instead or `import { useAsyncFilter } from '@woocommerce/components';`

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
> +	newInputValue?: string | boolean;
I think this is an `initialInputValue` and its type should be `string` | `undefined` and not `string` | `boolean` | `undefined` since undefined can be used as a falsy value too.

2023-09-04 17:23 UTC, mdperez86 commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
> +		if ( newInputValue !== false && isFocused ) {
`newInputValue !== undefined`

2023-09-06 13:28 UTC, octaedro commented on packages/js/product-editor/src/components/tags-field/use-tag-search.ts
> +	const isAsync =
Nice catch!

2023-09-06 13:29 UTC, octaedro commented on packages/js/components/src/experimental-select-tree-control/select-tree.tsx
> +		if ( newInputValue !== false && isFocused ) {
Good idea!

2023-09-06 13:50 UTC, octaedro commented
Thank you @mdperez86 for reviewing this PR.
I addressed the suggestions you made. Could you give this PR another look?

2023-09-06 18:12 UTC, mdperez86 approved these changes
Great job here @octaedro LGTM!!!

2023-09-06 18:51 UTC, merged

2023-09-07 03:14 UTC, rodelgc commented
Labeling this for internal testing and high impact because of the great number of changes contained in the PR.