Auto select one or more attribute terms when selecting an attribute
woocommerce/woocommerce pull request #40004
Opened 2023-09-01 13:42 UTC by mdperez86

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #39892

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-09-05 15:54 UTC, nathanss requested changes
Working as designed! Left some comments regarding the code. Nice job!

2023-09-05 15:54 UTC, nathanss commented on packages/js/product-editor/src/blocks/variation-options/edit.tsx
> +				termsAutoselection="all"
I think `termsAutoSelection` is more correct (camel case)

2023-09-05 15:54 UTC, nathanss commented on packages/js/product-editor/src/components/attribute-control/new-attribute-modal.tsx
> +										focusValueField( index );
I think it's odd to focus if all attributes were already selected. Not sure if it's an explicit requirement, but I would remove this

2023-09-05 15:54 UTC, nathanss commented on packages/js/product-editor/src/components/attribute-control/new-attribute-modal.tsx
> +									.catch( () => {} );
I think this would actually suppress an error, making it invisible. We should either remove this or add some error handling here

2023-09-05 17:04 UTC, mdperez86 commented on packages/js/product-editor/src/components/attribute-control/new-attribute-modal.tsx
> +										focusValueField( index );
Well we might want to create a term that is not part of the selection but I can understand your point.
While this is not specific to this issue, it is related to other one that was already implemented. Let's see what @jarekmorawski has to say here.

@nathanss I want to suggest leaving this as it is right now and tackle it once Jarek comes back.

2023-09-05 17:07 UTC, mdperez86 commented on packages/js/product-editor/src/blocks/variation-options/edit.tsx
> +				termsAutoselection="all"
done -> https://github.com/woocommerce/woocommerce/pull/40004/commits/abe946338c1ccbb0e7d43192da3f8c526d320e25

2023-09-05 17:19 UTC, mdperez86 commented on packages/js/product-editor/src/components/attribute-control/new-attribute-modal.tsx
> +									.catch( () => {} );
done -> https://github.com/woocommerce/woocommerce/pull/40004/commits/9313f2e13cf80ee7a720744aa991aa0652c7730d

2023-09-05 17:25 UTC, nathanss approved these changes

2023-09-05 19:29 UTC, merged

2023-09-06 00:21 UTC, rodelgc commented
Will be tested at a later stage, together with the other functionalities of the variation management features.