Migrate Category field to woocommerce/taxonomy-field block
woocommerce/woocommerce pull request #40021
Opened 2023-09-04 14:29 UTC by nathanss

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Migrate Category field to woocommerce/taxonomy-field block

Closes #40019 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. 
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-09-04 14:45 UTC, nathanss commented on plugins/woocommerce-admin/client/products/fills/details-section/details-section-fills.tsx
> -		<WooProductFieldItem
Is it OK to remove this?

2023-09-05 19:17 UTC, mattsherman requested changes
Overall, works largely as expected. Love all the removed code!

Left a comment or two.

In addition, I noticed the following differences:

- The style of the "Save" button in the create modal is incorrect when saving
    - We are missing a `setIsCreating( true )` call in `CreateTaxonomyModal::onSave()`

- If you create a new category and set a parent for it:
    - The old category field selects the parent when you save the new category
    - The new taxonomy field does not select the parent when you save the new category
    - I'm not really sure which one is "correct"... we don't auto-select the parent in any other scenario, so I'm leaning towards saying that the new behavior is actually correct

2023-09-05 19:17 UTC, mattsherman commented on plugins/woocommerce-admin/client/products/fills/details-section/details-section-fills.tsx
> -		<WooProductFieldItem
I believe so... this is from the old new product editor, right?

2023-09-05 19:17 UTC, mattsherman commented on plugins/woocommerce-admin/client/products/fills/details-section/details-section-fills.tsx
> -		<WooProductFieldItem
We really should get rid of all of that old new product editor code in a separate PR!

2023-09-05 19:17 UTC, mattsherman commented on plugins/woocommerce/src/Admin/Features/ProductBlockEditor/BlockRegistry.php
> -		'woocommerce/product-category-field',
Should we add an entry for `woocommerce/taxonomy-field`?

I'm not really sure why it works without it, or what any problem would be.

2023-09-05 20:47 UTC, nathanss commented
> * If you create a new category and set a parent for it:
>   
>   * The old category field selects the parent when you save the new category
>   * The new taxonomy field does not select the parent when you save the new category
>   * I'm not really sure which one is "correct"... we don't auto-select the parent in any other scenario, so I'm leaning towards saying that the new behavior is actually correct

@mattsherman I have never noticed that in the old field! I also think the new behavior is correct! I believe I addressed all your other suggestions. Thank you for the review!

2023-09-06 10:41 UTC, mattsherman approved these changes
Nice work on this, @nathanss ! :shipit:

2023-09-06 13:21 UTC, merged

2023-09-07 02:31 UTC, rodelgc commented
Hi @nathanss @mattsherman, just one quick question: the changes in this PR only affects the new product block editor, if I understand it correctly? Or does it also impact the categories in the legacy product editor?

The PR touched a lot of files and made changes across them, so just verifying with you both if this would have any impact on the legacy experience. 

For the meantime, I'm adding the `needs: internal testing` label with `impact: high` since the PR contains many changes even though it's behind a feature flag. I'll remove `impact: high` if the changes turn out to be not impacting the legacy experience.

2023-09-07 11:46 UTC, mattsherman commented
@rodelgc Correct, this PR only affects the new product block editor. It does not affect the legacy product editor.