Marketplace: update discover page card counts
woocommerce/woocommerce pull request #40020
Opened 2023-09-04 14:01 UTC by kdevnel

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR addresses In-app marketplace feedback.

Closes https://github.com/Automattic/woocommerce.com/issues/18030

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch locally and from `plugins/woocommerce-admin` run `pnpm run build`
2. Visit WooCommerce > Extensions from your development site (**wp-env**: http://localhost:8888/wp-admin/admin.php?page=wc-admin&path=%2Fextensions)
3. See that on mobile (one-column) all cards display
4. See that on 2-column layouts only 2 cards display per section
5. See that on 3-column layouts only 3 cards display per section
6. See that on larger screen sizes over 1920px that 4 cards display on the “Discover our Favourites” section (other sections only return 3 results in the API)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-09-05 10:27 UTC, andfinally requested changes
Works nicely! I like this for the first rule, which is simpler, and will hide all children from the third upwards, as opposed to just the third and fourth. We may be asked to show additional items on this page in future, but this gets it tidy for now.

I took the liberty of rebasing the branch to see if it fixes the weirdly broken test builds. I had a lot of trouble getting to see the UI on my local environment. I think this was because the WooCommerce Blocks package was missing – `pnpm install` may have helped in my case.

```diff
Index: plugins/woocommerce-admin/client/marketplace/components/product-list-content/product-list-content.scss
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/plugins/woocommerce-admin/client/marketplace/components/product-list-content/product-list-content.scss b/plugins/woocommerce-admin/client/marketplace/components/product-list-content/product-list-content.scss
--- a/plugins/woocommerce-admin/client/marketplace/components/product-list-content/product-list-content.scss	(revision 08370f27bf84f8d1d1286ea64cd96d59ebfa3be4)
+++ b/plugins/woocommerce-admin/client/marketplace/components/product-list-content/product-list-content.scss	(date 1693909384567)
@@ -20,10 +20,9 @@
 			gap: $large-gap;
 			grid-template-columns: repeat(2, 1fr);
 		}
-		// Hide third and fourth product cards on Discover page due to API result count
+		// Hide third and above product cards on Discover page due to API result count
 		// These are progressively displayed at larger screen sizes.
-		&__discover .woocommerce-marketplace__product-card:nth-child(3),
-		&__discover .woocommerce-marketplace__product-card:nth-child(4) {
+		&__discover .woocommerce-marketplace__product-card:nth-child(n+3){
 			display: none;
 		}
 	}
```

2023-09-05 12:37 UTC, kdevnel commented
I've implemented your feedback @andfinally – that's a neat nth-child trick! Thanks for sharing.

2023-09-06 16:22 UTC, raicem approved these changes

2023-09-08 09:44 UTC, kdevnel commented
@andfinally could you take another look at this one to unblock the merge? Thanks!

2023-09-08 14:38 UTC, andfinally approved these changes
Looks great, thanks for sorting this one!

2023-09-11 13:33 UTC, merged