Add filter woocommerce_hpos_enable_sync_on_read to disable sync on read with HPOS sync enabled.
woocommerce/woocommerce pull request #40039
Opened 2023-09-05 09:21 UTC by vedanshujain

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Allow opportunity to disable sync on read, while keeping sync on write disabled. This adds another step as a large shop progresses from full sync to no sync with HPOS authoritative.

This filter is only executed if data sync is enabled from settings in the first place as it's meant to be a step between full sync -> no sync, rather than a control for enabling just the read-on sync. Sync on read without sync on write is problematic as any update will reset on the next read, but sync on write without sync on read is fine.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Set HPOS to authoritative and sync to on.
2. Create a new order via order admin, note it's ID, let's say its X.
3. Add the following code snippet in your site: `add_filter( 'woocommerce_hpos_enable_sync_on_read', '__return_false' );`
4. Add direct post meta to this order using the following command:
```
wp post meta add X test_key test_value
```
5. Refresh the order edit page. Check that the test_key and test_value is not listed in the `Custom Fields` meta box.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-09-05 10:42 UTC, peterfabian commented
A few notes from my testing: 

Not sure if this is a problem only for my WP installation, but the WP CLI command doesn't work as I'd expect:
```
% wp post meta add 178045 test_key test_value
Success: Added custom field.
% wp post meta get 178045 test_key
%
```
Also, there were no traces of the data in the wp_postmeta table, so instead I manually added the postmeta and tried to confirm nothing happened on read.

In my installation, when I reload the Edit Order screen, the `_edit_lock ` gets updated, so the `test_key` and `test_value` pair gets deleted. What seemed to work as a pure read is to navigate to the Orders screen instead. 

Additionally, it would be nice to include a positive case in the testing instructions, i.e. to make sure that the sync on write still works as intended.

2023-09-05 10:43 UTC, peterfabian requested changes
After the testing instructions are improved and the docs get updated, I think it should be good to go.

2023-09-05 10:43 UTC, peterfabian commented on plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php
> +			 * Allow opportunity to disable sync on read, while keeping sync on write disabled. This adds another step as a large shop progresses from full sync to no sync with HPOS authoritative.
```suggestion
			 * Allow opportunity to disable sync on read, while keeping sync on write enabled. This adds another step as a large shop progresses from full sync to no sync with HPOS authoritative.
```

2023-09-05 12:38 UTC, peterfabian approved these changes
Looks good now!

2023-09-05 12:45 UTC, merged

2023-09-06 00:15 UTC, rodelgc commented
Will be tested internally because it's HPOS, and also because of the shell commands that need to be run within the test environment.