[WIP] Customize your store header
woocommerce/woocommerce pull request #40107
Opened 2023-09-11 09:38 UTC by samueljseay

Description TBD

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-09-11 09:39 UTC, samueljseay commented on plugins/woocommerce-admin/webpack.config.js
> +		// ! process.env.STORYBOOK && new ForkTsCheckerWebpackPlugin(),
Ignore, just me getting frustrated by TS errors while trying to develop :P

2023-09-12 01:42 UTC, samueljseay commented on plugins/woocommerce-admin/client/customize-store/assembler-hub/layout.tsx
> +			<EntityProvider kind="root" type="site">
This diff is hard to read but all I did was move EntityProvider here so we can access blocks from inside side nav

2023-09-12 08:48 UTC, chihsuan requested changes
Hey @samueljseay, Thanks for adding this super quickly. 👍 

I just noticed some issues:

1. It seems that the header patterns cannot be selected again when reloading the page after saving. Could you take a look?
https://github.com/woocommerce/woocommerce/assets/4344253/d7ad4f42-57d9-476e-bf82-6a445351c4d2

2. We should add a focus style border to the selected header pattern on the sidebar. Also need to start with the opacity preview frame (except the header) — when the user scrolls down, bring it back to 100%.

<img width="1280" alt="Header" src="https://github.com/woocommerce/woocommerce/assets/4344253/2bf6cabd-5d88-4d5c-864d-e0f5457b0cdc">

3. We only need to show these four header patterns (Sorry, didn't have it in the issue):

Slug:
- woocommerce-blocks/header-centered-menu-with-search
- woocommerce-blocks/header-essential
- woocommerce-blocks/header-large
- woocommerce-blocks/header-minimal

2023-09-12 08:48 UTC, chihsuan commented on plugins/woocommerce-admin/client/customize-store/assembler-hub/sidebar/sidebar-navigation-screen-header.tsx
> +	// return null;
```suggestion

```

2023-09-12 19:56 UTC, moon0326 reviewed
Thank you for the changes :) This is a good reference PR for me.

While testing the changes, I've noticed a possible bug in an edge case.

Steps to reproduce

1. Go to the header page
2. Refresh
3. Click `Assembler Hub`
4. Notice the blocks render twice.

https://github.com/woocommerce/woocommerce/assets/4723145/41c538eb-d101-4719-a717-a7c02fe12217

2023-09-13 06:59 UTC, samueljseay commented
@moon0326 I explored the flickering. As you mentioned it happens if you page refresh and it auto navigates to this screen. unfortunately I think this is some bug with the rendering of the layout and navigation screen code that causes redundant re-renders of `SidebarNavigationScreenHeader`, which in turn re-renders the `BlockPatternList`. I haven't got to the bottom of this yet, but I'm thinking maybe it needs to be solved in a separate PR.

2023-09-13 13:29 UTC, samueljseay commented
@chihsuan I've fixed the issue with saving, I've added some code to handle opacity too, but do you have a suggestion for overriding styles for items in `BlockPatternList`? kinda feels like we need something like emotion to add some targeted styles, otherwise I can add some global styles to fix it.

2023-09-14 02:36 UTC, chihsuan approved these changes
> I've fixed the issue with saving, I've added some code to handle opacity too, but do you have a suggestion for overriding styles for items in BlockPatternList? kinda feels like we need something like emotion to add some targeted styles, otherwise I can add some global styles to fix it.

Hey @samueljseay Thanks for the fix! I confirm that I can save changes successfully 👍  I think adding global styles is probably the only way at the moment. We could file an issue on Gutenberg repo to support that. 😄 

There seem to be a few issues but I think we can address as a follow-up to unblock other tasks as discussed:

1. After jumping out of the header sidebar menu, opacity still exists. We should remove it. 🙂 

https://github.com/woocommerce/woocommerce/assets/4344253/5f7a83dc-3f84-4719-945e-2576ee212cf4

2. I haven't been able to reliably reproduce this issue yet, but it seems that there are some things that may cause the page to become unresponsive. 🤔 

![Screenshot 2023-09-14 at 10 27 25](https://github.com/woocommerce/woocommerce/assets/4344253/3cb6b9c4-536c-4406-9cb9-b677e904760b)

2023-09-14 04:39 UTC, samueljseay commented
> After jumping out of the header sidebar menu, opacity still exists. We should remove it. 🙂

😅 good point, This wasn't hard so I added it.

> I haven't been able to reliably reproduce this issue yet, but it seems that there are some things that may cause the page to become unresponsive. 🤔

Ok I haven't seen this yet but I'll keep an eye on it 👁️

2023-09-14 08:24 UTC, merged