Shipping Settings: Add React base Region Picker
woocommerce/woocommerce pull request #40184
Opened 2023-09-14 22:56 UTC by psealock

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-09-21 18:39 UTC, samnajian commented
@psealock It's not allowing selection of a main stem if it has sub-trees ![YeiLpW.gif](https://github.com/woocommerce/woocommerce/assets/789421/b71a64c6-ccfb-4760-ac6b-66deee233653)

2023-09-21 19:21 UTC, samnajian requested changes
Great way of handling React in legacy JS!
Left some comments.

2023-09-21 19:21 UTC, samnajian commented on plugins/woocommerce/includes/admin/settings/views/html-admin-page-shipping-zone-methods.php
> +use Automattic\WooCommerce\Internal\Admin\WCAdminAssets;
Seems like line 12 to 49 doesn't belong to this template file but rather to `WC_Settings_Shipping::zone_methods_screen`

2023-09-21 19:21 UTC, samnajian commented on plugins/woocommerce/includes/admin/settings/views/html-admin-page-shipping-zone-methods.php
> +				<td id="wc-shipping-zone-region-picker-root" data-options='<?php echo wp_json_encode( $options ); ?>' data-values='<?php echo wp_json_encode( $locations ); ?>'/>
Once the above suggested code placement in `WC_Settings_Shipping::zone_methods_screen` is done, `options` and `locations` can be localized to `shippingZoneMethodsLocalizeScript` object, using 
```		
wp_localize_script(
   'wc-shipping-zone-methods',
	'shippingZoneMethodsLocalizeScript',
....
```
 in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/settings/class-wc-settings-shipping.php#L281-L301

2023-09-21 22:49 UTC, psealock commented
Thanks for the suggestions @samnajian !

I localized `options` and `locations`. Thats a much better way of doing it. I had to add an extra parameter to `WCAdminAssets::register_script` to handle extra dependencies outside of the ones generated by Webpack.

> It's not allowing selection of a main stem if it has sub-trees

This is a known issue mentioned above. [The fix has been merged](https://github.com/woocommerce/woocommerce/pull/40301) and I've rebased to include it in this branch. Selecting parent options should now function appropriately. Thanks!!

2023-09-22 09:33 UTC, samnajian commented
@psealock Thanks for the fixes, the root (`Select all countries`) is still not persisting ![1PrgO4.gif](https://github.com/woocommerce/woocommerce/assets/789421/b2985a07-9f8d-4031-8447-c95bc73ceed7)

2023-09-25 22:56 UTC, psealock commented
>@psealock Thanks for the fixes, the root (Select all countries) is still not persisting

Thanks for the review @samnajian and spotting this bug! This is related to the `TreeSelectControl` component and I've handled this bug in a separate PR to that component, @psealock Thanks for the fixes, the root (Select all countries) is still not persisting

https://github.com/woocommerce/woocommerce/pull/40422

2023-09-27 02:27 UTC, adrianduffell commented
Nice work on this @psealock !

> When typing to filter options, once an option is selected, the filtering text goes away and the view of options changes. This can be annoying if you'd like to select, say, several Mexican states and use the "Mexico" string to filter. You'd have to re-enter the filter string every time. Possibly, I can change the component such that the view of options doesn't change. I'm open to suggestions on this one.

I noticed this when filtering for "Australia". For this country, merchants would probably want to divide the states into different zones, so I think it would be helpful to keep the filtered view to allow a quick selection of several states. I could see it being a good follow-up improvement. Do you see any drawbacks to it?

2023-09-27 03:41 UTC, psealock commented
>Do you see any drawbacks to it?

Thanks for the review @adrianduffell. I think its a great idea and I'd like to tackle it as a 
follow up. Here is an issue to track: https://github.com/woocommerce/woocommerce/issues/40451

2023-09-27 03:44 UTC, psealock commented
>@psealock Thanks for the fixes, the root (Select all countries) is still not persisting

This is now fixed in https://github.com/woocommerce/woocommerce/pull/40422 and included in this branch

2023-09-27 04:56 UTC, chihsuan approved these changes
Great work! Confirmed the Region Picker is working as expected. LGTM. 🚢

2023-09-27 07:30 UTC, samnajian approved these changes
LGTM, thanks for the fixes @psealock.

2023-09-27 07:33 UTC, adrianduffell approved these changes
LGTM! 🚀 

Noting some unexpected changes (89 files touched) but I think it is due to the feature branch being a little behind?

2023-09-27 19:48 UTC, psealock commented
>Noting some unexpected changes (89 files touched) but I think it is due to the feature branch being a little behind?

Indeed, I've brought the base branch up to speed and changed files is now at 8.

Thanks for the review @adrianduffell @chihsuan @samnajian 

Note that e2e tests are failing because the change of HTML markup is affecting Playwright selectors. Since this is going into the feature branch, I will handle this separately. Issue to track: https://github.com/woocommerce/woocommerce/issues/40474

2023-09-27 19:49 UTC, merged