Check for empty value in get_order_id_by_order_key() #40055
woocommerce/woocommerce pull request #40254
Opened 2023-09-18 17:32 UTC by masteradhoc

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:
Check for empty value in get_order_id_by_order_key()
This is especially necessary due to the function being able to call directly see https://github.com/woocommerce/woocommerce/issues/40055#issuecomment-1710260022

Reason is that with an empty variable the sql call gets prepared like this:
`SELECT post_id FROM wp_postmeta WHERE meta_key = '_order_key' AND meta_value = ''`

The issue author mentioned:
_I noticed a 3PD plugin wasn't checking for empty order key value before calling wc_get_order_id_by_order_key() which likely resulted in a slow query and made the site unresponsive. The site's postmeta table is considerably large._

Closes #40055 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

Codebase with PR
1. call function **get_order_id_by_order_key** with parameter $order_key (valid orderkey) -> should pass
2. call function **get_order_id_by_order_key** with _empty_ parameter $order_key (valid orderkey) -> should return 0 & query shouldnt run

Codebase with**out** PR
3. call function **get_order_id_by_order_key** with parameter $order_key (valid orderkey) -> should return empty & query runs with empty orderkey

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [x] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Check if $order_key is empty in get_order_id_by_order_key() before running the sql query

#### Comment 

</details>

2023-09-19 14:13 UTC, lsinger requested changes
Thank you so much for your contribution, @masteradhoc! ☺️

Could we reverse the flow here to exit early in the non-happy path, and also add a warning? 

As in -- if the order key is empty, print a warning using `_doing_it_wrong( __FUNCTION__, __( '$order_key is empty.', 'woocommerce' ), '8.2.0 )`, and then return `0`. 

The normal case / happy path of returning the query results would then come after that. 

Finally, this feels like a unit test could be a good way to assure this behavior. Please let me know if you need any help writing one.

2024-05-17 14:13 UTC, barryhughes commented
Please feel free to re-request review once any feedback is addressed and you are happy for us to take another look :-)

2024-06-04 10:39 UTC, vedanshujain reviewed
This looks good, can you please rebase this branch with the latest trunk so that CI passes (additionally please add a changelog). Thanks!

2024-06-04 10:39 UTC, vedanshujain commented on plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php
> +  		global $wpdb;
this should be the first line in the functin.

2024-06-07 07:56 UTC, vedanshujain reviewed
Seems like there are couple more things we need to address before it can be merged:
1. Please use tabs instead of spaces for indents as per repo's lint rules.
2. We also need a changelog, seems like the automated task is failing for some reason. but you can add one manually by using the ` pnpm --filter=./plugins/woocommerce changelog add` command or adding one in `woocommerce/plugins/woocommerce/changelog` folder.

2024-07-23 09:48 UTC, vedanshujain commented
Hey @masteradhoc , seems like we are still using spaces instead of tabs for indentation, which is failing the lint check. Would you be able to fix this? Otherwise this PR is good to merge.

2024-07-23 19:24 UTC, masteradhoc commented
> Hey @masteradhoc , seems like we are still using spaces instead of tabs for indentation, which is failing the lint check. Would you be able to fix this? Otherwise this PR is good to merge.

@vedanshujain done :)

2024-10-09 15:04 UTC, vedanshujain commented
(Waiting for CI pass) Note that I also checked how the function is being used in the extensions, the common pattern is to immediately pass the return value to a `if ( ! $order_id )` or a `wc_get_order` function so this should be safe backward compatibility wise.

2024-10-15 06:26 UTC, vedanshujain approved these changes
LGTM!

<img width="446" alt="Screenshot 2024-10-15 at 11 55 48 AM" src="https://github.com/user-attachments/assets/5c8d6345-05be-4816-bad2-6fa6e7b11220">

2024-10-15 06:32 UTC, merged