Escape the default "Thank you" text instead of the filtered message
woocommerce/woocommerce pull request #40353
Opened 2023-09-21 16:01 UTC by YordanSoares

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #40329 and #40352

### How to test the changes in this Pull Request:

1. Activate this code snippet in your site:

```php
add_filter('woocommerce_thankyou_order_received_text', 'wc_test_thank_you_link', 10, 2);
function wc_test_thank_you_link( $text, $order ) {
    $text .= '<p><a href="https://example.com">Click here</a></p>';
    return $text;
}
```
2. Place a new order and check the code displayed after "Thank you. Your order has been received.", which should look like this:

![image](https://github.com/woocommerce/woocommerce/assets/38109855/3c45a02a-93f5-45e9-b1cc-608f246d0aa6)

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Escape the default "Thank you" text instead of the filtered message

#### Comment 

</details>

2023-09-22 12:44 UTC, lsinger requested changes
Thanks @YordanSoares for your contribution! I left a comment for a linting directive we'll need. Could you also please bump the version of that template file to 8.3.0? 

For the future to lint changes:

```
cd plugins/woocommerce
pnpm lint:php:changes
```

This would then at least detect the need for the directive.

2023-09-22 12:44 UTC, lsinger commented on plugins/woocommerce/templates/checkout/order-received.php
> +	echo $message;
We'll need a linting directive before this line: 
```suggestion
	// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	echo $message;
```

2023-09-22 12:46 UTC, lsinger commented
@YordanSoares It seems running the changelog adder doesn't currently work from forks. Could you run, from the root of the repository, the following to add a changelog file? 

```
pnpm --filter=./plugins/woocommerce run changelog add
```

2023-09-22 15:10 UTC, YordanSoares commented
> @YordanSoares It seems running the changelog adder doesn't currently work from forks. Could you run, from the root of the repository, the following to add a changelog file?
> 
> ```
> pnpm --filter=./plugins/woocommerce run changelog add
> ```

@lsinger I tried to add this command, but it didn't work on my Windows environment:

![image](https://github.com/woocommerce/woocommerce/assets/38109855/84f2084c-d1ce-4a99-9069-dd6efef9c764)

I tried installing all the [prerequisites](https://github.com/woocommerce/woocommerce#prerequisites), but I haven't being able to run it with success, yet. Any ideas?

2023-09-24 08:41 UTC, YordanSoares commented
@lsinger it seems that @github-actions finally managed to log the change :)

2023-09-25 11:27 UTC, lsinger approved these changes
Thank you for making those changes, @YordanSoares! Looks good to me. 

It seems the CI checks aren't running -- I'll try to close and re-open this PR to trigger them again.

2023-09-25 12:41 UTC, merged