Add edit downloads modal
woocommerce/woocommerce pull request #40599
Opened 2023-10-04 16:52 UTC by octaedro

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-10-17 14:15 UTC, mdperez86 requested changes
Nice job @octaedro I left a small comment.

2023-10-17 14:15 UTC, mdperez86 commented on packages/js/product-editor/src/blocks/product-fields/downloads/edit-downloads-modal/style.scss
> +	&__buttons {
Between the content and the buttons should be 32px space. AkVNGImLgSqCObTQ3idVn7-fi-7001_309117

2023-10-17 14:15 UTC, mdperez86 commented on packages/js/product-editor/src/blocks/product-fields/downloads/edit.tsx
> +													const clonedDownload =
This is not necessary here since `download` is a plain object. In line `263` you can do `downloableItem={ { ...selectedDownload } }` instead. Also since the modal is in fact a form I would rather use `initialValue` instead of `downloableItem`.

2023-10-17 19:16 UTC, octaedro commented on packages/js/product-editor/src/blocks/product-fields/downloads/edit-downloads-modal/style.scss
> +	&__buttons {
Good eyes! There is another padding in the design that I also added in the commit [288c712](https://github.com/woocommerce/woocommerce/pull/40599/commits/288c712fb721d0c22562a9ac82a7dad1316ed023)

2023-10-17 19:16 UTC, octaedro commented on packages/js/product-editor/src/blocks/product-fields/downloads/edit.tsx
> +													const clonedDownload =
Good call! I changed it in the commit [64496c5](https://github.com/woocommerce/woocommerce/pull/40599/commits/64496c56fc9c772e0b94a8c57774eb8b567817a9)

2023-10-18 13:32 UTC, mdperez86 requested changes
Nice job @octaedro I found something that it was not described like that in the ACs. When copying the file url the modal automatically hides and it should not.

https://github.com/woocommerce/woocommerce/assets/13334210/5f85ccc5-52ed-49d0-b6c1-01f480e79b11

2023-10-19 15:08 UTC, mdperez86 approved these changes
Nice job @octaedro LGTM!!!

2023-10-19 15:09 UTC, merged