Fix badge size issue when a number larger than 3 digits is used
woocommerce/woocommerce pull request #40624
Opened 2023-10-05 22:27 UTC by moon0326

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #34015 .

This PR fixes badge size issue when a number larger than 3 digits is used.

Credit to @aezazs-multidots for the fix.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch.
2. Go to `WooCommerce -> Home`
3. Right click on the badge next to `Thigns to do next` and choose `Inspect`
4. Change the number to 9999
5. Confirm the badge expands.

![Screen Shot 2023-10-05 at 3 24 47 PM](https://github.com/woocommerce/woocommerce/assets/4723145/a72c4b2a-0769-4087-8018-5b6c8137f5a7)

Before:

![Screen Shot 2023-10-05 at 3 25 06 PM](https://github.com/woocommerce/woocommerce/assets/4723145/a0cd891b-843e-4f92-8ed5-49d8c480cfc8)

After:

![Screen Shot 2023-10-05 at 3 25 30 PM](https://github.com/woocommerce/woocommerce/assets/4723145/b29c499b-9f55-4f47-9258-e92a5a995b02)

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix badge size issue when a number larger than 3 digits is used.

#### Comment 

</details>

2023-10-06 08:15 UTC, chihsuan requested changes, later dismissed
Thanks for the fix! Just left a suggestion.

2023-10-06 08:15 UTC, chihsuan commented on packages/js/components/src/badge/style.scss
> +	height: auto;
```suggestion
    min-width: 32px;
    height: 28px;
```

It seems to cause the normal styling to be a bit different. 

![Screenshot 2023-10-06 at 16 10 18](https://github.com/woocommerce/woocommerce/assets/4344253/2592d2eb-3ab7-40c4-a8aa-4cafd3a6012b)

Fixed:
![Screenshot 2023-10-06 at 16 10 22](https://github.com/woocommerce/woocommerce/assets/4344253/9e6e34d0-47e4-4af2-bf0d-93bcbd7857bb)

2023-10-06 08:30 UTC, rjchow approved these changes
Chi's suggestion looks good!

2023-10-11 01:01 UTC, psealock approved these changes
Works well, thanks @moon0326 🚀

2023-10-17 19:30 UTC, merged