Adds documentation for useful functions
woocommerce/woocommerce pull request #40771
Opened 2023-10-13 17:02 UTC by ibndawood

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Migrates the documentation from https://woocommerce.com/document/useful-functions/ into the `docs` folder. I've also added a lot of helpful core functions to the document.

### How to test the changes in this Pull Request:

Check that the content matches the documentation page and the links work.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-10-13 19:52 UTC, brentmackinnon approved these changes

2023-10-19 11:21 UTC, Konamiman requested changes
Hi @ibndawood, thanks for your contribution. Could you please:

1. Add a link to this new document in the `code-snippets/README.md` file.
2. Replace the bare URLs for wc_get_products and wc_get_orders with proper Markdown links e.g.: `[See arguments and usage](https://...)` (it's breaking our linter for Markdown otherwise)

Thank you!

2023-10-23 07:27 UTC, ibndawood commented
Thank you, @Konamiman, for taking the time to review my contribution. I've addressed your requested changes. Please take a look and let me know if there should be further changes.

2023-10-23 09:37 UTC, Konamiman approved these changes

2023-10-23 09:37 UTC, merged