Shipping Settings: Remove zone method defaults
woocommerce/woocommerce pull request #40838
Opened 2023-10-18 00:06 UTC by psealock

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fixes https://github.com/woocommerce/woocommerce/issues/40738

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add a new Shipping Zone `/wp-admin/admin.php?page=wc-settings&tab=shipping`
2. Add new Methods Free Shipping, Local Pickup, and Flate Rate
3. See defaults match TgDI6pJuBmnPyZ810B7uzX-fi
**Note - ** Selects don't have a placeholder in the [WooCommerce Settings API](https://github.com/woocommerce/woocommerce/blob/trunk/docs/extension-development/settings-api.md), so those will need to be the default selection instead.
4. Be sure to play around with the validation that enables/disables the create/save button

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-10-18 15:57 UTC, ilyasfoo requested changes
It seems like Flat rate default still has `0` as the cost:

<img width="611" alt="image" src="https://github.com/woocommerce/woocommerce/assets/3747241/5a1bfa3f-3608-4be4-8a0d-dab305148dac">

Everything else tested well

2023-10-18 15:57 UTC, ilyasfoo commented on plugins/woocommerce/includes/admin/settings/views/html-admin-page-shipping-zone-methods.php
> +						<button id="btn-ok" data-status='{{ data.status }}' disable='{{ data.status === "new" ? "disabled" : "" }}' class="button button-primary button-large {{ data.status === 'new' ? 'disabled' : ''
Typo perhaps, it seems like you can still click on `Create` despite it looks like disabled.

```suggestion
						<button id="btn-ok" data-status='{{ data.status }}' disabled='{{ data.status === "new" ? "disabled" : "" }}' class="button button-primary button-large {{ data.status === 'new' ? 'disabled' : '' }}">
```

2023-10-18 22:12 UTC, psealock commented
Thanks for the review @ilyasfoo 

Indeed, the default is `0` - Here is the design for reference. I'm handling currency symbols and formatting separately in https://github.com/woocommerce/woocommerce/pull/40816

<img width="514" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/c94d1b61-912f-4f82-86b6-daee5a9c8542">

2023-10-18 22:42 UTC, psealock commented on plugins/woocommerce/includes/admin/settings/views/html-admin-page-shipping-zone-methods.php
> +						<button id="btn-ok" data-status='{{ data.status }}' disable='{{ data.status === "new" ? "disabled" : "" }}' class="button button-primary button-large {{ data.status === 'new' ? 'disabled' : ''
Whoops, nice catch

2023-10-19 02:45 UTC, ilyasfoo approved these changes
> Indeed, the default is 0 - Here is the design for reference. I'm handling currency symbols and formatting separately in https://github.com/woocommerce/woocommerce/pull/40816

Ah, gotcha. The color in design looked a bit grey-ish, I thought it was meant as a placeholder instead of a default value.

In that case, LGTM! 🚢

2023-10-19 17:31 UTC, moon0326 approved these changes
LGTM and tested well 👍 🚀

2023-10-19 18:17 UTC, merged