Allow for $item_name filtering
woocommerce/woocommerce pull request #40969
Opened 2023-10-24 10:22 UTC by BusinessBloomer

### Changes proposed in this Pull Request:

$item_name is not filterable under /woocommerce/includes/admin/meta-boxes/views/html-order-item.php, while it is filterable in other files

For example, if I use this PHP:

```
add_filter( 'woocommerce_order_item_name', 'bbloomer_rename_variation_name_cart', 9999 );

function bbloomer_rename_variation_name_cart( $html ) {
	if ( strpos( $html, ' - ' ) !== false ) {
		$html = str_replace(
			[ "Yellow", "Green" ],
			[ "Test 1", "Test 3" ],
			$html
		);
	}
	return $html;
}
```

... the item name is correctly filtered inside emails, thank you page, single customer order view page, BUT it's not filtered in the admin edit single order page. This little edit should do the trick

#### Type

-   [ ] Tweak - A minor adjustment to the codebase

#### Message 

I've only edited /woocommerce/includes/admin/meta-boxes/views/html-order-item.php file with 1 new line and 3 replacements

2023-10-25 11:58 UTC, lsinger requested changes
Thank you @BusinessBloomer for your contribution. I found two issues in the code and left comments there. 

Apart from that the fact that you've made these changes on your own `trunk` branch proves to be problematic for our tooling around change log file generation, which expects changes to come from a feature branch. 

Ideally this wouldn't be an issue, but for the time being please recreate your pull request under a feature branch in your fork, something like `update/item-name-filtering-order-item`. 

When running `pnpm lint:php:changes:branch` against your changes, the linter also complains that the filter isn't documented properly: 

```
FILE: plugins/woocommerce/includes/admin/meta-boxes/views/html-order-item.php
-----------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 0 WARNINGS AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------
 16 | ERROR | A hook was found, but was not accompanied by a docblock comment on the line above to clarify the meaning of the hook. (WooCommerce.Commenting.CommentHooks.MissingHookComment)
-----------------------------------------------------------------------------------------------```

Of course that's the case for other instances of this filter in the code base as well, but the linter is only checking whether _changes_ comply to its rules. This way the code base and its documentation improve slowly but steadily. 

Please add a comment before your call to `apply_filters` similar to this: 

```
/**
 * Filter an order item's displayed name.
 *
 * @since 8.4.0
 * @param string $item_name The order item's name.
 * @param WC_Order_Item $item The order item itself.
 * @param bool $is_visible Whether the item refers to product that is visible in the catalog.
 */
```

2023-10-25 11:58 UTC, lsinger commented on plugins/woocommerce/includes/admin/meta-boxes/views/html-order-item.php
> +		echo $product_link ? '<a href="' . esc_url( $product_link ) . '" class="wc-order-item-name">' . wp_kses_post( $item_name() ) . '</a>' : '<div class="wc-order-item-name">' . wp_kses_post( $item_name
Need to remove the parentheses here: 

```suggestion
		echo $product_link ? '<a href="' . esc_url( $product_link ) . '" class="wc-order-item-name">' . wp_kses_post( $item_name ) . '</a>' : '<div class="wc-order-item-name">' . wp_kses_post( $item_name ) . '</div>';
```

2023-10-25 11:58 UTC, lsinger commented on plugins/woocommerce/includes/admin/meta-boxes/views/html-order-item.php
> +$item_name    = apply_filters( 'woocommerce_order_item_name', $item->get_name(), $item, $is_visible );
`$is_visible` does not seem to be defined here -- you probably need to add that:

`$is_visible = $product && $product->is_visible();`

2023-10-25 12:08 UTC, BusinessBloomer commented
Thank you, this is my first ever pull request so I'm learning now what I should've done. I'll see what I can do and sorry for not double checking those code errors/typos!

2023-10-25 12:15 UTC, lsinger commented
> Thank you, this is my first ever pull request so I'm learning now what I should've done. I'll see what I can do and sorry for not double checking those code errors/typos!

No worries, that's what reviews are for. ☺️ Congrats on opening your first PR!

2023-10-26 08:04 UTC, BusinessBloomer commented
I'm closing this PR and doing a new one. Thanks for your help!

2023-10-26 08:04 UTC, closed without merging