Use ' instead of backspace for escaping in csv export
woocommerce/woocommerce pull request #41163
Opened 2023-11-01 15:58 UTC by elazzabi

### Changes proposed in this Pull Request:

Closes https://github.com/Automattic/woocommerce-payments/issues/7307

When exporting data to a CSV file, some of the data may start with '=', '+', '-' or '@', which are considered potential chars for SQL injection. Thus, we are escaping those with a `\t` currently. However, the `\t` escaping is:
1. Not the current recommendation for escaping according to [OWASP](https://owasp.org/www-community/attacks/CSV_Injection). Having a `'` is the recommendation.
2. Not in line with what we have in [Core](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php#L374) and what is linked in the comments. We are also using `'` in Core.
3. The `\t` is problematic in some softwares like Excel and Google Sheets (as reported in this issue https://github.com/Automattic/woocommerce-payments/issues/7307)

### How to test the changes in this Pull Request:

Testing is done via unit tests.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-11-14 12:08 UTC, lsinger requested changes
Thank you for your contribution! ☺️ 

I left a question about additional characters and a request to correct the changelog file.

2023-11-14 12:08 UTC, lsinger commented on packages/js/csv-export/changelog/add-change-csv-export-escape-char
> +Use single quote instead of backspace for escaping in CSV exports.
```suggestion
Use single quote instead of tab for escaping in CSV exports.
```

2023-11-14 12:08 UTC, lsinger commented on packages/js/csv-export/src/test/index.ts
> +	it( 'should prefix single quote character when the cell value starts with one of =, +, -, and @', () => {
[The OWASP guideline](https://owasp.org/www-community/attacks/CSV_Injection) also mentions `tab (0x09)` and
`carriage return (0x0D)` as characters to avoid having a cell start with. Would it make sense to add these? 

In JavaScript, we'd get those like this: 
- `String.fromCharCode(0x09)`
- `String.fromCharCode(0x0D)`

2023-11-15 07:20 UTC, anu-rock commented on packages/js/csv-export/changelog/add-change-csv-export-escape-char
> +Use single quote instead of backspace for escaping in CSV exports.
Nice catch! Fixed in https://github.com/woocommerce/woocommerce/pull/41163/commits/b68e857c971f35d475eebeee4a8195f16c05e825

2023-11-15 07:20 UTC, anu-rock commented on packages/js/csv-export/src/test/index.ts
> +	it( 'should prefix single quote character when the cell value starts with one of =, +, -, and @', () => {
Another good catch! Fixed in https://github.com/woocommerce/woocommerce/pull/41163/commits/ffbc1a9bf6be2d6f8faa5ab6ee9bfdb5151a060f.

2023-11-15 08:49 UTC, lsinger approved these changes
Thank you @anu-rock for addressing my review comments. This looks good to me. Unfortunately the e2e tests have been failing. It seems like that's for an unrelated reason, possibly flakiness. I've restarted the tests, for now let's merge this only once all the checks are passing.

2023-11-15 09:29 UTC, merged