Try/log search
woocommerce/woocommerce pull request #41353
Opened 2023-11-10 06:48 UTC by coreymckrill

### Changes proposed in this Pull Request:

TBD

Fixes #41257

### How to test the changes in this Pull Request:

1. TBD

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-11-27 09:54 UTC, jorgeatorres requested changes
Hi @coreymckrill!

Good job on this one and the new logging implementation in general. Things are looking really good!
I left some comments, though nothing too serious.

I did have a question, though not something that we necessarily need to address in this PR (or even at all). When searching, my gut says that most of the time you'd like to see most recent results first instead of first to last. Would you consider filing an enhancement to make that either configurable or default behavior in the future?

I guess it can be tricky to read files bottom to top in a memory efficient way, and you can always refine the search terms to obtain better results, but thought I'd mention it anyways.

2023-11-27 09:54 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Admin/Logging/PageController.php
> +					'option'  => get_class( $list_table )::PER_PAGE_USER_OPTION_KEY,
I believe the `get_class()` here doesn't add much and probably reduces readability. You can access the constants directly with `$this->file_controller::SEARCH_MAX_RESULTS`, as you already do in different places.

2023-11-27 09:54 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Admin/Logging/PageController.php
> +				<?php if ( $file_count >= get_class( $this->file_controller )::SEARCH_MAX_FILES ) : ?>
`get_class()`.

2023-11-27 09:54 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Admin/Logging/PageController.php
> +							esc_html( number_format_i18n( get_class( $this->file_controller )::SEARCH_MAX_FILES ) )
`get_class()`.

2023-11-27 09:54 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Admin/Logging/FileV2/SearchListTable.php
> +		if ( $total_items > get_class( $this->file_controller )::SEARCH_MAX_RESULTS ) {
`get_class()`.

2023-11-27 09:54 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Admin/Logging/FileV2/SearchListTable.php
> +					esc_html( number_format_i18n( get_class( $this->file_controller )::SEARCH_MAX_RESULTS ) )
`get_class()`.

2023-11-27 09:54 UTC, jorgeatorres commented on plugins/woocommerce/src/Internal/Admin/Logging/FileV2/FileController.php
> +						break 2;
When we `break 2` here, the `$file->close_stream()` below doesn't get executed, which isn't truly a problem, but might be worth adding that just to keep things tidy.

2023-11-28 00:31 UTC, coreymckrill commented on plugins/woocommerce/src/Internal/Admin/Logging/PageController.php
> +					'option'  => get_class( $list_table )::PER_PAGE_USER_OPTION_KEY,
Good call. I feel like I tried it the more direct way, but my IDE protested, so I just used `get_class`. My IDE seems fine with it now, though, so updated: 99e2c0e562ad803dd8477693698d024cb41d5680

2023-11-28 00:31 UTC, coreymckrill commented on plugins/woocommerce/src/Internal/Admin/Logging/PageController.php
> +				<?php if ( $file_count >= get_class( $this->file_controller )::SEARCH_MAX_FILES ) : ?>
99e2c0e562ad803dd8477693698d024cb41d5680

2023-11-28 00:31 UTC, coreymckrill commented on plugins/woocommerce/src/Internal/Admin/Logging/PageController.php
> +							esc_html( number_format_i18n( get_class( $this->file_controller )::SEARCH_MAX_FILES ) )
99e2c0e562ad803dd8477693698d024cb41d5680

2023-11-28 00:31 UTC, coreymckrill commented on plugins/woocommerce/src/Internal/Admin/Logging/FileV2/SearchListTable.php
> +		if ( $total_items > get_class( $this->file_controller )::SEARCH_MAX_RESULTS ) {
99e2c0e562ad803dd8477693698d024cb41d5680

2023-11-28 00:32 UTC, coreymckrill commented on plugins/woocommerce/src/Internal/Admin/Logging/FileV2/SearchListTable.php
> +					esc_html( number_format_i18n( get_class( $this->file_controller )::SEARCH_MAX_RESULTS ) )
99e2c0e562ad803dd8477693698d024cb41d5680

2023-11-28 00:37 UTC, coreymckrill commented on plugins/woocommerce/src/Internal/Admin/Logging/FileV2/FileController.php
> +						break 2;
Yeah, the File class also does a `close_stream` in the `__destruct` magic method, but you're right that it's worth keeping things tidy: 280022cb7518b110f44b464eb091c7fa51ff4d6b

2023-11-28 00:55 UTC, coreymckrill commented
@jorgeatorres Thanks for the review!

> When searching, my gut says that most of the time you'd like to see most recent results first instead of first to last. Would you consider filing an enhancement to make that either configurable or default behavior in the future?

You could be right about this, although I can definitely see the argument for the "earliest to latest" order as well. Along the lines of what you mention, I suspect that reading the files from bottom to top would be tricky, since as far as I know none of the native PHP filesystem functions really support this.

One thing we might be able to do, in a later PR overhauling the log handler class itself (I've already started on it!), is have a configurable option so that the files themselves could be written by prepending new lines to the top rather than appending them to the bottom. That way, these search results would naturally be ordered with the most recent results first.

2023-11-29 14:52 UTC, jorgeatorres approved these changes
LGTM 💯

2023-11-29 14:52 UTC, merged