Fix product variation sale_price_dates_to not being set to 23:59:59 when it's set via the variation bulk actions
woocommerce/woocommerce pull request #41564
Opened 2023-11-19 02:51 UTC by mino129

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Since WooCommerce sets the sale end date hour to 23:59:59 for a given date on the Metabox UI for simple and variable products this should also happen when it's set via the bulk action editor for variations.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to the product editor on the Product data part
2. Create a variable product, set attributes and create variations.
3. In the Bulk Actions select "Set scheduled sale dates". Set for example the starting date to "2023-11-01" and the end date to "2023-11-30".
<img width="397" alt="Screenshot 2023-11-19 at 02 49 24" src="https://github.com/woocommerce/woocommerce/assets/43281889/9a0f4f95-c374-42cb-b871-b717ad481964">
<img width="448" alt="Screenshot 2023-11-19 at 02 49 54" src="https://github.com/woocommerce/woocommerce/assets/43281889/342f25a2-2e28-436e-b587-73d0062b5e3d">
<img width="451" alt="Screenshot 2023-11-19 at 02 50 29" src="https://github.com/woocommerce/woocommerce/assets/43281889/33dc8a0c-bdcb-41b4-b515-4c9f56cfca72">

4. In the post_meta table the meta_key `_sale_price_dates_to` should be set to `1701388799` indicating the end of the sale is set to `Thu Nov 30 2023 23:59:59`. If the fix in this commit is not applied the meta_key `_sale_price_dates_to` will be set to `1701302400` indicating the end of the sale is `Thu Nov 30 2023 00:00:00` which is incorrect and incoherent to the rest of the WooCommerce behaviours.
 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message
Fix product variation sale_price_dates_to not being set to 23:59:59 when it's set via the variation bulk actions

</details>

2023-11-21 16:00 UTC, mino129 commented
added another commit to make the function coherent with the rest of the codebase and added the missing changelog file. sorry if adding the commit this late adds any inconvenience on your side!

2023-11-23 16:09 UTC, jorgeatorres requested changes
Hi @mino129!

Thanks for your contribution. Overall, this looks good, but [there are a few code standards violations that need to be addressed first](https://github.com/woocommerce/woocommerce/actions/runs/6946409270/job/18970217535?pr=41564#step:4:23).

```
FILE: plugins/woocommerce/includes/class-wc-ajax.php
-----------------------------------------------------------------------------------------------
FOUND 2 ERRORS AND 0 WARNINGS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------
 2723 | ERROR | Spaces must be used for mid-line alignment; tabs are not allowed (WordPress.WhiteSpace.DisallowInlineTabs.NonIndentTabsUsed)
 2723 | ERROR | Whitespace found at end of line (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
-----------------------------------------------------------------------------------------------
```

Thanks again!

2023-11-23 20:58 UTC, mino129 commented
Hey @jorgeatorres ,

Thanks for the feedback!

I've gone ahead and fixed the code standards violations. Should be fine now!

If anything else needs to be changed please let me know.

Thank you for your work :)

2023-11-30 14:54 UTC, jorgeatorres approved these changes
LGTM. Thank you for your contribution @mino129!

2023-11-30 14:54 UTC, merged