Create woocommerce-plugin-api-callback.md
woocommerce/woocommerce pull request #41588
Opened 2023-11-20 16:44 UTC by brentmackinnon

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

 Create woocommerce-plugin-api-callback.md - migrated from wccom. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-11-21 09:44 UTC, lsinger requested changes
Thanks for working on this! I did leave a few comments with changes we should make.

2023-11-21 09:44 UTC, lsinger commented on docs/extension-development/woocommerce-plugin-api-callback.md
> +This document provides a detailed guide on how to use the WooCommerce Plugin API to initiate callbacks for plugin actions, especially for gateways and classes not initialized by default.
It's really very barebones in my opinion, so let's at least remove the "detailed" claim here. 

```suggestion
This document provides a guide on how to use the WooCommerce Plugin API to initiate callbacks for plugin actions, especially for gateways and classes not initialized by default.
```

2023-11-21 09:44 UTC, lsinger commented on docs/extension-development/woocommerce-plugin-api-callback.md
> +```php
This is not PHP, it's a URL -- we should put it into single quotes like so:

`https://...`

Putting it onto its own line seems fine here.

2023-11-21 09:44 UTC, lsinger commented on docs/extension-development/woocommerce-plugin-api-callback.md
> +```php
See above -- this is a URL, not PHP code.

2023-11-21 09:44 UTC, lsinger commented on docs/extension-development/woocommerce-plugin-api-callback.md
> +http://yoursite.com/?wc-api=CALLBACK
The `example.com` and `example.org` domains exist for specifically this purpose. Let's use them. Also, using HTTPS is a nicer default. 

```suggestion
https://example.com/?wc-api=CALLBACK
```

2023-11-21 09:44 UTC, lsinger commented on docs/extension-development/woocommerce-plugin-api-callback.md
> +http://yoursite.com/wc-api/CALLBACK/
See above. 

```suggestion
https://example.com/wc-api/CALLBACK/
```

2023-11-21 23:27 UTC, brentmackinnon commented
awesome thanks @lsinger! I've made those adjustments.

2023-11-24 09:02 UTC, lsinger approved these changes
Thank you for addressing my comments, @brentmackinnon. This looks good to go. 👍

2023-11-24 09:03 UTC, merged

2023-11-24 09:09 UTC, lsinger commented
@brentmackinnon in the spirit of friendly, constructive feedback, it would be nice if in the future you could ...

- edit the default commit messages that GitHub provides ("Update FILENAME") to something more meaningful ("use example.com instead of yoursite.com" or "tweak the wording in the opening paragraph")
- do the same with the PR title (which will end up in the repo commit history) -- I've renamed it to "Add plugin API callback documentation" from "Create woocommerce-plugin-api-callback.md"
- use the "re-request review" button when a PR is ready for another round of reviews -- that way your PR will show up in [your reviewer's review queue](https://github.com/pulls/review-requested), which will make it less likely that they will miss it:

![Screenshot 2023-11-24 at 09 59 48](https://github.com/woocommerce/woocommerce/assets/23619/e593cc9f-0870-4ba3-addf-faa263321238)

I know I'm dropping a lot of stuff here but again, my intention is purely kind and helpful. ☺️

Thanks for driving us all to make our documentation better!