Fix category title and add post_title to docs manifest
woocommerce/woocommerce pull request #41715
Opened 2023-11-27 19:03 UTC by rrennick

### Changes proposed in this Pull Request:

This PR 

- Fixes the category title generation to consistently use the name off the folder the `.md` is in. The gray-matter tool does not populate a `category_title` property. The category title was only being included for folders that did not have a `README.md`. 
- Adds support for multi-word category slugs.
- Adds a fallback post title of the first H1 encountered in the `.md` file when gray-matter does not populate it.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. In the root of the repository run `pnpm --filter=monorepo-utils build`
2. Run `pnpm utils md-docs docs woocommerce`
3. Compare `manifest.json` in the root of the repo to the sample manifest.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-12-01 03:28 UTC, rrennick commented
@JackBiggin This is ready for review. I edited the PR description to reflect the changes I've made as a result of our findings from ingesting the manifest.

2023-12-06 20:59 UTC, JacklynBiggin requested changes
Thanks for this, @rrennick!

- Ran testing instructions - manifest generated as expected with the correct titles
- Tried importing the newly generated manifest into the docs site, and this went smoothly. Posts updated as expected, and post titles are no longer duplicated.

The category creation seems to have a slight issue - the manifest importer is creating multiple `— _media` (I think it's creating new ones every time the importer runs). These categories are also showing up on the manifest without any posts in them. Once that's fixed, I think this is good to go! 

![CleanShot 2023-12-06 at 15 56 27@2x](https://github.com/woocommerce/woocommerce/assets/3846331/be176c73-c385-44f6-9bff-f61edb631575)

2023-12-07 15:18 UTC, JacklynBiggin commented
Chatted to Ron the issue in my previous comment. My understanding is that we're not planning on importing media from the monorepo for the initial docs site launch. Ron suggested solving this through implementing #41747 then ignoring the `— _media` folder, and I agree with this approach.

2023-12-07 17:46 UTC, JacklynBiggin approved these changes

2023-12-07 17:50 UTC, merged