Create image-sizes.md
woocommerce/woocommerce pull request #41722
Opened 2023-11-27 20:51 UTC by brentmackinnon

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

migrates image sizing doc from woo.com

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. this is a standalonw markdown file that shouldn't affect any other code, and should only be at risk of failing linting. 
2. make sure the doc looks alright before merging.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-11-29 12:18 UTC, lsinger requested changes
I think this PR is a good opportunity to also move over the Wiki page about thumbnail regeneration over to the docs folder. The current version of the image sizing article links to the Wiki article, and as we want to move those articles over anyway, we shouldn't introduce links to it now that we will soon have to fix.

2023-11-29 14:12 UTC, brentmackinnon commented
great catch, leif! thank you.

2023-12-15 14:42 UTC, brentmackinnon commented
@lsinger I think this one is ready for you to take another look.

2023-12-18 12:00 UTC, lsinger commented
> @lsinger I think this one is ready for you to take another look.

Thanks for the heads up, @brentmackinnon. In the future, ideally (also) use the "re-request review" button to ensure the PR comes up in my [list of PRs to review](https://github.com/pulls/review-requested): 

![Screenshot 2023-12-18 at 12 59 24](https://github.com/woocommerce/woocommerce/assets/23619/d1448c29-a9d5-4054-9cf5-e811f94e4b3d)

(No need to do that now with this PR.)

2023-12-18 12:04 UTC, lsinger commented on docs/theme-development/image-sizes.md
> +The customizer houses the options which control thumbnails in WooCommerce. ![Settings in the customizer](https://woocommerce.files.wordpress.com/2017/12/imagefeature.png?w=712) If the theme is declar
I'm not sure if an absolute link to `/docs/...md` will work once the markdown has been converted and published on the site. Pinging @rrennick for his expertise here -- is this the way to link between documents and if now, which way is?

2023-12-18 12:11 UTC, lsinger commented
Closing and re-opening PR to see if that helps the Playwright E2E test checks get started: 

![Screenshot 2023-12-18 at 13 11 12](https://github.com/woocommerce/woocommerce/assets/23619/a4cb0efc-7511-4793-95e2-3104f24254e6)

2023-12-18 12:50 UTC, merged