add composer install to package prepare script
woocommerce/woocommerce pull request #42839
Opened 2023-12-14 18:14 UTC by rrennick

### Changes proposed in this Pull Request:

`Turbo` used to automatically run composer install. With the switch to `wireit`, the prepare command fils due to composer install not being run. This PR adds `composer install` before running the changelogger scipt.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Run `../../../tools/package-release/bin/dev prepare @woocommerce/create-product-editor-block` from the `packages/js/create-product-editor-block` folder
2. Check the folder for the prepared files
```
# git status
On branch fix/package-prepare
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   CHANGELOG.md
	deleted:    changelog/update-create-prod-editor
	modified:   package.json
...
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2023-12-14 19:28 UTC, nathanss requested changes
It doesn't seem like the command is running in all scenarios it's supposed to. Here's my stack trace:


```
../../../tools/package-release/bin/dev prepare @woocommerce/create-product-editor-block
/bin/sh: ./vendor/bin/changelogger: No such file or directory
Error: Command failed: ./vendor/bin/changelogger validate
/bin/sh: ./vendor/bin/changelogger: No such file or directory

    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at validateChangelogEntries (/Users/nathan/git/woocommerce/tools/package-release/src/changelogger.ts:43:18)
    at /Users/nathan/git/woocommerce/tools/package-release/src/commands/prepare/index.ts:102:30
    at Array.forEach (<anonymous>)
    at PackagePrepare.preparePackages (/Users/nathan/git/woocommerce/tools/package-release/src/commands/prepare/index.ts:97:12)
    at PackagePrepare.run (/Users/nathan/git/woocommerce/tools/package-release/src/commands/prepare/index.ts:85:14)
    at async PackagePrepare._run (/Users/nathan/git/woocommerce/node_modules/.pnpm/@oclif+core@1.26.2/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/Users/nathan/git/woocommerce/node_modules/.pnpm/@oclif+core@1.26.2/node_modules/@oclif/core/lib/config/config.js:301:25) {
  status: 127,
  signal: null,
  output: [
    null,
    '',
    '/bin/sh: ./vendor/bin/changelogger: No such file or directory\n'
  ],
  pid: 92760,
  stdout: '',
  stderr: '/bin/sh: ./vendor/bin/changelogger: No such file or directory\n'
}
Preparing @woocommerce/create-product-editor-block... done
/Users/nathan/git/woocommerce/node_modules/.pnpm/@oclif+core@1.26.2/node_modules/@oclif/core/lib/errors/index.js:28
        err = new cli_2.CLIError(input, options);
              ^
CLIError: Command failed: ./vendor/bin/changelogger validate
/bin/sh: ./vendor/bin/changelogger: No such file or directory

    at Object.error (/Users/nathan/git/woocommerce/node_modules/.pnpm/@oclif+core@1.26.2/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at PackagePrepare.error (/Users/nathan/git/woocommerce/node_modules/.pnpm/@oclif+core@1.26.2/node_modules/@oclif/core/lib/command.js:103:23)
    at /Users/nathan/git/woocommerce/tools/package-release/src/commands/prepare/index.ts:128:11
    at Array.forEach (<anonymous>)
    at PackagePrepare.preparePackages (/Users/nathan/git/woocommerce/tools/package-release/src/commands/prepare/index.ts:97:12)
    at PackagePrepare.run (/Users/nathan/git/woocommerce/tools/package-release/src/commands/prepare/index.ts:85:14)
    at async PackagePrepare._run (/Users/nathan/git/woocommerce/node_modules/.pnpm/@oclif+core@1.26.2/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/Users/nathan/git/woocommerce/node_modules/.pnpm/@oclif+core@1.26.2/node_modules/@oclif/core/lib/config/config.js:301:25) {
  oclif: { exit: 2 },
  code: undefined
}
```

2023-12-14 19:46 UTC, rrennick commented
> It doesn't seem like the command is running in all scenarios it's supposed to. 

@nathanss I forgot to include build the tool in the instructions. I'll update the description.

2023-12-15 13:05 UTC, nathanss approved these changes

2023-12-15 13:05 UTC, nathanss commented
@rrennick Thanks for the clarification!

2023-12-15 15:08 UTC, merged