Fix for product meta lookup table incorrectly marking a product as onsale Closes #43008
woocommerce/woocommerce pull request #43011
Opened 2023-12-20 19:20 UTC by pintend

Determine if a product is on sale based on regular price, which is how its done in the WC_Product class https://github.com/woocommerce/woocommerce/blob/7122669d448acb90d0f8a7177b76baaccec2e76b/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1634

Currently `$product->is_on_sale() == false` when `_regular_price` and `_sale_price` are the same, but the product lookup table ignores the `_regular_price` and only checks that `_price` and `_sale_price` are the same.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/43008 .

### How to test the changes in this Pull Request:

Create a few products, set some on sale and set some with sale price the same as regular price

```sql
SELECT
    IF (
        CAST(meta1.meta_value AS DECIMAL) >= 0
        AND CAST(meta2.meta_value AS CHAR) != ''
        AND CAST(meta1.meta_value AS DECIMAL(10, 2)) = CAST(meta2.meta_value AS DECIMAL(10, 2))
        AND CAST(meta3.meta_value AS DECIMAL(10, 2)) > CAST(meta2.meta_value AS DECIMAL(10, 2))
    , 1, 0) AS new_on_sale,
    lookup_table.product_id,
    lookup_table.onsale,
    meta1.meta_value as _meta_price,
    meta2.meta_value as _meta_sale_price,
    meta3.meta_value as _meta_regular_price
FROM
    wp_wc_product_meta_lookup lookup_table
    LEFT JOIN wp_postmeta meta1 ON lookup_table.product_id = meta1.post_id AND meta1.meta_key = '_price'
    LEFT JOIN wp_postmeta meta2 ON lookup_table.product_id = meta2.post_id AND meta2.meta_key = '_sale_price'
    LEFT JOIN wp_postmeta meta3 ON lookup_table.product_id = meta3.post_id AND meta3.meta_key = '_regular_price'
```

you would see new_on_sale has the correct value and onsale has the value woocommerce set

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Use regular_price to determine if product is not sale and don't rely only on price for product_meta_lookup
#### Comment 

</details>

2024-01-08 11:57 UTC, jorgeatorres requested changes
Hi @pintend!

Thanks for your contribution 💯. I left some feedback regarding a tiny change that we would need to make in order for this to work as intended.

Let me know what you think!

2024-01-08 11:57 UTC, jorgeatorres commented on plugins/woocommerce/includes/wc-product-functions.php
> +							AND CAST( meta3.meta_value AS DECIMAL( 10, %d ) ) > CAST( meta2.meta_value AS DECIMAL( 10, %d ) )
We are adding two more placeholders (`%d`) with this change, so we need to add the corresponding variables (`$decimals`) to the `$wpdb->prepare()` call.

2024-01-09 06:28 UTC, pintend reviewed
did i miss that in the commit? i had it in my test query `AND CAST(meta3.meta_value AS DECIMAL(10, 2)) > CAST(meta2.meta_value AS DECIMAL(10, 2))`

2024-01-09 09:18 UTC, jorgeatorres commented
@pintend: You did use `DECIMAL(10, 2)~ in the testing instructions, but the code itself uses a placeholder for the decimal places (`%d`) which is correct, but then you need to provide the actual value.

https://github.com/woocommerce/woocommerce/blob/0fd0c8e9d406f178c9d1c3da2cfb5a3b63d1a290/plugins/woocommerce/includes/wc-product-functions.php#L1571-L1578

2024-02-13 22:50 UTC, jorgeatorres commented
Hey @pintend,

Thanks for making the changes. I was testing this again and now I'm wondering where the original bug came from. Using the `set_price()`, `set_regular_price()` and `set_sale_price()` functions I can't set a sale price that is equal to the price/regular price. In all cases, the `price` property updates to the proper amount, which is what the lookup table uses (as you mentioned).

We recently merged fixes related to product sales, so something might've changed.

Is there a way to reproduce this that doesn't involve changing the metadata directly in the database? This is not necessarily supported. Hardening the lookup update might still make sense, but I'd like to understand if there's something else we're missing.

2024-02-21 16:47 UTC, pintend commented
@jorgeatorres: The issue started when a 3rd party plugin created and updated product records directly in the db, although the issue _should_ really be fixed in that plugin (which I don't have control over) I don't see the harm "fixing" it here as well, especially when in the application this is the method it uses to determine if its on sale... might as well keep the logic consistent.

Although the functions dont allow a developer to create this issue, some developers might and do go around those helper functions. adding this extra check should be a safe change that protects from that even if its "useless" for most cases

> if the `sale_price` is not blank and `regular_price` is more than the `sale_price`
https://github.com/woocommerce/woocommerce/blob/7122669d448acb90d0f8a7177b76baaccec2e76b/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1634

> if the `sale_price` is not blank and the `price` and `sale_price` are equal 
https://github.com/woocommerce/woocommerce/blob/7122669d448acb90d0f8a7177b76baaccec2e76b/plugins/woocommerce/includes/wc-product-functions.php#L1572

my change:  
> if the `sale_price` is not blank and `regular_price` is more than the `sale_price` and the `price` and `sale_price` are equal
https://github.com/woocommerce/woocommerce/blob/7263053535bb5d5d46cdf05c82219ac3980cc56a/plugins/woocommerce/includes/wc-product-functions.php#L1574

it make it more consistent and prevents the issue from other plugins

2024-03-01 20:40 UTC, jorgeatorres approved these changes
LGTM. Thanks for your patience here @pintend and for this fix. It works great.

FYI I edited the first comment by adding some testing instructions to make it easier for our team to confirm this is working correctly.

2024-03-01 21:10 UTC, merged