[E2E] Tests for coupon usage restrictions
woocommerce/woocommerce pull request #43590
Opened 2024-01-12 22:45 UTC by lanej0

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # https://github.com/woocommerce/woocommerce-quality/issues/702

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. `pnpm env:start`
2. `pnpm test:e2e-pw shopper/checkout-coupons.spec.js`
3. Ensure CI passes

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-01-17 15:06 UTC, veljkho requested changes
Hi @lanej0, thanks for the great PR! 👍 

I left only one feedback about some leftover code.

Additionally, why don't we have any last total price check when we do apply or try to apply restricted coupons, just to be sure the total price is still without the applied coupon even if we get the proper message? Just like we did in the first test `describe( 'Checkout coupons'`, we have there both message and total price checks.

2024-01-17 15:06 UTC, veljkho commented on plugins/woocommerce/tests/e2e-pw/tests/shopper/checkout-coupons.spec.js
> +	test.beforeEach( async ( { page, context } ) => {
`page` is declared here but its value is never used.

2024-01-17 22:22 UTC, lanej0 commented on plugins/woocommerce/tests/e2e-pw/tests/shopper/checkout-coupons.spec.js
> +	test.beforeEach( async ( { page, context } ) => {
Thanks for catching that!  Fixed.

2024-01-19 09:47 UTC, veljkho approved these changes

2024-01-19 09:49 UTC, merged