Add e2e tests to verify block templates can be customized if the theme has its own custom templates
woocommerce/woocommerce pull request #43650
Opened 2024-01-15 12:47 UTC by Aljullu

### Changes proposed in this Pull Request:

This PR:

1. Creates a new Playwright test environment so we run tests in a block theme with custom templates.
2. In that environment, it adds a test for each template to verify they can be customized.
3. It updates some `package.json` scripts and some docs that were not up to date.
4. Removes `plugins/woocommerce-blocks/.github/workflows/playwright.yml`, as I understand, that file has been superseded by `.github/workflows/blocks-playwright.yml`.

Part of #43416.

### How to test the changes in this Pull Request:

Note: no need to test this for the release.

1. Verify e2e tests pass and there is a job specific for tests run in a block theme with templates.
2. Locally run `npm run test:e2e:side-effects`, `npm run test:e2e:side-effects:report`, `npm run test:e2e:classic-theme`, `npm run test:e2e:classic-theme:report`, `npm run test:e2e:block-theme-with-templates` and `npm run test:e2e:block-theme-with-templates:report` and verify all of them work (the report ones should open the report in your browser once finished).
3. Read the updated docs and verify they make sense.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment

Add e2e tests to verify block templates can be customized if the theme has its own custom templates.

</details>

2024-01-16 12:29 UTC, imanish003 requested changes
Thank you for adding E2E tests for the theme with custom templates 🙌🏻.

I've tested them locally and everything passed on my end. I've left a few minor suggestions in the review. Please feel free to overlook any nitpicks that don't resonate with you. However, there's one change regarding the “Hello World in the template” string that I believe is necessary.

Additionally, I'm not sure why, but when I run `npm run test:e2e:side-effects`, it seems to execute all tests, which is puzzling. Are you experiencing the same issue?

2024-01-16 12:29 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/mini-cart-template-part.block_theme_with_templates.spec.ts
> +const templateType = 'wp_template_part';
Nitpick: Would it be logical to encapsulate these three into a single object, considering they are all related to the template?

2024-01-16 12:29 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/product-catalog-template.block_theme_with_templates.spec.ts
> +} from '@woocommerce/e2e-utils';
It appears that cli and BLOCK_THEME_SLUG were not utilized in this file.

2024-01-16 12:29 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/product-catalog-template.block_theme_with_templates.spec.ts
> +		await page.goto( permalink );
Nitpick: It seems we're repeating the same code in multiple files, indicating it might be wise to develop a utility function.

- How about creating a new utility file within `plugins/woocommerce-blocks/tests/e2e/tests/templates`?
- Alternatively, we could develop a Page Object akin to `plugins/woocommerce-blocks/tests/e2e/tests/product-collection/product-collection.page.ts`.
- Or, perhaps this should be a global utility function?

IMO it would be more appropriate to create a local utility file in `plugins/woocommerce-blocks/tests/e2e/tests/templates`, unless we have strong reasons to believe it will be beneficial on a global scale.
What do you think?

2024-01-16 12:29 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/product-search-results-template.block_theme_with_templates.spec.ts
> +		).toHaveCount( 0 );
It seems that the text here differs from the intended text, 'Hello World in the theme template'. 🤔
Perhaps we should define a constant for this string to ensure consistency?

2024-01-16 12:29 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/product-search-results-template.block_theme_with_templates.spec.ts
> +		).toHaveCount( 0 );
It looks like this is the case for other files, too.

2024-01-16 12:29 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/products-by-category-template.block_theme_with_templates.spec.ts
I'm curious, could we possibly utilize [Parameterized tests](https://playwright.dev/docs/test-parameterize) instead of creating multiple files? It appears we are primarily altering some constants. 🤔

2024-01-16 12:29 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/README.md
Nitpick: Should we think about substituting "npm" with "pnpm" in the README.md file, given that PNPM is the recommended for Monorepo? 🤔

2024-01-16 12:29 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/README.md
> +_Note: All command parameters of `test:e2e` can be used for these commands too.
Thanks for updating the doc file as well 🙏🏻

2024-01-16 13:24 UTC, Aljullu commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/mini-cart-template-part.block_theme_with_templates.spec.ts
> +const templateType = 'wp_template_part';
Done in 4c253802d1c41e515a57fd4dfd9fad2510c455fb.

2024-01-16 13:24 UTC, Aljullu commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/product-catalog-template.block_theme_with_templates.spec.ts
> +} from '@woocommerce/e2e-utils';
Nice catch! Fixed in c17567365aabfe17f35b5ae091f0d56fe5ba5162.

2024-01-16 13:24 UTC, Aljullu commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/product-catalog-template.block_theme_with_templates.spec.ts
> +		await page.goto( permalink );
Are you referring to the three lines you commented or would you create additional utils for something else? In fact, `editorUtils.revertTemplateCustomizations()` is a util I created in a previous PR, but I intentional left `admin.visitAdminPage()` and `page.goto()` outside of the util, as it made more sense to me to keep navigation explicit in the test itself, so there is "less magic" done inside the util. I'm happy to reconsider it, though. What do you think? Another thing to keep in mind is that if we move to parameterized tests, there will be less repetition anyway. :slightly_smiling_face:

2024-01-16 13:24 UTC, Aljullu commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/product-search-results-template.block_theme_with_templates.spec.ts
> +		).toHaveCount( 0 );
Good idea, I changed it in all test files here: e2d99d33a4b4927ecc0707576493f4ef79731f9a.

2024-01-16 13:25 UTC, Aljullu commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/products-by-category-template.block_theme_with_templates.spec.ts
Good idea. I initially thought not to do it, as it made more sense to me to have one test file per template. :thinking:  But I just tried it and it's definitely much cleaner: 1adcad037208082a410cf261e55796dba33c11e1.

I will do the same for the other template tests in a separate PR, to avoid this one growing too much.

2024-01-16 13:25 UTC, Aljullu commented on plugins/woocommerce-blocks/tests/e2e/README.md
Good point, done in b4e7d9cbc5c1ef8047d5cc3896ed50e9b36a921e.

2024-01-16 13:35 UTC, Aljullu commented
Thanks for all the useful suggestions, @imanish003! I implemented most of the changes, so this is ready for another review.

2024-01-18 08:56 UTC, imanish003 approved these changes
Thank you so much for quickly making the changes. I've left one minor comment, but I'm pre-approving the PR. Everything else looks great 🚀

2024-01-18 08:56 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/mini-cart-template-part.block_theme.spec.ts
> +const userText = 'Hello World in the template part';
Nit: The userText variable is being duplicated.

2024-01-18 08:56 UTC, imanish003 commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/product-catalog-template.block_theme_with_templates.spec.ts
> +		await page.goto( permalink );
TBH I don't have a strong opinion on this. I noticed the repetition in the code and thought creating a utility function might be a good idea. We can name the utility function clearly to reflect its purpose.

Moreover, considering your point about transitioning to parameterized tests, it seems sensible to keep it as it is now 🙂

2024-01-18 10:12 UTC, Aljullu commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/mini-cart-template-part.block_theme.spec.ts
> +const userText = 'Hello World in the template part';
Good catch, removed in af23dd215af8ce24f7a243fe40f74981c51ede12.

2024-01-18 10:21 UTC, Aljullu commented on plugins/woocommerce-blocks/tests/e2e/tests/templates/product-catalog-template.block_theme_with_templates.spec.ts
> +		await page.goto( permalink );
Makes sense, thanks! I'm thinking to leave it as-is for now, however. I'm still planning to add some more tests related to templates in follow-up PRs, so I prefer to wait until we have more tests to see what makes sense being extracted into utilities, if that sounds ok.

2024-01-18 10:39 UTC, merged