Fix/42280 change address link in cart block
woocommerce/woocommerce pull request #43803
Opened 2024-01-18 21:09 UTC by tarunvijwani

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #42280.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-01-23 07:15 UTC, nielslange requested changes
Thanks for working on this, @tarunvijwani. I left a few comments and noticed one potential issue regarding _"default shipping zones"_.

2024-01-23 07:15 UTC, nielslange commented on plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx
> +		);
In the PR description, I see that you created the shipping zones `US` and `All`, but the shipping zone `Rest of the world` has no shipping methods. This function name here is called `hasMultipleAndDefaultZone`. Wouldn't the shipping zone `Rest of the world` reflect the default zone?

## Shipping zones `US` and `All`

<img width="1107" alt="Screenshot 2024-01-23 at 13 22 52" src="https://github.com/woocommerce/woocommerce/assets/3323310/1f704910-9057-478f-a13e-8edf184efc38">

<table>
  <tr>
    <td width="50%">Enable the shipping calculator on the cart page</td>
    <td width="25%">yes</td>
    <td width="25%">yes</td>
  </tr>
  <tr>
    <td>Hide shipping costs until an address is entered</td>
    <td>yes</td>
    <td>no</td>
  </tr>
  <tr>
    <td>Text within the shipping section</td>
    <td>Add an address for shipping options</td>
    <td><strong>Change address to view shipping options for your location</strong></td>
  </tr>
</table>

## Shipping zones `US` and `Rest of the world`

<img width="1103" alt="Screenshot 2024-01-23 at 13 23 39" src="https://github.com/woocommerce/woocommerce/assets/3323310/00cd1afe-e62a-4723-97ed-dbd7ad4090ba">

<table>
  <tr>
    <td width="60%">Enable the shipping calculator on the cart page</td>
    <td width="20%">yes</td>
    <td width="20%">yes</td>
  </tr>
  <tr>
    <td>Hide shipping costs until an address is entered</td>
    <td>yes</td>
    <td>no</td>
  </tr>
  <tr>
    <td>Text within the shipping section</td>
    <td>Add an address for shipping options</td>
    <td><strong>n/a</strong></td>
  </tr>
</table>

2024-01-23 07:15 UTC, nielslange commented on plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx
>  	// then the shipping calculator will be hidden to avoid confusion.
I'd change this part as follows:

```ts
// If there is no default customer location set in the store, 
// and the customer hasn't provided their address,
// and only one default shipping method is available for all locations, 
// then the shipping calculator will be hidden to avoid confusion.
```

I applied the following changes:
- Move each statement into a separate line
- Replace _"but only one"_ with _"and only one"_

2024-01-23 07:15 UTC, nielslange commented on plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx
> +		activeShippingZones.some(
These two lines show the TS error
```ts
'activeShippingZones' is of type 'unknown'.ts(18046)
```

In #4268, @mikejolley solved an identical TS error by creating 

```ts
type shippingAdminLink = {
	id: number;
	title: string;
	description: string;
};
```

and applying that type to the corresponding variable

```ts
const activeShippingZones = getSetting( 'activeShippingZones' ) as shippingAdminLink[];
```

2024-01-23 07:15 UTC, nielslange commented on plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx
> +		);
```suggestion
			( zone: { description: string } ) =>
				zone.description === 'Everywhere' ||
				zone.description === 'Locations outside all other zones'
		);
```

This code should solve the issue I mentioned before.

2024-01-23 07:15 UTC, nielslange commented on plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx
> +					label={ label }
Nicely done! 👏

2024-01-23 07:15 UTC, nielslange commented on plugins/woocommerce-blocks/assets/js/blocks/cart/inner-blocks/cart-order-summary-shipping/block.tsx
> +	// If there are no shipping rates, and we're in the editor, hide the shipping rates to match front-end.
I'd probably skip the comment here, as the if statement is pretty self-explaining.

2024-01-23 07:15 UTC, nielslange commented on plugins/woocommerce/changelog/43803-fix-42280-change-address-link-in-cart-block
> +- Hide the shipping calculator from the Cart editor when there is no default address and shipping zone.  - Display the change address link when there are multiple shipping zones available along with
This changelog message might appear in the release notes. I'd probably shorten it and avoid the use of dashes.

2024-01-23 14:12 UTC, tarunvijwani commented on plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx
> +		activeShippingZones.some(
Thank you, I fixed it. 🎉

2024-01-23 14:15 UTC, tarunvijwani commented on plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx
> +		);
Nice catch! Thank you, @nielslange, for covering that scenario.🙂

2024-01-23 14:50 UTC, tarunvijwani commented
@nielslange Thank you for the review. I have added all the suggested changes.

2024-01-24 05:28 UTC, nielslange commented
@tarunvijwani The testing steps 11. and 12. state:
> - Go to shipping settings at wp-admin/admin.php?page=wc-settings&tab=shipping&section=options
> - Enable the "Hide shipping costs until an address is entered" option.

When arriving at this point, I realised that the "Hide shipping costs until an address is entered" option should have been disabled before. I suggest adding a point in the early testing steps, maybe steps 3. and 4., to ensure that all preconditions for testing are met. Something like:
> - Go to shipping settings at wp-admin/admin.php?page=wc-settings&tab=shipping&section=options
> - Disable the "Hide shipping costs until an address is entered" option.

2024-01-24 05:53 UTC, nielslange reviewed
Step 4. states:
> - Confirm the "change address" link is not present in the Editor.

With ` Enable the shipping calculator on the cart page` being disabled on `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=options`, I'm seeing this

<table>
<tr>
<td valign="top">Cart block in page editor:
<br><br>
<img width="360" alt="Screenshot 2024-01-24 at 12 50 29" src="https://github.com/woocommerce/woocommerce/assets/3323310/fa4ee50c-63fe-4c3d-a18d-a8d79373b414">
</td>
<td valign="top">Checkout block in page editor:
<br><br>
<img width="350" alt="Screenshot 2024-01-24 at 12 51 33" src="https://github.com/woocommerce/woocommerce/assets/3323310/f313c4b7-0bb0-4c49-af50-b899702ce86f">
</td>
</tr>
</table>


I noticed that when `Hide shipping costs until an address is entered` is enabled, the `Calculate shipping for your location` link does not appear. I suggest adding all required pre-condition for testing, to avoid confusion.

2024-01-24 05:56 UTC, nielslange reviewed
The testing steps 5. and 6. state:
> - Add one shipping zone for the US with a free shipping option.
> - Add a flat rate shipping option for all shipping zones.

Based on https://github.com/woocommerce/woocommerce/pull/43803#discussion_r1462811860, what are your thoughts on extending the tests to also check for the default location? See also the screenshots I shared in https://github.com/woocommerce/woocommerce/pull/43803#discussion_r1462761071.

2024-01-24 07:54 UTC, nielslange commented
I noticed that when `Hide shipping costs until an address is entered` is enabled, the `Calculate shipping for your location` link does not appear. I suggest adding all required pre-condition for testing, to avoid confusion.

2024-01-24 10:44 UTC, tarunvijwani commented
@nielslange Sure, that's a good suggestion. I have updated the testing instructions.

2024-01-24 15:35 UTC, nielslange approved these changes
Thanks for working on this, @tarunvijwani. The PR works as expected and the code is in a great shape! Let's ⛴️ this improvement! 🙌

2024-01-24 15:35 UTC, nielslange commented on plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx
> +	);
Nice one! 👏

2024-01-24 15:35 UTC, nielslange commented on plugins/woocommerce/src/Blocks/Utils/CartCheckoutUtils.php
> +	}
Thanks for moving this one into a separate class. 👏

2024-01-24 16:40 UTC, merged