[e2e tests] Add new tests for up-sells and cross-sells
woocommerce/woocommerce pull request #44154
Opened 2024-01-29 15:41 UTC by adimoldovan

- Add tests skeleton
- Add up-sell test
- Add changelog

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-02-06 19:14 UTC, lanej0 requested changes
The viewport isn't an issue, more of a question.  I'm curious about creating a function to replace `page.goto` though -- we're definitely trying to stay away from replacing built-in Playwright functions with custom ones.

2024-02-06 19:14 UTC, lanej0 commented on plugins/woocommerce/tests/e2e-pw/playwright.config.js
> +		viewport: { width: 1280, height: 1600 },
While I don't think there's an issue with this, what was the driver for increasing the viewport size so much? Seems like an unlikely resolution that a user might use, which could lead to some false-negative test results... but maybe I'm overthinking it.

2024-02-06 19:14 UTC, lanej0 commented on plugins/woocommerce/tests/e2e-pw/tests/merchant/product-linked-producs.spec.js
> +		} );
Why did you choose to abstract this into a separate function instead of just inlining `page.goto` in the test?

2024-02-07 09:07 UTC, adimoldovan commented on plugins/woocommerce/tests/e2e-pw/tests/merchant/product-linked-producs.spec.js
> +		} );
There are two steps in that function, the `goto` and the click on the `Linked Products`, which are repeated in each test, so I extracted them into a function, the same way that I extracted the update product logic into `updateProduct` function.

2024-02-07 09:11 UTC, adimoldovan commented on plugins/woocommerce/tests/e2e-pw/playwright.config.js
> +		viewport: { width: 1280, height: 1600 },
I reverted the height in https://github.com/woocommerce/woocommerce/pull/44154/commits/fa6c18d646c8cc9806e9a6a4fa4a840b231a67fb.
It helped me when I ran tests locally to view all elements at once without needing to scroll. I should have reverted it before. 
I'm curious though to know your thoughts on the possible false-negative that could result from that.

2024-02-07 09:14 UTC, adimoldovan commented
Thanks @lanej0 for reviewing.

> I'm curious about creating a function to replace `page.goto` though -- we're definitely trying to stay away from replacing built-in Playwright functions with custom ones.

I think you misinterpreted this one. I did not replace Playwright's `page.goto` and I'm not trying to replace the build-in functions in any way. I was merely extracting some common code into a function. Those two steps are repeating in each of the 4 tests, it seems reasonable to me to extract it in a function.

2024-02-07 22:27 UTC, lanej0 commented on plugins/woocommerce/tests/e2e-pw/playwright.config.js
> +		viewport: { width: 1280, height: 1600 },
I don't really think it's an issue, but e2e tests are meant to mimic real-world testing.  Most people probably aren't browsing a site using a browser that's 1600 pixels tall.  In an extreme edge case, if there was some CSS limiting scrolling/the content shown, and the button you're supposed to click is cropped off screen... there could be an issue.  Not likely, scenario for sure.

2024-02-07 22:28 UTC, lanej0 approved these changes

2024-02-07 22:28 UTC, merged