Update deciding-pr-high-impact.md
woocommerce/woocommerce pull request #44205
Opened 2024-01-30 21:06 UTC by brentmackinnon

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Adjusts the language related to security fixes. 

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. read each changed line and ensure it's accurate and appropriate
2. doublecheck the new link to make sure it's correct. 
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-01-31 10:25 UTC, lsinger requested changes
The change looks good to me. However, the linter complains as follows: 

```
Linting successful for all files.
Changes in the docs folder require updating the manifest
Generate a manifest with 'pnpm utils md-docs create docs woocommerce -o docs/docs-manifest.json'
Error: Process completed with exit code 1.
```

2024-01-31 10:25 UTC, lsinger commented on docs/contributing/deciding-pr-high-impact.md
> +Note that security issues and fixes should all go through our [security reporting process](./reporting-security-issues.md).
With all the bolding going on above, maybe let's do something similar here as well? 

```suggestion
Note that **security issues and fixes** should all go through our [security reporting process](./reporting-security-issues.md).
```

2024-02-01 19:00 UTC, JacklynBiggin commented
@lsinger Please could you check whether the changes @brentmackinnon just made fix the issues you flagged and change your review to approved if so?

2024-02-02 13:37 UTC, lsinger commented
> @lsinger Please could you check whether the changes @brentmackinnon just made fix the issues you flagged and change your review to approved if so?

@JacklynBiggin Yes, looks good -- however now there's a conflict that needs to be resolved. I assume the manifest has changed in the meantime. A rebase and another regeneration of the manifest might make the most sense. Please let me know if I can help with anything. 

By the way -- in the future, ideally use the "Re-request review" button so that the PR comes up on the reviewer's "[Review requests](https://github.com/pulls/review-requested)" page.

2024-02-02 14:57 UTC, lsinger submitted a review, later dismissed
(As already mentioned as a comment, this looks good to me and just needs the conflict resolved, likely by rebasing on `trunk` and then regenerating the manifest.)

2025-01-30 14:55 UTC, dwainm submitted a review, later dismissed
Changes looks good.

2026-08-13 15:18 UTC, nerrad commented
@woocommerce/developer-advocacy I'm going to close this one too because I'm not sure of relevancy now. It's unfortunate that it looks like it had been approved at one point.

2026-08-13 15:18 UTC, closed without merging