Update daily workflow to sharding
woocommerce/woocommerce pull request #44330
Opened 2024-02-02 19:44 UTC by lanej0

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Updates the daily testing workflows to execute end-to-end tests with sharding

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Actions > Daily smoke test
2. Run the workflow using this branch
3. Ensure workflow passes

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-02-07 09:01 UTC, adimoldovan requested changes

2024-02-07 09:01 UTC, adimoldovan commented on .github/workflows/smoke-test-daily.yml
> +    e2e-tests-success:
I guess this job is not really needed, this workflow doesn't block anything being a scheduled one.

2024-02-07 09:01 UTC, adimoldovan commented on .github/workflows/smoke-test-daily.yml
> +        - name: Generate Playwright E2E Test report.
Nitpick, but `Generate Playwright E2E Test report.` makes me think the Playwright default report will be generated here, while in fact the Allure report is generated. If there was no Playwright report available it wouldn't be confusing. How about keeping it simple: `Generate test report`?

2024-02-07 09:01 UTC, adimoldovan commented on .github/workflows/smoke-test-daily.yml
> +      needs: e2e-tests-success
The `e2e-tests-success` only runs on `success()`, so I guess this one will not run on tests failures.
But I think `e2e-tests-success` is not needed in this case (see my other comment) and this job should wait for `e2e-tests` instead.

2024-02-07 19:23 UTC, lanej0 commented on .github/workflows/smoke-test-daily.yml
> +    e2e-tests-success:
Right. I was copying and pasting from the PR workflow :-)

2024-02-07 22:11 UTC, lanej0 commented
Thanks for your review @adimoldovan -- I've implemented all of your feedback, and fixed the last couple of bugs that were lingering with reporting.  The latest run can be seen here: https://github.com/woocommerce/woocommerce/actions/runs/7821375862

2024-02-08 09:44 UTC, adimoldovan approved these changes
Looks good 👍🏼

2024-02-08 09:45 UTC, merged