Add/43704 prepublish sidebar modal
woocommerce/woocommerce pull request #44331
Opened 2024-02-02 20:27 UTC by octaedro

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43704.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-02-06 21:15 UTC, louwie17 requested changes
Nice work @octaedro, this is a great start, I just left a couple suggestions to align a bit more with the GB implementation.
Also notice one small issue around the scrolling, I left an inline comment.

2024-02-06 21:15 UTC, louwie17 commented on packages/js/product-editor/src/components/editor/editor.tsx
> +								}
It appears that `sidebar` is used for the actual collapsable sidebar, we may want to use the `actions` input here, similar to GB. And if we do add an actual expandable/collapsable sidebar we can add it here.

2024-02-06 21:15 UTC, louwie17 commented on packages/js/product-editor/src/components/prepublish-sidebar/prepublish-button.tsx
> +			children={ __( 'Add', 'woocommerce' ) }
We are moving back to the `Publish` terminology, this may be part of a separate issue. But it may be worth to start using `Publish` here already.

2024-02-06 21:15 UTC, louwie17 commented on packages/js/product-editor/src/components/prepublish-sidebar/prepublish-sidebar.tsx
> +export function PrepublishSidebar( {
Maybe we should stick with `Panel` instead of `Sidebar` here to follow the same naming as GB

2024-02-06 21:15 UTC, louwie17 commented on packages/js/product-editor/src/components/prepublish-sidebar/prepublish-sidebar.tsx
> +			<div className="woocommerce-product-publish-panel__actions">
A nitpick, but to follow inline with GB implementation maybe use `__header` here?

2024-02-06 21:15 UTC, louwie17 commented on packages/js/product-editor/src/components/prepublish-sidebar/prepublish-sidebar.tsx
> +					onSuccess={ closePrepublishSidebar }
We actually don't want the side bar to auto close after its been published, to match GB it stays open and instead displays `<product name> is now live.` with a close button.
See: https://github.com/WordPress/gutenberg/blob/55fbdd96aa2642dff194cb69ebe02c3669eebae0/packages/editor/src/components/post-publish-panel/index.js#L79

2024-02-06 21:15 UTC, louwie17 commented on packages/js/product-editor/src/components/prepublish-sidebar/style.scss
> +	overflow: auto;
We also want a `fixed` position to avoid it from scrolling with the page.

2024-02-06 21:15 UTC, louwie17 commented on packages/js/product-editor/src/components/prepublish-sidebar/style.scss
> +	overflow: auto;
https://github.com/woocommerce/woocommerce/assets/2240960/cbb090fc-6953-49fa-b02a-ea4aedb0148f

2024-02-07 12:40 UTC, octaedro commented on packages/js/product-editor/src/components/prepublish-sidebar/prepublish-sidebar.tsx
> +export function PrepublishSidebar( {
Good idea! https://github.com/woocommerce/woocommerce/pull/44331/commits/6a1ed9783f840ec425730a61cf40f4f6f3d213e3

2024-02-07 12:40 UTC, octaedro commented on packages/js/product-editor/src/components/prepublish-sidebar/style.scss
> +	overflow: auto;
Done in https://github.com/woocommerce/woocommerce/pull/44331/commits/f4f3eedc7ec80bbf0322a0cef0e10c98b5e898ad

2024-02-07 12:41 UTC, octaedro commented on packages/js/product-editor/src/components/prepublish-sidebar/prepublish-button.tsx
> +			children={ __( 'Add', 'woocommerce' ) }
What do you think about adding that change in its own PR? We will have to change some E2E tests, as well and I think it makes sense to give that change more visibility. I can create an issue for that if we already don't have one.

2024-02-07 13:38 UTC, octaedro commented on packages/js/product-editor/src/components/editor/editor.tsx
> +								}
Good call! I did it in the commit https://github.com/woocommerce/woocommerce/pull/44331/commits/9ae966b35c0e4f7998c4b0384c5e402c19573be2

2024-02-07 14:54 UTC, octaedro commented
Thank you @louwie17 for your suggestions; I just addressed them. Could you take another look at this PR?

2024-02-07 15:58 UTC, louwie17 commented on packages/js/product-editor/src/components/prepublish-sidebar/prepublish-button.tsx
> +			children={ __( 'Add', 'woocommerce' ) }
Change to its own PR sounds great, we may already have an issue that encapsulates this. I think its related to the dropdown addition for scheduling https://github.com/woocommerce/woocommerce/issues/40374

2024-02-07 18:13 UTC, louwie17 approved these changes
Thanks for the updates @octaedro, this looks great and tested well!
I think this is fine as is.
It would be great if we can do these things as follow up:
- The `Add` to `Publish` naming update ( as mentioned in the comment thread )
- The issue with the `Publish` button looking disabled when the product isn't published already ( but saved ) logic should be disabled look if saved and published.
- Updating the sidebar to show `[product name] is now live.` after it has been published and not show the Add/Cancel buttons but instead just an `x` ( same as the post/site editor ).

2024-02-07 18:30 UTC, merged