Update the copy for the terms and conditions on WooCommerce.
woocommerce/woocommerce pull request #44449
Opened 2024-02-08 11:26 UTC by nefeline

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Based on internal discussion and recommendations from our legal team (reference: pdnLyh-5eI-p2#comment-3865), update the copy for the onboarding terms and conditions.

Closes #44435

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Start a new store while having this branch of Woo up and running. Alternatively, in case you already have a local install up and running, reset the onboarding flow to get access to the intro screen by installing the **WooCommerce Beta Tester** plugin and heading over to `Tools > WCA Test Helper > Tools > Reset Onboarding Wizard`
2. Click on WooCommerce > Home
3. When the following screen is displayed, make sure the copy matches the one exemplified on the screenshot below:

<img width="1231" alt="Screenshot 2024-02-08 at 08 13 44" src="https://github.com/woocommerce/woocommerce/assets/15730971/5fa297d1-42d5-49e9-93fd-7277e0e3c5ce">

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-02-08 12:57 UTC, albarin commented on plugins/woocommerce-admin/client/core-profiler/pages/IntroOptIn.tsx
> +								'I agree to share my data to tailor my store setup experience, get more relevant content, and help make WooCommerce better for everyone. You can opt out at any time in WooCommerce settings. {
Just a small comment, there's a closing bracket at the end, but it's never opened.

2024-02-08 12:57 UTC, albarin requested changes
@nefeline added a small comment about a loose bracket.

2024-02-08 21:52 UTC, nefeline commented on plugins/woocommerce-admin/client/core-profiler/pages/IntroOptIn.tsx
> +								'I agree to share my data to tailor my store setup experience, get more relevant content, and help make WooCommerce better for everyone. You can opt out at any time in WooCommerce settings. {
🤦‍♀️ thanks! Fixed https://github.com/woocommerce/woocommerce/pull/44449/commits/e31372df10323a296cb56bbebe4961c8961f4ea3 !

2024-02-08 21:53 UTC, nefeline commented
> @nefeline added a small comment about a loose parenthesis.

Nice catch, updated!

2024-02-09 08:01 UTC, albarin approved these changes
👌

2024-02-28 14:41 UTC, gigitux commented
As we discussed in the thread (reference: pdnLyh-5eI-p2#comment-3998), I updated the label on the WooCommerce Settings, and I updated some snapshots. @albarin, could you take a look?

2024-02-28 14:55 UTC, albarin approved these changes
Looks good! 🙌

2024-02-28 14:57 UTC, merged