Add new E2E shop test filtering products by price
woocommerce/woocommerce pull request #44516
Opened 2024-02-09 17:14 UTC by veljkho

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # [669](https://github.com/woocommerce/woocommerce-quality/issues/669) in Woo Quality

This is a good start to test also other filters in separate pull requests, but for this task this should be fine.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Checkout this branch
2. Run `pnpm test:e2e-pw ./tests/e2e-pw/tests/shopper/shop-products-filter-by-price.spec.js`
3. Make sure it passes

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-02-09 22:05 UTC, lanej0 reviewed
Running this locally, I can't get the second test to pass.  I keep getting:

```
1) [Chrome] › shopper/shop-products-filter-by-price.spec.js:116:2 › Filter items in the shop by product price › filter products by prices on the created page

    Error: Timed out 20000ms waiting for expect(locator).toBeHidden()

    Locator: locator('h2.wc-block-grid__product-title').filter({ hasText: 'AAA Filter Products 3' })
    Expected: hidden
    Received: visible
```

2024-02-10 09:44 UTC, veljkho commented
I see it always passing for me locally. Can you try running in --head or --debug mode and check if the value of $50 is applied to the filter? I will see to slow it down or something I suspect it's about it. @lanej0

2024-02-12 23:03 UTC, lanej0 commented
There's definitely something going on with me locally.  Applying the filter looks like it should update the URL (for example `http://localhost:8086/products-filtering/?max_price=50`) -- but that's not happening for me. 

@adimoldovan -- would you mind trying out this PR locally?  If the test passes for you, I'll just assume that something is up with my local environment.

2024-02-13 10:06 UTC, Stojdza commented
> Running this locally, I can't get the second test to pass. I keep getting:

I'm getting the same error:

<img width="1016" alt="Screenshot 2024-02-13 at 11 04 29" src="https://github.com/woocommerce/woocommerce/assets/7116222/989dc839-b96e-4b8b-bce5-c3a88b6c14df">

2024-02-13 10:17 UTC, adimoldovan commented
> @adimoldovan -- would you mind trying out this PR locally? If the test passes for you, I'll just assume that something is up with my local environment.

It's failing locally for me too, with the same error as @Stojdza and @lanej0 get.

2024-02-13 14:32 UTC, adimoldovan reviewed
I'm not so sure about having the second test dependent on the first one. Maybe putting it all into a single test would make more sense? Even if that test will be longer, I think it would work better. In fact, everything the second test does is to check that what the first one set up is actually working.

2024-02-13 14:32 UTC, adimoldovan commented on plugins/woocommerce/tests/e2e-pw/tests/shopper/shop-products-filter-by-price.spec.js
> +		await page.locator( 'text=Log In' ).click();
I'm curious on why you chose to go through login instead of using the admin storageState.

2024-02-13 14:32 UTC, adimoldovan commented on plugins/woocommerce/tests/e2e-pw/tests/shopper/shop-products-filter-by-price.spec.js
> +		await page.waitForLoadState( 'networkidle' );
Using `networkidle` is discouraged, eslint reports it as an error. You should asses readiness in other ways. In fact, the next line already checks for readiness before using the element, so this `networkidle` is not needed anyway.

2024-02-14 12:04 UTC, rodelgc commented
> I'm not so sure about having the second test dependent on the first one.

I agree with just combining the two tests together. It'll be a source of flakiness to have dependent tests without explicitly specifying [serial mode](https://playwright.dev/docs/test-parallel#serial-mode). But since we must avoid serial mode as much as possible, I agree with just merging the two tests together.

2024-02-14 12:16 UTC, rodelgc requested changes, later dismissed
I noticed that after the test has finished, it leaves a test page that wasn't cleaned up. It would be good to clean up this test page after the test is done, otherwise they might pile up during reruns/retries just like what happened in the screenshot below:

<img width="457" alt="rvg1QwWKTT" src="https://github.com/woocommerce/woocommerce/assets/4509348/e85e0707-990e-4fc6-bf12-b81399fa85c9">

2024-02-14 13:26 UTC, adimoldovan commented
> I noticed that after the test has finished, it leaves a test page that wasn't cleaned up. It would be good to clean up this test page after the test is done, otherwise they might pile up during reruns/retries

+1 on this. Not only it will pile up, but the new page created by the test will get a different slug, and the test uses a slug created from the page name, which in this case it will be a page created in a previous run. 
It might worth it to get the page slug from the UI after the page is published, to make sure the right one is always used.

2024-02-16 14:44 UTC, adimoldovan commented
While checking some other things today I came about [this spec](https://github.com/woocommerce/woocommerce/blob/33e42456150bceb92dca68fc4330394d8b2112f0/plugins/woocommerce-blocks/tests/e2e/tests/price-filter/price-filter.block_theme.side_effects.spec.ts), in woocommerce-blocks e2e tests. 
Isn't it testing the same thing?

2024-02-21 12:28 UTC, veljkho commented on plugins/woocommerce/tests/e2e-pw/tests/shopper/shop-products-filter-by-price.spec.js
> +		await page.locator( 'text=Log In' ).click();
Yeah, that is not needed actually, good catch. I worked with different tests where necessary, but it was not required for this one.

2024-02-21 12:28 UTC, veljkho commented on plugins/woocommerce/tests/e2e-pw/tests/shopper/shop-products-filter-by-price.spec.js
> +		await page.waitForLoadState( 'networkidle' );
Sure, many other tests still use it but not needed with Playwright ;) Removed.

2024-02-21 12:29 UTC, veljkho commented on plugins/woocommerce/tests/e2e-pw/tests/shopper/shop-products-filter-by-price.spec.js
> +		await page.waitForLoadState( 'networkidle' );
And for the main question, I will make it under a single test. 👍

2024-02-21 12:38 UTC, veljkho commented
> I noticed that after the test has finished, it leaves a test page that wasn't cleaned up.

Thanks for your review @rodelgc , that was intentional but I will clean it up. 👍 

> While checking some other things today I came about [this spec](https://github.com/woocommerce/woocommerce/blob/33e42456150bceb92dca68fc4330394d8b2112f0/plugins/woocommerce-blocks/tests/e2e/tests/price-filter/price-filter.block_theme.side_effects.spec.ts), in woocommerce-blocks e2e tests.
Isn't it testing the same thing?

Thank so much for the review @adimoldovan , I will make requested changes soon.
Regarding that test, I don't know what it tests, but it is from the blocks repo, which shouldn't be part of our Core testing.

I see that the test failed also on my local now, so it is flaky actually. Will make better steps for the second min/max check.

2024-02-21 15:48 UTC, veljkho commented
Added commit to fix flakiness and make the test more stable. Testing this filter is tricky due to playwright being very fast.

2024-02-21 16:35 UTC, veljkho commented
@rodelgc I added page removal at the end via `wpApi` in `afterAll`, that's the one we use also in `merchant/create-page` and `merchant/create-post` and few more places, but after executing all these tests locally I still see posts and pages left created. Seems something's wrong with deleting posts/pages via API, or just a local thing.

2024-02-23 08:44 UTC, veljkho commented
Hi @adimoldovan 
Since Rodel is AFK, can you please review this one? Thanks

2024-02-23 16:15 UTC, adimoldovan requested changes
Thanks @veljkho for the updates, it looks much better. However, I still find there are issues with this test that need to be addressed before merging.

I want to reiterate https://github.com/woocommerce/woocommerce/pull/44516#issuecomment-1943766433, regarding the effect of pages not being properly cleaned up. You're hardcoding the page slug, and always using `products-filtering`. However, on a second run the created page will be `products-filtering-2`, but the test will still use `products-filtering`, created by the first run. I suggest using a unique page name, like `Products Filtering ${ Date.now() }`. This will ensure the proper test data independent of a successful cleanup.

> I added page removal at the end via wpApi in afterAll, that's the one we use also in merchant/create-page and merchant/create-post and few more places, but after executing all these tests locally I still see posts and pages left created. Seems something's wrong with deleting posts/pages via API, or just a local thing.

The cleanup doesn't work indeed. In this case, can you please remove the code?

> I see that the test failed also on my local now, so it is flaky actually. Will make better steps for the second min/max check.

The test still fails for me. It failed 9 times out of 20 runs. The error was the same in each failure:
```
Locator: locator('h2.wc-block-grid__product-title').filter({ hasText: 'AAA Filter Products 3' })
Expected: hidden
Received: visible
```

I suggest running it more times locally and ensure it passed every time. The `REPEAT_EACH` env variable is very helpful for this.

> Regarding that test, I don't know what it tests, but it is from the blocks repo, which shouldn't be part of our Core testing.

It looks to me that's testing the same thing, the product filter block. And I think [this comment](https://github.com/woocommerce/woocommerce/blob/33e42456150bceb92dca68fc4330394d8b2112f0/plugins/woocommerce-blocks/tests/e2e/tests/price-filter/price-filter.block_theme.side_effects.spec.ts#L62) describes the issue with the price input resetting that's making this test flaky.
Without investigating too much that seems to me the proper place for such a test. But I may be missing stuff.

2024-02-23 17:26 UTC, veljkho commented
Hi @adimoldovan 
Appreciate it for taking another look.

> The cleanup doesn't work indeed. In this case, can you please remove the code?

Removed code in a new commit. 👍 

> However, on a second run the created page will be products-filtering-2,

I knew this initially, but this test will always run once in CI. It is impossible to experience this wrong slug in CI, only locally if running twice. Nevertheless, for appropriate E2E designing and hygiene, I would always make some cleanup in the end.

I will add `Date.now` in the page title until we figure out page removal, good suggestion. 👍 

> It failed 9 times out of 20 runs.

This is fine, we have retries in CI. The test passed recently 5/5 for me locally, and I feel comfortable merging.

2024-02-23 17:46 UTC, adimoldovan requested changes
> I knew this initially, but this test will always run once in CI. It is impossible to experience this wrong slug in CI, only locally if running twice. Nevertheless, for appropriate E2E designing and hygiene, I would always make some cleanup in the end.

> This is fine, we have retries in CI.

So, the retry will use the first run's data. It's not impossible in CI. But this is solved now, thank you for that.

> This is fine, we have retries in CI. The test passed recently 5/5 for me locally, and I feel comfortable merging.

I'm sorry, but I'm not comfortable merging a known flaky test. 9/20 is not a small failure rate. Please, check [the comment in test I left in the previous review](https://github.com/woocommerce/woocommerce/blob/33e42456150bceb92dca68fc4330394d8b2112f0/plugins/woocommerce-blocks/tests/e2e/tests/price-filter/price-filter.block_theme.side_effects.spec.ts#L62), it also gives a solution to the issue.

2024-02-23 18:23 UTC, veljkho commented
> I'm sorry, but I'm not comfortable merging a known flaky test. 9/20 is not a small failure rate. Please, check [the comment in test I left in the previous review](https://github.com/woocommerce/woocommerce/blob/33e42456150bceb92dca68fc4330394d8b2112f0/plugins/woocommerce-blocks/tests/e2e/tests/price-filter/price-filter.block_theme.side_effects.spec.ts#L62), it also gives a solution to the issue.

I added a new commit with this change, previously I used my concept to avoid flakiness and it worked for me locally, but this one also does the job so no problem.

Please check on your end if it's flaky anymore with this change @adimoldovan

2024-02-26 12:30 UTC, adimoldovan approved these changes
Thanks @veljkho, it tested well for me after the last changes.

2024-02-26 12:30 UTC, merged