Product Collection: disable "Sync with current query" option for 2nd+ block on archive
woocommerce/woocommerce pull request #44577
Opened 2024-02-13 10:49 UTC by kmanijak

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

There's a "Sync with current query" option available on Product Collection block (Product Catalog collection). Till now the option was enabled by default on product archives. This PR introduces the logic that the option is enabled ONLY IF there's no other Product Collection block that already syncs with query.
In other words, the rule of thumb is:
- first Product Collection (Product Catalog) on a page will get the option enabled by default
- second and next will get the option disabled.

Closes https://github.com/woocommerce/woocommerce/issues/44086

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

#### Scenario 1

1. Go to Product Catalog template
2. Add Product Collection (Beta) block
3. Choose "Featured" collection - this step is to make sure "other" collections don't influence the solution
4. Add Product Collection (Beta) block
3. Choose "Product Catalog" collection
4. **Expected:** Check inspector controls - "Sync with current query" should be ENABLED

<img width="291" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/f968b738-9011-4693-bb84-b8d96b1f2b81">

6. Add Product Collection (Beta) block
3. Choose "Product Catalog" collection
4. **Expected:** Check inspector controls - "Sync with current query" should be DISABLED
 
<img width="272" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/7d70802f-4048-42dc-909c-148391ffbb66">

#### Scenario 2

1. Go to Product Catalog template
2. Add Product Collection (Beta) block
3. Choose "Featured" collection - this step is to make sure "other" collections don't influence the solution
4. Add Product Collection (Beta) block
3. Choose "Product Catalog" collection
4. **Expected:** Check inspector controls - "Sync with current query" should be ENABLED
6. Disable the option
7. Add Product Collection (Beta) block
3. Choose "Product Catalog" collection
4. **Expected:** Check inspector controls - "Sync with current query" should be ENABLED because we disabled the option in previous one

#### Scenario 3

1. Create new post
2. Add Product Collection (Beta) block
3. Choose "Featured" collection
4. Add Product Collection (Beta) block
3. Choose "Product Catalog" collection
4. **Expected:** Check inspector controls - "Sync with current query" option is not available
6. Switch to Code Editor view (Three dots menu in top right corner of Editor -> Code Editor)
<img width="297" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/dc06f7dc-22a0-4202-9e35-53cd6391952d">

7. Search for `"inherit"` and make sure it's `false`
<img width="293" alt="image" src="https://github.com/woocommerce/woocommerce/assets/20098064/c83fb97c-057e-4b6f-b23c-8c5f2ed23bba">

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-02-15 16:28 UTC, thealexandrelara requested changes
Great work so far! I left two minor suggestions regarding the title of the tests. Here are the testing results:

⛔  Scenario 1: After adding the last Product Collection (Beta) block, the "Sync with current query" is not disabled:

https://github.com/woocommerce/woocommerce/assets/20469356/0b2f2e25-1ed0-4b34-a40d-aee99b288cc4

---

✅  Scenario 2: After adding the last Product Collection (Beta) block, the "Sync with current query" setting of the last added block is enabled.

https://github.com/woocommerce/woocommerce/assets/20469356/5a9df221-ea6d-4fcf-8cd0-70ffb7c5b27f

---

✅  Scenario 3: When I add the Product Collection (Beta) block to a new post, the ""Sync with current query" option is not available. If I switch to the Code Editor view, the "inherit" is set to `false`.

https://github.com/woocommerce/woocommerce/assets/20469356/7b83f2bd-97b7-481a-8283-8220b9ad553c

2024-02-15 16:28 UTC, thealexandrelara commented on plugins/woocommerce-blocks/tests/e2e/tests/product-collection/product-collection.block_theme.spec.ts
> +			test( 'is enlabled by default in 1st Product Collection and disabled in 2nd+', async ( {
I believe there is a small typo in the test title

```suggestion
			test( 'is enabled by default in 1st Product Collection and disabled in 2nd+', async ( {
```

2024-02-15 16:28 UTC, thealexandrelara commented on plugins/woocommerce-blocks/tests/e2e/tests/product-collection/product-collection.block_theme.spec.ts
> +		test.describe( 'Sync with current template aka Inherit query from template', () => {
I believe it would be better to avoid the abbreviation `aka`. For me, as a non-native English speaker, it took me some time to understand it was an abbreviation and not referring to some piece of the code or a template/settings name (unless it is not is not an abbreviation and I am confused 😅)

2024-02-16 07:59 UTC, kmanijak commented
@thealexandrelara , thanks for a review! I addressed minor comments 👍 

> ⛔ Scenario 1: After adding the last Product Collection (Beta) block, the "Sync with current query" is not disabled:

TBH I can't reproduce it at all. Is there any chance the project didn't rebuild on your side? I'm asking because scenarios 2 and 3 are only regression scenarios, meaning they would pass on `trunk` as well and only scenario 1 is new feature covered in that PR. I'd be grateful for double-checking 🙏

2024-02-16 16:46 UTC, thealexandrelara commented
> @thealexandrelara , thanks for a review! I addressed minor comments 👍
> 
> > ⛔ Scenario 1: After adding the last Product Collection (Beta) block, the "Sync with current query" is not disabled:
> 
> TBH I can't reproduce it at all. Is there any chance the project didn't rebuild on your side? I'm asking because scenarios 2 and 3 are only regression scenarios, meaning they would pass on `trunk` as well and only scenario 1 is new feature covered in that PR. I'd be grateful for double-checking 🙏

I tried rebuilding or creating a JN site from this branch, but still getting the same results, unless I'm doing something wrong while testing or there is some requirement that I'm missing. I'm going to send the JN site credentials to you in private :)

2024-02-19 15:27 UTC, kmanijak commented
> I tried rebuilding or creating a JN site from this branch, but still getting the same results, unless I'm doing something wrong while testing or there is some requirement that I'm missing

@thealexandrelara , I tested adding blocks on a higher level, while you tested with nested blocks. I misread one selector documentation I didn't notice it wouldn't work for nested blocks. I revisited implementation. May I ask you for yet another review? 🙏

2024-02-19 16:37 UTC, thealexandrelara approved these changes
Great work! Thank you for addressing all the raised points. I just tested it and everything is working as expected. 🚀

2024-02-19 16:51 UTC, merged