Fix block templates not being rendered in extension taxonomies
woocommerce/woocommerce pull request #44850
Opened 2024-02-21 13:48 UTC by Aljullu

### Changes proposed in this Pull Request:

Alternative approach from #44646.

Closes https://github.com/woocommerce/woocommerce/issues/44453.

In some circumstances, `woocommerce_has_block_template` wasn't set to `true` correctly, that meant that we were rendering a broken PHP template instead of the correct block template.

The issue was only reproducible in block themes with certain custom WooCommerce templates (ie: Tsubaki, which has the `archive-product.html` template), and were only reproducible in these cases:

* When rendering a product archive page belonging to a taxonomy with no template in the theme. That's excluding the category, tag and attribute taxonomies. So it was only reproducible in taxonomies added by extensions.
* When rendering the Shop page with certain filters (what's described in #44453).

This PR removes a check we had in the code that would only set `woocommerce_has_block_template` if the template was not in the theme.

### How to test the changes in this Pull Request:

**Verify #44453 is fixed**

1. With a theme with custom WooCommerce templates (ie: Tsubaki).
2. Go to WooCommerce > Settings > Products > Advanced and disable _Use the product attributes lookup table for catalog filtering_.
3. With a block theme with custom WooCommerce templates (ie: Tsubaki) go to `/shop/?product_cat=Clothing&filter_size=large`. Note: the values of `product_cat` and `filter_xyz` might vary depending on the categories and attributes of your store. In case of doubt, you can import the [products from `sample-data`](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/sample-data).
4. Verify the page is rendered correctly.

Before | After
--- | ---
![image](https://github.com/woocommerce/woocommerce/assets/3616980/12413fda-2c24-49d7-8b21-3cbb4537776f) | ![image](https://github.com/woocommerce/woocommerce/assets/3616980/2ab71af9-754c-46db-be31-9e25598f0167)

**Verify taxonomies added by extensions are rendered correctly (testing for devs)**

1. With a theme with custom WooCommerce templates (ie: Tsubaki).
2. Install WooCommerce Brands.
3. In the admin, create a brand, edit a product and assign that product to the brand you just created.
4. Visit the brand page in the frontend (the page should render correctly).
5. Edit `class-wc-brands-block-templates.php` and comment out this line: `add_filter( 'woocommerce_has_block_template', array( $this, 'has_block_template' ), 10, 2 );`.
6. Visit the brand page again. Verify the page still renders correctly.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-03-02 08:34 UTC, imanish003 requested changes
Hey @Aljullu,

I've tested the changes and everything is functioning as anticipated. I've left some minor comments and will await your response before giving my approval to this PR 🚀.

Thank you for your excellent work around templates so far 🙌🏻

2024-03-02 08:34 UTC, imanish003 commented on plugins/woocommerce/src/Blocks/Templates/CartTemplate.php
Nit: I am seeing multiple PHPCS warnings in this file. Can you see those, too? 

<img width="865" alt="image" src="https://github.com/woocommerce/woocommerce/assets/16707866/d759183f-434d-40de-8939-a4ab9ecaf9fd">
<img width="1141" alt="image" src="https://github.com/woocommerce/woocommerce/assets/16707866/c8c33389-a37c-4035-a0a6-6bc61254bd76">

2024-03-02 08:34 UTC, imanish003 commented on plugins/woocommerce/src/Blocks/Templates/CheckoutTemplate.php
Nit: I am seeing PHPCS warning in this file. Can you see it, too?

<img width="938" alt="image" src="https://github.com/woocommerce/woocommerce/assets/16707866/19b68396-618a-4a91-8fc6-e90768b8f5fa">

2024-03-02 08:34 UTC, imanish003 commented on plugins/woocommerce/src/Blocks/Templates/SingleProductTemplate.php
Nit: I am seeing PHPCS warning in this file. Can you see it, too?

![image](https://github.com/woocommerce/woocommerce/assets/16707866/9df8a11a-13e5-447b-976d-472d455f68f3)

2024-03-02 08:34 UTC, imanish003 commented on plugins/woocommerce/changelog/fix-44453-fix-block-templates-not-rendering
I don't think it's related to this PR, but "Subscribe to newsletter" isn't rendering correctly in Footer with Tsubaki theme, as you can see in screenshot below. Are you able to reproduce it? 

![image](https://github.com/woocommerce/woocommerce/assets/16707866/054f5dbd-992c-4206-9d7c-c7e366d5e4ce)

2024-03-02 08:34 UTC, imanish003 commented on plugins/woocommerce/changelog/fix-44453-fix-block-templates-not-rendering
I encountered this error with my local setup, so I created a new site to test the PR. I'm mentioning this here in case it affects any existing sites.
![image](https://github.com/woocommerce/woocommerce/assets/16707866/2ef6b49f-9073-42ac-9739-814e73cc7a41)

2024-03-04 13:14 UTC, WunderBart commented on plugins/woocommerce/src/Blocks/Templates/CartTemplate.php
I'm having some issues running `phpcs` in the monorepo, but shouldn't the CI also catch linting errors? It looks like all the checks are passing. 🤔

2024-03-05 11:05 UTC, imanish003 commented on plugins/woocommerce/src/Blocks/Templates/CartTemplate.php
@WunderBart Were you able to reproduce the PHPCS error? Maybe I have misconfigured my PHPCS extension in VSCode 😅

2024-03-05 11:07 UTC, imanish003 commented on plugins/woocommerce/src/Blocks/Templates/CartTemplate.php
> but shouldn't the CI also catch linting errors? It looks like all the checks are passing. 🤔

It should, maybe @ObliviousHarmony can provide more info on this? 👀

2024-03-05 16:59 UTC, ObliviousHarmony commented on plugins/woocommerce/src/Blocks/Templates/CartTemplate.php
WooCommerce uses `phpcs-changed` to lint files instead of `phpcs`. This limits linting to lines that have changed in files that have changed. This was done because WooCommerce violates a number of its own linting rules. Rather than attempting to fix all of these, a policy of fixing them as lines were touched was adopted.

2024-03-12 15:17 UTC, WunderBart commented on plugins/woocommerce/src/Blocks/Templates/CartTemplate.php
I'm not sure I'm doing this right, but I don't see the same errors. [The first one](https://private-user-images.githubusercontent.com/16707866/309460126-d759183f-434d-40de-8939-a4ab9ecaf9fd.png) seems to be coming from the `intelliphense` extension, which I'm not using (should I? 😅). [The second one](https://private-user-images.githubusercontent.com/16707866/309460154-c8c33389-a37c-4035-a0a6-6bc61254bd76.png) is from phpcs but it does not throw OnMyMachine™. When I run `phpcs` against that file I get the following errors:

```
$ ./vendor/bin/phpcs --standard=WooCommerce-Core src/Blocks/Templates/CartTemplate.php

FILE: /Users/bart/Code/woocommerce/woocommerce/plugins/woocommerce/src/Blocks/Templates/CartTemplate.php
--------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------
 1 | ERROR | Filenames should be all lowercase with hyphens as word separators. Expected
   |       | carttemplate.php, but found CartTemplate.php.
 1 | ERROR | Class file names should be based on the class name with "class-" prepended. Expected
   |       | class-carttemplate.php, but found CartTemplate.php.
 1 | ERROR | Missing file doc comment
--------------------------------------------------------------------------------------------------------
```

2024-03-12 15:30 UTC, WunderBart commented on plugins/woocommerce/src/Blocks/Templates/SingleProductTemplate.php
I can see the error only when runnning `phpcs` directly against that file (not caught by `phpcs-changed`):

```
$ ./vendor/bin/phpcs --standard=WooCommerce-Core src/Blocks/Templates/SingleProductTemplate.php

--------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------------------------------
  1 | ERROR | [ ] Filenames should be all lowercase with hyphens as word separators. Expected
    |       |     singleproducttemplate.php, but found SingleProductTemplate.php.
  1 | ERROR | [ ] Class file names should be based on the class name with "class-" prepended. Expected
    |       |     class-singleproducttemplate.php, but found SingleProductTemplate.php.
  1 | ERROR | [ ] Missing file doc comment
 54 | ERROR | [x] Short array syntax is not allowed
--------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------------------------------
```

2024-03-13 12:52 UTC, WunderBart commented on plugins/woocommerce/changelog/fix-44453-fix-block-templates-not-rendering
I can confirm this is true for `trunk` as well.

2024-03-14 13:21 UTC, WunderBart reviewed
I can repro the issue, but this PR doesn't seem to fix it. Here's what I see for the following themes on both `trunk` and this branch:

| 2024 | Tsubaki | Storefront |
| ------------- | ------------- | ------------- |
| <img width="1261" alt="Screenshot 2024-03-13 at 15 46 05" src="https://github.com/woocommerce/woocommerce/assets/1451471/7eac9109-8f01-44a8-94c4-7af64268d004"> | <img width="1259" alt="Screenshot 2024-03-13 at 15 45 15" src="https://github.com/woocommerce/woocommerce/assets/1451471/3aae5dc7-2954-4e36-ae12-18f793009c67"> | <img width="1264" alt="Screenshot 2024-03-13 at 15 45 36" src="https://github.com/woocommerce/woocommerce/assets/1451471/8617728f-aa2e-4a56-ad93-3324aece94d6"> |

Looks like Storefront is affected as well, and only 2024 seems to render the results correctly.

2024-03-14 13:23 UTC, WunderBart commented on plugins/woocommerce/changelog/fix-44453-fix-block-templates-not-rendering
I tried to reproduce with a fresh site but I can't see these errors.

2024-03-14 13:23 UTC, WunderBart commented on plugins/woocommerce/changelog/fix-44453-fix-block-templates-not-rendering
@Aljullu do you know if this is a known issue?

2024-03-14 13:26 UTC, WunderBart commented on plugins/woocommerce/src/Blocks/Templates/SingleProductTemplate.php
> not caught by phpcs-changed

By that, I meant that it seems to be aligned with the current linting standards! 😄

2024-03-14 15:05 UTC, WunderBart commented on plugins/woocommerce/src/Blocks/Templates/CheckoutTemplate.php
As above, linter does not show any errors:

```sh
$ pnpm lint:php src/Blocks/Templates/CheckoutTemplate.php

> @woocommerce/plugin-woocommerce@8.8.0 lint:php /Users/bart/Code/woocommerce/woocommerce/plugins/woocommerce
> composer run-script phpcs "src/Blocks/Templates/CheckoutTemplate.php"

> phpcs -s -p 'src/Blocks/Templates/CheckoutTemplate.php'
. 1 / 1 (100%)


Time: 145ms; Memory: 14MB
```

2024-03-14 15:06 UTC, WunderBart commented on plugins/woocommerce/src/Blocks/Templates/SingleProductTemplate.php
Ditto, linter is clear:

```sh
$ pnpm lint:php src/Blocks/Templates/SingleProductTemplate.php

> @woocommerce/plugin-woocommerce@8.8.0 lint:php /Users/bart/Code/woocommerce/woocommerce/plugins/woocommerce
> composer run-script phpcs "src/Blocks/Templates/SingleProductTemplate.php"

> phpcs -s -p 'src/Blocks/Templates/SingleProductTemplate.php'
. 1 / 1 (100%)


Time: 167ms; Memory: 12MB
```

2024-03-15 12:20 UTC, Aljullu commented
> I misunderstood the issue, but it seems to have been actually fixed on `trunk` as well as the page does not render differently on this branch.  

You're right, @WunderBart. It looks like the refactor PR (https://github.com/woocommerce/woocommerce/pull/44537) already fixed that issue. :smile: I updated the description of this PR and the refactor PR to account for that.

2024-03-15 12:23 UTC, Aljullu commented on plugins/woocommerce/changelog/fix-44453-fix-block-templates-not-rendering
@imanish003 did you switch themes after saving a customization on the template? If so, I think you are experimenting the issue described in https://github.com/woocommerce/woocommerce/issues/42181, which is definitely something that we want to fix, but IMO not in the scope of this PR.

2024-03-15 12:25 UTC, Aljullu commented on plugins/woocommerce/changelog/fix-44453-fix-block-templates-not-rendering
Looking at the source code of Tsubaki, I think it's intentional to have this shortcode in the footer. Tsubaki is not distributed on wordpress.org and is intended to be used on sites with Jetpack installed, so I'm pretty sure that's expected.

2024-03-15 12:28 UTC, Aljullu commented
Thanks for the reviews, folks! I think all comments have been answered and I updated the PR description and testing steps to account for the fact that https://github.com/woocommerce/woocommerce/issues/44453 was already fixed in `trunk` (sorry for the confusion!). This PR is ready for another look.

PS: even though #44453 has been fixed in `trunk`, I still think there is value in merging this PR because (1) it simplifies the code and (2) solves the issue described under the _Verify taxonomies added by extensions are rendered correctly_ testing section.

2024-03-18 08:06 UTC, imanish003 commented on plugins/woocommerce/changelog/fix-44453-fix-block-templates-not-rendering
@Aljullu Yeah, I think you are right. I did customization before switching the themes. I faced the same issue in the past too & now I know that it's a known issue 🙌🏻

2024-03-18 08:08 UTC, imanish003 commented on plugins/woocommerce/changelog/fix-44453-fix-block-templates-not-rendering
@Aljullu That makes sense. Thanks for sharing the reason behind it 🙌🏻

2024-03-18 08:25 UTC, imanish003 approved these changes
I verified the changes again & everything is working as expected :shipit:

2024-03-18 12:03 UTC, merged