[DRAFT] Allow extensions in Add Products task
woocommerce/woocommerce pull request #44892
Opened 2024-02-22 15:06 UTC by dakota

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-02-26 13:32 UTC, xristos3490 reviewed
Looks good to me, @dakota! Let's polish it so @ilyasfoo can take a final look as well before I approve. Also left a minor comment.

The only thing that stands out to me is that this filter will allow complete replacements of that list; which can be a nice-to-have feature for heavily customized stores.

2024-02-26 13:32 UTC, xristos3490 commented on plugins/woocommerce-admin/client/task-lists/fills/products/dummyplugin.js
> +/**
Is this file needed?

2024-02-26 13:35 UTC, dakota commented on plugins/woocommerce-admin/client/task-lists/fills/products/dummyplugin.js
> +/**
It is not. It was created by @ilyasfoo as part of the initial POC code. I thought of leaving it in as a example, but can remove it.

2024-02-27 06:35 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/task-lists/fills/products/dummyplugin.js
> +/**
Hey, @dakota! I'd recommend removing this file for review.

For a more realistic testing, appreciate if you could provide the GC plugin build that utilizes the filter. Thanks!

2024-02-28 16:04 UTC, dakota commented
> The only thing that stands out to me is that this filter will allow complete replacements of that list; which can be a nice-to-have feature for heavily customized stores.

@xristos3490 - I've made a change to prevent replacing the list as per the [project requirements](https://woostartp2.wordpress.com/2024/02/13/pt-optimize-onboarding-of-product-type-feature-extensions/#project-plan).

2024-02-28 16:05 UTC, dakota commented
@ilyasfoo @xristos3490 I believe this PR is now ready for CR and testing

2024-03-01 12:34 UTC, ilyasfoo requested changes
Testing well! However, I have few comments:

2024-03-01 12:34 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/task-lists/fills/products/constants.tsx
> +export const SETUP_TASKLIST_PRODUCT_TYPES =
Constant name could be a tad clearer. What do you think?
```suggestion
export const SETUP_TASKLIST_PRODUCT_TYPES_FILTER =
```

2024-03-01 12:34 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/task-lists/fills/products/constants.tsx
> +	'woocommerce_tasklist_experimental_product_types';
I looked at existing [experimental filters](https://github.com/woocommerce/woocommerce/blob/2f77de3f185644c0ef3b9b9cb5cdae6f9ca7b31e/plugins/woocommerce-admin/client/analytics/report/variations/table.js#L297), I think this is a better name
```suggestion
	'experimental_woocommerce_tasklist_product_types';
```

2024-03-01 12:34 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/task-lists/fills/products/utils.tsx
> +	 * Filter for adding custom product types to tasklist.
Similar suggestion with [existing experimental filter](https://github.com/woocommerce/woocommerce/blob/2f77de3f185644c0ef3b9b9cb5cdae6f9ca7b31e/plugins/woocommerce-admin/client/analytics/report/variations/table.js#L295)

```suggestion
	 * Experimental: Filter for adding custom product types to tasklist.
```

2024-03-01 12:34 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/task-lists/fills/products/utils.tsx
> +		...( applyFilters(
I think we should make the extension point safer. 

AFAIK spreading (`...`) a non-iteratable object may result in an error. Let's check if the filter value is iteratable first.

2024-03-07 01:36 UTC, ilyasfoo approved these changes
@dakota LGTM but please remember to update the filter name in GC plugin!

2024-03-07 10:04 UTC, merged