Filter the cart item quantity validation in StoreApi
woocommerce/woocommerce pull request #45489
Opened 2024-03-11 17:33 UTC by yoancutillas

### Changes proposed in this Pull Request:

Fixes #52263.

Filter the cart item quantity validation via Shop API to make it possible for third party plugins to prevent changing cart item quantity after checking their on their own conditions.

**Why it is necessary**
Third party developers cannot **validate a cart item quantity change with their custom conditions** with the storeAPI.
This used to be possible with the old API either with: “woocommerce_stock_amount_cart_item” or “woocommerce_update_cart_validation” hooks.

**What does it change**
This PR simply adds a PHP hook ([apply_filters](https://developer.wordpress.org/reference/functions/apply_filters/)) to the [Automattic\WooCommerce\StoreApi\Utilities\QuantityLimits validate_cart_item_quantity()](https://github.com/woocommerce/woocommerce/blob/9.4.1/plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php#L130) method return value to allow third party developers to prevent changing a cart item quantity and to display an error message explaining the reason.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

In this example, we are a third-party developer who wants to prevent the cart item quantity from being greater than 3.

1. Create a test plugin at `wp-content/plugins/test/test.php`
2. It should content the following code: 
```
<?php
/**
 * Plugin Name: Test woocommerce_store_api_validate_cart_item_quantity hook
 * Requires Plugins: woocommerce
 */

function test_wc_store_api_validate_cart_item_quantity( $true, $quantity, $cart_item ) {
	$custom_condition = $quantity <= 3;
	if( ! $custom_condition ) {
		return new \WP_Error(
			'invalid_custom_condition',
			'The quantity added to the cart doesn\'t meet the custom condition'
		);
	}
	
	return $true;
}
add_filter( 'woocommerce_store_api_validate_cart_item_quantity', 'test_wc_store_api_validate_cart_item_quantity', 10, 3 );
```
3. From your site admin, go to Plugins > All plugins > Make sure WooCommerce is active, deactivate everything else, and activate this test plugin
4. Make sure you are using the Block Cart (as opposed to the Classic Cart)
5. Create a product
6. Add this product to cart
7. Change the cart item quantity to 3, it should work
8. Change the cart item quantity to 4, an error message should be displayed
9. Refresh the page, the quantity should be reverted

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Filters the quantity validation for a cart item being updated via the Store API.

</details>

2024-04-25 13:42 UTC, yoancutillas commented
Hi, do I need to do something more?

2024-10-29 11:58 UTC, alexflorisca commented
Hi @yoancutillas I apologize that this PR slipped through the cracks. It was at a time when we were transitioning from a separate plugin into the main woo core repo. If you could please add some testing instructions to the PR, I will tag our team for review and someone will review it. Thank you for your contribution

2024-11-01 17:02 UTC, alexflorisca commented
Just a reminder that this is still waiting for testing instructions and some jobs are failing in CI - linting and tests. Please check those too. 🙏

2024-11-12 16:06 UTC, yoancutillas commented
Sorry, was this for me? I don't understand what can I do, I don't understand the failing jobs, there are no human readable instructions even after I click "details".

2024-11-13 12:01 UTC, alexflorisca commented
@yoancutillas can you update the PR description with what exactly this PR is for and I'll do the rest 🙏

2024-11-13 12:56 UTC, yoancutillas commented
@alexflorisca Sure, I have added a "What exactly this PR is for" section in the PR description. Thank you :)

2024-11-13 14:47 UTC, alexflorisca commented
Hi @yoancutillas. Thanks for updating the PR description. However it's still missing some testing instructions. There should be a PR template that you can follow when you open a PR. You may have edited this one, so here is an example of a good PR description: https://github.com/woocommerce/woocommerce/pull/52756

Notice the three headings
- Changes proposed in this Pull Request:
- How to test the changes in this Pull Request:
- Changelog entry

Please make sure your PR follows the same format here. The testing instructions are used by the reviewer and additionally by QA to test the changes proposed in the PR. 

It's important to have clear PR descriptions that follow a set format in order for us to review and consider the changes you propose. Thank you for understanding.

2024-11-13 15:27 UTC, yoancutillas commented
@alexflorisca Thank you, I have added Testing instructions and used the template with the three headings.

2024-11-15 13:24 UTC, alexflorisca approved these changes, later dismissed
I've updated the documentation with the new filter. Thanks for making this change, it will provide an extra extensibility point for everyone else to use as well.

2026-08-13 15:26 UTC, nerrad commented
@ralucaStan (you were assigned via team round robin) this surfaced in my stale PR scan and it looks like it had been approved at one point but then got lost in the shuffle with folks leaving Automattic. Likely needs a good refresh but the use-case still seems valid.

2026-08-14 08:51 UTC, ralucaStan commented
Thank you @nerrad, I'll take another look to decide on the next steps.

2026-08-14 09:18 UTC, ralucaStan commented
@yoancutillas Unfortunately, this PR wasn't on our team's radar. Could you update the branch and handle the conflicts? I'll then proceed to review the changes. 

Thank you, and we appreciate your contribution.

2026-08-19 09:06 UTC, ralucaStan commented
I pushed df53759 to clean up the docs file. The previous update reformatted the whole of `filters.md`, which corrupted several hook names with stray asterisks, dropped the `$total_packages` row from the `woocommerce_shipping_package_name` table, and removed the opening `<!-- FEEDBACK -->` marker.

The commit restores the file to the generated formatting from trunk and re-adds only the new `woocommerce_store_api_validate_cart_item_quantity` section. While there, I corrected the documented contract based on the review feedback: callbacks should return a `\WP_Error` to reject the new quantity instead of throwing; `$quantity` is `int|float`; and `$cart_item` is an `array`. I also added the missing TOC entries and pointed the Source link to a path that resolves.

The PHPDoc in `QuantityLimits.php` still needs the matching type updates (`int|float $quantity`, `array $cart_item`, and the `@since` bump to 11.2.0); that will come in a separate commit.

2026-08-19 09:11 UTC, ralucaStan commented on plugins/woocommerce/client/blocks/docs/third-party-developers/extensibility/hooks/filters.md
> +-   [StoreApi/Utilities/QuantityLimits.php](../../../../src/StoreApi/Utilities/QuantityLimits.php)
Fixed in df537594c8; the Source link now uses `../../../../../../src/StoreApi/Utilities/QuantityLimits.php`, which resolves from the docs directory. I went with the resolving path rather than the `../../../../../woocommerce/src/...` form used elsewhere in the file, since that established form has been broken repo-wide since the blocks merge.

2026-08-19 09:21 UTC, ralucaStan commented on plugins/woocommerce/client/blocks/docs/third-party-developers/extensibility/hooks/filters.md
> +| $query_args   | array   | Query args for the products query passed to BlocksWpQuery. |
This one is pre-existing on trunk and unrelated to this PR; the wrong description comes from the source docblock in `AbstractProductGrid.php` (its `@return array` is also wrong), and the markdown just reproduces it. Patching only the markdown would diverge from the source, so we will handle it separately together with the broken `build:docs` pipeline, and regenerate the doc from a corrected docblock. Leaving this thread open on those grounds.

2026-08-19 09:34 UTC, ralucaStan commented on plugins/woocommerce/client/blocks/docs/third-party-developers/extensibility/hooks/filters.md
> +| $query_args   | array   | Query args for the products query passed to BlocksWpQuery. |
Opened https://github.com/woocommerce/woocommerce/pull/67837 with the docblock fix and the matching correction in the generated hook reference; this thread can be resolved once it merges.

2026-08-19 10:13 UTC, ralucaStan requested changes
@yoancutillas to speed things I've cleaned up the PR so we can focus on the code changes. I left some comments that need your attention. 

Changes I did: updated the branch, fixed the documentation, run the tests, fixed the pr descriptio to use the new template, chose a milestone and a changelog

2026-08-19 10:13 UTC, ralucaStan commented on plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php
> +		 * Filters the quantity validation for a cart item being added to or updated in the cart via the Store API.
`woocommerce_store_api_validate_add_to_cart` handles the validation for a cart item being added to cart.

2026-08-19 10:13 UTC, ralucaStan commented on plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php
> +		return apply_filters( 'woocommerce_store_api_validate_cart_item_quantity', true, $quantity, $cart_item );
Users from the `woocommerce_update_cart_validation` filter might be inclined to return false. In this new filter, `false` would be treated as "not a WP_Error" and silently accepted unless normalized.

2026-08-19 10:13 UTC, ralucaStan commented on plugins/woocommerce/client/blocks/docs/third-party-developers/extensibility/hooks/filters.md
> +Filters the quantity validation for a cart item being added to or updated in the cart via the Store API. Return a \WP_Error with an informative message to reject the new quantity, or true to accept i
Let's drop the false claim 
```suggestion
Filters the quantity validation for a cart item being updated in the cart via the Store API. Return a \WP_Error with an informative message to reject the new quantity, or true to accept it.
```

2026-08-19 10:13 UTC, ralucaStan commented on plugins/woocommerce/src/StoreApi/Utilities/QuantityLimits.php
> +		return apply_filters( 'woocommerce_store_api_validate_cart_item_quantity', true, $quantity, $cart_item );
restated in https://github.com/woocommerce/woocommerce/pull/45489/changes#r3811896716

2026-08-19 17:00 UTC, yoancutillas commented
Hi,
Thank you for your work.

The AI suggestion seems fine, but it says it is "outdated" for some reasons, and I have no idea how to make a new one.
```
$valid = apply_filters( 'woocommerce_store_api_validate_cart_item_quantity', true, $quantity, $cart_item );

if ( true === $valid || is_wp_error( $valid ) ) {
	return $valid;
}

return new \WP_Error( 'invalid_quantity', __( 'The quantity is invalid.', 'woocommerce' ) );
```

So I tried to make a commit but it seems to be the wrong way to proceed. 

Look, if you can, do not wait for my approvals or anything and go ahead, I am quite lost with these processes and you clearly know what you are doing better than I do :)

2026-08-21 16:46 UTC, ralucaStan commented
> The AI suggestion seems fine, but it says it is "outdated" for some reasons, and I have no idea how to make a new one.

The suggestion was made on older code. Running `@coderabbitai review` starts a new review.

> Look, if you can, do not wait for my approvals or anything and go ahead, I am quite lost with these processes and you clearly know what you are doing better than I do :)
I started working on a complete PR + tests and testing steps. As it drifted a lot from the shape of this PR I started a new one, and kept your original commits.

I'll be closing this PR, feel free to add your thoughts to https://github.com/woocommerce/woocommerce/pull/67928

2026-08-21 16:46 UTC, closed without merging