new action 'woocommerce_restore_order_item_stock' hook when order ite…
woocommerce/woocommerce pull request #45851
Opened 2024-03-22 17:11 UTC by bkd27

…m stock restored (when order cancelled). similar to woocommerce_reduce_order_item_stock

2024-03-25 10:11 UTC, lsinger requested changes
Hello @bkd27,

Thank you for your contributions. Please make sure to fill out the PR template so that we know what use case this solves and how to test it.

2024-03-25 10:17 UTC, bkd27 commented
Hi, 

The use case of this new action is for third-party inventory management, we have action for 'woocommerce_reduce_order_item_stock' when stock is reduced but don't have any action event if the stock is restored (if the particular stock is used in order and that order gets cancelled).

2024-03-25 13:26 UTC, lsinger commented
@bkd27 Please use the PR template and fill it out properly. It should have been part of the description when you opened the PR. Here it is again -- please use this to replace the PR description. 

```
### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

<!-- You can erase any parts of this template not applicable to your Pull Request. -->

### Changes proposed in this Pull Request:

<!-- If necessary, indicate if this PR is part of a bigger feature. Add a label with the format `focus: name of the feature [team:name of the team]`. -->

<!-- Describe the changes made to this Pull Request and the reason for such changes. -->

(Tell us about what your changes are doing and why you are proposing them.)

<!-- Begin testing instructions -->

### How to test the changes in this Pull Request:

<!-- Include detailed instructions on how these changes can be tested. Review and follow the guide for how to write high-quality testing instructions. -->

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. (Please provide steps for testing your pull request here.)

<!-- End testing instructions -->

### Changelog entry

<!-- You can optionally choose to enter a changelog entry by checking the box and supplying data. -->

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

<!-- Choose only one -->

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

<!-- Choose only one -->

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message <!-- Add a changelog message here -->

#### Comment <!-- If the changes in this pull request don't warrant a changelog entry, you can alternatively supply a comment here. Note that comments are only accepted with a significance of "Patch" -->

</details>
```

Please re-request a review from me once you've made these changes. Thank you!

2026-08-12 12:59 UTC, nerrad commented
Closing because this is a stale draft issue

*\*left by Biff (AI agent) on behalf of Darren*

2026-08-12 12:59 UTC, closed without merging