add CF-Connecting-IP
woocommerce/woocommerce pull request #46138
Opened 2024-04-02 19:29 UTC by kkmuffme

it's already implemented in woocommerce/vendor/automattic/jetpack-status/src/class-visitor.php

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Adds CF-Connecting-IP header set by Cloudflare, which is already used/implemented in woocommerce/vendor/automattic/jetpack-status/src/class-visitor.php

### How to test the changes in this Pull Request:

This change is non-user-facing.

1. make sure site is behind Cloudflare CDN with orange cloud DNS proxy
2. open any page that uses WC geolocation and add breakpoint within the newly added condition.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

Cloudflare is widely used with WooCommerce sites and this speeds up and makes geolocation more reliable.

</details>

2024-04-04 11:19 UTC, senadir submitted a review, later dismissed
The logic seems fine and safe for me, I didn't test with a live website but I just passed the header to a Store API request and it did show up on the rate limiter.

2024-04-04 11:19 UTC, senadir commented
Closing and reopening so tests can run.

2024-05-14 08:13 UTC, vedanshujain requested changes
Requesting change to remove the support from authentication class (although it's fine for geolocation).

2024-05-14 08:13 UTC, vedanshujain commented on plugins/woocommerce/src/StoreApi/Authentication.php
> +		if ( array_key_exists( 'HTTP_CF_CONNECTING_IP', $_SERVER ) ) {
Note that using this header is fine for geolocation, but probably can't be used here, without also checking whether the request is also coming form one of [CloudFlare's IP address](https://www.cloudflare.com/en-gb/ips/)

2024-05-14 08:58 UTC, kkmuffme commented on plugins/woocommerce/src/StoreApi/Authentication.php
> +		if ( array_key_exists( 'HTTP_CF_CONNECTING_IP', $_SERVER ) ) {
Why? It can be spoofed in the same way all the other headers that are used/set there.

>also checking whether the request is also coming form one of [CloudFlare's IP address](https://www.cloudflare.com/en-gb/ips/)

How would you check that from PHP reliably? Since PHP isn't the webserver, the originating IP is often not the original IP if it's proxied by nginx e.g. via proxy pass. That's btw exactly the reason why this header is useful, bc it's not affected by reverse proxying but only set once by cloudflare.

2026-08-12 12:36 UTC, nerrad commented
Hey there, I'm going through a bunch of PRs that have been sitting for a while, and this one came up.

The underlying Cloudflare support remains relevant, and the Jetpack Status precedent is valid. However, Jetpack only checks forwarded headers when callers explicitly opt into Visitor::get_ip( true ); it does not establish that the request originated from Cloudflare.
The geolocation portion is consistent with WooCommerce’s existing handling of forwarded IP headers. The Store API change has a higher security impact because, when proxy support is enabled, the supplied address is used for rate-limit identity. In testing, a request sent directly to the origin with REMOTE_ADDR=127.0.0.1 and a spoofed CF-Connecting-IP=198.51.100.77 was attributed to 198.51.100.77. This is safe only when the deployment independently prevents untrusted clients from reaching the origin or supplying that header.
Since the requested separation or trusted-proxy handling was never resolved and the branch is now stale, I’m closing this implementation—not the underlying request. A fresh PR would be welcome if it either:
scopes Cloudflare support to geolocation; or defines an explicit trusted-proxy configuration before using forwarded IPs for Store API rate limiting. Even then though, it'd be good to outline the problem and why this is needed to be solved at the WooCommerce core level in an issue so we can keep the problem identified separately from the explorations on solving it.

2026-08-12 12:36 UTC, closed without merging