Slide animations always use CSS3 transitions instead of .animate()
woocommerce/woocommerce pull request #46564
Opened 2024-04-14 22:33 UTC by apenchev

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46563.

### How to test the changes in this Pull Request:

1. Add this custom code to your theme's `functions.php` in order to enable fade animations:
```
function carousel_options( $options ) {
	return array_merge(
		$options,
		array(
			'video' => true,
			'animationSpeed' => 1600,
			'easing' => 'easeInOutBack',
		)
	);
}
add_filter( 'woocommerce_single_product_carousel_options', 'carousel_options' );
```
2. Visit a Single Product Page.
3. Confirm that switching between gallery images happens with a slide transition that lasts 1.6 seconds.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-05-02 09:44 UTC, nefeline approved these changes
Thank you so much for your contribution @apenchev !

I've tested and confirmed that it is possible to control the animationSpeed via the filter as expected.

I'm pre-approving, but also tagging @roykho and @thealexandrelara for additional review since they have recently worked with the gallery block and might have additional input to offer.

2024-05-02 15:36 UTC, thealexandrelara requested changes
Hey @apenchev,
Thanks a lot for working on this! Your contribution is very much appreciated.

I noticed there's a small typo in the `transition-timing-function` CSS property. This causes the `easing` function not to be applied when `slider.transitions` is set to false. Once you fix this, I can take another look and approve the PR.

## With the typo | video: `true` | easing: `easeInOutBack` |

https://github.com/woocommerce/woocommerce/assets/20469356/d31d324b-534c-4847-8477-e20e0fb7e729

## Without the typo | video: `true` | easing: `easeInOutBack` |

https://github.com/woocommerce/woocommerce/assets/20469356/d270d186-0fb1-4f36-830b-fda8de85ca84

---

> I'm pre-approving, but also tagging @roykho and @thealexandrelara for additional review since they have recently worked with the gallery block and might have additional input to offer.

Thanks for the ping, @nefeline! I haven't directly worked on the jQuery slider myself, but it's good to know how things work behind the scenes 😄.

2024-05-02 15:36 UTC, thealexandrelara commented on plugins/woocommerce/client/legacy/js/flexslider/jquery.flexslider.js
> +        slider.container.css("transition-timing-funciton", easing);
I believe there is a small typo in here it should be `transition-timing-function`, right?

```suggestion
        slider.container.css("transition-timing-function", easing);
```

2024-05-05 09:42 UTC, nefeline commented
@thealexandrelara

> I noticed there's a small typo in the transition-timing-function CSS property.

Nice catch! 🙌

2024-05-06 07:29 UTC, apenchev commented on plugins/woocommerce/client/legacy/js/flexslider/jquery.flexslider.js
> +        slider.container.css("transition-timing-funciton", easing);
Fix typo.

2024-05-06 07:38 UTC, apenchev commented
> Hey @apenchev, Thanks a lot for working on this! Your contribution is very much appreciated.
> 
> I noticed there's a small typo in the `transition-timing-function` CSS property. This causes the `easing` function not to be applied when `slider.transitions` is set to false. Once you fix this, I can take another look and approve the PR.
> 
> ## With the typo | video: `true` | easing: `easeInOutBack` |
>  CleanShot.2024-05-02.at.12.24.43.mp4 
> ## Without the typo | video: `true` | easing: `easeInOutBack` |
>  CleanShot.2024-05-02.at.12.25.47.mp4 
> > I'm pre-approving, but also tagging @roykho and @thealexandrelara for additional review since they have recently worked with the gallery block and might have additional input to offer.
> 
> Thanks for the ping, @nefeline! I haven't directly worked on the jQuery slider myself, but it's good to know how things work behind the scenes 😄.

Excellent catch, thanks for checking! Commited the typo fix.

2024-05-07 18:04 UTC, thealexandrelara approved these changes
Awesome! Thank you for fixing that! I'm approving the PR ✅

2024-05-07 18:10 UTC, thealexandrelara commented
There's one thing I'd like you to do, though. Could you please use `pnpm --filter=./plugins/woocommerce changelog add` to add a changelog entry? This way, the required checks will pass and we can merge the PR.

2024-05-10 16:29 UTC, apenchev commented
@thealexandrelara Added a changelog.

2024-05-27 09:25 UTC, merged