Fix/migrate to pw
woocommerce/woocommerce pull request #46576
Opened 2024-04-15 08:38 UTC by gigitux

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-04-16 10:34 UTC, gigitux commented on plugins/woocommerce-blocks/tests/e2e/tests/price-filter/price-filter.block_theme.spec.ts
> +} );
This code was already in place

2024-04-16 12:34 UTC, WunderBart requested changes
Just a few comments!

2024-04-16 12:34 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/price-filter/price-filter.block_theme.spec.ts
> +		const postId = url.searchParams.get( 'post' );
`editor.publishPost()` returns the post ID so we can make a oneliner here:
```suggestion
		const postId = await editor.publishPost();
```

2024-04-16 12:34 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/price-filter/price-filter.block_theme.spec.ts
> +		// await page.pause();
🗑️

2024-04-16 12:34 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/price-filter/price-filter.block_theme.spec.ts
> +		await editor.canvas.locator( 'body' ).click();
We're already loading with `canvas: edit` so we should be good removing this line.

2024-04-17 14:26 UTC, WunderBart approved these changes

2024-04-26 10:07 UTC, merged