Blocks: Migrate stock filter to playwright
woocommerce/woocommerce pull request #46580
Opened 2024-04-15 09:56 UTC by gigitux

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR migrates the Stock Filter tests to the Playwright infrastructure.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Ensure that E2E tests are green.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 
Migrate Stock filter tests to Playwright

</details>

2024-04-15 23:34 UTC, wavvves reviewed
Thanks @gigitux, but there seems to be some [linting issues](https://github.com/woocommerce/woocommerce/actions/runs/8693037357/job/23839298314?pr=46580) blocking the CI

2024-04-16 07:45 UTC, gigitux commented
> Thanks @gigitux, but there seems to be some [linting issues](https://github.com/woocommerce/woocommerce/actions/runs/8693037357/job/23839298314?pr=46580) blocking the CI

Thanks, @wavvves, for catching it! 

The lining issues will be fixed with https://github.com/woocommerce/woocommerce/pull/46626

2024-04-16 09:07 UTC, WunderBart requested changes
Nice work here as well! Left just a couple of comments.

2024-04-16 09:07 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/stock-filter/stock-filter.block_theme.spec.ts
> +		await page.fill( textSelector, title );
Let's use locator.fill since page.fill is discouraged.

2024-04-16 09:07 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/stock-filter/stock-filter.block_theme.spec.ts
> +		await editor.canvas.locator( 'body' ).click();
Let's use the canvas param here:

```suggestion
		await admin.visitSiteEditor( {
			postId: 'woocommerce/woocommerce//archive-product',
			postType: 'wp_template',
			canvas: 'edit',
		} );
```

2024-04-16 09:07 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/stock-filter/stock-filter.block_theme.spec.ts
> +		} );
Same as before, let's make sure this is necessary!

2024-04-16 09:07 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/stock-filter/stock-filter.block_theme.spec.ts
> +		);
Ditto

2024-04-16 09:07 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/stock-filter/stock-filter.block_theme.spec.ts
> +		expect( domContentLoaded ).toBe( true );
...and this one as well 😄

2024-04-16 09:58 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/stock-filter/stock-filter.block_theme.spec.ts
> +		);
Are we waiting for a navigation change here, or do we want to ensure the query params are applied? If it's the latter, let's use the [toHaveURL](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-url) assertion instead:

```js
await expect( page ).toHaveURL( new RegExp( blockData.urlSearchParamWhenFilterIsApplied ) );

2024-04-17 14:28 UTC, WunderBart approved these changes

2024-04-26 13:14 UTC, merged