Add e2e tests to cover Publish dropdown options
woocommerce/woocommerce pull request #46658
Opened 2024-04-16 21:03 UTC by octaedro

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #46593.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-04-18 09:15 UTC, louwie17 requested changes
Thanks for adding this Fernando, the E2E test ran fine locally, I just think we should split it up in a couple different tests if possible?

Also in relation to your testing instructions:

> Run our E2E tests. All the tests should pass.

It be great if you could be more specific here in the future, for example: list the commands that are required for E2E tests. Not everyone on the team will be aware of how to do this and it would save the team a lot of time if they don't need to go looking for it. Linking to the E2E docs would also help.

2024-04-18 09:15 UTC, louwie17 commented on plugins/woocommerce/tests/e2e-pw/tests/merchant/products/block-editor/product-edit-block-editor.spec.js
> +test( 'can schedule a product publication', async ( { page, product } ) => {
This test schedules a product, duplicates a product and removes a product.
Should we not move these into individual tests?

2024-04-18 17:58 UTC, octaedro commented on plugins/woocommerce/tests/e2e-pw/tests/merchant/products/block-editor/product-edit-block-editor.spec.js
> +test( 'can schedule a product publication', async ( { page, product } ) => {
Good idea! Done in https://github.com/woocommerce/woocommerce/pull/46658/commits/03ac99954746babfc0b1459b4bd7c0d1c61694e4

2024-04-18 18:07 UTC, octaedro commented
Thank you @louwie17 for your review.

I updated the testing instructions and addressed the suggestion you made.
Could you take another look at this PR?

2024-04-19 13:06 UTC, louwie17 approved these changes
LGTM 🚀 Thanks for the updates @octaedro, just a small spelling mistake left but otherwise all is good.

2024-04-19 13:06 UTC, louwie17 commented on plugins/woocommerce/tests/e2e-pw/tests/merchant/products/block-editor/product-edit-block-editor.spec.js
> +	test( 'can dupicate a product', async ( { page, product } ) => {
```suggestion
	test( 'can duplicate a product', async ( { page, product } ) => {
```
Small spelling mistake

2024-04-19 13:46 UTC, merged