Track skip guided setup click
woocommerce/woocommerce pull request #47194
Opened 2024-05-06 19:21 UTC by moon0326

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR adds `coreprofiler_skip_guided_setup` track for the `skip guided setup` click.

Closes #47180 

Slack thread: p1714164814689059-slack-C06K8HHQPJ5

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new JN site with this branch.
2. When you're redirected to the core profiler, open your browser's inspector and type `localStorage.setItem( 'debug', 'wc-admin:*' );` and select `Verbose` from the log levels.
3. Make sure the usage tracking checkbox is checked.
4. Click on `Skip guided setup`
5. Confirm `recordevent wcadmin_coreprofiler_skip_guided_setup ` track gets fired.
6. Go back to the `Welcome to Woo!` page.
7. Uncheck the usage tracking checkbox.
8. Click on `Skip guided setup`
9. Confirm `recordevent wcadmin_coreprofiler_skip_guided_setup ` track does not get fired for this time.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Add track for skip guided setup click 

#### Comment 

</details>

2024-05-07 01:42 UTC, chihsuan approved these changes
Thanks, LGTM and tested well. 🚢

2024-05-07 02:01 UTC, rjchow commented
Mind if we put this issue on hold? I'll pick it up after I'm done with the v5 migration because there's a ton of changes and it'll be quite a bit of work for me to rebase if this PR is merged

2024-05-07 05:11 UTC, moon0326 commented
> Mind if we put this issue on hold? I'll pick it up after I'm done with the v5 migration because there's a ton of changes and it'll be quite a bit of work for me to rebase if this PR is merged

Yup! We can wait 👍

2024-07-25 22:15 UTC, moon0326 commented
@rjchow Hey RJ ✋ 

Just a reminder that this PR is still open 🙏 

See https://github.com/woocommerce/woocommerce/pull/47194#issuecomment-2097253994

2024-10-22 03:45 UTC, chihsuan commented
@moon0326 / @rjchow This PR has been open for a while. :sweat_smile: It seems that we need to rebase this PR. Since this PR is quite old, I think it would be better to close this PR and create a new PR. What do you think?

2024-10-22 03:57 UTC, rjchow commented
Hey @chihsuan thanks, last time I looked at it I thought I saw somewhere that we didn't want to proceed with this - but I can't find it in the linked slack thread. I'll follow up on that thread and see if it's still desired to make this change

2024-10-22 06:57 UTC, rjchow commented
Hey @chihsuan , @ilyasfoo I've updated the changes in this PR to 
1. be rebased on the new xstate v5 code
2. updated the position of the skip (discussed in p1714164814689059-slack-C06K8HHQPJ5)

2024-10-22 07:39 UTC, chihsuan approved these changes
Thanks for updating the PR! 🙌  

LGTM and confirmed the tracking events are firing as expected.

2024-10-22 13:47 UTC, ilyasfoo requested changes
@rjchow  Code looks good however I'm seeing the initial track is not actually fired since track hasn't been enabled yet:

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/66a97ab3-a832-4f75-abc5-c49bd5403ab0">

2024-10-23 07:01 UTC, rjchow commented
@ilyasfoo nice catch! That was a super sneaky one. I've moved the track firing to the entry of the skip guided setup step so that it'll definitely have resolved by then

2024-10-23 09:01 UTC, ilyasfoo requested changes
Thanks, @rjchow. However I'm still seeing the `shouldRecord` as false. I believe this is due to [`window.wcTracks.isEnabled` ](https://github.com/woocommerce/woocommerce/blob/6ca412f1ecca07fff533701e35e70e1bcffce3b5/plugins/woocommerce/includes/tracks/class-wc-site-tracking.php#L84) is false at the time of execution. You can reproduce this by deleting `woocommerce_allow_tracking` option each test

2024-10-23 10:02 UTC, rjchow commented
@ilyasfoo sorry 🙇 it's working for reals now
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/2b07782e-1cfb-4787-8cff-ebbf6aea8e82">

2024-10-23 13:33 UTC, ilyasfoo approved these changes
Thanks, tests well!

2024-10-23 14:19 UTC, merged