fixing issue https://github.com/woocommerce/woocommerce/issues/28774
woocommerce/woocommerce pull request #47217
Opened 2024-05-07 13:16 UTC by 79mplus-admin

Trimming the password before updating

### Changes proposed in this Pull Request:

Closes #28774 

### How to test the changes in this Pull Request:

1. Go to "my-account/edit-account/".
2. Change to a new password, including leading spaces.
3. Now log in again with the new password.
4. Attempt to change the password again, entering the old password with the leading spaces.
5. The password will be changed successfully. Previously, it used to give the error message "Your current password is incorrect."

2024-07-08 14:22 UTC, naman03malhotra submitted a review, later dismissed
Thanks for working on it, looks good to me. I'll move the fix to a new PR and add changelog.

2024-08-09 10:23 UTC, naman03malhotra requested changes
On a second look, we need to handle this for the login form as well, if we are trimming the password in reset form.

2024-08-09 10:24 UTC, naman03malhotra commented
Assigning review to Rubik, as the issue is assigned to the team.

2024-08-19 13:06 UTC, senadir approved these changes, later dismissed
This is looking good. I added a changelog to this.

2024-08-19 13:07 UTC, senadir commented
@naman03malhotra I'm not sure what you mean by supporting this at login? logging in works fine with spaces before and after this PR.

2024-08-19 17:32 UTC, naman03malhotra commented
>I'm not sure what you mean by supporting this at login? logging in works fine with spaces before and after this PR.

you are correct, I confused it with admin login, ignore my comment.

2026-08-14 17:58 UTC, nerrad commented
I don't think a strong enough case has been made for why this change should be implemented along with the implications of what has been proposed (it's not good). There needs to be good evidence of security/compatibility here and I don't see it. Also the PR description links to a non-existent issue.

2026-08-14 17:58 UTC, closed without merging