CYS: allow to the user to move the pattern
woocommerce/woocommerce pull request #47322
Opened 2024-05-09 14:10 UTC by gigitux

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-05-13 08:54 UTC, albarin commented
@gigitux Thanks for working on this, I'm seeing a few issues:
1. In the first template sidebar preview there are some errors.
2. When I change to the second template and come back to the first, some headers and texts have disappeared.
3. When entering the assembler the first time, there's no toolbar to move the patterns, it only appears when clicking on another template and coming back to the first.

https://github.com/woocommerce/woocommerce/assets/186112/c97d9a04-6bf3-4047-bd4c-e5cb8d3afd53

2024-05-13 08:57 UTC, gigitux commented
> @gigitux Thanks for working on this, I'm seeing a few issues:
> 
> 1. In the first template sidebar preview there are some errors.
> 2. When I change to the second template and come back to the first, some headers and texts have disappeared.
> 3. When entering the assembler the first time, there's no toolbar to move the patterns, it only appears when clicking on another template and coming back to the first.
> 
>  CleanShot.2024-05-13.at.10.47.30.mp4

Thanks, @albarin, for the review!

1 & 2 are not specifically related to this PR. It looks like there is a regression on Gutenberg (you have the same issue if you try Gutenberg's trunk). We have to double-check!

> When entering the assembler the first time, there's no toolbar to move the patterns, it only appears when clicking on another template and coming back to the first.

The UX about the toolbar will be handled in another issue: https://github.com/woocommerce/woocommerce/issues/47371

2024-05-13 09:06 UTC, albarin approved these changes

2024-05-13 10:36 UTC, nefeline requested changes

2024-05-13 10:36 UTC, nefeline commented on plugins/woocommerce-admin/client/customize-store/assembler-hub/block-preview.tsx
> +import { IS_TOOLBAR_ENABLED_FEATURE_FLAG } from './toolbar/feature-flag';
Can you please update this feature flag to rely on our newly introduced `pattern-toolkit-full-composability` ? https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/admin/config/core.json#L22

2024-05-13 12:01 UTC, gigitux commented on plugins/woocommerce-admin/client/customize-store/assembler-hub/block-preview.tsx
> +import { IS_TOOLBAR_ENABLED_FEATURE_FLAG } from './toolbar/feature-flag';
Yes! I updated it with [f58d81c](https://github.com/woocommerce/woocommerce/pull/47322/commits/f58d81ce32b99e421e12c4dfc3b44ccdb1acd3e7).

Let me know if I can merge this PR!

2024-05-13 20:55 UTC, nefeline commented
> It looks like there is a regression on Gutenberg (you have the same issue if you try Gutenberg's trunk). We have to double-check!

Could we investigate if this issue is indeed a consequence of a regression on GB and not from this PR?

2024-05-13 20:57 UTC, nefeline commented on plugins/woocommerce-admin/client/customize-store/assembler-hub/block-preview.tsx
> +import { IS_TOOLBAR_ENABLED_FEATURE_FLAG } from './toolbar/feature-flag';
Thanks. I've left some additional questions related to the issues found during the code review.

2024-05-14 07:28 UTC, gigitux commented
> Could we investigate if this issue is indeed a consequence of a regression on GB and not from this PR?

I checked the WooCommerce trunk branch, and I'm able to reproduce the issue :)

2024-05-16 11:30 UTC, nefeline commented
Thanks for the updates @gigitux ! Sharing here my test results:

- Whenever accessing the editor with the GB plugin disabled, I'm greeted with an error:

<img width="1228" alt="Screenshot 2024-05-16 at 13 09 09" src="https://github.com/woocommerce/woocommerce/assets/15730971/6d2a0aa9-2b6b-4138-9ee5-37e98b0ec43e">

Could we make a change to prevent this?

> I checked the WooCommerce trunk branch, and I'm able to reproduce the issue :)

Cool, thanks: do you think its worth creating issues for these two? Maybe you already did, but flagging anyways just to make sure we are on the same page:

> - In the first template sidebar preview there are some errors.
> - When I change to the second template and come back to the first, some headers and texts have disappeared.

2024-05-16 11:58 UTC, gigitux commented
> In the first template sidebar preview there are some errors.

This one is tracked by https://github.com/woocommerce/woocommerce/issues/47469!

> When I change to the second template and come back to the first, some headers and texts have disappeared.

I'm not able to replicate it:
https://github.com/woocommerce/woocommerce/assets/4463174/2b247dc3-887e-47c2-a3c5-3b4f083f161b

2024-05-17 07:57 UTC, nefeline commented
Thanks!

> I'm not able to replicate it:

Hm, yeah, I can't replicate it either. But I can replicate on this PR the same issue observed on https://github.com/woocommerce/woocommerce/pull/47356 regarding the scroll:

https://github.com/woocommerce/woocommerce/assets/15730971/4062ac47-95d9-4ee5-89f3-6c3e2d824b32

Just to confirm: do we have an issue open to solve this problem, in particular? If we do and we can prioritize it, I'm a-ok with approving/merging this PR 👌

2024-05-17 08:01 UTC, nefeline commented
Ah: can you also please update the description of this PR so it accounts for the changes on the feature flag & the fact that the PR on GB has already been merged? Thanks!

2024-05-17 09:39 UTC, gigitux commented
> Just to confirm: do we have an issue open to solve this problem, in particular? If we do and we can prioritize it, I'm a-ok with approving/merging this PR 👌

I created a dedicated issue: https://github.com/woocommerce/woocommerce/issues/47570 - are you able to reproduce this issue on https://github.com/woocommerce/woocommerce/pull/47415?


> Ah: can you also please update the description of this PR so it accounts for the changes on the feature flag & the fact that the PR on GB has already been merged? Thanks!

Done! Thanks for the review!

2024-05-23 07:49 UTC, nefeline commented
> Done! Thanks for the review!

Thanks @gigitux ! Do you mind double-checking the testing instructions to see if they are accurate? I'm still seeing references to IS_TOOLBAR_ENABLED_FEATURE_FLAG.

2024-05-23 08:12 UTC, nefeline commented
Thanks for updating the PR testing instructions again 🙏 

The notes I have here are very similar to the ones I shared on https://github.com/woocommerce/woocommerce/pull/47356#pullrequestreview-2068526586

1- I think this was mentioned here earlier, but whenever clicking on "Design your homepage" for the very first time, the toolbar to move patterns is not displayed on the first template.
2. Even after the user leaves the "Design your homepage" section, they can still see the tooltip to move the patterns.

I'm ok with addressing those separately, as long as we have issues to solve the aforementioned problems.

Regarding the scroll problem:

> are you able to reproduce this issue on https://github.com/woocommerce/woocommerce/pull/47415?

No, I'm not able to reproduce on #47415 : does this mean that you solved the problem via 47415? If yes, it would be nice to document those things here on this PR so the reviewers are aware of known issues and how they are being solved.

2024-05-23 08:21 UTC, gigitux commented
> No, I'm not able to reproduce on #47415 : does this mean that you solved the problem via 47415? If yes, it would be nice to document those things here on this PR so the reviewers are aware of known issues and how they are being solved.

I changed nothing in the specific, so I'm not sure. It is better to keep the issue open.

> 1- I think this was mentioned here earlier, but whenever clicking on "Design your homepage" for the very first time, the toolbar to move patterns is not displayed on the first template.

https://github.com/woocommerce/woocommerce/issues/47752

> 2. Even after the user leaves the "Design your homepage" section, they can still see the tooltip to move the patterns.

https://github.com/woocommerce/woocommerce/issues/47751

2024-05-23 08:48 UTC, nefeline commented
> I changed nothing in the specific, so I'm not sure. It is better to keep the issue open.

Do you think you can determine whether this PR introduces this bug? I'm concerned about approving it, merging it as-is, and then not being able to scroll up and down in the frame anymore. This type of bug can block us from doing other unrelated work down the line.

2024-05-23 15:56 UTC, gigitux commented
> > I changed nothing in the specific, so I'm not sure. It is better to keep the issue open.
> 
> Do you think you can determine whether this PR introduces this bug? I'm concerned about approving it, merging it as-is, and then not being able to scroll up and down in the frame anymore. This type of bug can block us from doing other unrelated work down the line.

I fixed it with [8a41f71](https://github.com/woocommerce/woocommerce/pull/47322/commits/8a41f7128e9aa4a14303a5adf25439e3ab4d6400)

2024-05-24 06:23 UTC, nefeline commented
> I fixed it with https://github.com/woocommerce/woocommerce/commit/15564d2b206f4625c0daceca7450a2b5efcce639

Thanks: I did a test, but unfortunately, this didn't fix the bug: it is still impossible to scroll up and down. To reproduce click on the second template: as soon as the taskbar with the move button is displayed, the frame freezes, and it is impossible to scroll.

2024-05-27 16:39 UTC, nefeline approved these changes
Registering here for future reference that additional tests were made, and of 3 different WordPress installs, I was able to repro the issue in one of them. https://github.com/woocommerce/woocommerce/issues/47855 has been created to keep an eye on this as there might be certain conditions to trigger it that were just not uncovered yet, given the consistency of the freeze.

2024-05-28 06:55 UTC, merged