Fix/related products options
woocommerce/woocommerce pull request #47845
Opened 2024-05-27 11:00 UTC by kmanijak

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-05-27 21:43 UTC, thealexandrelara requested changes
Thank you for working on this! Everything is working as expected. Considering the upgrade notice and the advanced filters require specific conditions to appear, it would be great if you could include an E2E test covering them 🙌 .

2024-05-29 09:31 UTC, kmanijak commented
> Considering the upgrade notice and the advanced filters require specific conditions to appear, it would be great if you could include an E2E test covering them 🙌 .

Added E2E test! @thealexandrelara can I ask you for re-review?

2024-05-29 16:23 UTC, thealexandrelara requested changes, later dismissed
Hey @kmanijak, thanks for adding the E2E tests . I noticed that the E2E tests are failing to run because you're using `editorUtils`, which seems no longer available. So, I believe you should be using `editor` instead, I commented in the code on the places you can replace it.

2024-05-29 16:23 UTC, thealexandrelara commented on plugins/woocommerce-blocks/tests/e2e/tests/related-products/related-products.block_theme.spec.ts
> +		editorUtils,
It seems that `editorUtils` does not exist anymore so it's causing an error in the E2E tests. You should use `editor` instead.

```suggestion
```

2024-05-29 16:23 UTC, thealexandrelara commented on plugins/woocommerce-blocks/tests/e2e/tests/related-products/related-products.block_theme.spec.ts
> +		);
You can use `editor` here:

```suggestion
		const relatedProducts = await editor.getBlockByName(
			blockData.slug
		);
```

2024-05-29 16:23 UTC, thealexandrelara commented on plugins/woocommerce-blocks/tests/e2e/tests/related-products/related-products.block_theme.spec.ts
> +		const productsBeta = await editorUtils.getBlockByName( querySlug );
This should be replaced by `editor`:

```suggestion
		const productsBeta = await editor.getBlockByName( querySlug );
```

2024-05-29 16:23 UTC, thealexandrelara commented on plugins/woocommerce-blocks/tests/e2e/tests/related-products/related-products.block_theme.spec.ts
> +		await editorUtils.enterEditMode();
This should be `editor`:

```suggestion
		await editor.enterEditMode();
```

2024-05-31 09:24 UTC, kmanijak commented
> Hey @kmanijak, thanks for adding the E2E tests . I noticed that the E2E tests are failing to run because you're using editorUtils, which seems no longer available. So, I believe you should be using editor instead, I commented in the code on the places you can replace it.

Oh, I merged `trunk` and didn't realize there was such change! Thanks for pointing it out and sorry I tagged you for re-review with the failing tests 😅 Now, can I ask for (hopefully) final re-review @thealexandrelara ?

2024-05-31 10:05 UTC, WunderBart commented on plugins/woocommerce-blocks/tests/e2e/tests/single-product-template/single-product-template-compatibility-layer.spec.ts
> +	for ( const scenario of singleOccurranceScenarios ) {
nit: 
```suggestion
	for ( const scenario of singleOccurrenceScenarios ) {
```

2024-06-04 09:46 UTC, imanish003 approved these changes
I tested the changes & verified that Advanced filters and Upgrade Notice aren't visible in the Related Products block. Thanks for quickly fixing this 🚀

2024-06-04 09:51 UTC, merged