Fix product tracks when importing
woocommerce/woocommerce pull request #47857
Opened 2024-05-27 16:55 UTC by octaedro

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

We trigger the `product_edit` and `product_add_publish` when a product published. This also happens when products are imported, generating a weird spike of edit/publish events that makes the data more difficult to analyze.

This PR modifies the source prop to set it as `bulk-import` to filter those products from the analysis results.

Closes #47107.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a new WooCommerce store and install the WooCommerce Beta Tester from the mono repo
2. Make sure you have tracking enabled under **WooCommerce > Settings > Advanced > WooCommerce.com > Enable tracking**
3. Go to **Products > All products** and click **Import**
4. Import the CSV available within the mono repo: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/sample-data/sample_products.csv
5. Finish the importing
6. Go to **WooCommerce > Status > Logs** and open the tracks log ( only created if the beta tester is enabled )
7. Notice the events `product_edit` and `product_add_publish` for each imported product have the source prop set as `bulk-import`.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

#### Comment 

</details>

2024-05-27 17:14 UTC, octaedro commented
Hi @pmcpinto,

Could you confirm that the solution proposed here solves the problem correctly?

2024-05-28 09:12 UTC, louwie17 requested changes
This tested well, but set it to request changes for two things:
- We should double check with @pmcpinto first to see if changing the `source` is the best method, or not triggering it all is better.
- Just want to double check if checking the post action is the most reliable solution?

2024-05-28 09:12 UTC, louwie17 commented on plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php
> +			return true;
Do you know if this is the only way to check if an import is happening? Or does the importer also set a global variable?
I am ok with this, but just wanted to double check if there are other ways.
Initially I thought someone could also import using the CLI, but looks like that is not the case.

2024-05-28 14:34 UTC, octaedro commented on plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php
> +			return true;
@louwie17 I couldn't find a better way to know that the importation was happening. Maybe we can add a transient when the process starts/finishes, but I'm not sure that it would be a better solution than relying on the `action`.

> Initially I thought someone could also import using the CLI, but looks like that is not the case.

As far as I know, there's no out-of-the-box way to do it with CLI.

2024-05-28 14:55 UTC, louwie17 commented on plugins/woocommerce/includes/tracks/events/class-wc-products-tracking.php
> +			return true;
Gotcha, yeah than the current approach seems like the easiest and best option. Thanks for looking into alternatives.

2024-05-29 13:53 UTC, louwie17 approved these changes
LGTM 🚀 This tested well and code looks good, thanks @octaedro

2024-05-29 13:54 UTC, merged