Add new buttonAttributes API to style express checkout buttons coherently
woocommerce/woocommerce pull request #47899
Opened 2024-05-28 14:27 UTC by alexflorisca

### Changes proposed in this Pull Request:

This PR adds some extra controls to the express checkout block in order to synchronise the styles of ALL express payment buttons. 

**Key things included**
- Introduce a new toggle which will override the payment extension specific settings with settings defined in the express checkout block
- Introduce `Button Size` and `Border Radius` attributes on the Express Checkout block that merchants can tweak and apply to all buttons.
- Expose a `darkMode` setting to give a hint to payment extensions as to what color they may want to render their buttons
- These will be enabled by default, merchants can switch them off if they like, and keep the payment extension settings
- Some improvements to the editor side of the express checkout block to better contain and align the payment buttons

**Not included**
- Label - every payment provider has different requirements for the button labels, so we cannot synchronise these
- Color - again every button renders different colors. The best we can do is to provide a hint as to wether the theme has a light or dark background (via the `darkMode` prop) and let payment extensions use this as they wish.

**API**
These settings are exposed to third party payment extensions through the props passed to the express payment buttons [here](https://github.com/woocommerce/woocommerce/blob/5c980cc6299af86ed18bb8cb10695364467db761/plugins/woocommerce-blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.js#L146). A new `buttonAttributes` property will be available, with the following signature:

```js
{
  height: string,
  borderRadius: string,
  darkMode: bool
}
```

For example 

```js
{
  height: '40',
  borderRadius: '4',
  darkMode: true
}
```
Note that the height and borderRadius properties do not include the `px` prefix. This is to align with the way existing payment extensions store similar settings.

Fixes #48810.
Fixes #47175.

### How to test the changes in this Pull Request:

#### User Testing
This PR relies on parallel work from other plugins, and cannot be tested properly without running other plugins locally on a specific branch (see below)

#### Developer Testing 

In order to test this PR properly, we rely on parallel work from [WooCommerce Stripe Gateway](https://github.com/woocommerce/woocommerce-gateway-stripe) and [WooCommerce Payments](https://github.com/Automattic/woocommerce-payments). The corresponding code lives on the `try/poc-express-checkout-button-styles` branches in both plugins. 

**Prerequisites**
1. Install both [WooCommerce Stripe Gateway](https://github.com/woocommerce/woocommerce-gateway-stripe) and [WooCommerce Payments](https://github.com/Automattic/woocommerce-payments) plugins
2. Checkout the `try/poc-express-checkout-button-styles` branches and build the front-end assets
3. Install the [WooCommerce Payments Dev Tools plugin](https://github.com/Automattic/woocommerce-payments-dev-tools). 
4. Check the `Force the platform_checkout_eligible flag (aka WooPay eligible) in the account cache to be` setting and set it to `true`
5. Check the `Enable the WooPay Express Checkout button` box

**Test the Checkout Page**
1. Make sure you meet the conditions for either Google or Apple Pay and visit the checkout page in the front-end to make sure the buttons display.
2. You should see 2 Google/Apple Pay buttons and the Woo Pay button.
3. Check the buttons all look ok, have a height of 48px and are rendered inside a grid as list items.
4. Visit the Checkout page in the editor
5. Click inside the Express Checkout Block. In the right sidebar, you should see a toggle (should be on) called `unify button styles`
6. Check the button size attribute is set as `Medium (48px)` and the border radius is set as `4px`. 
7. Change the button size to `Large (55px)`.
8. Check that the height of the buttons inside the editor change to the same value.
9. Click Save
10. Visit the checkout page on the front-end again.
11. Check the height of the buttons matches the setting (55px). 
12. Border radius is not yet implemented by these payment extensions, but will be in the future

**Test the Cart page**
1. Visit the Checkout page in the editor again
2. Change the button height to `Small (40px)`
3. Again check that the height of the buttons inside the editor change to the same value.
4. Click Save.
5. Visit the Cart Page on the front end
6. You should see the same 3 buttons as on the checkout page
7. Make sure they are stacked and display with a height of `40px`.

**Test the layout changes in the editor**
1. Install and activate the [WooCommercePayPal Payments Plugin](https://github.com/woocommerce/woocommerce-paypal-payments).
2. Enable at least 1 PayPal button
3. Visit the Checkout page in the editor
4. Try to click on any of the express checkout buttons. It shouldn't be possible.
5. Check that no buttons are overflowing out of their containers

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Adds unified styles for the express checkout block
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-07-30 09:19 UTC, alexflorisca commented on plugins/woocommerce-blocks/assets/js/blocks/cart-checkout-shared/payment-methods/test/express-payment-methods.tsx
> +	describe.skip( 'Payment methods available', () => {
I will get the tests working in another PR, skipping for now. I think this is ok as there were no tests to start with so this would be an addition anyway

2024-08-01 14:12 UTC, senadir commented
It would be much easier if you can provide a ZIP to said branches for testing.

2024-08-01 15:27 UTC, senadir commented
Here are built ZIP for those branches:

Stripe: [woocommerce-gateway-stripe.zip](https://github.com/user-attachments/files/16458572/woocommerce-gateway-stripe.zip)

WooPayment: [woocommerce-payments.zip](https://github.com/user-attachments/files/16458634/woocommerce-payments.zip)

2024-08-01 15:51 UTC, senadir requested changes
Upon load for Stripe, this is what I'm seeing:

<img width="608" alt="image" src="https://github.com/user-attachments/assets/f6b1cd4e-1757-4578-adeb-8b7a3595cbba">

Once I disable the styles, it looks fine but weirdly large

<img width="592" alt="image" src="https://github.com/user-attachments/assets/58f8611d-b7e8-4e45-8fab-0ad402ab3a2a">

The size input is a simple text input that doesn't support arrows, unlike other Gutenberg inputs

<img width="269" alt="image" src="https://github.com/user-attachments/assets/22b824f2-ff44-4734-8764-8f333cc510c9">


Beyond that on the frontend, I didn't manage to get 2 buttons to show up, they seem to respect size but not border radius.

2024-08-01 15:51 UTC, senadir commented on plugins/woocommerce-blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx
> +	const buttonAttributes = showButtonStyles
why do we need to toggle showButtonStyles?

2024-08-01 15:51 UTC, senadir commented on plugins/woocommerce-blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx
> +		: undefined;
Why not always pass the object with default values.

2024-08-05 11:47 UTC, alexflorisca commented on plugins/woocommerce-blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx
> +	const buttonAttributes = showButtonStyles
Because we want to give merchants the ability to be able to disable these "global" styles, in favour of payment extension specific ones.

2024-08-05 11:49 UTC, alexflorisca commented on plugins/woocommerce-blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx
> +		: undefined;
See comment above. We want a state where these styles are disabled, and buttons would respect payment specific settings instead.

2024-08-05 13:48 UTC, alexflorisca commented
> The size input is a simple text input that doesn't support arrows, unlike other Gutenberg inputs
The reason I used a normal text input instead of that one, is because the value needs to always be pixel, and the `HeightControl` component (which is the screenshot you showed) doesn't have a way to  just specify pixels. So a merchant could select `rem, em, %, etc, when you click on the `px` value. I agree with you, it's not ideal but we can improve on this in a future PR.

> Upon load for Stripe, this is what I'm seeing:
The preview images weren't aligned properly so I've centered them in the container. Good spot. They might still look big, because they are set to `width: 100%, height: auto` . And the containers are now wider, so they may display bigger than before. But the height is capped. This isn't perfect either, but this PR aims to improve over what's there at the moment, and I think this is much better. We can address any other optimisations and edge case scenarios in future PRs.

I've also made a change so the height of the buttons is capped to `48px` when the styles are disabled. Ideally we would pull in the styles from each specific payment extension here, but it's not really possible/easy, so I think this is an ok middle ground for now.

If you can take another look and let me know, that'd be great 👍

2024-08-07 11:53 UTC, senadir approved these changes
Shifting up sizes seems to work well for WooPay but not Apple Pay

<img width="613" alt="image" src="https://github.com/user-attachments/assets/7acb152c-705c-4db9-9047-cb74082b5df8">
<img width="609" alt="image" src="https://github.com/user-attachments/assets/859cd199-37c6-40bc-98bf-7fead86b5abd">


Applying border radius also only works for WooPay

<img width="604" alt="image" src="https://github.com/user-attachments/assets/1db6c340-2481-486c-aced-49f639a4b119">

Settings are not respected in the frontend

<img width="679" alt="image" src="https://github.com/user-attachments/assets/6d372b21-021a-43b8-8893-e96858efbdf2">

I understand this is not yet perfect but I'm a bit worried about shipping something that's broken out of the box, would it make sense to mark this as beta, or have it be opt in?

2024-08-07 11:54 UTC, senadir commented
Dark mode works in frontend but no the editor for some reason:

<img width="606" alt="image" src="https://github.com/user-attachments/assets/1cd9afd8-c60e-4d6a-bd0c-c2fa38f24f6b">

2024-08-14 09:43 UTC, alexflorisca commented
> Shifting up sizes seems to work well for WooPay but not Apple Pay

> Applying border radius also only works for WooPay

I've pushed a fix which improve the handling of images in the editor, and should adhere better to the height and borderRadius controls, although this won't be perfect. Additionally, borderRadius is only supported by WooPay currently, but will be available soon for Google/Apple Pay within WooPayments, and the WooCommerce Stripe Gateway once they are switched to the new ECE API.

> Settings are not respected in the frontend

There is currently a limitation in that payment extensions are rendering images in the editor and the actual buttons in the front-end. Within the editor, the height and borderRadius are applied to the container element, to simulate what the front-end would look like. Because of this, it's not a fully accurate representation of the front-end, and some buttons are yet to implement support for borderRadius for example.

This will be solved in the next chunk of work on this, which will be to render the express buttons inside the editor. 

> Dark mode works in frontend but no the editor for some reason:

Again this is because in the editor, images are rendered rather then. the buttons.

 Nadir and I had a conversation and addressed some of concerns mentioned on slack in this thread for more context (p1723030074907399-slack-C8X6Q7XQU).

I decided to merge this for now, as it is already a big improvement over what's there already, and carry on the work of optimising the editor in future PRs

2024-08-14 10:02 UTC, merged