Override product name height and font-size
woocommerce/woocommerce pull request #47979
Opened 2024-05-29 21:02 UTC by octaedro

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #47478.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

#### Comment 

</details>

2024-06-03 18:16 UTC, mdperez86 requested changes
Hey @octaedro nice job here!

I left one comment, since I think we should not use the `!important` constraint in css.

2024-06-03 18:16 UTC, mdperez86 commented on packages/js/product-editor/src/blocks/product-fields/name/editor.scss
> +	.components-input-control {
```suggestion
	.components-base-control .components-input-control__container {
		.components-input-control {
			&__input {
				font-size: $grid-unit-20;
				min-height: $grid-unit-60;
			}
			&__suffix {
				margin-right: 0;
			}
		}
	}
```

With this you don't need to use `!important` anymore.

2024-06-04 13:10 UTC, octaedro commented on packages/js/product-editor/src/blocks/product-fields/name/editor.scss
> +	.components-input-control {
Good call! Thank you @mdperez86  for the suggestion!

2024-06-04 13:11 UTC, octaedro commented
@mdperez86 Could you take another look at this PR?

2024-06-04 19:04 UTC, mdperez86 approved these changes
LGTM @octaedro nice job!!!

2024-06-04 19:40 UTC, merged