Replace truthy check with isset when setting default checkout field value
woocommerce/woocommerce pull request #48031
Opened 2024-05-31 01:35 UTC by jkudish

<details>
<summary>### Submission Review Guidelines:</summary>

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

</details>

### Changes proposed in this Pull Request:

This allows a falsey checkout field value to be set. Without this change, you aren't able to use the `woocommerce_get_default_value_for_{key}` filter to set a falsey value on a checkbox (i.e. to uncheck it dynamically) 

Fixes the issue i reported in https://github.com/woocommerce/woocommerce/issues/48030

### How to test the changes in this Pull Request:

See the reproduction steps in https://github.com/woocommerce/woocommerce/issues/48030

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

2024-05-31 11:16 UTC, senadir commented
Approved tests, let's see if this breaks anything, I assume it doesn't.

2024-05-31 11:28 UTC, senadir commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +			if ( isset($value) ) {
```suggestion
			if ( isset( $value ) ) {
```

2024-05-31 11:29 UTC, opr requested changes
Hi @jkudish thanks a lot for the PR! The change makes sense, but just a few small things to improve:

- We should ensure the [WP Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#space-usage) are being followed
- Please could you write a line for the changelog? You can do `pnpm --filter=@woocommerce/plugin-woocommerce changelog add` on the command line to get this file automatically generated and then commit that.
- While the reproduction steps in https://github.com/woocommerce/woocommerce/pull/48031 are good, it would be really helpful to have the steps copied here as well (just makes it that little bit easier for testers)

Again, thanks for the submission, and let us know if you need a hand with any of the above 🙇🏼

2024-05-31 11:29 UTC, opr commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +			if ( isset($value) ) {
```suggestion
			if ( isset( $value ) ) {
```

2024-05-31 11:29 UTC, senadir commented
This PR needs a change log, the initial template should have included a checkbox and message place to auto generate that.

2024-05-31 20:44 UTC, jkudish commented
Hi @opr and @senadir,

Thanks for the quick responses, much appreciated!

> This PR needs a change log, the initial template should have included a checkbox and message place to auto generate that.

My apologies - i think I had accidentally removed that when creating the PR. I've re-added that now and the github actions picked up on it but sadly still failed:

![image](https://github.com/woocommerce/woocommerce/assets/260253/f4872a16-cd17-493f-b0df-b5704be46594)

> Please could you write a line for the changelog? You can do pnpm --filter=@woocommerce/plugin-woocommerce changelog add on the command line to get this file automatically generated and then commit that.




> We should ensure the [WP Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#space-usage) are being followed
> While the reproduction steps in https://github.com/woocommerce/woocommerce/pull/48031 are good, it would be really helpful to have the steps copied here as well (just makes it that little bit easier for testers)

Both also taken care of 👍🏼

2024-06-05 19:17 UTC, jkudish commented
Hi @opr and @senadir, anything else required here to get this merged? :)

2024-06-06 08:54 UTC, opr approved these changes
Thanks @jkudish this is looking good now, I made a small adjustment to the testing steps. Really appreciate your PR and patience on this! 🙇🏼

2024-06-06 08:55 UTC, merged

2024-06-06 20:57 UTC, jkudish commented
Awesome, thank you @opr ! :)

2024-06-07 05:25 UTC, jkudish commented
@opr Thank you again for merging this!

Do you know which version of WooCommerce this will end up in? 8.9.3? 9.0.0-rc2? 9.1? I'll need to make the new code that we're using this in be aware of the version this is fixed in :)

No worries if that's unknown for now, I can keep an eye out, but thought I'd ask!

Cheers

2024-06-07 09:09 UTC, opr commented
@jkudish no problem! It will ship with WooCommerce 9.1 which is scheduled for release on 9th July

If you do another PR in future and have the same question, the Milestone value on the PR's sidebar will let you know what release it will be part of.

<img width="325" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/264bff4b-5180-4db0-aea5-da2f882330d7">

2024-06-07 19:01 UTC, jkudish commented
Ah perfect, I missed that will know for next time, thank you again @opr  :)