[WIP] Migrate Checkout StateInput and CountryInput to native `<select>`
woocommerce/woocommerce pull request #48180
Opened 2024-06-05 12:07 UTC by samueljseay

### Changes proposed in this Pull Request:

TBD

### How to test the changes in this Pull Request:

TBD

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-06-13 04:27 UTC, samueljseay commented
Hey @opr @senadir while there is still a little bit of work to do and a question in the air about validation, I really need someone to start reviewing the implementation so we can catch any early problems. Most of the work is done.

Right now I will work on fixing the e2e tests in the meantime.

2024-06-14 15:55 UTC, opr reviewed
Hi @samueljseay - looks like some extra commits got brought in here 👀  therefore I didn't do a code review, however I did check out the functionality and it seems great!

The list feels a little long when all the countries are displayed, but I don't know if we can shorten it to show fewer options at once?
<img width="1059" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/b9b86b90-3a9b-4e5f-846b-fdd441dc4023">

I also noticed a small styling issue after autofilling, there's a small blank space at the bottom of the input

<img width="887" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/ea42976e-cefb-4060-8ae7-6faa2c75a24e">

please re-request review once the merge has been fixed!

2024-06-15 01:10 UTC, samueljseay commented
@opr Yes, sorry about that, this branch is a branch from the cart checkout bundle work so when I updated that branch wth trunk this one got out of date. fixed now. Thanks for the review, I'll explore what you've mentioned here.

2024-06-15 11:18 UTC, opr commented
Noting that this PR also closes https://github.com/woocommerce/woocommerce/issues/44653 - I've updated the PR body.

2024-06-18 17:28 UTC, nielslange reviewed
Thanks for working on this, @samueljseay. I've successfully tested this PR. The code changes look good as well, but it would be great to get a second review from @opr and @senadir.

2024-06-21 15:10 UTC, nielslange requested changes
I noticed two CSS lint errors and one of the JS unit tests is failing as it still checks against `Combobox`. I also noticed that some blocks e2e tests failed running. I'll trigger them again now.

2024-06-21 15:10 UTC, nielslange commented on plugins/woocommerce-blocks/assets/js/base/components/select/style.scss
> +		border-radius: $universal-border-radius;
This definition is a duplicate of line 5.

2024-06-21 15:10 UTC, nielslange commented on plugins/woocommerce-blocks/assets/js/base/components/select/style.scss
> +		transform: translateY(15%) scale(0.75);
This `transform` statement overwrites the one from line 47.

2024-06-21 17:25 UTC, senadir submitted a review, later dismissed
I did a quick test for this and styles seems to be broken slightly, the outline is smaller than the actual button, and the select starts a bit too high.

I'm using 2024 with a small font size.

<img width="663" alt="image" src="https://github.com/woocommerce/woocommerce/assets/6165348/1dd23c49-b0f3-46f4-a47b-58abea9d539b">

2024-06-26 03:35 UTC, samueljseay commented on plugins/woocommerce-blocks/assets/js/base/components/select/style.scss
> +		transform: translateY(15%) scale(0.75);
Thanks, that's what I get for copy paste 😅

2024-06-26 03:41 UTC, samueljseay commented
@senadir apologies for the styling regression that slipped in there. I've addressed that now

2024-06-26 03:42 UTC, samueljseay commented on plugins/woocommerce-blocks/assets/js/base/components/select/style.scss
> +		border-radius: $universal-border-radius;
Thanks for spotting this!

2024-07-01 00:21 UTC, samueljseay commented
@nielslange @senadir this is ready for re-review. Styling issue fixed and most of the additional changes are refactoring of e2e tests

2024-07-01 14:15 UTC, nielslange requested changes
I noticed that the global styles are no longer applied to the native `<select>` fields:

<table>
<tr>
<td valign="top">Cart block:
<br><br>
<img width="451" alt="Screenshot 2024-07-01 at 16 10 36" src="https://github.com/woocommerce/woocommerce/assets/3323310/02718636-9ded-4d33-992d-63070595f437">
</td>
<td valign="top">Checkout block:
<br><br>
<img width="831" alt="Screenshot 2024-07-01 at 16 11 01" src="https://github.com/woocommerce/woocommerce/assets/3323310/c9f6a1a6-7248-452d-97aa-415281338c3a">
</td>
</tr>
</table>

The screens above show the Rust styles of the Twenty Twenty-Four theme. I expect the following elements to appear in red:

- Text color, e.g. Germany
- Border color on focus
- Chevron color

2024-07-01 21:30 UTC, samueljseay commented
Thanks @nielslange ! thats great spotting. will fix.

2024-07-01 23:39 UTC, samueljseay commented
@nielslange I've addressed the theming issue in https://github.com/woocommerce/woocommerce/pull/48180/commits/180834279d7736c5e3918b1c3f2b4f62d545d537

2024-07-02 10:04 UTC, nielslange approved these changes
Thanks for addressing my previous feedback, @samueljseay. I've tested the PR successfully and found no issues in the code. Unless @opr or @senadir spot anything, I'd say let's ⛴️ this change.

2024-07-02 14:51 UTC, senadir reviewed
All is testing fine, one thing that seem to have regressed is that State is no longer 50% (or respecting that style, or getting).

In trunk, State is a half field, in this branch, it's always 100%.

<img width="664" alt="Screenshot 2024-07-02 at 4 49 03 PM" src="https://github.com/woocommerce/woocommerce/assets/6165348/9f8f840b-e153-4975-8455-0520b5e4fe49">
<img width="738" alt="Screenshot 2024-07-02 at 4 47 51 PM" src="https://github.com/woocommerce/woocommerce/assets/6165348/372a9636-6c96-4c83-9b60-685c8d4fc80d">

2024-07-03 08:30 UTC, samueljseay commented
Thanks @senadir for spotting that. I have changed the select to apply passed down classname to the top level element of the select component instead to fix this, this will work with the existing class better because it applies flex and half width to the component. I tested with this change and it now looks correct to me. Would you mind taking another look? 🙇🏻 Thanks for your time reviewing this.

2024-07-12 21:17 UTC, merged