Using new coupon_info metadata, if it exists, to determine the actual coupon id
woocommerce/woocommerce pull request #48262
Opened 2024-06-07 11:18 UTC by davefx

Changes to make use of the new coupon_info meta data, if it exists, to determine the actually-used coupon.

If coupon_info meta data doesn't exist, I'm also adding an extra filter so, in case there are more than one active coupons with the same name, we filter out the ones that were created after the order.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #48260  .

### How to test the changes in this Pull Request:

1. Generate a coupon with an expiry date in the past with a defined coupon code.
2. Generate another coupon without expiry date, but with the same coupon code as the one created in the previous step.
3. Complete a purchase using the coupon code. The applied coupon is the last-created one.
4. Visit the order edition page in the backend. The coupon link should points to the last-created coupon, the actually used one, and not the first one.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Fix the order-items view for coupons, so we show the actually-used coupon info, if it exists.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-06-12 07:47 UTC, Konamiman requested changes
Hi @davefx, thanks for your contribution. Your fix tests well, however I'd like to request a couple of small changes:

1. [WordPress coding standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/) disallow assignments placed directly inside conditionals (search for "Assignments must not be placed in conditionals" in the page). Please split the `if ( $coupon_info = $item->get_meta( 'coupon_info' ) )` in two separate lines, one for the assignment and then another for the conditional.

2. It seems that your testing instructions aren't covering this part:

> I'm also adding an extra filter so, in case there are more than one active coupons with the same name, we filter out the ones that were created after the order

Could you please add some additional testing steps for this case?

2024-06-12 09:50 UTC, davefx commented
Hi, @Konamiman 

I just made the change to adapt the code to the Coding Standard.

About the extra steps to test the change in the SQL query, I'm not sure: the else branch of the if clause will only be executed for orders created with old versions of WooCommerce (as all new orders generate the corresponding coupon_info meta). I'm not sure if we can use old versions of WooCommerce in the tests.

Basically, I'm limiting the search for coupons that already existed when the order was created, to avoid the case of wrongly showing the link to a coupon that still didn't exist. 

So, to test this, we could:
1. With an old version of WooCommerce, generate a coupon.
2. Generate an order using this coupon.
3. Invalidate the coupon, moving it to "private" status.
4. Generate a new coupon, with the same name, but with different properties.
5. Upgrade WooCommerce to the last version, using this patch.
6. In the backend order page, check that the coupon name doesn't wrongly link to the last coupon we created.

2024-06-12 14:00 UTC, Konamiman commented
Hi @davefx,

> the else branch of the if clause will only be executed for orders created with old versions of WooCommerce (as all new orders generate the corresponding coupon_info meta). I'm not sure if we can use old versions of WooCommerce in the tests.

It's fine if the testing steps involve manually modifying the database to simulate an older version of WooCommerce. In this case, it would be something like using `wp db query` (or a smilar CLI command or sequence of commands) to delete the `coupon_info` entry that was generated.

2024-09-04 11:03 UTC, davefx commented
@Konamiman The test steps were already updated on June 12th to test the second case.

2024-09-09 14:59 UTC, Konamiman approved these changes
Works as expected. Just noting that the example SQL query from the testing instructions for deleting the coupon info didn't work for me (in MariaDB, throws syntax error) so I used this variant instead:

```SQL
DELETE FROM wp_woocommerce_order_itemmeta WHERE meta_id in 
(SELECT oim.meta_id FROM wp_woocommerce_order_itemmeta oim
JOIN wp_woocommerce_order_items oi ON oi.order_item_id=oim.order_item_id 
WHERE oi.order_id=<order id> and oi.order_item_type='coupon' 
and oim.meta_key='coupon_info')
```

2024-09-09 15:00 UTC, merged