fix: set correct shipping_method indexes in cart
woocommerce/woocommerce pull request #48383
Opened 2024-06-11 14:02 UTC by adtennant

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The `$index` variable is never set within `templates/cart/cart-shipping.php` is never set and so all of the shipping methods have `name=shipping_method[0]` and `woocommerce_after_shipping_rate` always receives `0` for the index.
<img width="470" alt="Screenshot 2024-06-11 at 14 48 59" src="https://github.com/woocommerce/woocommerce/assets/2420216/1137fdb5-69d2-4e45-ae77-de721b0497bb">

This change sets `$index` correctly within the loop:
<img width="483" alt="Screenshot 2024-06-11 at 14 51 02" src="https://github.com/woocommerce/woocommerce/assets/2420216/f05bbb42-4fd9-4257-ba3d-c7e74b715680">

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to `WooCommerce > Settings > Shippings` and configure a Shipping Zone with multiple shipping methods available. 
2. Add at least one product to your basket.
3. Go to the Basket or Checkout page and fill in the billing address details until the shipping methods populate.
4. The shipping method `input` elements should have sequential name attributes of the form `shipping_method[i]` where `i` is their position in the list.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
fix: set correct shipping_method indexes in cart
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-06-11 23:05 UTC, barryhughes requested changes
Thanks! Looks good. For clarity, it may be worth noting that this change applies to the 'classic checkout' and not the default Blocks-driven checkout experience.

2024-06-11 23:05 UTC, barryhughes commented on plugins/woocommerce/templates/cart/cart-shipping.php
> +				<?php foreach ( array_values( $available_methods ) as $index=>$method ) : ?>
Small tweak needed here to satisfy the `WordPress.WhiteSpace.OperatorSpacing.*` rules:

```suggestion
				<?php foreach ( array_values( $available_methods ) as $index => $method ) : ?>
```

2024-06-11 23:05 UTC, barryhughes commented on plugins/woocommerce/changelog/48383-fix-shipping_method_index
> +fix: set correct shipping_method indexes in cart  </details>  <details>  <summary>Changelog Entry Comment</summary>
I think something went wrong with the changelog generation tool here, as we've got various bits of extra markup. Tweak:

```suggestion
Set the correct shipping method indexes in the cart/cart-shipping template.
```

2024-06-11 23:42 UTC, barryhughes requested changes
We'll also need to change the `@version` tag in the template. Given where we are in the release cycle, `9.1.0` makes sense.

2024-06-11 23:45 UTC, barryhughes commented on plugins/woocommerce/changelog/48383-fix-shipping_method_index
> +fix: set correct shipping_method indexes in cart  </details>  <details>  <summary>Changelog Entry Comment</summary>
```suggestion
Set the correct shipping method indexes in the cart/cart-shipping template.
```

Re-applying earlier suggestion.

2024-07-11 20:54 UTC, barryhughes commented
Hi @adtennant, I saw you made some further commits: is this ready for a second look? If not, just request a fresh review whenever you're ready.

2026-08-14 18:31 UTC, nerrad commented
This PR is not ready to merge and given the staleness I'm going to close. Ideally the problem would be described in an issue first. A few concerns with the PR here:

- The changes are not considering the [variables already defined](https://github.com/woocommerce/woocommerce/blob/d41b917b4544a333c942c57a1705b3bcd92cb83b/plugins/woocommerce/includes/wc-cart-functions.php#L258-L272) in the calling function loading the template (for example `$index`).
- It looks like `$index` is the shipping-package index, not an undefined rate index. The implementation here breaks classic cart/checkout selection. With multiple packages, every field is named `shipping_method[0]`.
- The public hook argument silently changes meaning. `woocommerce_after_shipping_rate( $method, $index )` has historically received the package index, this PR changes it to the rate ordinal.
- The PR's testing instructions assert the wrong behaviour. Shipping methods within one package must share `shipping_method[<package index>]` otherwise they are not one radio group.

2026-08-14 18:31 UTC, closed without merging