Classic Checkout: Mark required fields as invalid if they only contain space character
woocommerce/woocommerce pull request #48428
Opened 2024-06-12 10:17 UTC by pramodjodhani

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) ✅ 
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change. ✅ 
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). ✅ 
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate. 

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1. Make sure you are on the trunk branch and you are using the classic checkout shortcode
2. Add a product to the cart and visit the checkout page
3. In any of the required fields, add some spaces and change the focus
4. Notice that the field is not considered as invalid and `woocommerce-invalid` class is not added to its parent form-row.

https://github.com/woocommerce/woocommerce/assets/5794565/2d05f59b-f296-4af0-892c-a5d085675ba9

5. Switch to this branch and confirm that the field with empty spaces is still considered as invalid and it's form-row parent contains the invalid class

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
[fix] Classic Checkout: Mark fields as invalid on change when they only contain space characters

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-06-17 10:46 UTC, alexflorisca approved these changes, later dismissed
Thanks for contributing! This looks like a sensible change 👍

2026-08-24 15:33 UTC, jorgeatorres requested changes
@pramodjodhani: thank you for your contribution! Apologies this fell through the cracks, but I'm not sure the current shape of this PR is entirely correct. I've left some inline comments, but will be closing the PR as it's clear it's stale now.

Feel free to re-open once those issues are addressed and we will happily take another look.

Thanks!

2026-08-24 15:33 UTC, jorgeatorres commented on plugins/woocommerce/client/legacy/js/frontend/checkout.js
> +					} else if ( $this.val().trim() === '' ) {
Note that `validate_field` is bound to more than just text inputs, so `$this` could be a `<select>` for example, and `.val().trim()` might not work correctly, possibly producing type errors.

I think we should only trim strings, and keep the old behavior for everything else.

2026-08-24 15:33 UTC, jorgeatorres commented on plugins/woocommerce/changelog/48428-fix-trigger-validation-for-empty-fields
> +[fix] Classic Checkout: Mark fields as invalid on change when they only contain space characters  </details>  <details>  <summary>Changelog Entry Comment</summary>
This might've been a bug in the changelogger implementation, but the changelog entry includes part of the PR template in it.

2026-08-24 15:33 UTC, closed without merging