Update Card component reference
woocommerce/woocommerce pull request #48679
Opened 2024-06-20 14:47 UTC by emmanuel-ferdman

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

The Card component was moved. This PR adjusts sources to changes.

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [x] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-09-02 12:32 UTC, emmanuel-ferdman commented
@tjcafferkey @gigitux can you please review this PR?

2024-09-02 12:44 UTC, tjcafferkey commented
Thanks for this contribution @emmanuel-ferdman. The PR does correct the source link, for my own benefit I am just trying to understand why a generic component was moved into a specific directory.

@ecgan it looks like a PR authored by yourself (https://github.com/woocommerce/woocommerce/pull/37444) was part of this decision. Would you mind both providing a second review and also providing a little context please? I would have thought `card` would belong in `components` due to its generic nature. 😅

2024-09-04 14:15 UTC, ecgan requested changes
Hi @emmanuel-ferdman , thanks for your contribution here! I'm requesting a small change below, to make the text match with the link path.

2024-09-04 14:15 UTC, ecgan commented on docs/README.md
> +- [`client/marketing/components/card`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/marketing/coupons/card/README.md)
Change the text to match with the link path:

```suggestion
- [`client/marketing/coupons/card`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/client/marketing/coupons/card/README.md)
```

2024-09-04 14:29 UTC, ecgan commented
> @ecgan it looks like a PR authored by yourself (#37444) was part of this decision. Would you mind both providing a second review and also providing a little context please? I would have thought `card` would belong in `components` due to its generic nature. 😅

Hi @tjcafferkey , thanks for tagging me here! 🙇 The context is in the PR description of https://github.com/woocommerce/woocommerce/pull/37444, i.e. "some of the shared marketing components are only used by the Coupons page", so I moved them into the coupons directory, to be colocated with where they are being used. I hope that makes sense. 😄

2024-09-19 13:14 UTC, gigitux commented
Hi @emmanuel-ferdman, thanks for your contribution! Could you please address the feedback so we can proceed with merging this PR? Thanks! 🙇

2024-09-19 13:57 UTC, emmanuel-ferdman commented
@gigitux I accepted the changes and updated the branch up to date. Let me know if you need anything else from my side before merge 😄

2024-09-19 14:06 UTC, gigitux commented
> @gigitux I accepted the changes and updated the branch up to date. Let me know if you need anything else from my side before merge 😄

Thanks for updating the PR. The PR LGTM! I pushed a small change (f25df4e) to fix the markdown lint error.

2024-09-19 14:07 UTC, gigitux approved these changes
LGTM

2024-09-19 14:07 UTC, gigitux commented
@ecgan could you review and approve the PR if everything looks okay on your side? Thanks!

2024-09-23 14:15 UTC, ecgan approved these changes
LGTM 👍

2024-09-23 14:20 UTC, ecgan commented
I have approved this PR. I'll proceed to merge this community contribution.

2024-09-23 14:20 UTC, merged