[WIP][Accessibility] Focus coupon input if it has an error
woocommerce/woocommerce pull request #48738
Opened 2024-06-22 01:04 UTC by Manussakis

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #37602  .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-06-23 16:47 UTC, Manussakis commented
@dkotter This PR is ready for code review.

2024-06-24 13:54 UTC, dkotter approved these changes

2024-06-24 13:54 UTC, dkotter commented
@qasumitbagthariya @ankitguptaindia This is ready for QA

2024-06-25 12:09 UTC, mikejolley reviewed
This tested well and the code looks good. #37602 however reports the issue with the classic cart experience. This PR only fixes the issue in the block based checkout experience.

If we are fixing classic in a different PR, we should leave #37602 open. Unless it is tackled in this PR instead.

2024-06-25 15:38 UTC, Manussakis commented
> This tested well and the code looks good. #37602 however reports the issue with the classic cart experience. This PR only fixes the issue in the block based checkout experience.
> 
> If we are fixing classic in a different PR, we should leave #37602 open. Unless it is tackled in this PR instead.

Good catch @mikejolley !
I will move the issue to the "In Progress" column and tackle the classic cart experience.
Thanks!

2024-06-27 19:44 UTC, Manussakis commented
@dkotter This task is ready for code review.
Note that this is the first out of two PRs needed to close the #37602 issue. Please, check the PR description for more context

2024-06-27 20:44 UTC, dkotter approved these changes
@qasumitbagthariya @ankitguptaindia This is ready for QA

2024-06-28 21:17 UTC, Manussakis commented
@dkotter FYI – I have made a small change to improve the HTML semantics of the error message.
[Improve coupon error message semantics](https://github.com/woocommerce/woocommerce/pull/48738/commits/0311453e5e8ce0814f8d7d4ac43227c8ccb76162)

2024-06-28 21:41 UTC, dkotter approved these changes

2024-07-08 17:03 UTC, vikrampm1 commented
@qasumitbagthariya @ankitguptaindia This is ready for QA with the additional changes

2024-07-10 10:34 UTC, ankitguptaindia commented
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.5.5
* Theme: Main News Version: 1.0.1
* WooCommerce - Dev version with this fix specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 126
* OS: macOS Sonoma 14.5
* Git Branch: Manussakis:fix/37602


</Details>


**Test Results -** 

Changes work as expected.  ✅ 

Tested Cases with Classic and Block Checkout: 

- Focus when the customer enters a correct coupon code. ✅ 
- Focus when the customer enters an incorrect coupon code.✅ 
- When there is more than one coupon on the cart and checkout pages. ✅ 
- When the user enters a correct coupon code after entering an incorrect coupon code. ✅ 
- When the user enters an incorrect coupon code multiple times. ✅ 
- When the user uses an expired coupon code. ✅ 
- When the user uses the same coupon code again. ✅ 
- When a customer removes a coupon code after it has been applied. ✅ 
- When a customer applies multiple coupons sequentially (one after the other). ✅ 


 

**Functional Demo /  Screencast -*


**Classic Cart and Checkout Page:** 

https://github.com/woocommerce/woocommerce/assets/6384299/2758a56c-aa55-4f3f-97c9-6a67c0482ac7


**Block-based Cart Page and Checkout Page:** 


https://github.com/woocommerce/woocommerce/assets/6384299/19359ee9-05a2-4be8-9be6-dabf76a7a32b



**Next Step-** Ready for Code Review.

2024-07-10 10:41 UTC, ankitguptaindia commented
@Manussakis This PR is ready for Woo review, please update the title. Thank you! 


>This PR closes part of the https://github.com/woocommerce/woocommerce/issues/37602 issue. 

Please also link this PR with the issue https://github.com/woocommerce/woocommerce/issues/37602 so it will be visible in the project board view. TY.

2024-07-17 14:59 UTC, vikrampm1 commented
@mikejolley this PR is ready for your re-review.

2024-07-19 10:36 UTC, mikejolley commented
@Manussakis @vikrampm1 Could you add additional instructions for classic cart? I'm trying this out and after submitting the coupon the content is reloaded and nothing has focus. Could it be because I'm using shortcode cart on a block based theme? Notices may have different styles under those circumstances.

2024-07-19 14:23 UTC, Manussakis commented
@mikejolley I was able to reproduce the issue you flagged. Block based themes with the shortcode cart are not getting the focus on the coupon input if there is an error.
I'm moving the issue to "In progress" again.

Thanks for catching that.

2024-07-20 00:15 UTC, Manussakis commented
@dkotter I have addressed the issue identified by @mikejolley on [this comment](https://github.com/woocommerce/woocommerce/pull/48738#issuecomment-2239298830).
Please re-review the PR and pass it to @ankitguptaindia for a second round of QA if no fixes are needed 🙂.

2024-07-22 15:14 UTC, dkotter commented on plugins/woocommerce/client/legacy/js/frontend/cart.js
> +			if ( preserve_notices && $old_coupon_error_msg.length > 0) {
```suggestion
			if ( preserve_notices && $old_coupon_error_msg.length > 0 ) {
```

2024-07-22 15:15 UTC, dkotter commented on plugins/woocommerce/client/legacy/js/frontend/checkout.js
> +			if ($target.length === 0) {
```suggestion
			if ( $target.length === 0 ) {
```

2024-07-22 15:15 UTC, dkotter commented on plugins/woocommerce/client/legacy/js/frontend/checkout.js
> +						if ( response.indexOf('woocommerce-error') === -1 && response.indexOf('is-error') === -1) {
```suggestion
						if ( response.indexOf('woocommerce-error') === -1 && response.indexOf('is-error') === -1 ) {
```

2024-07-22 15:16 UTC, dkotter commented on plugins/woocommerce/client/legacy/js/frontend/checkout.js
> +							});
```suggestion
							$form.slideUp( 400, function() {
								$form.before( response );
							} );
```

2024-07-22 15:16 UTC, dkotter approved these changes
@ankitguptaindia This is ready for another round of QA

2024-07-25 08:18 UTC, ankitguptaindia commented
If the customer fills invalid coupan code and coupon field shows an error message. If the customer moves to another field and clicks on that (for example, shipping options/payment option radio buttons) then customer needs to click twice. 

This only happens on Cart Page and works fine on checkout page. 

Tried on both, shortcode cart and block cart with TT4 theme and non WC theme. 


Classic Cart

https://github.com/user-attachments/assets/49e4ba5c-2119-492a-99da-d5fcde1a0235


Block Cart

2024-07-26 00:33 UTC, Manussakis commented
@ankitguptaindia Thanks for testing it again.

**Point-1**
This is not an issue introduced by this PR. You can reproduce it on the trunk branch by:
- Applying an invalid coupon code.
- Clicking on the input after the error message appears.
- Trying to interact with an element below the input.

This is because the coupon input is not required, so the error message disappears once the focus moves away from it, which happens as soon as you click on any element of the page. When the error message disappears, the height of its container decreases making all the elements below it change their position. That's why the first click doesn't take any effect, because the target changes its initial place.

This issue is more evident now because the focus is automatically moved to the coupon input if there is an error.

I suggest creating a new issue to tackle the bug. I did a quick investigation and noticed that the coupon input uses the same component as several elements on the checkout form (`<ValidatedTextInput>`). I believe it's worth it to centralize the discussion on a dedicated issue.

@mikejolley any thoughts on creating a new issue to deal with the **Point-1** above?

**Point-2**
Good catch! Let's keep consistency and preserve the value across all Cart types.

@dkotter Please take a look at this commit: [Don't clear coupon input if code doesn't exist](https://github.com/woocommerce/woocommerce/pull/48738/commits/11e7b8bf7441abe05715e5b09c10943536fe0afa)

2024-07-26 13:50 UTC, dkotter approved these changes

2024-07-27 10:33 UTC, ankitguptaindia commented
**QA/Test Report-**  
------------

Thanks @Manussakis for checking the above concerns.


> Point-1
This is not an issue introduced by this PR. You can reproduce it on the trunk branch by:

ℹ️ Reported here  https://github.com/woocommerce/woocommerce/issues/50053   as a separate issue to address separately. 

> Point-2
Good catch! Let's keep consistency and preserve the value across all Cart types.

Point-2:  ✅ This issue has been fixed and works as expected now. ✅ 


Tested all scenarios on: 

- Tested on both shortcode-based cart/checkout pages and block-based cart/checkout.
- Tested with TT-4 theme, TT-1 theme, and Storefront. 

----


**Next Step:** Ready for code review.

2024-07-27 18:27 UTC, Manussakis commented
@vikrampm1 This PR is ready to be reviewed by the appropriate Woo team.

2024-07-29 10:18 UTC, nielslange requested changes, later dismissed
Thanks for working on this, @Manussakis. While testing the classic cart against various themes, I noticed an inconsistency in how we display the error message when an invalid coupon code had been provided.

## Twenty Twenty-Four 

✅ This is what I expect to see for all themes.

<img width="1036" alt="Screenshot 2024-07-29 at 12 07 24" src="https://github.com/user-attachments/assets/38599860-3997-428c-91d3-c253caf1f1b8">

## Twenty Twenty-Three

❌ I expect the error message in red and below the coupon input field.

<img width="1052" alt="Screenshot 2024-07-29 at 12 08 40" src="https://github.com/user-attachments/assets/9d910f1e-4b14-483e-b018-ff634b5637bd">

## Twenty Twenty-Two

❌ I expect the error message in red and below the coupon input field.

<img width="1075" alt="Screenshot 2024-07-29 at 12 10 09" src="https://github.com/user-attachments/assets/8a668086-d49a-4955-a56b-3b4cf4108c0d">

## Twenty Twenty-One

❌ I expect the error message in red, left-aligned with the coupon input field, and with more spacing between the input field and the error message.

<img width="1302" alt="Screenshot 2024-07-29 at 12 10 36" src="https://github.com/user-attachments/assets/41f1eb12-f3bd-4e7c-b67d-0c632fde87a5">

## Twenty Twenty

❌ I expect the error message in red, left-aligned with the coupon input field, and with more spacing between the input field and the error message.

<img width="1384" alt="Screenshot 2024-07-29 at 12 12 12" src="https://github.com/user-attachments/assets/a4d3ec5f-996b-4591-998b-a18a4d7a2cb8">

## Storefront

❌ I expect the error message in red, left-aligned with the coupon input field, and with more spacing between the input field and the error message.

<img width="824" alt="Screenshot 2024-07-29 at 12 12 48" src="https://github.com/user-attachments/assets/785e81ad-9e6a-4c36-ba72-bb1c71db69f1">

IMO, the error code should always appear left-aligned, below the input field, and displayed in red. Preferably, the input field should also have a red border when the coupon code is invalid.

@nikkivias What are your thoughts regarding the styling of the error messages, which I mentioned above?

---

I also noticed that when clicking into a different browser window, the focus gets lost. While the test steps state _"Verify the error message disappears after moving the focus away from the input [...]"_, is it expected that the focus gets lost when leaving the browser, e.g. to double-check the coupon code in another browser window or another app, e.g. an email client?

2024-07-29 12:02 UTC, Manussakis commented
@nielslange Thanks for testing this PR.
The reason the error message style is inconsistent across different themes is that not all themes load the WooCommerce default CSS files. Only the Twenty Twenty-Four one does it and that's why it works as expected in this case.
This PR introduces a new CSS class named `coupon-error-notice` and themes don't have their own CSS rules for it yet.
I am curious about how would I fix this issue since we don't have control over whether themes will use WooCommerce default styles or not. Could you give more guidance on that?

-----

> I also noticed that when clicking into a different browser window, the focus gets lost [...]

I tested it again and couldn't reproduce the loss of focus. What I did notice is that the error message disappeared, but when I got back to the page, the coupon input still had the focus. Could you give more context on how you are having this issue?

2024-08-05 13:37 UTC, Manussakis commented
Hey @nielslange 
I am just following up to see if you have any feedback on my last comment.
Thanks!

2024-08-07 12:50 UTC, vikrampm1 commented
@nielslange this is currently blocked and awaiting your feedback.

2024-08-07 15:34 UTC, mikejolley commented
> This PR introduces a new CSS class named coupon-error-notice and themes don't have their own CSS rules for it yet.
I am curious about how would I fix this issue since we don't have control over whether themes will use WooCommerce default styles or not. Could you give more guidance on that?

We should at least add the styling rules for default WP themes to cover this. You can see by searching `.twenty` we have styles in place for those. These default themes should also load default Woo stylesheets? Only woo custom themes like Storefront would disable these.

2024-08-08 13:30 UTC, Manussakis commented
@mikejolley Thanks for the feedback!

@dkotter Please re-review this task.

2024-08-08 14:42 UTC, dkotter commented on plugins/woocommerce/client/legacy/js/frontend/cart.js
> +					if ( response.indexOf('woocommerce-error') === -1 && response.indexOf('is-error') === -1 ) {
```suggestion
					if ( response.indexOf( 'woocommerce-error' ) === -1 && response.indexOf( 'is-error' ) === -1 ) {
```

2024-08-08 14:42 UTC, dkotter commented on plugins/woocommerce/client/legacy/js/frontend/checkout.js
> +						if ( response.indexOf('woocommerce-error') === -1 && response.indexOf('is-error') === -1 ) {
```suggestion
						if ( response.indexOf( 'woocommerce-error' ) === -1 && response.indexOf( 'is-error' ) === -1 ) {
```

2024-08-08 14:43 UTC, dkotter approved these changes
@ankitguptaindia This is ready for another round of QA

2024-08-13 14:33 UTC, ankitguptaindia commented
Hello @Manussakis, 


Tested with WordPress Default themes and Storefront. Works as described. 

-  Classic Cart and Checkout Pages and,
-  Storefront -  Block and Classic Cart/Checkout pages.
- Twenty-twenty-four - Block and Classic Cart/Checkout pages. 


I have a few points to confirm:

1. In WordPress default themes with Classic Cart & Checkout pages, when a user adds an invalid coupon code, the field is cleared on the Cart page but remains populated on the Checkout page. Can we ensure consistent behavior for coupon fields on both pages? On the Block Cart/Checkout pages, the invalid coupon code remains in the field on both pages after the error notice.

<Details>
  <summary>Click for more details</summary>



https://github.com/user-attachments/assets/8e4942a7-e85f-42b9-a8d0-45692115a517

</Details>

2.  With Classic Checkout, when an invalid coupon code message appears, the border color of the cart field looks correct, but on the checkout page, it appears differently, as shown in the screenshot below.

<Details>
  <summary>Click for more details</summary>



| Cart Page | Checkout Page |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/bcc3847e-a4cf-4e1d-932b-e7e10083e364) | ![image](https://github.com/user-attachments/assets/7d0a3cf3-26e8-4ae0-8ca7-7bda284478bc) | 

</Details>

3. A question regarding the Storefront theme: 

>Note: I noticed that when the Storefront theme is installed, these CSS files aren't loaded on the classic Cart and Checkout pages:

On the Storefront theme, the validation message appears differently, particularly in terms of error message color and alignment (the reason is already mentioned in the description). Does this require any fixes in the theme repository? Since Storefront is a WooCommerce-supported theme, it would be great if it worked efficiently with it. 


<Details>
  <summary>Click for more details</summary>



![image](https://github.com/user-attachments/assets/f3d7e7c2-dbb4-428c-bde6-f28990d78c0c)





</Details>

2024-08-13 19:25 UTC, Manussakis commented
Hey @ankitguptaindia 

Replying to your points:

**Point 1**
> In WordPress default themes with Classic Cart & Checkout pages, when a user adds an invalid coupon code, the field is cleared on the Cart page but remains populated on the Checkout page. [...]

Thanks for flagging that. Fixed on [Keep input with the invalid coupon code after notice appears](https://github.com/woocommerce/woocommerce/pull/48738/commits/d2ffffd4e3d4c0657c9164888a222be21147fccb)

@dkotter please review this commit.

**Point 2**

> With Classic Checkout, when an invalid coupon code message appears, the border color of the cart field looks correct, but on the checkout page, it appears differently, as shown in the screenshot below.

The coupon field uses the same input style as the other ones on the checkout page, so it's consistent with them.
![Screenshot at Aug 13 16-05-31](https://github.com/user-attachments/assets/c1e95a92-4691-49f9-903a-f0e4db2f45aa)

**Point 3**
[As recommended](https://github.com/woocommerce/woocommerce/pull/48738#issuecomment-2273759321) by @mikejolley I have provided styles for the default WP themes. My understanding is that we can't cover it for the Storefront theme since it doesn't load the default Woo stylesheet.

2024-08-13 21:12 UTC, dkotter approved these changes

2024-08-13 21:25 UTC, Manussakis commented
@ankitguptaindia Please check if point-1, flagged by you, is now working as expected. Thanks!

2024-08-17 08:27 UTC, ankitguptaindia commented
Thanks for the fixes @Manussakis Changes look great to me. 

PR is ready for the next step.  
cc: @vikrampm1

2024-08-17 14:01 UTC, vikrampm1 commented
@nielslange @mikejolley this is back for your re-review!

2024-08-19 12:05 UTC, mikejolley requested changes
I tested a selection of themes and both checkouts/carts and it works now good job.

Please fix the typos I highlighted and check the CI here (https://github.com/woocommerce/woocommerce/actions/runs/10375805397/job/28726542138?pr=48738). Once the linting issues are solved we can merge.

2024-08-19 12:05 UTC, mikejolley commented on plugins/woocommerce/client/legacy/js/frontend/checkout.js
> +						// We only want to show coupon notices if they are not errors.
```suggestion
						// We only want to show coupon notices if they are no errors.
```

2024-08-19 12:05 UTC, mikejolley commented on plugins/woocommerce/client/legacy/js/frontend/cart.js
> +	 * @param {string|object} html_element The HTML string response after applying an invalid coupon or a jQuey element.
```suggestion
	 * @param {string|object} html_element The HTML string response after applying an invalid coupon or a jQuery element.
```

2024-08-19 23:22 UTC, Manussakis commented
@mikejolley Thanks for testing this PR.
I fixed the CI issues with these two commits:
- [Break notice message into two lines](https://github.com/woocommerce/woocommerce/pull/48738/commits/6960fc06d7d368469a2da40287049352a42107f1)
- [Break if statement into two lines](https://github.com/woocommerce/woocommerce/pull/48738/commits/001a270e57de9c6570c3bb0674e4c809cd333e4d)

cc: @dkotter

2024-08-23 18:21 UTC, mikejolley approved these changes

2024-08-23 18:22 UTC, merged