Checkout: Add password strength meter to new field
woocommerce/woocommerce pull request #49164
Opened 2024-07-04 16:27 UTC by mikejolley

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

WIP. Adds a password strength meter.

Closes #48628

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-07-05 10:56 UTC, mikejolley commented
I don't think the test fails are related to these changes so I'll mark for review. Note that this targets the https://github.com/woocommerce/woocommerce/pull/48985 branch, so I'll merge this into the other branch before trunk, or rebase on trunk if we do the other one first.

2024-07-05 11:06 UTC, senadir commented
Some notes about your questions:

- Enqueues zxcvbn-async if registration is enabled and the user is logged out. If zxcvbn is not present, it will instead use the check-password-strength library which is less accurate. We could instead just hide the meter if zxcvbn is not present (feedback?)
  -  We can look into making this opt-in at some point? I still hold the opinion that this shouldn't be strict for all stores.
- Uses the semantic HTML meter component. Browser compatibility was awkward but I tested across Safari, Arc, Firefox. [Firefox does not show the "score" because :after is not supported.](https://css-tricks.com/html5-meter-element/)
  - Can we detect if `after` is not supported and just do a couple of components. Doesn't seem like a huge problem for now.
- I've set a minimum allowed strength of 2 (medium) which will block checkout if not met. Is this sensible default or do we want it lower or unrestricted?
  - We can start with keeping this set in stone as 2, if we ever make it extensible (filter maybe in which store sets an accepted strength), we can reevaluate, if it's less than 2, we should just skip the strength meter completely, no point from using it if everything is accepted.

2024-07-09 13:23 UTC, mikejolley commented
> We can look into making this opt-in at some point? I still hold the opinion that this shouldn't be strict for all stores.

Yeah but I still find the protection against common passwords really beneficial to secure accounts. 

> Can we detect if after is not supported and just do a couple of components. Doesn't seem like a huge problem for now.

We could avoid using meter and use something custom, or append the label some other way. I was trying to keep it semantic. The bar should still be understandable without the text.

> We can start with keeping this set in stone as 2, if we ever make it extensible (filter maybe in which store sets an accepted strength), we can reevaluate, if it's less than 2, we should just skip the strength meter completely, no point from using it if everything is accepted.

Makes sense.

2024-07-10 10:11 UTC, opr requested changes
Nice work on this Mike, it's looking good. The code looks alright, but I didn't do a full review on the CSS, because I think things will change following this review.

A few things I spotted and wonder about:

- The layout shifts when the meter appears, could we either:
  - Keep the meter visible, but indicate it'll update as they type (if necessary)
  - Keep it hidden, but reserve the space for the meter, so when it appears there's no shift
- Is this accessible, would a screen reader know about the password strength while typing? While using VoiceOver, the password strength was not read out to me. (actually, voicover says "Two shipping options were found" while interacting with this field, but I doubt it's related to the strength meter PR). Maybe consider having the strength announced to screen readers after typing?
- On mobile/small desktop, if the "Please create a stronger password" text is long (e.g. after being translated) then it overlaps with the strength.
<img width="369" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/d60c766a-8e86-4fe6-8a6b-028cfa1784be">

> The bar should still be understandable without the text.

I'm not confident about this, unless we add some text indicating it's for password strength.

2024-07-10 13:13 UTC, mikejolley commented
@opr 

- Added feedback element that shows strength across all browsers and is picked up by voiceover
- Prevented error notices and strength bar rendering at the same time
- Updated initial state to be hidden but take up space

2024-07-10 14:42 UTC, opr requested changes
Thanks for the changes!

A11y, think this is working OK but is it possible to read the strength with "Password strength: %s" rather than just the strength? I feel like it could be confusing to just hear "Weak" "medium" with no real context. 

Is it also possible to delay this announcement until the user has finished typing, or at least announce it every time the password changes, not just the first time it switches strength level?

There's still some layout shift when tabbing out of the input with an invalid password

https://www.loom.com/share/f9a9d4113e364a48b5dac7686bde27ad

In Safari, the "weak" bar is green and bigger than it should be
<img width="817" alt="image" src="https://github.com/woocommerce/woocommerce/assets/5656702/9d92d7b9-2dc2-4961-8b6c-d8da542a377d">

2024-07-10 15:51 UTC, mikejolley commented
@opr 

> A11y, think this is working OK but is it possible to read the strength with "Password strength: %s" rather than just the strength? I feel like it could be confusing to just hear "Weak" "medium" with no real context.

I've added that and the character count so its announced more often.

> There's still some layout shift when tabbing out of the input with an invalid password

All fields with validation notices have layout shift.

> In Safari, the "weak" bar is green and bigger than it should be

Should be fixed. Safari has some unique bugs around the meter element.

2024-07-11 12:42 UTC, opr approved these changes
Thanks Mike, this is working well for me, a11y is improved a lot (though still facing the issue with the shipping options being read out, but that's separate) and safari looks to be working well too.

Happy for you to merge this and resolve the failing tests on the base PR.

2024-07-11 12:42 UTC, opr commented on plugins/woocommerce-blocks/assets/js/blocks/checkout/password-strength-meter/index.tsx
> +} ): JSX.Element | null => {
`JSX.Element` is deprecated and the preferred way is `React.ReactElement` though I don't think this should block this PR, feel free to change it if you like.

2024-07-15 15:22 UTC, merged