[WIP][Accessibility] Update the breadcrumb so the last item is an accessible link
woocommerce/woocommerce pull request #49417
Opened 2024-07-11 17:11 UTC by amesplant

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #43626

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Make sure that the last item in the breadcrumb is a link
2. Inspect the code and make sure that the last link in the breadcrumb has an `aria-current` attribute set to `page`
3. Using a screen reader, make sure that when the focus is on the last link that it announces that it is the `current page`

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>
Turns the last item in the breadcrumb into a link with an `aria` attribute that announces to screen readers that the link is the current page.
<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-07-11 17:12 UTC, amesplant commented
@dkotter sending this your way to Code Review

2024-07-11 17:54 UTC, nielslange reviewed
Thanks for working on this, @amesplant. If I understand issue #43626 correctly, the only part missing is the [`aria-current="page"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) attribute. The last element should not be a link.

While researching, I found https://www.aditus.io/aria/aria-current/, which references the breadcrumb structure on https://www.service-public.fr/particuliers/vosdroits/N23493. Their breadcrumb markup is as follows:

```html
<ol class="fr-breadcrumb__list" data-test="ol-filDAriane">
  <li>
    <a class="fr-breadcrumb__link" href="https://www.service-public.fr/particuliers" data-fr-js-breadcrumb-link-actionee="true">Accueil</a>
  </li>
  <li>
    <a class="fr-breadcrumb__link" href="https://www.service-public.fr/particuliers/vosdroits/N19805" data-fr-js-breadcrumb-link-actionee="true">Famille - Scolarité</a>
  </li>
  <li>
    <span class="fr-breadcrumb__link" aria-current="page">Obligation scolaire</span>
  </li>
</ol>
```

It's my understanding that the last item should not be a link, as the user is already on that page. @amberhinds, can you confirm this?

2024-07-11 17:58 UTC, amesplant commented
@nielslange 
`aria-current` is not relevant on a `span` and thus that last element does and should be a link for accessibility reasons.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current

2024-07-11 18:04 UTC, nielslange commented
> @nielslange `aria-current` is not relevant on a `span` and thus that last element does and should be a link for accessibility reasons. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current

Oh, that's strange, as the same site also shows this example: https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Breadcrumb_Navigation

That said, I'm not an accessibility expert. Let's see what @amberhinds has to say.

2024-07-11 18:16 UTC, amesplant commented
@nielslange I mispoke .. `aria-current` _should_ be used on interactive elements. There are arguments for having the last item as a link or non-link. I can update the code to simply be a non-link, although as an Accessibility Expert, I _would_ rather see it as a link, but not a critical issue if it isn't (and would not fail any WCAG 2.2 criteria).

2024-07-11 18:32 UTC, nielslange commented
> @nielslange I mispoke .. `aria-current` _should_ be used on interactive elements. There are arguments for having the last item as a link or non-link. I can update the code to simply be a non-link, although as an Accessibility Expert, I _would_ rather see it as a link, but not a critical issue if it isn't (and would not fail any WCAG 2.2 criteria).

You're right, @amesplant. I looked up Governmental sites, that are required to be accessible by law and the while the [Germany embassy](https://jakarta.diplo.de/id-de/ueber-uns/botschaft/botschafter/2483324) does not use a link for the last item, the [British embassy](https://www.gov.uk/apply-renew-passport) does.

<table>
<tr>
<td valign="top"><a href="https://jakarta.diplo.de/id-de/ueber-uns/botschaft/botschafter/2483324">Germany embassy</a>:
<br><br>
<img width="849" alt="Screenshot 2024-07-11 at 20 28 45" src="https://github.com/woocommerce/woocommerce/assets/3323310/7bd768f3-c157-489c-a86f-7802a3a920a2">
</td>
<td valign="top"><a href="https://www.gov.uk/apply-renew-passport">British embassy</a>:
<br><br>
<img width="971" alt="Screenshot 2024-07-11 at 20 29 22" src="https://github.com/woocommerce/woocommerce/assets/3323310/cc334b2a-5d65-4725-bb48-f633b1a7710d">
</td>
</tr>
</table>

Guess as a German citizen, I'm more used to the last item in the breadcrumb not being a _"clickable"_ link. That said, the PR looks good, so I'm pre-approving it. 😀

2024-07-11 18:32 UTC, nielslange approved these changes, later dismissed
I'm pre-approving this PR based on https://github.com/woocommerce/woocommerce/pull/49417#issuecomment-2223628932. Thanks again for working on this, @amesplant. 🙌

2024-07-11 19:01 UTC, dkotter submitted a review, later dismissed
@ankitguptaindia @qasumitbagthariya This is ready for QA

2024-07-12 15:18 UTC, ankitguptaindia commented
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.5.5
* Theme: Storefront Version: 4.6.0 
* WooCommerce - Dev version with this fix specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 126
* OS: macOS Sonoma 14.5
* Git Branch: amesplant:fix/43626-breadcrumb-current-page


</Details>


**Test Results -** 

Changes work as expected. Tested via macOS Voice Over. Tested with Storefront theme. 
 

**Functional Demo /  Screencast -**


![Screenshot 2024-07-12 at 8 41 54 PM](https://github.com/user-attachments/assets/67eb9553-e717-4614-9790-faf02de9ff13)

2024-07-17 15:04 UTC, vikrampm1 commented
@amesplant please remove [WIP] from the title and take this PR out of draft.

@nielslange once the above steps are complete this PR can be merged. Thanks!

2024-07-18 12:22 UTC, amesplant commented
@nielslange
I have removed [WIP] from the title and have marked this PR as **Ready for Review**

2024-07-19 07:00 UTC, nielslange commented
Restarting the CI pipeline by closing and reopening this PR:

<img width="716" alt="Screenshot 2024-07-19 at 08 59 54" src="https://github.com/user-attachments/assets/84e599fd-1a4f-41d4-b1bf-8039db867f4f">

2024-07-19 07:40 UTC, nielslange requested changes
Hello @amesplant, when running the CI pipeline, I noticed the following PHP lint error: https://github.com/woocommerce/woocommerce/actions/runs/10003971080/job/27651828753?pr=49417. Once you've addressed this, we should be able to merge the PR.

To spot things like this during development, you could use @ObliviousHarmony's [PHP_CodeSniffer](https://marketplace.visualstudio.com/items?itemName=obliviousharmony.vscode-php-codesniffer) extension for VSCode.

2024-07-22 20:09 UTC, amberhinds commented
Hi, sorry for the delay - just getting back in the office from a vacation following WordCamp Canada.

I think it's fine if the last element in a breadcrumb nav is not a link. In that case, the aria-current isn't needed because it's not getting read out. Screen readers won't read aria-current on a span. That linked example from MDN is suspicious to me. I tested it there and indeed it's not read out in that example.

I'm a little confused about the title of this PR as a response to #43626 - That's about the My Account nav, which is not a breadcrumbs nav. If this about the My Account Nav, I don't think the current page should be changed from a link to a span. That is likely to cause a lot of confusion for users. The current page should stay a link and just have aria-current added to it.

2024-07-23 12:31 UTC, amesplant commented
@amberhinds thanks so much for jumping in. I was the one confused! I was so focused in the Breadcrumb not having the `aria-current` that I read [#43626](https://github.com/woocommerce/woocommerce/issues/43626) as if that was the issue needing to be addressed. I am going create a new PR to specifically address the My Account Navigation. 

cc @dkotter

2024-07-23 14:24 UTC, nielslange commented
@amesplant Given [this comment](https://github.com/woocommerce/woocommerce/pull/49417#issuecomment-2243730035) of @amberhinds, I wonder if we should actually merge this PR given that there's no issue for this and no one seems to have requested this change.

cc: @ralucaStan

2024-07-23 14:27 UTC, amberhinds commented
If it does get merged, we should make sure it doesn't close https://github.com/woocommerce/woocommerce/issues/43626

2024-07-24 14:59 UTC, amesplant commented
> If it does get merged, we should make sure it doesn't close #43626

I removed the note for closing https://github.com/woocommerce/woocommerce/issues/43626

2024-07-30 11:57 UTC, nielslange approved these changes, later dismissed
Thanks again for working on this, @amesplant. I've successfully reviewed your PR, and just updated the branch. Once the CI pipeline finished, I'll merge this PR.

2024-09-03 09:52 UTC, Aljullu commented
Howdy! :wave: Chiming in as I'm assigned to review this PR but didn't take a look as @nielslange was already handling it.

I noticed the `Highlight Template Changes` job is failing, so we should update the template version before merging.

Having said that, based on the conversation in this PR (and some other articles I found around) it looks like making the last item in breadcrumbs a link is optional. Given that until now WooCommerce wasn't making it a link, is there any reason to change it? I acknowledge there is nothing wrong with the approach in this PR, but considering the current approach is also correct, I would lean towards leaving it as-is instead of changing it. What do you folks think?

2024-09-05 17:38 UTC, ralucaStan commented
Thank you @Aljullu for your input. 

As there is no agreement on the last element being a link and we also don't have a strong argument for making it one, I think we should proceed with just adding the `aria-current` attribute. 

@amesplant are you still able to make this change, rebase and check the `Highlight Template Changes` passes?

2024-09-05 17:59 UTC, vikrampm1 commented
Tagging @Manussakis to review/help here.

2025-07-02 12:55 UTC, ralucaStan commented
I think it's safe to close this PR as there hasn't been any activity and https://github.com/woocommerce/woocommerce/issues/43626 was completed

2025-07-02 12:55 UTC, closed without merging