add function wc_get_cart_item_data
woocommerce/woocommerce pull request #49510
Opened 2024-07-13 04:13 UTC by luongvancong

**add function wc_get_cart_item_data**

2024-07-15 23:53 UTC, barryhughes commented
Thanks, @luongvancong!

- You seem to have deleted most of PR template, instead of populating it. Can you please add a description describing why this is necessary/desirable, along with testing instructions?
- Please give some consideration to adding unit tests.
- I'll run our CI checks, and I think you may find there are some linting issues that need to be corrected.

2024-07-15 23:58 UTC, barryhughes commented on plugins/woocommerce/includes/wc-cart-functions.php
> +        if ( $cart_item['data']->is_type( 'variation' ) && is_array( $cart_item['variation'] ) ) {
It seems like we only populate `$item_data` for variations and so, for non-variations, we'll just return `[]`. Is that intentional? Can you speak a little more to this, or add appropriate notes in the function doc block?

2024-07-15 23:59 UTC, barryhughes requested changes
Please see my notes, and the list of linting issues.

2026-08-14 18:40 UTC, closed without merging

2026-08-14 18:41 UTC, nerrad commented
Closed because there is no followup from the author and no good rationale shared for the PR.