Add description and delivery time to $data
woocommerce/woocommerce pull request #49643
Opened 2024-07-17 16:06 UTC by opr

### Changes proposed in this Pull Request:

Adds two new properties to the data of a `WC_Shipping_Rate`: `delivery_time` and `description`.

Both are strings, and they will be used to display a delivery time, and a description of the shipping rate in the Checkout block.

<img width="989" alt="image" src="https://github.com/user-attachments/assets/3452297e-fba4-4b25-a823-c89808fc48f8">

The code for displaying these properties already exists in the Checkout block, but it was never used as these properties didn't exist.

Closes #42667

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add several shipping methods to your store. A mix of free and flate rate shipping options should be used. Local pickup _can_ be added, but isn't relevant to this, as it depends on the extension's use of `delivery_time` and `description` props, rather than anything we control.
2. Add the following code using a plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/)
```php
function custom_shipping_description( $rates, $package ) {
    foreach ( $rates as $rate_id => $rate ) {
		if ( 'pickup_location' === $rate->method_id ) {
			continue;
		}
		$rate->description = 'This is a custom description for ' . $rate->label . '.';
		$rate->delivery_time = 'This will be delivered in ' . rand( 1, 5 ) . ' days.';
	}
    return $rates;
}
add_filter( 'woocommerce_package_rates', 'custom_shipping_description', 10, 2 );
```
4. Ensure you have `WooCommerce -> Settings -> Shipping -> Shipping settings -> Enable the shipping calculator on the cart page` checked.
5. Add an item to your cart and go to the Cart block.
6. Ensure you see the rate descriptions and delivery times in the shipping calculator, like so:
<img width="343" alt="image" src="https://github.com/user-attachments/assets/36860a09-54db-40c9-8677-0dc0375a4efa">

7. Go to the Checkout block. Ensure you see the descriptions and delivery times in the shipping methods block, like so:
<img width="615" alt="image" src="https://github.com/user-attachments/assets/66ca2ed4-732d-43b5-9b5d-3f60bf056fcc">

8. Change the text in the snippet above to be quite long, e.g. like so:
```php
function custom_shipping_description( $rates, $package ) {
    foreach ( $rates as $rate_id => $rate ) {
		if ( 'pickup_location' === $rate->method_id ) {
			continue;
		}
		$rate->description = 'This is a custom description for ' . $rate->label . '. It is quite a long, descriptive description that should flow onto multiple lines, for testing purposes.';
		$rate->delivery_time = 'This will be delivered in ' . rand( 1, 5 ) . ' days.';
	}
    return $rates;
}
add_filter( 'woocommerce_package_rates', 'custom_shipping_description', 10, 2 );
```
9. Refresh the Checkout block and ensure it looks OK with the text on multiple lines. There should be no widows/runts (single words on their own line at the end of a block of text) in the description or delivery time.

<img width="998" alt="image" src="https://github.com/user-attachments/assets/bb85c096-35ce-4fef-a440-c210d5b968c8">

10. Try with different screen sizes, and on mobile and various different browsers.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-07-19 13:07 UTC, senadir commented
Should the props be more generic? Otherwise, if we really want to go with `delivery_time`, maybe we can abstract it a bit to an integer so it can be used in other places.

2024-07-22 11:15 UTC, opr commented
> Should the props be more generic? Otherwise, if we really want to go with delivery_time, maybe we can abstract it a bit to an integer so it can be used in other places.

I think `description` should stay, `delivery_time` could be made generic, but not sure what to, "secondary description" doesn't feel right.

If we did abstract that to a number, then it wouldn't work because delivery times can be ranges "2-3 days".

2024-07-22 11:32 UTC, senadir commented
> If we did abstract that to a number, then it wouldn't work because delivery times can be ranges "2-3 days".

That's a valid one, @jamesckemp is working on modernizing the shipping entity in WooCommerce and part of it is that delivery time and shipping information will be first-class props in a shipping entity, so there might be some overlap here.

I think we can keep delivery time a string, in the future, once such system is in place, we can generate a default string from whatever values are there + shipping providers can generate their own strings.

2024-07-22 16:27 UTC, nielslange reviewed
Thanks for working on this, @opr. I've successfully tested this PR, but noticed that the font size of the description and the delivery time is rather small. While your PR did not touch that change, I wonder if we should align it with the font size of the pickup section. Here's what I mean:

<img width="832" alt="Screenshot 2024-07-22 at 18 21 49" src="https://github.com/user-attachments/assets/55b80713-1483-4d47-a4fe-96faba176055">

<img width="839" alt="Screenshot 2024-07-22 at 18 22 28" src="https://github.com/user-attachments/assets/24f0716a-c70a-47f4-8a5a-fb09c1606f5d">

The details and delivery times within the shipping options section have a font size of 11.025em, while the pickup details have a font size of 14.7em. 

This is what the section would look like when we're applying the same font size:

<img width="840" alt="Screenshot 2024-07-22 at 18 25 43" src="https://github.com/user-attachments/assets/80bceb68-d32a-4c53-b87e-49bfced0a9a1">

And this is what the section would look like if we go a step further and also apply the same color `#757575` as we use for the pickup address:

<img width="830" alt="Screenshot 2024-07-22 at 18 27 12" src="https://github.com/user-attachments/assets/13ef0c22-5a52-43db-a15b-1dddb855d02d">

cc: @nikkivias

2024-07-22 16:56 UTC, opr commented
Good point Niels, happy to defer to @nikkivias for guidance here!

2024-08-19 12:54 UTC, senadir approved these changes
Working well, except when it's free shipping, then it doesn't work in Cart.

<img width="330" alt="image" src="https://github.com/user-attachments/assets/a056cc1e-2338-4bb9-b855-faa8e1df9648">

Also not sure if @nikkivias took a look at font sizes or not?

2024-09-04 16:22 UTC, nikkivias commented
@opr @senadir Hi team, I agree the subtext sizes are _tiny_ in the shipping options. I would say styling should generally stay the same across our "options" components. Let's align styling, sizing, alignment and grouping of items across Shipping, Pickup, and Payment options please. 🙏

2024-09-04 16:31 UTC, nikkivias requested changes
Hi team, I agree the subtext sizes are tiny in the shipping options. I would say styling should generally stay the same across our "options" components. Let's align styling, sizing, positioning, alignment and grouping of items across Shipping, Pickup, and Payment options please. 🙏

2024-09-13 15:27 UTC, senadir commented
Setting this to draft for Thomas to work on when he's back.

2025-01-02 15:03 UTC, opr commented
@senadir @nielslange - Rebased and made the font size the same. We won't make the font a lighter colour for now, as we lack a robust way of doing this for different themes and light/dark mode. Safest way is to keep it the same.

Please could you re-review when able? 🙇🏼

2025-01-06 09:26 UTC, senadir approved these changes
Thanks! This is working as expected for me, both in Cart and Checkout.

2025-01-06 10:39 UTC, merged