Fix radio field description in settings
woocommerce/woocommerce pull request #50062
Opened 2024-07-28 21:42 UTC by passatgt

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

In settings, the radio field description is rendered inside the `<ul>` element if the `desc_at_end` parameter is used. This changes moves the field below the list. Also fixes the rendering issue: `$description` is already a `<p>` element, so we don't need to wrap it again in a separate `<p>`. Margin-top removed, because it doesn't have any effect due to other styling. 

### How to test the changes in this Pull Request:

Create a new settings field under the general tab using:

```
add_filter( 'woocommerce_general_settings', function($settings){
	$new_settings = array(
		array(
		   'title' => 'Radio test',
		   'type'  => 'title',
		   'id'    => 'radio_test',
		),
		array(
			'name' => 'Radio test',
			'type' => 'radio',
			'id' => 'radio_test',
			'options' => array(
				'1' => '1',
				'2' => '2'
			 ),
			'desc' => 'Radio test description',
			'desc_at_end' => true
		),
		array(
		   'type' => 'sectionend',
		   'id'   => 'radio_test',
		),
	 );
	  
	 return array_merge( $settings, $new_settings );
});
```

Check the source code around this field and you can notice that the description is inside the <ul> element, which is not valid HTML. After the change, the description is moved below `</ul>`.

2024-08-31 00:20 UTC, jorgeatorres requested changes
Hi @passatgt!

Thank you for your contribution and apologies for the delay here. Overall, this looks good to me and only left some minor feedback. Once that's addressed, it should be good to merge.

Thanks again for your contribution!

2024-08-31 00:20 UTC, jorgeatorres commented on plugins/woocommerce/includes/admin/class-wc-admin-settings.php
> +										echo $description; // WPCS: XSS ok.
We should use `phpcs:ignore` here instead, and it's good to indicate why the rule is being ignored.

```suggestion
										echo $description; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- description is already sanitized in WC_Admin_Settings::get_field_description().
```

2024-08-31 00:20 UTC, jorgeatorres commented on plugins/woocommerce/includes/admin/class-wc-admin-settings.php
> +										echo $description; // WPCS: XSS ok.
Same as above.

2024-09-03 22:11 UTC, barryhughes commented
:bulb: Couple of additional testing notes ...

The fix *may not be obvious* if you examine the resulting markup using your browser's developer tools (because browsers are smart, and try to fix/resolve bad markup). However, if you compare that actual source HTML before and after this change (in many browsers, you can do this with `Ctrl` + `U` or else `Cmd` + `U`), it's possible to see the correction.

Markup before this change (from the closing tag of the last list item to the closing tag of the fieldset):

```html
		</li>
		<p class='description description-thin'>
			<p style="margin-top:0">Radio test description</p>
		</p>				
	</ul>
</fieldset>
```

Markup after this change (paragraph is moved outside of the list, and is no longer double-wrapped):

```html
		</li>
	</ul>
	<p class="description ">Radio test description</p>
</fieldset>
```

The other note I wanted to share is that you may wish to re-test, but with a slight modification to the provided snippet. Changing `'desc_at_end' => true` to `'desc_at_end' => false` will you test both of the modified code paths (escaping was removed in both cases).

2024-09-03 22:13 UTC, barryhughes requested changes
Once you've made the changes suggested by Jorge, please let me know/re-request my review, and we can merge this :+1:

2025-12-27 13:11 UTC, closed without merging