[WIP][Accessibility] Announce notice messages after page loads
woocommerce/woocommerce pull request #50061
Opened 2024-07-28 17:44 UTC by Manussakis

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

1. This PR introduces a JS code that looks for any notice element with the `role="alert"` attribute on the page and focuses it if it exists once the page loads.
2. The markup of the success message of the add-to-cart action has been changed. Before this change, the link came before the message on the DOM. With this change, the message now comes first. There were two accessibility issues with the old markup:
    1. The visual order of the elements didn't match the DOM order, so the focus changing didn't follow a logical order.
    2. Once the notice message was focused, the link's content was announced before the message itself.
3. This PR introduces a new CSS class named `woocommerce-notice-content` used on the element that wraps the message and the link on the add-to-cart success message.

**Before**
![image](https://github.com/user-attachments/assets/9c6f522e-656d-4aab-9da4-a5f688226bbe)

**After**
![image](https://github.com/user-attachments/assets/dbe72402-e4e7-4836-a220-34b980b64072)

Closes #43614 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
5.
6.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-07-28 18:22 UTC, Manussakis commented on plugins/woocommerce/includes/wc-cart-functions.php
> +		$message = sprintf( '<div class="woocommerce-notice-content">%s <a href="%s" class="button wc-forward%s">%s</a></div>', esc_html( $added_text ), esc_url( wc_get_cart_url() ), esc_attr( $wp_button_c
Add a wrapper to the message and the link and swap their position in the DOM.

2024-07-28 19:35 UTC, Manussakis commented
@dkotter This PR is ready for code review.

2024-07-29 14:51 UTC, dkotter approved these changes
@ankitguptaindia @qasumitbagthariya This is ready for QA

2024-07-29 14:52 UTC, dkotter commented
@Manussakis One thing I just noticed, looks like this PR is causing one of the unit tests to fail. That will need to be fixed up before this can be merged in: https://github.com/woocommerce/woocommerce/actions/runs/10133808611/job/28019382690?pr=50061#step:7:121

2024-07-29 21:01 UTC, Manussakis commented
Thanks for spotting that, @dkotter . Somehow I didn't associate it with my changes.
@ankitguptaindia @qasumitbagthariya I have fixed the tests and this task is ready for QA.

2024-07-30 09:14 UTC, nielslange commented
I'll remove myself from the review, given that this PR affects the product page, while I'm maintaining the Cart and Checkout blocks.

2024-07-30 16:36 UTC, ankitguptaindia commented
Thanks for the PR @Manussakis this PR works as explained but I have some points to confirm:

1. When a product is added to the cart, a success message appears and announces "YourProduct has been added to your cart." However, this message is announced twice. Is this related to this PR, or can we fix this here?
2. When the message announces "YourProduct has been added to your cart," it also announces "1 more item," but there is no other item in the cart or on the page.

**Please watch this video explanation for more details:**  



https://github.com/user-attachments/assets/50eb4555-9635-4587-8ff7-034603ff57ee






QA Status-  WIP, will add more points tomorrow.

2024-07-30 19:46 UTC, Manussakis commented
@ankitguptaindia Thanks for testing this PR!
> 1. When a product is added to the cart, a success message appears and announces "YourProduct has been added to your cart." However, this message is announced twice. Is this related to this PR, or can we fix this here?
> 2. When the message announces "YourProduct has been added to your cart," it also announces "1 more item," but there is no other item in the cart or on the page.

This is how VoiceOver works in this context. The message it announces when the alert element is initially focused is like a summary:
`'"Belt" has been added to your cart, and 1 more item, alert, main'`
Let's break it down:
- `"Belt" has been added to your cart` – This is the first element in the alert.
- `and 1 more item` – Since it's a summary, VoiceOver doesn't announce all the elements now, so it only announces that in addition to the message before there is one more item inside the alert element, which is the "View cart" link on the right side of the alert.
- `alert,` – because the element has the `role="alert"` attribute.
- `main` – because the element is inside the `<main>` HTML tag.

Next, VoiceOver starts reading each one of the elements inside the alert. That's why the message is announced again. Notice that after announcing the message it announces `visited, link, View cart`, which is the "View cart" link on the right side.

Other screen readers may address alert messages differently, but this is something that users should update via screen reader preferences.

2024-08-02 11:38 UTC, ankitguptaindia commented
QA Report: Needs feedback ⚠️ 
---

@Manussakis Thanks for the detailed explanation https://github.com/woocommerce/woocommerce/pull/50061#issuecomment-2259089291. 


-----
Regarding the PR workflow: 

Part-1:  `Verify that after the page loads, the focus goes to the success message at the top of the page` 

It works as intended.  ✅ 

Demo: 

<Details>


https://github.com/user-attachments/assets/05609b26-a31f-4c7a-a87c-ef78cab93359

</Details>

-----------

Part -2: `Verify the error message gets the focus once the page loads.`. ⚠️ 

It works fine when editing the billing address but if editing the shipping address, sometimes it doesn't announce the alert message: 

<Details>

https://github.com/user-attachments/assets/45d27073-5e60-437e-a975-170637767c3b

</Details>

When trying with a new user in different tab, it doesn't announce the alert message: 


<Details>

https://github.com/user-attachments/assets/efe64546-843f-4d07-a94c-bc2c4221e6ba

</Details>

With Screen Reader Chrome extension, it works fine for same page: 

<Details>

https://github.com/user-attachments/assets/b36f5c76-373e-4f4a-8218-1b91c680715d

</Details>

2024-08-02 18:37 UTC, Manussakis commented
@ankitguptaindia Thanks for the feedback!
Part-2:
Good catch! I have updated the code.
Since Local returns AJAX requests almost instantly, could you also test this PR with a slower connection to simulate a more realistic scenario?

@dkotter Please review this change: [Cobine delay with queue method](https://github.com/woocommerce/woocommerce/pull/50061/commits/72d8efb993637338b46df1046e29211d96929f49)

2024-08-02 19:06 UTC, dkotter approved these changes

2024-08-05 11:58 UTC, ankitguptaindia commented
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.6.1
* Theme: 
**Storefront Version: 4.6.0  
**Twenty Twenty-Four Version: 1.2
* WooCommerce - Development version with this fix-specific branch.  
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 127
* OS: macOS Sonoma 14.5
* Git Branch: fix/43614


</Details>


**Test Results -** 

Tested with Safari, Firefox and Chrome, Changes work as expected. Tested via macOS Voice Over and Screen Reader Chrome extension. Tested with Storefront theme and Twenty-Twenty-Four theme
 

**Functional Demo /  Screencast -**

**With macOS Voice Over:**


https://github.com/user-attachments/assets/85846ffc-0f8e-46a9-8440-8ab2278cb766

2024-08-05 12:00 UTC, ankitguptaindia commented
@Manussakis PR changes LGTM. Please Un-draft this PR for the next step.

2024-08-05 12:29 UTC, Manussakis commented
@vikrampm1 This task is ready to be reviewed by the appropriate Woo team.

2024-08-05 16:28 UTC, jeffpaul commented
@woocommerce/woo-fse this PR relates to an issue labeled for your team and the PR is now ready for your review

2024-08-06 06:14 UTC, imanish003 commented
Thanks, @jeffpaul! As I am assigned to this PR, I can review it from the Woo FSE perspective. However, I believe it will require a review from @woocommerce/Rubik as well, as it touches files around the Cart and Checkout code.

2024-08-06 08:48 UTC, alexflorisca commented
> This PR introduces a new CSS class named woocommerce-notice-content used on the element that wraps the message and the link on the add-to-cart success message.

@Manussakis Why do we need the wrapper here? 

> Themes that override the WooCommerce default styles must update their CSS files to include styles for the woocommerce-notice-content CSS class.

This is quite worrying to me as it seems this has the potential for breaking a lot of themes. Could we find a way to avoid this?

2024-08-06 22:57 UTC, Manussakis commented
@alexflorisca, thanks for the feedback!

> Why do we need the wrapper here?

The wrapper holds the flex behavior that allows the order of the elements to be swapped while preserving the current visual alignment.

> This is quite worrying to me as it seems this has the potential for breaking a lot of themes. Could we find a way to avoid this?

I will look into it further.

2024-08-07 13:52 UTC, Manussakis commented
@alexflorisca I updated the PR description to explain the new changes after your feedback.

@dkotter Please re-review this PR.

2024-08-07 14:29 UTC, dkotter approved these changes

2024-08-07 15:07 UTC, jeffpaul commented
@imanish003 @alexflorisca this is back to you for review, thanks!

2024-08-07 15:41 UTC, alexflorisca commented
I'm happy with the code changes and the approach here now. But I'm off until next week and won't have time to properly test. So if @dkotter has tested it then we can merge, I don't see any problems with Cart & Checkout here.

2024-08-07 15:51 UTC, dkotter commented
@ankitguptaindia I know you tested this before but there's been some changes since (which you can read through the thread on this issue for full details). Can you test this one again before we proceed with merging?

2024-08-10 08:17 UTC, ankitguptaindia commented
Re-tested PR after new changes in Safari, Chrome and Firefox with macOS 14.5VoiceOver.

https://github.com/user-attachments/assets/5e9a7d86-8f64-42fc-b055-3aed117d9544



**Next Step-** PR is ready for merge. 🚀

2024-08-10 13:09 UTC, Manussakis commented
@vikrampm1 This PR is ready for the next step.

2024-08-12 15:13 UTC, vikrampm1 commented
@imanish003 / @woocommerce/woo-fse this PR is ready for your review!

2024-08-13 12:54 UTC, imanish003 requested changes
Hey @Manussakis,

Thanks for working on improving the accessibility of the notice messages 🚀 I have left one comment on the PR.

2024-08-13 12:54 UTC, imanish003 commented on plugins/woocommerce/client/legacy/js/frontend/woocommerce.js
> +	} );
Can we please avoid using JQuery in this PR? Instead, can we use Vanilla JavaScript with `IntersectionObserver` or `MutationObserver` to achieve the same functionality? Internally, there was a discussion (pcShBQ-1S4-p2) around it with title "Please don’t write any more JQuery in WooCommerce" by @samueljseay. Based on this @ObliviousHarmony also created issue #48589. As we are making efforts to get rid of JQuery, it would be great if we can avoid using it in this PR. Otherwise, it will introduce another peace of code that will eventually need to be migrated. 

What do you think?

2024-08-13 12:58 UTC, senadir commented on plugins/woocommerce/client/legacy/js/frontend/woocommerce.js
> +	} );
I'd advice against using Vanilla here, at least, not using `IntersectionObserver` and `MutationObserver`. It make sense to stop using jQuery but this is already an existing script that does exactly that. I understand @samueljseay advised against that but unless we have some good effort to get rid of it, we would be just fragmenting files.

If we're to go with vanilla, I'd be wary of observers, they're a bit recentish and we don't ship any polyfills for them, we hade some reports in Checkout block of a Checkout not loading due to the browser (usally an old phone or an in-app android browser like facebook) not supporting that.

2024-08-13 14:57 UTC, Manussakis commented on plugins/woocommerce/client/legacy/js/frontend/woocommerce.js
> +	} );
Thanks @imanish003 @senadir !
I will refactor the code to use Vanilla JS without using observers.

2024-08-13 18:14 UTC, Manussakis commented
@imanish003 @dkotter I have updated the code to use vanilla JS, please review it: [Refactor to vanilla JS code that focus on notice message](https://github.com/woocommerce/woocommerce/pull/50061/commits/186d2a20fa9919e5e3a4a71b7268adab869fd565)

@ankitguptaindia This PR will need another round of QA once the code is approved.

2024-08-13 18:37 UTC, dkotter approved these changes

2024-08-13 20:26 UTC, Manussakis commented
@ankitguptaindia Please test this PR again 🙏

2024-08-18 18:49 UTC, qasumitbagthariya commented
### QA Update ✅ 
-------------

I have checked this PR in the `Manussakis:fix/43614` branch and the changes are working as expected.

**Testing the add-to-cart notice** ✅

https://github.com/user-attachments/assets/e694b8b5-ee18-4d10-8d3e-df7eef0a863d

**Testing the stock notice** ✅

https://github.com/user-attachments/assets/612dc392-04c9-4493-980f-bfe1e15416cc

**Testing the Address form notices** ✅

https://github.com/user-attachments/assets/87079187-237d-4676-b8ae-150a82e2fcf2



**Testing Environment** 

<Details>

- WordPress: 6.6
- Theme: Twenty Twenty-Four 1.2
- WooCommerce - WooCommerce - Dev version with this fix specific branch.
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: Manussakis:fix/43614

</Details>


**Status update:**
@vikrampm1  This PR is ready for the next step.

2024-08-19 11:32 UTC, vikrampm1 commented
@imanish003 @senadir this is back for your re-review!

2024-08-20 09:01 UTC, imanish003 approved these changes
@Manussakis Changes looks good to me. I have tested the changes locally and they are working as expected. Thanks for updating the code to use Vanilla JavaScript instead of JQuery 🙌🏻

2024-08-20 16:51 UTC, vikrampm1 commented
@imanish003 this is ready to be merged by you / Woo now. Thanks!

2024-08-21 06:24 UTC, merged

2024-08-26 19:43 UTC, ktmn commented
> This PR introduces a JS code that looks for any notice element with the role="alert" attribute on the page and focuses it once the page loads.

https://github.com/woocommerce/woocommerce/issues/43614:

> You can either do this by:
> A) When the page reloads, set keyboard focus on the status message so it is read out. OR
> B) Add an [aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) region on the status message and trigger it after the page loads.

@Manussakis Is option "A" ideal? 

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role:

> The element with the alert role does not have to be able to receive focus, as screen readers (speech or braille) will automatically announce the updated content regardless of where keyboard focus when the role is added.

> Setting `role="alert"` is equivalent to setting `aria-live="assertive"` and `aria-atomic="true"`. As they don't receive focus, focus does not need to be managed and no user interaction should be required.

---

For me, the focus adds a thick black border to the alert (browser default styles):

```css
:focus-visible {
    outline: -webkit-focus-ring-color auto 1px;
}
```

I'm wondering if hurts accessibility if I were to to disable it with:

```css
.wc-block-components-notice-banner:focus-visible {
    outline: none;
}
```
as it's not actually a focusable element. For example when going to **My account -> Downloads** and there are no downloads, the message that says _"No downloads available yet."_ has a thick outline which looks like the message is styled poorly.

2024-08-27 15:04 UTC, Manussakis commented
From #43614 

> You can either do this by:
A) When the page reloads, set keyboard focus on the status message so it is read out. OR
B) Add an [aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) region on the status message and trigger it after the page loads.

> @Manussakis Is option "A" ideal?

@ktmn Thanks for raising this question.

Live regions tend to work well across different browser/screen reader combinations, but the ideal use of it is when their content is updated dynamically via JavaScript. However, most pages in Woo come with the live region content populated on the initial markup, which doesn't trigger its announcement by screen readers.

Please, check the "Live regions that are already "populated" don't work" section of this article: https://tetralogical.com/blog/2024/05/01/why-are-my-live-regions-not-working/

Considering this scenario, focusing on the live region once the page loads becomes the better option for fixing this issue, in my opinion.

I agree with your point regarding the thick black border added to the alert when it gets the focus and would add one more selector to your suggestion:
```scss
.wc-block-components-notice-banner {
	&:focus,
	&:focus-visible {
		outline: none;
	}
}
```

2024-08-27 21:13 UTC, Manussakis commented
@ktmn I have created the https://github.com/woocommerce/woocommerce/issues/51003 issue to tackle the focus style of the notice message.

2024-09-09 12:49 UTC, senadir commented
Following up here to say that this PR introduced a small regression in One Page Checkout. When landing on a product page with Checkout in it, focus will jump from top of page to Checkout (which sits low in the page).

Maybe we can add some exclude classes to notices (dont-autofocus) and One Page Checkout can hook into Checkout and add those classes.

2024-09-10 14:41 UTC, jeffpaul commented
@Manussakis @vikrampm1 can one of you please open an issue to document @senadir's issue above and drop into our a11y project board to work on resolving?

2024-09-11 16:30 UTC, Manussakis commented
@jeffpaul I will create the issue once I reproduce it locally so I can fill the issue form out with all the bug details.
I plan to do it today.

2024-10-04 21:38 UTC, Manussakis commented
> Following up here to say that this PR introduced a small regression in One Page Checkout. When landing on a product page with Checkout in it, focus will jump from top of page to Checkout (which sits low in the page).
> 
> Maybe we can add some exclude classes to notices (dont-autofocus) and One Page Checkout can hook into Checkout and add those classes.

@senadir Would you mind giving me more context on this issue?
I activated the One Page Checkout from the Product data panel:
![image](https://github.com/user-attachments/assets/8188d2e2-946b-4df2-8e82-10fd3cf1ab5c)

Then I went to the product page, but the only notice message available low on the page is the Coupon one, which has the `role="status"` attribute, therefore, the focus is not jumping there since the script looks only for notice messages [with the `role="alert"` attribute](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/js/frontend/woocommerce.js#L161).

![image](https://github.com/user-attachments/assets/1a81fe10-4e40-41df-9ebd-a6be8812a6f5)

I have tested with both Classic and Block themes, but I was not able to reproduce it yet.

Could you please help me with that?

2024-11-11 19:20 UTC, vikrampm1 commented
@senadir can you help review the comment above?

2024-11-14 15:18 UTC, senadir commented
Hey! I do recall it jumping to notice, though maybe it was the account creation one. I can look again today.

2024-11-26 18:45 UTC, vikrampm1 commented
@senadir following up on the above if you have any additional comments.

2025-01-15 16:30 UTC, vikrampm1 commented
@senadir #51003 is still blocked and awaiting your response on the above if you can take a look.

2025-01-17 11:12 UTC, senadir commented
I can no longer reproduce the issue, I'm not sure what changed, but we can consider those unblocked for now