Add product form extensibility tutorials
woocommerce/woocommerce pull request #50137
Opened 2024-07-30 15:06 UTC by louwie17

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Add two tutorials, one on using the generic fields and the second one on writing a custom field.
**Note:** Some of the links that link to the new markdown files are pointing at `trunk` currently, so they may not work until merged.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Read through the documentation to make sure everything looks ok
2. Walk through the tutorials to see if you can follow it and it works.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-07-31 15:20 UTC, nathanss requested changes
Added some suggestions. Overall, it looks good! Nice job!

2024-07-31 15:20 UTC, nathanss commented on docs/product-editor-development/how-to-guides/custom-field-tutorial.md
> +If you wanted to create a plugin from scratch with the necessary build tools I recommend using the `@wordpress/create-block` script, we also have a specific template for the product form: [README](ht
```suggestion
If you want to create a plugin from scratch with the necessary build tools, we recommend using the `@wordpress/create-block` script. We also have a specific template for the product form: [README](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/create-product-editor-block/README.md).
```

2024-07-31 15:20 UTC, nathanss commented on docs/product-editor-development/how-to-guides/custom-field-tutorial.md
> +Inside a new folder within your plugin lets create a `block.json` file with the contents below. The only main difference between this `block.json` and a `block.json` for the site editor is that we wi
```suggestion
Inside a new folder within your plugin, let's create a `block.json` file with the contents below. The only main difference between this `block.json` and a `block.json` for the site editor is that we will set `supports.inserter` to false, so it doesn't show up there. We will also be registering this slightly different.
```

2024-07-31 15:20 UTC, nathanss commented on docs/product-editor-development/how-to-guides/custom-field-tutorial.md
> +In the same directory create a `index.js` file, which we can keep simple by just outputting a hello world.
```suggestion
In the same directory, create a `index.js` file, which we can keep simple by just outputting a hello world.
```

2024-07-31 15:20 UTC, nathanss commented on docs/product-editor-development/how-to-guides/custom-field-tutorial.md
> +In react:
```suggestion
In React:
```

2024-07-31 15:20 UTC, nathanss commented on docs/product-editor-development/how-to-guides/custom-field-tutorial.md
> +    return <p>Hello World (from the editor).<p>;
```suggestion
    return <p>Hello World (from the editor).</p>;
```

2024-07-31 15:20 UTC, nathanss commented on docs/product-editor-development/how-to-guides/custom-field-tutorial.md
> +Lastly in order to make this work the block registration needs to know about the JavaScript dependencies, we can do so by adding a `index.asset.php` file with the below contents:
```suggestion
Lastly, in order to make this work the block registration needs to know about the JavaScript dependencies, we can do so by adding a `index.asset.php` file with the below contents:
```

2024-07-31 15:20 UTC, nathanss commented on docs/product-editor-development/how-to-guides/custom-field-tutorial.md
> +What I did was the following ( see [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/ProductBlockEditor/ProductTemplates/README.md#usage) for more re
Can we avoid the use of "I" here somehow?

2024-07-31 15:20 UTC, nathanss commented on docs/product-editor-development/how-to-guides/custom-field-tutorial.md
> +We can add it to our `edit` function pretty easily by making use of `wp.components`. I will also add a constant for the filter options.
Same as before, I would try to avoid "I will also add", "I also added", etc.

2024-07-31 15:20 UTC, nathanss commented on docs/product-editor-development/how-to-guides/generic-fields-tutorial.md
> +Lets say we want to add something to the basic details section, we can do so by making use of the above mentioned hook:
```suggestion
Let's say we want to add something to the basic details section, we can do so by making use of the above mentioned hook:
```

2024-08-01 08:09 UTC, louwie17 commented
> Added some suggestions. Overall, it looks good! Nice job!

Thanks for the review @nathanss, I have addressed all your suggestions as part of this commit: https://github.com/woocommerce/woocommerce/pull/50137/commits/a58739f125580f23432cc1447b3a1b8492acf615

2024-08-01 13:45 UTC, nathanss approved these changes

2024-08-01 13:50 UTC, merged