[Experimental] Product Filters Redesign > Overlay: Add Fullscreen view
woocommerce/woocommerce pull request #50505
Opened 2024-08-08 21:25 UTC by thealexandrelara

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #49977.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment  Add the Fullscreen view to the Product Filters

</details>

2024-09-06 08:38 UTC, dinhtungdu requested changes
Thanks for working on the PR. I tested the overlay locally and I can confirm the overlay works well following the testing instructions:
- the trigger button is rendered when the overlay setting is set to Always.
- the fullscreen overlay is opened when clicking on the trigger button.
- the overlay is closed when clicking on the close button.
However, I have some questions:
- You didn't mention the Mobile settings, however, I can see the trigger button when I set the overlay setting to Mobile.
- When I set the overlay setting to Always, I can still see the main filter blocks, which are expected to be hidden. Are you working on it in other PRs?
- I can't scroll or swipe down the content of the overlay, it seems to affect the main content of the page instead. So I can't access the filter block under the fold of the overlay.

2024-09-06 17:40 UTC, thealexandrelara commented
Thank you for reviewing it @dinhtungdu!

> * You didn't mention the Mobile settings, however, I can see the trigger button when I set the overlay setting to Mobile.

Yes, when the overlay is set to Mobile, it should be hidden on desktop, but it should appear when the user is on a mobile device.

> * When I set the overlay setting to Always, I can still see the main filter blocks, which are expected to be hidden. Are you working on it in other PRs?

I'll be working on that in a separate PR, basically I would have to edit some other parts in the codebase to remove those blocks on the frontend. We also will need to check how we would display that in the editor, when merchants select the Always option, should we hide the filters in the editor? Should we show some kind of a message stating that the filters will be hidden?

> * I can't scroll or swipe down the content of the overlay, it seems to affect the main content of the page instead. So I can't access the filter block under the fold of the overlay.

Nice catch! I'll investigate this. We had something similar when we created the Product Gallery overlay, so I believe we can implement the same solution here.

2024-09-06 21:01 UTC, roykho requested changes
Thanks for working on this. Mostly looks great. Just a few things which I left comments.

✅ When overlay is set to "Always", I can see the overlay navigation button in the frontend and clicking on it opens up a fullscreen dialog of the filters.
✅ When overlay is set to "Mobile", I no longer see the overlay navigation button in the frontend if I am not on a mobile device.
🛑 I also had issue with the scrolling inside the fullscreen dialog as mentioned by Tung.

2024-09-06 21:01 UTC, roykho commented on plugins/woocommerce-blocks/tests/e2e/tests/product-filters-overlay/product-filters-overlay-template-part.block_theme.spec.ts
> +			await page.getByText( 'Product Filters (Experimental)' ).click();
Since we're using lots of these string names, perhaps we should add a block data object at the top so that we could replace these strings as variables and only need to change/update the string names in one place in the future for example when we need to remove the "(Experimental)"...etc. Same with other tests if necessary.

2024-09-09 13:26 UTC, thealexandrelara commented on plugins/woocommerce-blocks/tests/e2e/tests/product-filters-overlay/product-filters-overlay-template-part.block_theme.spec.ts
> +			await page.getByText( 'Product Filters (Experimental)' ).click();
Great suggestion! I'm going to move these names to a constant.

2024-09-09 21:05 UTC, thealexandrelara commented on plugins/woocommerce-blocks/tests/e2e/tests/product-filters-overlay/product-filters-overlay-template-part.block_theme.spec.ts
> +			await page.getByText( 'Product Filters (Experimental)' ).click();
Done in 77e14968946a69a1c95c370b0c539c97fdc71416

2024-09-09 21:07 UTC, thealexandrelara commented
Hey @dinhtungdu and @roykho, I fixed the issues you both raised. Would you mind re-reviewing this PR?

2024-09-09 23:06 UTC, roykho approved these changes
Thanks for working on this and making the changes.

✅ Setting the overlay mode to mobile and always, I see the navigation block in the editor.
✅ Setting the overlay mode to mobile and always, I see the navigation block in the frontened.
✅ I am able to open the fullscreen dialog box in the frontend by clicking on the navigation trigger button.
✅ I am able to close the dialog box in the frontend by clicking on the navigation close button.
✅ I am able to scroll the filters in the dialog box when filters are longer than the screen.
✅ When set to mobile, I only see the overlay navigation trigger button in mobile devices.

2024-09-10 12:38 UTC, dinhtungdu requested changes
Thanks for the update. I can confirm I can scroll the overlay content now. The only concern I have is this experimental PR is touching a public feature, and I don't think we should do that. The tests are also failing too.

---

>>When I set the overlay setting to Always, I can still see the main filter blocks, which are expected to be hidden. Are you working on it in other PRs?

>I'll be working on that in a separate PR, basically I would have to edit some other parts in the codebase to remove those blocks on the frontend. We also will need to check how we would display that in the editor, when merchants select the Always option, should we hide the filters in the editor? Should we show some kind of a message stating that the filters will be hidden?

Looks like what you described falls under the scope of https://github.com/woocommerce/woocommerce/issues/50866.
 
> should we hide the filters in the editor?

IMO, we should do our best to match the front end and the editor preview, so my answer to your question is, yes, we should. Observing the design, I believe it's also how Jarek wants the block to behave.

2024-09-10 12:38 UTC, dinhtungdu commented on plugins/woocommerce-blocks/assets/js/blocks/product-gallery/frontend.tsx
> -			);
Even the change looks innocent, I think we should avoid modifying the public feature in an experimental PR.

2024-09-10 20:04 UTC, thealexandrelara commented on plugins/woocommerce-blocks/assets/js/blocks/product-gallery/frontend.tsx
> -			);
Nice catch! I'll leave to modify this once the experimental flag is removed from the Product Filters block.

2024-09-11 07:09 UTC, dinhtungdu approved these changes
Thanks for the updates! This is LGTM now so I'm approving. Note that the CI is still failing.

2024-09-11 14:30 UTC, merged