Add react-powered main payments settings screen
woocommerce/woocommerce pull request #50825
Opened 2024-08-21 04:43 UTC by chihsuan

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/50721.

This PR replicates the existing payment methods screen in the new React component (as much as possible).

It provides the following functionalities:

- It pre-fills the WooPayments gateway when store is eligible for it.
- Show the payment methods in a table by fetching the payment methods from the server.
- Can enable/disable payment methods.
- Show additional payment providers in the last row.

It doesn't include the following:

- The re-order functionality.
- The 3-dots menu on the WooPayments row.
- The sub menu items `WooPayments |All payment methods` when WooPayments is enabled.
- The Save button since re-order functionality is not supported

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. In a fresh site with beta tester plugin installed, go through onboarding wizard and set country to Afghanistan.
2. Go to `Tools > WCA Tester Helper` and enable the feature flag `reactify-classic-payments-settings`.
2. Go to `WooCommerce > Settings > Payments`
3. Observe the Main payments screen shows the payment methods in a table without WooPayments.
4. Change store country to United States.
5. Observe the Main payments screen shows the payment methods in a table with WooPayments.
6. Enable/disable payment methods and observe the changes.
7. Click the payment method and confirm it redirects to the corresponding settings page.
8. Click on WCPay `Install` button and confirm it redirects to the payment page after installation.
9. Go back to the payments screen and confirm the WooPayments row is updated. 
10. Observe that WooPayments banner (`Payments made simple, designed exclusively for WooCommerce stores.`) is shown

#### Before installing WCPay:

Classic:

![Screenshot 2024-08-21 at 12 41 20](https://github.com/user-attachments/assets/8e5dd04c-bc5a-4ed6-99b7-c5523a36535f)

React:

![Screenshot 2024-08-21 at 12 41 32](https://github.com/user-attachments/assets/fd0ed9f2-9f58-4992-91fc-75311544bc5a)

#### After installing WCPay:

Classic:

![Screenshot 2024-08-21 at 12 41 03](https://github.com/user-attachments/assets/6ad859f4-a54a-45a3-87e7-6d67f10f4ace)

React:
![Screenshot 2024-08-21 at 12 40 46](https://github.com/user-attachments/assets/a635692b-8479-4e31-b2c9-08ab2095a32f)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-08-21 09:54 UTC, ilyasfoo requested changes
Looking good so far, @chihsuan! I also found that `Recommended payment providers` is not shown when it's supposed to because I've removed it in https://github.com/woocommerce/woocommerce/commit/3ae1aca65a386bfbaacf14fbda1a8682c7b0578f. I can write a PR to re-introduce it in main settings page, let me know!

#### Issue 1: Extra payment methods

When `Stripe` plugin is installed and activated, multiple Stripe's payment methods are listed ([screenshot](https://github.com/user-attachments/assets/2af3f154-0bce-4517-ab48-fe664896f3cf)). While this did not occur with the non-react screen ([classic screenshot](https://github.com/user-attachments/assets/3b9702f2-9536-4064-8c36-83ed8792648f)).

I reproduce this with: 
1. Setting my country to Mexico
2. Install Stripe plugin (I also installed a bunch other from the "Recommended payment providers" while the feature flag is disabled). 
3. Observe the Stripe payment methods in `WooCommerce > Settings > Payments` like `Stripe Alipay`

#### Issue 2: Unable to enable payment gateway

Another issue I found that payment gateways couldn't be enabled (I believe it should navigated users to the specific payment gateway settings page).

To reproduce:

1. In a fresh site, select Mexico in onboarding
2. Go to `WooCommerce > Settings > Payments`
3. Install Stripe plugin from the "Recommended payment providers"
4. Enable the `reactify-classic-payments-settings` feature flag
2. Go to `WooCommerce > Settings > Payments`
3. Attempt to enable `Stripe – Credit Card (Stripe)`
4. Observe you're not not redirected anywhere and error in console



https://github.com/user-attachments/assets/1fd6653c-7114-47cc-8bac-b75971d2cd78

2024-08-21 09:54 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/settings-payments/components/payment-method.tsx
> +						window.woocommerce_admin.nonces?.gateway_toggle || '',
I wonder if we should even try to fetch if nonce is unavailable? What do you think of adding a guard for the variable?

2024-08-21 12:39 UTC, adrianduffell commented
> I also found that Recommended payment providers is not shown when it's supposed to because I've removed it in https://github.com/woocommerce/woocommerce/commit/3ae1aca65a386bfbaacf14fbda1a8682c7b0578f. I can write a PR to re-introduce it in main settings page, let me know!

@ilyasfoo @chihsuan Good catch on this. I'll check whether it's in the requirements!

2024-08-21 20:48 UTC, moon0326 reviewed
Other than what @ilyasfoo already mentioned, LGTM with a minor comment.

When I click `Install` button, it does not change to busy state unlike non-react page.


https://github.com/user-attachments/assets/29617595-075e-44f9-8da2-ae5365605166

2024-08-22 08:23 UTC, chihsuan commented on plugins/woocommerce-admin/client/settings-payments/components/payment-method.tsx
> +						window.woocommerce_admin.nonces?.gateway_toggle || '',
Good idea. Updated to check nonce in d19baf63227ad6c48da02d4dd94c7a618f853b27

2024-08-22 08:23 UTC, chihsuan commented
> When I click `Install` button, it does not change to busy state unlike non-react page.

Good catch! Fixed in 466c246ecf2d92d3d02186762f5674175d7b0f62

2024-08-22 15:32 UTC, adrianduffell commented
> I also found that Recommended payment providers is not shown when it's supposed to because I've removed it in https://github.com/woocommerce/woocommerce/commit/3ae1aca65a386bfbaacf14fbda1a8682c7b0578f. I can write a PR to re-introduce it in main settings page, let me know!

@ilyasfoo @chihsuan It's considered a "nice to have" (see below). How about we add a follow-up PR to re-introduce it if it's not much work?

_"Having the recommended plugins listing in place – as it is today – will greatly help us build on top of it. But I’d say the installed gateways list is more important in case you need to prioritize"._

2024-08-23 02:33 UTC, chihsuan commented
> It's considered a "nice to have" (see below). How about we add a follow-up PR to re-introduce it if it's not much work?

Sounds good! 👍

2024-08-23 03:54 UTC, chihsuan commented
Thanks for the detailed report! @ilyasfoo I've fixed those two issues in 97e088a0d9f0c5dc99f6dae9dcc7e4fe7d94f5d0 and 
e8a2ae71576c6d49cbfb0b1e2d3a220c081603d1

2024-08-23 04:10 UTC, chihsuan commented
@adrianduffell 👋  I found something related to https://github.com/woocommerce/team-ghidorah/issues/349.

WooPayments uses React + JQuery script to show a confirmation modal when disabling the payment method (see screen recording below). 


They hook into the `woocommerce_admin_field_payment_gateways` action to [render a `div`](
https://github.com/Automattic/woocommerce-payments/blob/0d017f60546aa1870cac7b437b7cedad14ccbf0e/includes/admin/class-wc-payments-admin.php#L1067-L1076
), which is then [rendered as a modal using React](https://github.com/Automattic/woocommerce-payments/blob/0d017f60546aa1870cac7b437b7cedad14ccbf0e/client/payment-gateways/index.js#L12-L20).

I couldn't make it work with the react setting screen in this PR. I think WooPayments need to change something in their code to make it work:

1. WooPayments need to use a valid div tag. It's using the self-closing div tag `<div />` which is not valid and somehow breaks the React page so I have to disable their output buffer to make the page work.
2. WooPayments [listen to the JQuery `ajaxSend` event](https://github.com/Automattic/woocommerce-payments/blob/develop/client/payment-gateways/payment-gateways-confirmation.js#L90) to show the modal. I think they need to change it to listen to a native event to make it work with React. 


https://github.com/user-attachments/assets/b259bada-1cfd-45cf-94b3-b403654d5e6b

2024-08-23 08:14 UTC, adrianduffell commented
> I found something related to https://github.com/woocommerce/team-ghidorah/issues/349

Thanks @chihsuan, good find! We can mention it in the audit but proceed without it in this PR 👍

2024-08-26 02:34 UTC, ilyasfoo commented
> It's considered a "nice to have" (see below). How about we add a follow-up PR to re-introduce it if it's not much work?

@adrianduffell  Sounds good, it should be a quick PR, I'll attempt to do it today

2024-08-26 03:10 UTC, ilyasfoo approved these changes
Minor comments on translations, but tests well, pre-approving! 🚢

2024-08-26 03:10 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/settings-payments/components/payment-method.tsx
> +								: `Set up the "${ method_title }" payment method`
These are missing translations

2024-08-26 03:10 UTC, ilyasfoo commented on plugins/woocommerce-admin/client/settings-payments/components/payment-method.tsx
> +						aria-label={ `The "${ method_title }" payment method is currently ${
Also missing translation

2024-08-26 07:21 UTC, chihsuan commented on plugins/woocommerce-admin/client/settings-payments/components/payment-method.tsx
> +								: `Set up the "${ method_title }" payment method`
Good catch! Fixed in 62a3b2209236f8966678f6da362834552213143a

2024-08-26 07:21 UTC, chihsuan commented on plugins/woocommerce-admin/client/settings-payments/components/payment-method.tsx
> +						aria-label={ `The "${ method_title }" payment method is currently ${
Fixed in 62a3b2209236f8966678f6da362834552213143a

2024-08-27 05:05 UTC, moon0326 approved these changes
LGTM! Thank you for the update 👍 🚀

2024-08-27 06:30 UTC, merged