Fix incorrectly rendered HTML tags in docs
woocommerce/woocommerce pull request #50966
Opened 2024-08-26 18:40 UTC by JacklynBiggin

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Fixes an issue reported in the community Slack where HTML tags aren't being rendered correctly on certain pages.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

This branch is live on `develop` for testing. Visually confirm that all pages are rendered as expected.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-08-27 08:15 UTC, piinthecloud approved these changes

2024-08-27 08:22 UTC, piinthecloud requested changes
There's still some missing characters to convert to HTML entities

2024-08-27 08:25 UTC, piinthecloud commented on docs/building-a-woo-store/adding-a-custom-field-to-variable-products.md
Lines  97, 98, 150

2024-09-04 17:15 UTC, JacklynBiggin commented on docs/building-a-woo-store/adding-a-custom-field-to-variable-products.md
Fixed!

2024-09-04 20:25 UTC, piinthecloud approved these changes

2024-09-04 20:25 UTC, merged