Remove the wc combobox component, it is no longer used
woocommerce/woocommerce pull request #50975
Opened 2024-08-27 01:55 UTC by samueljseay

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-08-29 14:34 UTC, mikejolley submitted a review, later dismissed
There are some types exported by that file still being consumed in places. The CI fails are valid. See:

https://github.com/woocommerce/woocommerce/actions/runs/10612882905/job/29415561141?pr=50975

Thanks

2024-08-30 01:36 UTC, samueljseay commented
Whoops I missed that failure. Apologies.

Have moved these files to using the types for the Select that they render now anyway. Will ping for re-review when CI is 🍏

2024-08-30 12:23 UTC, opr requested changes
Thanks Sam! Just one tiny nit relating to a comment, and in https://github.com/woocommerce/woocommerce/blob/9f7a6779f6d4134d9bc74b9655dcac6dbe108360/plugins/woocommerce-blocks/assets/js/base/components/country-input/style.scss#L3 I just want to confirm if this import is still needed?

2024-08-30 12:23 UTC, opr commented on plugins/woocommerce-blocks/assets/js/base/components/country-input/CountryInputProps.ts
On line 15 of this file the comment references combobox still, could we update it?

2024-08-31 01:35 UTC, samueljseay commented
> I just want to confirm if this import is still needed?
@opr Oh right 🤔 I think when searching I thought it was still needed, but I can see now that import is for the country input. We can remove that :) thanks for pointing that out.

2024-08-31 01:38 UTC, samueljseay commented on plugins/woocommerce-blocks/assets/js/base/components/country-input/CountryInputProps.ts
Thanks good spotting. Fixed.

2024-09-02 11:20 UTC, opr approved these changes
Thanks, Sam this looks great now. Tested in Edge, Firefox, Safari 👌🏼

2024-09-03 09:20 UTC, merged