Fixed : Path cannot be empty in wc_template_redirect() include statement
woocommerce/woocommerce pull request #51307
Opened 2024-09-12 06:47 UTC by narenin

Closes #51304 .

### How to test the changes in this Pull Request:

No steps to share, this was observed by monitoring error logs.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-10-15 10:51 UTC, agabor commented
I came to fix this myself, but then I noticed that there is already an open issue with a pull request. However, I would suggest to do this fix in a style that is more consistent with handling missing template in other parts of WooCommerce:

```php
$not_found_template = get_query_template( '404' );
if ( ! empty( $not_found_template ) && file_exists( $not_found_template ) ) {
	include $not_found_template;
}
```

2025-01-15 14:31 UTC, naman03malhotra requested changes
Thank you for working on it, the change looks good to me, however I agree with the comment https://github.com/woocommerce/woocommerce/pull/51307#issuecomment-2413552994 to make it more defensive and aligned with how we handle the template check in the rest of WooCommerce.

Can you please update the code accordingly?

2025-01-15 15:04 UTC, narenin commented
@naman03malhotra Thanks for the feedback, I have implemented the suggestions.

2025-01-17 15:02 UTC, naman03malhotra reviewed
Can you please also update the step by step testing instructions for our internal and quality teams to test it?

https://github.com/woocommerce/woocommerce/pull/54621 this PR can be used as a reference on how to structure your testing instructions.

2025-02-04 05:48 UTC, closed without merging

2025-02-04 05:48 UTC, naman03malhotra commented
Closing on behalf of: https://github.com/woocommerce/woocommerce/pull/54927