Add Upsells collection
woocommerce/woocommerce pull request #51374
Opened 2024-09-13 09:28 UTC by kmanijak

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-09-13 20:29 UTC, ObliviousHarmony commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php
> +				);
```suggestion
				$upsells = array_map( 'strval', $product->get_upsell_ids() );
```

Interestingly, PHP actually lets you just use the string name of the function as the argument!

2024-09-17 04:46 UTC, ObliviousHarmony requested changes, later dismissed
Thanks @kmanijak, it's great to see an implementation of the collection handlers 😄 This tests well for me, however, I'm _not_ going to approve it yet until a decision is made on the handlers. After all, this is targeting my branch!

2024-09-18 15:24 UTC, imanish003 approved these changes
Hey @kmanijak,

I tested the changes and everything seems to be working as expected. Here is what I tested:

**Single Product template**
- ✅ It's showing 8 products in the editor on Single Product template
- ✅ Product with Upsells:
	- ✅ Rendered with "You may also like" heading
	- ✅ Correct Upsell products are showing on frontend
- ✅ Product without Upsells:
	- ✅ Not rendered

**Specific product template**
- ✅ Upsells are showing in the editor on Specific Product template

**Cart**
- ✅ On Editor, it previews 8 products in preview mode
- ✅ Upsells collection is empty when product with no upsells is added to cart
- ✅ Upsells collection is rendered when product with upsells is added to cart
- ✅ Upsells from two products are merged (no specific order). There's no duplicates.

---

Code also looks good to me 🚀 I can see that there is some duplication of code between "Related Products" and "Upsells" collection but I believe refactoring can be done as part of new task.

2024-09-18 15:24 UTC, imanish003 commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php
> +				}
Excellent work, Karol! I really appreciate how you've handled this edge case 💪🏻 This is important because there will be cases when the merchant might not have selected a product reference.

2024-09-18 15:24 UTC, imanish003 commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php
> +				$upsells        = array_diff( $unique_upsells, $product_reference );
💜

2024-09-21 13:58 UTC, merged