Add Dimensions to Product Collection block
woocommerce/woocommerce pull request #51420
Opened 2024-09-16 19:18 UTC by octaedro

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #47884.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-09-26 04:13 UTC, kmanijak requested changes
Hey, thanks for taking care of it! I tested the changes and found some issues but we're getting there!

One more thing is the Product Collection is left-aligned in Editor and centered in frontend when fixed width is applied

Editor | Frontend
-- | --
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/f8af9a04-a99b-4be5-bbee-75ff9d2ca1b1"> | <img width="801" alt="Screenshot 2024-09-26 at 12 11 24" src="https://github.com/user-attachments/assets/99e2814d-4b71-4daf-a3d4-134ed4faaa53">

I don't have preferences in which way but they should be aligned 🤔 I guess centered makes more sense and brings more value until we add some alignment options.

2024-09-26 04:13 UTC, kmanijak commented on plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx
> -import { ProductCollectionAttributes } from '@woocommerce/blocks/product-collection/types';
I think it's in use so should be brought back.

2024-09-26 04:13 UTC, kmanijak commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php
> +			$style .= sprintf( 'width:%dpx;', intval( $fixed_width ) );
Control allows you to change units so we should not assume it's `px`. BTW unit is respected in Editor

<img width="286" alt="image" src="https://github.com/user-attachments/assets/eb77d32b-c819-4b9a-ab18-e9da63ebea40">

2024-09-26 04:13 UTC, kmanijak commented on plugins/woocommerce-blocks/assets/js/blocks/product-collection/edit/inspector-controls/width-options-control.tsx
> +			hasValue={ () => true }
I suggest using actual conditions for `hasValue` so basically whenever the value is different from a default:

```suggestion
			hasValue={ () => widthType !== WidthOptions.FILL }
			isShownByDefault
```

You can even import the default value from `plugins/woocommerce-blocks/assets/js/blocks/product-collection/constants.ts` for comparison.

If you wanted to make sure option is shown by default, use `isShownByDefault` prop as in the suggestion above.

2024-09-26 15:05 UTC, octaedro commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php
> +		return sprintf( '<div>%s</div>', $block_content );
We add this `div` to center the product list on the front end when we select a percentage (%) `width`.

2024-09-26 19:31 UTC, octaedro commented on plugins/woocommerce-blocks/assets/js/blocks/product-template/edit.tsx
> -import { ProductCollectionAttributes } from '@woocommerce/blocks/product-collection/types';
Good eyes! Added in the commit [cb8407d](https://github.com/woocommerce/woocommerce/pull/51420/commits/cb8407d66ce45e22bfa6da39ee36cd086f423f48)

2024-09-26 19:32 UTC, octaedro commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductCollection.php
> +			$style .= sprintf( 'width:%dpx;', intval( $fixed_width ) );
Good call! I fixed this in the commit [1620002](https://github.com/woocommerce/woocommerce/pull/51420/commits/1620002ff43b43b40ef7e02ede420333ed8f7b52)

2024-09-26 19:47 UTC, octaedro commented
Thank you @kmanijak for your review,

> I don't have preferences in which way but they should be aligned 🤔 I guess centered makes more sense and brings more value until we add some alignment options.

Good idea, I centered the items.

I addressed the changes you suggested and fixed the E2E tests. Could you take another look at this PR?

2024-09-27 02:17 UTC, kmanijak approved these changes
Thanks for addressing all of the comments, LGTM! Amazing work @octaedro! 🚀

2024-09-27 03:04 UTC, merged