Blocks: Add missing `wp-block-woocommerce-{name}` to Add to Cart with Options, Product Image, Product Rating, Product Rating Stars, Product Rating Counter and Product Image
woocommerce/woocommerce pull request #51558
Opened 2024-09-19 21:20 UTC by thealexandrelara

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Part of #49739 .

This PR adds the missing `wp-block-woocommerce-{name}` to the following blocks:

- Product Image
- Product Rating
- Product Rating Stars
- Product Rating Counter
- Add to Cart with Options

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Visit the shop page (/shop) and click on a product.
2. After being redirected to the Single Product page, make sure the Product Image, Add to Cart with Options, Product Rating, Product Rating Counter and Product Ratings Stars blocks are being rendered correctly.
3. Inspect each block and make sure you can see the `wp-block-woocommerce-{block-name}` attached to the class property of the HTML tag. (`{block_name}` is the name of the block, for instance for Product Rating, it is `product-rating`). 

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
Add missing `wp-block-woocommerce-{name}` class to Add to Cart with Options, Product Image, Product Rating, Product Rating Stars, Product Rating Counter and Product Image blocks.
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-09-23 13:15 UTC, louwie17 requested changes
Thanks for this @thealexandrelara, this overall tested well although I wasn't sure how to get the Product Rating Counter and the Product Rating Star blocks to display, they don't show up for me, only the **Product Rating** block seems to show up for me. The changes for those blocks look fine, but would like to also test it.
![Screenshot 2024-09-23 at 3 13 30 PM](https://github.com/user-attachments/assets/a1a204c7-267f-46e3-9d4a-586930413e2f)

I also noticed the removal of one of the classes in the add to cart form, removing it may be fine, but just wanted to call it out. Also suggesting to use a `filter` for with a `implode` to concatenate the classes together to avoid unnecessary whitespaces.

2024-09-23 13:15 UTC, louwie17 commented on plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php
> -			'<div class="wp-block-add-to-cart-form wc-block-add-to-cart-form %1$s %2$s %3$s" style="%4$s">%5$s</div>',
`wp-block-add-to-cart-form` was there a specific reason for removing `wp-block-add-to-cart-form` and only keeping the `wc-block-add-to-cart-form`?

2024-09-23 13:15 UTC, louwie17 commented on plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php
> +				'class' => 'wc-block-add-to-cart-form ' . esc_attr( $classes_and_styles['classes'] ) . ' ' . esc_attr( $classname ) . ' ' . esc_attr( $product_classname ),
I think we can remove this one `esc_attr( $classname )`, as it already gets included as part of `esc_attr( $classes_and_styles['classes'] )`. At-least when I tested it and and added a custom class name in the site editor.

2024-09-23 13:15 UTC, louwie17 commented on plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php
> +				'class' => 'wc-block-add-to-cart-form ' . esc_attr( $classes_and_styles['classes'] ) . ' ' . esc_attr( $classname ) . ' ' . esc_attr( $product_classname ),
Would it also make sense to use `array_filter` here as some of these classes can actually be empty causing a bunch of spaces: `wc-block-add-to-cart-form    wp-block-woocommerce-add-to-cart-form` 
While it doesn't break anything, it looks a bit odd when inspecting the html.
We use `array_filter` for several of the other block types within `get_block_wrapper_attributes`

2024-09-27 16:07 UTC, thealexandrelara commented on plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php
> +				'class' => 'wc-block-add-to-cart-form ' . esc_attr( $classes_and_styles['classes'] ) . ' ' . esc_attr( $classname ) . ' ' . esc_attr( $product_classname ),
Nice catch! I removed the `esc_attr( $classname )` and used the  `array_filter` method there (38d31719bac91bd2b0a967b551feaea2552beffa).

2024-09-27 16:10 UTC, thealexandrelara commented on plugins/woocommerce/src/Blocks/BlockTypes/AddToCartForm.php
> -			'<div class="wp-block-add-to-cart-form wc-block-add-to-cart-form %1$s %2$s %3$s" style="%4$s">%5$s</div>',
Now that you mentioned, I just added it back (38d31719bac91bd2b0a967b551feaea2552beffa). I initially thought it was redundant but I just realized it does not contain the `woocommerce` namespace (`wp-block-add-to-cart-form !== wp-block-woocommerce-add-to-cart-form`).

2024-09-27 19:23 UTC, thealexandrelara commented
Thank you for reviewing the PR, @louwie17!

>  I wasn't sure how to get the Product Rating Counter and the Product Rating Star blocks to display, they don't show up for me, only the Product Rating block seems to show up for me.

Yeah, I believe those blocks cannot be directly added to the template. One way to test them is to add them manually. 

1. Go to a template/post/page;
2. Add the Single Product block. 
3. Switch to the "Code Editor" mode (in MacOS: Shift + Option + CMD + M);
4. Add the following within the Single Product block:

```
<!-- wp:woocommerce/product-rating-counter {"isDescendentOfSingleProductBlock":true} /-->

<!-- wp:woocommerce/product-rating-stars {"isDescendentOfSingleProductBlock":true} /-->
```

5. Save and check the changes on the frontend.

>  I also noticed the removal of one of the classes in the add to cart form, removing it may be fine, but just wanted to call it out. Also suggesting to use a filter for with a implode to concatenate the classes together to avoid unnecessary whitespace.

Nice catch! I replied to your comment on the code and also changed the code to include the `implode` + `array_filter` methods.

Could you review the PR again?

2024-09-30 13:00 UTC, louwie17 approved these changes
Thanks for the updates @thealexandrelara and for adding the extra test instructions around the product rating blocks.
It would be worth updating the PR description as well to include those instructions for when this gets tested by QA.

Approving this though, code looks good and it tested well 💯

2024-09-30 15:41 UTC, merged

2024-10-03 14:06 UTC, gigitux commented
I think that this PR introduced this regression: https://github.com/woocommerce/woocommerce/issues/51883

The point is that `get_block_wrapper_attributes` already generates all the necessary CSS classes and styles starting from attributes. This means that we should not pass to `get_block_wrapper_attributes` classed and styles generated with `StyleAttributesUtils`. Tomorrow I will work on a fix.

2024-10-03 17:30 UTC, thealexandrelara commented
> I think that this PR introduced this regression: #51883
> 
> The point is that `get_block_wrapper_attributes` already generates all the necessary CSS classes and styles starting from attributes. This means that we should not pass to `get_block_wrapper_attributes` classed and styles generated with `StyleAttributesUtils`. Tomorrow I will work on a fix.

Ohh, TIL! Good to know that this removes the need for the StyleAttributesUtils.