refactor: WooPayments onboarding components
woocommerce/woocommerce pull request #51572
Opened 2024-09-20 08:42 UTC by frosso

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2026-06-13 06:54 UTC, dmallory42 requested changes
Thanks for the refactor! The local WooCommerce admin runtime path looks good because admin consumes `@woocommerce/onboarding` through the `wc-source` export and webpack handles `.svg` assets.

   I did notice one package-build concern though. `@woocommerce/onboarding` still advertises a CommonJS entry:

   ```json
   "require": "./build/index.js"
 ```

 After this PR, the CJS build leaves raw SVG requires in the emitted JS, e.g.

 ```js
   require("../../images/cards/visa.svg")
 ```

 Plain Node/CommonJS/Jest consumers can’t load that without custom SVG loader config. I confirmed with:

 ```bash
   pnpm --filter @woocommerce/onboarding build:publish:project:cjs
   node -e "require('./packages/js/onboarding/build/components/WooPaymentsMethodsLogos')"
 ```

 which fails with:

 ```text
   SyntaxError: Unexpected token '<'
 ```

 because Node tries to parse the SVG file as JS.

 If @woocommerce/onboarding is only intended to be consumed in WooCommerce admin’s webpack/source context, that may be fine for the current product path. But I think we should avoid shipping an advertised CJS entry that no longer works for this component.

 Possible ways forward:

 1. Teach @woocommerce/internal-build to turn SVG imports into JS-safe URL/string modules for both ESM and CJS package builds.
 2. Move these logos to public WooCommerce plugin assets and use URL strings, similar to the Blocks payment-icon pattern.
 3. If CommonJS/built-package consumption is not supported for this package, remove/close the CJS require export path so we don’t imply compatibility there.

 Given the current use case, option 3 might be the smallest fix, while 1 or 2 would make SVG asset usage more generally supported.

2026-06-15 12:17 UTC, frosso commented
Thank you @dmallory42 - good point! I went ahead with your third suggestion (since it's just faster and more pragmatic), dropping the CJS build (also removing the `main`/`cjs`build step) and making the package ESM only.

2026-06-16 15:05 UTC, dmallory42 approved these changes
Thanks for the update — the CJS concern I raised looks addressed now that the `require` export and CJS build script are removed. Looks good now!

   Two minor package-cleanup thoughts:

   - `@woocommerce/onboarding` is now effectively bundler-only for the built package entry, since the ESM build still contains raw `.svg` imports copied alongside `build-module`. If that’s intentional, it may be worth documenting or adding a small package-build smoke test so we don’t imply plain Node ESM compatibility. (I personally don't think this package is intended for consumption outside WooCommerce internal usage, so we could make that explicit).
   - `files` still includes `build`, but the PR removes the CJS build that produced that directory. Removing `"build"` would make the manifest match the current outputs (`build-module`, `build-style`, `build-types`).

But those cleanups are optional, this PR LGTM.

2026-06-16 15:24 UTC, frosso commented
Good feedback @dmallory42 , I addressed it in the latest commit :) thanks again for taking the time to review!

2026-06-16 16:17 UTC, merged