#50557 - Order summary Shipping updates
woocommerce/woocommerce pull request #51608
Opened 2024-09-23 06:03 UTC by samueljseay

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-09-25 08:46 UTC, samueljseay commented on plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/totals/footer-item/style.scss
> +		font-weight: bold;
This is to retain the font weight being bold within the footer.

2024-09-25 13:04 UTC, samueljseay commented
Something is up with the changelog CI action, but otherwise I think this is ready for review.

2024-09-26 18:18 UTC, opr requested changes
Thanks Sam, this is looking pretty good! While testing with Subscriptions I noticed an issue which I raised here: https://github.com/woocommerce/woocommerce-subscriptions/issues/4728

I also noticed an issue in Storefront, the text is larger than the row title and other values, could we fix that please?

<img src="https://github.com/user-attachments/assets/29601f5f-3986-46dc-8ef4-fd2443ee3183" width="450" />

According to [the design](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic%5D-Cart-%26-Checkout-Blocks?node-id=463-6541&node-type=frame&t=fiQT9tjgNOYZZr9g-0), the text on the right should be slightly lighter than the title however in Tove, TT4, and Storefront (not an exhaustive list, they're just the ones I tested) it's not. Was this a decision made on purpose because of themes with different colour palettes?

Besides those issues, it's working well in in Firefox, Safari, and Edge.

2024-09-27 03:43 UTC, samueljseay commented
> According to [the design](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic%5D-Cart-%26-Checkout-Blocks?node-id=463-6541&node-type=frame&t=fiQT9tjgNOYZZr9g-0), the text on the right should be slightly lighter than the title however in Tove, TT4, and Storefront (not an exhaustive list, they're just the ones I tested) it's not. Was this a decision made on purpose because of themes with different colour palettes?

Yeah I opted not to add it because we don't have a good way to support a dark pallette out of the box. I do realize that this could be contentious, but I didn't like the change because this area already looks ok with a dark pallette ootb, and at least it's readable, but going to a dark pallette would immediately make this piece of text unreadable. The user can switch to dark mode setting to fix this, so I'm ok to introduce the lighter color if you agree, but also @senadir mentioned removing the one low-emphasis text color we have so I wondered, what should this color be set to?

2024-09-27 05:53 UTC, samueljseay commented
> I also noticed an issue in Storefront, the text is larger than the row title and other values, could we fix that please?
@opr thanks for checking this. I approached the font size completely wrong. I have updated it to use the em based mixin, but note that we don't have an exactly `80%` size (0.8em of the basis), so I've set it to the `0.875` size, because `0.75` felt too small.

2024-09-27 05:54 UTC, samueljseay commented
I've requested re-review, but please let me know how you're feeling about the color. I'm open to changing it, and it was really just my personal idea to make it not look worse with dark pallettes.

2024-09-27 08:00 UTC, opr approved these changes
Thanks for your explanations Sam, I am fine with using 0.875 and your reasoning behind the colour makes sense. Happy to approve, also tagging @nikkivias here to check she's OK with us taking the initiative on this. Nikki if you'd like us to change/update anything let us know and we can iterate on it in a follow up.

2024-09-30 04:53 UTC, merged