Give the "Change address" in classic cart the `role="button"`
woocommerce/woocommerce pull request #51960
Opened 2024-10-08 16:18 UTC by waclawjacek

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51896.

This PR solves an issue with the accessibility of the "Change address" link on the classic cart page.

The issue is that the link functions as a button so it should either be a `<button>` HTML element (which is preferred) or have the attribute `role="button"` and handle both Enter and spacebar key presses.

I opted for the second approach not to disrupt existing themes that might rely on the current styling of the link in the classic cart, especially since the default experience is now the cart block.

The cart block already uses role="button" and handles spacebar key presses so no change was needed there.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add some products to your cart.
1. Ensure your cart page is displaying the classic cart.
2. Using the Tab key, focus the "Change address" link.
3. Press spacebar. Notice it opens the form to change the address but does not scroll the page down.
4. Press spacebar again. The form should hide.
5. Press another key that isn't spacebar or Enter. The native browser behavior should happen (so possibly nothing should happen if you press a letter key).

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

Fix - Accessibility: Give "Change address" link in classic cart `role="button"`

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-10-09 14:59 UTC, mikejolley requested changes
Changes look and test good, thank you! There is just one extra change needed to increase the template version of shipping-calculator.php.

Cheers

2024-10-09 14:59 UTC, mikejolley commented on plugins/woocommerce/templates/cart/shipping-calculator.php
> +	<?php printf( '<a href="#" role="button" class="shipping-calculator-button">%s</a>', esc_html( ! empty( $button_text ) ? $button_text : __( 'Calculate shipping', 'woocommerce' ) ) ); ?>
Since this is a template change we should bump the version so merchants are aware of the change if they have overridden the file.

```
@version 7.0.1
```

This should be updated to the version of WooCommerce this is targetting.

2024-10-09 16:03 UTC, waclawjacek commented on plugins/woocommerce/templates/cart/shipping-calculator.php
> +	<?php printf( '<a href="#" role="button" class="shipping-calculator-button">%s</a>', esc_html( ! empty( $button_text ) ? $button_text : __( 'Calculate shipping', 'woocommerce' ) ) ); ?>
Thanks! I set it to 9.4.1 because the upcoming 9.4.0 is in code freeze. Is that the right thing to do?

2024-11-05 13:55 UTC, kloon commented on plugins/woocommerce/templates/cart/shipping-calculator.php
> +	<?php printf( '<a href="#" role="button" class="shipping-calculator-button">%s</a>', esc_html( ! empty( $button_text ) ? $button_text : __( 'Calculate shipping', 'woocommerce' ) ) ); ?>
Should we bump this to 9.5.0 as the next release, @waclawjacek?

2026-08-06 09:21 UTC, ralucaStan commented
I'll close this PR as there have been no progress on it, and https://github.com/woocommerce/woocommerce/pull/67137 will provide a complete fix for the issue.

2026-08-06 09:21 UTC, closed without merging