Fix accessibility name for individual product checkboxes in the grouped product page
woocommerce/woocommerce pull request #51964
Opened 2024-10-08 21:34 UTC by elazzabi

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #51928

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add 2/3 products, mark the type as "Single Product" and make sure to check "Limit purchases to 1 item per order" found in the `Inventory` tab
2. Create a new product, mark the type as "Grouped Product" and add the products created in Step 1 from the `Linked Products` tab.
3. Visit the product page, checkboxes should show for each linked product:

<img width="1211" alt="Screenshot 2024-10-08 at 16 30 38" src="https://github.com/user-attachments/assets/2e5e1700-3655-45ee-a9bd-ebe00602782d">

4. Inspect the checkbox and look for a label with the "screen-reader-text" class name:

```
<label for="quantity-12" class="screen-reader-text">Buy one of Yellow Can for €19</label>
```

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [x] Minor
-   [ ] Major

#### Type

-   [x] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

Fix accessibility name for individual product checkboxes in the grouped product page

</details>

2025-02-12 14:13 UTC, vikrampm1 commented
@woocommerce/woo-fse just checking on this PR to see if you are able to review/merge it. Please note that this is not from our team, but I wanted to check and see if we can mark it as closed from our end.

2025-02-12 17:59 UTC, kmanijak requested changes, later dismissed
Hey @elazzabi!

Thanks for your contribution, really sorry for a delay with reviewing it! 😅

Great job overall. There' couple of stuff we need to address before merging the PR though:

- there's couple of PHP lint errors that requires fixing:
```
. lint:changes:branch:php: FILE: plugins/woocommerce/templates/single-product/add-to-cart/grouped.php
. lint:changes:branch:php: -----------------------------------------------------------------------------------------------
. lint:changes:branch:php: FOUND 6 ERRORS AND 0 WARNINGS AFFECTING 6 LINES
. lint:changes:branch:php: -----------------------------------------------------------------------------------------------
. lint:changes:branch:php:  67 | ERROR | Whitespace found at end of line (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
. lint:changes:branch:php:  69 | ERROR | A function call to esc_html__() with texts containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the placeholders. (WordPress.WP.I18n.MissingTranslatorsComment)
. lint:changes:branch:php:  70 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$grouped_product_child'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
. lint:changes:branch:php:  71 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'get_woocommerce_currency_symbol'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
. lint:changes:branch:php:  72 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$grouped_product_child'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
. lint:changes:branch:php:  73 | ERROR | Whitespace found at end of line (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
. lint:changes:branch:php: -----------------------------------------------------------------------------------------------
```

- also, the template requires version bump in [here](https://github.com/woocommerce/woocommerce/pull/51964/files#diff-28f58995a9e8e683b463eb8f6b2cac6fec8e856e353c353f66086a4e49180c14R15). We'll be aiming `9.7.0` so please bump to this version

- I also left some comment about currency formatting.

Let me know if that's clear! I'm happy to help with addressing those if needed. 🙌

2025-02-12 17:59 UTC, kmanijak commented on plugins/woocommerce/templates/single-product/add-to-cart/grouped.php
> +										$grouped_product_child->get_price()
This combination works only for some currencies. What about using `$grouped_product_child->get_price_html()` which does all the stuff to format the price properly and then running `wp_strip_all_tags` on that?

2025-02-13 17:07 UTC, elazzabi commented on plugins/woocommerce/templates/single-product/add-to-cart/grouped.php
> +										$grouped_product_child->get_price()
Thanks for the tip!

2025-02-13 17:08 UTC, elazzabi commented
Hey @kmanijak, thank you for the review! Sorry I forgot about this PR and left it in a non-ready format, I fixed everything now and it should be good for a review.

Let me know if I missed something 🙌

2025-02-14 11:49 UTC, kmanijak reviewed
Looks good! I allowed myself to merge `trunk` into the branch as there's one unrelated failing test. I guess it may be fixed on `trunk`.

Also, there's duplicated changelog file, for some reason automation picked up and created a second file. Let's remove it and PR is ready to go!

2025-02-14 11:49 UTC, kmanijak commented on plugins/woocommerce/changelog/51964-fix-accessible-form-field
> +Fix accessibility name for individual product checkboxes in the grouped product page
Weird, automation added another changelog file: https://github.com/woocommerce/woocommerce/pull/51964/commits/523f7f84f704331029f6e23adebdd9d1952a7e37.

Let's remove one.

2025-02-14 14:10 UTC, kmanijak commented
Failing test is flaky and unrelated to this PR. There are attempts to fix it https://github.com/woocommerce/woocommerce/pull/55445

2025-02-17 09:11 UTC, elazzabi commented
@kmanijak removed the extra changelog and tests are passing 🕺 let me know if this looks good to go!

2025-02-17 12:10 UTC, WunderBart requested changes
Thanks for addressing the feedback so far, @elazzabi!

It looks good for provided testing instructions, although I've found one issue when grouping items on sale.

2025-02-17 12:10 UTC, WunderBart commented on plugins/woocommerce/templates/single-product/add-to-cart/grouped.php
> +										esc_html( wp_strip_all_tags( $grouped_product_child->get_price_html() ) )
When a product is `on sale` the regular+sale price info text appears concatenated which might be confusing:

<img width="623" alt="Screenshot 2025-02-17 at 13 01 51" src="https://github.com/user-attachments/assets/9ed62e02-caf9-4e9d-a72d-70eb3af8802b" />

Can we make sure this is formatted nicely?

2025-02-18 09:01 UTC, elazzabi commented on plugins/woocommerce/templates/single-product/add-to-cart/grouped.php
> +										esc_html( wp_strip_all_tags( $grouped_product_child->get_price_html() ) )
Great catch! I changed the output to catch on sale and regular prices in [ca5730d](https://github.com/woocommerce/woocommerce/pull/51964/commits/ca5730d8282d4142237299beccff7a477b368d72).

2025-02-18 11:24 UTC, WunderBart commented on plugins/woocommerce/templates/single-product/add-to-cart/grouped.php
> +										esc_html( wp_strip_all_tags( $grouped_product_child->get_price_html() ) )
Looks great, thanks!

<img width="1046" alt="Screenshot 2025-02-18 at 12 23 02" src="https://github.com/user-attachments/assets/e513928b-97e5-42a6-9a92-d6f708299d56" />

2025-02-18 12:19 UTC, WunderBart commented on plugins/woocommerce/templates/single-product/add-to-cart/grouped.php
> +								'</label>';
Do you think it would make sense to separate the translations so that translators can be more precise? For example:

```suggestion
								echo '<label for="' . esc_attr( 'quantity-' . $grouped_product_child->get_id() ) . '" class="screen-reader-text">';
								if ( $grouped_product_child->is_on_sale() ) {
									printf(
										/* translators: %1$s: Product name. %2$s: Sale price. %3$s: Regular price */
										esc_html__( 'Buy one of %1$s on sale for %2$s, original price was %3$s', 'woocommerce' ),
										esc_html( $grouped_product_child->get_name() ),
										esc_html( wp_strip_all_tags( wc_price( $grouped_product_child->get_price() ) ) ),
										esc_html( wp_strip_all_tags( wc_price( $grouped_product_child->get_regular_price() ) ) )
									);
								} else {
									printf(
										/* translators: %1$s: Product name. %2$s: Product price */
										esc_html__( 'Buy one of %1$s for %2$s', 'woocommerce' ),
										esc_html( $grouped_product_child->get_name() ),
										esc_html( wp_strip_all_tags( wc_price( $grouped_product_child->get_price() ) ) )
									);
								}
								echo '</label>';

```

2025-02-18 12:45 UTC, elazzabi commented on plugins/woocommerce/templates/single-product/add-to-cart/grouped.php
> +								'</label>';
@WunderBart yesss, I think that's better! Thank you 🙇

2025-02-18 12:53 UTC, WunderBart approved these changes
Looks good, thanks! 🚀

2025-02-18 13:22 UTC, merged