fix: $email missing for woocommerce_email_header action
woocommerce/woocommerce pull request #51980
Opened 2024-10-09 12:32 UTC by morvy

$email was declared in all do_action hooks for woocommerce_email_header but couldn't be used.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [x] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-12-07 00:12 UTC, coreymckrill commented
Hey @morvy thanks for the PR, and sorry for the delay in responding.

I have a concern here, which is that most of the email templates where `do_action( 'woocommerce_email_header', $email_heading, $email );` appears are overridable, like [this one](https://github.com/woocommerce/woocommerce/blob/3eff0f27cbcf29ff9ad225f9037d2baedf92f863/plugins/woocommerce/templates/emails/admin-cancelled-order.php#L5-L15), meaning that it's possible, although not super likely, that someone has created a custom template where they did something like this:

```php
do_action( 'woocommerce_email_header', $email_heading );
```

...because they knew the callback was only expecting one parameter. In such a case, this change would cause a fatal error from WordPress because we're changing the `add_action` call to require two parameters.

I'm trying to think of a way we could work around this, while still adding in the missing parameter. Let me know if you have any ideas.

2024-12-10 00:31 UTC, coreymckrill requested changes
Hi @morvy, chatted about this a bit with my team, and I think my suggestion (below) should alleviate concerns about back compatibility.

The other thing this PR needs is some testing instructions. Could you add some step-by-step instructions about how to test the change?

2024-12-10 00:31 UTC, coreymckrill commented on plugins/woocommerce/includes/class-wc-emails.php
> +	public function email_header( $email_heading, $email ) {
```suggestion
	public function email_header( $email_heading, $email = null ) {
```

Making the new parameter optional should prevent any compatibility issues with custom templates.

2024-12-10 08:36 UTC, morvy commented
@coreymckrill Hi, yes I understand the template holding the action is overridable, but if that's the only reason to override, it should be also possible to just use a simple action. Adding `null` as default value will definitely prevent errors, but $email parameter was there since I remember, so since Woo 3.0.0 at least. People tend to override those by copying over the original, so I believe it really won't happen.

Use case for this parameter, which I couldn't use and created this PR was to add custom block depending on the shipping method and payment method. I belive there are many other use cases :)

2026-08-15 12:34 UTC, nerrad commented
There isn't sufficient rationale presented on the PR for implementing this change and the backward compatibility concern still remains.

2026-08-15 12:34 UTC, closed without merging