Fix product count display on mini cart first render
woocommerce/woocommerce pull request #52124
Opened 2024-10-17 18:55 UTC by opr

### Changes proposed in this Pull Request:

Updates the PHP render of the Mini-Cart block so that the setting for displaying the product count is reflected on first render. In the block settings the count can be shown: always (`always`), never (`never`), or if cart is not empty (`greater_than_zero`).

The bug manifests because the initial HTML for the block is written to the page as plain HTML and hydrated only when the user interacts with the mini cart, this led to an incorrect state being shown where the setting was not respected.

In the case that the attribute is set to `never`, or `greater_than_zero` and product count is 0, the HTML for the badge will not be output in PHP.

If `always` or `greater_than_zero` and product count is >0 the HTML for the badge _will_ be output in PHP.

Also, PHP Unit tests have been added

Closes #52114

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Add the Mini-Cart block to your site (or find it in the site editor, usually in the header)
2. Select the Mini-Cart block in the editor and go to the `Show Cart Item Count:` setting
3. Set this to `Never`.
4. Ensure the preview on the editor updates, and the badge is hidden.
5. Load the block on the front end and ensure there is no count badge on the Mini-Cart block. Test this with an item in the cart, and no items in the cart. Ensure the badge never shows.
6. Go back to the Mini-Cart block in the editor and go to the `Show Cart Item Count:` setting
7. Set this to `Always (Even if empty)`.
8. Ensure the preview on the editor updates, and the badge is shown.
9. Load the block on the front end and ensure there is a count badge on the Mini-Cart block. Test this with an item in the cart, and no items in the cart. It should show 0 when the cart is empty, and the number of products when it is not. Ensure the number updates as you add/remove items from your cart.
10. Go back to the Mini-Cart block in the editor and go to the `Show Cart Item Count:` setting
11. Set this to `Only if cart has items`.
12. Ensure the preview on the editor updates, and the badge is shown.
13. Load the block on the front end and empty your cart. Ensure there is no count badge on the Mini-Cart block.
14. Add an item to your cart and ensure the count is shown.
15. Remove the item from your cart and ensure the count is no longer shown.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-10-19 09:12 UTC, alexflorisca requested changes
Nice work, this tests well, code looks good mostly, I think you just missed changing some of the logic in the test

2024-10-19 09:12 UTC, alexflorisca commented on plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCart.php
> +		$block  = parse_blocks( '<!-- wp:woocommerce/mini-cart {"productCountVisibility":"always"} /-->' );
```suggestion
		$block  = parse_blocks( '<!-- wp:woocommerce/mini-cart {"productCountVisibility":"never"} /-->' );
```

2024-10-19 09:12 UTC, alexflorisca commented on plugins/woocommerce/tests/php/src/Blocks/BlockTypes/MiniCart.php
> +		$this->assertStringContainsString( '<span class="wc-block-mini-cart__badge"', $output );
```suggestion
		$this->assertStringNotContainsString( '<span class="wc-block-mini-cart__badge"', $output );
```

2024-10-21 11:04 UTC, opr commented
> Nice work, this tests well, code looks good mostly, I think you just missed changing some of the logic in the test

Thanks, yeah I did 🙈

2024-10-22 11:31 UTC, alexflorisca approved these changes
All good now, thanks for making the changes. 👍

2024-10-23 14:50 UTC, merged

2024-10-24 05:42 UTC, samueljseay commented
I think this closes https://github.com/woocommerce/woocommerce/issues/50877 as well?

2024-10-29 21:31 UTC, opr commented
Yes, thanks Sam