Fix ExtendStore Task Not Marked as Completed Upon Navigating Back to Home
woocommerce/woocommerce pull request #52127
Opened 2024-10-17 23:38 UTC by chihsuan

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/49221

When users navigate to the Enhance your store with extensions task and return to the Home page via the Home link, the ExtendStore task is not marked as completed until the page is fully reloaded. The ExtendStore task should be marked as completed after the task is visited. This issue is causing a poor user experience, as the task status does not reflect the most current state.

This PR introduces a fix to ensure the task list status is always updated when navigating back to the Home page. By re-fetching the task list status on each return, we ensure that the task completion is correctly displayed without requiring a full page reload.

This approach could cause a slight re-fetching delay when returning to the Home page, but I think it is a trade-off to ensure the task list status is always up-to-date. This can avoid any bugs like the one reported in the issue due to the task list status not being updated, but also reduce the logic where we need to invalidate the task list cache when a task is completed.

I'm open to feedback on this approach. If having other ideas to solve this issue, please feel free to share.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create a fresh site
2. Navigate to `WooCommerce > Home.`
3. Click on the `Enhance your store with extensions` task and complete it.
4. Click the Home link to return to the Home page.
5. Confirm that the ExtendStore task is now marked as completed without requiring a page reload.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-10-18 03:05 UTC, ilyasfoo requested changes
@chihsuan  This is causing loop on activity panel sidebar when opening it twice:

https://github.com/user-attachments/assets/6beeb84a-1194-4b8e-a861-dd762ccd0843

2024-10-18 03:07 UTC, ilyasfoo commented
I think the approach is not the most ideal since sidebar panel is accessible from non-homescreen pages. I wonder if it's viable to invalidate tasklist completion when a task is navigated to? 🤔

2024-10-18 03:33 UTC, chihsuan commented
> I think the approach is not the most ideal since sidebar panel is accessible from non-homescreen pages. I wonder if it's viable to invalidate tasklist completion when a task is navigated to? 🤔

Thanks for the feedback! Yeah, we could invalidate the task list completion when a task is navigated to. That would be a better approach. I'll update the PR with this change.

2024-10-18 04:00 UTC, chihsuan commented
@ilyasfoo Updated in 72f136d425d8333116cc641b955ce5ca0c03d4e5. 🙏

2024-10-18 06:17 UTC, ilyasfoo approved these changes
Nice, this is working well! LGTM 🚢

2024-10-20 00:31 UTC, moon0326 approved these changes
LGTM and tested well 👍 🚀

2024-10-20 23:41 UTC, merged