[Experimental] Attribute Filter: Respect Show Empty settings
woocommerce/woocommerce pull request #52208
Opened 2024-10-22 09:38 UTC by dinhtungdu

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR fixes the issue of the Attribute Filter block that doesn't show empty options when the corresponding setting is enabled.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

0. Ensure the experimental blocks are enabled:
    - If you use the WooCommerce Beta Tester plugin, you can enable the experimental blocks in Tools > WCA Test Helper > Features. Toggle the `experimental-blocks` option.
    - If you build this PR locally, build the branch with `pnpm --filter='@woocommerce/plugin-woocommerce' watch:build` command to have experimental blocks available.
1. Add a new attribute term without assigning any product to it.
2. Add the Product Filters block to the Product Catalog template.
4. Select the Attribute block, and change it to the matching attribute that has the term added in step 1.
5. Enable Styles > Empty filter options.
6. See the term added in step 1 appear.
7. Enable Product Counts.
8. See the count of new term shows zero.
9. Save and see the same option on the front end.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-10-28 20:26 UTC, roykho requested changes
I am seeing a JS error in the frontend

![file.png](https://github.com/user-attachments/assets/1bc93905-e5d7-4a2e-ac26-d0120e3c89c3)

2024-10-29 02:47 UTC, dinhtungdu commented
@roykho I rebased the branch onto `trunk` and didn't get any warning. Can you take another look at this?

2024-10-29 19:08 UTC, roykho approved these changes
Working as expected and approving however I don't see what the point is to have this filter option. What would be the benefit of showing an attribute that has no products linked to it?

2024-10-30 05:41 UTC, dinhtungdu commented
> What would be the benefit of showing an attribute that has no products linked to it?

It informs users that the product they're looking for is out of stock or unavailable. For example, if I want a blue T-shirt, showing `Blue (0)` tells me that the store does provide one, but it's out of stock at the moment. @j111q can share more insights here after she comes back from AFK.

2024-10-30 05:41 UTC, merged