Migrate setup script into monorepo
woocommerce/woocommerce pull request #52318
Opened 2024-10-24 22:24 UTC by lanej0

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Moves a setup script used when creating e2e test environments from a different repository to within the monorepo.

Closes # [WCQuality 926](https://github.com/woocommerce/woocommerce-quality/issues/926)

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Nothing to test

2024-10-28 19:56 UTC, adimoldovan commented
Thanks for working on this @lanej0.
- We should also update the paths to the plugins to install to point to the ones in the monorepo instead of `https://github.com/rodelgc/woo-e2e-site-setup/raw/trunk/mu-plugins/...`.
- We should probably include woocommerce-cleanup.php as well.
- Ideally we'll have a single script, for both local and external environments setup. I don't see a good reason to maintain two scripts, they doing the same thing.

2024-10-28 19:57 UTC, adimoldovan requested changes
Thanks for working on this @lanej0.

- We should also update the paths to the plugins to install to point to the ones in the monorepo instead of https://github.com/rodelgc/woo-e2e-site-setup/raw/trunk/mu-plugins/....
- We should probably include woocommerce-cleanup.php as well.
- Ideally we'll have a single script, for both local and external environments setup. I don't see a good reason to maintain two scripts, they doing the same thing.

2024-11-01 18:57 UTC, lanej0 commented
Made the updates.

It was slightly more complicated because wp cli will only install a .zip file and the plugins in the monorepo were all just php files.  So I had to create zips and commit those to the repo so that we have somewhere to install from.

2024-11-04 14:04 UTC, adimoldovan commented
> Made the updates.
> 
> It was slightly more complicated because wp cli will only install a .zip file and the plugins in the monorepo were all just php files. So I had to create zips and commit those to the repo so that we have somewhere to install from.

Instead of storing zip files in the repo we can download the plugins and zip them in the install script. The `zip` utility should be available and if not, it's a simple command to install.

```
curl -o filter-setter.php https://github.com/woocommerce/woocommerce/raw/trunk/plugins/woocommerce/tests/e2e-pw/bin/filter-setter.php
zip filter-setter.zip filter-setter.php
wp plugin install --force --activate filter-setter.zip
rm filter-setter.php filter-setter.zip
```

2024-11-04 19:13 UTC, lanej0 commented
> > Made the updates.
> > It was slightly more complicated because wp cli will only install a .zip file and the plugins in the monorepo were all just php files. So I had to create zips and commit those to the repo so that we have somewhere to install from.
> 
> Instead of storing zip files in the repo we can download the plugins and zip them in the install script. The `zip` utility should be available and if not, it's a simple command to install.
> 
> ```
> curl -o filter-setter.php https://github.com/woocommerce/woocommerce/raw/trunk/plugins/woocommerce/tests/e2e-pw/bin/filter-setter.php
> zip filter-setter.zip filter-setter.php
> wp plugin install --force --activate filter-setter.zip
> rm filter-setter.php filter-setter.zip
> ```

Yes!  I like this approach much better.  I was trying to envision some kind of GH action/workflow that would do the zip and then delete the files... but storage was stumping me.  Doing this part locally makes a lot of sense.

2024-11-05 14:27 UTC, adimoldovan commented on plugins/woocommerce/tests/e2e-pw/bin/test-env-setup-external.sh
> +    # rm "$plugin.php" "${plugin%}.zip"
Forgot it commented out?

2024-11-05 14:27 UTC, adimoldovan commented on plugins/woocommerce/tests/e2e-pw/bin/wp-cache-flush.php
> +<?php
I checked the setup guide that recommended adding the `wp_cache_flush();` snippet and it looks like the issue it was helping with was fixed in the meantime.
I don't think we need this and it should not be added.

2024-11-06 21:21 UTC, lanej0 commented on plugins/woocommerce/tests/e2e-pw/bin/test-env-setup-external.sh
> +    # rm "$plugin.php" "${plugin%}.zip"
Yup, was debugging.

2024-11-08 11:03 UTC, adimoldovan approved these changes

2024-11-08 11:03 UTC, merged