Update broken links
woocommerce/woocommerce pull request #52495
Opened 2024-10-31 16:30 UTC by emmanuel-ferdman

### Description
Commit a16f11ad6ee01389bdb68ee499b85c676e283d36 moved bunch of files. This PR adjusts sources to changes.

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-10-31 21:52 UTC, lanej0 commented on docs/extension-development/handling-merchant-onboarding.md
>  For a complete example of adding a custom task as a WordPress plugin, you can check out the [add-task examples directory](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce-adm
Think you missed one here!

2024-10-31 21:54 UTC, lanej0 requested changes
Looks good.  Just one missed link that I noticed in the review.

2024-10-31 21:59 UTC, emmanuel-ferdman commented
@lanej0 thanks for the review, I fixed it

2024-10-31 22:11 UTC, lanej0 commented
Looks good!  I kicked off the checks and it looks like there was just one failure in the Markdown linting (it may even be un-related to your changes, but if you wouldn't mind taking a look/fixing it along with this PR, that would be great).  Also just need a changelog entry with this.  If you could run `pnpm --filter='@woocommerce/plugin-woocommerce' changelog add` and fill in the details, we should be able to get this merged!  Thanks for your contribution.

2024-10-31 22:56 UTC, lanej0 approved these changes

2024-11-01 14:48 UTC, emmanuel-ferdman commented
@lanej0 fixed the markdown errors and added the changelog entry

2024-11-01 19:02 UTC, lanej0 commented
I'm really sorry, it's been a while since I did docs updates and there's one more step.  Can you run `pnpm utils md-docs create docs woocommerce -o docs/docs-manifest.json` and commit the file that's changed.  That will update the manifest and get the lint check passing.

2024-11-04 21:11 UTC, emmanuel-ferdman commented
@lanej0 added, please merge

2024-11-04 21:59 UTC, merged