[Experimental] Add alignment controls
woocommerce/woocommerce pull request #52598
Opened 2024-11-06 01:57 UTC by roykho

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/woocommerce/issues/51787

This PR adds additional styling to the active filter block per design.

- Added Orientation to the toolbar and inspector controls
- Added Dimensions, Typography and Border controls

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

> [!NOTE]  
> **Pre-requisite**
> - If you're using WC Beta Tester plugin, make sure the `experimental-blocks` feature is enabled (Tools > WCA Test Helper > Features).
> - Make sure to reset Product Catalog Template.

1. Navigate to Product Catalog template (Appearance > Editor > Templates > Product Catalog template.
2. Edit the template.
3. With the block inserter, add Product Filters (Experimental) block to the template.
4. Open the Document Overview (List view) and ensure you see the Product Filter Active block in the new design structure.
5. Select the parent Active Filters block
6. Ensure you see the Orientation (Vertical, Horizontal) settings in the toolbar.
7. Go to the Inspector Controls -> Settings Panel and ensure you also see the Orientation settings there.
8. Try toggling vertical and horizontal settings and watch it change in the editor. Save and view it in the frontend. It should reflect the same as your saved settings.
9. Also play around with the Dimensions, Typography and Border settings. They should reflect in the editor and in the frontend after saving.
10. The clear button setting has already been tested in prior PR https://github.com/woocommerce/woocommerce/pull/52268

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 
Adds additional styling settings to active filter block
</details>

2024-11-06 04:32 UTC, dinhtungdu reviewed
Thanks for working on this. The typo, margin, padding, and border controls are working as expected in my test. But others didn't seem to work probably:

- Justification: this seems to have no effect when I changed the option.
- Orientation: this changes the Orientation of the chips, but I'm not sure it's the correct behavior. The setting belongs to the Active block, changing the orientation should affect the direction of its inner blocks as Row block does.
- Block spacing: this also seems to have no effect.

https://github.com/user-attachments/assets/dde59270-edea-4c02-9599-27734d17f188

2024-11-06 04:42 UTC, roykho commented
> Justification: this seems to have no effect when I changed the option.

It is working on my end. Also note it only has affect in vertical. I am not sure how it would look or if it even should function for horizontal.
![file.png](https://github.com/user-attachments/assets/3fb4e7af-9cea-4e08-ab2d-a411bd59056b)

> Orientation: this changes the Orientation of the chips, but I'm not sure it's the correct behavior. The setting belongs to the Active block, changing the orientation should affect the direction of its inner blocks as Row block does.

I purposely did it this way so that the clear button remains at the bottom per design. Do you think we should make all/any inner blocks change with the orientation settings?

> Block spacing: this also seems to have no effect.

Will look into this one.

2024-11-06 04:49 UTC, roykho commented
> Block spacing: this also seems to have no effect.

I think block spacing is actually not needed here right? Because block spacing only works if you have blocks inline?

2024-11-06 05:17 UTC, dinhtungdu commented
> Because block spacing only works if you have blocks inline?

I believe not only inline. It's the spacing between inner blocks, like Row and Group blocks are doing.

> I think block spacing is actually not needed here right?

I actually agree. We can add it later if needed. 

> > Orientation: this changes the Orientation of the chips, but I'm not sure it's the correct behavior. The setting belongs to the Active block, changing the orientation should affect the direction of its inner blocks as Row block does.
>
> I purposely did it this way so that the clear button remains at the bottom per design. Do you think we should make all/any inner blocks change with the orientation settings?

What I worry about is: it's possible to add inner blocks to the Active block, so even if no one is doing so, we still need to support that case. I think the orientation setting is better moved to Removable Chips instead. I don't see the need to place inner blocks of Active in a row.

2024-11-06 05:18 UTC, dinhtungdu commented
As you mentioned, it's easier to add more features but the opposite is not.

2024-11-07 22:14 UTC, thealexandrelara requested changes
Great work! Thank you for working on this. Code looks good! I noticed an issue with the vertical orientation when combined with Centered Justification. Also, could you please add some tests covering these new settings?

✅ Scenario 1: Merchants can modify the Dimensions
- Conditions:
    - A merchant edits the Product Catalog template.
    - The merchant adds the Product Filters (Experimental) block.
    - The merchant selects the Product Filters (Experimental) block.
    - The merchant modifies the Padding, Margin, Border, and Border Radius in the Inspector Controls.
- Expected Outcome: The changes are reflected in the editor and on the frontend.
- Summary: Scenario passed as expected. No issues found.

⚠️  Scenario 2: Merchants can modify the Dimensions
- Conditions:
    - A merchant edits the Product Catalog template.
    - The merchant adds the Product Filters (Experimental) block.
    - The merchant selects the Active Filters block.
    - The merchant modifies the Justification and Orientation in the Inspector Controls.
- Expected Outcome: The changes are reflected in the editor and on the frontend.
- Summary: When setting the Justification to Center and the Orientation to Vertical, the result differs between the editor and the frontend.

| Editor | Frontend |
|--------|--------|
| ![CleanShot 2024-11-07 at 19 08 24@2x](https://github.com/user-attachments/assets/1ada4325-7cd1-4c9a-9698-1a051bb0e597) | ![CleanShot 2024-11-07 at 19 09 42@2x](https://github.com/user-attachments/assets/de6fb4fa-8ed0-44d4-98f4-46f31a425de0) | 

- Another thing I noticed is that when a border has a large border radius and the justification is set to Left or Right, the items get cut off. Although merchants can address this issue by adjusting the padding, it is important to highlight this point:

![CleanShot 2024-11-07 at 19 10 19@2x](https://github.com/user-attachments/assets/7032b333-b961-4705-b9ae-c820cdf83235)

2024-11-07 22:38 UTC, roykho commented
@thealexandrelara Thanks for the review.

> When setting the Justification to Center and the Orientation to Vertical, the result differs between the editor and the frontend.

This is what I see in the editor and frontend.

Editor:
![file.png](https://github.com/user-attachments/assets/243a0db5-ec9e-42cc-ab02-1bf9251b63c7)

Frontend:
![file.png](https://github.com/user-attachments/assets/f3f0e1cc-5951-4f9e-bb3d-871e3976579a)

> Another thing I noticed is that when a border has a large border radius and the justification is set to Left or Right, the items get cut off. Although merchants can address this issue by adjusting the padding, it is important to highlight this point:

I believe that's just how GB behaves. You can replicate this with core blocks by adding a group and several inner blocks.
![file.png](https://github.com/user-attachments/assets/b6bb73dc-01ae-47d7-b0a5-f1f8d1517d37)

> Also, could you please add some tests covering these new settings?

I am not sure if we should do that as these styling settings are not a critical flow and would only further slow our CIs down.

2024-11-08 20:18 UTC, thealexandrelara commented
This is interesting, I created a new JN site to ensure it's not a cache problem, and for me this issue is still happening . When I access the page containing the Filters block for the first time and select some filter options, the issue occurs. However, the issue does not happen if I select some filter options and reload the page, or if I open a URL that contains filter query parameters that pre-populate the Active Filters block. Here is a video showing this behavior:

https://github.com/user-attachments/assets/4087dec8-7a8d-4600-a076-c93b8359c4eb

> I believe that's just how GB behaves. You can replicate this with core blocks by adding a group and several inner blocks. 

I see, so yeah, that's something I believe we cannot control. The good thing is that merchants can see that in the Editor, so they can make their own adjustments.

> I am not sure if we should do that as these styling settings are not a critical flow and would only further slow our CIs down. I think only functional items we should add tests for. For example the clear button. If clear button doesn't work on click, that is a significant issue. We should only write tests for those.

TBH, I don’t think we should limit our testing just because CI might slow down. This is a separate issue that would require different solutions. Tests are essential for ensuring reliability and preventing regressions. Even if we lose some extra seconds during the process, IMO it is worth it to prevent a bug from reaching production, which would then require debugging, fixing, reviewing, coordinating a patch release, etc., and take significantly longer.

I’m not suggesting visual testing, but at a minimum, we should ensure that these settings are there and can be modified.

2024-11-09 15:59 UTC, roykho commented
Thanks for the review @thealexandrelara 

I've added basic test to ensure both layout settings exists and clicking on each of them produces the correct css class names to the container. Though I am still not convince we need to add these tests. Mainly because these are GB core functionality. If we were to add custom settings, yeah I would agree we should add tests. But any how it's there now.

> I created a new JN site to ensure it's not a cache problem, and for me this issue is still happening

Yeah I was finally able to reproduce this. I am not entirely sure what the fix would be. My hunch is because the chips are added dynamically, the width is not fully calculated at the time and causes this issue. When you refresh, it works is because the chips are already know (in the URL params) and there knows the calculated width. But again this is just my speculation. I will dig in further to see how this can be remedied but if you have any suggestions, it would be great.

2024-11-09 22:36 UTC, roykho commented
Note: There is a failing e2e tests (the ones added in this PR) ref https://github.com/woocommerce/woocommerce/actions/runs/11759348403/job/32758726253?pr=52598#step:9:253

I am not sure what is causing this error but the tests passes locally.

2024-11-11 20:19 UTC, thealexandrelara approved these changes
Thank you for working on this! I ran another round of tests, and everything is working as expected. Amazing work, Roy! 🚀 

✅ Scenario 1: Merchants can modify the Dimensions
- Conditions:
    - A merchant edits the Product Catalog template.
    - The merchant adds the Product Filters (Experimental) block.
    - The merchant selects the Product Filters (Experimental) block.
    - The merchant modifies the Padding, Margin, Border, and Border Radius in the Inspector Controls.
- Expected Outcome: The changes are reflected in the editor and on the frontend.
- Summary: Scenario passed as expected. No issues found.

✅   Scenario 2: Merchants can modify the Dimensions
- Conditions:
    - A merchant edits the Product Catalog template.
    - The merchant adds the Product Filters (Experimental) block.
    - The merchant selects the Active Filters block.
    - The merchant modifies the Justification and Orientation in the Inspector Controls.
- Expected Outcome: The changes are reflected in the editor and on the frontend.
- Summary: Scenario passed as expected. No issues found.

2024-11-11 20:19 UTC, thealexandrelara commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductFilterRemovableChips.php
> +			'data-wc-key'         => wp_unique_prefixed_id( $this->get_full_block_name() ),
TIL. Oh, this is great; I've never used it.

2024-11-11 21:44 UTC, merged