Fix product SKU styles
woocommerce/woocommerce pull request #52787
Opened 2024-11-13 18:36 UTC by octaedro

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This PR modifies some `Product SKU` styles.

Before

![Screenshot 2024-11-14 at 3 24 18 PM](https://github.com/user-attachments/assets/8439210f-971d-42c3-aa19-c61aeb7fb333)

After

![Screenshot 2024-11-14 at 3 17 41 PM](https://github.com/user-attachments/assets/5d3f6175-b5c0-40cf-9436-b47d9f614919)

Closes #52396.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go to Editor > Single Product template
2. Reset customizations if you've applied any changes
3. Verify Product SKU looks good

![Screenshot 2024-11-14 at 3 20 47 PM](https://github.com/user-attachments/assets/b9df7a28-91a1-44b1-80a7-0fbc094717bb)

After selecting it the `Suffix` should be visible.

![Screenshot 2024-11-14 at 3 17 41 PM](https://github.com/user-attachments/assets/5d3f6175-b5c0-40cf-9436-b47d9f614919)

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-11-14 18:14 UTC, octaedro commented on plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/sku/block.tsx
> +			placeholder={ ' ' + __( 'Suffix', 'woocommerce' ) }
I added the space here to follow the same pattern that [GB is using](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-terms/edit.js#L149).

2024-11-15 12:43 UTC, kmanijak requested changes
Thanks for taking care of it and kudos for adding `i18n`!

I tested the changes and I see some differences between SKU vs Categories/Tags on TT5 theme, SKU is thin, the others are strong:

Place | Screenshot
-- | --
Editor | <img width="577" alt="image" src="https://github.com/user-attachments/assets/23ac8031-926c-4cde-be7a-64c05bb3755b">
Frontend | <img width="832" alt="image" src="https://github.com/user-attachments/assets/74226dda-7b39-4a17-94bf-14f3140e1027">

Also, on TT5 on the frontend the SKU value is "bolder" (font-weight: 700) compared to categories/tags value (font-weight: 600). It's subtle but it caught my attention:

Place | Screenshot
-- | --
Current (font-weight: 700) | <img width="769" alt="image" src="https://github.com/user-attachments/assets/ae20275b-9772-4bed-90b6-d66b9ed2cc1f">
Changed manually to (font-weight: 600) | <img width="788" alt="image" src="https://github.com/user-attachments/assets/15268e54-fb24-4b1d-9875-a8dcf419cf19">

2024-11-15 13:48 UTC, octaedro commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductSKU.php
> +			'<div class="wc-block-components-product-sku wc-block-grid__product-sku wp-block-woocommerce-product-sku product_meta wp-block-post-terms %1$s" style="%2$s">
To ensure this element mimics the styles of `Category` and `Tags` no matter the theme, I applied to the SKU the class `wp-block-post-terms`.
Same with [prefix](https://github.com/woocommerce/woocommerce/pull/52787/files#diff-df15f52ea37c48bc26b7c89c44cae66ef305373ec59313074fe6819c7eab8d6bR74) and [suffix](https://github.com/woocommerce/woocommerce/pull/52787/files#diff-df15f52ea37c48bc26b7c89c44cae66ef305373ec59313074fe6819c7eab8d6bR79).

2024-11-15 13:51 UTC, octaedro commented
Thank you for your feedback, @kmanijak.
I just fixed the problem you mentioned. Could you take another look at this PR?

2024-11-15 15:10 UTC, kmanijak commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductSKU.php
> +			'<div class="wc-block-components-product-sku wc-block-grid__product-sku wp-block-woocommerce-product-sku product_meta wp-block-post-terms %1$s" style="%2$s">
I think that's the right approach! It looks nice in frontend:

<img width="373" alt="image" src="https://github.com/user-attachments/assets/9a5ccaa8-cc7a-4ee9-940f-bd20592b9c20">

but I think we should apply the same classes in Editor (screenshot with TT5):

<img width="366" alt="image" src="https://github.com/user-attachments/assets/9857b161-e39c-49ed-b64b-ff88d7c5489e">

2024-11-15 19:07 UTC, octaedro commented on plugins/woocommerce/src/Blocks/BlockTypes/ProductSKU.php
> +			'<div class="wc-block-components-product-sku wc-block-grid__product-sku wp-block-woocommerce-product-sku product_meta wp-block-post-terms %1$s" style="%2$s">
@kmanijak Done in the commit [c8f4943](https://github.com/woocommerce/woocommerce/pull/52787/commits/c8f494306fa5c9bf82ebfb5b77573b776465e72b)

2024-11-18 07:59 UTC, kmanijak approved these changes
I left one last comment. I testes TT5, TT4, TT3 and TT2 with the two marked lines removed and in all of them SKU looks aligned with Categories and Tags. So I'm recommending removing those lines.

Thanks for your patience, pre-approving! 😄

2024-11-18 07:59 UTC, kmanijak commented on plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/sku/style.scss
>  	@include font-size(small);
I tested TT5, TT4, TT3 and TT2. On TT2 the size differs.

<img width="523" alt="image" src="https://github.com/user-attachments/assets/6b002f0d-6466-4735-bc43-98af42447808">

With the current `wp-block-post-terms` class this line is no longer needed as theme takes care of the size (but due to specificity this line takes precedence over theme styles and small font-size is applied).

2024-11-18 07:59 UTC, kmanijak commented on plugins/woocommerce-blocks/assets/js/atomic/blocks/product-elements/sku/style.scss
> +	font-size: var(--wp--preset--font-size--small);
With the current `wp-block-post-terms` class this line is no longer needed as theme takes care of the size. 🤔

2024-11-18 15:29 UTC, merged