Fix grouped product styles for TT5
woocommerce/woocommerce pull request #52856
Opened 2024-11-15 00:28 UTC by octaedro

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #52700.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-11-20 08:33 UTC, louwie17 requested changes
Thanks for this @octaedro, this tested well!
I do think we should add the theme specific CSS somewhere else, as it looks like we already have some logic in place on how we handled this with previous themes.

I left a detailed comment with an example of the twenty twenty three theme.

2024-11-20 08:33 UTC, louwie17 commented on plugins/woocommerce/client/legacy/css/woocommerce.scss
> +body.theme-twentytwentyfive {
I don't think we should add the `twentytwentyfive` specific CSS to the general `woocommerce.scss` file.

It looks like that we usually create a new `scss` file for the theme specifically and only enqueue that style when that theme is active.
See the example of twenty twenty three:
css file: https://github.com/woocommerce/woocommerce/blob/c5faf64bfab9a87e24b10ba805a1090741a40537/plugins/woocommerce/client/legacy/css/twenty-twenty-three.scss#L1
PHP file to enqueue the style: https://github.com/woocommerce/woocommerce/blob/0f204dbb575fed81d9a0ed8befc0e83a5b992cfa/plugins/woocommerce/includes/theme-support/class-wc-twenty-twenty-three.php#L27
Case statement for only including the above PHP file when the specific theme is active: https://github.com/woocommerce/woocommerce/blob/f107670192f02eb6d4a36181f067f413ec1a8ea1/plugins/woocommerce/includes/class-woocommerce.php#L796

2024-11-26 20:05 UTC, octaedro commented
Thank you, @louwie17, for your review!
Taking into account our discussion in this thread (p1732281119914949-slack-C02FL3X7KR6), I’ve added the commit 662546b and made some adjustments to the testing instructions.

2024-11-26 20:14 UTC, octaedro commented on plugins/woocommerce-blocks/assets/js/blocks/product-elements/add-to-cart-form/style.scss
> +			word-break: normal;
This will prevent every text under the grouped product form from being shown oddly.

2024-11-27 13:10 UTC, louwie17 approved these changes
Nice work @octaedro, I like how simple the change end up being now!
This tested well and changes look good 👍 💯

2024-11-27 13:57 UTC, merged