WIP Add checkout step logging
woocommerce/woocommerce pull request #53230
Opened 2024-11-27 01:56 UTC by wavvves

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2025-01-01 14:37 UTC, senadir reviewed
Submitting comments that already were here. Do ping me when this is ready for another review

2025-01-01 14:37 UTC, senadir commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +
I suggest you just go inside process_without_payment and process_payment and do the same as shortcode.

2025-01-01 14:37 UTC, senadir commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #7] Created and/or persisted customer data from order', array( 'order_id' => $this->order->get_id() ) );
Do we want to go inside those functions and trigger from there?

2025-01-01 14:37 UTC, senadir commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #1] Place Order flow initiated' );
Regarding numbers, can it be kept as a static var at the logger level so in case we started moving inside functions, we don't need to keep count in our heads? Or do we want to keep it static like this to validate if it's firing at the right time?

2025-01-10 17:56 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #1] Place Order flow initiated' );
Thought that initially, but wanted to keep track of what I was happening. A bit clunky I know, but makes it easier to spot if any step was missed or ran in an unexpected sequence.
Also I wanted to follow the flow branchout, eg [Shortcode #6A]

2025-01-10 18:00 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #7] Created and/or persisted customer data from order', array( 'order_id' => $this->order->get_id() ) );
Don't steal my questions, I also would like to know this from the review 😂 
In case those error out, even inside a try catch at least we would know where to look. Imagine getting a bunch of dropped orders at step 6, we would these had problems with processing customers.
Problem is, some of these methods might branch out to much to be easy to spot problems.

2025-01-10 18:01 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +
I'll open the PR up for review, tag some more eyes, and then will look into these 👍🏼

2025-01-10 18:03 UTC, wavvves commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +function wc_log_order_step( string $message, ?array $context = null, bool $final_step = false ) {
@senadir do we want to put this behind a toggle/flag for debugging? No right? I bet that most of the issues might be invisible to merchants, if shoppers are able to do the order again successfully or go buy somewhere else.

2025-01-10 18:07 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #1] Place Order flow initiated' );
what we can do is make this a bit more elegant, supplying source (shortcode/api, not to be confused with logger's context source), and step as args along with the message, and let the method prettify the output

2025-01-10 18:54 UTC, wavvves commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +		$logger = new WC_Logger( null, WC_Log_Levels::DEBUG );
Do we want to force the file logger handler here? So that merchants can submit files if requested.

If database is selected on settings, or any other custom handler is defined it might get clunky to copy and paste stuff, and sort by order.

You can test this by selecting database here `/wp-admin/admin.php?page=wc-status&tab=logs&view=settings`

2025-01-10 19:00 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #5] Created/Updated draft order', array( 'order_id' => $this->order->get_id() ) );
Do we wanna log order details? We can't log everything due to PII, but only the id is actually useless unless we request details. 

We need to take special care when logging, anything can potentially provide data we can't legally obtain.

2025-01-10 19:38 UTC, wavvves commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +		$logger->clear( $context['source'] );
This kinda pollutes the File logger by logging this to wc-logger file:
```
2025-01-10T19:31:36+00:00 Info 1 log file from source <code>place-order-debug-756c90a7</code> was deleted. 
```

If we allow different handlers, then we're stuck here. If we force the file logger handler we may extend it and override this, but that's a complexity I'd like to avoid.

2025-01-13 16:39 UTC, opr reviewed
I added some comments, the testing steps you provided work OK for me.

In its current state, I think this is useful, but it could be improved a lot, see my comments about logging more deeply. We also need to ensure these steps are documented somewhere so a merchant or HE looking at the logs knows where along in the process it failed.

For now I won't approve as I want to hear your thoughts on deeper logging and if it's something we _don't_ want to do right now I can come back and give it a more thorough test.

2025-01-13 16:39 UTC, opr commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +function wc_log_order_step( string $message, ?array $context = null, bool $final_step = false ) {
> behind a toggle/flag for debugging

Can you clarify what you mean here? Do you mean only declaring the function if some flag is set? I don't think that's a good idea, it just adds more friction to logging these issues.

2025-01-13 16:39 UTC, opr commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +		$logger = new WC_Logger( null, WC_Log_Levels::DEBUG );
By force, do you mean force enable it to be file logging, or disable logging unless it's set to file logging?

In my opinion, we should be agnostic to what logging solution the site is using, if the database logging is harder to read, then that is a tradeoff the merchant should be willing to accept (also database logging isn't recommended in prod).

2025-01-13 16:39 UTC, opr commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +		$logger->clear( $context['source'] );
> If we allow different handlers, then we're stuck here.

Can you clarify what you mean by this? Why are we stuck? Can't we just check if it's callable?

Did you consider updating `LogHandlerFileV2`'s `clear` method to accept a second parameter `quiet` which defaults to `false` which when set would skip logging the clear. As far as I see, `clear` isn't on the interface, it's something added specifically to `LogHandlerFileV2` right?

2025-01-13 16:39 UTC, opr commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #1] Place Order flow initiated' );
We need to document these steps somewhere then, similar to what we have on https://developer.woocommerce.com/docs/cart-and-checkout-checkout-flow-and-events/ and https://developer.woocommerce.com/docs/cart-and-checkout-how-the-checkout-block-processes-an-order/

2025-01-13 16:39 UTC, opr commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #5] Created/Updated draft order', array( 'order_id' => $this->order->get_id() ) );
Presumably logging the items in the cart and quantities is OK? I think we should do this at every step tbh in case that helps with debugging an issue, for example if a product with a bad configuration is causing problems. Can we also log non-PII such as country, state, selected shipping methods?

2025-01-13 16:39 UTC, opr commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #7] Created and/or persisted customer data from order', array( 'order_id' => $this->order->get_id() ) );
I think we should go as in depth as we can with logging:

> some of these methods might branch out to much to be easy to spot problems

In my opinion, we should log as deeply as we can before we get into internal WP code. For example in `process_customer` we can log inside `should_create_customer_account` too, logging in each of the if statements _may_ be useful at some point. 

Right now this is useful, but it could be a lot more useful the more deeply we go. The amount of logging is also not a factor as it's deleted on successful orders, so it's not like we're going to fill up people's storage unnecessarily.

2025-01-13 16:39 UTC, opr commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +
Agree with Nadir. See my previous comment about going deeper.

2025-01-13 16:46 UTC, wavvves commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +function wc_log_order_step( string $message, ?array $context = null, bool $final_step = false ) {
>Do you mean only declaring the function
Preferably the best possible solution (returning early could be an option). 
Anyway doesn't matter, the question here was between this logging being an opt-in or not. For me it's not a question anymore, we're trying to catch unknown problems here, probably not even reported. We should ship it, wait, see. 👍🏼

2025-01-13 16:49 UTC, wavvves commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +		$logger = new WC_Logger( null, WC_Log_Levels::DEBUG );
Yeah, those are the 2 default options, but any handler can be injected to the Logger instance. 
Maybe this is not pertinent right now, or maybe ever. Marking this as resolved, and putting the effort on logging the correct steps from the get go 👍🏼

2025-01-13 16:52 UTC, wavvves commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +		$logger->clear( $context['source'] );
Nice catch, I didn't notice `clear` wasn't enforced. I'll do that 👍🏼

2025-01-15 17:04 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #5] Created/Updated draft order', array( 'order_id' => $this->order->get_id() ) );
Can cart items contain personalizations with sensitive data? Like printed t-shirts with my name and social security number 😅
Not sure about country/state. Shipping method should be the same as cart, can we say for sure its not extended in a way that we don't see more than we can?

2025-01-15 17:19 UTC, wavvves commented on plugins/woocommerce/includes/wc-order-step-logger-functions.php
> +		$logger->clear( $context['source'] );
Done. Had to change the class WC_Logger since indirect call is routing through there.

2025-01-16 12:35 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #5] Created/Updated draft order', array( 'order_id' => $this->order->get_id() ) );
@opr as soon as we get an Order object, what would be the data in your opinion that we should log?
I'm hesitant because we need to be 100% confident before releasing this.

2025-01-16 13:44 UTC, opr commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #5] Created/Updated draft order', array( 'order_id' => $this->order->get_id() ) );
> Can cart items contain personalizations with sensitive data? Like printed t-shirts with my name and social security number 😅

I would suggest skipping those then if we're not confident, maybe we could add a filter to enable their logging if the merchant is sure there is no issue with it.

> Not sure about country/state

Me neither, I recommend reaching out to the legal team to find out.

> what would be the data in your opinion that we should log?

Order ID, products (minus any data we're not confident about), country, state (pending legal confirmation) payment method used, shipping method selected. What do you think?

> I'm hesitant because we need to be 100% confident before releasing this.

Hesitant about what exactly? If you have doubts then I think the legal team are the only ones who can really clear this up.

2025-01-16 14:59 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #7] Created and/or persisted customer data from order', array( 'order_id' => $this->order->get_id() ) );
Tried to do it, but we have a problem. These methods maybe called from somewhere else, if we log inside, we won't be able to clear the log in the end. This can result in several false positives, and pollute our logs. The only way I can think of, is on the first call pass an argument opening the flow. If that is false skip. Wdyt?

2025-01-16 15:33 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +
Just went inside those. They seem pretty robust yet with thrown errors, apart from that, it's only setters, not much can go wrong there. I think there won't be a silent error there, if we see logs dropping off just before it we may go deeper in a second iteration.

2025-01-16 15:38 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +
At least for Store API. I also added backtrace and a last error entry.

2025-01-16 15:41 UTC, opr commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #7] Created and/or persisted customer data from order', array( 'order_id' => $this->order->get_id() ) );
Like setting a flag somewhere that an order is being placed, and only log if that's set? That could work?

2025-01-16 15:55 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #1] Place Order flow initiated' );
I'll update those entries once we get a fixed set of logs. I'm also stopping tweaks on logging messages and step counter until I get the full picture.

2025-01-16 16:06 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #5] Created/Updated draft order', array( 'order_id' => $this->order->get_id() ) );
With the Order id we can ask for further details with the merchant.
Hesitant about going too loose on data and catch some sensitive things.

2025-01-16 16:08 UTC, wavvves commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #7] Created and/or persisted customer data from order', array( 'order_id' => $this->order->get_id() ) );
I've commited a solution https://github.com/woocommerce/woocommerce/pull/53230/commits/8fab6928acc64b59e441af44576cd7fc153e1eea . An arg on the first call sets an active logging session. Any call without an active logging session will be disregarded.

2025-01-17 15:01 UTC, opr commented on plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php
> +		wc_log_order_step( '[Store API #5] Created/Updated draft order', array( 'order_id' => $this->order->get_id() ) );
OK, I still think you should ask the legal folks about this. The ideal outcome is the merchant has to do as little work as possible to help us debug it, so knowing the limits of what we can log will be useful.

2025-01-17 16:58 UTC, opr requested changes
Thanks for working on this again Paulo!

Could we improve the testing steps so it includes some steps for blocks flow too? Perhaps a couple of different flows to test logs stopping at certain steps?

This is working for me and logging the steps correctly, as well as removing the log when the order is successful. I am still of the opinion that we should log as much info as we can (another recommendation/push for you to collaborate with the legal team to define what this is) rather than being cautious and limiting what we log. In my opinion, it feels a little wasteful to merge this PR _without_ this collaboration and then spin another one up later. With that said, I don't want my opinion on this to block us merging something that's actually working, so feel free to bring this up to the team and see what the consensus is, if we agree as a team releasing with the current level of logging is fine I will come back and approve.

2025-01-17 16:58 UTC, opr requested changes
Thanks for working on this again Paulo!

Could we improve the testing steps so it includes some steps for blocks flow too? Perhaps a couple of different flows to test logs stopping at certain steps?

This is working for me and logging the steps correctly, as well as removing the log when the order is successful. I am still of the opinion that we should log as much info as we can (another recommendation/push for you to collaborate with the legal team to define what this is) rather than being cautious and limiting what we log. In my opinion, it feels a little wasteful to merge this PR _without_ this collaboration and then spin another one up later. With that said, I don't want my opinion on this to block us merging something that's actually working, so feel free to bring this up to the team and see what the consensus is, if we agree as a team releasing with the current level of logging is fine I will come back and approve.

2025-01-28 16:03 UTC, wavvves commented
Temporarily blocking this waiting for feedback on permitted logged data.

2025-01-30 13:45 UTC, wavvves commented
>We need to document these steps somewhere then, similar to what we have on https://developer.woocommerce.com/docs/cart-and-checkout-checkout-flow-and-events/ and https://developer.woocommerce.com/docs/cart-and-checkout-how-the-checkout-block-processes-an-order/

This is something for internal use, and something we should use temporarily just to get a sample of "silent" fails. These logs get cleared if the order fails in a way we already expect in the code. I don't think it should be advertised.

>Presumably logging the items in the cart and quantities is OK? I think we should do this at every step tbh in case that helps with debugging an issue, for example if a product with a bad configuration is causing problems. Can we also log non-PII such as country, state, selected shipping methods?

I can log cart data, country, state and selected shipping method (already logging payment), but I recently added last error and backtrace. Any technical uncaught issue will be present there, and any misconfiguration will probably end there (accessing non-existent props/keys etc). Getting the data to try and replicate the order is not going to cut it since we're not going to be able to do it on a live website without paying, and if we need to get in touch with the merchant, then we can request the data we need.

@opr Apart from testing steps and putting in a bit more data in the logging, what else would be needed to unlock this?
It's a shot in the dark experiment, we're trying to probe for the unknown here.

2025-01-30 17:40 UTC, opr commented
> This is something for internal use, and something we should use temporarily just to get a sample of "silent" fails. These logs get cleared if the order fails in a way we already expect in the code. I don't think it should be advertised.

I still think it should be documented, not necessarily advertised but it can be stored in the internal developers folder, and it doesn't have to be in depth. Maybe just a list of steps, the associated line that will be logged, and a description of what that step does will be fine.

> I can log cart data, country, state and selected shipping method (already logging payment), but I recently added last error and backtrace. Any technical uncaught issue will be present there, and any misconfiguration will probably end there (accessing non-existent props/keys etc). Getting the data to try and replicate the order is not going to cut it since we're not going to be able to do it on a live website without paying, and if we need to get in touch with the merchant, then we can request the data we need.

Alright, has that been cleared with the legal team? I think we need to be careful here, especially if we are potentially going to ask for these logs from our customers.

> @opr Apart from testing steps and putting in a bit more data in the logging, what else would be needed to unlock this?
It's a shot in the dark experiment, we're trying to probe for the unknown here.

Yeah, I think this is fine then, I will review again later. I am pushing for more logging because, given the lead time on getting something into a release it makes sense to try to log as much as we legally can. Pushing something out "just to see" is fine but if we realise we missed something later then there's another release cycle or CFE to wait for which isn't great.

2025-02-05 16:26 UTC, wavvves commented
> it can be stored in the internal developers folder

👍🏼 

> Alright, has that been cleared with the legal team?

Still giving details and waiting for a response.

2025-03-10 09:26 UTC, senadir commented
Hey @wavvves! Pleas add me back to this PR once it's marked ready again :D

2025-03-13 16:48 UTC, wavvves commented
> Hey @wavvves! Pleas add me back to this PR once it's marked ready again :D

It's ready for another review 👍🏼 
It's not sending to Remote Logging as 1) it wouldn't pass rate limiting, 2) wouldn't send a single entry if it could.
For properly sending it there we would probably need a corn scanning for log files, and a tracking system to avoid sending them more than once.
How do I check allow tracking adoption? If this is residual, then it's probably not worth it.

2025-03-25 15:47 UTC, opr reviewed
Hi Paulo thanks for sticking with this.

When I placed the orders with the error snippets the checkout failed as expected, but the backtrace in the logs is not showing the actual error, is that expected? It shows:


```
{
    "order_id": 4352,
    "payment": "Credit / Debit Card",
    "order_uid": "dbba5e46-1245-45f4-9b8a-47a67af394ab",
    "store_url": "https://tomato.local",
    "last_error": {
        "type": 8192,
        "message": "Creation of dynamic property WooCommerce\Square\Gateway\Gift_Card::$placeholder_id is deprecated",
        "file": "/Users/thomas/code/tomato/app/public/wp-content/plugins/woocommerce-square/includes/Framework/PaymentGateway/Payment_Gateway.php",
        "line": 428
    },
    "backtrace": [
        {
            "file": "/Users/thomas/code/tomato/app/public/wp-content/plugins/woocommerce-monorepo/plugins/woocommerce/src/StoreApi/Utilities/CheckoutTrait.php",
            "line": 164,
            "function": "wc_log_order_step"
        },
        {
            "file": "/Users/thomas/code/tomato/app/public/wp-content/plugins/woocommerce-monorepo/plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php",
            "line": 456,
            "function": "update_order_from_request",
            "class": "Automattic\WooCommerce\StoreApi\Routes\V1\Checkout",
            "type": "->"
        },
        {
            "file": "/Users/thomas/code/tomato/app/public/wp-content/plugins/woocommerce-monorepo/plugins/woocommerce/src/StoreApi/Routes/V1/AbstractRoute.php",
            "line": 119,
            "function": "get_route_post_response",
            "class": "Automattic\WooCommerce\StoreApi\Routes\V1\Checkout",
            "type": "->"
        }
    ],
    "remote-logging": false
}
```

Here's a screen recording of me testing this:

https://www.loom.com/share/68b30060d0714837a5c080d3b3d5a796

If you go to 1:32 you'll notice that I'm using Square's saved payment method, and when the order is placed, for a brief moment an error shows:

<img width="277" alt="image" src="https://github.com/user-attachments/assets/4de1c789-fadd-4282-a99d-e20e68c704cb" />

I think this is an error with the way Square processes the payment/checkout, so I think it's not expected that this would be caught by the logger (especially since the order is placed successfully) so just highlighting it in case it comes up.

If you let me know about the stack trace, if it's **expected** that this unrelated notice shows then we can merge this, otherwise let's see if we can get the correct error to show.

2025-03-28 13:28 UTC, wavvves commented
>When I placed the orders with the error snippets the checkout failed as expected, but the backtrace in the logs is not showing the actual error, is that expected?

@opr Yes, the backtrace is a three-level deep trace for the logging call, so we could check the origin of the parent function call. This way, we can check if it's the normal checkout flow or something programmatically calling the checkout process functions.

The last error show anything bad happening before the code is halted. If the code is halted by an uncaught exception, that exception will appear on normal logs, but not this one. But if there is a timeout, this can provide hints for what probably went wrong along the way.

So data there is up to date with the last successful log. If the order doesn't come through to success or expected fail, and a log file is produced, we know that something went wrong in the code after the log, and before the next step.

The example snippets with dies mimic a timeout, but if you thrown an error there it won't get caught in the step logger.

2025-03-28 16:04 UTC, opr approved these changes
Ok Paulo, sounds good! Thanks for your patience on this, let's merge it 👏🏼

2025-04-01 14:34 UTC, merged