Add error when conditional tag is used too early
woocommerce/woocommerce pull request #53257
Opened 2024-11-27 20:30 UTC by kkmuffme

I added it to the ones from https://developer.woocommerce.com/docs/conditional-tags-in-woocommerce/ and any that made sense at first glance. If any is a false positive (= this conditional can be used before the wp hook), feel free to remove that from the PR and update the docs on https://developer.woocommerce.com/docs/conditional-tags-in-woocommerce/ please

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #53256

### How to test the changes in this Pull Request:

1. go to checkout
2. add to theme's functions.php

```
add_action( 'wp_loaded', function () {
    if ( is_checkout() ) {
        return;
    }
    
    wp_die( 'This is not the checkout page' );
}, 10, 0 );
```

3. refresh checkout page. It will die saying that this isn't the checkout page.
4. enable `WP_DEBUG` if you want to get the doing it wrong error message (and refresh the checkout page)

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [x] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 
report doing_it_wrong error when conditional tags are used too early
</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-12-09 09:37 UTC, Konamiman requested changes
Hi @kkmuffme, thanks for your contribution. What you suggest is a good idea but I'd like to suggest some changes:

1. Returning false from the method, while is theorically the proper thing to do, is risky for already existing code as it could break extensions that use these functions (and we don't want that to happen, even if they are using the functions incorrectly). So I suggest triggering the warning, but otherwise leaving the function to proceed.
2. The warning message should be translated using the `__` function, for consistency with the other existing warnings.
3. The warning message is always the same, only the function name changes. Could we extract the `wc_doing_it_wrong` call to an auxiliary method to avoid repetition? It could be for example a static method named `ConditionalTagBeforeWpAction(string $function_name)` in a `src/Internal/Warnings` class, then you call it as `Warnings::ConditionalTagBeforeWpAction(__FUNCTION__)`.

2024-12-17 13:41 UTC, kkmuffme commented
Thanks for the feedback.

>1. Returning false from the method, while is theorically the proper thing to do, is risky for already existing code as it could break extensions that use these functions (and we don't want that to happen, even if they are using the functions incorrectly). So I suggest triggering the warning, but otherwise leaving the function to proceed.

Technical reply:
If the docs and conditions are correct and these are the earliest hooks, then `return false;` won't make a difference - since if it's too early, it will already return false in all cases anyway - there's no change in functionality.
And in case it doesn't and this would indeed break a plugin, we know that that the docs are wrong and that specific filter can be used earlier and the code adjusted.

Additionally, not returning false, would cause redundant errors, since the functions often call another conditional tag themselves

Practical reply:
I removed the `return false;` - once any plugins that might encounter the doing it wrong, have changed/fixed their code, I'll add it back as a separate PR at some point in a couple versions.

>2. The warning message should be translated using the __ function, for consistency with the other existing warnings.

Done.

>3. The warning message is always the same, only the function name changes

I could, however that would change the stack trace of the reported errors. From a plugin developer POV this makes it worse, since one has to manually adjust the step filters in xdebug,... just for this one case. So I'd rather stick with how it is now.
The only thing I could do is to create a function that returns the error message, but I doubt this makes maintaing it any easier. Especially, if the error message for one of them changes in the future (in case it can be used on an earlier hook indeed), it would make it more complex.

---

Could you merge it before WC 9.6 so I don't have to update the versions for the doing it wrong again, thanks!

2026-07-14 23:20 UTC, kkoteen commented
@Konamiman Could you take a look at this PR and suggest next steps? Thanks!

2026-07-30 03:34 UTC, Konamiman commented
Hi @kkmuffme, sorry for having left this abandoned for so many time.

After a closer review it seems that these doing-it-wrongs would be problematic because they would fire during normal WooCommerce operation: WooCommerce core itself uses these functions before the corresponding hooks are fired, and this causes the functions to always return `false`, but this is the expected behavior. So instead we are going to update the documentation in https://github.com/woocommerce/woocommerce/pull/67143 to explicitly state when the functions are expected to be invoked from outside of WooCommerce (the PR description has details about the calling paths that would be problematic in core).

So many thanks for your contribution, but we're going to close this in favor of the documentation-only https://github.com/woocommerce/woocommerce/pull/67143.

2026-07-30 03:34 UTC, closed without merging