ISO Code update for Odisha state (India)
woocommerce/woocommerce pull request #53341
Opened 2024-12-02 01:23 UTC by sorensd

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

ISO Code change for Odisha state (India)

ISO Code update for Odisha state (India) https://en.wikipedia.org/wiki/ISO_3166-2:IN (23 November 2023)

### Changelog entry
Updated Odisha ISO Code - 23 November 2023

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ X ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ X ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>
ISO Code update for Odisha state (India) https://en.wikipedia.org/wiki/ISO_3166-2:IN (23 November 2023)
#### Comment 

</details>

2024-12-09 10:30 UTC, albarin requested changes

2024-12-09 10:30 UTC, albarin commented on packages/js/onboarding/changelog/53341-trunk
> +ISO Code update for Odisha state (India) https://en.wikipedia.org/wiki/ISO_3166-2:IN (23 November 2023)
@sorensd would you mind removing this changelog file? 🙏 somehow it got pushed but the correct one is the `plugins/woocommerce/changelog/53341-trunk`

2024-12-09 12:49 UTC, sorensd reviewed
This is done.

2024-12-09 23:03 UTC, sorensd reviewed
@albarin I am not very sure how the packages/js/onboarding/changelog/53341-trunk is getting created? I am stuck on a loop

2024-12-10 08:13 UTC, albarin commented
@sorensd Sorry about this, I just realized it's probably created automatically because there are changes to this file `packages/js/onboarding/src/utils/countries/test/utils/country-options.ts`, I think it's okay to leave it 🙏

2024-12-10 08:52 UTC, albarin approved these changes

2024-12-10 08:52 UTC, merged