Cache valid paths check to avoid duplicate queries
woocommerce/woocommerce pull request #53431
Opened 2024-12-04 07:01 UTC by unfulvio

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #49318 

### How to test the changes in this Pull Request:

I was able to replicate the issue from #49318 by using Amazon S3 Storage for WooCommerce (extension sold on the WC Marketplace) and noticing several duplicated queries, which this PR mitigates by caching them.

To replicate, set up some downloadable files using S3 Storage or use the steps from #49318, then compare with this PR

2024-12-08 07:33 UTC, unfulvio commented
@coreymckrill is this being looked at?

![image](https://github.com/user-attachments/assets/6e3c1c8c-0d1b-44d4-bcf2-f50dfa0ed94c)


the first column shows the number of duplicate queries

as you can see from this Query Monitor screenshot, as it's currently, WC will generate hundreds of duplicate queries for product with downloadables -- I believe this could be easily fixed by caching/memozing those queries result internally while in the same thread

2024-12-10 01:31 UTC, coreymckrill approved these changes, later dismissed
Thanks for the PR @unfulvio !

Followed the replication instructions in #49318 and saw the duplicated queries on trunk. They are not present with this branch.

Left two minor code style suggestions to appease the linter, which I will go ahead and commit.

2024-12-10 01:31 UTC, coreymckrill commented on plugins/woocommerce/src/Internal/ProductDownloads/ApprovedDirectories/Register.php
> +
```suggestion
			$this->valid_paths[ $download_url ] = false;

```
Removing extra line at the top...

2024-12-10 01:31 UTC, coreymckrill commented on plugins/woocommerce/src/Internal/ProductDownloads/ApprovedDirectories/Register.php
> +	private array $valid_paths = [];
```suggestion
	private array $valid_paths = array();
```
WPCS prefers longform array declaration.

2024-12-10 01:33 UTC, coreymckrill commented
Actually, looks like I can't commit the suggestions myself, probably because this PR branch is in an organization (`kestrelwp`).

2024-12-10 01:35 UTC, unfulvio commented
@coreymckrill thank you! I have updated the PR as advised

2024-12-10 01:35 UTC, coreymckrill commented on plugins/woocommerce/src/Internal/ProductDownloads/ApprovedDirectories/Register.php
> +	/** @var array<string, bool> cached valid paths */
```suggestion
	/**
	 * Cache for valid paths, to avoid making duplicate queries.
	 *
	 * @var bool[]
	 */
```

2024-12-10 01:36 UTC, unfulvio commented on plugins/woocommerce/src/Internal/ProductDownloads/ApprovedDirectories/Register.php
> +	 * @var bool[]
```suggestion
	 * @var array<string, bool>
```

2024-12-10 01:40 UTC, coreymckrill commented
@unfulvio One more thing: can you generate a changelog file for this?

`pnpm --filter=plugins/woocommerce run changelog add`

2024-12-10 01:52 UTC, unfulvio commented
@coreymckrill done

2024-12-10 18:49 UTC, coreymckrill commented
@unfulvio Sorry, I just noticed that this change is breaking two unit tests. Here's the output:

```
There were 2 failures:

1) WC_Abstract_Product_Test::test_fetching_of_approved_downloads
If a trusted download directory rule is disabled, corresponding product downloads will also be marked as disabled.
Failed asserting that true is false.

/var/www/html/wp-content/plugins/woocommerce/tests/php/includes/abstracts/class-wc-abstract-product-test.php:91

2) WC_Download_Handler_Tests::test_inactive_downloads_will_not_be_served
Failed asserting that false is true.

/var/www/html/wp-content/plugins/woocommerce/tests/php/includes/class-wc-download-handler-tests.php:126
```

You can run the relevant unit tests with the following:

```
cd plugins/woocommerce
pnpm env:start
pnpm run test:php:env --filter="WC_Abstract_Product_Test|WC_Download_Handler_Tests"
```

2024-12-10 18:51 UTC, coreymckrill requested changes
* Investigate breaking unit tests
* Update unit tests or change code

2024-12-11 12:11 UTC, unfulvio commented
@coreymckrill the issue as of why the tests fail is likely due to caching introduced in this PR because in the same thread the cache will return the same cached values, so in a way it's working as intended -- IMO it's acceptable that in the same thread the value persists in a real-use scenario; test classes should be refactored to account for that to reset the state or maybe add a method to purge the cache - I'll leave it up to you and your team how do you want to approach that, refactor tests or add purge method in the concrete class which can be called by the test or any other actor if necessary

2024-12-19 00:26 UTC, coreymckrill commented
@unfulvio I think your idea to add a method to clear the cache is a good one. Not just for passing unit tests, but for general robustness as well.

My suggestion would be:

* A new public method in the `Register` class called something like `clear_cache_path`
* Ensure that the method is called in all of the methods that enable or disable directories

2026-08-15 12:56 UTC, nerrad commented
It looks like this PR was attached to an issue that was marked as a duplicate of another one and that one has a PR that was merged which addresses this (see #61159).

2026-08-15 12:56 UTC, closed without merging