[Documentation] Add document describing Cart/Checkout data flow
woocommerce/woocommerce pull request #53512
Opened 2024-12-06 12:43 UTC by opr

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-12-06 16:08 UTC, opr commented
@brentmackinnon I tagged you here as dev advocacy to take a look at this document.

2024-12-06 17:19 UTC, alexflorisca requested changes
Nice work, I think this is really handy to have and will help third party dev (and us!) understand what's going on a bit better. I left a few suggestions and comments. I think a large part of this will have to be updated once the checkout `PUT` endpoint is in place (I'm working on it now). This will enable persisting order notes, payment methods and additional fields (and maybe extension data too - hadn't thought of that). We can update the docs at a later date though if and when it gets merged.

A few other thoughts:
- Could mention additional fields in here - address ones are persisted, others not (yet)
- I would try to be more direct when writing documentation, and avoid phrases like "it would be a good idea to...". Instead I would say "You need to...".  I would try to avoid vagueness in general (e.g. A few ways of doing thins, words like could, maybe, etc).

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +
Might be good to start by expanding a bit on what `data` is here and give some examples.

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +In the WooCommerce Cart and Checkout blocks, the server is the source of truth, and data should be persisted server side. Things like component state (e.g. the checkout order notes, or coupon form in
`component state` - this is quite vague, I'm not sure what you mean here? Local state in a react component? Data stores? Context? State is stored at many levels.

Also I'm working on a PR that will persist additional fields, order notes and selected payment methods. So actually we're heading in the opposite direction of persisting everything to the server - which makes sense as it's the source of truth.

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +All the data relating to a cart, customer, and order is stored on the server, either in the database or in the customer's session. When it is sent to the server, it is stored in [`@wordpress/data`](h
```suggestion
All the data relating to a cart, customer, and order is stored on the server, either in the database or in the customer's session. When it is sent to the client, it is stored in [`@wordpress/data`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/) data stores.
```

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +There are different ways to get your data from the server to the client on whether your it is static (e.g. an option from the WooCommerce settings dashboard) or if it is dynamic/might change during t
```suggestion
There are two ways to get your data from the server to the client, depending on wether it is static or  dynamic
```

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +If the data is static, i.e. it is not likely to change based on actions the shopper takes then a good way of getting this data to the client might be through the `AssetDataRegistry`.
```suggestion
Static data is not likely to change based on actions the shopper takes. For example, an option from the WooCommerce settings dashboard. A good way of getting this data to the client might be through the `AssetDataRegistry`.
```

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +If a duplicate key exists, it will not be overwritten. Using a unique identifier is important.
Maybe mention the format `namespace/value` in order to ensure uniqueness

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +To add data here, you'll need to extend the API response. The [Exposing your data in the Store API](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-d
```suggestion
To add data here, you'll need to extend the API response. See [Exposing your data in the Store API](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-add-data.md)
```

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +document outlines how to do this.
```suggestion
```

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +If data might change, e.g. based on a shopper's location or items in the cart, it is a good idea to add this to the cart API response. The cart response is sent on many routes during the shopper's jo
```suggestion
Dynamic data is data that is likely to change in response to the shopper's actions. For example, changing location, or items in the cart. In this case, you need to add this to the cart API response. The cart response is sent on many routes during the shopper's journey, and on almost every API response triggered by the Cart/Checkout blocks.
```

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +This is useful for things that don't require an immediate response from the server, for example if you've added a new block to the Checkout and it contains a form field that should be saved along wit
The `PUT` endpoint on checkout will likely make this easier, but we can update the docs at a later date

2024-12-06 17:19 UTC, alexflorisca commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +Modifying form fields while the shopper is interacting with them _could_ be a jarring experience.
If we mention this, do you think we should also say how to mitigate against it?

2024-12-09 12:23 UTC, opr commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +Modifying form fields while the shopper is interacting with them _could_ be a jarring experience.
Yeah, good idea. I added

> Instead of making these changes while the user is interacting with the form, consider making them while processing the checkout action on the server.

Thanks

2024-12-09 12:40 UTC, opr commented on docs/cart-and-checkout-blocks/overview-of-data-flow.md
> +In the WooCommerce Cart and Checkout blocks, the server is the source of truth, and data should be persisted server side. Things like component state (e.g. the checkout order notes, or coupon form in
> Also I'm working on a PR that will persist additional fields, order notes and selected payment methods. So actually we're heading in the opposite direction of persisting everything to the server - which makes sense as it's the source of truth.

Great! I think my point is still OK here though, selected payment method could be considered important to persist.

2024-12-10 13:02 UTC, opr commented
@alexflorisca thanks a lot for the review, I tried to remove as much of the "could/should/good idea" stuff from here and tried improve directness. I also addressed your other comments, if you could take another look when possible that would be great!

2024-12-10 13:59 UTC, alexflorisca approved these changes
Nice one, thanks for making those changes. What do you think would be a good way to keep track of https://github.com/woocommerce/woocommerce/pull/53553 and update these docs when it's merged?

2024-12-10 14:00 UTC, opr commented
@alexflorisca Thanks! I'd say let's merge this when CI passes, and then the docs can be directly updated in #53553

2024-12-10 15:03 UTC, merged

2024-12-10 15:22 UTC, alexflorisca commented
Passing the buck to me I see! That's cool, let's do that 😎