Add ValidatedCheckboxControl component
woocommerce/woocommerce pull request #53591
Opened 2024-12-10 10:43 UTC by opr

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2025-01-08 04:01 UTC, samueljseay reviewed
I haven't tested this yet, but I have a bunch of feedback mainly just trying to clean up some of the copy pasted patterns from the old component. 🙏🏻

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	// id to use for the input. If not provided, an id will be generated.
Things like id, className, onChange should all already be on the type if it's typed correctly.

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	ariaDescribedBy?: string | undefined;
Why have you omitted aria-describedby then added a new declaration here? It should use the one built into the type.

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	label?: string | undefined;
a type with `?` and `undefined` is unusual and not how I'd present the type (although I have seen it done a lot in blocks for some reason).

`?` itself means it may not be passed. `undefined` means it might explicitly be passed and be undefined, which doesn't make a whole lot of sense for react props. 
You have a lot of cases of this so I won't mark each one but they should all be `?` and remove `| undefined`

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	customValidityMessage?: ( validity: ValidityState ) => undefined | string;
Given the comment this is a little confusing. why have the callback take validity and not always return a value if its only for false validity? 

I think that it would be more helpful from TS point of view to always return `string` which makes the contract more explicit.

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	// Whether validation should run when focused - only has an effect when focusOnMount is also true.
The comment implies focus, but the code and variable name are for on mount.

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> + * A text based input which validates the input value.
This is a checkbox not a text based input.

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +		// @ts-ignore - The second argument is a dependency array, this has no deps it should recalculate all the time.
I don't think this holds true, why should it "recalculate all the time"? The deps array is best to provide because the way useSelect works is that it memoizes based on combination of deps and the store so it's never really correct to pass no deps. See p6rkRX-3WM-p2

I realize this started as copy pasta of validated text input but that component as nature of being old and untouched has legacy stuff that I'd like to not bring forward into new components.

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +		if ( passedErrorMessage !== '' && isObject( validationError ) ) {
The typechecks and validation of validationError are not correct, and its partially because the `useSelect` where it's declared does not have a type passed as generic arg. Start by passing a type to the useSelect e.g. (inline type but you get the idea):

```ts
const { validationError } = useSelect<{validationError: string | undefined, validationErrorId: string | undefined}>
```

then the isObject check (which will always be true) can be removed here.

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +				aria-invalid={ hasError === true }
Not saying this is wrong, but it feels odd. is there a situation where would we have validationError be hidden and mark this as valid? not sure if that even makes sense but it's at least a smell to me. What does validation error being hidden mean when there is a validation error?

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +				onChange={ ( newValue ) => {
This should be using useCallback

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +			typeof id !== 'undefined' ? id : 'textinput-' + instanceId;
Can we clean this statement up. no way we need to check typeof is not undefined and we should assign one for empty string too since it's an id.

so:

```js
const textInputId = id || `textinput-${instanceId}`;
```

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +		const errorIdString = errorId !== undefined ? errorId : textInputId;
This too I see no reason why it can't be simpler `const errorIdString = errorId || textInputId;`

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +			customValidationRef.current = customValidation;
I think we should take a look at why this was done this way. How is this better than just adding the validation call back as a dep to the [useCallback](https://github.com/woocommerce/woocommerce/pull/53591/files#diff-f60a87418ee0312ad818a4b230090c7cd6217b3c6b72f6bc56a81f9e45fcab0eR131) ?

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	): JSX.Element => {
Just noting we don't need explicit return type. imo its better to let TS infer this based on what we actually return. it's more automatic and doesn't require updating a type when we decide for example that maybe this component can return null. TS can figure it all out ✨

2025-01-08 04:01 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +		const instanceId = useInstanceId(
Can we ditch the dep on useInstanceId and just do useId?

Although with useId we'll have to do:

```
const genId = useId();
const instanceId = preferredInstanceId || genId;
```

it still won't be a loss because under the hood useInstanceId still calls useMemo. It would be great to just keep to plain React where possible and avoid bringing in any dep we don't need.

2025-01-08 12:14 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	// id to use for the input. If not provided, an id will be generated.
this version of `onChange` doesn't receive an event as a parameter, just the value of the checkbox. className and id, I agree.

2025-01-08 21:07 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	ariaDescribedBy?: string | undefined;
Think this was added because of the case, I can update that.

2025-01-08 21:10 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	label?: string | undefined;
I think this is because we have `"exactOptionalPropertyTypes": true,` in the tsconfig, previously this gave errors when not passing optional props unless they were also typed as `undefined`. I removed them and it doesn't seem to have an issue with it.

2025-01-08 21:13 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	ariaDescribedBy?: string | undefined;
I don't think we can update this in `ValidatedTextInput` (at the moment) as this is in use by third parties (exported in the components package). Will save it for a follow up.

2025-01-08 21:13 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	customValidityMessage?: ( validity: ValidityState ) => undefined | string;
Agreed, updated.

2025-01-08 21:27 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	label?: string | undefined;
I tried updated the `ValidatedTextInput` and get this error:

```
TS2375: Type
{     type: string | undefined;     ariaDescribedBy: string;     value: string;     onChange: ( newValue: string ) => void;     customFormatter: ( value: string ) => string;     customValidation: ( inputObject: HTMLInputElement ) => boolean;     ... 10 more ...;     ref: ( el: ValidatedTextInputHandle | null ) => ValidatedTextInputHandle | null; }
is not assignable to type ValidatedTextInputProps with 'exactOptionalPropertyTypes: true'. Consider adding undefined to the types of the target's properties.
Types of property errorMessage are incompatible.
Type string | undefined is not assignable to type string
Type undefined is not assignable to type string
```

See the docs for this config https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes

The branch currently shows this error in `plugins/woocommerce-blocks/assets/js/base/components/cart-checkout/form/form.tsx` if you want to check it out

2025-01-08 21:37 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +		// @ts-ignore - The second argument is a dependency array, this has no deps it should recalculate all the time.
Ah nice, so if we supply an empty array it seems to work OK, even if the validation data store is changed externally (e.g. in case a third party modifies it)

2025-01-08 22:49 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +		if ( passedErrorMessage !== '' && isObject( validationError ) ) {
I think we need to solve the issue of the types on `useSelect` before we look at this, let's circle back to it.

2025-01-08 22:51 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +				aria-invalid={ hasError === true }
> What does validation error being hidden mean when there is a validation error?

All required fields have errors added to the validation data state, they start off as hidden, and they get removed when the field becomes valid. The errors become unhidden when the form is submitted.

2025-01-09 04:41 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	// id to use for the input. If not provided, an id will be generated.
ok yep fair enough 👍🏻

2025-01-09 04:43 UTC, samueljseay commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +	label?: string | undefined;
@opr was this the issue you want to look at? Happy to take a look. I feel pretty sure we could clean this up. I think with React in most cases the `?` is enough because it implies we don't pass it at all.

I don't think we want to encourage pattern like someProp={undefined} it just doesn't make a whole lot of sense.

2025-01-16 11:15 UTC, opr commented
Currently waiting on https://github.com/woocommerce/woocommerce/issues/54429 to be complete before continuing

2025-01-22 12:41 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +			customValidationRef.current = customValidation;
Moving this into the `useCallback` below results in infinite loop and a max depth exceeded error.

2025-01-22 12:45 UTC, opr commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +		if ( passedErrorMessage !== '' && isObject( validationError ) ) {
I think with the changes from https://github.com/woocommerce/woocommerce/pull/54468 this is no longer an issue

2025-01-27 11:53 UTC, wavvves requested changes
I'm currently reviewing this as well, heads up about `docs-manifest.json` needing regeneration 🙂 👍🏼

2025-01-27 17:14 UTC, wavvves reviewed
Hey Thomas, tested out ok, just left a few comments on the `process_checkbox_field` which seems a bit overworked 👍🏼

2025-01-27 17:14 UTC, wavvves commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +			_doing_it_wrong( 'woocommerce_register_additional_checkout_field', esc_html( $message ), '9.8.0' );
Do we really need to throw a doing it wrong here?
Wondering if anyone makes a GUI plugin for this, having an error msg field filled and changing the checkbox to optional again wouldn't be a huge penalty. That way, for instance, the plugin could just show/hide the field, but maintain it, so toggling it back to required in the future would have the previous error message persisted.
We can just unset it to avoid carrying unnecessary data over.

2025-01-27 17:14 UTC, wavvves commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +		}
We can rework this to avoid all the issets (I don't think they might be need actually) and really cut down the fat from the method. We can start by null coalescing and filtering the 'required' key, and then return early as you have. 
Note: 1, '1', 'yes' / 0, '0', 'no will evaluate to (bool) true/false, is this acceptable?
From there $options['required'] will always be set and true, which will make life easier:
 
```suggestion
$field_data['required'] = filter_var( $options['required'] ?? null, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE ); // Note: 1, '1', 'yes', / 0, '0', 'no' will evaluate to (bool) true/false, is this acceptable?
		if ( null === $field_data['required'] ) { // we exit early if can't be coalesced into boolean
		   $message = sprintf( 'The required property for field with id: "%s" must be a boolean, you passed %s. The field will not be registered.', $id, gettype( $field_data['required'] ) ); // This message should be adjusted, as it can accepts certain strings and ints as stated above.
			_doing_it_wrong( 'woocommerce_register_additional_checkout_field', esc_html( $message ), '9.8.0' );
			return false;
	    }
	    
	    if ( false === $field_data['required'] ) {
	        unset( $field_data['error_message'] ); // See comment below
	        return $field_data; // We're done, in this case.
	    }
```

2025-01-27 17:14 UTC, wavvves commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +
This wouldn't be needed anymore. At this point `$field_data['required']` === `true`

```suggestion

```

2025-01-27 17:14 UTC, wavvves commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +		}
This is odd, isn't the $field_data already carrying defaults? We check for $options, but I don't see where the value from it gets copied to $field_data

2025-01-27 19:17 UTC, wavvves commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
>  	private function process_checkbox_field( $field_data, $options ) {
Hey Thomas, It's hard to use commit suggestions to exemplify this, so I've opened a [PR](https://github.com/woocommerce/woocommerce/pull/54895) targeting this branch ✋🏼 

The validate-parse-process is becoming a bit convoluted, and if we don't start tidying this up we might get some nasty tech debt soon around mixed responsibilities (validation) and mixed return types (false|array).
In theory, the `process_checkbox_field()` should be as clean as this (on the my PR it's almost equivalent to your version):

```php
private function process_checkbox_field( array $field_data ): array {
    if ( isset( $field_data['error_message'] ) ) {

        if ( '' !== $field_data['error_message'] ) { // Validate should verify is_string or undefined
            $field_data['errorMessage'] = $field_data['error_message'];
        }

         unset( $field_data['error_message'] );
    }

    return $field_data;
}
```

2025-01-28 11:00 UTC, opr commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +			_doing_it_wrong( 'woocommerce_register_additional_checkout_field', esc_html( $message ), '9.8.0' );
> Do we really need to throw a doing it wrong here?

No, but we do this in every other "unexpected" configuration. I feel it's useful and doesn't add any complexity to the code. I am in favour of keeping it

> if anyone makes a GUI plugin for this, having an error msg field filled and changing the checkbox to optional again wouldn't be a huge penalty. 

This doing it wrong is designed for the developer, not the end-user. The developer would have to make sure the error message was stripped out if the field was optional.

> That way, for instance, the plugin could just show/hide the field, but maintain it, so toggling it back to required in the future would have the previous error message persisted.
We can just unset it to avoid carrying unnecessary data over.

In the case of a UI manager for the additional fields, I think the string would be saved and either passed/not passed  to `woocommerce_register_additional_checkout_field` based on required/optional.

2025-01-28 12:05 UTC, opr commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +		}
Thanks for the suggestions Paulo!

> Note: 1, '1', 'yes' / 0, '0', 'no will evaluate to (bool) true/false, is this acceptable?

Yeah, we should tolerate these values, especially 'false' and 'true' but the others are fine. We can't use `wc_string_to_bool` here because we specifically want null on failure.

> // This message should be adjusted, as it can accepts certain strings and ints as stated above

They're accepted but not encouraged, don't think it's worth advertising it.

I tried making some of the refactors you suggested.

```php
$field_data['required'] = filter_var( $options['required'] ?? null, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE ); // Note: 1, '1', 'yes', / 0, '0', 'no' will evaluate to (bool) true/false, is this acceptable?
		if ( null === $field_data['required'] ) { // we exit early if can't be coalesced into boolean
		   $message = sprintf( 'The required property for field with id: "%s" must be a boolean, you passed %s. The field will not be registered.', $id, gettype( $field_data['required'] ) ); // This message should be adjusted, as it can accepts certain strings and ints as stated above.
			_doing_it_wrong( 'woocommerce_register_additional_checkout_field', esc_html( $message ), '9.8.0' );
			return false;
	    }
```

The problem with this is we want to check the original type provided in `$options['required']`, you've set `$field_data['required']` to the result of `filter_var` which will be either null, or a valid boolean. It won't represent the actual type provided to the register function. We'd need to check whether `$options['required']` is set before accessing it in `gettype`.

2025-01-28 12:05 UTC, opr commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +
I'm going to remove setting `$options['required']` and instead set it straight to `$field_data['required']` I don't think we need to reference `$options` again and can just use `$field_data` from here.

2025-01-28 12:09 UTC, opr commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
>  	private function process_checkbox_field( $field_data, $options ) {
The PR you opened contains all changes from my branch too, did you base it properly on this branch?

2025-01-28 17:32 UTC, wavvves commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
>  	private function process_checkbox_field( $field_data, $options ) {
Weird, I created it from this one, it shouldn't have the 20 changed files. You don't have to merge it, I was just having trouble submitting a suggestion because it wouldn't let me select all the lines.

Do you agree with refactoring this bit before it gets too dense? I think this validate-parse-process can be much more clean. If so, we can do it on a separate issue not to block this, since it might not be that straightforward. That way we can touch other bits like the other process_* method if needed.

2025-01-28 17:37 UTC, wavvves commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +		}
Yeah it should be $options instead of field_data there, and needs to check if defined. If undefined then it's optional right? we can adjust the filter_var

2025-01-28 17:48 UTC, opr commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
>  	private function process_checkbox_field( $field_data, $options ) {
> Do you agree with refactoring this bit before it gets too dense?

Yes, I think we should look into it, there are going to be other field types where the same logic gets added, so refactoring and untangling this is a good idea. I don't think we should do it on this PR as it would increase complexity further, and it makes sense to refactor as part of a separate effort.

You could suggest this on the cycle post pca54o-8RL-p2

2025-01-28 17:55 UTC, opr commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +		}
> Yeah it should be $options instead of field_data there

But then we're overwriting the developer's setting, if we do that also can't present the type later.

> and needs to check if defined. If undefined then it's optional right?

Yeah, that's why I have the isset check there, if there's no`required` field then we can skip checking its type. If it's set, we need to check its type.

> we can adjust the filter_var

Adjust it to do what? filter_var only returns bool, or null if the value could't be filtered, I am not sure what we're trying to optimize here? Reduce the number of isset checks? To what end? If it were expensive calls then I would be totally on board, but `isset` is cheap, and I'd say better to overuse it than risk having any warning showing on a merchant's site.

2025-01-29 18:20 UTC, wavvves commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +		}
> But then we're overwriting the developer's setting, if we do that also can't present the type later.
No, on the get type call. It's checking if field_data is null and then calling get type on it instead of doing it on the original options value.

2025-01-29 18:29 UTC, wavvves commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
>  	private function process_checkbox_field( $field_data, $options ) {
I created https://github.com/woocommerce/woocommerce/issues/54987 to tackle that.
Going to proceed with the review 👍🏼

2025-01-29 18:54 UTC, opr commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +		}
> No, on the get type call. 

Ah, I see, yeah, so we do need to keep `isset` to check if `$options['required']` has a value. I think the current setup is OK for this?

2025-01-30 12:53 UTC, wavvves approved these changes
All good Thomas, thanks for the patience ☺️

2025-02-03 16:06 UTC, senadir approved these changes
All is good Thomas, preapproving on the condition that we will remove feedback and pass errors on top directly.

2025-02-03 16:06 UTC, senadir commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +			/>
Given we don't have a good case for feedback let's just skip it for now, and render the error message here directly in validated checkbox control

2025-02-03 16:06 UTC, senadir commented on plugins/woocommerce-blocks/packages/components/checkbox-control/index.tsx
> +	feedback?: ReactNode | null;
Also delete this as we don't need feedback

2025-02-03 16:06 UTC, senadir commented on plugins/woocommerce-blocks/packages/components/checkbox-control/validated-checkbox-control.tsx
> +							elementId={ errorIdString }
```suggestion
							propertyName={ errorIdString }
```

Passing `errorMessage` and/or `elementId` causes the error to always be shown, only `propertyName` should be passed here.

2025-02-03 16:06 UTC, senadir commented on plugins/woocommerce-blocks/tests/e2e/plugins/additional-checkout-fields.php
> +				'required'      => 'true',
```suggestion
				'required'      => true,
```

2025-02-03 16:06 UTC, senadir commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +		if ( isset( $options['required'] ) && null === filter_var( $options['required'], FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE ) ) {
This filter_var is probably allowing `"true"` so maybe let's not do that?

2025-02-03 16:06 UTC, senadir commented on plugins/woocommerce/src/Blocks/Domain/Services/CheckoutFields.php
> +		}
This can go

2025-02-03 16:06 UTC, senadir commented on plugins/woocommerce/tests/php/src/Blocks/StoreApi/Routes/AdditionalFields.php
> +				'required' => 'true',
```suggestion
				'required' => true,
```

2025-02-03 20:27 UTC, merged