PoC: Migrate Back in stock notifications tests to Core
woocommerce/woocommerce pull request #53641
Opened 2024-12-11 17:43 UTC by nathanss

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

This is a proof of concept regarding migration of E2E tests from the plugin Back in Stock notifications.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. For now, please extract the woocommerce-back-in-stock-notifications plugin into your Downloads folder, alongside the `provision.php` and `bis-acceptance-test-helper.php` files, as mapped in .wp-env.json
2. Go to the `plugins/woocommerce` folder and run `pnpm playwright test --config="./tests/e2e-pw/playwright.config.js" ./tests/e2e-pw/tests/back-in-stock-notifications`

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2025-01-22 11:51 UTC, PanosSynetos requested changes
Hey @nathanss - I've uploaded a zip for BIS in order for the test suite to run. I noticed that the CI has failed, unit and E2E tests.

https://github.com/woocommerce/woocommerce/actions/runs/12907206456

Please have a look and resolve them, before we proceed further with reviewing.
Thanks

2025-01-24 06:26 UTC, PanosSynetos requested changes
Hey Nathan - Thanks for fixing the E2E tests - The unit tests need to be fixed and some linting errors and we should be good for a full review

```
1) WC_Webhook_Test::test_payload_for_deleted_user_id_with_reassign
Unexpected incorrect usage notice for register_rest_route.
The REST API route definition for <code>wc/v3/create-bis-notifications</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. (This message was added in version 5.5.0.)
Failed asserting that an array is empty.
```

2025-01-29 14:00 UTC, jimjasson commented
@nathanss When Back In Stock Notifications will be merged into core, it will be disabled at first. This means that Back In Stock Notifications tests shouldn't run in all core PRs during that time. Is there a way to skip/disable/ignore tests? For Brands, we did a `test.skip`, but it was only 1 E2E test then. Perhaps we should explore bulk disabling Back In Stock Notifications tests?

2025-02-03 10:17 UTC, PanosSynetos commented
@xristos3490 if you have any comments on this PR, feel free to share, so Nathan can address them.

2025-02-04 07:31 UTC, PanosSynetos commented
@nathanss did you check @jimjasson 's [comment](https://github.com/woocommerce/woocommerce/pull/53641#issuecomment-2621736377) ?

2025-02-04 12:11 UTC, nathanss commented
@PanosSynetos yup! when it's time to merge, we can either ignore the whole folder in the configuration through the `testIgnore` attribute.

2025-02-04 15:05 UTC, xristos3490 reviewed
Great job setting this up, @nathanss! I like how this is progressing so far and how the previous Gherkin arch inspired you to create a new one in PW. Also, excellent work on reducing the footprint on the base test site!

One note: These features used to run **in a matrix for block themes and legacy themes** (Tsubaki and Storefront). I can only see them running in TT3 now. An interesting example can be found [here](https://github.com/woocommerce/woocommerce/blob/c62e16b7931d6a3f88a30531ece3440d54a96689/plugins/woocommerce/tests/e2e-pw/tests/shopper/launch-your-store.spec.js#L5) for the CommingSoonPage's tests. 

Should we do this here as well? If so, I'd suggest to go with (TT4 + Storefront) this time cc @PanosSynetos 

Aside from that, I left a couple of comments, mainly nits and my thoughts on this migration so far.

2025-02-04 15:05 UTC, xristos3490 commented on plugins/woocommerce/tests/e2e-pw/bin/class-wc-bis-acceptance-test-helper.php
> +		add_shortcode( 'confirmation_received_email', array( __CLASS__, 'render_confirmation_received_email_shortcode' ) );
We could prefix these shortcodes with `bis`?

2025-02-04 15:05 UTC, xristos3490 commented on plugins/woocommerce/tests/e2e-pw/bin/test-env-setup.sh
> +wp-env run tests-cli wp post create --post_type=page --post_status=publish --post_title='Confirmation email' --post_name='confirmation-email' --post_content='[confirmation_received_email]'
Same for page slugs. I think it's a good idea to prefix with `bis`; page title and name(slug). WDYT?

2025-02-04 15:05 UTC, xristos3490 commented on plugins/woocommerce/tests/e2e-pw/tests/back-in-stock-notifications/helper.js
> +				'Want to be notified when this product is back in stock?'
A few thoughts about generally searching for texts in this PR. In Codeception, we use more specific rules; for example, something like:
```js
this.page.frameLocator( '.product #wc_bis_product_form .wc_bis_form_title' ).getByText( 'Want to be notified when this product is back in stock?' )
```

The reason I feel uncertain about this change, is that: 
- On one hand, [specific DOM searches](https://github.com/woocommerce/woocommerce-back-in-stock-notifications/blob/50e96331b1697761900e6709d5987af998846788/tests/_support/AcceptanceTester.php#L353-L355) have been a good practice for monitoring the DOM and classes, and even catching potential regressions in the past _(e.g., like catching block-specific store notices bleed to legacy themes)_
- On the other hand, end-to-end tests should focus on functionality, so they shouldn't become overly sensitive to small improvement iterations.

But,

While reviewing other Core tests, I've noticed this pattern _frequently_. So, my intention with this comment is to highlight a potential change rather than to hold up this PR. Curious to hear your thoughts @nathanss! Also, cc @jimjasson

2025-02-04 15:05 UTC, xristos3490 commented on plugins/woocommerce/tests/e2e-pw/bin/test-env-setup.sh
> +wp-env run tests-cli wp post create --post_type=page --post_status=publish --post_title='Confirmation email' --post_name='confirmation-email' --post_content='[confirmation_received_email]'
Along with that nit, and speaking about "minimizing footprint.", I believe there's a more effective way **to eliminate the need for custom pages and shortcodes**.

To properly test the "end-to-end" notification process in this new Core environment, the ideal flow would be:

- Sign up for an OOS product.
- Change the stock status of that product.
- Process the Action Scheduler (AS) action behind the scenes (probably via $GET). 
- Use the _(already available)_ WP Mail Logging plugin to monitor email activity and contents.

Once more, I'm not blocking here since this is perfectly aligned with what we had before, but I'll make sure to create a technical debt so we can tackle it in our next steps.

2025-02-04 16:57 UTC, nathanss commented on plugins/woocommerce/tests/e2e-pw/tests/back-in-stock-notifications/helper.js
> +				'Want to be notified when this product is back in stock?'
> While reviewing other Core tests, I've noticed this pattern frequently.

What pattern are you referring to? Being specific or generic?

I prefer being generic on E2E tests, as a rule of thumb, since the tests fail very easily for multiple reasons. But, it is, like in most cases, a tradeoff. If we're too generic, we risk making a test pass when it shouldn't. I tried to strike a good balance in this PR! :)

2025-02-04 17:12 UTC, nathanss commented on plugins/woocommerce/tests/e2e-pw/bin/test-env-setup.sh
> +wp-env run tests-cli wp post create --post_type=page --post_status=publish --post_title='Confirmation email' --post_name='confirmation-email' --post_content='[confirmation_received_email]'
> Same for page slugs. I think it's a good idea to prefix with bis; page title and name(slug). WDYT?

Sounds good!

2025-02-04 17:13 UTC, nathanss commented on plugins/woocommerce/tests/e2e-pw/bin/test-env-setup.sh
> +wp-env run tests-cli wp post create --post_type=page --post_status=publish --post_title='Confirmation email' --post_name='confirmation-email' --post_content='[confirmation_received_email]'
> Once more, I'm not blocking here since this is perfectly aligned with what we had before, but I'll make sure to create a technical debt so we can tackle it in our next steps.

That makes sense, I didn't knew there was already infrastructure available for this.

2025-02-04 17:14 UTC, nathanss commented
> Should we do this here as well? If so, I'd suggest to go with (TT4 + Storefront) this time cc @PanosSynetos

@xristos3490 I've updated the code to run with both themes, as we were doing before. Please take a look!

2025-02-05 08:40 UTC, jimjasson commented on plugins/woocommerce/tests/e2e-pw/tests/back-in-stock-notifications/helper.js
> +				'Want to be notified when this product is back in stock?'
As @xristos3490 mentioned, using specific selectors mainly helped us identify regressions in the cart/checkout blocks. Now that Back In Stock Notifications will be merged into core, I don't think there is much value in continuing to test functionality added by other core modules, like blocks. It is up to those modules to ensure that they add the necessary tests that are required to prevent regressions like those discovered by Back In Stock Notifications tests. 

So, I propose that we move to generic selectors when it comes to core elements, but consider using more specific selectors for Back In Stock Notifications-specific elements.

2025-02-05 13:53 UTC, jimjasson reviewed
Great work here Nathan! 

I am amazed from how well Codeception tests were ported to Playwright. My only concern is that it is a bit difficult to read the `helper.js` file as each function has a very long name and calls other functions with equally long names. However, we need to see this in practice in the future -- for example, when/if we need to add more tests.

Looks good for now, I will approve as soon as we are able to run these tests with Back In Stock Notifications code in core.

2025-02-05 14:49 UTC, xristos3490 commented on plugins/woocommerce/tests/e2e-pw/tests/back-in-stock-notifications/helper.js
> +				'Want to be notified when this product is back in stock?'
Sounds good, folks! 

>What pattern are you referring to? Being specific or generic?

To clarify, I noticed that **this simple form of selectors** is used in other Core tests, so I’m also inclined to follow that. Additionally, considering the effort it took to run these tests for both legacy and blocks, seems like another proof of that direction! 

As Jason mentioned, if we need to guard against class issues and other regressions, a dedicated test must be created.

2025-02-05 15:22 UTC, xristos3490 commented
Looking good, @nathanss! 👌 

FYI, I've created a follow-up to remove the need for pages and shortcodes [here](https://github.com/woocommerce/woocommerce/issues/55141).

2025-02-24 20:10 UTC, peterfabian commented on plugins/woocommerce/tests/e2e-pw/bin/test-env-setup.sh
> +
This didn't seem to work in my testing, as once there are some pages, WC won't create pages like Cart and Checkout and then the e2e tests fail during the step to 
> convert Cart and Checkout pages to shortcode 

Will think about how to address this.

2025-03-13 08:20 UTC, peterfabian commented
This has been merged to https://github.com/woocommerce/woocommerce/pull/55836. Closing this PR. Thanks @nathanss !

2025-03-13 08:20 UTC, closed without merging