Add coming soon template - split right image
woocommerce/woocommerce pull request #53774
Opened 2024-12-17 03:18 UTC by chihsuan

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-12-17 13:46 UTC, ilyasfoo requested changes
Looking great, @chihsuan! I have some minor comments.

I also helped compressed images using https://compressor.io/ where I think we can have significant savings. Visually they look the same to me, but let me know if you find it to be of low quality.

2024-12-17 13:46 UTC, ilyasfoo commented on plugins/woocommerce/assets/images/pattern-placeholders/orange-wall-with-bicycle.jpg
Compressed down to 38kb:

https://github.com/user-attachments/assets/eafb07a7-00cc-4c3b-9665-fc750e7c2054

2024-12-17 13:46 UTC, ilyasfoo commented on plugins/woocommerce/assets/images/pattern-placeholders/wheel-leaf-bicycle-bike-vehicle-spoke.jpg
Compressed down to 7kb:

https://github.com/user-attachments/assets/3c26c6d9-5c8b-4060-87e7-fb30d4bfd710

2024-12-17 13:46 UTC, ilyasfoo commented on plugins/woocommerce/patterns/page-coming-soon-split-right-image.php
> +				<div class="wp-block-cover is-light woocommerce-split-right-image-cover" style="padding-top:126px;padding-right:75px;padding-bottom:126px;padding-left:76px;min-height:100%"><span aria-hidden="tru
I find this to be better, especially on smaller screens where the bike will be in focus

<img width="493" alt="image" src="https://github.com/user-attachments/assets/b3ae6afe-468e-4d0a-9bcb-dbbe71c40b20" />

```suggestion
			<div class="wp-block-column is-vertically-aligned-stretch"><!-- wp:cover {"url":"<?php echo esc_url( $right_image ); ?>","id":34,"dimRatio":0,"customOverlayColor":"#cd7550","isUserOverlayColor":false,"focalPoint":{"x":0.5,"y":0.8},"minHeight":100,"minHeightUnit":"%","isDark":false,"className":"woocommerce-split-right-image-cover","style":{"spacing":{"padding":{"top":"126px","bottom":"126px","left":"76px","right":"75px"}}},"layout":{"type":"default"}} -->
				<div class="wp-block-cover is-light woocommerce-split-right-image-cover" style="padding-top:126px;padding-right:75px;padding-bottom:126px;padding-left:76px;min-height:100%"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim" style="background-color:#cd7550"></span><img class="wp-block-cover__image-background wp-image-34" alt="" src="<?php echo esc_url( $right_image ); ?>" style="object-position:50% 80%" data-object-fit="cover" data-object-position="50% 80%"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","style":{"typography":{"fontSize":"75px","fontStyle":"normal","fontWeight":"400","lineHeight":"1.3"},"color":{"text":"#ffffff80"},"elements":{"link":{"color":{"text":"#ffffff80"}}}},"fontFamily":"<?php echo esc_attr( $cardo_font_family ); ?>"} -->
```

2024-12-18 00:15 UTC, chihsuan commented
> I also helped compressed images using https://compressor.io/ where I think we can have significant savings. Visually they look the same to me, but let me know if you find it to be of low quality.

Thanks for the help! @ilyasfoo This is looking great. Updated the images in 2534e388d7d8e168595f130d8df062c5fa96880b.

2024-12-18 01:44 UTC, ilyasfoo approved these changes
Awesome, thanks! Tests well, LGTM!

2024-12-18 07:00 UTC, rjchow approved these changes
Tested well and looks good! Nice catch on the image optimisation @ilyasfoo !

2024-12-18 07:24 UTC, merged