Update examples in
woocommerce/woocommerce pull request #53808
Opened 2024-12-17 20:33 UTC by vyskoczilova

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [x] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [x] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Update typos in `experimental__woocommerce_blocks-checkout-set-shipping-address` and `experimental__woocommerce_blocks-checkout-set-billing-address` 

</details>

2024-12-23 18:05 UTC, wavvves approved these changes, later dismissed
Hi @vyskoczilova thank you so much for your contribution!

2025-01-30 16:29 UTC, wavvves commented
Hi @vyskoczilova, can you please add a changelog entry with `pnpm --filter='@woocommerce/plugin-woocommerce' changelog add` so this PR can be merged?
You should choose the option to add a comment, and copy the string from the PR description. Unfortunately the job to auto add the entry will not work with PRs coming from forks, and this needs to be added manually.

2025-01-30 16:37 UTC, vyskoczilova commented
@wavvves Hi Paulo, done.

2025-01-30 16:41 UTC, wavvves requested changes

2025-01-30 16:41 UTC, wavvves commented on plugins/woocommerce/changelog/2025-01-30-16-35-38-940528
> +Update typos in experimental__woocommerce_blocks-checkout-set-shipping-address and experimental__woocommerce_blocks-checkout-set-billing-address
```suggestion
Significance: patch
Type: tweak
Comment: Update typos in experimental__woocommerce_blocks-checkout-set-shipping-address and experimental__woocommerce_blocks-checkout-set-billing-address

```

2025-01-30 16:41 UTC, wavvves approved these changes

2025-01-30 16:56 UTC, merged