Introducing payment method constants
woocommerce/woocommerce pull request #53941
Opened 2024-12-20 17:55 UTC by wjrosa

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2025-01-06 18:41 UTC, barryhughes reviewed
Thanks!

Left a couple of minor notes. Also wanted to double check if anything flagged using the following one-liner needs to be updated:

```sh
grep -Ern "'(bacs|cheque|cod|paypal|woocommerce_payments)'" ./ | grep .php
```

For instance, in [class-wc-settings-payment-gateways.php](https://github.com/woocommerce/woocommerce/blob/b4020a8432f669e0c67b32c3beedcb3238654d0d/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php) should we update the following, and use the new constants for the array keys?

```php
$wcpay_setup        = isset( $payment_gateways['woocommerce_payments'] ) && ! $payment_gateways['woocommerce_payments']->needs_setup();
```

2025-01-06 18:41 UTC, barryhughes commented on plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php
> +			return $can_paypal ? array( PaymentMethods::PAYPAL => $gateways['paypal'] ) : array();
```suggestion
			return $can_paypal ? array( PaymentMethods::PAYPAL => $gateways[PaymentMethods::PAYPAL] ) : array();
```

I might be mistaken, but shouldn't we use the constant twice in this case?

2025-01-06 18:41 UTC, barryhughes commented on plugins/woocommerce/tests/legacy/unit-tests/payment-gateways/payment-gateways.php
> +		WC()->session->set( 'chosen_payment_method', PaymentMethods::BACS );
Just curious, why don't we use the new constant on the previous line? That is, like this:

```php
$gateways[PaymentMethods::BACS]->chosen = false;
```

(I'm only flagging this one, but I think there are a few areas like this.)

2025-01-07 14:46 UTC, wjrosa commented
> Thanks!
> 
> Left a couple of minor notes. Also wanted to double check if anything flagged using the following one-liner needs to be updated:
> 
> ```shell
> grep -Ern "'(bacs|cheque|cod|paypal|woocommerce_payments)'" ./ | grep .php
> ```
> 
> For instance, in [class-wc-settings-payment-gateways.php](https://github.com/woocommerce/woocommerce/blob/b4020a8432f669e0c67b32c3beedcb3238654d0d/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php) should we update the following, and use the new constants for the array keys?
> 
> ```
> $wcpay_setup        = isset( $payment_gateways['woocommerce_payments'] ) && ! $payment_gateways['woocommerce_payments']->needs_setup();
> ```

Thanks for the review, @barryhughes ! I replaced all occurrences returned by your command and accepted your suggestions as well 👍

2025-01-07 23:10 UTC, barryhughes requested changes
Thanks for this!

1. Some test failures we need to address (looks like we haven't imported the enum in a few cases).
2. Also, and perhaps in some ways it's a little late to be asking this (though, better late than never ... and I'd anyway be interested in fellow reviewer @kalessil's thoughts) but in this particular case I actually wonder if introducing a new class, as we're doing here, is preferable to adding constants to the gateway classes themselves. 

To clarify that second point, I guess my feeling is that something like `WC_Gateway_Cheque::ID` (or `::SLUG`) might feel a little more natural than `PaymentMethods::CHEQUE` (why *wouldn't* the class know its own slug/ID/moniker)?. This would also remove the need to introduce yet another class.

Again, I wanted to pause and ask the question, since we'll be working with this new enum class for a long time, but I'm also not opposed to it in its current form.

2025-01-07 23:10 UTC, barryhughes commented on plugins/woocommerce/tests/php/src/Blocks/BlockTypes/OrderConfirmation/Totals.php
> +				'payment_method'   => PaymentMethods::BACS,
Many of our checks are failing, and I think one of the causes may be that in some cases we haven't imported the enum (ie, we need a `use` statement at the top of this file) ... same applies to a few other files we touched.

Example of a failing test:

```
2) Automattic\WooCommerce\Tests\Blocks\BlockTypes\OrderConfirmation\Totals::test_order_notes_cleaned
Error: Class 'Automattic\WooCommerce\Tests\Blocks\BlockTypes\OrderConfirmation\PaymentMethods' not found
```

2025-01-08 12:32 UTC, wjrosa commented
> Thanks for this!
> 
> 1. Some test failures we need to address (looks like we haven't imported the enum in a few cases).
> 2. Also, and perhaps in some ways it's a little late to be asking this (though, better late than never ... and I'd anyway be interested in fellow reviewer @kalessil's thoughts) but in this particular case I actually wonder if introducing a new class, as we're doing here, is preferable to adding constants to the gateway classes themselves.
> 
> To clarify that second point, I guess my feeling is that something like `WC_Gateway_Cheque::ID` (or `::SLUG`) might feel a little more natural than `PaymentMethods::CHEQUE` (why _wouldn't_ the class know its own slug/ID/moniker)?. This would also remove the need to introduce yet another class.
> 
> Again, I wanted to pause and ask the question, since we'll be working with this new enum class for a long time, but I'm also not opposed to it in its current form.

I actually think it makes total sense! And it matches what was done with WooPayments and the Stripe extension already. I have updated the main implementation in https://github.com/woocommerce/woocommerce/pull/53941/commits/69e77454c4e54c976a397556e6e33ee93a018a91. I had to remove `woocommerce_payments` value as we don't have the gateway class in this repository.

2025-01-08 17:07 UTC, barryhughes requested changes
Thanks for implementing that change (adding an ID constant to the existing gateway classes). Looks good, though left some minor notes and suggestions:

- Need to tweak formatting in a few places to satisfy our linting rules.
- Not essential, but we could be more consistent in terms of how we reference classes (unnecessary qualifiers in lots of places).
- One or more checks are failing, but I think I spotted one of the problems.

2025-01-08 17:07 UTC, barryhughes commented on plugins/woocommerce-beta-tester/api/tools/class-fake-wcpayments.php
> +
I think if we nix this line then we can remove this file from the changeset.

```suggestion
```

2025-01-08 17:07 UTC, barryhughes commented on plugins/woocommerce-beta-tester/changelog/53941-dev-introducing-payment-method-constants
> +Introduces and implements payment method identifier constants in the WooCommerce plugin codebase.
Following my earlier comment, if we are not making substantive changes to the beta tester then we don't need a separate changelog entry for it.

2025-01-08 17:07 UTC, barryhughes commented on plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php
> +		$offline_payment_gateways = array( WC_Gateway_BACS::ID, \WC_Gateway_Cheque::ID, \WC_Gateway_COD::ID );
This isn't wrong, of course, and it doesn't break any linting rules, but I'd personally think this is cleaner:

```suggestion
		$offline_payment_gateways = array( WC_Gateway_BACS::ID, WC_Gateway_Cheque::ID, WC_Gateway_COD::ID );
```

Just because we are already within the root namespace, so using `\` to qualify the classes doesn't add much (and it's a little odd to do it for just two of the referenced classes).

2025-01-08 17:07 UTC, barryhughes commented on plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php
> +				'settings'         => array(
Here but also in one or more of the following blocks, can we verify the spacing before the `=>` is correct? PHPCS is complaining and I think the problem is alignment should be "per level". That is, within the inner array we don't need alignment with the arrows from the outer array.

```suggestion
				'name'        => __( 'WooCommerce Stripe Gateway', 'woocommerce' ),
				'image'       => WC()->plugin_url() . '/assets/images/stripe.png',
				'description' => $stripe_description,
				'class'       => 'checked stripe-logo',
				'repo-slug'   => 'woocommerce-gateway-stripe',
				'settings'    => array(
```

Etc, repeating as needed.

2025-01-08 17:07 UTC, barryhughes commented on plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php
> +			\WC_Gateway_Cheque::ID => array(
Similar to a previous comment, throughout the changeset (there's another example on line 1604 where we reference `\WC_Gateway_COD`) we should be consistent in terms of where we do and don't qualify our class names.

```suggestion
			WC_Gateway_Cheque::ID => array(
```

2025-01-08 17:07 UTC, barryhughes commented on plugins/woocommerce/tests/legacy/unit-tests/rest-api/Helpers/OrderHelper.php
> +		$order->set_payment_method( $payment_gateways[ WC_Gateway_BACS::class ] );
```suggestion
		$order->set_payment_method( $payment_gateways[ WC_Gateway_BACS::ID ] );
```

I think we intend to use the ID and not the class name here, right? This should a set of failing tests.

2025-01-10 13:49 UTC, kalessil commented
@wjrosa @barryhughes, sorry for the late response - adding the PR to review queue on Monday.

2025-01-10 19:12 UTC, wjrosa commented on plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php
> +		$offline_payment_gateways = array( WC_Gateway_BACS::ID, \WC_Gateway_Cheque::ID, \WC_Gateway_COD::ID );
Oh right. I removed all of them and imported the class when necessary on my latest commits.

2025-01-10 19:45 UTC, wjrosa commented
> Thanks for implementing that change (adding an ID constant to the existing gateway classes). Looks good, though left some minor notes and suggestions:
> 
> * Need to tweak formatting in a few places to satisfy our linting rules.
> * Not essential, but we could be more consistent in terms of how we reference classes (unnecessary qualifiers in lots of places).
> * One or more checks are failing, but I think I spotted one of the problems.

Thanks, Barry! I have fixed the lint issues, removed the changelog entry, the \ before the class name calls and saw tests are passing. When you have some time, I would appreciate additional 👀

2025-01-13 17:06 UTC, barryhughes reviewed
Great! Nothing else to add on my end, so hitting approve (although linting still seems to be failing in relation to arrow alignment, so we should find a way to address that if possible).

2025-01-13 17:06 UTC, barryhughes approved these changes

2025-01-13 18:59 UTC, merged