Add/54020 global unique id orders endpoint
woocommerce/woocommerce pull request #54024
Opened 2024-12-24 14:20 UTC by jobjen02

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #54020.

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Go with the Rest API to the /orders uri.
2. See that the global_unique_id appeared in the `line_items` list.

### Changelog entry

-   [x] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [x] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [x] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2024-12-24 14:25 UTC, jobjen02 commented
I also did a small cleanup there, as you can see. Before there was a double check to see if the product exists. It's now in one check with the product variable added, to increase performance.

2024-12-27 14:21 UTC, jobjen02 commented
@naman03malhotra, when are you albe to check this? This is an really important fix for our warehousing software. Thanks!

2025-01-09 13:19 UTC, jobjen02 commented
@naman03malhotra, when are you albe to check this? This is an really important fix for our warehousing software. Thanks!

2025-01-17 14:54 UTC, naman03malhotra commented on plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php
> +				}
I am yet to review this PR in depth, however I am curious why include this change as part of this PR?

2025-01-17 14:58 UTC, jobjen02 commented on plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php
> +				}
Thanks! I updated that because there was some duplicate code for that part. I just moved some lines, but git displays it as an big change.

I can revert that part if you prefer that?

2025-01-17 15:17 UTC, jobjen02 commented on plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php
> +				}
@naman03malhotra I just restored the original code, so only my change is there now :)

2025-01-21 12:36 UTC, naman03malhotra reviewed
Thanks for making the changes. I am also curious about your usecase of needing global id with orders endpoint.

2025-01-21 12:40 UTC, jobjen02 commented
> Thanks for making the changes. I am also curious about your usecase of needing global id with orders endpoint.

We develop warehouse software for customers. Every product with us has an ean code on which we match everything. For example, as soon as a Shopify order comes in, we get the ean and we know which products have been ordered. With WooCommerce, this was also possible with an EAN plugin, then this ean was put in the meta_data by the plugin. But now that WooCommerce itself supports EAN codes, this is no longer in the meta data, but we need it natively.

In short, based on the EAN code we know which product it is.

2025-01-21 12:40 UTC, jobjen02 commented
> Thanks for making the changes. I am also curious about your usecase of needing global id with orders endpoint.

@naman03malhotra 

We develop warehouse software for customers. Every product with us has an ean code on which we match everything. For example, as soon as a Shopify order comes in, we get the ean and we know which products have been ordered. With WooCommerce, this was also possible with an EAN plugin, then this ean was put in the meta_data by the plugin. But now that WooCommerce itself supports EAN codes, this is no longer in the meta data, but we need it natively.

In short, based on the EAN code we know which product it is.

2025-01-22 11:18 UTC, naman03malhotra requested changes, later dismissed
Thanks for explaining. Can you please
- Add this change to the [schema](https://github.com/naman03malhotra/woocommerce/blob/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L1142) as well.
- Please update the tests accordingly.

2025-06-27 22:32 UTC, hafizubikm commented
This is also really important in terms of being able to look up/search for products by GTIN for inventory control etc.

2025-07-02 12:44 UTC, naman03malhotra commented
I've reopned the PR and assigned Rubik to review as the original issues is assigned to their team.

2025-07-04 12:27 UTC, mikejolley requested changes
This looks good actually and since its present in products routes its fine to include.

I do however think we need to match the product route in the naming of the field in schema. Ive submitted a suggestion.

2025-07-04 12:27 UTC, mikejolley commented on plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php
> +								'description' => __( 'Product global unique id.', 'woocommerce' ),
```suggestion
								'description' => __( 'GTIN, UPC, EAN or ISBN.', 'woocommerce' ),
```

2025-07-04 13:48 UTC, mikejolley approved these changes

2025-07-04 13:57 UTC, merged