[Settings] Use DataForms to render settings fields
woocommerce/woocommerce pull request #54041
Opened 2024-12-26 08:02 UTC by chihsuan

### Submission Review Guidelines:

-   I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
-   I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
-   I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
-   Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1.
2.
3.

### Changelog entry

-   [ ] Automatically create a changelog entry from the details below.

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Details</summary>

#### Significance

-   [ ] Patch
-   [ ] Minor
-   [ ] Major

#### Type

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

#### Message 

</details>

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

2025-01-05 05:25 UTC, psealock reviewed
This is really awesome @chihsuan !

This is working well, I just noted issues with ids and select.

>DataForm is a component that allows us to render form fields with a consistent UI. It supports a variety of field types, including text, number, checkbox, and selects

The consistency in UI is great, but given that we will be passing in `InputControl`, possibly `SelectControl` and a few others do you think the added complexity is worthwhile? One thought I have is this depends on what changes we can get merged upstream. For instance, if can get `InputControl` rendered by dataviews instead of what it does now, this will support several more text types (email, password, etc) out of the box and we can remove the `getInputEdit` you've added here. This example seems like a no-brainer, but I was curious if you have any further thoughts on this?

2025-01-05 05:25 UTC, psealock commented on packages/js/settings-editor/src/utils/dataforms-transformers.tsx
> +				Edit: 'select',
Maybe its a problem upstream but I'm seeing this error:
```
react-dom.js?ver=18:73 Warning: The `value` prop supplied to <select> must be a scalar value if `multiple` is false.
```

2025-01-05 05:25 UTC, psealock commented on packages/js/settings-editor/src/utils/dataforms-transformers.tsx
> +				Edit: 'select',
Also an upstream problem, but this select does not apply the id to the element, instead using something like `inspector-select-control-1`. We could use `SelectControl` in a similar way that you've used `InputControl` in this PR. 

It will be important for input elements to have the `id` applied because the legacy forms follow this pattern. Some extensions assume this is the case for things like form manipulation or even creating their own submit button.

Alternatively we could make this contribution upstream.

2025-01-05 05:25 UTC, psealock commented on packages/js/settings-editor/src/utils/dataforms-transformers.tsx
> +} );
We'll need to add some js unit tests for these functions 😄

2025-01-10 13:22 UTC, kalessil requested changes

2025-01-10 13:22 UTC, kalessil commented on package.json
> +			"@wordpress/dataviews@4.10.0": "patches/@wordpress__dataviews@4.10.0.patch"
It looks like the new patch location needs to be updated. We keep patches under `bin/patches/` directory.

2025-01-13 08:11 UTC, chihsuan commented on package.json
> +			"@wordpress/dataviews@4.10.0": "patches/@wordpress__dataviews@4.10.0.patch"
Ah, that's right. Thanks for catching this! I just noticed that `@wordpress/dataviews@4.11.1` has been released, which includes the fix for the issue so I'll update the dependency and remove the patch.

2025-01-13 08:25 UTC, chihsuan commented
> The consistency in UI is great, but given that we will be passing in InputControl, possibly SelectControl and a few others do you think the added complexity is worthwhile?
>This example seems like a no-brainer, but I was curious if you have any further thoughts on this?


@psealock Yeah, as discussed in the meetup, I think we could contribute upstream so that we don't need to implement our custom InputControl, SelectControl, etc (though we're pausing on contributing upstream now 😅 ).

2025-01-13 08:27 UTC, chihsuan commented on packages/js/settings-editor/src/utils/dataforms-transformers.tsx
> +				Edit: 'select',
Good catch! I'll update the InputControl and add a SelectControl

2025-01-13 08:43 UTC, chihsuan commented on packages/js/settings-editor/src/utils/dataforms-transformers.tsx
> +				Edit: 'select',
Added in 7bd2444ef4968e6db4458ac587d0acfbb3df6f1f.

2025-01-13 08:44 UTC, chihsuan commented on package.json
> +			"@wordpress/dataviews@4.10.0": "patches/@wordpress__dataviews@4.10.0.patch"
Updated in fc4e1498112a92a76e51d3faf65e301ed2f011de.

2025-01-14 04:06 UTC, chihsuan commented
@psealock  I've addressed the issues you mentioned. I also added a `useSettingsForm` hook to make it easier to understand. Could you please review it again? 🙏  Thanks!

2025-01-14 07:40 UTC, kalessil commented on package.json
> +			"@wordpress/dataviews@4.10.0": "patches/@wordpress__dataviews@4.10.0.patch"
Super, thanks!

2025-01-14 07:42 UTC, kalessil approved these changes
LGTM (I reviewed only patch/deps bump part)!

2025-01-14 09:41 UTC, louwie17 commented
Just a drive by comment here :)
Nice work @chihsuan, and happy to see you got this also working with DataForm's. I see in some previous comments you mentioned around making changes upstream. Given the pause, it may be good in the mean time to surface some of your feedback either by creating an issue in Gutenberg, sharing some feedback in [this Slack channel](https://wordpress.slack.com/archives/C082S8Q9PL3), or on P2 ( internally ). 

Btw I saw the big switch statement, we currently have something similar within the DataForm package: https://github.com/WordPress/gutenberg/blob/0ceac8f5e8b74cbeb7ef36c44009c67ec5fabbf7/packages/dataviews/src/field-types/index.tsx#L15. The plan is to elaborate on this, for example your `getInputEdit` solution may be a great addition to this. We also want to create some functions around this to be able to register field types, so you don't have to explicitly these definitions through the `fields` list.

Anyhow glad to see you make it work and the more use cases the better :)

2025-01-16 19:14 UTC, psealock approved these changes
This is looking great, code looks good and tests well 🚢

2025-01-23 17:52 UTC, moon0326 approved these changes
LGTM and tested well 👍 🚀

2025-01-23 23:24 UTC, psealock commented
One thing I just noticed is when a text field has no `desc` then the label is just the id. For `text` types we should also respect `placeholder` values and figure out what to do with `desc_tip`. We could address this in a follow up or just create an issue for the backlog.

<img width="753" alt="image" src="https://github.com/user-attachments/assets/c3e82fc3-2be3-49ec-a810-c4c4fada9e03" />

2025-01-24 01:57 UTC, chihsuan commented
> One thing I just noticed is when a text field has no `desc` then the label is just the id. For `text` types we should also respect `placeholder` values and figure out what to do with `desc_tip`. We could address this in a follow up or just create an issue for the backlog.

Thanks, I'll create an issue for this.

2025-01-24 02:24 UTC, merged