Removed IN country code from get_vat_country_list
woocommerce/woocommerce pull request #54094
Opened 2024-12-31 07:43 UTC by himanshu-here

Here’s how you can structure your Pull Request (PR) submission for the proposed changes:

---

### Changes proposed in this Pull Request:

- Removed the `'IN'` country code from the `$countries` array list since India adopted GST (Goods and Services Tax) on 1 July 2017, and it is no longer applicable to include it in this context.

### How to test the changes in this Pull Request:

1. **Set up a WooCommerce instance** with the updated code.
2. **Verify the functionality** that relies on the `$countries` array to ensure it works as expected without the `'IN'` country code.
3. **Test edge cases** by ensuring no functionality breaks due to the removal of `'IN'` from the array.
4. **Check for regressions** in other parts of the codebase that might depend on this array.

### Changelog entry

- [x] Automatically create a changelog entry from the details below.

<details>

<summary>Changelog Entry Details</summary>

#### Significance

- [x] Patch

#### Type

- [x] Fix - Fixes an existing bug

#### Message

Removed `'IN'` country code from the `$countries` array as India adopted GST on 1 July 2017.

</details>

---

### Updated Code:

```php
$countries = array( 'AE', 'AL', 'AR', 'AZ', 'BB', 'BH', 'BO', 'BS', 'BY', 'CL', 'CO', 'EC', 'EG', 'ET', 'FJ', 'GH', 'GM', 'GT', 'IL', 'IR', 'KN', 'KR', 'KZ', 'LK', 'MD', 'ME', 'MK', 'MN', 'MU', 'MX', 'NA', 'NG', 'NP', 'PS', 'PY', 'RS', 'RU', 'RW', 'SA', 'SV', 'TH', 'TR', 'UA', 'UY', 'UZ', 'VE', 'VN', 'ZA' );
```

---

### Explanation:

- **Why the change?** India implemented GST on 1 July 2017, making the inclusion of `'IN'` in this array unnecessary or incorrect for the context in which this array is used.
- **Impact:** This change ensures the array reflects the correct list of countries relevant to the functionality it supports.

---

This PR follows the WooCommerce Contributing Guidelines and WordPress Coding Standards. It has been tested for security best practices and does not conflict with any other open PRs.

2024-12-31 15:39 UTC, jorgeatorres commented
Hi @himanshu-here!

Thanks for your contribution! Under normal circumstances, taxes are listed by their respective name, and "VAT" or "tax" is only used in certain locations when there's not enough space to list all the taxes that apply and particularly on sites where the tax display settings are inconsistent.

Removing India from this list of countries just means that in those particular locations, instead of "10.0 (excl. VAT)" sites will display "12.5 (incl. tax)" for example.

Is the intention of this PR to change the term VAT to the more generic "tax" in those locations? If so, could you fill out the testing instructions above with the relevant details so that it's clear what to look for while testing?

2024-12-31 15:39 UTC, jorgeatorres requested changes
Hi @himanshu-here!

Thanks for your contribution! Under normal circumstances, taxes are listed by their respective name, and "VAT" or "tax" is only used in certain locations when there's not enough space to list all the taxes that apply and particularly on sites where the tax display settings are inconsistent.

Removing India from this list of countries just means that in those particular locations, instead of "10.0 (excl. VAT)" sites will display "12.5 (incl. tax)" for example.

Is the intention of this PR to change the term VAT to the more generic "tax" in those locations? If so, could you fill out the testing instructions above with the relevant details so that it's clear what to look for while testing?

2025-01-02 06:39 UTC, himanshu-here commented
Hello @jorgeatorres 

Thank you for taking the time to review and focus on our PR request.

To assist in reproducing the issue, please follow the steps outlined below:

  1. Navigate to WooCommerce → Settings → Tax.
  2. Set the tax option to Inclusive and configure the display tax totals as a Single Total.
  3. Proceed to the Shop Page and create an order.
  4. On the Thank You page, you will notice that VAT is displayed instead of TAX.

This is incorrect, as India has adopted GST in place of VAT, and the display should reflect this change accordingly.
For further clarity, we have attached a detailed video demonstrating the issue:

Video Link: https://webkul.chatwhizz.com/share/view-recording/67763246f2e9336a27ccce08

Please take a look at the video and let us know if you need any more information or help.

Thank you for your attention to this matter.

2025-01-09 14:33 UTC, himanshu-here commented
Can you please suggest what this issue actually is? we just change in single class-wc-countries.php file for merge, Thanks

2025-01-13 12:59 UTC, jorgeatorres requested changes
Hi @himanshu-here!

Thank you for your patience and apologies for the delay. We had less coverage during the holidays, but we're back.
Changes look good to me, but there's a unit test that is now failing (due to the removal of India from the list of VAT countries). You can see the output here: https://github.com/woocommerce/woocommerce/actions/runs/12593659126/job/35372195281?pr=54094#step:9:143.

Would you be able to make the adjustments to this unit test too?

2025-01-13 13:13 UTC, himanshu-here commented
Dear @jorgeatorres,  

Thank you for taking the time to review and provide your valuable feedback on our PR request.  

I have updated the test case as discussed, and it should now align with the required specifications. Additionally, I have made the necessary updates to the code as outlined below:  

**Updated Code:**  
```php  
$this->assertCount(79, $countries->get_vat_countries());  
```  

This change ensures that the test case accurately verifies the count of VAT countries returned by the `get_vat_countries()` method.  

Kindly review the updated PR at your earliest convenience. The test case should no longer fail, and I am confident it meets the expected standards.  

Please let me know if there are any additional adjustments needed. I appreciate your support and guidance throughout this process.  

Best regards,

2025-01-13 13:52 UTC, jorgeatorres approved these changes
LGTM. Thank you @himanshu-here!

2025-01-13 13:52 UTC, merged

2025-01-13 14:50 UTC, himanshu-here commented
Dear @jorgeatorres,

Thank you for merging my PR! I truly appreciate the opportunity to contribute to this project and am grateful for your guidance and support throughout the process. Collaborating with the team has been a rewarding experience, and I’m excited to continue contributing and learning in the future. Looking forward to more opportunities to work together!

Best regards,
Himanshu Kumar